#include <bits/stdc++.h>
using namespace std;
struct M {int f,i,t,j,n;};
struct S {array<vector<int>,8> c; array<int,4> x={-1,-1,-1,-1}; array<int,4> h={0,0,0,0};};
int r(int c){return c%13+1;} int suit(int c){return c/13;} bool fit(int a,int b){return r(a)==r(b)+1&&(suit(a)%2)!=(suit(b)%2);}
string key(S const&s){vector<string> cs;for(auto&a:s.c){string v;for(int b:a)v+=char(b+1);cs.push_back(v);}sort(cs.begin(),cs.end());string k;for(auto&a:cs){k+=a;k+=char(60);}auto x=s.x;sort(x.begin(),x.end());for(int a:x)k+=char(a+1);for(int a:s.h)k+=char(a+1);return k;}
void apply(S&s,M m){vector<int>v;if(m.f==0){auto&a=s.c[m.i];v.assign(a.end()-m.n,a.end());a.resize(a.size()-m.n);}else{v.push_back(s.x[m.i]);s.x[m.i]=-1;}if(m.t==0)s.c[m.j].insert(s.c[m.j].end(),v.begin(),v.end());else if(m.t==1)s.x[m.j]=v[0];else s.h[m.j]++;}
void autoHome(S&s,vector<M>&ms){bool change=true;while(change){change=false;for(int f=0;f<2;f++)for(int i=0;i<(f==0?8:4);i++){int c=f==0?(s.c[i].empty()?-1:s.c[i].back()):s.x[i];if(c<0||r(c)!=s.h[suit(c)]+1)continue;int rank=r(c);bool safe=rank<=2; if(!safe){safe=true;for(int h=0;h<4;h++)if(h%2!=suit(c)%2&&s.h[h]<rank-1)safe=false;}if(safe){M m{f,i,2,suit(c),1};apply(s,m);ms.push_back(m);change=true;}}}}
int score(S const&s){int home=accumulate(s.h.begin(),s.h.end(),0),bad=0,depth=0,empty=0,used=0;for(auto&a:s.c){if(a.empty())empty++;for(int i=1;i<(int)a.size();i++)if(!fit(a[i-1],a[i]))bad++;for(int i=0;i<(int)a.size();i++)if(r(a[i])<=s.h[suit(a[i])]+2)depth+=(a.size()-1-i);}for(int c:s.x)if(c>=0)used++;return(52-home)*120+bad*12+depth*8+used*8-empty*25;}
struct Node{S s;int parent;vector<M> ms;int depth;};
vector<M> solve(S start,int limit,int seed){vector<Node> nodes;nodes.reserve(limit+100);vector<M>root;autoHome(start,root);nodes.push_back({start,-1,root,0});priority_queue<pair<int,int>,vector<pair<int,int>>,greater<pair<int,int>>>q;q.push({score(start),0});unordered_set<string>seen;seen.reserve(limit*2);seen.insert(key(start));int expansions=0;while(!q.empty()&&nodes.size()<(size_t)limit){int idx=q.top().second;q.pop();S s=nodes[idx].s;if(accumulate(s.h.begin(),s.h.end(),0)==52){vector<vector<M>> chunks;while(idx>=0){chunks.push_back(nodes[idx].ms);idx=nodes[idx].parent;}vector<M>ans;for(int z=chunks.size()-1;z>=0;z--)for(auto m:chunks[z])ans.push_back(m);return ans;}expansions++;int free=count(s.x.begin(),s.x.end(),-1),empty=0;for(auto&a:s.c)if(a.empty())empty++;vector<M>cand;for(int f=0;f<2;f++)for(int i=0;i<(f==0?8:4);i++){int top=f==0?(s.c[i].empty()?-1:s.c[i].back()):s.x[i];if(top<0)continue;if(r(top)==s.h[suit(top)]+1)cand.push_back({f,i,2,suit(top),1});int seq=1;if(f==0){auto&a=s.c[i];while(seq<(int)a.size()&&fit(a[a.size()-seq-1],a[a.size()-seq]))seq++;}bool didEmpty=false;for(int j=0;j<8;j++){if(f==0&&i==j)continue;auto&b=s.c[j];bool vacant=b.empty();if(vacant&&didEmpty)continue;if(vacant)didEmpty=true;int cap=(free+1)*(1<<(empty-(vacant?1:0)));for(int n=1;n<=min(seq,cap);n++){int c=f==0?s.c[i][s.c[i].size()-n]:top;if(vacant){if(f==0&&n==(int)s.c[i].size())continue;}else if(!fit(b.back(),c))continue;cand.push_back({f,i,0,j,n});}}
if(f==0&&free){int j=find(s.x.begin(),s.x.end(),-1)-s.x.begin();cand.push_back({f,i,1,j,1});}}
for(M m:cand){S ns=s;apply(ns,m);vector<M>ms{m};autoHome(ns,ms);string k=key(ns);if(!seen.insert(k).second)continue;int depth=nodes[idx].depth+1;int id=nodes.size();int val=score(ns)+depth/8;nodes.push_back({move(ns),idx,move(ms),depth});q.push({val,id});}}
return{};}
void printmove(M m){cout<<'['<<m.f<<','<<m.i<<','<<m.t<<','<<m.j<<','<<m.n<<']';}
int main(int argc,char**argv){int wanted=argc>1?atoi(argv[1]):50;int limit=argc>2?atoi(argv[2]):250000;cout<<"[\n";int done=0;for(int seed=1;done<wanted&&seed<20000;seed++){mt19937 rng(904271+seed);vector<int>deck(52);iota(deck.begin(),deck.end(),0);for(int k=51;k>0;k--)swap(deck[k],deck[rng()%(k+1)]);S s;for(int i=0;i<52;i++)s.c[i%8].push_back(deck[i]);auto proof=solve(s,limit,seed);if(proof.empty()){cerr<<"skip "<<seed<<endl;continue;}if(done)cout<<",\n";cout<<"{\"id\":"<<++done<<",\"seed\":"<<904271+seed<<",\"columns\":[";for(int i=0;i<8;i++){if(i)cout<<',';cout<<'[';for(int j=0;j<(int)s.c[i].size();j++){if(j)cout<<',';cout<<s.c[i][j];}cout<<']';}cout<<"],\"proof\":[";for(int i=0;i<(int)proof.size();i++){if(i)cout<<',';printmove(proof[i]);}cout<<"]}";cout.flush();cerr<<"solved "<<done<<" seed "<<seed<<" moves "<<proof.size()<<endl;}cout<<"\n]\n";}
