(function(){'use strict';
const GAME='tents',E=TentsEngine,levels=TENTS_LEVELS,key='arcade.logic.'+GAME+'.v1',$=id=>document.getElementById(id);
let index=0,records={},finished={},s,view=false,selected=-1,focusIndex=0,storageOK=true;
function empty(p){return Array(p.size*p.size).fill(0);}
function validCells(p,a){return Array.isArray(a)&&a.length===empty(p).length&&a.every((v,i)=>Number.isInteger(v)&&v>=0&&v<=2&&(!p.trees.includes(i)||v===0));}
function fresh(p){return{cells:empty(p),history:[],moves:0,hints:0};}
try{const raw=JSON.parse(localStorage.getItem(key)||'null');if(raw&&raw.version===1){index=Number.isInteger(raw.index)?Math.max(0,Math.min(49,raw.index)):0;for(let i=0;i<levels.length;i++){const r=raw.records?.[i];if(r&&validCells(levels[i],r.cells)){records[i]={cells:r.cells,history:Array.isArray(r.history)?r.history.filter(h=>h&&validCells(levels[i],h.cells)&&Number.isInteger(h.moves)&&h.moves>=0).slice(-100):[],moves:Number.isSafeInteger(r.moves)&&r.moves>=0?r.moves:0,hints:Number.isSafeInteger(r.hints)&&r.hints>=0?r.hints:0};}if(raw.finished?.[i]&&typeof raw.finished[i].assisted==='boolean')finished[i]=raw.finished[i];}}}catch(_){storageOK=false;}
function save(){records[index]=s;try{localStorage.setItem(key,JSON.stringify({version:1,index,records,finished}));}catch(_){storageOK=false;}$('saveNotice').textContent=storageOK?'進度自動儲存於目前瀏覽器。':'此瀏覽器目前無法儲存進度；本頁仍可正常遊玩。';}
function status(text){$('status').textContent=text;}
function selectLevel(i){if(s)save();index=Math.max(0,Math.min(49,i));s=records[index]||fresh(levels[index]);view=false;selected=-1;focusIndex=0;closeDialog($('winDialog'));render();save();status('點空格放帳篷，再點一次標草地，第三次清空');}
function snapshot(){s.history.push({cells:s.cells.slice(),moves:s.moves,hints:s.hints});if(s.history.length>100)s.history.shift();}
function apply(cells,message,fromHint=false){if(view)return;const wasWon=E.inspect(levels[index],s.cells).won;snapshot();s.cells=cells;s.moves++;if(fromHint)s.hints++;render();save();if(message)status(message);const result=E.inspect(levels[index],s.cells);if(result.won&&!wasWon){const prev=finished[index],record={assisted:s.hints>0,moves:s.moves};if(!prev||prev.assisted&&!record.assisted)finished[index]=record;save();render();$('winText').textContent='第 '+(index+1)+' 關，以 '+s.moves+' 步完成'+(s.hints?'（使用 '+s.hints+' 次提示）':'，全程獨立解出')+'。'+(index===49?'五段旅程的最後一關也完成了！':'下一片風景正等著你。');$('winNext').textContent=index===49?'回到第一關 →':'前往下一關 →';status('完成！'+(s.hints?'這次使用了提示':'這次是獨立完成'));openDialog($('winDialog'));}}
function undo(){if(view||!s.history.length)return;const h=s.history.pop();s.cells=h.cells;s.moves=h.moves;s.hints=Math.max(s.hints,h.hints||0);selected=-1;render();save();status('已撤銷上一步；提示使用紀錄保留');}
function reset(){if(view){view=false;render();}snapshot();s.cells=empty(levels[index]);s.moves=0;s.hints=0;selected=-1;render();save();status('已清空本關；完成紀錄保留，可以撤銷這次重來');}
function hint(){if(view)return;const p=levels[index],sol=new Set(p.solution);let k=s.cells.findIndex((v,i)=>v===1&&!sol.has(i));if(k>=0){const a=s.cells.slice();a[k]=2;apply(a,'提示：第 '+(Math.floor(k/p.size)+1)+' 行第 '+(k%p.size+1)+' 列不放帳篷，已修正這一格',true);return;}k=p.solution.find(i=>s.cells[i]!==1);if(k===undefined){status('所有帳篷已正確完成');return;}const a=s.cells.slice();a[k]=1;apply(a,'提示：第 '+(Math.floor(k/p.size)+1)+' 行第 '+(k%p.size+1)+' 列應放帳篷',true);}
function toggleSolution(){view=!view;selected=-1;render();status(view?'解答檢視中 · 不會覆蓋棋盤或計入通關':'已回到原本的棋盤');}
function render(){const p=levels[index],a=view?answerCells(p):s.cells,info=E.inspect(p,a),done=Object.keys(finished).length;$('levelName').textContent=String(index+1).padStart(2,'0')+' / '+p.name;$('tier').textContent=['入門','初階','中階','進階','大師'][p.tier-1]+' · '+p.size+'×'+p.size;$('moves').textContent=s.moves;$('completed').textContent=done+' / 50';$('progress').textContent='已完成 '+done+' / 50';$('level').value=String(index);$('prev').disabled=index===0;$('next').disabled=index===49;$('undo').disabled=view||!s.history.length;$('hint').disabled=view||E.inspect(p,s.cells).won;$('solution').textContent=view?'回到棋盤':'查看解答';$('solution').setAttribute('aria-pressed',String(view));
for(let i=0;i<50;i++)$('level').options[i].textContent=String(i+1).padStart(2,'0')+' · '+['入門','初階','中階','進階','大師'][levels[i].tier-1]+(finished[i]?(finished[i].assisted?' ✓ 輔助':' ✓'): '');renderBoard(p,a,info);if(view){const ribbon=document.createElement('div');ribbon.className='solution-ribbon';ribbon.textContent='解答檢視 · 不計入通關';$('board').appendChild(ribbon);}else status(info.reason);}
function openDialog(d){if(!d.open)d.showModal();}function closeDialog(d){if(d.open)d.close();}
function fit(){const r=$('zone').getBoundingClientRect(),size=Math.max(200,Math.floor(Math.min(r.width,r.height||r.width)));$('board').style.setProperty('--board-size',size+'px');}

function answerCells(p){const a=empty(p);p.solution.forEach(i=>a[i]=1);return a;}
function changeCell(i,value){if(view||levels[index].trees.includes(i))return;const a=s.cells.slice();a[i]=value;apply(a);}
function renderBoard(p,a,info){const board=$('board'),active=document.activeElement?.dataset?.cell;board.replaceChildren();const n=p.size,trees=new Set(p.trees);board.style.gridTemplateColumns='0.7fr repeat('+n+',1fr)';board.style.gridTemplateRows='0.7fr repeat('+n+',1fr)';board.setAttribute('role','group');const treeArt='<svg class="tree-art" viewBox="0 0 40 44" aria-hidden="true"><path d="M18 32h5v10h-5z" fill="#ae9767"/><path d="m20 1 12 17h-7l11 14H5l11-14H9z" fill="#a1c28a"/><path d="m20 5 1 25H8l10-13h-5z" fill="#82ae75"/></svg>',tentArt='<svg class="tent-art" viewBox="0 0 48 40" aria-hidden="true"><path d="M24 4 46 36H2z" fill="#efd79b"/><path d="m24 4 22 32H27z" fill="#c8a967"/><path d="m24 15 10 21H14z" fill="#304334"/><path d="M2 37h44" stroke="#d5be86" stroke-width="2" stroke-linecap="round"/></svg>';
function count(text,cls,label){const d=document.createElement('div');d.className='count '+cls;d.textContent=text;if(label)d.setAttribute('aria-label',label);board.appendChild(d);}
count('↘','corner');for(let c=0;c<n;c++)count(p.cols[c],info.cols[c]===p.cols[c]?'done':info.cols[c]>p.cols[c]?'over':'','第 '+(c+1)+' 列需 '+p.cols[c]+' 頂，目前 '+info.cols[c]+' 頂');
for(let r=0;r<n;r++){count(p.rows[r],info.rows[r]===p.rows[r]?'done':info.rows[r]>p.rows[r]?'over':'','第 '+(r+1)+' 行需 '+p.rows[r]+' 頂，目前 '+info.rows[r]+' 頂');for(let c=0;c<n;c++){const i=r*n+c,b=document.createElement('button');b.type='button';b.className='cell '+(trees.has(i)?'tree':a[i]===1?'tent':a[i]===2?'grass':'')+(info.bad.has(i)?' bad':'');b.dataset.cell=String(i);if(trees.has(i))b.innerHTML=treeArt;else if(a[i]===1)b.innerHTML=tentArt;else b.textContent=a[i]===2?'·':'';b.setAttribute('aria-label','第 '+(r+1)+' 行第 '+(c+1)+' 列，'+(trees.has(i)?'樹':a[i]===1?'帳篷':a[i]===2?'草地標記':'空白'));b.setAttribute('aria-disabled',String(view||trees.has(i)));b.tabIndex=i===focusIndex?0:-1;b.onclick=()=>{focusIndex=i;changeCell(i,(s.cells[i]+1)%3);board.querySelector('[data-cell="'+i+'"]')?.focus();};b.onfocus=()=>{focusIndex=i;};b.onkeydown=e=>{const dirs={ArrowLeft:[0,-1],ArrowRight:[0,1],ArrowUp:[-1,0],ArrowDown:[1,0]};if(dirs[e.key]){e.preventDefault();const [dy,dx]=dirs[e.key],rr=Math.max(0,Math.min(n-1,r+dy)),cc=Math.max(0,Math.min(n-1,c+dx));focusIndex=rr*n+cc;board.querySelectorAll('[data-cell]').forEach(el=>el.tabIndex=Number(el.dataset.cell)===focusIndex?0:-1);board.querySelector('[data-cell="'+focusIndex+'"]')?.focus();}else if(['t','g','Backspace','Delete'].includes(e.key)){e.preventDefault();changeCell(i,e.key==='t'?1:e.key==='g'?2:0);}};board.appendChild(b);}}
if(active!==undefined)board.querySelector('[data-cell="'+focusIndex+'"]')?.focus();
}

levels.forEach((p,i)=>{const o=document.createElement('option');o.value=String(i);o.textContent=String(i+1);$('level').appendChild(o);});$('level').addEventListener('change',()=>selectLevel(Number($('level').value)));$('prev').onclick=()=>selectLevel(index-1);$('next').onclick=()=>selectLevel(index+1);$('undo').onclick=undo;$('reset').onclick=reset;$('hint').onclick=hint;$('solution').onclick=toggleSolution;$('help').onclick=()=>openDialog($('helpDialog'));$('helpClose').onclick=()=>closeDialog($('helpDialog'));$('winClose').onclick=()=>closeDialog($('winDialog'));$('winNext').onclick=()=>selectLevel((index+1)%50);
for(const id of ['helpDialog','winDialog'])$(id).addEventListener('click',e=>{if(e.target===$(id)){const r=$(id).getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDialog($(id));}});
document.addEventListener('keydown',e=>{if($('helpDialog').open||$('winDialog').open||/^(SELECT|INPUT|TEXTAREA)$/.test(e.target.tagName)||e.ctrlKey||e.metaKey||e.altKey)return;if(e.key.toLowerCase()==='z'){e.preventDefault();undo();}else if(e.key.toLowerCase()==='h'){e.preventDefault();hint();}});
if(typeof ResizeObserver!=='undefined')new ResizeObserver(fit).observe($('zone'));window.addEventListener('resize',fit);selectLevel(index);fit();
})();
