'use strict';const fs=require('fs'),path=require('path'),U=require('./core.js'),C=require('./challenges.js');
const ids=process.argv.slice(2).length?process.argv.slice(2):['go9','hex','ataxx','amazons','dots-and-boxes','dou-shou-qi','hnefatafl','backgammon'];
function canon(s,E,id){if(id==='backgammon')return [s.board.join(','),s.board.slice().reverse().map(x=>-x).join(',')].sort()[0];if(id==='dots-and-boxes'){const w=E.width,h=E.height,n=2*w+1,b=Array(n*n).fill(0);for(let i=0;i<s.board.length;i++){let x,y;if(i<E.EH){x=(i%w)*2+1;y=Math.floor(i/w)*2;}else{x=((i-E.EH)%(w+1))*2;y=Math.floor((i-E.EH)/(w+1))*2+1;}b[y*n+x]=s.board[i]?1:0;}s={board:b};E={width:n,height:n};}const w=E.width,h=E.height,a=[];for(let t=0;t<8;t++){if(w!==h&&t>3)continue;const b=Array(w*h).fill(0);for(let i=0;i<w*h;i++){let x=i%w,y=Math.floor(i/w),xx=x,yy=y;if(t&1)xx=w-1-xx;if(t&2)yy=h-1-yy;if(t&4)[xx,yy]=[yy,xx];b[yy*w+xx]=s.board[i];}a.push(b.join(','));if(['go9','hex','ataxx','amazons'].includes(id))a.push(b.map(x=>Math.abs(x)===1?-x:x).join(','));}return a.sort()[0];}
function save(id,levels,stats){const dir=path.join(__dirname,'..',id);fs.writeFileSync(path.join(dir,'levels.json'),JSON.stringify(levels));fs.writeFileSync(path.join(dir,'levels.js'),'globalThis.CompetitiveLevels='+JSON.stringify(levels)+';\n');fs.writeFileSync(path.join(dir,'generation-report.json'),JSON.stringify({game:id,seed:'competitive-v1-'+id,count:levels.length,semantics:'specified-position tactical objective; witness proves achievement, no claim about longer game result',canonicalUnique:stats.unique,generatedCandidates:stats.candidates,goals:[...new Set(levels.map(x=>x.goal.type))],solutions:levels.map(x=>x.solution.length)},null,2));}
for(const id of ids){const E=require('../'+id+'/engine.js'),rng=U.rng(921843+id.split('').reduce((a,c)=>a+c.charCodeAt(0),0)),levels=[],seen=new Set(),stats={candidates:0};let attempts=0;
function add(s,goal,solution,title,description,extra={}){const k=canon(s,E,id);if(seen.has(k))return false;let n=s;for(const m of solution)n=E.play(n,m);const l={id:levels.length+1,title,description,start:U.clone(s),goal,solution,proof:{kind:'legal-tactical-witness',semantics:'在指定局面及手數內達成明示目標；不宣稱整局必勝'},...extra};if(!C.goalMet(E,l,n))throw Error('Bad witness '+id);seen.add(k);levels.push(l);return true;}
if(id==='backgammon'){while(levels.length<100){const s=E.initial(),p=rng()<.5?1:-1,k=E.idx(p);s.board.fill(0);s.phase='move';s.turn=p;s.ply=0;s.off=[Math.floor(rng()*10),Math.floor(rng()*10)];for(const side of[1,-1])for(let i=s.off[E.idx(side)];i<15;i++){const j=Math.floor(rng()*6);s.board[side===1?j:23-j]+=side;}const d=[1+Math.floor(rng()*6),1+Math.floor(rng()*6)];s.dice=d[0]===d[1]?[...d,...d]:d;const seq=E.sequences(s),max=Math.max(...seq.map(x=>x.length));let lines=seq.filter(x=>x.length===max);if(max===1&&d[0]!==d[1]){const hi=Math.max(...lines.map(x=>x[0].die));lines=lines.filter(x=>x[0].die===hi);}let best=-1,witness;for(const line of lines){let n=s;for(const m of line)n=E.apply(n,m);const gain=n.off[k]-s.off[k];if(gain>best){best=gain;witness=line;}}stats.candidates++;if(best>=2)add(s,{type:'bear-off',count:best},witness,'精準收子 '+(levels.length+1),'使用本回合所有可走骰點，至少移出 '+best+' 枚棋子。必須遵守盡量用骰與高點優先。');}stats.unique=seen.size;save(id,levels,stats);console.log(id,levels.length,stats);continue;}
while(levels.length<100&&attempts++<10000){let s=E.initial(), added=0;for(let ply=0;ply<(id==='go9'?170:id==='hex'?121:id==='amazons'?90:240)&&!E.outcome(s)&&levels.length<100;ply++){let legal=E.legal(s);if(!legal.length)break;stats.candidates++;let best=-Infinity,witness=null,goal=null,title='',desc='';const opponent=-s.turn;
if(id==='go9'&&ply>14){for(const m of legal)if(m.to!==undefined){const r=E.raw(s,m.to);if(r.enemy.length>best){best=r.enemy.length;witness=m;}}if(best>=1){goal={type:'capture-go',count:best};title='收氣提子';desc='落下一子，立即提走至少 '+best+' 枚對方棋子。';}}
if(id==='hex'&&ply>50){for(const m of legal){const n=E.apply(s,m);if(E.connected(n,s.turn)){witness=m;break;}}if(witness){goal={type:'connect'};title='連通終點';desc='下一手連通己方兩條目標邊，贏得本局。';}}
if(id==='ataxx'&&ply>6){const before=s.board.filter(x=>x===s.turn).length;for(const m of legal){const n=E.apply(s,m),gain=n.board.filter(x=>x===s.turn).length-before;if(gain>best){best=gain;witness=m;}}if(best>=3){goal={type:'gain',count:best};title='增殖與轉化';desc='一步令己方棋子總數增加至少 '+best+' 枚（包含增殖與感染）。';}}
if(id==='dots-and-boxes'&&ply>8){for(const m of legal){const n=E.apply(s,m),gain=n.boxes.filter(x=>x===s.turn).length-s.boxes.filter(x=>x===s.turn).length;if(gain>best){best=gain;witness=m;}}if(best>=1){goal={type:'boxes',count:best};title=best>1?'一線雙收':'封閉方格';desc='畫一條線，立即取得至少 '+best+' 個方格。';}}
if(id==='dou-shou-qi'&&ply>8){for(const m of legal)if(s.board[m.to]&&Math.abs(s.board[m.to])>best){best=Math.abs(s.board[m.to]);witness=m;}if(witness){goal={type:'capture-rank',rank:best};title='獸群攻防';desc='下一手吃掉階級至少 '+best+' 的對方動物（鼠1、貓2、狗3、狼4、豹5、虎6、獅7、象8）。';}}
if(id==='hnefatafl'&&ply>12){for(const m of legal){const n=E.apply(s,m),gain=s.board.filter(x=>Math.sign(x)===opponent).length-n.board.filter(x=>Math.sign(x)===opponent).length;if(gain>best){best=gain;witness=m;}}if(best>=1){goal={type:'capture-tafl',count:best};title='夾擊包圍';desc='下一手夾擊並移除至少 '+best+' 枚對方棋子。';}}
if(id==='amazons'&&ply>20&&ply%2===0){const before=E.mobility(s,opponent);let samples=legal;if(legal.length>700)samples=legal.filter((m,i)=>i%Math.ceil(legal.length/700)===0);for(const m of samples){const n=E.apply(s,m),mob=E.mobility(n,opponent);if(before-mob>best){best=before-mob;witness=m;}}if(best>=5){goal={type:'mobility',maximum:before-best};title='封鎖射線';desc='移動皇后並射箭，把對方「皇后可移動落點總數」由 '+before+' 降到 '+(before-best)+' 或更少。各皇后分別計數；不是整局必勝題。';}}
if(goal&&added<3&&add(s,goal,[witness],title+' '+(levels.length+1),desc))added++;
// Seeded legal random walk; favor contact without taking only the puzzle witness.
let candidates=legal.filter(m=>m.type!=='pass'&&m.type!=='swap');if(!candidates.length)candidates=legal;
let chosen=candidates[Math.floor(rng()*candidates.length)];if(id==='go9'&&ply>70&&rng()<.25){const active=candidates.filter(m=>m.to!==undefined&&U.neighbors(m.to,9).some(j=>s.board[j]===-s.turn));if(active.length)chosen=active[Math.floor(rng()*active.length)];}
if(id==='dou-shou-qi'&&rng()<.45){const target=s.turn===1?0:8,forward=candidates.filter(m=>Math.abs(Math.floor(m.to/7)-target)<Math.abs(Math.floor(m.from/7)-target));if(forward.length)chosen=forward[Math.floor(rng()*forward.length)];}
s=E.apply(s,chosen);if(added>=3)break;
}if(attempts%100===0)console.log('progress',id,levels.length,attempts);}
if(levels.length!==100)throw Error('Insufficient '+id+':'+levels.length);stats.unique=seen.size;save(id,levels,stats);console.log(id,levels.length,stats);}
