/* No network or dependencies. All hints are derived from the current board. */
(function(){'use strict';
const E=window.Sokoban,levels=window.SOKOBAN_LEVELS,$=id=>document.getElementById(id),session=new window.SokobanSession(levels[0]);
const SAVE='arcade.sokoban.progress.v1',RECORDS='arcade.sokoban.records.v1',ARROWS={U:'↑',D:'↓',L:'←',R:'→'},NAMES={U:'上',D:'下',L:'左',R:'右'};
let records={},timer=null,request=0,busy=false,hintCell=-1,prepared='',preparedKey='',pointer=null,storageOK=true;
function read(key,fallback){try{const text=localStorage.getItem(key);if(text&&text.length>300000)return fallback;return text?JSON.parse(text):fallback}catch(e){return fallback}}
function save(){try{localStorage.setItem(SAVE,JSON.stringify(session.serialize()));localStorage.setItem(RECORDS,JSON.stringify(records));storageOK=true}catch(e){storageOK=false}$('saveStatus').textContent=storageOK?'進度自動儲存在此瀏覽器':'瀏覽器無法儲存；本次仍可正常遊玩'}
function sanitizeRecords(raw){const out={};if(!raw||typeof raw!=='object')return out;for(let i=1;i<=50;i++){const r=raw[i];if(r&&Number.isInteger(r.moves)&&Number.isInteger(r.pushes)&&r.pushes>0&&r.moves>=r.pushes&&r.moves<25000)out[i]={moves:r.moves,pushes:r.pushes,assisted:r.assisted===true}}return out}
function tell(text,warning=false){$('status').textContent=text;$('status').classList.toggle('warning',warning)}
function stop(){request++;busy=false;if(timer!==null){clearInterval(timer);timer=null}$('play').textContent='▶ 示範';$('play').classList.remove('active');$('hint').disabled=false;$('solution').disabled=false}
function options(){const chosen=session.level.id;$('level').replaceChildren();for(const l of levels){const opt=document.createElement('option');opt.value=l.id;opt.textContent=`${records[l.id]?'✓ ':''}${String(l.id).padStart(2,'0')} · ${l.name}`;$('level').append(opt)}$('level').value=String(chosen);$('progress').textContent=`${Object.keys(records).length} / 50 已完成`}
function draw(){const b=session.board,s=session.state;$('board').replaceChildren();$('board').style.setProperty('--cols',b.w);$('board').style.setProperty('--rows',b.h);
$('board').style.setProperty('--ratio',String(b.w/b.h));
for(let p=0;p<b.w*b.h;p++){const cell=document.createElement('div');cell.className='cell'+(b.walls.has(p)?' wall':'')+(b.goals.has(p)?' goal':'')+(p===hintCell?' hinted':'');let label=b.walls.has(p)?'牆':b.goals.has(p)?'目標':'空地';if(s.boxes.includes(p)){const token=document.createElement('span');token.className='token crate'+(b.goals.has(p)?' placed':'');cell.append(token);label=b.goals.has(p)?'箱子已到位':'箱子'}if(s.player===p){const token=document.createElement('span');token.className='token worker';cell.append(token);label='你'+(b.goals.has(p)?'，站在目標':'')}cell.setAttribute('aria-label',`${Math.floor(p/b.w)+1} 列 ${p%b.w+1} 欄：${label}`);$('board').append(cell)}
$('moves').textContent=s.moves;$('pushes').textContent=s.pushes;$('undo').disabled=session.history.length<2;$('prev').disabled=session.level.id===1;$('next').disabled=session.level.id===50;$('levelNumber').textContent=String(session.level.id).padStart(2,'0');$('levelTitle').textContent=session.level.name;$('tier').textContent=['入門 · 1 箱','進階 · 2 箱','挑戰 · 3 箱','專家 · 4 箱'][session.level.stage-1];$('reference').textContent=`參考解答：${session.level.solutionMoves} 步 / ${session.level.solutionPushes} 推`;const best=records[session.level.id];$('best').textContent=best?`${best.pushes} 推 / ${best.moves} 步${best.assisted?' · 輔助':''}`:'—';
const won=E.won(b,s);$('win').hidden=!won;if(won){stop();if(!session.demo){const old=records[session.level.id];if(!old||s.pushes<old.pushes||s.pushes===old.pushes&&s.moves<old.moves)records[session.level.id]={pushes:s.pushes,moves:s.moves,assisted:session.assisted};options();$('best').textContent=`${records[session.level.id].pushes} 推 / ${records[session.level.id].moves} 步${records[session.level.id].assisted?' · 輔助':''}`} $('winText').textContent=`${s.moves} 步移動 · ${s.pushes} 次推箱${session.demo?'\n示範完成，不計通關紀錄':session.assisted?'\n使用提示，一樣值得開心':'\n漂亮的倉庫調度！'}`;$('winNext').textContent=session.level.id===50?'回到第一關 →':'挑戰下一關 →';save()}}
function load(id){stop();hintCell=-1;prepared='';preparedKey='';session.reset(levels[id-1]||levels[0]);options();draw();save();tell('把每個箱子推到綠色標記上。箱子只能推，不能拉。')}
function move(d,fromDemo=false){if(!fromDemo)stop();hintCell=-1;const ok=session.move(d);if(!ok){if(!E.won(session.board,session.state))tell('這裡過不去：前方有牆、箱子，或沒有推箱空間。',true);return false}draw();save();if(!E.won(session.board,session.state)){if(E.deadlock(session.board,session.state))tell('箱子進入無法解開的死角。用「復原」回到推錯之前。',true);else tell(fromDemo?'示範中。點「停止」或操作棋盤即可暫停。':'先找好站位，再慢慢把箱子送回目標。')}return true}
function undo(){stop();hintCell=-1;if(session.undo()){draw();save();tell('已復原一步。換個方向試試。')}}
function requestSolution(callback){stop();if(E.won(session.board,session.state)){tell('這間倉庫已整理完成！');return}const known=session.knownSolution();if(known!==null){callback(known);return}const revision=session.revision,token=++request;busy=true;$('hint').disabled=true;$('solution').disabled=true;tell('正在從目前位置找路，仍可操作或復原取消。');const search=E.createSearch(session.board,E.clone(session.state),160000);function pump(){if(token!==request||revision!==session.revision)return;const result=search.tick(120);if(result.status==='searching'){setTimeout(pump,0);return}busy=false;$('hint').disabled=false;$('solution').disabled=false;if(result.status==='solved')callback(result.answer);else if(result.status==='impossible')tell('目前局面已無解。請復原幾步，或重新開始；不會套用開局的失效解答。',true);else tell('這個局面暫時找不到解答。可復原幾步再試；開局的完整解答仍可從「重來」查看。',true)}pump()}
function hint(){requestSolution(route=>{if(!route)return;session.assisted=true;hintCell=E.next(session.board,session.state.player,route[0]);draw();save();tell(`下一步：向${NAMES[route[0]]} ${ARROWS[route[0]]}。這條可行路線還有 ${route.length} 步。`)})}
function solution(){requestSolution(route=>{session.assisted=true;prepared=route;preparedKey=E.key(session.state);$('solutionSummary').textContent=`從你目前的局面出發，共 ${route.length} 步。`; $('solutionSteps').replaceChildren();for(let i=0;i<route.length;i++){const span=document.createElement('span');const small=document.createElement('small');small.textContent=i+1;span.append(small,ARROWS[route[i]]);$('solutionSteps').append(span)}save();$('solutionDialog').showModal()})}
function playback(route){stop();if(!route)return;session.demo=true;session.assisted=true;hintCell=-1;let index=0;$('play').textContent='■ 停止';$('play').classList.add('active');tell('示範中。任何手動動作都會停止；示範局不計通關紀錄。');save();timer=setInterval(()=>{if(index>=route.length){stop();return}const d=route[index++];if(!move(d,true))stop()},350)}
$('level').addEventListener('change',()=>load(Number($('level').value)));$('prev').addEventListener('click',()=>load(Math.max(1,session.level.id-1)));$('next').addEventListener('click',()=>load(Math.min(50,session.level.id+1)));$('undo').addEventListener('click',undo);$('restart').addEventListener('click',()=>{stop();if(session.route.length)$('confirmDialog').showModal();else load(session.level.id)});$('confirmRestart').addEventListener('click',()=>{$('confirmDialog').close();load(session.level.id)});$('hint').addEventListener('click',hint);$('solution').addEventListener('click',solution);$('play').addEventListener('click',()=>{if(timer!==null||busy){stop();tell('已停止示範。可以復原或繼續操作。')}else requestSolution(playback)});$('solutionPlay').addEventListener('click',()=>{$('solutionDialog').close();if(preparedKey===E.key(session.state))playback(prepared);else requestSolution(playback)});$('rulesButton').addEventListener('click',()=>{stop();$('rulesDialog').showModal()});$('winNext').addEventListener('click',()=>load(session.level.id===50?1:session.level.id+1));document.querySelectorAll('[data-close]').forEach(button=>button.addEventListener('click',()=>$(button.dataset.close).close()));document.querySelectorAll('[data-direction]').forEach(button=>button.addEventListener('click',()=>move(button.dataset.direction)));
document.addEventListener('keydown',event=>{if(document.querySelector('dialog[open]')||['INPUT','TEXTAREA','SELECT'].includes(event.target.tagName))return;const k=event.key.toLowerCase(),d={arrowup:'U',arrowdown:'D',arrowleft:'L',arrowright:'R',w:'U',s:'D',a:'L',d:'R'}[k];if(d){event.preventDefault();move(d)}else if(k==='z'){event.preventDefault();undo()}else if(k==='h'){event.preventDefault();hint()}else if(k==='r'){event.preventDefault();$('restart').click()}else if(k==='escape'){stop();tell('已停止提示搜尋或示範。')}});
$('board').addEventListener('pointerdown',event=>{pointer={x:event.clientX,y:event.clientY,id:event.pointerId};$('board').setPointerCapture?.(event.pointerId)});$('board').addEventListener('pointerup',event=>{if(!pointer||pointer.id!==event.pointerId)return;const dx=event.clientX-pointer.x,dy=event.clientY-pointer.y;pointer=null;if(Math.max(Math.abs(dx),Math.abs(dy))<12)return;move(Math.abs(dx)>Math.abs(dy)?dx>0?'R':'L':dy>0?'D':'U')});$('board').addEventListener('pointercancel',()=>{pointer=null});window.addEventListener('pagehide',()=>{stop();save()});document.addEventListener('visibilitychange',()=>{if(document.hidden){stop();save()}});
records=sanitizeRecords(read(RECORDS,{}));const stored=read(SAVE,null);if(stored){try{session.restore(stored,levels);tell('已安全接續上次的倉庫進度。')}catch(e){session.reset(levels[0]);tell('舊進度無法驗證，已安全回到第 1 關。')}}options();draw();save();
window.SokobanGame={getState:()=>E.clone(session.state),getLevel:()=>session.level.id,getRoute:()=>session.route,load,move,undo,hint,solution,getRecords:()=>JSON.parse(JSON.stringify(records)),isPlaying:()=>timer!==null};
})();
