/* Minimal deterministic DOM/event harness. Executes the shipped UI scripts.
   It is not a browser renderer; browser pixel/layout QA is reported separately. */
const fs=require('fs'),vm=require('vm'),path=require('path');
class Element{constructor(tag,doc){this.tagName=tag.toUpperCase();this.doc=doc;this.children=[];this.events={};this.dataset={};this.attributes={};this.disabled=false;this.hidden=false;this.value='';this._text='';this._classes=new Set();this.style={setProperty:(k,v)=>this.style[k]=v};this.classList={add:(...xs)=>xs.forEach(x=>this._classes.add(x)),remove:(...xs)=>xs.forEach(x=>this._classes.delete(x)),contains:x=>this._classes.has(x),toggle:(x,on)=>{const b=on===undefined?!this._classes.has(x):on;b?this._classes.add(x):this._classes.delete(x);return b;}};}
set className(x){this._classes=new Set(x.split(/\s+/).filter(Boolean));}get className(){return [...this._classes].join(' ');}set innerHTML(x){this._html=x;this.children=[];this._text='';}get innerHTML(){return this._html||'';}set textContent(x){this._text=String(x);this.children=[];}get textContent(){return this._text+this.children.map(c=>c.textContent).join('');}appendChild(e){e.parentNode=this;this.children.push(e);return e;}setAttribute(k,v){this.attributes[k]=String(v);}getAttribute(k){return this.attributes[k];}addEventListener(type,fn){(this.events[type]||=[]).push(fn);}focus(){this.doc.activeElement=this;}closest(selector){return selector==='[data-cell]'&&this.dataset.cell!==undefined?this:this.parentNode?.closest(selector)||null;}dispatch(type,extra={}){if(type==='click'&&this.disabled)return;const event={type,target:this,detail:0,button:0,preventDefault(){},...extra};for(const f of this.events[type]||[])f(event);}}
function boot(folder,storage={},options={}){const html=fs.readFileSync(path.join(folder,'../'+path.basename(folder)+'.html'),'utf8'),ids={},document={events:{},activeElement:null,createElement(tag){return new Element(tag,this);},createTextNode(s){const e=new Element('text',this);e.textContent=s;return e;},getElementById(id){if(!ids[id])throw Error('Unknown element '+id);return ids[id];},addEventListener(type,fn){(this.events[type]||=[]).push(fn);},querySelectorAll(selector){return selector==='[data-mode]'?this.modes:[];},elementFromPoint(){return this.hit||null;}};
for(const m of html.matchAll(/<([a-z]+)[^>]*\bid="([^"]+)"[^>]*>/g)){ids[m[2]]=new Element(m[1],document);ids[m[2]].id=m[2];if(m[0].includes(' hidden'))ids[m[2]].hidden=true;}
document.modes=[...html.matchAll(/data-mode="([^"]+)"/g)].map(m=>{const e=new Element('button',document);e.dataset.mode=m[1];return e;});
const sandbox={document,localStorage:{getItem(k){if(options.blockStorage)throw Error('denied');return storage[k]||null;},setItem(k,v){if(options.blockStorage)throw Error('denied');storage[k]=v;}},console};sandbox.globalThis=sandbox;vm.createContext(sandbox);for(const file of ['levels.js','engine.js','app.js'])vm.runInContext(fs.readFileSync(path.join(folder,file),'utf8'),sandbox,{filename:file});
return {ids,document,storage,sandbox,click:id=>ids[id].dispatch('click'),cell:i=>ids.board.children[i].dispatch('click'),select:i=>{ids.levelSelect.value=String(i);ids.levelSelect.dispatch('change');},event:(type,extra={})=>{for(const fn of document.events[type]||[])fn({preventDefault(){},...extra});}};}
module.exports={boot,Element};
