(function(root){'use strict';
const copy=x=>JSON.parse(JSON.stringify(x));
function adjacent(a,b,n){return Number.isInteger(a)&&Number.isInteger(b)&&Math.abs(Math.floor(a/n)-Math.floor(b/n))+Math.abs(a%n-b%n)===1;}
function valid(level,paths){if(!Array.isArray(paths)||paths.length!==level.pairs.length)return false;const seen=new Set(),ends=new Map();level.pairs.forEach((p,k)=>p.forEach(i=>ends.set(i,k)));for(let k=0;k<paths.length;k++){const p=paths[k];if(!Array.isArray(p)||p.length>level.n**2)return false;if(p.length&&!level.pairs[k].includes(p[0]))return false;for(let j=0;j<p.length;j++){const v=p[j];if(!Number.isInteger(v)||v<0||v>=level.n**2||seen.has(v)||ends.has(v)&&ends.get(v)!==k)return false;if(j&&(!adjacent(v,p[j-1],level.n)||ends.has(p[j-1])&&j>1))return false;seen.add(v);}}return true;}
function won(level,paths){return valid(level,paths)&&paths.every((p,k)=>p.length>1&&level.pairs[k].includes(p[p.length-1])&&p[0]!==p[p.length-1])&&paths.reduce((s,p)=>s+p.length,0)===level.n**2;}
function empty(level){return level.pairs.map(()=>[]);}
function move(level,paths,active,cell){if(!Number.isInteger(cell)||cell<0||cell>=level.n**2)return {ok:false,message:'請選擇棋盤內的格子'};const owner=paths.findIndex(p=>p.includes(cell));const terminal=level.pairs.findIndex(p=>p.includes(cell));const out=copy(paths);
if(active>=0&&out[active].length){let path=out[active],last=path[path.length-1];if(last===cell)return {ok:false,message:'選擇相鄰的一格繼續'};if(owner===active){const at=path.indexOf(cell);out[active]=path.slice(0,at+1);return {ok:true,paths:out,active,message:'已回退到這一格'};}if(adjacent(last,cell,level.n)&&owner<0&&(terminal<0||terminal===active)&&!(path.length>1&&level.pairs[active].includes(last))){path.push(cell);return {ok:true,paths:out,active,message:terminal===active?'這一對已連接，還要填滿所有格子':'繼續連到相同數字'};}}
if(terminal>=0){out[terminal]=[cell];return {ok:true,paths:out,active:terminal,message:`正在連接 ${terminal+1} 號；點相鄰格或拖曳`};}
return {ok:false,message:owner>=0?'這格已有其他路線，不能交叉或重疊':'請由數字開始，沿上下左右相鄰格連線'};}
function hint(level,paths){for(let k=0;k<paths.length;k++){let answer=level.solution[k].slice();let p=paths[k];if(p.length&&p[0]===answer[answer.length-1])answer.reverse();if(p.some((v,i)=>answer[i]!==v))return {kind:'wrong',pair:k,cell:p.find((v,i)=>answer[i]!==v),message:`${k+1} 號路線已偏離唯一解。提示依答案比對；請先回退或重畫這條線。`};}let k=paths.findIndex((p,i)=>p.length<level.solution[i].length);if(k<0)return {kind:'done',message:'所有路線都已完成'};let answer=level.solution[k].slice();if(paths[k][0]===answer[answer.length-1])answer.reverse();const v=answer[paths[k].length];return {kind:'next',pair:k,cell:v,message:`答案比對提示：${k+1} 號下一格在第 ${Math.floor(v/level.n)+1} 列、第 ${v%level.n+1} 欄。提示不會改動棋盤。`};}
const api={copy,adjacent,valid,won,empty,move,hint};root.NL=api;if(typeof module!=='undefined')module.exports=api;
})(globalThis);
