const assert=require('assert/strict'),fs=require('fs'),path=require('path'),{boot}=require('./dom-harness.cjs'),E=require('./engine.js'),L=require('./levels.json');let checks=0;const ok=(x,m)=>{assert.ok(x,m);checks++;};
for(const l of L){ok(E.valid(l,l.solution),'valid '+l.id);ok(E.won(l,l.solution),'win '+l.id);ok(!E.won(l,E.empty(l)),'empty');const bad=E.copy(l.solution);bad[0].push(bad[0][0]);ok(!E.valid(l,bad),'duplicate');const short=E.copy(l.solution);short[0].pop();ok(!E.won(l,short),'incomplete');const wrong=E.copy(l.solution);wrong[0][1]=l.n*l.n;ok(!E.valid(l,wrong),'bounds');ok(!E.valid(l,{}),'shape');ok(!E.move(l,E.empty(l),-1,-1).ok,'invalid move');}
let storage={},ui=boot(__dirname,storage);ok(ui.ids.levelSelect.children.length===50,'50 selector');const key='logic-numberlink-v1';let actions=0;
for(let i=0;i<L.length;i++){ui.select(i);for(const p of L[i].solution)for(const v of p){ui.cell(v);actions++;}ok(ui.ids.status.classList.contains('win'),'UI win '+(i+1));ok(E.won(L[i],JSON.parse(storage[key]).boards[i]),'persist win');}
ok(Object.keys(JSON.parse(storage[key]).medals).length===50,'50 medals');const solved=storage[key];ui.click('solution');ok(ui.ids.playarea.classList.contains('viewmode'),'preview on');ui.cell(0);ui.click('check');ok(storage[key]===solved,'preview nonmutating');ui.click('solution');ok(storage[key]===solved,'preview return unchanged');ui.click('undo');ok(!E.won(L[49],JSON.parse(storage[key]).boards[49]),'undo full win');const beforeReset=storage[key];ui.click('reset');ok(!ui.ids.modal.hidden,'reset confirmation');ui.click('cancelModal');ok(storage[key]===beforeReset,'cancel preserves');ui.click('reset');ui.click('confirmModal');ok(JSON.parse(storage[key]).boards[49].every(p=>!p.length),'reset clears');ui.click('undo');ok(JSON.stringify(JSON.parse(storage[key]).boards)===JSON.stringify(JSON.parse(beforeReset).boards),'reset undo');ui=boot(__dirname,storage);ok(ui.ids.levelSelect.value==='49','current saved');ok(Object.keys(JSON.parse(storage[key]).medals).length===50,'completion saved');
// A locally legal wrong branch must be described as wrong, not extended.
let found=false;for(let i=0;i<L.length&&!found;i++){const l=L[i],ends=l.pairs.flat();for(let k=0;k<l.pairs.length&&!found;k++){const p=l.solution[k],a=p[0];for(let b=0;b<l.n*l.n;b++){if(!E.adjacent(a,b,l.n)||ends.includes(b)||b===p[1])continue;ui.select(i);ui.click('reset');ui.click('confirmModal');ui.cell(a);ui.cell(b);const old=storage[key];ui.click('hint');ok(ui.ids.status.textContent.includes('偏離唯一解'),'wrong hint');ok(storage[key]===old,'hint preserves');found=true;break;}}}ok(found,'wrong fixture exists');
ui.click('help');ok(!ui.ids.modal.hidden&&ui.ids.modalBody.innerHTML.includes('全格覆蓋'),'help');ui.event('keydown',{key:'Escape'});ok(ui.ids.modal.hidden,'escape closes');ui.select(0);ok(ui.ids.prev.disabled,'first prev disabled');ui.select(49);ok(ui.ids.next.disabled,'last next disabled');
// Direct drag/touch events execute the real UI event handlers.
ui.select(0);ui.click('reset');ui.click('confirmModal');let p=L[0].solution[0];ui.ids.board.children[p[0]].dispatch('pointerdown',{pointerType:'touch'});ui.document.hit=ui.ids.board.children[p[1]];ui.event('pointermove',{pointerType:'touch',clientX:1,clientY:1});ui.event('pointerup');ok(JSON.parse(storage[key]).boards[0][0].length===2,'touch path move');let before=storage[key];ui.cell(L[0].n*L[0].n-1);ok(E.valid(L[0],JSON.parse(storage[key]).boards[0]),'bad input remains valid');
for(const raw of ['{broken','null',JSON.stringify({version:1,current:1000,boards:{0:[[999]]},medals:{0:[[999]]}})]){const s={[key]:raw},u=boot(__dirname,s);ok(u.ids.levelSelect.value==='0','corrupt save safe');ok(E.valid(L[0],JSON.parse(s[key]).boards[0]),'corrupt board sanitized');}const blocked=boot(__dirname,{}, {blockStorage:true});ok(blocked.ids.saveStatus.textContent.includes('無法'),'storage denial handled');
const report={game:'numberlink',levels:L.length,engineAssertions:400,totalAssertions:checks,actualUIScriptWins:50,uiCellActions:actions,flows:['all 50 wins through real click handlers','invalid inputs','undo','reset confirmation/cancel/undo','save/reload','malformed save','storage denial','wrong-state transparent hint','non-destructive answer preview','touch pointer path','keyboard-click handlers','help/escape','navigation bounds'],uiMethod:'shipped app.js evaluated with deterministic DOM/event harness; no browser pixels tested',browserLayout:'not measured by this DOM-based test'};fs.writeFileSync(path.join(__dirname,'test-report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
