(()=>{'use strict';const E=UnrulyEngine,levels=UNRULY_LEVELS,$=id=>document.getElementById(id),key='logic-unruly-v1';let index=0,states={},focus=0,onConfirm=null,storageOk=true;
try{let raw=localStorage.getItem(key),d=null;try{d=JSON.parse(raw)}catch(e){}if(d&&d.version===1&&Number.isInteger(d.current)&&d.current>=0&&d.current<levels.length){index=d.current;let records=d.records&&typeof d.records==='object'&&!Array.isArray(d.records)?d.records:{};for(let i=0;i<levels.length;i++)states[i]=E.state(levels[i],records[i])}}catch(e){storageOk=false}
const p=()=>levels[index],s=()=>states[index]||(states[index]=E.state(p(),null));function save(){try{localStorage.setItem(key,JSON.stringify({version:1,current:index,records:states}))}catch(e){storageOk=false}}function say(t){$('message').textContent=t;$('message').className='message'}
function drawBoard(el,level,marks,interactive){let info=E.inspect(level,marks),n=level.size;el.innerHTML='';el.style.gridTemplateColumns=`repeat(${n},minmax(0,1fr))`;el.style.width=`min(100%, ${n*(interactive?44:32)}px)`;for(let i=0;i<n*n;i++){let b=document.createElement(interactive?'button':'span'),r=Math.floor(i/n),c=i%n,v=marks[i];b.className='cell '+(v===1?'black':v===2?'white':'empty')+(level.clues[i]?' given':'')+(info.bad.has(i)?' conflict':'');b.setAttribute('role','gridcell');b.setAttribute('aria-label',`第 ${r+1} 列第 ${c+1} 欄，${v===1?'黑':v===2?'白':'空白'}${level.clues[i]?'，固定提示':''}`);b.textContent=level.clues[i]?'•':v?'':'·';if(interactive){b.dataset.cell=i;b.tabIndex=i===focus?0:-1;b.setAttribute('aria-readonly',level.clues[i]?'true':'false');b.onclick=ev=>act(i,ev.shiftKey);b.oncontextmenu=ev=>{ev.preventDefault();act(i,true)};b.onfocus=()=>focus=i;b.onkeydown=ev=>boardKey(ev,i)}el.append(b)}return info}
function render(){let info=drawBoard($('board'),p(),s().marks,true),completed=levels.map((q,i)=>states[i]&&E.inspect(q,states[i].marks).won);$('level').innerHTML='';levels.forEach((q,i)=>{let o=document.createElement('option');o.value=i;o.textContent=`第 ${String(i+1).padStart(2,'0')} 關${completed[i]?' ✓':''}`;$('level').append(o)});$('level').value=index;$('prev').disabled=index===0;$('next').disabled=index===levels.length-1;$('variant').textContent=`${p().size} × ${p().size} · 唯一解`;$('count').textContent=`已填 ${info.filled} / ${p().size*p().size}`;$('undo').disabled=!s().history.length;let balanced=info.lines.filter(x=>x.complete).length;$('balance').textContent=`平衡行列 ${balanced} / ${p().size*2} · 每行每列各 ${p().size/2} 黑、${p().size/2} 白`;if(info.won){say('黑白剛剛好，沒有任何三連！🎉');$('message').classList.add('win')}else if(info.bad.size)say('紅框處出現三連，或某一色超過該行／列的一半。');save();$('progress').textContent=`已完成 ${completed.filter(Boolean).length} / 50 關${storageOk?'':' · 無法儲存進度'}`}
function focusCell(i){let b=$('board').querySelector(`[data-cell="${i}"]`);if(b)b.focus()}
function act(i,back=false){focus=i;if(p().clues[i]){say('小圓點是固定提示，不能更改。');return}if(E.cycle(p(),s(),i,back)){say('');render();focusCell(i)}}
function boardKey(ev,i){let n=p().size,delta={ArrowUp:-n,ArrowDown:n,ArrowLeft:-1,ArrowRight:1};if(ev.key in delta){ev.preventDefault();let j=i+delta[ev.key];if(j>=0&&j<n*n&&(!(ev.key==='ArrowLeft'||ev.key==='ArrowRight')||Math.floor(i/n)===Math.floor(j/n)))focusCell(j)}else if(ev.key===' '||ev.key==='Enter'){ev.preventDefault();act(i,ev.shiftKey)}else if(['b','B','w','W','Delete','Backspace'].includes(ev.key)){ev.preventDefault();let v=ev.key.toLowerCase()==='b'?1:ev.key.toLowerCase()==='w'?2:0;if(E.set(p(),s(),i,v)){say('');render();focusCell(i)}}}
function move(i){if(!Number.isInteger(i)||i<0||i>=levels.length)return;if($('modal').open)$('modal').close();index=i;focus=p().clues.indexOf(0);say('');render()}
function modal(title,body,confirm){$('modalTitle').textContent=title;$('modalBody').replaceChildren(body);onConfirm=confirm;$('confirm').hidden=!confirm;$('cancel').textContent=confirm?'取消':'繼續挑戰';$('modal').showModal()}
$('level').onchange=()=>move(+$('level').value);$('prev').onclick=()=>move(index-1);$('next').onclick=()=>move(index+1);$('undo').onclick=()=>{if(E.undo(p(),s())){say('已撤銷上一個動作。');render()}};$('reset').onclick=()=>{let target=index,t=document.createElement('p');t.textContent='這一關你填入的黑白格會清除，固定提示保留。';modal('重新開始這一關？',t,()=>{states[target]=E.state(levels[target],null);say('已重新開始。');render()})};$('hint').onclick=()=>{let wrong=s().marks.findIndex((v,i)=>v&&v!==p().solution[i]),i=wrong>=0?wrong:s().marks.findIndex(v=>!v);if(i<0){say('所有黑白格都正確！');return}say(`提示：唯一解的第 ${Math.floor(i/p().size)+1} 列、第 ${i%p().size+1} 欄是${p().solution[i]===1?'黑':'白'}色。棋盤未更動。`)};$('solution').onclick=()=>{let body=document.createElement('div'),t=document.createElement('p'),grid=document.createElement('div');t.textContent='唯一解預覽。查看不會改動你的填色或完成關卡。';grid.className='board preview';drawBoard(grid,p(),p().solution,false);body.append(t,grid);modal('解答 · 第 '+(index+1)+' 關',body,null)};$('cancel').onclick=()=>$('modal').close();$('confirm').onclick=()=>{let fn=onConfirm;$('modal').close();onConfirm=null;if(fn)fn()};$('modal').addEventListener('close',()=>onConfirm=null);focus=p().clues.indexOf(0);render();
})();
