(function(){'use strict';const E=window.SurvivalEngine,S=window.SurvivalSession,R=window.SurvivalRender,id=document.body.dataset.game,q=E.specs.find(x=>x.id===id),$=x=>document.getElementById(x),key='arcade-frontier-survival-v1:'+id;let session=S.create(id),timer=null,demoTrace=[],reference=null,hintText='';try{const saved=S.decode(localStorage.getItem(key),id);if(saved)session=saved;}catch(e){}const save=()=>{try{localStorage.setItem(key,S.encode(session));}catch(e){$('storage-note').textContent='瀏覽器未開放儲存，仍可正常遊玩。';}};
function stopDemo(){if(timer){clearInterval(timer);timer=null;}demoTrace=[];}
function render(){const s=session.state,n=s.level.number,legal=E.actions(s),check=E.constraints(s);$('level').value=String(n);$('difficulty').value=s.difficulty;$('scene').innerHTML=R.svg(s);$('forecast').textContent=R.forecastText(s);$('full-forecast').textContent=s.level.stages.map((f,i)=>`第${i+1}輪：${R.forecastText({...s,stage:i})}`).join('。 ');$('resources').textContent=R.resources(s);$('state-summary').textContent=R.stateText(s);$('round').textContent=`第 ${Math.min(4,s.stage+1)} / 4 輪 · 操作 ${s.turn} · ${session.mode==='manual'?'手動':session.mode==='hint'?'提示輔助':'示範參考'}`;$('issues').textContent=s.status==='won'?'基地已完成四輪任務！':s.status==='lost'?s.last:check.ready?'安全條件齊備，可以推進。':check.issues.join('；');$('issues').className='issues '+(check.ready?'success':'');$('status').textContent=session.paused?'已暫停。所有操作和示範都停止。':s.last;$('pause').textContent=session.paused?'繼續 P':'暫停 P';$('board-panel').classList.toggle('paused',session.paused);let previous=$('action').value;$('action').innerHTML='';for(const a of legal){const o=document.createElement('option');o.value=a.id;o.textContent=a.label;$('action').appendChild(o);}if(legal.some(a=>a.id===previous))$('action').value=previous;$('perform').disabled=session.paused||s.status!=='playing';$('action').disabled=session.paused||s.status!=='playing';$('quick').innerHTML='';for(const a of legal.filter(a=>['collect','commit','travel'].includes(a.id))){const b=document.createElement('button');b.textContent=a.label;b.className=a.id==='commit'?'primary':'';b.disabled=session.paused;b.dataset.action=a.id;b.addEventListener('click',()=>play(a.id));$('quick').appendChild(b);}$('hint-text').textContent=hintText;for(const k of ['manual','hint','demo'])$('count-'+k).textContent=session.progress[k].length;$('journal').textContent=s.log.slice(-12).map((a,i)=>`${Math.max(1,s.log.length-11)+i}. ${a}`).join('　');$('next').disabled=s.status!=='won'||n===100;save();}
function play(action,fromDemo=false){if(timer&&!fromDemo)return;const r=S.apply(session,action);if(r.accepted){session=r.session;render();}else if(r.reason){$('status').textContent=r.reason;}return r.accepted;}
function pause(){session={...session,paused:!session.paused};render();}
function reset(number=session.state.level.number,difficulty=session.state.difficulty){stopDemo();session=S.reset(session,number,difficulty);hintText='';reference=null;render();}
for(let n=1;n<=100;n++){const o=document.createElement('option');o.value=String(n);o.textContent=`第 ${String(n).padStart(3,'0')} 關`;$('level').appendChild(o);}
$('level').addEventListener('change',e=>reset(Number(e.target.value)));$('difficulty').addEventListener('change',e=>reset(session.state.level.number,e.target.value));$('perform').addEventListener('click',()=>play($('action').value));$('restart').addEventListener('click',()=>reset());$('pause').addEventListener('click',pause);$('next').addEventListener('click',()=>reset(Math.min(100,session.state.level.number+1)));
$('hint').addEventListener('click',()=>{if(session.paused||session.state.status!=='playing'||timer)return;session=S.assist(session,'hint');const a=E.advise(session.state,$('coach').value);hintText=a?`建議：${a.label}。${a.explanation}`:'目前沒有安全建議，請重看條件或重新規劃。';if(a){$('action').value=a.action;}render();if(a)$('action').value=a.action;});
$('solution').addEventListener('click',()=>{if(session.paused||timer)return;session=S.assist(session,'hint');const trace=E.witness(session.state.level);reference=E.create(session.state.level,session.state.difficulty);const entries=[];for(let i=0;i<trace.length;i++){const a=E.actions(reference).find(a=>a.id===trace[i]);entries.push(`${i+1}. ${a.label}`);reference=E.step(reference,trace[i]).state;}$('solution-steps').textContent=entries.join(' → ');$('solution-details').open=true;hintText='這是一條從關卡起點出發的可行路線，其他符合條件的基地配置也接受。看過路線後本局記為提示輔助。';render();});
$('demo').addEventListener('click',()=>{stopDemo();session=S.assist(S.reset(session),'demo');demoTrace=E.witness(session.state.level);hintText='示範逐步使用和玩家完全相同的動作。可暫停查看；重開可開始新的手動挑戰。';render();timer=setInterval(()=>{if(session.paused)return;if(!demoTrace.length||session.state.status!=='playing'){stopDemo();render();return;}const a=demoTrace.shift();play(a,true);},650);});
$('stop-demo').addEventListener('click',()=>{stopDemo();hintText='示範已停止，接著操作仍記為示範參考。重開可開始手動挑戰。';render();});
document.addEventListener('keydown',e=>{if(e.repeat||e.ctrlKey||e.metaKey||e.altKey)return;const tag=e.target&&e.target.tagName;if(['INPUT','SELECT','TEXTAREA','BUTTON'].includes(tag))return;if(e.key.toLowerCase()==='p'){e.preventDefault();pause();}if(e.key.toLowerCase()==='r'){e.preventDefault();reset();}if(e.key==='Enter'){e.preventDefault();play($('action').value);}});window.addEventListener('blur',()=>{if(session.state.status==='playing'){session={...session,paused:true};render();}});document.addEventListener('visibilitychange',()=>{if(document.hidden&&session.state.status==='playing'){session={...session,paused:true};render();}});window.addEventListener('pagehide',save);window.SurvivalUI={getSession:()=>E.copy(session),selectAction:action=>{$('action').value=action;},perform:()=>play($('action').value),pause,reset,render};render();})();
