#!/usr/bin/env node
'use strict';
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
process.chdir(__dirname);
require('./verify-static.cjs');
const source=fs.readFileSync('app.js','utf8'), registry=vm.runInNewContext(source.slice(0,source.indexOf('let activeCategory'))+';({games,categoryNames,artMarkup,GAME_BUILD})');
assert.equal(registry.games.length,70);assert.equal(new Set(registry.games.map(x=>x.id)).size,70);
for(const [category,count] of Object.entries({puzzle:4,strategy:6,casual:3,cards:5,board:10,logic:10,classic:10,collection:10,tabletop:12}))assert.equal(registry.games.filter(x=>x.category===category).length,count);
const index=fs.readFileSync('index.html','utf8');for(const asset of ['app.js','styles.css'])assert(index.includes(asset+'?v='+registry.GAME_BUILD));
assert(index.includes('70 款遊戲'));assert(index.includes('2,000 關益智'));assert(index.includes('data-filter="classic"'));assert(index.includes('data-filter="tabletop"'));assert.equal(new Set(registry.games.filter(g=>g.category==='tabletop').map(g=>registry.artMarkup[g.art])).size,12);
for(const g of registry.games){assert.equal(g.status,'ready');assert(registry.artMarkup[g.art]);assert(registry.categoryNames[g.category]);assert(/^\.\/games\/[\w\-/]+\.html$/.test(g.url));assert(fs.existsSync(g.url),g.url);const html=fs.readFileSync(g.url,'utf8');for(const m of html.matchAll(/<(?:script|link)\b[^>]*(?:src|href)=["']([^"']+)["'][^>]*>/gi)){if(/^(?:[a-z]+:|\/\/)/i.test(m[1]))continue;const file=path.resolve(path.dirname(g.url),m[1].split('?')[0]);assert(fs.existsSync(file),'Missing asset '+file);if(file.endsWith('.js'))new vm.Script(fs.readFileSync(file,'utf8'),{filename:file});}}
class Element{constructor(tag='div'){this.tagName=tag;this.children=[];this.attributes={};this.events={};this.style={setProperty(){}};this.value='';this.dataset={};}append(...x){this.children.push(...x);}replaceChildren(...x){this.children=x;}setAttribute(k,v){this.attributes[k]=v;}addEventListener(k,f){this.events[k]=f;}querySelector(){return this.span||(this.span=new Element('span'));}focus(){this.focused=true;}}
const nodes=Object.fromEntries(['#game-grid','#search','#empty','#results','#reset'].map(k=>[k,new Element()]));const filters=['all','puzzle','strategy','casual','cards','board','logic','classic','collection','tabletop'].map(k=>{const n=new Element('button');n.dataset.filter=k;return n;});
vm.runInNewContext(source,{document:{querySelector:s=>nodes[s],querySelectorAll:()=>filters,createElement:t=>new Element(t)}});assert.equal(nodes['#game-grid'].children.length,70);
for(const f of filters){f.events.click();assert.equal(f.attributes['aria-pressed'],'true');assert.equal(nodes['#game-grid'].children.length,f.dataset.filter==='all'?70:registry.games.filter(g=>g.category===f.dataset.filter).length);}
filters[0].events.click();for(const query of ['AIR TRAFFIC CONTROL','空中指揮所','XIANGQI','象棋','BANQI','暗棋','REVERSI','黑白棋','GOMOKU','五子棋','CONNECT FOUR','西洋跳棋','CHINESE CHECKERS','飛行棋','KALAH','九子棋','QUORIDOR','QUARTO','MAHJONG','麻將接龍','TANGRAM','七巧板','SAMEGAME','UNTANGLE','DOMINOSA','UNRULY','KEEN','GALAXIES','SIGNPOST','FILLOMINO','SUDOKU','數獨','MINESWEEPER','漢諾塔','猜密碼','STAR BATTLE']){nodes['#search'].value=query;nodes['#search'].events.input();assert.equal(nodes['#game-grid'].children.length,query==='數獨'?2:1,query);}
filters.find(f=>f.dataset.filter==='collection').events.click();nodes['#search'].value='KLONDIKE';nodes['#search'].events.input();assert.equal(nodes['#game-grid'].children.length,0);assert.equal(nodes['#empty'].hidden,false);nodes['#reset'].events.click();assert.equal(nodes['#game-grid'].children.length,70);assert(nodes['#search'].focused);
for(const card of nodes['#game-grid'].children){const link=card.children[1].children[3].children[1];assert.equal(link.tagName,'a');assert(link.href.endsWith('?v='+registry.GAME_BUILD));}
console.log('PASS: 70 unique lobby entries, all local assets, 10 category filters, bilingual search, empty/reset, and 70 versioned links.');
module.exports=registry;
