window.ClueUI={mount:function(){if(window.clueApp)return window.clueApp;'use strict';const E=ClueEngine,L=CLUE_LEVELS,slug=document.body.dataset.game,title=document.body.dataset.title,$=id=>document.getElementById(id),el=(t,c,text)=>{const e=document.createElement(t);if(c)e.className=c;if(text!==undefined)e.textContent=text;return e;},names=['X','Y','Z'];
const intro={logic:'用人物、職業與飲品之間的關係，完成兩張交叉配對表。',truth:'每人只有一句證詞。找出能讓所有人的身分與證詞一致的安排。',timeline:'還原離開時間，再用往返路程檢驗誰有機會到達案發現場。',cipher:'固定的一對一替換，加上完整候選字典。每一個詞都能用交叉限制解開。',family:'沿著世代、同輩與祖輩線索，接回一份失散的單線族譜。',hats:'每句「我不知道」都會排除一批可能。追蹤公開發言如何改變知識。',evidence:'把機關紀錄排成符合先後因果的事件鏈。所有合法順序都會被接受。',rule:'主動設計實驗，找出三個測量值如何決定機器的通過訊號。',map:'你站在哪裡、面向何方？把地標距離與左右前後線索對回地圖。',escape:'材料有限，操作會消耗道具。規劃組裝順序，製成開門所需的最後模組。'};
const rules={logic:'人物依表格由上到下坐在第 1 至第 N 位。「在前」代表座位編號較小；「相隔 N 位」代表兩個座位編號差 N。每種職業與飲品恰好使用一次。點格子建立配對，再點可清空。',truth:'本關明確給出誠實者人數。誠實者說的整句話為真，說謊者說的整句話為假。「或者」包含兩者皆是；「如果 A，那麼 B」只有 A 真、B 假時為假。沒有其他未公開故事設定。',timeline:'全部人物各占一個不同的離開時段。途中不必停留；案發時間那一刻抵達也算有機會。路程為固定單程時間，兩地之間沒有其他捷徑。請先填滿所有時間，再標記唯一能往返現場的人。',cipher:'密文字母與明文字母形成一對一替換。相同符號總是同一字母，不同符號不能共用一字母。候選字典是完整可能範圍，不需要英文詞義知識。公開錨點不可修改。',family:'這是單線直系家譜，不含配偶，也不聲稱記錄每人的全部生物學父母。第 2、3 代每人恰有一位緊鄰上一代；創始一代沒有上一代連線。「同一位上代」表示兩條線接到同一人。',hats:'1 表示紅帽，0 表示藍帽。每人只看得到視線圖所列的人，自己看不到自己的帽子；所有人知道紅帽總數範圍與視線圖，都會完美推理且發言真實。按發言順序更新共同可能世界。你是沒有私下視線的旁觀者，要標記每頂帽子是否已被公開資訊唯一確定，不能偷用某個人的私人視野。',evidence:'每件事件必須放一次。「A → B」表示 A 先於 B，不要求緊鄰。若有「不可相鄰」條件，兩件事中間至少隔一件。可撤回或用上下箭頭調整順序。系統檢查約束本身，不會只認一個標準答案。',rule:'機器的規則一定是：(a×X + b×Y + c×Z) 除以 m，餘數等於 r 才通過。a、b、c 為 0–10；m 為 2–11；r 為 0 至 m−1；X、Y、Z 都是 0–3。可以不限次數測試尚未測過的輸入。提交時，所有 64 組輸入必須與機器相同；等價公式也接受。',map:'每一格都可沿上下左右步行；地標所在格不能站立。距離為橫向步數 + 縱向步數。「前方投影」只算前後方向分量，「右側投影」只算左右方向分量，負數代表反方向。面向北時，前是上、右是右；轉向時一起旋轉。',escape:'所有配方都已公開；沒有藏道具、時間限制或未說明的互動。每按一次機關，就消耗列出的數量並產出右側材料。廢料壓床只銷毀材料，不會暗中給獎勵。任一能製成「出口」的合法行動序列都可通關。'};
$('intro').textContent=intro[L[0].kind];$('rules-text').textContent=rules[L[0].kind];
function btn(text,key,fn,c=''){const b=el('button','cp-button '+c,text);b.type='button';b.dataset.focus=key;b.onclick=fn;return b;}
function select(options,value,key,fn,label){const s=el('select','cp-select');s.dataset.focus=key;s.setAttribute('aria-label',label);for(const [v,t] of options){const o=el('option','',t);o.value=v;s.append(o);}s.value=value;s.onchange=()=>fn(s.value);return s;}
function section(head){const e=el('section','cp-panel');e.append(el('h3','',head));return e;}
function listClues(lines,checks){const sec=section('公開線索');const ol=el('ol','clues');lines.forEach((t,j)=>{const li=el('li',checks[j]===true?'satisfied':checks[j]===false?'conflict':'',t);if(checks[j]!==undefined)li.setAttribute('aria-label',t+(checks[j]===true?'，目前符合':checks[j]===false?'，目前不符':'，尚未填完'));ol.append(li);});sec.append(ol);return sec;}
function ref(p,a){return a[0]===0?p.people[a[1]]:a[0]===1?'「'+p.jobs[a[1]]+'」':'喝「'+p.drinks[a[1]]+'」的人';}
function logicText(p,c){const a=ref(p,c.a),b=ref(p,c.b);return c.op==='eq'?a+' 和 '+b+' 是同一人。':c.op==='ne'?a+' 不是 '+b+'。':c.op==='before'?a+' 的座位在 '+b+' 之前。':a+' 與 '+b+' 的座位編號相差 '+c.d+'。';}
function stmt(p,c){const a=p.people[c.a],b=p.people[c.b];let t={single:a+' 是誠實者',and:a+' 和 '+b+' 都是誠實者',or:a+' 或 '+b+' 至少一人是誠實者',xor:a+' 和 '+b+' 恰有一人是誠實者',same:a+' 和 '+b+' 的身分相同',implies:'如果 '+a+' 是誠實者，那麼 '+b+' 也是誠實者'}[c.op];return c.neg?'「'+t+'」這句話不成立。':t+'。';}
function clock(n){return String(9+Math.floor(n/60)).padStart(2,'0')+':'+String(n%60).padStart(2,'0');}
function familyText(p,c){return c.op==='parent'?p.people[c.a]+' 是 '+p.people[c.b]+' 的上一代。':c.op==='grand'?p.people[c.a]+' 是 '+p.people[c.b]+' 的祖輩（向上兩條連線）。':p.people[c.a]+' 和 '+p.people[c.b]+(c.op==='siblings'?' 有同一位上一代。':' 沒有同一位上一代。');}
function mapText(p,c){let n=p.landmarks[c.landmark].name,v=c.v;return c.op==='distance'?'到'+n+'的格線距離是 '+v+' 步。':c.op==='forward'?n+'的前方投影是 '+v+' 格（負值表示後方）。':c.op==='right'?n+'的右側投影是 '+v+' 格（負值表示左側）。':c.op==='frontsign'?n+(v>0?'位於你的前方半平面。':v<0?'位於你的後方半平面。':'與你在同一條左右橫線上。'):n+(v>0?'位於你的右側半平面。':v<0?'位於你的左側半平面。':'與你在同一條前後直線上。');}
function render(snap,dispatch,board){const p=snap.level,s=snap.state,active=document.activeElement?.dataset.focus;board.replaceChildren();const area=el('div','cp-layout '+p.kind),main=el('div','cp-workbench'),side=el('aside','cp-sidebar'),help=el('p','cp-detail',snap.inspection.detail);main.append(help);area.append(main,side);board.append(area);const send=a=>{if(snap.mode==='replay')return;try{if(JSON.stringify(E.applyAction(p,s,a))===JSON.stringify(s))return;}catch(_){/* controller reports the rule-specific error */}dispatch(a);};
if(p.kind==='logic'){
 for(let cat=0;cat<2;cat++){const sec=section(cat===0?'人物 × 職業':'人物 × 飲品'),wrap=el('div','table-scroll'),table=el('table','logic-table'),head=el('tr');head.append(el('th','','座位 / 人物'));const labels=cat===0?p.jobs:p.drinks;labels.forEach(t=>head.append(el('th','',t)));table.append(head);p.people.forEach((name,j)=>{const row=el('tr');row.append(el('th','',`${j+1} · ${name}`));labels.forEach((label,k)=>{const td=el('td'),on=s.grid[cat][j]===k,b=btn(on?'●':'·',`grid-${cat}-${j}-${k}`,()=>send({type:'set',category:cat,row:j,value:on?-1:k}),on?'selected':'grid-choice');b.setAttribute('aria-label',`${name} 配對 ${label}${on?'，已選取':''}`);b.setAttribute('aria-pressed',on);td.append(b);row.append(td);});table.append(row);});wrap.append(table);sec.append(wrap);main.append(sec);}side.append(listClues(p.clues.map(c=>logicText(p,c)),snap.inspection.checks));
}else if(p.kind==='truth'){
 main.append(el('div','case-banner','已知：'+p.honest+' 位誠實者，'+(p.n-p.honest)+' 位說謊者'));const grid=el('div','witness-grid');p.people.forEach((n,j)=>{const card=section(n+'的證詞');card.append(el('p','testimony',stmt(p,p.statements[j])));const bar=el('div','choice-row');[[-1,'未定'],[1,'誠實者'],[0,'說謊者']].forEach(([v,t])=>{const b=btn(t,'truth-'+j+'-'+v,()=>send({type:'set',index:j,value:v}),s.values[j]===v?'selected':'');b.setAttribute('aria-pressed',s.values[j]===v);bar.append(b);});card.append(bar);grid.append(card);});main.append(grid);side.append(listClues(['誠實者人數恰為 '+p.honest+'。','逐一驗證：每位誠實者的整句話為真。','逐一驗證：每位說謊者的整句話為假。'],[]));
}else if(p.kind==='timeline'){
 main.append(el('div','case-banner','案發時刻 '+clock(p.crime)+' · 每個離開時段只用一次'));p.people.forEach((name,j)=>{const card=section(name),line=el('div','timeline-line');const dep=s.times[j]<0?0:s.times[j]*10;const bar=el('span','timeline-bar');bar.style.left=dep/(p.crime+50)*100+'%';bar.style.width=Math.max(0,p.returns[j]-dep)/(p.crime+50)*100+'%';line.append(bar);const mark=el('span','crime-marker');mark.style.left=p.crime/(p.crime+50)*100+'%';line.append(mark);card.append(line);const row=el('div','choice-row');row.append(select([[-1,'選擇離開時間'],...Array.from({length:p.n},(_,k)=>[k,clock(k*10)])],s.times[j],'time-'+j,v=>send({type:'time',index:j,value:+v}),name+'離開時間'));row.append(el('span','',`返回 ${clock(p.returns[j])} · 單程 ${p.distances[j]} 分鐘`));card.append(row);const b=btn(s.culprit===j?'已標記：能到場':'標記為能到場的人','culprit-'+j,()=>send({type:'culprit',value:j}),s.culprit===j?'selected':'');b.setAttribute('aria-pressed',s.culprit===j);card.append(b);main.append(card);});side.append(listClues(p.clues.map(c=>c.op==='at'?p.people[c.a]+' 在 '+clock(c.v*10)+' 離開。':c.op==='before'?p.people[c.a]+' 比 '+p.people[c.b]+' 先離開。':p.people[c.a]+' 和 '+p.people[c.b]+' 的離開時間相差 '+c.d*10+' 分鐘。'),snap.inspection.checks));
}else if(p.kind==='cipher'){
 const message=section('加密便箋');p.encoded.forEach((w,j)=>{const row=el('div','cipher-word');[...w].forEach(c=>{const cell=el('span','cipher-cell');cell.append(el('small','',c),el('b','',s.mapping[c]||'·'));row.append(cell);});message.append(row);});main.append(message);const keys=section('替換字母盤'),keygrid=el('div','cipher-keys');p.symbols.forEach(k=>{const box=el('label','cipher-key',k+' → '),anchor=p.anchors.find(([a])=>a===k);const sel=select([['','?'],...p.alphabet.map(a=>[a,a])],s.mapping[k]||'','cipher-'+k,v=>send({type:'map',symbol:k,value:v}),k+' 的明文字母');sel.disabled=!!anchor;box.append(sel);if(anchor)box.append(el('small','','公開錨點'));keygrid.append(box);});keys.append(keygrid);main.append(keys);const dict=section('完整候選字典'),chips=el('div','dictionary');p.bank.forEach(w=>chips.append(el('span','word-chip',w)));dict.append(chips,el('p','small','不需要知道詞義。比較字長、重複位置，以及不同詞之間共用的字母。'));side.append(dict);
}else if(p.kind==='family'){
 const tree=el('div','family-chart');for(let g=0;g<3;g++){const col=section('第 '+(g+1)+' 代');p.people.forEach((n,j)=>{if(p.generations[j]!==g)return;const node=el('div','family-node');node.append(el('b','',n));if(g){const choices=p.people.map((name,k)=>[k,name]).filter(([k])=>p.generations[k]===g-1);node.append(el('span','small','上一代'),select([[-2,'尚未連線'],...choices],s.parents[j],'family-'+j,v=>send({type:'parent',index:j,value:+v}),n+' 的上一代'));if(s.parents[j]>=0)node.append(el('small','ancestry','← '+p.people[s.parents[j]]));}else node.append(el('small','','創始一代'));col.append(node);});tree.append(col);}main.append(tree);side.append(listClues(p.clues.map(c=>familyText(p,c)),snap.inspection.checks));
}else if(p.kind==='hats'){
 main.append(el('div','case-banner','紅帽總數可能為 '+p.totals.join('、')+' 頂；其餘為藍帽'));const grid=el('div','hat-grid');p.people.forEach((n,j)=>{const card=section(n),hat=el('div','hat '+(s.claims[j]===1?'red':s.claims[j]===0?'blue':'unknown'),s.claims[j]===-2?'?':s.claims[j]===-1?'?':s.claims[j]===1?'紅':'藍');card.append(hat,el('p','small','看得到：'+p.seen[j].map(k=>p.people[k]).join('、')));card.append(select([[-2,'尚未判定'],[1,'必為紅帽'],[0,'必為藍帽'],[-1,'仍不確定']],s.claims[j],'hat-'+j,v=>send({type:'claim',index:j,value:+v}),n+' 的公開可知帽色'));grid.append(card);});main.append(grid);side.append(listClues(p.transcript.map((t,j)=>`第 ${j+1} 次 · ${p.people[t.who]}：「`+(t.answer===-1?'我還不能確定自己的帽色。':t.answer?'我確定自己是紅帽。':'我確定自己是藍帽。')+'」'),[]));side.append(el('p','small','每人是在聽完前面的公開發言後，再根據自己的視野回答。若你選「仍不確定」，是說旁觀者仍能找到紅、藍兩種一致世界。'));
}else if(p.kind==='evidence'){
 const tray=section('尚未排入的物證');const options=el('div','event-tray');p.events.forEach((t,j)=>{if(!s.order.includes(j))options.append(btn('＋ '+t,'event-'+j,()=>send({type:'append',value:j})));});tray.append(options);main.append(tray);const chain=section('事件時間鏈');if(!s.order.length)chain.append(el('p','small','從上方挑一件事件，放入最早的位置。'));s.order.forEach((v,j)=>{const row=el('div','order-row');row.append(el('b','order-number',j+1),el('span','event-name',p.events[v]));if(j)row.append(btn('↑','up-'+j,()=>send({type:'move',index:j,to:j-1})));if(j<s.order.length-1)row.append(btn('↓','down-'+j,()=>send({type:'move',index:j,to:j+1})));row.append(btn('移回','remove-'+j,()=>send({type:'remove',index:j})));chain.append(row);});main.append(chain);side.append(listClues(p.edges.map(([a,b])=>p.events[a]+' → '+p.events[b]).concat(p.apart.map(([a,b])=>p.events[a]+' 與 '+p.events[b]+' 不可相鄰。')),snap.inspection.checks));
}else if(p.kind==='rule'){
 const lab=section('測試台'),input=el('div','dial-row');s.probe.forEach((v,j)=>{const l=el('label','dial',names[j]);l.append(select([0,1,2,3].map(x=>[x,x]),v,'probe-'+j,x=>send({type:'probe',index:j,value:+x}),names[j]+'實驗輸入'));input.append(l);});lab.append(input,btn('進行實驗','test',()=>send({type:'test'}),'primary'));main.append(lab);const build=section('建立規則');build.append(el('p','formula','(a×X + b×Y + c×Z) mod m = r'));const params=el('div','dial-row');s.weights.forEach((v,j)=>{const l=el('label','dial',['a','b','c'][j]);l.append(select(Array.from({length:11},(_,x)=>[x,x]),v,'weight-'+j,x=>send({type:'weight',index:j,value:+x}),'係數 '+['a','b','c'][j]));params.append(l);});const m=el('label','dial','除數 m');m.append(select(Array.from({length:10},(_,x)=>[x+2,x+2]),s.mod,'mod',x=>send({type:'mod',value:+x}),'除數 m'));const rem=el('label','dial','餘數 r');rem.append(select(Array.from({length:s.mod},(_,x)=>[x,x]),s.residue,'residue',x=>send({type:'residue',value:+x}),'餘數 r'));params.append(m,rem);build.append(params,btn('提交公式並驗證','submit',()=>send({type:'submit'}),'primary'));main.append(build);const notes=section('實驗紀錄'),notebook=el('div','notebook');s.experiments.forEach((e,j)=>{const row=el('div','experiment '+(e.output?'pass':'fail'));row.append(el('span','',e.input.join(' / ')),el('b','',e.output?'通過 ●':'不通過 ○'),el('small','',j<p.samples.length?'起始樣本':'你的實驗'));notebook.append(row);});notes.append(el('p','small','X / Y / Z · 共 '+s.experiments.length+' 組不同測試'),notebook);side.append(notes);
}else if(p.kind==='map'){
 const map=section('調查區域 · ↑ 北'),grid=el('div','map-grid');grid.style.setProperty('--size',p.size);for(let y=0;y<p.size;y++)for(let x=0;x<p.size;x++){const lm=p.landmarks.find(l=>l.x===x&&l.y===y),on=s.x===x&&s.y===y,b=btn(lm?lm.name:on?['↑','→','↓','←'][s.facing]||'◎':'·',`map-${x}-${y}`,()=>send({type:'position',x,y}),lm?'landmark':on?'selected observer':'map-cell');b.disabled=!!lm;b.setAttribute('aria-label',`第 ${x+1} 欄第 ${y+1} 列`+(lm?'，'+lm.name:on?'，你的所在地':''));grid.append(b);}map.append(grid);const dirs=el('div','choice-row compass');['北 ↑','東 →','南 ↓','西 ←'].forEach((t,j)=>{const b=btn(t,'facing-'+j,()=>send({type:'facing',value:j}),s.facing===j?'selected':'');b.setAttribute('aria-pressed',s.facing===j);dirs.append(b);});map.append(el('p','small','點選一格空地，再設定面向。'),dirs);main.append(map);side.append(listClues(p.clues.map(c=>mapText(p,c)),snap.inspection.checks));
}else if(p.kind==='escape'){
 const inv=section('隨身道具'),inventory=el('div','inventory');p.items.forEach((t,j)=>{if(s.inventory[j]){const item=el('div','item');item.append(el('b','',t),el('strong','',s.inventory[j]));inventory.append(item);}});inv.append(inventory);main.append(inv);const machines=section('工作台與機關');p.recipes.forEach((r,j)=>{const card=el('div','recipe'),ready=!!E.recipeApply(s.inventory,r);card.append(el('b','',r.name),el('span','recipe-flow',r.take.map(([k,v])=>p.items[k]+' ×'+v).join(' ＋ ')+' → '+(r.give.length?r.give.map(([k,v])=>p.items[k]+' ×'+v).join(' ＋ '):'永久丟棄（可撤銷）')));const b=btn('操作','recipe-'+j,()=>send({type:'recipe',index:j}),ready?'primary':'');b.disabled=!ready;card.append(b);machines.append(card);});main.append(machines);const log=section('操作紀錄');if(!s.log.length)log.append(el('p','small','先查看出口需要哪些模組，再逆推材料。'));const ol=el('ol','action-log');s.log.forEach(j=>ol.append(el('li','',p.recipes[j].name)));log.append(ol);side.append(log);
}
if(snap.hint?.action&&snap.mode==='play'){const callout=el('div','apply-hint');callout.append(btn('套用這一步提示','apply-hint',()=>send(snap.hint.action),'primary'));main.prepend(callout);}if(snap.mode==='replay'){board.querySelectorAll('button,select').forEach(b=>b.disabled=true);main.prepend(el('p','replay-note','示範盤面 · 使用上方「示範下一步」觀察解法。'));}else if(snap.inspection.goalMet){main.prepend(el('div','victory','✓ 本關推理成立，所有條件已通過驗證。'));}
if(active){const focus=[...board.querySelectorAll('[data-focus]')].find(e=>e.dataset.focus===active);if(focus&&!focus.disabled)focus.focus({preventScroll:true});}
}
const controller=ArcadeChallenge.createController({gameId:slug,revision:slug==='logic-grid'?'clue-100-v2':'clue-100-v1',levels:L,engine:E});window.clueApp={controller,engine:E,levels:L};ArcadeChallenge.mountControls($('game'),controller,{title:'100 關調查手冊',render,getReplayActions:E.solutionActions});
}};
