(function(){
'use strict';
const E=window.GameEngine,S=window.GameSession,L=window.GAME_LEVELS,$=id=>document.getElementById(id),TANGRAM=E.kind==='tangram',KEY='arcade.'+(TANGRAM?'tangram':'mahjong-solitaire')+'.v1';
let raw=null;try{raw=localStorage.getItem(KEY)}catch{}const loaded=S.load(raw,L,E);let data=loaded.data,level=L[data.index],state=E.replay(level,data.actions),preview=null,pending=null,message='',hintData=null;
function time(n){return Math.floor(n/60)+':'+String(n%60).padStart(2,'0')}
function save(){try{localStorage.setItem(KEY,JSON.stringify(data));$('save').textContent='進度保存在此瀏覽器'+(data.assisted?' · 本局使用輔助':'')}catch{$('save').textContent='目前無法儲存；仍可遊玩，關閉後進度可能遺失'}}
function blocked(){return !!preview||!!pending||$('helpDialog').open}
function normal(){return TANGRAM?'先選一片，再點剪影放下；也可以拖曳拼片':'先選一張自由牌，再選相同圖案的另一張'}
function render(){const shown=preview?preview.state:state,won=E.won(level,shown);$('remaining').textContent=TANGRAM?shown.filter(Boolean).length+' / 7':shown.filter(x=>!x).length;$('moves').textContent=data.actions.length;$('timer').textContent=time(data.seconds);$('progress').textContent=Object.keys(data.completed).length+' / 50';$('progressBar').style.width=(Object.keys(data.completed).length*2)+'%';$('boardTitle').textContent='第 '+String(data.index+1).padStart(2,'0')+' 關 · '+level.name;$('badge').textContent=preview?'解答觀摩 · 不計過關':TANGRAM?'七片標準形狀 · 合法拼法皆可':level.layers+' 層 · '+E.pairs(level,state).length+' 對可取';$('level').replaceChildren();for(let i=0;i<L.length;i++){const o=document.createElement('option');o.value=String(i);o.textContent=String(i+1).padStart(2,'0')+' · '+L[i].name+(data.completed[i]?' ✓':'');$('level').append(o)}$('level').value=String(data.index);$('levelInfo').textContent=TANGRAM?'剪影 '+level.width+' × '+level.height+' · 標準總面積 32\n旋轉、鏡射與平移去重的完整拼圖':level.tiles.length+' 張牌 · '+level.layers+' 層 · '+level.solution.length+' 對\n完整合法配對證明，初始保證可解';$('undo').disabled=!!preview||!data.actions.length;$('restart').disabled=!!preview;$('next').disabled=!!preview||data.index===49;$('level').disabled=!!preview;$('hint').disabled=!!preview||E.won(level,state);$('solution').hidden=!!preview;$('solution').disabled=E.won(level,state);for(const id of ['pause','step','stop'])$(id).hidden=!preview;$('pause').disabled=!!preview&&preview.done;$('step').disabled=!!preview&&preview.done;$('pause').textContent=preview&&preview.paused?'繼續':'暫停';$('win').hidden=!(won&&(preview?preview.done:true));if(won){$('winTitle').textContent=preview?'解答觀摩完成':TANGRAM?'七片歸位，形狀完整。':'層層鬆開，牌桌清空。';$('winDetail').textContent=preview?'沒有計入過關，原本棋局完整保留':data.actions.length+' 步 · '+time(data.seconds)+' · '+(data.assisted?'使用輔助':'自力完成')}const best=data.completed[data.index];$('best').textContent=best?'最佳：'+best.actions.length+' 步 · '+time(best.seconds)+' · '+(best.assisted?'使用輔助':'自力完成'):'最佳紀錄：尚未完成';drawBoard(shown);$('status').textContent=message;}
function action(a){if(blocked()||E.won(level,state))return false;if(!E.legal(level,state,a))return false;if(data.actions.length>=20000){message='保存步數已達上限，請復原或重新開始';render();return false}state=E.step(level,state,a);data.actions.push(JSON.parse(JSON.stringify(a)));hintData=null;afterAction();const won=S.record(data,level,E);message=won?'完成！可以復原回想，或前往下一關':normal();save();render();return true}
function ask(text,fn){if(pending)return;pending=fn;$('confirmText').textContent=text;$('confirmDialog').showModal()}
function choose(index){if(blocked()||!Number.isInteger(index)||!L[index]||index===data.index)return;const run=()=>{data=S.fresh(index,data.completed);level=L[index];state=E.initial(level);hintData=null;resetSelection();message=normal();save();render()};if(data.actions.length&&!E.won(level,state))ask('換關會清除目前尚未完成的走法；已完成紀錄會保留。',run);else run()}
$('level').addEventListener('change',()=>{const n=Number($('level').value);$('level').value=String(data.index);choose(n)});$('next').addEventListener('click',()=>choose(data.index+1));
$('restart').addEventListener('click',()=>{if(blocked())return;const run=()=>{data=S.fresh(data.index,data.completed);state=E.initial(level);hintData=null;resetSelection();message='已重新開始，慢慢想，不用急';save();render()};if(data.actions.length||data.assisted)ask('本局走法、時間與輔助標記會歸零；完成紀錄會保留。',run);else run()});
$('cancelConfirm').addEventListener('click',()=>{pending=null;$('confirmDialog').close()});$('confirmDialog').addEventListener('cancel',()=>{pending=null});$('confirmDialog').addEventListener('close',()=>{pending=null});$('acceptConfirm').addEventListener('click',()=>{const f=pending;pending=null;$('confirmDialog').close();if(f)f()});
$('undo').addEventListener('click',()=>{if(blocked()||!data.actions.length)return;data.actions.pop();state=E.replay(level,data.actions);hintData=null;resetSelection();message='已復原一步；已驗證的完成紀錄會保留';save();render()});
$('hint').addEventListener('click',()=>{if(blocked()||E.won(level,state))return;data.assisted=true;showHint();save();render()});
function schedule(){if(preview&&!preview.paused&&!preview.done)preview.timer=setTimeout(tick,700)}
function tick(){if(!preview||preview.done)return;preview.timer=null;preview.state=E.step(level,preview.state,level.solution[preview.pos]);preview.pos++;preview.done=preview.pos===level.solution.length;message=preview.done?'觀摩完成；按「返回自己的棋局」繼續原本進度':'觀摩 '+preview.pos+' / '+level.solution.length+'；原本走法與時間不變';render();schedule()}
function stopPreview(text='已返回自己的棋局，盤面、走法與時間都保留'){if(!preview)return;clearTimeout(preview.timer);preview=null;message=text;render();save()}
$('solution').addEventListener('click',()=>{if(blocked()||E.won(level,state))return;data.assisted=true;preview={state:E.initial(level),pos:0,done:false,paused:false,timer:null};message='從關卡起點觀摩完整解答；你的棋局會完整保留';save();render();schedule()});
$('pause').addEventListener('click',()=>{if(!preview||preview.done)return;preview.paused=!preview.paused;clearTimeout(preview.timer);preview.timer=null;message=preview.paused?'觀摩已暫停；可單步或返回自己的棋局':'繼續觀摩；原本進度不變';render();schedule()});$('step').addEventListener('click',()=>{if(!preview||preview.done)return;clearTimeout(preview.timer);preview.paused=true;tick()});$('stop').addEventListener('click',()=>stopPreview());
$('help').addEventListener('click',()=>{if(preview){clearTimeout(preview.timer);preview.paused=true;render()}$('helpDialog').showModal()});$('closeHelp').addEventListener('click',()=>$('helpDialog').close());
$('home').addEventListener('click',ev=>{if(preview)stopPreview();if(data.actions.length&&!E.won(level,state)){ev.preventDefault();ask('棋局已自動保存在此瀏覽器。要返回遊戲大廳嗎？',()=>{save();window.location.href=$('home').getAttribute('href')})}});
setInterval(()=>{if(!document.hidden&&!blocked()&&!E.won(level,state)){data.seconds++;$('timer').textContent=time(data.seconds);if(data.seconds%5===0)save()}},1000);document.addEventListener('visibilitychange',()=>{if(document.hidden){if(preview)stopPreview('頁面進入背景，已停止觀摩並保留原本棋局');save()}});window.addEventListener('pagehide',save);
let selected=null;
const nums=['一','二','三','四','五','六','七','八','九'],honors=['東','南','西','北','中','發','白'];
function faceName(n){return n<27?nums[n%9]+['萬','筒','索'][Math.floor(n/9)]:honors[n-27]}
function resetSelection(){selected=null}function afterAction(){selected=null}
function selectTile(i){if(blocked()||E.won(level,state))return;if(!E.free(level,state,i)){message='這張牌被上方壓住，或左右兩側都被夾住';render();return}if(selected===i){selected=null;message=normal()}else if(selected===null){selected=i;message='已選 '+faceName(level.tiles[i].face)+'，請找另一張相同的自由牌'}else if(level.tiles[selected].face===level.tiles[i].face){action([selected,i]);return}else{selected=i;message='已改選 '+faceName(level.tiles[i].face)+'；配對圖案必須完全相同'}hintData=null;render()}
function drawBoard(shown){const board=$('board'),focus=document.activeElement&&document.activeElement.dataset?document.activeElement.dataset.tile:null;board.replaceChildren();const minX=Math.min(...level.tiles.map(t=>t.x)),minY=Math.min(...level.tiles.map(t=>t.y)),maxX=Math.max(...level.tiles.map(t=>t.x+.24*t.z)),maxY=Math.max(...level.tiles.map(t=>t.y)),w=(maxX-minX)/2+1.12,h=(maxY-minY)/2+1.15+(level.layers-1)*.15,ratio=w/(h*1.24);board.style.aspectRatio=String(ratio);board.style.setProperty('--board-ratio',String(ratio));board.style.setProperty('--board-max',(Math.min(560,350*ratio))+'px');for(const t of level.tiles){if(shown[t.id])continue;const b=document.createElement('button'),available=E.free(level,shown,t.id),suit=Math.floor(t.face/9);b.className='mahjong-tile suit'+suit+(!available?' blocked':'')+(t.face>=27?' honor':'')+(!preview&&selected===t.id?' selected':'')+(!preview&&hintData&&hintData.includes(t.id)?' hinted':'');b.dataset.tile=String(t.id);b.style.left=(((t.x-minX)/2+t.z*.12)/w*100)+'%';b.style.top=(((t.y-minY)/2+(level.layers-1-t.z)*.15)/h*100)+'%';b.style.width=(.91/w*100)+'%';b.style.height=(.94/h*100)+'%';b.style.zIndex=String(t.z*100+t.id);b.setAttribute('aria-label',faceName(t.face)+'，第 '+(t.z+1)+' 層，'+(available?'自由牌':'目前被擋住'));b.setAttribute('aria-pressed',String(!preview&&selected===t.id));b.disabled=!!preview;if(t.face<27){const n=document.createElement('span'),s=document.createElement('span');n.className='face-number';n.textContent=nums[t.face%9];s.className='face-suit';s.textContent=['萬','筒','索'][suit];b.append(n,s)}else b.textContent=honors[t.face-27];b.addEventListener('click',()=>selectTile(t.id));board.append(b)}if(focus!==null){const q=board.querySelector('[data-tile="'+focus+'"]');if(q)q.focus()}}
function showHint(){selected=null;const solved=E.solve(level,state);if(solved.route&&solved.route.length){hintData=solved.route[0];message='提示：綠框的兩張 '+faceName(level.tiles[hintData[0]].face)+' 可接續完整合法解'}else if(solved.limited){hintData=E.pairs(level,state)[0]||null;message='搜尋達到上限；綠框僅代表合法配對，尚未證明此局面可通關'}else{hintData=null;message='目前局面已無完整解；請復原先前的配對，或重新開始'}}
$('board').addEventListener('keydown',ev=>{if(blocked())return;if(ev.key==='Escape'){selected=null;hintData=null;message=normal();render()}if(['ArrowRight','ArrowLeft','ArrowUp','ArrowDown'].includes(ev.key)){ev.preventDefault();const a=Array.from($('board').querySelectorAll('button')),i=a.indexOf(document.activeElement),n=(i+(ev.key==='ArrowLeft'||ev.key==='ArrowUp'?-1:1)+a.length)%a.length;if(a[n])a[n].focus()}});

S.record(data,level,E);message=loaded.bad?'部分存檔未通過合法性驗證，已安全恢復':data.actions.length?'已還原上次棋局，接著慢慢想':normal();render();save();
})();
