/* Deterministic 60 Hz duel simulation. Browser, training corpus and replay tests use this exact transition. */
(function(r,f){const a=f(typeof module==='object'?require('./definitions.js'):r.DuelDefinitions);if(typeof module==='object')module.exports=a;else r.DuelEngine=a;})(globalThis,function(D){'use strict';
const W=960,H=540,DT=1/60,R=18,clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),hyp=Math.hypot,clone=x=>JSON.parse(JSON.stringify(x));
const signed=(x)=>x>0?1:x<0?-1:0,finite=(v,d=0)=>Number.isFinite(v)?v:d;
function unit(x,y){const d=hyp(x,y);return d<1e-6?{x:1,y:0}:{x:x/d,y:y/d};}
function distance(a,b){return hyp(a.x-b.x,a.y-b.y);}
function segDist(p,a,b){const dx=b.x-a.x,dy=b.y-a.y,t=clamp(((p.x-a.x)*dx+(p.y-a.y)*dy)/(dx*dx+dy*dy||1),0,1);return hyp(p.x-a.x-t*dx,p.y-a.y-t*dy);}
function normalize(raw={}){if(Array.isArray(raw)){const m=Number.isInteger(raw[2])&&raw[2]>=0&&raw[2]<=15?raw[2]:0;raw={x:raw[0],y:raw[1],a:!!(m&1),b:!!(m&2),c:!!(m&4),d:!!(m&8)};}if(!raw||typeof raw!=='object')raw={};const x=clamp(finite(raw.x),-1,1),y=clamp(finite(raw.y),-1,1),h=hyp(x,y),n=h>1+1e-12?h:1;return{x:x/n,y:y/n,a:raw.a===true,b:raw.b===true,c:raw.c===true,d:raw.d===true};}
function pack(raw){const v=normalize(raw);return[v.x,v.y,(v.a?1:0)|(v.b?2:0)|(v.c?4:0)|(v.d?8:0)];}
function blankStats(){return{hits:0,damage:0,blocks:0,parries:0,magnetCombo:0,salvage:0,shadowHit:0,chainHit:0,cancelHit:0,recycleHit:0,breathHit:0,wallHit:0,poleHit:0,ribbonHit:0,topple:0,echoHit:0,dualHit:0,reaction:0,heightHit:0};}
function actor(x,y,id,L){return{id,x,y,vx:0,vy:0,r:R,hp:L.hp||100,stamina:100,cool:0,stun:0,attack:null,guard:false,guardTicks:0,prev:normalize(),face:{x:id?-1:1,y:0},stats:blankStats(),polarity:1,magnetTicks:0,modules:clone(id?(L.enemyModules||['blade','ram']):(L.playerModules||['blade'])),lastModule:'blade',mass:id?1.7:1.25,form:0,cancelWindow:0,blades:2,recycled:false,breath:65,burst:0,gravity:0,attached:false,air:0,wraps:0,tether:-1,balance:0,weight:1,weightFlips:0,echoPushed:0,leftCharge:0,rightCharge:0,leftCool:0,rightCool:0,lastArm:'',armChain:0,element:0,aura:-1,auraTime:0,chargeClock:0,toolCool:0,skillCool:0,spin:0,angle:id?Math.PI:0,length:90,hammer:null,hammerHit:0,reels:0,dash:0,z:0,vz:0,hitFlash:0};}
function create(id,level,options={}){const def=D.byId[id];if(!def)throw Error('Unknown duel '+id);const L=clone(level);const opt={mode:['challenge','free','local'].includes(options.mode)?options.mode:'challenge',difficulty:['easy','normal','hard'].includes(options.difficulty)?options.difficulty:'normal'};const s={version:D.VERSION,id,kind:def.kind,level:L,options:opt,tick:0,status:'playing',winner:null,message:'觀察預備線，掌握距離後出手。',players:[actor(L.start.x,L.start.y,0,L),actor(L.enemy.x,L.enemy.y,1,L)],obstacles:clone(L.obstacles||[]),shards:[],parts:[],echoes:[],projectiles:[],effects:[],lamp:{x:L.lamp?.x||300,y:L.lamp?.y||260},pole:0,heights:clone(L.heights||Array(96).fill(0)),ai:{history:[],lastDecision:-999,held:normalize(),events:[],observations:0},events:[],inputs:0,damageEvents:0};
if(opt.mode==='free'||opt.mode==='local'){s.players.forEach(p=>{p.hp=140;p.modules=['blade','ram'];p.mass=1.7;});}
if(s.kind===7)s.players.forEach(p=>{p.gravity=0;});
if(s.kind===8){s.players[0].x=400;s.players[1].x=565;s.players[0].y=s.players[1].y=270;s.obstacles=s.obstacles.filter(o=>o.x<320||o.x>640||o.y<170||o.y>365);}
return s;}
function rectClear(a,b,r){const minX=r.x-R,maxX=r.x+r.w+R,minY=r.y-R,maxY=r.y+r.h+R;let t0=0,t1=1;for(const [p,q]of[[-(b.x-a.x),a.x-minX],[b.x-a.x,maxX-a.x],[-(b.y-a.y),a.y-minY],[b.y-a.y,maxY-a.y]]){if(Math.abs(p)<1e-9){if(q<0)return true;}else{const t=q/p;if(p<0){if(t>t1)return true;t0=Math.max(t0,t);}else{if(t<t0)return true;t1=Math.min(t1,t);}}}return false;}
function clearLine(s,a,b){return !s.obstacles.some(o=>!rectClear(a,b,o));}
function nav(s,p,q){if(clearLine(s,p,q))return unit(q.x-p.x,q.y-p.y);const cols=24,rows=14,sz=40,key=(x,y)=>y*cols+x;const sx=clamp(Math.floor(p.x/sz),0,cols-1),sy=clamp(Math.floor(p.y/sz),0,rows-1),gx=clamp(Math.floor(q.x/sz),0,cols-1),gy=clamp(Math.floor(q.y/sz),0,rows-1),start=key(sx,sy),goal=key(gx,gy),parent=new Int16Array(cols*rows).fill(-2),queue=[start];parent[start]=-1;let found=-1;
for(let qi=0;qi<queue.length;qi++){const z=queue[qi],x=z%cols,y=Math.floor(z/cols);if(z===goal){found=z;break;}for(const [dx,dy]of[[1,0],[-1,0],[0,1],[0,-1]]){let nx=x+dx,ny=y+dy,nz=key(nx,ny);if(nx<1||nx>22||ny<1||ny>12||parent[nz]!==-2)continue;const at={x:nx*sz+20,y:ny*sz+20};if(s.obstacles.some(o=>at.x>o.x-R-3&&at.x<o.x+o.w+R+3&&at.y>o.y-R-3&&at.y<o.y+o.h+R+3))continue;parent[nz]=z;queue.push(nz);}}
if(found<0)return unit(q.x-p.x,q.y-p.y);while(parent[found]!==start&&parent[found]>=0)found=parent[found];return unit(found%cols*sz+20-p.x,Math.floor(found/cols)*sz+20-p.y);}
function floorIndex(p){return clamp(Math.floor(p.y/60),0,7)*12+clamp(Math.floor(p.x/80),0,11);}
function height(s,p){return s.heights[floorIndex(p)]||0;}
function pushOut(p,o){const cx=clamp(p.x,o.x,o.x+o.w),cy=clamp(p.y,o.y,o.y+o.h),dx=p.x-cx,dy=p.y-cy,d=hyp(dx,dy);if(d>=R)return;if(d>0.0001){p.x=cx+dx/d*R;p.y=cy+dy/d*R;if(Math.abs(dx)>Math.abs(dy))p.vx=0;else p.vy=0;}else{const edges=[[Math.abs(p.x-o.x),0,o.x-R],[Math.abs(p.x-o.x-o.w),0,o.x+o.w+R],[Math.abs(p.y-o.y),1,o.y-R],[Math.abs(p.y-o.y-o.h),1,o.y+o.h+R]].sort((a,b)=>a[0]-b[0]);if(edges[0][1]){p.y=edges[0][2];p.vy=0;}else{p.x=edges[0][2];p.vx=0;}}}
function embedded(s,p){return s.obstacles.some(o=>hyp(p.x-clamp(p.x,o.x,o.x+o.w),p.y-clamp(p.y,o.y,o.y+o.h))<R-1e-7);}
function settleWorld(s,p){p.x=clamp(p.x,R,W-R);p.y=clamp(p.y,R,H-R);for(let i=0;i<5&&embedded(s,p);i++){for(const o of s.obstacles)pushOut(p,o);p.x=clamp(p.x,R,W-R);p.y=clamp(p.y,R,H-R);}if(embedded(s,p)&&Number.isFinite(p.safeX)){p.x=p.safeX;p.y=p.safeY;p.vx=p.vy=0;}}
function settleBodies(s){const[p,q]=s.players;for(let i=0;i<24;i++){settleWorld(s,p);settleWorld(s,q);const d=distance(p,q);if(d>=2*R-1e-7)break;const n=unit(q.x-p.x,q.y-p.y),over=2*R-d+.00001;p.x-=n.x*over*.5;p.y-=n.y*over*.5;q.x+=n.x*over*.5;q.y+=n.y*over*.5;}settleWorld(s,p);settleWorld(s,q);}
function log(s,event){s.events.push({...event,tick:s.tick});if(s.events.length>100)s.events.shift();}
function effect(s,x,y,text,color='#ffe4ac'){s.effects.push({x,y,text,color,ttl:45});if(s.effects.length>30)s.effects.shift();}
function damage(s,p,q,amount,type,origin,dir,force=3){if(q.hp<=0||q.z>28&&type!=='wall'&&type!=='shadow')return false;origin=origin||p;dir=dir||unit(q.x-origin.x,q.y-origin.y);const to=unit(origin.x-q.x,origin.y-q.y);const frontal=q.face.x*to.x+q.face.y*to.y>-.12;let dealt=amount;
if(q.guard&&frontal&&q.stamina>=8&&type!=='shard'&&type!=='echo'&&type!=='ribbon'){q.stamina-=8;q.stats.blocks++;dealt*=.18;if(q.guardTicks<=7){p.stun=Math.max(p.stun,13);q.stats.parries++;dealt=0;effect(s,q.x,q.y-28,'招架','#9bead7');}}
if(s.kind===6&&q.prev.b)dealt*=.6;
if(s.kind===10){const torque=force*11/(q.weight===-1?1.5:.85);q.balance+=torque; if(q.balance>=100){q.balance=35;q.stun=Math.max(q.stun,36);dealt+=22;if(p.weightFlips>0)p.stats.topple++;effect(s,q.x,q.y-35,'失衡倒地');}}
if(s.kind===14&&height(s,p)>height(s,q)&&type==='sweep'){dealt*=1.6;p.stats.heightHit++;}
dealt=Math.max(0,dealt);q.hp=Math.max(0,q.hp-dealt);q.vx+=dir.x*force/q.mass;q.vy+=dir.y*force/q.mass;q.hitFlash=9;p.stats.damage+=dealt;if(dealt>0){p.stats.hits++;s.damageEvents++;log(s,{type:'hit',source:p.id,target:q.id,kind:type,damage:+dealt.toFixed(3),x:q.x,y:q.y});}
if(dealt>0&&q.magnetTicks>0&&type==='punch')p.stats.magnetCombo++;
if(dealt>0&&type==='shadow')p.stats.shadowHit++;
if(dealt>0&&type==='hammer'&&p.reels>=12)p.stats.chainHit++;
if(dealt>0&&p.cancelWindow>0&&type!=='shard')p.stats.cancelHit++;
if(dealt>0&&type==='glass'&&p.recycled)p.stats.recycleHit++;
if(dealt>0&&type==='breath')p.stats.breathHit++;
if(dealt>0&&type==='wall'&&p.air>0&&p.gravity!==0)p.stats.wallHit++;
if(dealt>0&&type==='pole')p.stats.poleHit++;
if(dealt>0&&type==='ribbon')p.stats.ribbonHit++;
if(dealt>0&&type==='push')q.echoPushed=180;
if(dealt>0&&type==='echo'&&q.echoPushed>0)p.stats.echoHit++;
if(dealt>0&&['left','right'].includes(type)){if(p.lastArm&&p.lastArm!==type)p.stats.dualHit++;p.lastArm=type;}
if(dealt>0&&type==='element'){const next=p.element;if(q.aura>=0&&q.aura!==next&&q.auraTime>0){p.stats.reaction++;const pair=q.aura+':'+next,bonus=pair==='0:1'?14:pair==='1:0'?10:8;q.hp=Math.max(0,q.hp-bonus);p.stats.damage+=bonus;if(pair==='1:2'||pair==='1:3')q.stun=Math.max(q.stun,30);effect(s,q.x,q.y-35,{'0:1':'蒸汽爆發','1:0':'蒸散','1:2':'導電麻痺','1:3':'凍結'}[pair]||'元素反應');q.aura=-1;q.auraTime=0;}else{q.aura=next;q.auraTime=210;}}
return dealt>0;}
function startAttack(s,p,q,spec){if(p.stun||p.cool||p.attack||p.stamina<(spec.cost||8)||p.wraps>=3&&spec.type==='punch')return false;p.stamina-=spec.cost||8;p.attack={...spec,age:0,dir:{...p.face},hit:false,origin:{x:p.x,y:p.y}};p.cool=(spec.wind||10)+(spec.recover||16);return true;}
function standard(s,p,q,type='punch',damageN=12,range=75,wind=9,force=3){return startAttack(s,p,q,{type,damage:damageN,range,wind,recover:18,force,cost:10,width:21});}
function resolveAttack(s,p,q){const a=p.attack;if(!a)return;a.age++;if(a.age===(a.wind||10)){let o=a.fixedOrigin||p;if(a.type==='shadow')o=shadow(s,p);const end={x:o.x+a.dir.x*a.range,y:o.y+a.dir.y*a.range};if(a.type==='dig'){const loc=distance(p,q)<a.range+R?q:end,idx=floorIndex(loc),old=s.heights[idx];s.heights[idx]=Math.max(-3,old-1);const near=clamp(idx+(a.dir.x>=0?-1:1),0,95);if(Math.floor(near/12)===Math.floor(idx/12))s.heights[near]=Math.min(3,s.heights[near]+1);effect(s,loc.x,loc.y,'地板削低','#e8cf8a');}
if(a.type==='echoSeed'){s.echoes.push({owner:p.id,x:o.x,y:o.y,dx:a.dir.x,dy:a.dir.y,range:a.range,due:s.tick+120,ttl:126});}
if(a.type==='cannon'){s.projectiles.push({owner:p.id,x:o.x+a.dir.x*24,y:o.y+a.dir.y*24,vx:a.dir.x*9,vy:a.dir.y*9,ttl:60});}
else if(segDist(q,o,end)<q.r+(a.width||18)&&clearLine(s,o,q)&&distance(o,q)<a.range+q.r){const t=a.type==='echoSeed'?'punch':a.type==='dig'?'dig':a.type;const yes=damage(s,p,q,a.damage,t,o,a.dir,a.force||3);a.hit=yes;if(yes&&a.type==='glass'&&p.blades>0){p.blades--;for(let k=-1;k<=1;k++)s.shards.push({x:clamp(q.x+a.dir.y*k*20,25,935),y:clamp(q.y-a.dir.x*k*20,25,515),owner:p.id,life:900,safe:24,cool:[0,0]});}if(a.type==='strip'&&yes&&q.modules.length){const part=q.modules.pop();q.mass=1+q.modules.length*.35;s.parts.push({x:q.x,y:q.y,kind:part,owner:q.id});effect(s,q.x,q.y,'武裝脫落');}}
}
if(a.age>=(a.wind||10)+6)p.attack=null;}
function shadow(s,p){const d=distance(p,s.lamp),n=unit(p.x-s.lamp.x,p.y-s.lamp.y),length=clamp(190-d*.38,48,155);return{x:clamp(p.x+n.x*length,20,940),y:clamp(p.y+n.y*length,20,520),length};}
function magnet(s,p,q,u){if(u.b&&!p.prev.b)p.polarity*=-1;if(u.c&&!p.skillCool&&p.stamina>=15&&distance(p,q)<330&&clearLine(s,p,q)){p.stamina-=15;p.skillCool=44;const n=unit(q.x-p.x,q.y-p.y),d=distance(p,q),force=clamp(13-d*.023,4,11)*p.polarity;q.vx+=n.x*force/q.mass;q.vy+=n.y*force/q.mass;p.vx-=n.x*force*.3/p.mass;p.vy-=n.y*force*.3/p.mass;q.magnetTicks=75;effect(s,q.x,q.y,p.polarity>0?'排斥':'吸引',p.polarity>0?'#ff9ca5':'#83e6ef');}if(u.a)standard(s,p,q);}
function mech(s,p,q,u){if(u.b)standard(s,p,q,'strip',6,64,16,1);else if(u.a){const part=p.modules[p.modules.length-1];if(part==='ram')standard(s,p,q,'ram',19,64,17,7);else if(part==='cannon')standard(s,p,q,'cannon',10,90,18,2);else standard(s,p,q,'punch',part?14:7,part?92:57,part?11:7,3);}if(u.c&&!p.toolCool){const i=s.parts.findIndex(t=>distance(t,p)<112);if(i>=0){const part=s.parts.splice(i,1)[0];p.modules.push(part.kind);if(embedded(s,p))errors.push('obstacle penetration');if(p.modules.length>3)p.modules.shift();p.mass=1+p.modules.length*.35;p.stats.salvage+=part.owner!==p.id?1:0;p.toolCool=25;effect(s,p.x,p.y-25,'裝上 '+({blade:'刀臂',ram:'撞角',cannon:'砲臂'}[part.kind]));}}}
function shadowGame(s,p,q,u){if(u.b){const goal={x:p.x-p.face.x*112,y:p.y-p.face.y*112},n=unit(goal.x-s.lamp.x,goal.y-s.lamp.y),d=distance(goal,s.lamp);s.lamp.x=clamp(s.lamp.x+n.x*Math.min(d,7),35,925);s.lamp.y=clamp(s.lamp.y+n.y*Math.min(d,7),35,505);}if(u.a)standard(s,p,q,'punch',11,68,8,2);if(u.c){const sh=shadow(s,p);if(startAttack(s,p,q,{type:'shadow',damage:17,range:56,wind:13,recover:20,force:2,cost:14,width:25}))p.attack.dir=unit(q.x-sh.x,q.y-sh.y);}}
function chain(s,p,q,u){if(u.a&&p.stamina>0){p.spin=clamp(p.spin+.0035,-.19,.19);p.stamina-=.14;}else p.spin*=.988;const old=p.length;if(u.b&&p.length>48){p.length-=1.3;p.reels++;}if(u.c&&p.length<174){p.length+=1.6;p.reels++;}p.length=clamp(p.length,48,174);if(old!==p.length)p.spin=clamp(p.spin*old/p.length,-.23,.23);const prior=p.hammer||{x:p.x+Math.cos(p.angle)*p.length,y:p.y+Math.sin(p.angle)*p.length};p.angle+=p.spin;const ball={x:p.x+Math.cos(p.angle)*p.length,y:p.y+Math.sin(p.angle)*p.length};if(!clearLine(s,p,ball)){p.spin*=-.65;effect(s,ball.x,ball.y,'反彈');}else if(segDist(q,prior,ball)<R+15&&Math.abs(p.spin)*p.length>4&&!p.hammerHit){if(damage(s,p,q,8+Math.abs(p.spin)*p.length*.45,'hammer',ball,unit(q.x-p.x,q.y-p.y),5))p.hammerHit=25;}p.hammer=ball;}
function folding(s,p,q,u){if(u.b&&!p.prev.b&&!p.toolCool&&p.stamina>=8){const cancel=p.cool>0&&!p.attack;p.form=(p.form+1)%3;p.stamina-=8;p.toolCool=15;if(cancel){p.cool=0;p.cancelWindow=48;effect(s,p.x,p.y-24,'取消收招');}}if(u.c&&p.form===0){p.guard=true;}else if(u.a||u.c){const range=[61,135,69][p.form],dmg=[8,13,10][p.form];startAttack(s,p,q,{type:'punch',range,damage:dmg,wind:[8,14,5][p.form],recover:[16,21,10][p.form],force:p.form===0?6:2,cost:8,width:p.form===2?30:17});}}
function glass(s,p,q,u){if(u.b&&!p.toolCool){let count=0;for(let i=s.shards.length-1;i>=0;i--)if(distance(s.shards[i],p)<125){s.shards.splice(i,1);count++;}if(count){p.blades=Math.min(4,p.blades+Math.ceil(count/3));p.recycled=true;p.toolCool=28;effect(s,p.x,p.y-30,'回收重鑄');}}if(u.a)standard(s,p,q,p.blades?'glass':'punch',p.blades?13:5,73,9,2);if(u.c)standard(s,p,q,'kick',6,80,14,10);}
function breath(s,p,q,u){if(u.b&&!p.burst){p.breath=Math.min(100,p.breath+1.4);p.guard=true;}if(u.c&&!u.b&&!p.burst&&p.breath>=45&&!p.cool&&!p.stun){p.breath-=45;p.burst=65;}if(p.burst>0){p.burst--;if(p.burst%17===0&&!p.attack){p.cool=0;startAttack(s,p,q,{type:'breath',damage:11,range:82,wind:5,recover:10,force:1.3,cost:2,width:22});}}else if(u.a&&!u.b&&p.breath>=12&&!p.cool&&!p.stun){if(standard(s,p,q,'punch',10,70,7,2))p.breath-=12;}}
function wall(s,p,q,u){if(u.b&&!p.toolCool){const walls=[{d:H-R-p.y,g:0,x:p.x,y:H-R},{d:p.x-R,g:1,x:R,y:p.y},{d:p.y-R,g:2,x:p.x,y:R},{d:W-R-p.x,g:3,x:W-R,y:p.y}].sort((a,b)=>a.d-b.d);let w=walls[0];if(u.x<-.2&&p.x<110)w=walls.find(v=>v.g===1);if(u.x>.2&&p.x>850)w=walls.find(v=>v.g===3);if(u.y<-.2&&p.y<110)w=walls.find(v=>v.g===2);if(w.d<100){p.gravity=w.g;p.attached=true;p.x=w.x;p.y=w.y;p.vx=p.vy=0;p.toolCool=25;effect(s,p.x,p.y,'重力轉向');}}if(u.c&&p.attached&&!p.skillCool){const n=unit(q.x-p.x,q.y-p.y);p.vx=n.x*14;p.vy=n.y*14;p.attached=false;p.air=105;p.skillCool=70;p.dash=20;startAttack(s,p,q,{type:'wall',damage:21,range:60,wind:10,recover:28,force:5,cost:15,width:30});}if(u.a)standard(s,p,q,p.air?'wall':'punch',12,73,8,2);}
function pole(s,p,q,u){const direction=p.id?-1:1;if(u.b&&p.stamina>.3){s.pole=clamp(s.pole+direction*.009,-1,1);p.stamina-=.35;const n=unit(p.x-q.x,p.y-q.y);q.vx+=n.x*.3;q.vy+=n.y*.3;}if(u.c&&!p.toolCool&&p.stamina>=12){s.pole=clamp(s.pole+direction*.31,-1,1);p.stamina-=12;p.toolCool=38;p.cool=Math.max(p.cool,12);}if(u.a)standard(s,p,q,s.pole*direction>.55?'pole':'kick',s.pole*direction>.55?19:6,s.pole*direction>.55?185:69,11,s.pole*direction>.55?5:2);}
function ribbon(s,p,q,u){if(u.b&&!p.toolCool&&p.stamina>=10&&distance(p,q)<190&&clearLine(s,p,q)){p.wraps=Math.min(4,p.wraps+1);p.tether=q.id;p.toolCool=24;p.stamina-=10;effect(s,q.x,q.y,'纏繞 '+p.wraps);}if(u.c&&p.wraps&&!p.skillCool){const wraps=p.wraps;p.wraps=0;p.tether=-1;p.skillCool=38;if(distance(p,q)<220&&clearLine(s,p,q))damage(s,p,q,wraps*8,'ribbon',p,unit(q.x-p.x,q.y-p.y),wraps*2);}if(u.a)standard(s,p,q,'punch',9,68,9,2);}
function armor(s,p,q,u){if(u.b&&!p.prev.b){p.weight*=-1;p.weightFlips++;p.balance=Math.max(0,p.balance-17);}if(u.c&&!p.skillCool&&p.stamina>=18){p.skillCool=46;p.stamina-=18;p.dash=18;const n=unit(q.x-p.x,q.y-p.y);p.vx=n.x*(p.weight===1?12:8);p.vy=n.y*(p.weight===1?12:8);startAttack(s,p,q,{type:'shoulder',damage:13,range:65,wind:9,recover:24,force:p.weight===1?8:5,cost:5,width:26});}if(u.a)standard(s,p,q,'kick',11,78,14,p.weight===1?5:3.5);}
function echo(s,p,q,u){if(u.a)standard(s,p,q,'echoSeed',7,79,8,1);if(u.b)standard(s,p,q,'push',5,75,12,7);if(u.c&&!p.skillCool){p.skillCool=42;const n=unit(q.x-p.x,q.y-p.y);p.vx=-n.y*10;p.vy=n.x*10;p.dash=11;}}
function arms(s,p,q,u){for(const [button,hand,max,wind] of[['a','left',36,5],['b','right',66,12]]){const ck=hand+'Charge',cd=hand+'Cool';if(u[button]&&!p[cd]&&!p.stun){p[ck]=Math.min(max,p[ck]+1);}if(!u[button]&&p.prev[button]&&p[ck]>3&&!p[cd]&&!p.stun&&p.stamina>=8){const charge=p[ck];p[ck]=0;p[cd]=hand==='left'?25:43;p.stamina-=8;const spec={type:hand,damage:6+charge*.32,range:hand==='left'?76:95,wind,recover:12,force:hand==='left'?2:5,cost:1,width:22};if(!p.attack){p.cool=0;startAttack(s,p,q,spec);}else{p.pendingArm=spec;}}}if(p.pendingArm&&!p.attack&&!p.stun){p.cool=0;startAttack(s,p,q,p.pendingArm);p.pendingArm=null;}if(u.c&&(p.leftCool===0||p.rightCool===0)&&!(u.a&&u.b))p.guard=true;}
function element(s,p,q,u){if(u.b&&!p.prev.b)p.element=(p.element+1)%4;if(u.a)standard(s,p,q,'element',10,76,8,2);if(u.c&&!p.skillCool){p.element=(p.element+1)%4;if(standard(s,p,q,'element',13,96,13,4))p.skillCool=45;}}
function sculpt(s,p,q,u){if(u.a)standard(s,p,q,'dig',9,91,16,1);if(u.b)standard(s,p,q,'sweep',12,90,8,2);if(u.c&&!p.skillCool&&p.z===0){p.z=1;p.vz=4.4;p.skillCool=60;}}
const handlers=[magnet,mech,shadowGame,chain,folding,glass,breath,wall,pole,ribbon,armor,echo,arms,element,sculpt];
function snapshot(s){return{tick:s.tick,players:s.players.map(p=>({id:p.id,x:p.x,y:p.y,hp:p.hp,stamina:p.stamina,attack:p.attack?{age:p.attack.age,wind:p.attack.wind,range:p.attack.range,dir:{...p.attack.dir}}:null,cool:p.cool,guard:p.guard,breath:p.breath,burst:p.burst,wraps:p.wraps,form:p.form,air:p.air,attached:p.attached,leftCool:p.leftCool,rightCool:p.rightCool,blades:p.blades,element:p.element,balance:p.balance,modules:[...p.modules]})),pole:s.pole};}
function aiInput(s){const ai=s.ai,mode=s.options.mode,diff=mode==='challenge'?'easy':s.options.difficulty;const cfg={easy:{delay:28,period:22,range:65,defend:false},normal:{delay:14,period:12,range:70,defend:true},hard:{delay:6,period:6,range:60,defend:true}}[diff];const memory=ai.history;let obs=null;for(let i=memory.length-1;i>=0;i--)if(memory[i].tick<=s.tick-cfg.delay){obs=memory[i];break;}if(!obs)return normalize();if(s.tick-ai.lastDecision<cfg.period)return ai.held;ai.lastDecision=s.tick;ai.observations++;const p=obs.players[1],q=obs.players[0],d=distance(p,q),n=nav(s,p,q),u=normalize();const approach=d>cfg.range;
if(approach){u.x=n.x;u.y=n.y;}else if(diff==='hard'&&q.guard&&d<55){u.x=-n.x;u.y=-n.y;}if(mode==='challenge'){const period=s.level.attackPeriod||145,phase=(s.tick+(s.level.opening||0))%period;if(phase<32){u.a=d<110;u.d=false;}if(s.level.stance==='guard'&&phase>=55&&phase<95)u.d=true;}else {u.a=d<135;u.d=cfg.defend&&!!q.attack&&q.attack.age<q.attack.wind&&d<q.attack.range+40;if(diff==='easy')u.a=u.a&&s.tick%100<55;}
if(!u.d&&(mode!=='challenge'||s.tick%240<45)){
switch(s.kind){case 0:if(d>105&&d<290){u.c=true;u.b=s.players[1].polarity>0;}break;case 1:u.b=diff!=='easy'&&d<62&&p.modules.length<3;u.c=true;break;case 2:u.b=d<190;u.c=d>82&&d<190;u.a=d<85;break;case 3:u.a=d<220;u.b=d<90;u.c=d>120;break;case 4:u.b=!!p.cool&&!p.attack;u.c=p.form===0&&u.d;break;case 5:u.b=p.blades<2;u.c=diff==='hard'&&d<75&&s.tick%180<25;break;case 6:if(mode==='challenge'){u.b=p.breath<40;u.a=!u.b&&d<100;u.c=p.breath>=65&&d<90;}else{u.b=p.breath<75&&!p.burst;u.a=!u.b&&!p.burst&&d<100;u.c=p.breath>=75&&d<100;}break;case 7:u.b=d>160;u.c=p.attached;break;case 8:u.b=obs.pole>-.6;u.c=obs.pole>-.6;break;case 9:u.b=p.wraps<2&&d<190;u.c=p.wraps>=2;break;case 10:u.c=d<190;u.b=p.balance>55;break;case 11:u.b=diff==='hard'&&d<55&&s.tick%200<30;break;case 12:u.a=d<130&&s.tick%50<20;u.b=d<130&&s.tick%85<45;break;case 13:u.b=s.tick%70<cfg.period;u.c=diff==='hard'&&s.tick%150<cfg.period;break;case 14:u.a=s.tick%80<40;u.b=!u.a;break;}}
if(mode==='challenge'&&s.kind!==3&&s.kind!==12&&(s.tick+(s.level.opening||0))%(s.level.attackPeriod||145)>70){u.a=false;u.c=false;u.b=false;}
if(u.d){u.a=false;u.b=false;u.c=false;}ai.held=normalize(u);ai.events.push({tick:s.tick,observedTick:obs.tick,difficulty:diff,input:{...ai.held}});if(ai.events.length>500)ai.events.shift();return ai.held;}
function move(s,p,q,u){if(p.hp<=0)return;p.safeX=p.x;p.safeY=p.y;const tied=q.tether===p.id?q.wraps:0;let speed=3.6/(.8+p.mass*.2)*(p.guard?.43:1)*(p.attack?.5:1)*(p.stun?0:1)/(1+tied*.22+p.wraps*.13);if(s.kind===6&&u.b)speed*=.55;if(s.kind===10)speed*=p.weight===1?.8:.68;if(s.kind===14){const ahead={x:p.x+u.x*25,y:p.y+u.y*25};if(height(s,ahead)>height(s,p)&&p.z<5)speed*=.45;}
if(s.kind===7&&!p.attached){const gravity=[[0,.25],[-.25,0],[0,-.25],[.25,0]][p.gravity];p.vx+=gravity[0];p.vy+=gravity[1];}if(s.kind===7&&p.attached){const vertical=p.gravity===1||p.gravity===3;if(vertical)p.y+=u.y*speed;else p.x+=u.x*speed;}else{p.x+=u.x*speed;p.y+=u.y*speed;}p.vx=clamp(p.vx,-18,18);p.vy=clamp(p.vy,-18,18);p.x+=p.vx;p.y+=p.vy;const damp=p.dash>0?.93:s.kind===7?.965:.83;p.vx*=damp;p.vy*=damp;
const beforeX=p.x,beforeY=p.y;p.x=clamp(p.x,R,W-R);p.y=clamp(p.y,R,H-R);if(beforeX!==p.x){if(s.kind===0&&Math.abs(p.vx)>3&&p.magnetTicks){p.hp=Math.max(0,p.hp-3);s.players[1-p.id].stats.magnetCombo++;}p.vx=-p.vx*(s.kind===0?.4:.08);}if(beforeY!==p.y)p.vy=-p.vy*(s.kind===0?.4:.08);
if(s.kind===7&&p.air<=0&&(p.x===R||p.x===W-R||p.y===R||p.y===H-R))p.attached=true;
settleWorld(s,p);
if(p.z>0){p.z+=p.vz;p.vz-=.28;if(p.z<=0){p.z=0;p.vz=0;}}
}
function ambient(s){for(let i=s.shards.length-1;i>=0;i--){const t=s.shards[i];t.life--;t.safe=Math.max(0,t.safe-1);for(const p of s.players){t.cool[p.id]=Math.max(0,t.cool[p.id]-1);if(!t.safe&&!t.cool[p.id]&&distance(p,t)<R+9&&p.z<12){const owner=s.players[t.owner];damage(s,owner,p,4,'shard',t,unit(p.x-t.x,p.y-t.y),.5);t.cool[p.id]=48;}}if(t.life<=0)s.shards.splice(i,1);}for(let i=s.echoes.length-1;i>=0;i--){const e=s.echoes[i];if(s.tick===e.due){const p=s.players[e.owner],q=s.players[1-e.owner],end={x:e.x+e.dx*e.range,y:e.y+e.dy*e.range};if(segDist(q,e,end)<R+24&&clearLine(s,e,q))damage(s,p,q,18,'echo',e,{x:e.dx,y:e.dy},2);effect(s,e.x,e.y,'殘影','#bca8ff');}if(s.tick>e.due+6)s.echoes.splice(i,1);}for(let i=s.projectiles.length-1;i>=0;i--){const b=s.projectiles[i],old={x:b.x,y:b.y};b.x+=b.vx;b.y+=b.vy;b.ttl--;const p=s.players[b.owner],q=s.players[1-b.owner];if(segDist(q,old,b)<R+7){damage(s,p,q,10,'cannon',old,unit(b.vx,b.vy),2);b.ttl=0;}if(!clearLine(s,old,b)||b.x<10||b.x>950||b.y<10||b.y>530)b.ttl=0;if(b.ttl<=0)s.projectiles.splice(i,1);}s.effects=s.effects.filter(e=>--e.ttl>0);}
function check(s){const[p,q]=s.players;if(p.hp<=0||q.hp<=0){s.winner=p.hp<=0?(q.hp<=0?-1:1):0;if(s.options.mode==='challenge'){const metric=D.byId[s.id].metric,goal=s.level.goal||1;const complete=p.stats[metric]>=goal&&p.stats.blocks>=(s.level.defenseGoal||0);if(s.winner===0&&complete){s.status='won';s.message='挑戰成功：'+D.byId[s.id].metricName+'達標，並擊敗對手。';}else{s.status='lost';s.message=s.winner===0?'擊倒成功，但專屬技巧尚未完成；再試一次。':'本回合落敗；觀察預備線後防守。';}}else{s.status=s.winner===0?'won':'lost';s.message=s.winner<0?'雙方同時倒下。':'玩家 '+(s.winner+1)+' 獲勝！';}}
if(s.tick>=s.level.limit&&s.status==='playing'){s.status='lost';s.message='時間到；調整接近路線與連段節奏。';}return s;}
function step(s,raw={},raw2){if(s.status!=='playing')return s;const u=normalize(raw),v=s.options.mode==='local'?normalize(raw2):aiInput(s);s.tick++;if(u.a||u.b||u.c||u.d||u.x||u.y)s.inputs++;const inputs=[u,v];s.ai.history.push(snapshot(s));if(s.ai.history.length>90)s.ai.history.shift();
for(let i=0;i<2;i++){const p=s.players[i],q=s.players[1-i],a=inputs[i];for(const k of['cool','stun','toolCool','skillCool','magnetTicks','cancelWindow','leftCool','rightCool','hammerHit','dash','air','hitFlash','auraTime','echoPushed'])p[k]=Math.max(0,p[k]-1);p.stamina=Math.min(100,p.stamina+.28);p.balance=Math.max(0,p.balance-.25);p.guard=!!a.d&&p.stamina>2&&!p.stun&&!p.attack;const n=unit(q.x-p.x,q.y-p.y);if(!p.attack)p.face=n;if(!p.stun)handlers[s.kind](s,p,q,a);if(p.guard){p.guardTicks++;p.stamina=Math.max(0,p.stamina-.16);}else p.guardTicks=0;move(s,p,q,a);}
const[p,q]=s.players;let d=distance(p,q);if(d<2*R){const n=unit(q.x-p.x,q.y-p.y),over=2*R-d;p.x-=n.x*over*.5;p.y-=n.y*over*.5;q.x+=n.x*over*.5;q.y+=n.y*over*.5;}
if(s.kind===8&&d>225){const n=unit(q.x-p.x,q.y-p.y),over=d-225;p.x+=n.x*over*.5;p.y+=n.y*over*.5;q.x-=n.x*over*.5;q.y-=n.y*over*.5;}
settleBodies(s);for(let i=0;i<2;i++){const p=s.players[i];resolveAttack(s,p,s.players[1-i]);p.prev=inputs[i];}
ambient(s);return check(s);}
function replay(id,level,witness,options){const s=create(id,level,options);for(const row of witness){if(!Array.isArray(row)||row.length!==2||!Number.isInteger(row[0])||row[0]<1||row[0]>600)throw Error('Illegal replay segment');for(let i=0;i<row[0]&&s.status==='playing';i++)step(s,row[1]);}return s;}
function invariants(s){const errors=[];for(const p of s.players){for(const k of['x','y','vx','vy','hp','stamina','mass','breath','balance','spin','length','z'])if(!Number.isFinite(p[k]))errors.push('finite:'+k);if(p.x<R-.001||p.x>W-R+.001||p.y<R-.001||p.y>H-R+.001)errors.push('bounds');if(p.hp<0||p.stamina<-.5||p.stamina>100.001||p.breath<0||p.breath>100)errors.push('resource');if(embedded(s,p))errors.push('obstacle penetration');if(p.modules.length>3||p.wraps<0||p.wraps>4||p.length<48||p.length>174)errors.push('mechanic bounds');}if(distance(...s.players)<R*2-.01)errors.push('body penetration');return errors;}
return{W,H,DT,R,create,step,replay,normalize,pack,invariants,shadow,nav,height,clearLine,distance,snapshot,definitions:D.games,VERSION:D.VERSION};});
