const fs=require('fs'),path=require('path'),crypto=require('crypto'),E=require('./engine.js'),D=require('./definitions.js'),Coach=require('./coach.cjs');
const base=__dirname,games=path.dirname(base);const rand=seed=>()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};
function canonical(L){const cells=L.obstacles.map(o=>[o.x,o.y,o.w,o.h]);let variants=[];for(let fx=0;fx<2;fx++)for(let fy=0;fy<2;fy++)variants.push(JSON.stringify(cells.map(([x,y,w,h])=>[fx?960-x-w:x,fy?540-y-h:y,w,h]).sort((a,b)=>a[0]-b[0]||a[1]-b[1])));return variants.sort()[0];}
function level(kind,n,attempt=0){const r=rand((kind+1)*8191+n*983+attempt*171713),obstacles=[];let count=3+(n%9);const cells=new Set();while(obstacles.length<count){const col=2+Math.floor(r()*8),row=1+Math.floor(r()*6),k=col+','+row;if(cells.has(k)||col>=4&&col<=7&&row>=2&&row<=5)continue;cells.add(k);obstacles.push({x:col*80+9,y:row*60+8,w:30+Math.floor(r()*17),h:27+Math.floor(r()*13)});}
const start={x:110+(n%3)*14,y:105+(n*37)%330},enemy={x:705+(n%4)*26,y:98+(n*53)%350};if(kind===7){start.x=48;start.y=80+n*23%380;enemy.x=690;enemy.y=390+n%4*22;}for(let i=obstacles.length-1;i>=0;i--){const o=obstacles[i];if([start,enemy].some(p=>Math.hypot(p.x-Math.max(o.x,Math.min(o.x+o.w,p.x)),p.y-Math.max(o.y,Math.min(o.y+o.h,p.y)))<28))obstacles.splice(i,1);}
const heights=Array(96).fill(0);if(kind===14){for(let i=0;i<96;i++)if(r()<.18)heights[i]=r()<.5?-1:1;}
return{id:n+1,seed:(kind+1)*8191+n*983+attempt*171713,start,enemy,obstacles,hp:88+n%5*7,limit:4800,goal:1+(n>=60?1:0),defenseGoal:n%10===9?1:0,enemyModules:[['blade','ram'],['ram','cannon'],['cannon','blade']][n%3],attackPeriod:135+n%7*13,opening:n%5*17,stance:n%4===2?'guard':'counter',hammerRadius:68+n%7*13,heights,lamp:{x:260+n%6*40,y:80+n%7*53},title:['側翼切入','窄道交換','反擊節奏','長短距離','回收窗口','繞柱牽制','連段保持','防守拆解','地形角度','耐力管理'][Math.floor(n/10)]+' '+(n%10+1),brief:'先完成專屬技巧，再擊倒對手。障礙有實際碰撞，橘色線是攻擊預備。'};}
function generate(selection=[]){const report=[];for(const g of D.games){if(selection.length&&!selection.includes(g.id))continue;const levels=[],proofs=[],seen=new Set(),failures=[];for(let n=0;n<100;n++){let solved=null,L;for(let attempt=0;attempt<25;attempt++){L=level(g.kind,n,attempt);const can=canonical(L);if(seen.has(can))continue;const result=Coach.solve(g.id,L);if(result.state.status==='won'){solved=result;seen.add(can);break;}failures.push({n:n+1,attempt,status:result.state.status,ticks:result.state.tick,hp:result.state.players.map(p=>Math.round(p.hp)),metric:result.state.players[0].stats[g.metric]});}
if(!solved){console.log('FAILED',g.id,n+1,failures.slice(-4));break;}levels.push(L);proofs.push({id:L.id,status:'won',ticks:solved.state.tick,witness:solved.witness,final:{hp:+solved.state.players[0].hp.toFixed(5),metric:solved.state.players[0].stats[g.metric]},levelHash:crypto.createHash('sha256').update(JSON.stringify(L)).digest('hex')});}
fs.mkdirSync(path.join(games,g.id),{recursive:true});fs.writeFileSync(path.join(games,g.id,'levels.json'),JSON.stringify(levels));fs.writeFileSync(path.join(games,g.id,'proofs.json'),JSON.stringify(proofs));fs.writeFileSync(path.join(games,g.id,'levels.js'),'window.DuelLevels='+JSON.stringify(levels)+';\nwindow.DuelProofs='+JSON.stringify(proofs)+';\n');report.push({id:g.id,count:levels.length,retries:failures.length,ticks:proofs.reduce((a,b)=>a+b.ticks,0)});console.log(report.at(-1));}

return report;}
if(require.main===module)generate(process.argv.slice(2));
module.exports={canonical,level,generate};
