/* Original whole-line creature puzzle. No swap-match engine is used. */
(function(root,f){if(typeof module==='object')module.exports=f();else root.Puffball=f();})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';const VERSION=1,clone=x=>JSON.parse(JSON.stringify(x));

// Presentation traces are outputs, never stored simulation or alternate game rules.
const TRACES=new WeakMap();
function visual(s){const {refill,events,...v}=s;return clone({...v,events:[]});}
function frame(s,kind,meta={}){const out=TRACES.get(s);if(out)out.push({kind,...clone(meta),state:visual(s)});}
function compactTimeline(input){const out=[];for(let i=0;i<input.length;i++){const f=input[i];if(!['fall','refill'].includes(f.kind)||!out.length){out.push(f);continue;}const group=[f];while(i+1<input.length&&['fall','refill'].includes(input[i+1].kind))group.push(input[++i]);const before=out[out.length-1].state,last=group[group.length-1],key=t=>t&&(t.uid??(t.id+':'+(t.part??0))),known=new Set(before.board.filter(Boolean).map(key));const falling=clone(last.state);falling.board=falling.board.map(t=>t&&known.has(key(t))?t:null);const moved=falling.board.some((t,j)=>t&&key(t)!==key(before.board[j]));if(moved)out.push({kind:'fall',label:'空格下落・原有棋子保留',state:falling});const cells=last.state.board.map((t,j)=>t&&!known.has(key(t))?j:-1).filter(j=>j>=0);if(cells.length)out.push({kind:'refill',label:'新棋子補入',cells,spawn:group.flatMap(x=>x.spawn||[]),state:last.state});}return out;}
function finishTrace(s,result){const timeline=TRACES.get(s)||[];TRACES.delete(s);return {...result,timeline:compactTimeline(timeline)};}
function rng(s){s.rng=(Math.imul(s.rng,1664525)+1013904223)>>>0;return s.rng;}
function fresh(s){let c=s.refill[s.refillAt++%s.refill.length];return {id:s.nextId++,c:c===undefined?rng(s)%s.colors:c,star:false,lock:0,giant:false};}
function neighbors(s,i){let x=i%s.w,y=Math.floor(i/s.w);return [[x-1,y],[x+1,y],[x,y-1],[x,y+1]].filter(([x,y])=>x>=0&&x<s.w&&y>=0&&y<s.h).map(([x,y])=>y*s.w+x);}
function createScenario(level,options={}){const p=clone(level.initial);let s={version:VERSION,game:'puffball-shift',levelId:level.id,w:p.w,h:p.h,colors:p.colors||5,board:[],nextId:1,rng:p.seed||119,refill:p.refill||[],refillAt:0,turn:0,moves:level.moves||20,score:0,groups:0,collected:[0,0,0,0,0,0],unlocked:0,rescued:0,stars:0,detonated:0,maxChain:0,targets:p.targets||[],washed:[],shuffleLeft:p.shuffles||0,shufflesUsed:0,objective:clone(level.objective),status:'playing',paused:false,assisted:false,mode:options.mode||'campaign',message:'選一隻毛球，用畫面箭頭或 W/A/S/D 滑動整行、整列。',events:[]};s.board=p.board.map(t=>typeof t==='number'?{id:s.nextId++,c:t,star:false,lock:0,giant:false}:{id:s.nextId++,star:false,lock:0,giant:false,...t});for(const g of p.giants||[]){let id=s.nextId++;for(const [part,i]of g.cells.entries())s.board[i]={id,part,c:g.c,giant:true,star:!!g.star,lock:g.lock||0};}if(!legalMoves(s).length&&!s.shuffleLeft){s.status='lost';s.message='全部行列被鎖住，沒有洗牌額度；請重新開始。';}return s;}
function groups(s){let seen=new Set(),out=[];for(let i=0;i<s.board.length;i++){if(seen.has(i)||!s.board[i])continue;let q=[i],cells=[],ids=new Set(),c=s.board[i].c;seen.add(i);while(q.length){let n=q.shift();cells.push(n);ids.add(s.board[n].id);for(const j of neighbors(s,n))if(!seen.has(j)&&s.board[j]?.c===c){seen.add(j);q.push(j);}}if(ids.size>=3)out.push({cells,ids:[...ids],c});}return out;}
function affectedLines(s,axis,line){if(!['row','col'].includes(axis)||!Number.isInteger(line)||line<0||line>=(axis==='row'?s.h:s.w))return [];const set=new Set([line]);let changed=true;while(changed){changed=false;const giantIds=new Set(s.board.filter((t,i)=>t.giant&&set.has(axis==='row'?Math.floor(i/s.w):i%s.w)).map(t=>t.id));s.board.forEach((t,i)=>{let n=axis==='row'?Math.floor(i/s.w):i%s.w;if(giantIds.has(t.id)&&!set.has(n)){set.add(n);changed=true;}});}return [...set].sort((a,b)=>a-b);}
function canShift(s,a){if(!['row','col'].includes(a.axis)||![-1,1].includes(a.dir))return false;const ls=affectedLines(s,a.axis,a.line);return ls.length>0&&!s.board.some((t,i)=>t.lock>0&&ls.includes(a.axis==='row'?Math.floor(i/s.w):i%s.w));}
function legalMoves(s){const arr=[];for(const axis of ['row','col'])for(let line=0;line<(axis==='row'?s.h:s.w);line++)for(const dir of [-1,1]){const a={type:'shift',axis,line,dir};if(canShift(s,a))arr.push(a);}return arr;}
function shift(s,a){const ls=affectedLines(s,a.axis,a.line),old=s.board.slice();for(let i=0;i<old.length;i++){let x=i%s.w,y=Math.floor(i/s.w);if(!ls.includes(a.axis==='row'?y:x))continue;let nx=a.axis==='row'?(x+a.dir+s.w)%s.w:x,ny=a.axis==='col'?(y+a.dir+s.h)%s.h:y;s.board[ny*s.w+nx]=old[i];}s.events.push({type:'shift',axis:a.axis,lines:ls,dir:a.dir});frame(s,'shift',{axis:a.axis,lines:ls,dir:a.dir,label:ls.length>1?'大毛球連動・整條循環移動':'整條循環移動'});}
function gravity(s){for(let x=0;x<s.w;x++){let cells=[];const settle=()=>{if(!cells.length)return;const before=s.board.map(t=>t?.id),top=Math.floor(cells[0]/s.w);let items=cells.map(i=>s.board[i]).filter(Boolean),empty=[];for(let k=cells.length-1;k>=0;k--){const i=cells[k];s.board[i]=items.length?items.pop():null;if(!s.board[i])empty.push(i);}if(cells.some(i=>s.board[i]&&before[i]!==s.board[i].id))frame(s,'fall',{column:x,cells:cells.slice(),label:'毛球沿空格下落'});for(let k=cells.length-1;k>=0;k--){const i=cells[k];if(s.board[i])continue;let t;for(let attempt=0;attempt<24;attempt++){t=fresh(s);s.board[i]=t;if(!groups(s).some(g=>g.cells.includes(i)))break;}}if(empty.length)frame(s,'refill',{column:x,cells:empty,spawn:empty.map(i=>({i,top})),label:'新毛球補位'});cells=[];};for(let y=0;y<s.h;y++){const i=y*s.w+x;if(s.board[i]?.giant||s.board[i]?.lock){settle();continue;}cells.push(i);}settle();}}
function resolve(s){for(let wave=1;wave<=80;wave++){const gs=groups(s);if(!gs.length)return;frame(s,'match',{cells:gs.flatMap(g=>g.cells),chain:wave,label:'同色毛球成群'});let ids=new Set(gs.flatMap(g=>g.ids)),cells=new Set(gs.flatMap(g=>g.cells)),newStars=[];for(const g of gs)if(g.ids.length>=5){let i=g.cells.find(i=>!s.board[i].giant&&!s.board[i].lock&&!s.board[i].star);if(i!==undefined)newStars.push({i,c:g.c});}let queue=[...cells],fired=new Set();while(queue.length){const i=queue.shift(),t=s.board[i];if(!t.star||fired.has(t.id))continue;fired.add(t.id);s.detonated++;const x=i%s.w,y=Math.floor(i/s.w);for(let j=0;j<s.board.length;j++)if((j%s.w===x||Math.floor(j/s.w)===y)&&!cells.has(j)){cells.add(j);queue.push(j);ids.add(s.board[j].id);}s.events.push({type:'star',cells:[i]});}for(let j=0;j<s.board.length;j++)if(ids.has(s.board[j].id))cells.add(j);if(fired.size)frame(s,'blast',{cells:[...cells],chain:wave,label:'星毛球十字清場'});const unlockIds=new Set();for(const i of cells)for(const j of neighbors(s,i))if(s.board[j].lock&&!cells.has(j))unlockIds.add(s.board[j].id);for(const id of unlockIds){const t=s.board.find(t=>t.id===id);const lock=t.lock-1;s.board.forEach(t=>{if(t.id===id)t.lock=lock;});if(!lock)s.unlocked++;}const removedIds=new Set();for(const i of cells){const t=s.board[i];if(t.lock){if(!unlockIds.has(t.id)){unlockIds.add(t.id);const lock=t.lock-1;s.board.forEach(v=>{if(v.id===t.id)v.lock=lock;});if(!lock)s.unlocked++;}continue;}if(!removedIds.has(t.id)){s.collected[t.c]++;if(t.giant)s.rescued++;removedIds.add(t.id);}if(s.targets.includes(i)&&!s.washed.includes(i))s.washed.push(i);}for(let i=0;i<s.board.length;i++)if(removedIds.has(s.board[i].id))s.board[i]=null;s.groups+=gs.length;s.score+=removedIds.size*15*wave;s.maxChain=Math.max(s.maxChain,wave);frame(s,'clear',{cells:[...cells],chain:wave,creatures:removedIds.size,unlocks:[...unlockIds],label:'毛球消除・鄰接結鎖鬆開'});gravity(s);for(const p of newStars)if(!s.board[p.i].giant&&!s.board[p.i].lock){s.board[p.i].star=true;s.board[p.i].c=p.c;s.stars++;}if(newStars.length)frame(s,'special',{cells:newStars.map(p=>p.i),chain:wave,label:'五隻成群・星毛球誕生'});s.events.push({type:'clear',cells:[...cells],creatures:removedIds.size,unlocks:[...unlockIds],chain:wave});if(!removedIds.size&&!unlockIds.size)break;}if(groups(s).length){s.status='fault';s.message='連鎖超過安全上限，請重開此關。';}}
function achieved(s){const o=s.objective;return (!o.colors||Object.entries(o.colors).every(([c,n])=>s.collected[c]>=n))&&(!o.groups||s.groups>=o.groups)&&(!o.unlocks||s.unlocked>=o.unlocks)&&(!o.giants||s.rescued>=o.giants)&&(!o.stars||s.stars>=o.stars)&&(!o.detonations||s.detonated>=o.detonations)&&(!o.targets||s.washed.length>=o.targets)&&(!o.chain||s.maxChain>=o.chain);}
function finish(s){if(s.status!=='playing')return;if(s.mode==='campaign'&&achieved(s)){s.status='won';s.message='毛球們脫困了！重玩可以挑戰少滑一步。';}else if(s.mode==='campaign'&&s.moves<=0){s.status='lost';s.message='滑動步數用完了。試試把大毛球當成連動機關。';}else if(!legalMoves(s).length&&!s.shuffleLeft){s.status='lost';s.message='全部行列被鎖住，洗牌額度也已用完。';}}
function applyAction(state,a){let s=clone(state);s.events=[];TRACES.set(s,[]);const bad=t=>{s.message=t;return finishTrace(s,{state:s,ok:false,error:t});};if(a.type==='pause'){s.paused=true;return finishTrace(s,{state:s,ok:true});}if(a.type==='resume'){s.paused=false;return finishTrace(s,{state:s,ok:true});}if(a.type==='hint'){s.assisted=true;let options=legalMoves(s),best=options[0],n=-1;for(const m of options){let q=clone(s);shift(q,m);const score=groups(q).reduce((v,g)=>v+g.ids.length,0);if(score>n){n=score;best=m;}}return finishTrace(s,{state:s,ok:true,hint:best});}if(s.paused||s.status!=='playing')return bad('請先繼續遊戲或重新開始。');if(a.type==='end'&&s.mode==='relaxed'){s.status='ended';return finishTrace(s,{state:s,ok:true});}if(a.type==='shuffle'){if(!s.shuffleLeft)return bad('本關沒有洗牌額度。');const pos=s.board.map((t,i)=>!t.giant&&!t.lock?i:-1).filter(i=>i>=0);for(let j=pos.length-1;j>0;j--){let k=rng(s)%(j+1);[s.board[pos[j]],s.board[pos[k]]]=[s.board[pos[k]],s.board[pos[j]]];}s.shuffleLeft--;s.shufflesUsed++;s.turn++;if(s.mode==='campaign')s.moves--;frame(s,'shuffle',{label:'未鎖小毛球重新排列'});resolve(s);finish(s);return finishTrace(s,{state:s,ok:true});}if(a.type!=='shift'||!canShift(s,a)){frame(s,'blocked',{cells:s.board.map((t,i)=>t.lock?i:-1).filter(i=>i>=0),label:'結鎖擋住行列・不扣步'});return bad('這條行列被結鎖擋住；先在鎖旁消除一群。');}s.turn++;if(s.mode==='campaign')s.moves--;shift(s,a);resolve(s);s.message=s.events.some(e=>e.type==='clear')?'毛球群消完成。大毛球始終四格連動。':'整條循環滑動完成；這一步是在準備下一群。';finish(s);return finishTrace(s,{state:s,ok:true});}
function checkRestored(s,level){const bad=()=>{throw Error('存檔欄位或數值損壞');},plain=x=>x&&typeof x==='object'&&!Array.isArray(x),num=(x,max=1000000000)=>Number.isSafeInteger(x)&&x>=0&&x<=max;if(!plain(s)||!level)bad();const expected=createScenario(level,{mode:s.mode});for(const k of Object.keys(expected)){if(!(k in s))bad();const v=expected[k];if(v!==null&&typeof v!=='object'&&typeof s[k]!==typeof v)bad();if(Array.isArray(v)&&!Array.isArray(s[k]))bad();if(plain(v)&&!plain(s[k]))bad();}if(s.w!==expected.w||s.h!==expected.h||JSON.stringify(s.objective)!==JSON.stringify(level.objective)||JSON.stringify(s.refill)!==JSON.stringify(expected.refill))bad();if(!['playing','won','lost','ended','fault'].includes(s.status)||typeof s.paused!=='boolean'||typeof s.assisted!=='boolean'||typeof s.message!=='string'||s.message.length>10000||!num(s.turn)||!num(s.moves,level.moves||24)||!num(s.score,1000000000000)||!num(s.rng,4294967295)||!num(s.refillAt)||s.events.length>10000)bad();for(const e of s.events){if(!plain(e)||typeof e.type!=='string'||(e.cells&&(!Array.isArray(e.cells)||e.cells.some(i=>!Number.isInteger(i)||i<0||i>=s.w*s.h))))bad();}if(!['campaign','relaxed'].includes(s.mode)||s.colors!==expected.colors||!num(s.nextId)||!num(s.shuffleLeft,99)||!num(s.shufflesUsed)||JSON.stringify(s.targets)!==JSON.stringify(expected.targets)||s.washed.some(i=>!s.targets.includes(i))||new Set(s.washed).size!==s.washed.length||s.collected.length!==6||s.collected.some(n=>!num(n)))bad();for(const k of ['groups','unlocked','rescued','stars','detonated','maxChain'])if(!num(s[k]))bad();for(const t of s.board)if(!plain(t)||'uid'in t||(!t.giant&&'part'in t)||!num(t.id)||t.id>=s.nextId||!Number.isInteger(t.c)||t.c<0||t.c>=s.colors||typeof t.star!=='boolean'||typeof t.giant!=='boolean'||!num(t.lock,9))bad();const ids=new Map();for(const t of s.board)ids.set(t.id,(ids.get(t.id)||0)+1);for(const t of s.board)if(ids.get(t.id)!==(t.giant?4:1))bad();for(const id of new Set(s.board.filter(t=>t.giant).map(t=>t.id))){const cells=s.board.map((t,i)=>t.id===id?i:-1).filter(i=>i>=0),ts=cells.map(i=>s.board[i]),xs=[...new Set(cells.map(i=>i%s.w))].sort((a,b)=>a-b),ys=[...new Set(cells.map(i=>Math.floor(i/s.w)))].sort((a,b)=>a-b);if(xs.length!==2||ys.length!==2||![1,s.w-1].includes(xs[1]-xs[0])||![1,s.h-1].includes(ys[1]-ys[0])||ts.some(t=>t.c!==ts[0].c||t.lock!==ts[0].lock||t.star!==ts[0].star))bad();const left=(xs[0]+1)%s.w===xs[1]?xs[0]:xs[1],top=(ys[0]+1)%s.h===ys[1]?ys[0]:ys[1],legacy=ts.every(t=>!('part'in t));for(const i of cells){const t=s.board[i],part=((Math.floor(i/s.w)-top+s.h)%s.h)*2+(i%s.w-left+s.w)%s.w;if(legacy)t.part=part;else if(!Number.isInteger(t.part)||t.part!==part)bad();}}}
function serialize(s){return JSON.stringify(s);}function deserialize(text,levels){const s=JSON.parse(text);if(s.version!==VERSION||s.game!=='puffball-shift'||!levels.some(l=>l.id===s.levelId)||s.w<4||s.w>8||s.h<4||s.h>9||!Array.isArray(s.board)||s.board.length!==s.w*s.h||s.board.some(t=>!t||!Number.isInteger(t.c)||t.c<0||t.c>5))throw Error('毛球存檔損壞');checkRestored(s,levels.find(l=>l.id===s.levelId));return s;}
return {VERSION,createScenario,applyAction,getOutcome:s=>s.status,serialize,deserialize,legalMoves,groups,affectedLines,canShift,achieved};
});
