/* This title's DOM controller only issues legal public actions to its independent engine. */
(function(){'use strict';const E=Puffball,R=GameRender,levels=GameLevels,SLUG='puffball-shift',$=id=>document.getElementById(id),board=$('board');let run=null,match=null,selected=[],focus=0,hintCells=[],pointer=null,suppressClick=false,soundContext=null,player=null,displayState=null,completedBefore=0,runEpoch=0;
const store=new GameStorage(SLUG,localStorage,(text,notice)=>{$('saveNotice').textContent=text;if(run&&notice?.pause){settleAnimation(false);run=E.applyAction(run,{type:run.status==='playing'?'pause':'resume'}).state;if(match)match.run=run;render();}});
let profile=store.read('profile',{version:1,manual:{},assisted:{},best:0}),options=store.read('options',{reduced:false,contrast:false,sound:false});function validProfile(p){return p&&p.version===1&&Number.isFinite(p.best)&&p.best>=0&&['manual','assisted'].every(k=>p[k]&&typeof p[k]==='object'&&!Array.isArray(p[k])&&Object.entries(p[k]).every(([id,v])=>levels.some(l=>l.id===id)&&v&&Number.isSafeInteger(v.turn)&&v.turn>=0&&Number.isFinite(v.score)&&v.score>=0));}if(!validProfile(profile)){profile={version:1,manual:{},assisted:{},best:0};$('saveNotice').textContent='紀錄欄位損壞，原資料保留；目前顯示安全空白紀錄。';}if(!options||typeof options!=='object'||['reduced','contrast','sound'].some(k=>typeof options[k]!=='boolean'))options={reduced:false,contrast:false,sound:false};
levels.forEach(l=>{const o=document.createElement('option');o.value=l.id;o.textContent=l.id+' · '+l.title;$('level').append(o);});
function currentLevel(){return levels.find(l=>l.id===$('level').value)||levels[0];}function preview(){return E.createScenario(currentLevel());}
function clearInput(){if(pointer)try{board.releasePointerCapture(pointer.id)}catch(e){}selected=[];pointer=null;hintCells=[];}
function save(){if(!run)return;store.write('run',{state:E.serialize(run),match:null,mode:$('mode').value});store.write('profile',profile);}
function sound(){if(!options.sound)return;try{soundContext=soundContext||new (window.AudioContext||window.webkitAudioContext)();const o=soundContext.createOscillator(),g=soundContext.createGain();o.type='sine';o.frequency.value=420+(run?.turn||0)%5*70;g.gain.setValueAtTime(.03,soundContext.currentTime);g.gain.exponentialRampToValueAtTime(.001,soundContext.currentTime+.15);o.connect(g);g.connect(soundContext.destination);o.start();o.stop(soundContext.currentTime+.16);}catch(e){}}
function award(){if(!run)return;if(run.status==='won'&&run.mode==='campaign'){const records=run.assisted?profile.assisted:profile.manual,old=records[run.levelId];if(!old||run.turn<old.turn||run.score>old.score)records[run.levelId]={turn:Math.min(old?.turn||Infinity,run.turn),score:Math.max(old?.score||0,run.score)};}profile.best=Math.max(profile.best||0,run.score);}
function settleAnimation(draw=true){if(player?.busy){player.cancel();$('motionTitle').textContent='已顯示這一步的完整結果';$('motionMeta').textContent=run?.message||'準備下一步';}displayState=null;if(draw)render();}
function renderHUD(s){$('score').textContent=s.score;$('moves').textContent=s.mode==='campaign'?s.moves:'∞';$('stageGoals').replaceChildren();for(const g of R.goals(s)){const chip=document.createElement('span');chip.className=g.value>=g.target?'complete':'';chip.textContent=g.label+' '+Math.min(g.value,g.target)+'/'+g.target;$('stageGoals').append(chip);}$('goals').replaceChildren();for(const g of R.goals(s)){const li=document.createElement('li');li.className=g.value>=g.target?'done':'';const label=document.createElement('span'),value=document.createElement('b');label.textContent=g.label;value.textContent=Math.min(g.value,g.target)+' / '+g.target;li.append(label,value);$('goals').append(li);}}
function resetRecap(restored=false){const li=document.createElement('li');li.textContent=restored&&run?.turn>0?'已載入第 '+run.turn+' 步的盤面；逐波紀錄不隨存檔保存，下一步會重新記錄。':run?'本局尚未操作。下一步後會記錄每一波實際變化。':'開始後，這裡會記錄每一波實際變化。';$('turnRecap').replaceChildren(li);$('turnRecapPanel').open=false;}
function recap(before,result){$('turnRecap').replaceChildren();let prev=before,n=0;for(const f of result.timeline||[]){if(['clear','special','beacon'].includes(f.kind)){const li=document.createElement('li'),gain=f.state.score-prev.score;li.textContent=(f.chain?'第'+f.chain+'波：':'')+(f.kind==='clear'?'消除 '+(f.creatures??f.cells?.length??0)+' '+(SLUG==='puffball-shift'?'隻毛球':'格晶石')+(gain?'，+'+gain+'分':''):f.label);$('turnRecap').append(li);n++;}prev=f.state;}if(!n){const li=document.createElement('li');li.textContent=result.ok?'位置已調整，保留給下一步布局。':result.error;$('turnRecap').append(li);}}
function start(){runEpoch++;settleAnimation(false);clearInput();match=null;run=E.createScenario(currentLevel(),{mode:$('mode').value});resetRecap();$('motionTitle').textContent='準備下一步';$('motionMeta').textContent='先選棋子，再決定移動方向。';render();save();}
function act(action){if(!run)return;if(player?.busy){if(!['pause','resume','end'].includes(action.type))return;settleAnimation(false);}if(action.type==='pause'&&run.status!=='playing'){render();return;}const before=run,result=E.applyAction(run,action);completedBefore=Object.keys(profile.manual).length;run=result.state;hintCells=[];if(result.hint){const h=result.hint;hintCells=run.board.map((t,i)=>(h.axis==='row'?Math.floor(i/run.w):i%run.w)===h.line?i:-1).filter(i=>i>=0);run.message='提示：第'+(h.line+1)+(h.axis==='row'?'列':'欄')+(h.axis==='row'?(h.dir<0?'向左':'向右'):(h.dir<0?'向上':'向下'))+'滑動。';};clearSelectionAfter(action,result);award();save();if(result.timeline?.length&&!run.paused){selected=[];recap(before,result);player.start(before,result.timeline);}else{if(result.ok&&action.type!=='hint')sound();render();}}

function clearSelectionAfter(a,result){}
function render(force=false){if(player?.busy&&!force)return;const s=displayState||run||preview(),l=levels.find(l=>l.id===s.levelId)||currentLevel();$('levelTitle').textContent=l.id+' · '+l.title;$('decision').textContent=l.intendedDecision;$('score').textContent=s.score;$('moves').textContent=s.mode==='campaign'?s.moves:s.mode==='versus'?Math.max(0,12-s.turn):'∞';$('completed').textContent=(player?.busy?completedBefore:Object.keys(profile.manual).length)+' / '+levels.length;$('credit').textContent=s.assisted?'輔助練習・另列紀錄':'手動挑戰';$('goals').replaceChildren();for(const g of R.goals(s)){const li=document.createElement('li'),span=document.createElement('span'),b=document.createElement('b');span.textContent=g.label;b.textContent=Math.min(g.value,g.target)+' / '+g.target;li.className=g.value>=g.target?'done':'';li.append(span,b);$('goals').append(li);}board.style.setProperty('--cols',s.w);const previous=document.activeElement?.dataset?.cell;board.replaceChildren();for(let i=0;i<s.board.length;i++){const t=R.cell(s,i),b=document.createElement('button');b.type='button';b.dataset.cell=i;b.setAttribute('role','gridcell');b.setAttribute('aria-label',`第${Math.floor(i/s.w)+1}列 第${i%s.w+1}格，${t.label}`);b.className='cell '+t.className+(selected.includes(i)?' selected':'')+(hintCells.includes(i)?' hint':'')+(s.events?.some(e=>e.cells?.includes(i))?' effect':'');const piece=document.createElement('span');piece.className='piece';piece.dataset.piece=GameMotion.key(s.board[i])||'';piece.innerHTML=t.html;b.append(piece);b.disabled=!!t.disabled||!run||run.paused||run.status!=='playing'||!!player?.busy;b.tabIndex=i===focus?0:-1;board.append(b);}if(previous!==undefined&&document.activeElement===document.body)board.querySelector(`[data-cell="${Math.min(focus,s.board.length-1)}"]`)?.focus({preventScroll:true});$('message').textContent=run?s.message:'選擇關卡後按開始。每個目標都必須完成。';$('pause').textContent=s.paused?'繼續':'暫停';$('pause').disabled=!run||(!player?.busy&&run.status!=='playing');$('shuffle').disabled=!!player?.busy||!run||s.paused||s.status!=='playing'||s.shuffleLeft<=0;$('end').disabled=!run||s.mode==='campaign'||s.status!=='playing';$('records').textContent='手動完成 '+Object.keys(profile.manual).length+' 關；輔助完成 '+Object.keys(profile.assisted).length+' 關；最高分 '+(profile.best||0)+'。';;let visible=!player?.busy&&(!run||s.paused||s.status!=='playing'),title=!run?'準備好了嗎？':s.paused?'已暫停':s.status==='won'?'任務完成':s.status==='ended'?'本局完成':'再試一次',text=!run?l.intendedDecision:s.paused?'時間不會偷偷前進。繼續後再作下一步決定。':s.message,button=!run?'開始遊戲':s.paused?'繼續遊戲':'重玩本關';;$('overlay').hidden=!visible;$('overlayTitle').textContent=title;$('overlayText').textContent=text;$('overlayAction').textContent=button;$('hint').disabled=!!player?.busy||!run||run.paused;document.querySelectorAll('[data-dir]').forEach(b=>b.disabled=!!player?.busy||!run||run.paused||run.status!=='playing');renderHUD(s);}
function selectCell(i){if(player?.busy||!run||run.paused||run.status!=='playing'||!run.board[i])return;focus=i;selected=[i];;render();}
function focusCell(i,quiet=false){focus=Math.max(0,Math.min((run||preview()).board.length-1,i));board.querySelector(`[data-cell="${focus}"]`)?.focus(quiet?{preventScroll:true}:undefined);}
board.addEventListener('click',e=>{if(suppressClick){suppressClick=false;return;}const b=e.target.closest('[data-cell]');if(b)selectCell(+b.dataset.cell);});
board.addEventListener('keydown',e=>{const s=run||preview(),i=+(e.target.closest('[data-cell]')?.dataset.cell??focus);if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();let x=i%s.w,y=Math.floor(i/s.w);if(e.key==='ArrowLeft')x=Math.max(0,x-1);if(e.key==='ArrowRight')x=Math.min(s.w-1,x+1);if(e.key==='ArrowUp')y=Math.max(0,y-1);if(e.key==='ArrowDown')y=Math.min(s.h-1,y+1);focusCell(y*s.w+x);}else if(e.key==='Enter'){e.preventDefault();selectCell(i);}else if(e.key==='Escape'){clearInput();render();}else if(['w','a','s','d'].includes(e.key.toLowerCase())){e.preventDefault();const k=e.key.toLowerCase(),p=selected[0]??i;act({type:'shift',axis:['a','d'].includes(k)?'row':'col',line:['a','d'].includes(k)?Math.floor(p/run.w):p%run.w,dir:['a','w'].includes(k)?-1:1});}});
board.addEventListener('pointerdown',e=>{if(player?.busy||pointer||!run||run.paused||run.status!=='playing')return;const b=e.target.closest('[data-cell]');if(!b)return;pointer={id:e.pointerId,start:+b.dataset.cell,x:e.clientX,y:e.clientY,axis:null,last:+b.dataset.cell,drag:false};board.setPointerCapture?.(e.pointerId);});
board.addEventListener('pointermove',e=>{if(!pointer||e.pointerId!==pointer.id)return;const dx=e.clientX-pointer.x,dy=e.clientY-pointer.y;if(Math.hypot(dx,dy)>14){pointer.drag=true;if(!pointer.axis)pointer.axis=Math.abs(dx)>Math.abs(dy)?'row':'col';}const hit=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-cell]');if(hit)pointer.last=+hit.dataset.cell;});
board.addEventListener('pointerup',e=>{if(!pointer||e.pointerId!==pointer.id)return;const p=pointer;pointer=null;suppressClick=true;if(!p.drag){selectCell(p.start);}else{const dx=e.clientX-p.x,dy=e.clientY-p.y;act({type:'shift',axis:p.axis,line:p.axis==='row'?Math.floor(p.start/run.w):p.start%run.w,dir:(p.axis==='row'?dx:dy)>0?1:-1});};try{board.releasePointerCapture(e.pointerId)}catch(err){};});
board.addEventListener('pointercancel',e=>{if(pointer&&e.pointerId!==pointer.id)return;pointer=null;selected=[];suppressClick=true;render();});board.addEventListener('lostpointercapture',()=>{pointer=null;});
$('start').onclick=start;$('restart').onclick=start;$('overlayAction').onclick=()=>{if(!run||run.status!=='playing')start();else if(run.paused)act({type:'resume'});};$('level').onchange=()=>{runEpoch++;settleAnimation(false);run=null;match=null;clearInput();resetRecap();render();};$('mode').onchange=()=>{runEpoch++;settleAnimation(false);run=null;match=null;clearInput();resetRecap();render();};$('pause').onclick=()=>{clearInput();act({type:run.paused?'resume':'pause'});};$('hint').onclick=()=>act({type:'hint'});$('shuffle').onclick=()=>act({type:'shuffle'});$('end').onclick=()=>act({type:'end'});document.querySelectorAll('[data-dir]').forEach(b=>b.onclick=()=>{if(!run)return;const d=b.dataset.dir,i=selected[0]??focus;act({type:'shift',axis:['left','right'].includes(d)?'row':'col',line:['left','right'].includes(d)?Math.floor(i/run.w):i%run.w,dir:['left','up'].includes(d)?-1:1});});
function pause(){settleAnimation(false);clearInput();if(run&&run.status==='playing'&&!run.paused)act({type:'pause'});else render();}window.addEventListener('blur',pause);document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});window.addEventListener('storage',e=>{if(store.external(e))pause();});
for(const key of ['reduced','contrast','sound']){$(key).checked=!!options[key];$(key).onchange=()=>{settleAnimation(false);options[key]=$(key).checked;document.body.classList.toggle('reduced',!!options.reduced);document.body.classList.toggle('contrast',!!options.contrast);store.write('options',options);render();};}document.body.classList.toggle('reduced',!!options.reduced||matchMedia('(prefers-reduced-motion:reduce)').matches);document.body.classList.toggle('contrast',!!options.contrast);
$('export').onclick=()=>{const data={version:1,game:SLUG,profile,options,run:run?E.serialize(run):null,match:null};const url=URL.createObjectURL(new Blob([JSON.stringify(data)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=SLUG+'-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};$('import').onclick=()=>{pause();$('importFile').click();};$('importFile').onchange=async()=>{const epoch=runEpoch;try{const f=$('importFile').files[0];if(!f||f.size>2000000)throw Error();const b=JSON.parse(await f.text());if(epoch!==runEpoch)return;if(b.version!==1||b.game!==SLUG||!validProfile(b.profile))throw Error();const candidate=b.run?E.deserialize(b.run,levels):null;runEpoch++;settleAnimation(false);profile=b.profile;run=candidate;match=null;;if(run){run=E.applyAction(run,{type:run.status==='playing'?'pause':'resume'}).state;$('level').value=run.levelId;$('mode').value=run.mode;}clearInput();resetRecap(true);render();save();$('saveNotice').textContent='備份已匯入，請檢查關卡與紀錄後繼續。';}catch(e){if(epoch!==runEpoch)return;$('saveNotice').textContent='備份格式或版本不符，目前進度未更改。';}};
$('reset').onclick=()=>{pause();$('resetDialog').showModal();};$('cancelReset').onclick=()=>$('resetDialog').close();$('confirmReset').onclick=()=>{runEpoch++;settleAnimation(false);profile={version:1,manual:{},assisted:{},best:0};run=null;match=null;store.write('profile',profile);store.write('run',null);clearInput();resetRecap();$('resetDialog').close();render();};
player=GameAnimator({board,renderer:R,renderState:s=>{displayState=s;render(true);},updateHUD:renderHUD,reduced:()=>!!options.reduced||matchMedia('(prefers-reduced-motion:reduce)').matches,onFinish:()=>{displayState=null;$('motionTitle').textContent='這一步已完成';$('motionMeta').textContent=run?.message||'準備下一步';render();if(run?.status==='playing'&&!run.paused)focusCell(focus,true);sound();}});$('skipMotion').onclick=()=>{settleAnimation(false);$('motionTitle').textContent='已顯示這一步的完整結果';$('motionMeta').textContent='可在本步紀錄查看各波消除。';render();};for(const event of ['pagehide','popstate'])window.addEventListener(event,()=>{pause();save();});window.addEventListener('resize',()=>{if(player.busy){settleAnimation(false);render();}});
try{const saved=store.read('run',null);if(saved?.state){run=E.deserialize(saved.state,levels);match=null;;run=E.applyAction(run,{type:run.status==='playing'?'pause':'resume'}).state;$('level').value=run.levelId;$('mode').value=saved.mode||run.mode;}}catch(e){$('saveNotice').textContent='這份進度無法繼續，原存檔仍保留。請開始安全新局。';run=null;match=null;}resetRecap(true);render();window.GameDebug=Object.freeze({snapshot:()=>run?JSON.parse(E.serialize(run)):null,profile:()=>JSON.parse(JSON.stringify(profile)),match:()=>match?JSON.parse(JSON.stringify(match)):null,animation:()=>player.snapshot()});
})();
