'use strict';const assert=require('node:assert/strict'),E=require('./engine.js');
function run(){let names=[],ai={},selfPlay=[];function test(name,fn){fn();names.push(name)}const replay=moves=>moves.reduce((s,m)=>E.apply(s,m),E.create());
test('initial 7-by-6 board and gravity',()=>{let s=E.create();assert.equal(s.board.length,42);assert.equal(E.legal(s).length,7);s=E.apply(s,2);assert.equal(s.board[37],1);assert.equal(s.turn,-1);s=E.apply(s,2);assert.equal(s.board[30],-1);assert.equal(s.last,30)});
test('full column and illegal moves rejected',()=>{let s=replay([0,0,0,0,0,0]);assert(!E.legal(s).includes(0));for(const m of [0,-1,7,1.2,null])assert.throws(()=>E.apply(s,m))});
test('horizontal, vertical and both diagonals',()=>{for(const ms of [[0,6,1,6,2,5,3],[0,1,0,1,0,1,0],[0,1,1,2,3,2,2,3,4,3,3],[6,5,5,4,3,4,4,3,2,3,3]]){let s=replay(ms),end=E.outcome(s);assert.equal(end.winner,1);assert.equal(end.cells.length,4);assert.equal(E.legal(s).length,0);assert.throws(()=>E.apply(s,4))}});
const draw=[5,2,0,3,2,6,3,4,1,5,5,3,6,1,3,0,0,3,3,5,6,2,4,5,5,2,2,4,1,4,4,4,0,2,6,0,0,6,6,1,1,1];test('legal 42-turn draw replay',()=>assert.deepEqual(E.outcome(replay(draw)),{winner:0,reason:'full',cells:[]}));
for(const difficulty of ['easy','normal','hard']){let win=E.chooseMove(replay([0,6,1,6,2,5]),difficulty,{timeMs:80}),block=E.chooseMove(replay([0,6,1,6,2]),difficulty,{timeMs:80}),start=E.chooseMove(E.create(),difficulty,{timeMs:180});assert.equal(win.move,3);assert.equal(block.move,3);assert(E.legal(E.create()).includes(start.move));assert(start.depth>0);ai[difficulty]={legal:true,immediateWin:true,immediateBlock:true,openingDepth:start.depth,openingNodes:start.nodes,maxDepth:E.LIMITS[difficulty].depth};}
test('difficulty search budgets and depths differ',()=>{assert(E.LIMITS.easy.depth<E.LIMITS.normal.depth);assert(E.LIMITS.normal.depth<E.LIMITS.hard.depth);assert(E.LIMITS.easy.ms<E.LIMITS.normal.ms&&E.LIMITS.normal.ms<E.LIMITS.hard.ms);assert.equal(ai.easy.openingDepth,2);assert(ai.normal.openingDepth>2);assert(ai.hard.openingDepth>2)});
for(let seed=1;seed<=6;seed++){let s=E.create(),moves=[],levels=['easy','normal','hard'];while(!E.outcome(s)){let d=levels[(s.ply+seed)%3],pick=E.chooseMove(s,d,{timeMs:12,maxDepth:d==='easy'?2:4,seed:seed*123+s.ply});assert(E.legal(s).includes(pick.move));let before=JSON.stringify(s);let next=E.apply(s,pick.move);assert.equal(JSON.stringify(s),before);s=next;moves.push(pick.move);assert(moves.length<=42)}selfPlay.push({seed,plies:s.ply,result:E.outcome(s),legalEveryTurn:true})}
return{passed:true,rules:{count:names.length,names},ai,selfPlay,drawFixture:draw}}
if(require.main===module){let r=run();require('node:fs').writeFileSync(__dirname+'/rules-report.json',JSON.stringify(r,null,2)+'\n');console.log('Connect Four rules / AI passed:',r.rules.count,'fixtures;',r.selfPlay.length,'seeded matches')}module.exports={run};
