/* Starweave Mage • original deterministic simulation. No dependencies. */
(function (root, factory) { const api=factory(); if(typeof module==='object'&&module.exports)module.exports=api; else root.Starweave=api; })(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const VERSION=1, BAG_SIZE=18, BASKET_LIMIT=2000, MAX_LEVEL=999, MAX_DEPTH=9999;
const SLOTS=['wand','hat','robe','charm','boots','ring'];
const SLOT_NAMES={wand:'法杖',hat:'法帽',robe:'長袍',charm:'護符',boots:'短靴',ring:'戒指'};
const RARITIES={common:{name:'樸素',factor:1,color:'#9faead'},magic:{name:'魔法',factor:1.3,color:'#68bcdc'},rare:{name:'稀有',factor:1.7,color:'#f0c66d'},epic:{name:'史詩',factor:2.2,color:'#bf98e8'},mythic:{name:'星耀',factor:2.9,color:'#ef9c9a'}};
const BIOMES=[{name:'薄荷林徑',subtitle:'葉影之間，第一顆星光',type:'forest',enemy:'slime',elite:'苔冠巨團'},{name:'月傘洞窟',subtitle:'跟著發亮的小蘑菇',type:'cave',enemy:'mushroom',elite:'月傘長老'},{name:'霜鈴遺跡',subtitle:'古老的鐘聲凍在風裡',type:'ice',enemy:'golem',elite:'霜晶守衛'},{name:'琥珀曠野',subtitle:'暖風捲起金色的塵土',type:'wild',enemy:'bat',elite:'琥珀風獸'},{name:'星夜書庫',subtitle:'那些還沒讀完的冒險',type:'library',enemy:'wisp',elite:'迷途書靈'}];
const SKILLS={fire:{name:'絨火彈',icon:'✹',level:1,max:10,cost:9,cooldown:3.6,color:'#ee9879',description:'火球爆開，主目標與附近敵人一起受傷。'},ice:{name:'霜花環',icon:'❄',level:3,max:10,cost:15,cooldown:7,color:'#83d7e3',description:'冰晶波掃過全場，敵人移動與攻擊減速 45%。'},shield:{name:'星紗護罩',icon:'◇',level:4,max:10,cost:17,cooldown:10,color:'#bea3ef',description:'受傷時自動織起護罩，先吸收接下來的傷害。'},lightning:{name:'跳跳雷光',icon:'ϟ',level:5,max:10,cost:19,cooldown:6,color:'#f4d776',description:'雷光在最多三名敵人之間彈跳。'},meteor:{name:'晚安流星',icon:'☄',level:8,max:10,cost:27,cooldown:11,color:'#efa4c2',description:'星星落下，對全場造成大量傷害。'}};
const ATTRS={int:{name:'智力',description:'每點 +2 法力強度、+2 魔力'},vit:{name:'體質',description:'每點 +14 生命、+1 護甲'},focus:{name:'專注',description:'每點 +3 魔力、+0.16 魔力回復／秒'},luck:{name:'靈巧',description:'每點 +0.5% 暴擊率、+0.3% 閃避率'}};
const AFFIX_NAMES=['星火','晨露','守望','月影'];
function clamp(n,a,b){return Math.max(a,Math.min(b,n));} function round(n){return Math.round(n*10)/10;}
function rand(s){let x=s.rng>>>0;x^=x<<13;x^=x>>>17;x^=x<<5;s.rng=x>>>0||1;return s.rng/4294967296;}
function log(s,text,kind='info'){s.logs.unshift({text,kind,time:s.time});if(s.logs.length>45)s.logs.length=45;s.revision++;}
function effect(s,x,y,kind,text,color){s.effects.push({x,y,kind,text:text||'',color:color||'#fff',life:1.1,maxLife:1.1});if(s.effects.length>90)s.effects.splice(0,s.effects.length-90);}
function xpNeed(level){return Math.floor(35+level*20+Math.pow(level,1.8)*7);}
function itemStats(item){if(!item)return {power:0,hp:0,mana:0,armor:0,regen:0,crit:0};const q=RARITIES[item.rarity].factor,v=(3+item.level*1.75)*q*(.9+item.roll/50000),m=1+.08*item.enhance;const a={power:0,hp:0,mana:0,armor:0,regen:0,crit:0};
if(item.slot==='wand')a.power=v*1.65;else if(item.slot==='robe'){a.hp=v*4;a.armor=v*.6;}else if(item.slot==='hat'){a.mana=v*2;a.power=v*.4;}else if(item.slot==='charm'){a.hp=v*2;a.power=v*.65;}else if(item.slot==='boots'){a.hp=v*1.5;a.armor=v*.75;}else{a.power=v*.8;a.mana=v;}
if(item.affix===0)a.power+=v*.35;else if(item.affix===1){a.mana+=v;a.regen+=v*.025;}else if(item.affix===2){a.hp+=v*1.8;a.armor+=v*.2;}else a.crit+=.004*q;
for(const k of ['power','hp','mana','armor','regen'])a[k]=round(a[k]*m);return a;}
function itemPower(item){const a=itemStats(item);return Math.round(a.power*3+a.hp*.22+a.mana*.3+a.armor*1.5+a.regen*8+a.crit*300);}
function enhanceCost(item){return item.enhance>=10?null:Math.round((12+5*item.level)*Math.pow(1.55,item.enhance));}
function sellValue(item){let spent=0;for(let i=0;i<item.enhance;i++)spent+=Math.round((12+5*item.level)*Math.pow(1.55,i));return Math.floor((8+item.level*4)*RARITIES[item.rarity].factor+spent*.25);}
function itemName(item){return `${AFFIX_NAMES[item.affix]}${SLOT_NAMES[item.slot]}`;}
function stats(s){const a=s.attrs,o={maxHp:110+(s.level-1)*13+a.vit*14,maxMana:48+(s.level-1)*3+a.int*2+a.focus*3,power:11+(s.level-1)*2.2+a.int*2,armor:3+(s.level-1)*.75+a.vit,regen:3.3+a.focus*.16,crit:Math.min(.45,.06+a.luck*.005),dodge:Math.min(.25,a.luck*.003),speed:108};for(const item of Object.values(s.equipment)){const z=itemStats(item);o.maxHp+=z.hp;o.maxMana+=z.mana;o.power+=z.power;o.armor+=z.armor;o.regen+=z.regen;o.crit+=z.crit;}o.crit=Math.min(.5,o.crit);for(const k of ['maxHp','maxMana','power','armor','regen'])o[k]=round(o[k]);return o;}
function makeItem(s,level,slot,rarity){let r=rand(s);rarity=rarity||(r<.52?'common':r<.81?'magic':r<.95?'rare':r<.994?'epic':'mythic');return {id:'g'+s.nextId++,level:clamp(Math.round(level),1,MAX_DEPTH),slot:slot||SLOTS[Math.floor(rand(s)*SLOTS.length)],rarity,roll:Math.floor(rand(s)*10001),affix:Math.floor(rand(s)*4),enhance:0,locked:false};}
function create(seed){const s={version:VERSION,rng:(seed>>>0)||Math.floor(Math.random()*4294967294)+1,time:0,revision:0,nextId:1,level:1,xp:0,gold:0,attrs:{int:0,vit:0,focus:0,luck:0},attrPoints:0,skillPoints:0,skills:{fire:1,ice:0,shield:0,lightning:0,meteor:0},equipment:{},bag:[],basket:[],depth:1,frontier:1,encounter:0,mode:'camp',modeTime:0,failures:0,farmRemaining:0,player:{x:125,y:310,hp:110,mana:48,shield:0,face:1},enemies:[],projectiles:[],effects:[],pickups:[],cooldowns:{basic:0,fire:0,ice:0,shield:0,lightning:0,meteor:0},logs:[],metrics:{kills:0,elites:0,drops:0,retreats:0,areas:0,sold:0,earned:0,casts:0},settings:{reducedMotion:false,sound:false},lastLoot:'冒險自動開始。坐好，讓星星帶路。'};
s.equipment.wand=makeItem(s,1,'wand','common');s.equipment.robe=makeItem(s,1,'robe','common');const z=stats(s);s.player.hp=z.maxHp;s.player.mana=z.maxMana;log(s,'星絨法師出發了！你只需要決定如何成長。','story');return s;}
function addItem(s,item){s.bag.push(item);if(s.bag.length>BAG_SIZE){let candidates=s.bag.filter(i=>!i.locked);candidates.sort((a,b)=>itemPower(a)-itemPower(b)||sellValue(a)-sellValue(b)||a.id.localeCompare(b.id));let worst=candidates[0]||item;s.bag.splice(s.bag.indexOf(worst),1);s.basket.push(worst);s.metrics.drops++;}if(s.basket.length>=BASKET_LIMIT){s.mode='blocked';log(s,'儲物籃已達 2,000 件，本場戰利品全部保留；出售或取回後繼續。','warn');}return true;}
function gainXp(s,amount){s.xp+=Math.max(0,Math.floor(amount));while(s.level<MAX_LEVEL&&s.xp>=xpNeed(s.level)){s.xp-=xpNeed(s.level);s.level++;s.attrPoints+=3;s.skillPoints++;const z=stats(s);s.player.hp=Math.min(z.maxHp,s.player.hp+z.maxHp*.22);s.player.mana=z.maxMana;effect(s,s.player.x,s.player.y-32,'level','LEVEL UP','#ffdf8b');log(s,`升到 Lv.${s.level}！獲得 3 屬性點與 1 技能點。`,'level');}if(s.level>=MAX_LEVEL)s.xp=0;}
function spawn(s){s.enemies=[];s.projectiles=[];const d=s.depth,b=BIOMES[(d-1)%5],boss=s.encounter===3;const count=boss?3:2+(d>2?1:0);for(let i=0;i<count;i++){const elite=boss&&i===0,type=elite?b.enemy:(i===count-1&&d>1?'wisp':b.enemy),hp=Math.round((21+12*d+Math.pow(d,2)*5)*(elite?3.2:1)*(type==='golem'?1.2:1)),ranged=type==='wisp'||type==='bat';s.enemies.push({id:'e'+s.nextId++,x:630+rand(s)*190,y:175+i*85+rand(s)*35,hp,maxHp:hp,type,elite,name:elite?b.elite:'',attack:(3.2+d*1.9+Math.pow(d,1.95)*.8)*(elite?1.65:1),speed:(type==='bat'?65:type==='golem'?32:44)*(elite?.85:1),range:ranged?270:52,timer:1.3+rand(s),windup:0,slow:0,hit:0,tx:0,ty:0});}s.mode='travel';s.modeTime=0;}
function move(a,x,y,speed,dt){const dx=x-a.x,dy=y-a.y,d=Math.hypot(dx,dy);if(d<1)return true;const v=Math.min(d,speed*dt);a.x+=dx/d*v;a.y+=dy/d*v;if('face'in a)a.face=dx<0?-1:1;return d<speed*dt+2;}
function retreat(s){s.player.hp=Math.max(1,s.player.hp);s.mode='retreat';s.modeTime=0;s.projectiles=[];s.enemies=[];s.pickups=[];s.player.shield=0;s.metrics.retreats++;s.failures++;if(s.failures>=2){s.farmRemaining=Math.min(12,2+s.failures);const safer=Math.max(1,Math.min(s.depth-1,s.frontier-2-Math.floor((s.failures-2)/2)));s.depth=safer;s.encounter=0;}log(s,s.failures>=2?`先回營地休息，再到深度 ${s.depth} 安全練功 ${s.farmRemaining} 場。`:'有點勉強！先退回營地，補滿生命再來。','retreat');}
function damage(s,e,value,kind,z){if(e.hp<=0)return;const critical=rand(s)<z.crit;const amount=Math.max(1,Math.round(value*(critical?1.65:1)));e.hp-=amount;e.hit=.2;effect(s,e.x,e.y-25,'hit',(critical?'✦ ':'')+amount,critical?'#ffdb8c':SKILLS[kind]?.color||'#faf8ed');if(e.hp<=0){s.metrics.kills++;if(e.elite)s.metrics.elites++;const gold=Math.round((3+s.depth*2)*(e.elite?4:1));s.gold+=gold;s.metrics.earned+=gold;gainXp(s,(9+s.depth*5)*(e.elite?3:1));s.pickups.push({id:'p'+s.nextId++,x:e.x,y:e.y,kind:'gold',label:'+'+gold,color:'#f4d47f'});if(e.elite||rand(s)<.48){const item=makeItem(s,s.depth+(e.elite?1:0));addItem(s,item);s.pickups.push({id:item.id,x:e.x+12,y:e.y+12,kind:'item',label:itemName(item),color:RARITIES[item.rarity].color});s.lastLoot=`${RARITIES[item.rarity].name} ${itemName(item)} · iLv.${item.level}`;log(s,`拾取 ${s.lastLoot}`,'loot');}effect(s,e.x,e.y,'burst','',RARITIES.common.color);}}
function cast(s,kind,target,z){const rank=s.skills[kind]||1,def=SKILLS[kind];if(kind!=='spark'){s.player.mana-=def.cost;s.cooldowns[kind]=def.cooldown;s.metrics.casts++;}if(kind==='shield'){s.player.shield=Math.round(z.maxHp*(.17+rank*.035)+z.power*.4);effect(s,s.player.x,s.player.y,'shield','護罩','#c9b1f0');return;}
if(kind==='ice'){for(const e of s.enemies.filter(e=>e.hp>0)){e.slow=3.5+rank*.2;damage(s,e,z.power*(.55+rank*.12),kind,z);}effect(s,s.player.x,s.player.y,'ring','',def.color);return;}
if(kind==='lightning'){for(const e of s.enemies.filter(e=>e.hp>0).slice(0,3)){s.projectiles.push({x:s.player.x,y:s.player.y-18,tx:e.x,ty:e.y,target:e.id,kind,color:def.color,speed:680,damage:z.power*(.85+rank*.18)});}return;}
if(kind==='meteor'){s.projectiles.push({x:target.x-80,y:-60,tx:target.x,ty:target.y,target:target.id,kind,color:def.color,speed:420,damage:z.power*(1.55+rank*.3)});return;}
s.projectiles.push({x:s.player.x+10*s.player.face,y:s.player.y-20,tx:target.x,ty:target.y,target:target.id,kind,color:kind==='spark'?'#eee0ff':def.color,speed:kind==='spark'?340:270,damage:z.power*(kind==='spark'?.7:1.05+rank*.22)});}
function combat(s,dt,z){const p=s.player,alive=s.enemies.filter(e=>e.hp>0);if(!alive.length){s.mode='loot';s.modeTime=0;s.projectiles=[];return;}const target=alive.slice().sort((a,b)=>Math.hypot(a.x-p.x,a.y-p.y)-Math.hypot(b.x-p.x,b.y-p.y))[0],dist=Math.hypot(target.x-p.x,target.y-p.y);const danger=alive.find(e=>e.windup>0&&e.range<100&&Math.hypot(p.x-e.tx,p.y-e.ty)<88);if(danger)move(p,clamp(p.x-60,300,700),p.y<285?400:180,z.speed,dt);else if(dist>210)move(p,target.x-175,target.y,z.speed,dt);else if(dist<95)move(p,clamp(p.x-90,300,690),clamp(p.y+(target.y>p.y?-65:65),155,430),z.speed*.9,dt);p.x=clamp(p.x,295,790);p.y=clamp(p.y,145,435);p.face=target.x>p.x?1:-1;
if(dist<285){if(s.cooldowns.basic<=0){cast(s,'spark',target,z);s.cooldowns.basic=.9;}const choices=['shield','meteor','ice','lightning','fire'];for(const key of choices){if(s.skills[key]>0&&s.cooldowns[key]<=0&&p.mana>=SKILLS[key].cost&&(key!=='shield'||(p.hp<z.maxHp*.8&&p.shield<=0))){cast(s,key,target,z);break;}}}
for(const e of alive){e.slow=Math.max(0,e.slow-dt);e.hit=Math.max(0,e.hit-dt);const slow=e.slow>0?.55:1;if(e.windup>0){e.windup-=dt*slow;if(e.windup<=0){const hit=e.range>100||Math.hypot(p.x-e.tx,p.y-e.ty)<90;if(hit){if(rand(s)<z.dodge)effect(s,p.x,p.y-35,'hit','閃避','#c4eddd');else {let amount=e.attack*(1-Math.min(.7,z.armor/(z.armor+60+s.depth*4)));const absorbed=Math.min(p.shield,amount);p.shield-=absorbed;amount-=absorbed;p.hp=Math.max(0,p.hp-amount);effect(s,p.x,p.y-30,'hit','−'+Math.ceil(amount),'#f0a4a9');}}e.timer=e.elite?1.8:2.2;}continue;}
const ed=Math.hypot(e.x-p.x,e.y-p.y);if(ed>e.range)move(e,p.x,p.y,e.speed*slow,dt);e.timer-=dt*slow;if(e.timer<=0&&ed<=e.range+10){e.windup=e.elite?1.05:.7;e.tx=p.x;e.ty=p.y;}}
if(p.hp<=z.maxHp*.25)retreat(s);}
function tick(s,delta){if(!Number.isFinite(delta)||delta<=0||s.mode==='blocked')return;s.time+=Math.min(delta,.25);let dt=Math.min(delta,.25),z=stats(s);const p=s.player;p.hp=clamp(p.hp,0,z.maxHp);p.mana=Math.min(z.maxMana,p.mana+z.regen*dt);s.modeTime+=dt;for(const k in s.cooldowns)s.cooldowns[k]=Math.max(0,s.cooldowns[k]-dt);for(const f of s.effects)f.life-=dt;s.effects=s.effects.filter(f=>f.life>0);
if(s.mode==='retreat'){if(move(p,125,310,180,dt)){s.mode='camp';s.modeTime=0;log(s,'回到星燈營地。暖茶會補滿生命與魔力。','camp');}return;}
if(s.mode==='camp'){p.hp=Math.min(z.maxHp,p.hp+z.maxHp*.13*dt);p.mana=Math.min(z.maxMana,p.mana+z.maxMana*.2*dt);if(p.hp>=z.maxHp&&p.mana>=z.maxMana&&s.modeTime>1.8){if(s.basket.length>=BASKET_LIMIT){s.mode='blocked';return;}spawn(s);}return;}
if(s.mode==='travel'){move(p,425,295,z.speed,dt);if(p.x>=410){s.mode='combat';s.modeTime=0;}return;}
if(s.mode==='combat'){combat(s,dt,z);if(s.mode!=='combat')return;for(const b of s.projectiles){const target=s.enemies.find(e=>e.id===b.target);if(target&&target.hp>0){b.tx=target.x;b.ty=target.y;}if(move(b,b.tx,b.ty,b.speed,dt)){b.done=true;if(b.kind==='meteor'){for(const e of s.enemies.filter(e=>e.hp>0))damage(s,e,b.damage,b.kind,z);effect(s,b.tx,b.ty,'burst','',b.color);}else if(target&&target.hp>0){damage(s,target,b.damage,b.kind,z);if(b.kind==='fire'){for(const e of s.enemies.filter(e=>e.hp>0&&e.id!==target.id&&Math.hypot(e.x-target.x,e.y-target.y)<145))damage(s,e,b.damage*.55,b.kind,z);effect(s,b.tx,b.ty,'burst','',b.color);}}}}s.projectiles=s.projectiles.filter(b=>!b.done);s.enemies=s.enemies.filter(e=>e.hp>0);return;}
if(s.mode==='loot'){if(s.pickups.length)move(p,s.pickups[0].x,s.pickups[0].y,z.speed,dt);if(s.modeTime>1.8){s.pickups=[];s.enemies=[];if(s.farmRemaining>0){s.farmRemaining--;if(s.farmRemaining===0){s.depth=s.frontier;s.encounter=0;s.mode='retreat';s.modeTime=0;log(s,`練功完成，補給後再次挑戰深度 ${s.frontier}。`,'story');return;}s.encounter=(s.encounter+1)%3;}else{s.encounter++;if(s.encounter>=4){s.encounter=0;s.depth=Math.min(MAX_DEPTH,s.depth+1);s.frontier=Math.max(s.frontier,s.depth);s.metrics.areas++;s.failures=0;log(s,`走進 ${BIOMES[(s.depth-1)%5].name} · 深度 ${s.depth}`,'story');}}s.mode='advance';s.modeTime=0;}return;}
if(s.mode==='advance'){move(p,865,285,z.speed,dt);if(s.modeTime>1.7){p.x=310;p.y=295;spawn(s);}return;}}
function findItem(s,id){for(const [where,arr]of [['bag',s.bag],['basket',s.basket]]){const item=arr.find(i=>i.id===id);if(item)return {item,where};}for(const [slot,item]of Object.entries(s.equipment))if(item&&item.id===id)return {item,where:'equipment',slot};return null;}
function act(s,type,payload={}){let message='',ok=false;const before=stats(s);if(type==='attribute'){const key=payload.key;if(Object.hasOwn(ATTRS,key)&&s.attrPoints>0){s.attrs[key]++;s.attrPoints--;message=ATTRS[key].name+' +1';ok=true;}}
else if(type==='skill'){const key=payload.key,d=Object.hasOwn(SKILLS,key)?SKILLS[key]:null;if(d&&s.level>=d.level&&s.skillPoints>0&&s.skills[key]<d.max){s.skills[key]++;s.skillPoints--;message=d.name+'提升至 '+s.skills[key]+' 級';ok=true;}}
else if(type==='equip'){const found=findItem(s,payload.id);if(found&&found.where==='bag'){const item=found.item,old=s.equipment[item.slot];s.bag.splice(s.bag.indexOf(item),1);s.equipment[item.slot]=item;if(old)s.bag.push(old);message='穿上 '+itemName(item);ok=true;}}
else if(type==='lock'){const found=findItem(s,payload.id);if(found){found.item.locked=!found.item.locked;message=found.item.locked?'已鎖定，不會溢出或出售':'已解除鎖定';ok=true;}}
else if(type==='stash'){const f=findItem(s,payload.id);if(f&&f.where==='bag'&&!f.item.locked&&s.basket.length<BASKET_LIMIT){s.bag.splice(s.bag.indexOf(f.item),1);s.basket.push(f.item);message='已放入儲物籃';ok=true;}}
else if(type==='retrieve'){const f=findItem(s,payload.id);if(f&&f.where==='basket'){if(s.bag.length>=BAG_SIZE){message='背包已滿，先把一件未鎖定裝備放入儲物籃。';}else{s.basket.splice(s.basket.indexOf(f.item),1);s.bag.push(f.item);message='已取回背包';ok=true;}}}
else if(type==='sell'){const unlocked=s.basket.filter(i=>!i.locked);if(unlocked.length){const value=unlocked.reduce((a,i)=>a+sellValue(i),0);s.basket=s.basket.filter(i=>i.locked);s.gold+=value;s.metrics.sold+=unlocked.length;message=`售出 ${unlocked.length} 件，獲得 ${value} 金幣`;ok=true;}}
else if(type==='enhance'){const f=findItem(s,payload.id);if(f){const cost=enhanceCost(f.item);if(cost!==null&&s.gold>=cost){s.gold-=cost;f.item.enhance++;message=`${itemName(f.item)} 強化至 +${f.item.enhance}`;ok=true;}else message=cost===null?'已達強化上限 +10':'金幣不足';}}
else if(type==='setting'&&['reducedMotion','sound'].includes(payload.key)){s.settings[payload.key]=!!payload.value;ok=true;}
if(ok){const after=stats(s);s.player.hp=Math.min(after.maxHp,type==='equip'?s.player.hp/before.maxHp*after.maxHp:s.player.hp+Math.max(0,after.maxHp-before.maxHp));s.player.mana=Math.min(after.maxMana,type==='equip'?s.player.mana/before.maxMana*after.maxMana:s.player.mana+Math.max(0,after.maxMana-before.maxMana));if(s.mode==='blocked'&&s.basket.length<BASKET_LIMIT){s.mode='retreat';s.modeTime=0;}s.revision++;if(message)log(s,message,'action');}return {ok,message:message||'目前無法執行這個動作'};}
function serialize(s){const keys=['rng','time','nextId','level','xp','gold','attrs','attrPoints','skillPoints','skills','equipment','bag','basket','depth','frontier','encounter','failures','farmRemaining','metrics','settings'];const profile={};for(const k of keys)profile[k]=s[k];profile.hp=s.player.hp;profile.mana=s.player.mana;return JSON.stringify({version:VERSION,savedAt:Date.now(),profile});}
function integer(v,min,max,name){if(!Number.isInteger(v)||v<min||v>max)throw Error('Invalid '+name);return v;}
function finite(v,min,max,name){if(!Number.isFinite(v)||v<min||v>max)throw Error('Invalid '+name);return v;}
function restore(raw){if(typeof raw!=='string'||raw.length>2500000)throw Error('Invalid save');const env=JSON.parse(raw);if(!env||env.version!==VERSION||!env.profile)throw Error('Unsupported save version');const p=env.profile,s=create(1);s.rng=integer(p.rng,1,4294967295,'rng');s.time=finite(p.time,0,1e12,'time');s.level=integer(p.level,1,MAX_LEVEL,'level');s.xp=integer(p.xp,0,xpNeed(s.level)-1,'xp');s.gold=integer(p.gold,0,1e14,'gold');s.nextId=integer(p.nextId,1,1e12,'nextId');s.depth=integer(p.depth,1,MAX_DEPTH,'depth');s.frontier=integer(p.frontier,s.depth,MAX_DEPTH,'frontier');s.encounter=integer(p.encounter,0,3,'encounter');s.failures=integer(p.failures,0,1e6,'failures');s.farmRemaining=integer(p.farmRemaining,0,12,'farmRemaining');for(const k of Object.keys(ATTRS))s.attrs[k]=integer(p.attrs?.[k],0,(s.level-1)*3,'attribute');s.attrPoints=integer(p.attrPoints,0,(s.level-1)*3,'attrPoints');if(Object.values(s.attrs).reduce((a,b)=>a+b,0)+s.attrPoints!==(s.level-1)*3)throw Error('Invalid attribute budget');for(const [k,d]of Object.entries(SKILLS)){s.skills[k]=integer(p.skills?.[k],k==='fire'?1:0,d.max,'skill');if(s.skills[k]>0&&s.level<d.level)throw Error('Invalid skill unlock');}s.skillPoints=integer(p.skillPoints,0,s.level-1,'skillPoints');if(Object.values(s.skills).reduce((a,b)=>a+b,0)+s.skillPoints!==s.level)throw Error('Invalid skill budget');
const ids=new Set();function readItem(i){if(!i||typeof i.id!=='string'||!/^g[1-9]\d{0,12}$/.test(i.id)||ids.has(i.id)||!SLOTS.includes(i.slot)||!Object.hasOwn(RARITIES,i.rarity))throw Error('Invalid item');ids.add(i.id);if(Number(i.id.slice(1))>=s.nextId)throw Error('Invalid item sequence');return {id:i.id,slot:i.slot,rarity:i.rarity,level:integer(i.level,1,MAX_DEPTH,'item level'),roll:integer(i.roll,0,10000,'item roll'),affix:integer(i.affix,0,3,'affix'),enhance:integer(i.enhance,0,10,'enhance'),locked:i.locked===true};}
if(!Array.isArray(p.bag)||p.bag.length>BAG_SIZE||!Array.isArray(p.basket)||p.basket.length>BASKET_LIMIT+4||!p.equipment)throw Error('Invalid inventory');s.equipment={};for(const slot of SLOTS)if(p.equipment[slot]){s.equipment[slot]=readItem(p.equipment[slot]);if(s.equipment[slot].slot!==slot)throw Error('Invalid equipped slot');}s.bag=p.bag.map(readItem);s.basket=p.basket.map(readItem);for(const k in s.metrics)s.metrics[k]=integer(p.metrics?.[k],0,1e13,'metric');s.settings={reducedMotion:p.settings?.reducedMotion===true,sound:p.settings?.sound===true};const z=stats(s);s.player.hp=finite(p.hp,0,z.maxHp,'hp');s.player.mana=finite(p.mana,0,z.maxMana,'mana');s.mode=s.basket.length>=BASKET_LIMIT?'blocked':'camp';s.logs=[];log(s,'歡迎回來！離開時遠征會休息，現在從營地繼續。','story');return s;}
return {VERSION,BAG_SIZE,BASKET_LIMIT,SLOTS,SLOT_NAMES,RARITIES,BIOMES,SKILLS,ATTRS,create,tick,act,stats,itemStats,itemPower,itemName,enhanceCost,sellValue,xpNeed,serialize,restore,findItem,makeItem,addItem};
});
