#!/usr/bin/env node
'use strict';
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict'),crypto=require('node:crypto'),cp=require('node:child_process');
const base=__dirname,html=fs.readFileSync(path.join(base,'../starweave-idle.html'),'utf8'),tests=[];
const hash=file=>crypto.createHash('sha256').update(fs.readFileSync(path.join(base,file))).digest('hex');
function check(name,fn){fn();tests.push(name);}
check('Entry uses traditional Chinese and local-only asset closure',()=>{assert(html.includes('lang="zh-Hant"'));for(const m of html.matchAll(/(?:src|href)="([^"]+)"/g)){const ref=m[1];if(ref.startsWith('../index.html'))continue;assert(!/^https?:|^\/\//.test(ref),'external asset '+ref);assert(fs.existsSync(path.resolve(base,'..',ref.split('?')[0])),'missing '+ref);}for(const file of ['engine.js','ui.js','storage.js','render.js','style.css','art.svg']){const s=fs.readFileSync(path.join(base,file),'utf8');assert(!/https?:\/\/(?!www\.w3\.org)/.test(s),'network URL '+file);}});
check('Catalog binding has isolated slug and original cover',()=>{const c=JSON.parse(fs.readFileSync(path.join(base,'catalog.json')));assert.equal(c.id,'starweave-idle');assert.equal(c.artFile,'games/starweave-idle/art.svg');assert(c.title.includes('星絨法師'));});
check('Production JavaScript syntax passes',()=>{for(const name of ['engine.js','storage.js','render.js','ui.js'])cp.execFileSync(process.execPath,['--check',path.join(base,name)]);});
const out=fs.mkdtempSync(path.join(os.tmpdir(),'starweave-verify-'));const env={...process.env,STARWEAVE_REPORT_DIR:out};
check('Core fixtures and all ten actual-tick progression scenarios pass',()=>{cp.execFileSync(process.execPath,[path.join(base,'verify-engine.cjs'),'matrix','engine'],{env,stdio:'pipe'});const r=JSON.parse(fs.readFileSync(path.join(out,'engine-results.json')));assert.equal(r.sha256,hash('engine.js'));assert.equal(r.tests.length,24);assert(r.tests.every(t=>t.pass));assert.equal(r.simulations.length,10);assert(r.simulations.every(t=>t.saveRoundTrip));});
check('Natural capacity run preserves every item and resumes after exact sale',()=>{cp.execFileSync(process.execPath,[path.join(base,'verify-cap.cjs'),'cap'],{env,stdio:'pipe'});const r=JSON.parse(fs.readFileSync(path.join(out,'cap-results.json')));assert.equal(r.sha256,hash('engine.js'));assert.equal(r.cap.mode,'blocked');assert.equal(r.cap.missingDrops,0);assert(r.saveRoundTrip&&r.exactSaleGold&&r.sale.ok&&!r.duplicateSale.ok&&r.resume.newKills>0);});
check('Two genuine normal-speed 70-second engine runs match current engine',()=>{const r=JSON.parse(fs.readFileSync(path.join(base,'realtime-verification.json')));assert.equal(r.sha256,hash('engine.js'));assert.equal(r.wallClock.length,2);for(const w of r.wallClock){assert(w.realElapsedSeconds>=70);assert(w.simulatedSeconds>=69&&w.simulatedSeconds<=71);assert(w.kills>0);assert.equal(w.browserTest,false);}});
check('UI and storage source lifecycle regressions pass',()=>{cp.execFileSync(process.execPath,[path.join(base,'verify-ui.cjs'),'--report',path.join(out,'ui-independent-results.json')],{env,stdio:'pipe'});const r=JSON.parse(fs.readFileSync(path.join(out,'ui-independent-results.json')));assert.equal(r.counts.failed,0);});
const report={status:'passed',checks:tests.length,tests,engineHash:hash('engine.js'),scope:'Source/static/VM checks and simulated legal actions. Real-time engine evidence is retained separately; actual browser and human playtest are not implied.',reportDirectory:out};
console.log(JSON.stringify(report,null,2));if(process.argv.includes('--report'))fs.writeFileSync(path.join(base,'verification-report.json'),JSON.stringify(report,null,2)+'\n');
