#!/usr/bin/env node
'use strict';
// Offline, independent UI/storage audit: production scripts are evaluated unchanged.
// Usage: node evidence/verify-ui-v3.cjs [--report results.json] [--baseline private-v1-save.json]
// Default migration input is generated, synthetic and portable. --baseline is optional and never copied into reports.
// This mock-DOM harness cannot prove native-browser layout, accessibility tree,
// top-layer behavior, focus trapping, or raster quality. No browser is launched.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict'),crypto=require('node:crypto'),os=require('node:os');
const base=fs.existsSync(path.join(__dirname,'engine.js'))?__dirname:path.resolve(__dirname,'../games/starweave-idle');
const files=['../starweave-idle.html','bestiary.js','engine.js','storage.js','render.js','ui.js','style.css'];
const source=Object.fromEntries(files.map(f=>[f,fs.readFileSync(path.join(base,f),'utf8')]));
const html=source['../starweave-idle.html'],css=source['style.css'];
const baselineArg=process.argv.indexOf('--baseline');if(baselineArg>=0&&!process.argv[baselineArg+1])throw Error('--baseline needs an input path');
const baselineInput=baselineArg<0?null:process.argv[baselineArg+1];
function migrationRaw(){if(baselineInput)return fs.readFileSync(path.resolve(baselineInput),'utf8');const E=require(path.join(base,'engine.js')),s=E.create(53041);s.level=7;s.xp=89;s.attrPoints=18;s.skillPoints=6;s.gold=500;for(let i=0;i<19;i++){const item=E.makeItem(s,1+i%7,E.SLOTS[i%6],Object.keys(E.RARITIES)[i%5]);item.locked=i===3||i===18;s.bag.push(item);}const v=JSON.parse(E.serialize(s));v.version=1;v.profile.basket=v.profile.bag.splice(18);delete v.profile.world;delete v.profile.discoveries;return JSON.stringify(v);}
let assertions=0;const results=[],measurements={};
function ok(v,m){assertions++;assert.ok(v,m);}function eq(a,b,m){assertions++;assert.equal(a,b,m);}
async function test(name,fn){const before=assertions;try{await fn();results.push({name,status:'passed',assertions:assertions-before});}catch(e){results.push({name,status:'failed',assertions:assertions-before,error:e.message,stack:e.stack.split('\n').slice(0,5).join('\n').replaceAll(__dirname,'.').replaceAll(base,'games/starweave-idle')});}}
class Events{constructor(){this.listeners=new Map();}addEventListener(t,f){if(!this.listeners.has(t))this.listeners.set(t,[]);this.listeners.get(t).push(f);}emit(t,extra={}){const e={type:t,target:this,currentTarget:this,defaultPrevented:false,preventDefault(){this.defaultPrevented=true;},stopPropagation(){this.stopped=true;},...extra};const responses=[];for(const f of this.listeners.get(t)||[])responses.push(f(e));e.responses=responses;return e;}}
function context2d(){const stats={calls:0,methods:new Set()};return new Proxy({stats},{get(o,k){if(k in o)return o[k];if(k==='measureText')return t=>({width:String(t).length*6});if(k==='createLinearGradient'||k==='createRadialGradient')return (...a)=>{for(const n of a)assert.ok(Number.isFinite(n),'finite gradient');return{addColorStop(){}};};return (...a)=>{stats.calls++;stats.methods.add(k);if(['ellipse','arc','arcTo','fillRect','clearRect','moveTo','lineTo','translate','rotate','scale','setTransform','bezierCurveTo','quadraticCurveTo'].includes(k))for(const n of a)assert.ok(typeof n==='boolean'||Number.isFinite(n),'finite canvas '+k);};},set(o,k,v){o[k]=v;return true;}});}
function matches(e,s){const compound=s.match(/^([a-z]+)(\[[^\]]+\])$/);if(compound)return e.tagName===compound[1].toUpperCase()&&matches(e,compound[2]);if(s.startsWith('.'))return e.classList.contains(s.slice(1));if(s==='dialog')return e.tagName==='DIALOG';if(s==='dialog[open]')return e.tagName==='DIALOG'&&e.open;if(s==='button')return e.tagName==='BUTTON';if(s.startsWith('#'))return e.id===s.slice(1);const m=s.match(/^\[([\w-]+)(?:="([^"]*)")?\]$/);if(m)return e.getAttribute(m[1])!==null&&(m[2]===undefined||e.getAttribute(m[1])===m[2]);throw Error('Unsupported selector '+s);}
class Element extends Events{
 constructor(tag,doc){super();this.tagName=tag.toUpperCase();this.ownerDocument=doc;this.attributes={};this.children=[];this.parentElement=null;this.style={};this.dataset={};this.hidden=false;this.open=false;this.checked=false;this.disabled=false;this._text='';this._html='';this._classes=new Set();this.classList={add:(...x)=>x.forEach(v=>this._classes.add(v)),remove:(...x)=>x.forEach(v=>this._classes.delete(v)),contains:x=>this._classes.has(x),toggle:(x,force)=>{const v=force===undefined?!this._classes.has(x):!!force;v?this._classes.add(x):this._classes.delete(x);return v;}};}
 setAttribute(k,v){this.attributes[k]=String(v);if(k==='id')this.id=String(v);if(k==='class')this._classes=new Set(String(v).split(/\s+/));if(['hidden','disabled','checked','open'].includes(k))this[k]=true;if(k.startsWith('data-'))this.dataset[k.slice(5).replace(/-([a-z])/g,(_,c)=>c.toUpperCase())]=String(v);}
 getAttribute(k){return this.attributes[k]??null;}removeAttribute(k){delete this.attributes[k];if(['hidden','disabled','checked','open'].includes(k))this[k]=false;}
 get className(){return [...this._classes].join(' ');}set className(v){this.setAttribute('class',v);}
 get isConnected(){let e=this;while(e.parentElement)e=e.parentElement;return e===this.ownerDocument.root;}
 get textContent(){return this._text+this.children.map(e=>e.textContent||'').join('');}set textContent(v){this.detach();this._text=String(v);}
 get innerHTML(){return this._html;}set innerHTML(v){this.detach();this._html=String(v);this._text='';parse(String(v),this.ownerDocument,this);}
 detach(){const focused=this.ownerDocument.activeElement;if(focused&&this.contains(focused)&&focused!==this)this.ownerDocument.activeElement=this.ownerDocument.body;for(const e of this.children)e.parentElement=null;this.children=[];}
 contains(el){for(let e=el;e;e=e.parentElement)if(e===this)return true;return false;}
 append(...nodes){for(const n of nodes){this.children.push(n);n.parentElement=this;}}
 focus(){this.ownerDocument.activeElement=this;}
 showModal(){this.open=true;this.beforeFocus=this.ownerDocument.activeElement;this.ownerDocument.activeElement=this;}
 close(){if(this.open){this.open=false;this.ownerDocument.activeElement=this.beforeFocus?.isConnected?this.beforeFocus:this.ownerDocument.body;this.emit('close');}}
 closest(s){for(let e=this;e;e=e.parentElement)if(matches(e,s))return e;return null;}
 querySelectorAll(s){return walk(this).slice(1).filter(e=>matches(e,s));}querySelector(s){return this.querySelectorAll(s)[0]||null;}
 getContext(){return this.context||(this.context=context2d());}
 click(){if(this.tagName==='A'){this.ownerDocument.downloads.push({href:this.href,download:this.download});return;}return this.ownerDocument.click(this);}
}
function walk(el){return[el,...el.children.flatMap(walk)];}
class Document extends Events{
 constructor(){super();this.root=new Element('root',this);this.body=null;this.activeElement=null;this.hidden=false;this.downloads=[];}
 createElement(t){return new Element(t,this);}getElementById(id){return walk(this.root).find(e=>e.id===id)||null;}
 querySelectorAll(s){return walk(this.root).filter(e=>matches(e,s));}querySelector(s){return this.querySelectorAll(s)[0]||null;}
 click(el){if(el.disabled)return null;let e={type:'click',target:el,defaultPrevented:false,preventDefault(){this.defaultPrevented=true;},stopPropagation(){this.stopped=true;}};for(let n=el;n&&!e.stopped;n=n.parentElement)for(const f of n.listeners.get('click')||[])f(e);if(!e.stopped)for(const f of this.listeners.get('click')||[])f(e);return e;}
}
function parse(text,doc,parent){const stack=[parent],voids=new Set(['area','base','br','col','embed','hr','img','input','link','meta','param','source','track','wbr']);for(const m of text.matchAll(/<!--[\s\S]*?-->|<![^>]*>|<\/?([a-zA-Z][\w-]*)([^>]*)>|([^<]+)/g)){if(m[0].startsWith('<!'))continue;if(m[3]){stack.at(-1)._text+=m[3];continue;}const t=m[1].toLowerCase();if(m[0].startsWith('</')){while(stack.length>1&&stack.pop().tagName.toLowerCase()!==t){}continue;}const el=doc.createElement(t);for(const a of m[2].matchAll(/([\w:-]+)(?:\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s'"=<>`]+)))?/g))el.setAttribute(a[1],a[2]??a[3]??a[4]??'');stack.at(-1).append(el);if(t==='body')doc.body=el;if(!voids.has(t))stack.push(el);}return doc;}
function memory(initial={}){const map=new Map(Object.entries(initial));return{map,sets:[],removes:[],getItem(k){return map.get(k)??null;},setItem(k,v){this.sets.push([k,String(v)]);map.set(k,String(v));},removeItem(k){this.removes.push(k);map.delete(k);}};}
const flush=async()=>{for(let i=0;i<8;i++)await Promise.resolve();};
function webLocks(){let held=false;return{request:async(name,opts,fn)=>{if(held)return fn(null);held=true;try{return await fn({name});}finally{held=false;}},get held(){return held;}};}
async function boot(options={}){
 const doc=new Document();parse(html,doc,doc.root);doc.activeElement=doc.body;doc.hidden=!!options.hidden;
 const window=new Events(),raf=new Map(),timers=new Map(),intervals=new Map(),draws=[],actions=[],steps=[],blobs=new Map();let next=1,ts=100,state=null;
 Object.assign(window,{document:doc,window,devicePixelRatio:options.dpr||1,matchMedia:()=>({matches:!!options.reduced})});const storage=options.storage||memory();Object.defineProperty(window,'localStorage',options.denied?{get(){throw Error('denied');}}:{value:storage});
 class TestDate extends Date{static now(){return 1720000000000+Math.floor(ts);}}
 const seededMath=Object.create(Math);let seed=7;seededMath.random=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};
 const context=vm.createContext({window,document:doc,navigator:{locks:options.locks},console,Date:TestDate,Math:seededMath,CSS:{escape:String},Blob,URL:{createObjectURL:b=>{const u='blob:mock-'+next++;blobs.set(u,b);return u;},revokeObjectURL:u=>blobs.delete(u)},performance:{now:()=>ts},requestAnimationFrame:f=>{const id=next++;raf.set(id,f);return id;},cancelAnimationFrame:id=>raf.delete(id),setTimeout:(fn,delay=0)=>{const id=next++;timers.set(id,{fn,due:ts+delay});return id;},clearTimeout:id=>timers.delete(id),setInterval:(fn,delay)=>{const id=next++;intervals.set(id,{fn,delay,due:ts+delay});return id;},clearInterval:id=>intervals.delete(id)});
 for(const f of ['bestiary.js','engine.js','storage.js','render.js']){vm.runInContext(source[f],context,{filename:f});for(const key of ['StarweaveBestiary','Starweave','StarweaveStorage','StarweaveRender'])if(context[key])window[key]=context[key];}
 const E=window.Starweave,S=window.StarweaveStorage,R=window.StarweaveRender;
 // Observe only state actually used by UI stats/tick/draw, not speculative import fixtures.
 for(const method of ['stats','tick','act']){const raw=E[method];E[method]=(s,...a)=>{state=s;if(method==='tick')steps.push(a[0]);const result=raw(s,...a);if(method==='act')actions.push({type:a[0],payload:a[1],result});return result;};}
 const rawDraw=R.draw;R.draw=(ctx,s,opts)=>{state=s;draws.push({time:s.time,opts});return rawDraw(ctx,s,opts);};
 vm.runInContext(source['ui.js'],context,{filename:'ui.js'});await flush();
 const $=id=>doc.getElementById(id);
 async function tick(n=1,ms=100){for(let i=0;i<n;i++){ts+=ms;for(const [id,t] of [...timers])if(t.due<=ts){timers.delete(id);t.fn();}for(const t of intervals.values())if(t.due<=ts){t.due=ts+t.delay;t.fn();}await flush();const fns=[...raf.values()];raf.clear();for(const fn of fns)fn(ts);await flush();}}
 async function change(id,extra={}){const target=typeof id==='string'?$(id):id;const responses=[];const e={type:'change',target,defaultPrevented:false,preventDefault(){this.defaultPrevented=true;},stopPropagation(){this.stopped=true;},...extra};for(let n=target;n&&!e.stopped;n=n.parentElement)for(const f of n.listeners.get('change')||[])responses.push(f(e));if(!e.stopped)for(const f of doc.listeners.get('change')||[])responses.push(f(e));await Promise.all(responses);await flush();}
 function close(id){doc.click(doc.querySelectorAll('[data-close]').find(e=>e.dataset.close===id));}
 async function visibility(hidden){doc.hidden=hidden;doc.emit('visibilitychange');await flush();}
 function escape(id){const d=$(id),e=d.emit('cancel');if(!e.defaultPrevented)d.close();return e;}
 return{$,doc,window,storage,E,S,R,steps,actions,draws,blobs,raf,context,get state(){return state;},click:id=>doc.click(typeof id==='string'?$(id):id),change,tick,close,escape,visibility,elapse:ms=>{ts+=ms;},get ts(){return ts;}};
}
function grow(h,level=3){const s=h.state;s.level=level;s.attrPoints=(level-1)*3;s.skillPoints=level-1;return s;}
function rawAt(E,{gold=777,level=3}={}){const s=E.create(53);s.gold=gold;s.level=level;s.attrPoints=(level-1)*3;s.skillPoints=level-1;return E.serialize(s);}
function detailButton(h,type){return h.$('itemActions').querySelectorAll('[data-action]').find(e=>e.dataset.action===type);}
function refresh(h){return h.tick(2);}
// Comparison expectations use a separate score calculation over the current full build.
function scoreOracle(E,s,equipment=s.equipment){const z=E.stats(s,equipment);let spell=0,spend=0;for(const key of ['fire','ice','lightning','meteor']){const rank=s.skills[key];if(!rank)continue;const factor={fire:1.05+.22*rank,ice:.55+.12*rank,lightning:.85+.18*rank,meteor:1.55+.3*rank}[key];spell+=factor/E.SKILLS[key].cooldown;spend+=E.SKILLS[key].cost/E.SKILLS[key].cooldown;}const sustained=spend?Math.min(1,(z.regen+z.maxMana/30)/spend):1;const damage=z.power*(.7/.9+spell*sustained)*(1+z.crit*.65),shield=s.skills.shield?z.maxHp*(.17+.035*s.skills.shield)+z.power*.4:0;const effectiveHp=(z.maxHp+shield/2)*(1+Math.min(2.333,z.armor/(60+s.frontier*4)))/(1-z.dodge);return Math.round(damage*8+effectiveHp*.16+z.maxMana*.4);}
function compareOracle(h,item){const current=scoreOracle(h.E,h.state),after=scoreOracle(h.E,h.state,{...h.state.equipment,[item.slot]:item});return{current,after,delta:after-current,better:after>current};}
function inventorySnapshot(items){return JSON.stringify(items.map(i=>Object.fromEntries(Object.keys(i).sort().map(k=>[k,i[k]]))));}
function bagIds(h){return h.$('bagItems').querySelectorAll('[data-item]').map(e=>e.dataset.item);}
function itemTile(h,id){return h.doc.querySelectorAll('[data-item]').find(e=>e.dataset.item===id);}
function checkTile(h,id){return h.$('bagItems').querySelectorAll('[data-select-id]').find(e=>e.dataset.selectId===id);}
function bagAdd(h,count=1){const out=[];for(let n=0;n<count;n++){const item=h.E.makeItem(h.state,1+n%25,h.E.SLOTS[n%h.E.SLOTS.length],Object.keys(h.E.RARITIES)[n%5]);item.locked=n%11===0;h.E.addItem(h.state,item);out.push(item);}return out;}
async function choose(h,id,value){h.$(id).value=value;await h.change(id);}
async function selectItem(h,id,on=true){const checkbox=checkTile(h,id);ok(checkbox,'checkbox rendered '+id);checkbox.checked=on;await h.change(checkbox);}
function assertComparisons(h){eq(h.$('combatPower').textContent,scoreOracle(h.E,h.state).toLocaleString('zh-TW'),'HUD uses whole-build score');for(const id of bagIds(h)){const item=h.E.findItem(h.state,id).item,expected=compareOracle(h,item),tile=itemTile(h,id),card=tile.closest('.item-card');eq(card.classList.contains('is-upgrade'),expected.better,'highlight uses signed whole-build equip result '+id);eq(tile.querySelector('.equip-gain').classList.contains('better'),expected.better,'text marker uses true improvement '+id);const abs=Math.abs(expected.delta).toLocaleString('zh-TW');ok(tile.textContent.includes(abs)||expected.delta===0,'exact comparison magnitude '+id);}}
function assertDetail(h,item){const c=compareOracle(h,item),detail=h.$('itemDetail'),score=detail.querySelector('.item-score');ok(score.textContent.includes(c.current.toLocaleString('zh-TW')),'detail current score');ok(score.textContent.includes(c.after.toLocaleString('zh-TW')),'detail next score');ok(score.textContent.includes('→'),'detail displays explicit current-to-next');eq(score.classList.contains('improves'),c.better,'detail improves class');return c;}

(async()=>{
await test('HTML IDs, local asset references and script order are valid',async()=>{const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(x=>x[1]);eq(ids.length,new Set(ids).size);for(const m of source['ui.js'].matchAll(/\$\('([^']+)'\)/g))ok(ids.includes(m[1]),'HTML ID: '+m[1]);for(const m of html.matchAll(/(?:src|href)="([^"]+)"/g)){if(m[1]==='../index.html?category=simulation')continue;ok(!/^https?:/.test(m[1]));ok(fs.existsSync(path.resolve(base,'..',m[1].split(/[?#]/)[0])),'asset: '+m[1]);}ok(!/\b(?:fetch|XMLHttpRequest|WebSocket)\s*\(/.test(source['ui.js']));const scripts=[...html.matchAll(/<script src="([^"]+)"/g)].map(x=>x[1]);eq(scripts.map(x=>x.split(/[?#]/)[0]).join(','),'starweave-idle/bestiary.js,starweave-idle/engine.js,starweave-idle/storage.js,starweave-idle/render.js,starweave-idle/ui.js');ok(scripts.every(x=>x.endsWith('?v=4')),'shared cache-busted runtime version');ok(html.includes('starweave-idle/style.css?v=4'));ok(!/左上.{0,10}右上.{0,10}右下/.test(html),'No obsolete three-direction tutorial');ok(html.includes('右上方'),'NE entrance guide');});
await test('Zero-input boot advances actual engine and renderer continuously',async()=>{const h=await boot();eq(h.$('pauseOverlay').hidden,true);eq(h.raf.size,1);await h.tick(250);ok(h.state.time>24);ok(h.state.metrics.kills>0,'zero-input kills');ok(h.draws.length>=250);eq(h.raf.size,1);ok(h.$('world').context.stats.calls>1000);eq(h.$('world').width,960);ok(h.storage.map.has(h.S.KEY),'automatic save');});
await test('Manual pause and resume preserve one RAF and freeze simulation',async()=>{const h=await boot();await h.tick(5);h.click('pause');const t=h.state.time;await h.tick(30);eq(h.state.time,t);eq(h.raf.size,1);eq(h.$('pauseOverlay').hidden,false);h.click('pause');await h.tick(3);ok(h.state.time>t);eq(h.$('pauseOverlay').hidden,true);});
await test('Help/settings close and native Escape leave RAF alive and resume correctly',async()=>{for(const [button,id]of [['help','guideDialog'],['settings','settingsDialog']]){const h=await boot();await h.tick(5);h.click(button);const t=h.state.time;eq(h.$(id).open,true);await h.tick(5);eq(h.state.time,t);eq(h.raf.size,1);h.close(id);await h.tick(3);ok(h.state.time>t);h.click(button);const e=h.escape(id);eq(e.defaultPrevented,false);await h.tick(2);eq(h.$(id).open,false);eq(h.raf.size,1);}});
await test('Closing guide preserves prior explicit pause',async()=>{const h=await boot();h.click('pause');h.click('help');h.close('guideDialog');const t=h.state.time;await h.tick(4);eq(h.state.time,t);eq(h.$('pause').textContent,'繼續');});
await test('Item dialog allows continuing auto battle and repeated upgrade transactions stay bounded',async()=>{const h=await boot();h.state.gold=100000;const item=h.state.equipment.wand;h.click(h.doc.querySelectorAll('[data-item]').find(e=>e.dataset.item===item.id));eq(h.$('itemDialog').open,true);const t=h.state.time;await h.tick(3);ok(h.state.time>t);let expected=0;for(let i=0;i<10;i++)expected+=h.E.enhanceCost({...item,enhance:i});const gold=h.state.gold;for(let i=0;i<14;i++)h.click(detailButton(h,'enhance'));eq(item.enhance,10);eq(h.state.gold,gold-expected);eq(detailButton(h,'enhance').disabled,true);eq(h.raf.size,1);});
await test('Attribute/skill eligibility and repeated delegated clicks cannot overspend',async()=>{const h=await boot();eq(h.$('plus-int').disabled,true);eq(h.$('learn-ice').disabled,true);grow(h);await refresh(h);for(let i=0;i<9;i++)h.click('plus-int');eq(h.state.attrs.int,6);eq(h.state.attrPoints,0);eq(h.$('plus-int').disabled,true);h.click('learn-ice');h.click('learn-fire');h.click('learn-fire');eq(h.state.skillPoints,0);eq(h.state.skills.ice,1);eq(h.state.skills.fire,2);eq(h.$('learn-shield').disabled,true);});
await test('Reset Cancel, Escape and repeated Confirm are transactional',async()=>{const h=await boot();h.state.gold=555;h.click('settings');h.click('reset');eq(h.$('confirmDialog').open,true);h.click('cancelConfirm');eq(h.state.gold,555);eq(h.$('settingsDialog').open,true);h.click('reset');h.escape('confirmDialog');eq(h.state.gold,555);h.click('acceptConfirm');eq(h.state.gold,555,'dismissed callback cannot execute');h.click('reset');h.click('acceptConfirm');const seed=h.state.rng;eq(h.state.gold,0);h.click('acceptConfirm');eq(h.state.rng,seed);eq(h.$('settingsDialog').open,false);await h.tick(3);eq(h.raf.size,1);});
await test('Import validation and confirmation protect current progress',async()=>{const h=await boot();h.state.gold=555;h.click('settings');for(const file of [{size:2600000,text:async()=>'{large'}, {size:10,text:async()=>'{corrupt'}, {size:10,text:async()=>JSON.stringify({version:999,profile:{}})}]){h.$('importSave').files=[file];await h.change('importSave');eq(h.state.gold,555);eq(h.$('confirmDialog').open,false);}const raw=rawAt(h.E,{gold:777});h.$('importSave').files=[{size:raw.length,text:async()=>raw}];await h.change('importSave');eq(h.state.gold,555);eq(h.$('confirmDialog').open,true);h.click('cancelConfirm');eq(h.state.gold,555);h.$('importSave').files=[{size:raw.length,text:async()=>raw}];await h.change('importSave');h.click('acceptConfirm');eq(h.state.gold,777);eq(h.state.level,3);eq(h.state.mode,'camp');eq(h.$('settingsDialog').open,false);eq(JSON.parse(h.storage.map.get(h.S.KEY)).profile.gold,777);});
await test('Export downloads current validated save and revokes its blob URL',async()=>{const h=await boot();h.state.gold=234;h.click('exportSave');eq(h.doc.downloads.length,1);const d=h.doc.downloads[0];ok(d.download.endsWith('.json'));const data=await h.blobs.get(d.href).text();eq(h.E.restore(data).gold,234);await h.tick(11);eq(h.blobs.has(d.href),false);});
await test('Visibility hide/resume saves, releases lease, loads fresh camp and never simulates hidden time',async()=>{const h=await boot();await h.tick(13);h.state.gold=654;await h.visibility(true);const t=h.state.time;ok(!h.storage.map.has(h.S.LEASE));await h.tick(300);eq(h.state.time,t);eq(h.raf.size,1);await h.visibility(false);eq(h.state.gold,654);eq(h.state.time,t);eq(h.state.mode,'camp');await h.tick(2);ok(h.state.time>t);});
await test('Pagehide/pageshow preserve RAF, saved progress and prevent elapsed wall-time gains',async()=>{const h=await boot();await h.tick(5);h.state.gold=432;h.window.emit('pagehide');const t=h.state.time;h.elapse(12000);eq(h.state.time,t);h.window.emit('pageshow');await flush();eq(h.state.gold,432);eq(h.state.time,t);await h.tick(3);ok(h.state.time>t);eq(h.raf.size,1);});
await test('Initially background-loaded page does not claim the active writer lease',async()=>{const h=await boot({hidden:true});h.window.emit('pageshow');await flush();eq(h.storage.map.has(h.S.LEASE),false,'hidden initial page must not retain lease');await h.tick(5);eq(h.state.time,0);await h.visibility(false);await h.tick(3);ok(h.state.time>0);});
await test('Blocked storage remains playable and retains temporary progress across visibility changes',async()=>{const h=await boot({denied:true});await h.tick(15);h.state.gold=456;const t=h.state.time;ok(/儲存|保存/.test(h.$('saveStatus').textContent));await h.visibility(true);await h.tick(10);await h.visibility(false);eq(h.state.gold,456,'temporary gold preserved');eq(h.state.time,t,'temporary journey preserved');await h.tick(3);ok(h.state.time>t);});
await test('Quota failure preserves unsaved progress when returning from background',async()=>{const storage=memory(),h=await boot({storage});h.state.gold=123;h.click('pause');h.click('pause');const original=storage.map.get(h.S.KEY);storage.setItem=function(k,v){if(k===h.S.KEY)throw Error('QuotaExceededError');this.map.set(k,String(v));};h.state.gold=999;await h.visibility(true);eq(storage.map.get(h.S.KEY),original);await h.visibility(false);eq(h.state.gold,999,'unsaved progress survives quota failure');});
await test('Corrupt saved bytes are protected, exportable, and temporary progress survives hiding',async()=>{const key='arcade.starweave-idle.save.v1',storage=memory({[key]:'{broken'}),h=await boot({storage});h.state.gold=567;const earnedBefore=h.state.metrics.earned;await h.tick(60);const expectedGold=567+h.state.metrics.earned-earnedBefore;eq(storage.map.get(key),'{broken');eq(h.$('exportOriginal').hidden,false);h.click('exportSave');const live=h.doc.downloads.at(-1);eq(h.E.restore(await h.blobs.get(live.href).text()).gold,expectedGold,'current temporary session exported separately');h.click('exportOriginal');const d=h.doc.downloads.at(-1);eq(await h.blobs.get(d.href).text(),'{broken');ok(d.download.includes('original-recovery'));await h.visibility(true);await h.visibility(false);eq(h.state.gold,expectedGold,'protected temporary session survives');eq(storage.map.get(key),'{broken');});
await test('Waiting tab cannot mutate and takes latest progress after ownership release',async()=>{const storage=memory(),locks=webLocks(),first=await boot({storage,locks}),second=await boot({storage,locks});eq(second.$('pauseOverlay').hidden,false);ok(second.$('autoLabel').textContent.includes('等候'));first.state.gold=987;grow(first);await refresh(first);await first.visibility(true);await second.tick(26);eq(second.state.gold,987);eq(second.state.level,3);eq(second.$('pauseOverlay').hidden,true);h: {const t=second.state.time;await second.tick(3);ok(second.state.time>t);}await second.visibility(true);});
await test('Lease theft event prevents UI transactions and keeps other-game keys untouched',async()=>{const storage=memory({'other-game':'keep'}),h=await boot({storage});grow(h);await refresh(h);const before=h.state.attrs.int;storage.map.set(h.S.LEASE,JSON.stringify({token:'other',until:1720001000000}));h.window.emit('storage',{key:h.S.LEASE});h.click('plus-int');eq(h.state.attrs.int,before);eq(h.$('pauseOverlay').hidden,false);eq(storage.map.get('other-game'),'keep');ok(storage.sets.every(([k])=>[h.S.KEY,h.S.LEASE].includes(k)));});
await test('Changed saved bytes after failed save protect both sessions and export live unsaved progress',async()=>{const storage=memory(),h=await boot({storage});h.state.gold=123;h.click('pause');h.click('pause');const original=storage.map.get(h.S.KEY),set=storage.setItem.bind(storage);let quota=true;storage.setItem=function(k,v){if(quota&&k===h.S.KEY)throw Error('QuotaExceededError');set(k,v);};h.state.gold=999;await h.visibility(true);eq(storage.map.get(h.S.KEY),original);const external=rawAt(h.E,{gold:888});storage.map.set(h.S.KEY,external);quota=false;await h.visibility(false);eq(h.state.gold,999);ok(h.$('storageNotice').textContent.includes('另一分頁已更新'));const goldBefore=h.state.gold,earnedBefore=h.state.metrics.earned;await h.tick(60);const expectedGold=goldBefore+h.state.metrics.earned-earnedBefore;eq(storage.map.get(h.S.KEY),external,'foreign save preserved');h.click('exportSave');const d=h.doc.downloads.at(-1);eq(h.E.restore(await h.blobs.get(d.href).text()).gold,expectedGold);h.click('settings');h.$('importSave').files=[{size:external.length,text:async()=>external}];await h.change('importSave');h.click('acceptConfirm');eq(h.state.gold,888);eq(h.$('storageNotice').textContent.includes('另一分頁已更新'),false);eq(h.E.restore(storage.map.get(h.S.KEY)).gold,888);});
await test('Waiting duplicate-tab export never produces a fabricated fresh-session backup',async()=>{const storage=memory(),locks=webLocks(),a=await boot({storage,locks});a.state.gold=876;a.click('pause');const b=await boot({storage,locks});b.click('settings');b.click('exportSave');if(b.doc.downloads.length===0){ok(b.$('exportSave').disabled||b.$('toast').textContent.length>0,'unavailable export explained');}else{const d=b.doc.downloads.at(-1);eq(b.E.restore(await b.blobs.get(d.href).text()).gold,876,'export actual saved state while waiting');}await a.visibility(true);});
await test('Reset confirmation cannot mutate after losing tab ownership',async()=>{const h=await boot();h.state.gold=654;h.click('settings');h.click('reset');h.storage.map.set(h.S.LEASE,JSON.stringify({token:'other',until:1720001000000}));h.window.emit('storage',{key:h.S.LEASE});const raw=h.storage.map.get(h.S.KEY);h.click('acceptConfirm');eq(h.state.gold,654);eq(h.storage.map.get(h.S.KEY),raw);ok(h.$('toast').textContent.includes('等候'));});
await test('Import confirmation cannot mutate after losing tab ownership',async()=>{const h=await boot();h.state.gold=654;const raw=rawAt(h.E,{gold:999});h.click('settings');h.$('importSave').files=[{size:raw.length,text:async()=>raw}];await h.change('importSave');h.storage.map.set(h.S.LEASE,JSON.stringify({token:'other',until:1720001000000}));h.window.emit('storage',{key:h.S.LEASE});const before=h.storage.map.get(h.S.KEY);h.click('acceptConfirm');eq(h.state.gold,654);eq(h.storage.map.get(h.S.KEY),before);});
await test('Newer file choice wins when older asynchronous import finishes late',async()=>{const h=await boot();h.click('settings');const old=rawAt(h.E,{gold:111}),latest=rawAt(h.E,{gold:222});let complete;h.$('importSave').files=[{size:old.length,text:()=>new Promise(r=>{complete=r;})}];const pending=h.change('importSave');await flush();h.$('importSave').files=[{size:latest.length,text:async()=>latest}];await h.change('importSave');ok(h.$('confirmText').textContent.includes('222'));h.click('acceptConfirm');eq(h.state.gold,222);complete(old);await pending;eq(h.$('confirmDialog').open,false,'obsolete import must not reopen confirmation after newer import accepted');eq(h.state.gold,222);});
await test('Closing settings invalidates an unfinished file read',async()=>{const h=await boot();h.state.gold=321;h.click('settings');const raw=rawAt(h.E,{gold:999});let complete;h.$('importSave').files=[{size:raw.length,text:()=>new Promise(r=>{complete=r;})}];const pending=h.change('importSave');await flush();h.close('settingsDialog');complete(raw);await pending;eq(h.$('confirmDialog').open,false,'dismissed settings must not resurface a deferred import dialog');eq(h.state.gold,321);});
await test('Escape from settings invalidates an unfinished file read',async()=>{const h=await boot();h.state.gold=321;h.click('settings');const raw=rawAt(h.E,{gold:999});let complete;h.$('importSave').files=[{size:raw.length,text:()=>new Promise(r=>{complete=r;})}];const pending=h.change('importSave');await flush();h.escape('settingsDialog');complete(raw);await pending;eq(h.$('confirmDialog').open,false);eq(h.state.gold,321);eq(h.raf.size,1);});
await test('Reset decision invalidates an earlier pending import without stale prompts',async()=>{const h=await boot();h.state.gold=321;h.click('settings');const raw=rawAt(h.E,{gold:999});let complete;h.$('importSave').files=[{size:raw.length,text:()=>new Promise(r=>{complete=r;})}];const pending=h.change('importSave');await flush();h.click('reset');complete(raw);await pending;ok(h.$('confirmTitle').textContent.includes('重新'));h.click('cancelConfirm');eq(h.state.gold,321);});
await test('Original damaged-save export disappears after explicit accepted recovery',async()=>{const key='arcade.starweave-idle.save.v1',storage=memory({[key]:'{broken'}),h=await boot({storage});eq(h.$('exportOriginal').hidden,false);h.click('settings');const raw=rawAt(h.E,{gold:444});h.$('importSave').files=[{size:raw.length,text:async()=>raw}];await h.change('importSave');h.click('acceptConfirm');eq(h.state.gold,444);eq(h.$('exportOriginal').hidden,true);eq(h.E.restore(storage.map.get(key)).gold,444);});
await test('Reduced motion settings take OS preference initially and survive saved settings',async()=>{const h=await boot({reduced:true});eq(h.state.settings.reducedMotion,true);eq(h.$('reducedMotion').checked,true);h.click('settings');h.$('reducedMotion').checked=false;await h.change('reducedMotion');eq(h.state.settings.reducedMotion,false);h.$('sound').checked=true;await h.change('sound');eq(h.state.settings.sound,true);h.close('settingsDialog');await h.tick(3);eq(h.draws.at(-1).opts.reducedMotion,false);});
await test('Keyboard-focused item action survives passive inventory/detail rerender',async()=>{const h=await boot();h.click(h.doc.querySelectorAll('[data-item]')[0]);const button=detailButton(h,'lock');button.focus();eq(h.doc.activeElement,button);h.state.gold+=1;await refresh(h);ok(h.doc.activeElement?.dataset.action==='lock','current item action focus retained after gold/inventory update');});
await test('Import action is reachable from keyboard in source',async()=>{const h=await boot(),input=h.$('importSave'),label=input.parentElement;ok(!input.hidden||label.getAttribute('tabindex')==='0'||h.doc.querySelectorAll('[data-import]').length>0||h.$('importButton'),'file picker has a keyboard-focusable route');});
await test('Responsive and accessibility source safeguards exist',async()=>{for(const pattern of [/@media\(max-width:860px\)/,/@media\(max-width:560px\)/,/focus-visible/,/prefers-reduced-motion/,/100dvh/,/\[hidden\]/])ok(pattern.test(css),'CSS safeguard '+pattern);ok(html.includes('width=device-width'));ok(html.includes('aria-live="polite"'));for(const id of ['guideDialog','settingsDialog','itemDialog','confirmDialog'])ok(new RegExp('<dialog id="'+id+'" aria-labelledby=').test(html),'named native dialog '+id);ok(!html.includes('onclick='));const mobile=css.slice(css.lastIndexOf('@media(max-width:560px)'));for(const pattern of [/\.boss-hud\{left:9px;right:9px;top:9px;/,/\.boss-hud strong\{font-size:12px\}/,/\.boss-hud span,\.boss-hud p\{font-size:9px\}/,/\.boss-hud p\{line-height:1\.4\}/])ok(pattern.test(mobile),'final mobile HUD readability safeguard '+pattern);ok(/\.has-boss \.stage-top\{visibility:hidden\}/.test(css),'ordinary stage labels suppressed while boss HUD is visible');});
await test('Unified backpack controls have no active basket, stash, retrieve, or 18-slot dependencies',async()=>{
 const h=await boot();eq('basket' in h.state,false);eq(h.$('basketItems'),null);eq(h.$('basketMore'),null);eq(h.$('sellAll'),null);
 for(const id of ['bagSlot','bagFilter','bagSort','selectPage','selectUnlocked','clearSelection','sellSelected','bagPrev','bagNext','bagPrevBottom','bagNextBottom'])ok(h.$(id),'new control '+id);
 ok(!/s\.basket|data-action=["'](?:stash|retrieve)|basketLimit|BAG_LIMIT|\/\s*18/.test(source['ui.js']+html),'no old active bag capacity or basket actions');
 h.click(h.doc.querySelectorAll('[data-tab]').find(e=>e.dataset.tab==='bag'));eq(h.$('panel-bag').hidden,false);eq(h.$('panel-growth').hidden,true);eq(h.doc.querySelectorAll('[data-tab]').find(e=>e.dataset.tab==='bag').getAttribute('aria-pressed'),'true');
});
await test('V1 migration checkpoint appears as all 19 unified bag items, 2 worn items and 2 locks',async()=>{
 const raw=migrationRaw(),original=JSON.parse(raw).profile;
 const h=await boot({storage:memory({'arcade.starweave-idle.save.v1':raw})});eq(h.state.bag.length,19);eq(h.$('bagCount').textContent,'19');eq(h.$('bagItems').children.length,19);eq(Object.values(h.state.equipment).filter(Boolean).length,2);eq(h.state.bag.filter(i=>i.locked).length,2);
 eq(h.state.gold,original.gold);eq(h.state.metrics.sold,original.metrics.sold);eq(h.state.bag.map(i=>i.id).join(','),[...original.bag,...original.basket].map(i=>i.id).join(','));
 await choose(h,'bagFilter','locked');eq(bagIds(h).length,2);ok(h.$('bagItems').querySelectorAll('[data-select-id]').every(e=>e.disabled));
 h.click('exportSave');const exportRaw=await h.blobs.get(h.doc.downloads.at(-1).href).text(),v2=JSON.parse(exportRaw);eq(v2.version,3);eq(v2.profile.bag.length,19);eq('basket' in v2.profile,false);eq(h.E.restore(exportRaw).bag.length,19);
 measurements.v1Migration={fixture:baselineInput?'explicit private --baseline input':'generated deterministic synthetic v1 fixture',sha256:crypto.createHash('sha256').update(raw).digest('hex'),unifiedBag:19,worn:2,locked:2,gold:original.gold};
});
await test('Both pager control pairs show exactly 30 cards, bound the last page, and reset for a new filter',async()=>{
 const h=await boot();bagAdd(h,73);await refresh(h);eq(h.$('bagItems').children.length,30);eq(h.$('bagPrev').disabled,true);eq(h.$('bagPrevBottom').disabled,true);eq(h.$('bagPage').textContent,'第 1 / 3 頁');
 const first=bagIds(h);h.click('bagNext');eq(h.$('bagItems').children.length,30);ok(!bagIds(h).some(id=>first.includes(id)));eq(h.$('bagPageBottom').textContent,'第 2 / 3 頁');
 h.click('bagNextBottom');eq(h.$('bagItems').children.length,13);eq(h.$('bagNext').disabled,true);eq(h.$('bagNextBottom').disabled,true);h.click('bagNext');eq(h.$('bagItems').children.length,13);h.click('bagPrevBottom');eq(h.$('bagPage').textContent,'第 2 / 3 頁');h.click('bagPrev');eq(h.$('bagPage').textContent,'第 1 / 3 頁');
 h.click('bagNext');await choose(h,'bagFilter','locked');eq(h.$('bagPage').textContent,'第 1 / 1 頁');eq(bagIds(h).length,7);
});
await test('All sort choices and combined slot, upgrade, unlocked, locked filters reflect current actual items',async()=>{
 const h=await boot();bagAdd(h,94);await refresh(h);const ranks=Object.keys(h.E.RARITIES),sequence=i=>Number(i.id.slice(1));
 const sorts={gain:(a,b)=>compareOracle(h,b).delta-compareOracle(h,a).delta,newest:(a,b)=>sequence(b)-sequence(a),level:(a,b)=>b.level-a.level,rarity:(a,b)=>ranks.indexOf(b.rarity)-ranks.indexOf(a.rarity),value:(a,b)=>h.E.sellValue(b)-h.E.sellValue(a)};
 for(const [sort,cmp] of Object.entries(sorts)){await choose(h,'bagSort',sort);const expected=h.state.bag.slice().sort((a,b)=>cmp(a,b)||sequence(b)-sequence(a)).slice(0,30).map(i=>i.id);eq(bagIds(h).join(','),expected.join(','),'actual '+sort+' order');}
 for(const filter of ['upgrades','unlocked','locked']){await choose(h,'bagFilter',filter);for(const id of bagIds(h)){const i=h.E.findItem(h.state,id).item;ok(filter==='upgrades'?compareOracle(h,i).better:filter==='locked'?i.locked:!i.locked,'filter '+filter);}}
 await choose(h,'bagSlot','hat');for(const id of bagIds(h)){const i=h.E.findItem(h.state,id).item;eq(i.slot,'hat');eq(i.locked,true);}await choose(h,'bagFilter','all');eq(bagIds(h).length,h.state.bag.filter(i=>i.slot==='hat').length);
});
await test('Positive equip highlighting and detail current-to-next use full build rather than item-only power',async()=>{
 const h=await boot();grow(h,100);h.state.attrs.luck=90;h.state.attrPoints-=90;Object.assign(h.state.equipment.wand,{level:1,rarity:'common',roll:5000,affix:3,enhance:0});
 const misleading=h.E.makeItem(h.state,1,'wand','common');Object.assign(misleading,{roll:5000,affix:1,enhance:0});h.E.addItem(h.state,misleading);const better=h.E.makeItem(h.state,15,'wand','mythic');h.E.addItem(h.state,better);await refresh(h);
 ok(h.E.itemPower(misleading)>h.E.itemPower(h.state.equipment.wand),'fixture has higher obsolete item-only power');ok(compareOracle(h,misleading).delta<0,'fixture decreases current whole-build score');assertComparisons(h);
 h.click(itemTile(h,misleading.id));const comparison=assertDetail(h,misleading);eq(h.$('itemDetail').querySelector('.item-score').classList.contains('improves'),false);h.close('itemDialog');h.click(itemTile(h,better.id));ok(assertDetail(h,better).better);measurements.misleadingItem={itemOnlyDelta:h.E.itemPower(misleading)-h.E.itemPower(h.state.equipment.wand),wholeBuildDelta:comparison.delta};
});
await test('HUD, cached highlights and open detail recompute after points, skill, bag enhancement, worn enhancement and equip',async()=>{
 const h=await boot();grow(h,8);h.state.gold=100000;const items=bagAdd(h,18);await refresh(h);assertComparisons(h);const focus=items.find(i=>i.slot==='wand');h.click(itemTile(h,focus.id));let expected=assertDetail(h,focus);const initial=expected.current;
 h.click('plus-int');assertComparisons(h);expected=assertDetail(h,focus);ok(expected.current>initial,'point changes whole-build score');const afterPoint=expected.current;
 h.click('learn-ice');assertComparisons(h);expected=assertDetail(h,focus);ok(expected.current!==afterPoint,'skill changes whole-build score');const beforeEnhance=expected.after;
 h.click(detailButton(h,'enhance'));assertComparisons(h);expected=assertDetail(h,focus);ok(expected.after>beforeEnhance,'candidate enhance affects projected score');h.close('itemDialog');
 const worn=h.state.equipment.wand;h.click(itemTile(h,worn.id));h.click(detailButton(h,'enhance'));assertComparisons(h);h.close('itemDialog');h.click(itemTile(h,focus.id));assertDetail(h,focus);h.click(detailButton(h,'equip'));
 eq(h.state.equipment.wand.id,focus.id);eq(bagIds(h).includes(focus.id),false);eq(h.state.bag.some(i=>i.id===worn.id),true);assertComparisons(h);eq(assertDetail(h,focus).delta,0);eq(detailButton(h,'equip').disabled,true);
});
await test('Checkbox selection survives sort, filters and pages; new arrivals never become automatically selected',async()=>{
 const h=await boot();bagAdd(h,65);await refresh(h);h.click('selectPage');const chosen=h.$('bagItems').querySelectorAll('[data-select-id]').filter(e=>e.checked).map(e=>e.dataset.selectId);eq(chosen.length,h.$('bagItems').querySelectorAll('[data-select-id]').filter(e=>!e.disabled).length);ok(chosen.length>0);
 h.click('bagNext');eq(h.$('bagItems').querySelectorAll('[data-select-id]').filter(e=>e.checked).length,0);await choose(h,'bagSort','newest');await choose(h,'bagFilter','unlocked');
 const firstId=bagIds(h)[0];await selectItem(h,firstId,true);ok(itemTile(h,firstId).closest('.item-card').classList.contains('is-selected'));await selectItem(h,firstId,false);eq(itemTile(h,firstId).closest('.item-card').classList.contains('is-selected'),false);
 h.click('selectUnlocked');const before=h.state.bag.filter(i=>!i.locked).length,arrival=h.E.makeItem(h.state,2,'hat','rare');h.E.addItem(h.state,arrival);await refresh(h);eq(checkTile(h,arrival.id).checked,false);ok(h.$('selectionSummary').textContent.includes('已選 '+before+' 件'));
 h.click('clearSelection');eq(h.$('sellSelected').disabled,true);eq(h.$('clearSelection').disabled,true);
});
await test('Selected sale confirms exact count and value, excludes newly gained items, and never pays twice',async()=>{
 const h=await boot();const items=bagAdd(h,9);await refresh(h);h.click('selectUnlocked');const selected=items.filter(i=>!i.locked),ids=selected.map(i=>i.id),value=selected.reduce((n,i)=>n+h.E.sellValue(i),0),gold=h.state.gold;h.click('sellSelected');
 eq(h.state.gold,gold);eq(h.$('confirmDialog').open,true);ok(h.$('confirmTitle').textContent.includes(String(ids.length)));ok(h.$('confirmText').textContent.includes(value.toLocaleString('zh-TW')));const upgrades=selected.filter(i=>compareOracle(h,i).better).length;if(upgrades)ok(h.$('confirmText').textContent.includes('其中 '+upgrades+' 件穿上後能提升戰力'),'valuable upgrade warning matches selected current build improvements');
 const late=h.E.makeItem(h.state,30,'wand','mythic');h.E.addItem(h.state,late);await refresh(h);h.click('acceptConfirm');eq(h.state.gold,gold+value);eq(h.state.metrics.sold,ids.length);eq(h.state.bag.length,2);ok(h.state.bag.some(i=>i.id===late.id));ok(h.state.bag.some(i=>i.locked));
 const sale=h.actions.filter(a=>a.type==='sell').at(-1);eq(sale.payload.ids.join(','),ids.join(','));eq(h.actions.some(a=>a.type==='sellAll'),false);for(let n=0;n<8;n++){h.click('acceptConfirm');h.click('sellSelected');}eq(h.state.gold,gold+value);eq(h.state.metrics.sold,ids.length);eq(h.$('confirmDialog').open,false);
});
await test('Cancel and Escape destroy pending sale callbacks and preserve selected items',async()=>{
 const h=await boot();bagAdd(h,5);await refresh(h);h.click('selectUnlocked');const gold=h.state.gold,count=h.state.bag.length;
 for(const dismiss of [()=>h.click('cancelConfirm'),()=>h.escape('confirmDialog')]){h.click('sellSelected');eq(h.$('confirmDialog').open,true);dismiss();h.click('acceptConfirm');eq(h.state.gold,gold);eq(h.state.bag.length,count);eq(h.actions.filter(a=>a.type==='sell').length,0);eq(h.raf.size,1);}
});
await test('Single-item sale uses the same exact snapshot confirmation and closes obsolete details after selling',async()=>{
 const h=await boot();const item=h.E.makeItem(h.state,2,'hat','magic');h.E.addItem(h.state,item);await refresh(h);h.click(itemTile(h,item.id));h.click(detailButton(h,'sell-item'));eq(h.$('confirmDialog').open,true);const gold=h.state.gold,value=h.E.sellValue(item);h.click('acceptConfirm');eq(h.state.gold,gold+value);eq(h.E.findItem(h.state,item.id),null);eq(h.$('itemDialog').open,false);h.click('acceptConfirm');eq(h.state.gold,gold+value);
});
await test('Locked and worn items are excluded, equipped selections prune, and locks revalidate before sale',async()=>{
 const h=await boot();const items=bagAdd(h,4);await refresh(h);const locked=items[0],item=items[1];eq(checkTile(h,locked.id).disabled,true);h.click(itemTile(h,locked.id));eq(detailButton(h,'sell-item').disabled,true);h.close('itemDialog');
 h.click('selectUnlocked');h.click(itemTile(h,item.id));h.click(detailButton(h,'equip'));eq(h.state.equipment[item.slot].id,item.id);eq(detailButton(h,'sell-item'),undefined);h.close('itemDialog');h.click('sellSelected');const rawCount=h.state.bag.length,gold=h.state.gold;
 const pending=items[2];h.E.act(h.state,'lock',{id:pending.id});h.click('acceptConfirm');eq(h.state.gold,gold);eq(h.state.bag.length,rawCount);ok(h.$('toast').textContent.includes('改變'));eq(h.state.equipment[item.slot].id,item.id);
 h.click('clearSelection');h.click('selectUnlocked');h.click('sellSelected');h.click('acceptConfirm');ok(h.E.findItem(h.state,locked.id));ok(h.E.findItem(h.state,pending.id));eq(h.state.equipment[item.slot].id,item.id);ok(h.state.bag.every(i=>i.locked));
});
await test('Changed item enhancement price rejects an old sale rather than silently selling at a changed value',async()=>{
 const h=await boot();h.state.gold=10000;const items=bagAdd(h,3);await refresh(h);h.click('selectUnlocked');h.click('sellSelected');h.E.act(h.state,'enhance',{id:items[1].id});const gold=h.state.gold,count=h.state.bag.length;h.click('acceptConfirm');eq(h.state.gold,gold);eq(h.state.bag.length,count);ok(h.$('toast').textContent.includes('改變'));eq(h.actions.filter(a=>a.type==='sell').length,0);
});
await test('Sale loses authority immediately after lease theft and cannot overwrite another session',async()=>{
 const h=await boot();bagAdd(h,4);await refresh(h);h.click('selectUnlocked');h.click('sellSelected');const count=h.state.bag.length,gold=h.state.gold;h.storage.map.set(h.S.LEASE,JSON.stringify({token:'other',until:1720001000000}));h.window.emit('storage',{key:h.S.LEASE});const raw=h.storage.map.get(h.S.KEY);h.click('acceptConfirm');eq(h.state.gold,gold);eq(h.state.bag.length,count);eq(h.storage.map.get(h.S.KEY),raw);eq(h.actions.filter(a=>a.type==='sell').length,0);
});
await test('Hide, reload and persisted pageshow invalidate an old sale session without selling restored items',async()=>{
 for(const lifecycle of ['visibility','bfcache']){const h=await boot();bagAdd(h,4);await refresh(h);h.click('selectUnlocked');h.click('sellSelected');const count=h.state.bag.length,gold=h.state.gold;
 if(lifecycle==='visibility'){await h.visibility(true);await h.visibility(false);}else{h.window.emit('pagehide',{persisted:true});h.elapse(30000);h.window.emit('pageshow',{persisted:true});await flush();}
 h.click('acceptConfirm');eq(h.state.gold,gold);eq(h.state.bag.length,count);eq(h.actions.filter(a=>a.type==='sell').length,0);ok(h.$('toast').textContent.includes('旅程已更新'));eq(h.raf.size,1);}
});
await test('2,105-item backpack stays at 30 card nodes, caches comparisons, paginates, and exports without truncation',async()=>{
 const h=await boot();let calls=0;const original=h.E.compareEquip;h.E.compareEquip=(...args)=>{calls++;return original(...args);};const start=performance.now();bagAdd(h,2105);await refresh(h);eq(h.state.bag.length,2105);eq(h.$('bagItems').children.length,30);const initialCalls=calls,initialNodes=walk(h.doc.root).length;ok(initialNodes<1700,'DOM nodes bounded independently of total bag length');eq(initialCalls,2105);
 h.state.gold+=1;await refresh(h);eq(calls,initialCalls,'unchanged build comparisons reused on gold-only refresh');h.click('bagNext');eq(calls,initialCalls);eq(h.$('bagItems').children.length,30);for(let i=1;i<71;i++)h.click('bagNext');eq(h.$('bagItems').children.length,5);eq(h.$('bagPage').textContent,'第 71 / 71 頁');ok(walk(h.doc.root).length<=initialNodes);
 h.click('exportSave');const raw=await h.blobs.get(h.doc.downloads.at(-1).href).text(),restored=h.E.restore(raw);eq(restored.bag.length,2105);eq('basket' in JSON.parse(raw).profile,false);eq(restored.bag.map(i=>i.id).join(','),h.state.bag.map(i=>i.id).join(','));h.click('settings');h.$('importSave').files=[{size:Buffer.byteLength(raw),text:async()=>raw}];await h.change('importSave');h.click('acceptConfirm');eq(h.state.bag.length,2105);eq(h.$('bagItems').children.length,30);eq(h.$('bagPage').textContent,'第 1 / 71 頁');
 measurements.largeInventory={items:2105,pageSize:30,pageCount:71,initialRenderedNodeCount:initialNodes,finalPageCards:5,serializedBytes:Buffer.byteLength(raw),comparisonCallsOnInitialRender:initialCalls,cachedComparisonCallsOnGoldChange:0,elapsedMs:Math.round(performance.now()-start)};
});
await test('Import rejects over 32 MiB before reading, accepts exact 32 MiB, and independently guards oversized returned text',async()=>{
 const h=await boot();h.state.gold=543;h.click('settings');let reads=0;const raw=rawAt(h.E,{gold:765}),max=32*1024*1024;eq(h.E.MAX_SAVE_BYTES,max);
 h.$('importSave').files=[{size:max+1,text:async()=>{reads++;return raw;}}];await h.change('importSave');eq(reads,0);eq(h.state.gold,543);eq(h.$('confirmDialog').open,false);ok(h.$('toast').textContent.includes('32 MiB'));
 const padded=raw+' '.repeat(max-raw.length);h.$('importSave').files=[{size:max,text:async()=>padded}];await h.change('importSave');eq(h.$('confirmDialog').open,true);eq(h.state.gold,543);h.click('acceptConfirm');eq(h.state.gold,765);
 h.click('settings');h.$('importSave').files=[{size:1,text:async()=>padded+' '}];await h.change('importSave');eq(h.$('confirmDialog').open,false);eq(h.state.gold,765);measurements.importBoundary={maximumBytes:max,rejectedBytes:max+1,rejectedBeforeRead:true,exactMaximumAccepted:true,oversizedReturnedTextRejected:true};
});
await test('RAF maintains a single chain through repeated bag changes, item Escape and sale confirmation cycles',async()=>{
 const h=await boot();bagAdd(h,40);await refresh(h);for(let i=0;i<12;i++){h.click('bagNext');h.click('bagPrev');h.click(itemTile(h,bagIds(h)[0]));h.escape('itemDialog');h.click('selectPage');h.click('sellSelected');h.escape('confirmDialog');await h.tick(2);eq(h.raf.size,1);eq(h.$('itemDialog').open,false);eq(h.$('confirmDialog').open,false);}ok(h.state.time>2);eq(h.state.metrics.sold,0);
});

await test('V3 catalog exposes exactly 50 normal and 10 boss identities with complete descriptions',async()=>{
 const h=await boot(),B=h.window.StarweaveBestiary;eq(h.E.VERSION,3);eq(B.version,3);eq(h.E.CREATURES.length,60);eq(h.E.MONSTERS.length,50);eq(h.E.BOSSES.length,10);eq(new Set(h.E.CREATURES.map(d=>d.id)).size,60);eq(new Set(h.E.CREATURES.map(d=>d.name)).size,60);eq(B.validate().ok,true);
 for(const d of h.E.CREATURES){ok(d.name&&d.description&&d.body,'complete '+d.id);eq(d.kind,h.E.BOSSES.includes(d)?'boss':'normal');ok(d.biome>=0&&d.biome<5);}
 measurements.roster={total:60,normal:50,boss:10,biomes:5,allDefinitionsAvailableBeforeDiscovery:true};
});
await test('All 60 bestiary cards are visible through five bounded pages and invoke the actual renderer',async()=>{
 const h=await boot();eq(typeof h.R.drawCreature,'function');const rendered=[],raw=h.R.drawCreature;h.R.drawCreature=(...args)=>{rendered.push(args[1].id);return raw(...args);};const tab=h.doc.querySelectorAll('[data-tab]').find(t=>t.dataset.tab==='bestiary');h.click(tab);const ids=[];
 for(let page=1;page<=5;page++){eq(h.$('creaturePage').textContent,`第 ${page} / 5 頁`);eq(h.$('creatureGrid').children.length,12);eq(h.$('creaturePrev').disabled,page===1);eq(h.$('creatureNext').disabled,page===5);for(const c of h.$('creatureGrid').querySelectorAll('canvas[data-creature]')){ids.push(c.dataset.creature);ok(c.context.stats.calls>10,'real thumbnail drawing '+c.dataset.creature);eq(c.getAttribute('aria-hidden'),'true');const d=h.E.CREATURES.find(d=>d.id===c.dataset.creature);ok(c.parentElement.textContent.includes(d.name));ok(c.parentElement.textContent.includes(d.description));ok(c.parentElement.textContent.includes('尚未遇見'));}if(page<5)h.click('creatureNext');}
 eq(ids.join(','),h.E.CREATURES.map(d=>d.id).join(','));eq(rendered.join(','),ids.join(','));eq(new Set(ids).size,60);h.click('creatureNext');eq(h.$('creaturePage').textContent,'第 5 / 5 頁');for(let i=0;i<6;i++)h.click('creaturePrev');eq(h.$('creaturePage').textContent,'第 1 / 5 頁');eq(h.$('discoveryCount').textContent,'0/60');
});
await test('Bestiary normal, boss and biome filter combinations expose exactly the matching roster',async()=>{
 const h=await boot();h.click(h.doc.querySelectorAll('[data-tab]').find(t=>t.dataset.tab==='bestiary'));eq(h.$('creatureBiome').children.length,6);
 for(const kind of ['all','normal','boss'])for(const biome of ['all','0','1','2','3','4']){await choose(h,'creatureKind',kind);await choose(h,'creatureBiome',biome);const expected=h.E.CREATURES.filter(d=>(kind==='all'||d.kind===kind)&&(biome==='all'||d.biome===Number(biome))),pages=Math.ceil(expected.length/12),ids=[];for(let p=1;p<=pages;p++){eq(h.$('creaturePage').textContent,`第 ${p} / ${pages} 頁`);eq(h.$('creatureGrid').children.length,Math.min(12,expected.length-12*(p-1)));ids.push(...h.$('creatureGrid').querySelectorAll('canvas[data-creature]').map(c=>c.dataset.creature));if(p<pages)h.click('creatureNext');}eq(ids.join(','),expected.map(d=>d.id).join(','),kind+' biome '+biome);eq(ids.length,biome==='all'?(kind==='all'?60:kind==='normal'?50:10):(kind==='all'?12:kind==='normal'?10:2));}
 await choose(h,'creatureKind','all');await choose(h,'creatureBiome','all');h.click('creatureNext');h.click('creatureNext');await choose(h,'creatureKind','boss');eq(h.$('creaturePage').textContent,'第 1 / 1 頁');eq(h.$('creatureNext').disabled,true);
});
await test('Three navigation buttons keep focus, native keyboard reachability and exclusive aria/hidden state',async()=>{
 const h=await boot(),tabs=h.doc.querySelectorAll('[data-tab]');eq(tabs.length,3);eq(tabs.map(t=>t.dataset.tab).join(','),'growth,bag,bestiary');
 // Native buttons provide Enter/Space activation; mock clicks exercise the exact registered path.
 // This is not evidence of a browser keyboard event, tab order, or accessibility tree.
 for(const tab of [...tabs,...tabs.slice().reverse()]){eq(tab.tagName,'BUTTON');eq(tab.disabled,false);ok(!tab.getAttribute('tabindex')||Number(tab.getAttribute('tabindex'))>=0);tab.focus();h.click(tab);eq(h.doc.activeElement,tab);for(const other of tabs){eq(other.getAttribute('aria-pressed'),String(other===tab));eq(other.classList.contains('active'),other===tab);eq(h.$('panel-'+other.dataset.tab).hidden,other!==tab);}await refresh(h);eq(h.doc.activeElement,tab);eq(h.raf.size,1);}
 ok(/focus-visible/.test(css));ok(!/addEventListener\(['"]keydown['"][\s\S]*preventDefault/.test(source['ui.js']),'no global key interception of native activation');
});
await test('Real spawn and kill update discovered status, encounter counts and visible bestiary cards',async()=>{
 const h=await boot();h.click('pause');const s=h.state;s.mode='travel';s.world.goal={x:s.player.x,y:s.player.y};h.E.tick(s,.1);h.E.tick(s,.1);const e=s.enemies[0];ok(e,'real scheduled enemy spawned');eq(s.discoveries[e.speciesId].seen,1);eq(s.discoveries[e.speciesId].kills,0);
 h.click(h.doc.querySelectorAll('[data-tab]').find(t=>t.dataset.tab==='bestiary'));await refresh(h);let c=h.$('creatureGrid').querySelectorAll('canvas[data-creature]').find(c=>c.dataset.creature===e.speciesId);ok(c);ok(c.parentElement.textContent.includes('遇見 1 · 擊敗 0'));eq(h.$('discoveryCount').textContent,'1/60');
 s.projectiles.push({x:e.x,y:e.y,tx:e.x,ty:e.y,target:e.id,kind:'spark',damage:e.maxHp+1000,speed:100000,color:'#fff'});h.E.tick(s,.1);eq(s.discoveries[e.speciesId].kills,1);await refresh(h);c=h.$('creatureGrid').querySelectorAll('canvas[data-creature]').find(c=>c.dataset.creature===e.speciesId);ok(c.parentElement.textContent.includes('遇見 1 · 擊敗 1'));eq(h.$('discoveryCount').textContent,'1/60');
 const raw=h.E.serialize(s);eq(h.E.restore(raw).discoveries[e.speciesId].kills,1);h.click('settings');h.$('importSave').files=[{size:raw.length,text:async()=>raw}];await h.change('importSave');h.click('acceptConfirm');eq(h.state.discoveries[e.speciesId].kills,1);eq(h.$('discoveryCount').textContent,'1/60');
});
await test('Boss HUD uses a real scheduled boss name, HP ratio and windup tell then clears after death',async()=>{
 const h=await boot();h.click('pause');const s=h.state;s.depth=3;s.frontier=3;s.encounter=3;s.mode='travel';s.world.goal={x:s.player.x,y:s.player.y};h.E.tick(s,.1);for(let n=0;n<40;n++)h.E.tick(s,.1);const boss=s.enemies.find(e=>e.boss);ok(boss);eq(boss.speciesId,h.E.bossForDepth(3).id);await refresh(h);eq(h.$('bossHud').hidden,false);eq(h.$('world').parentElement.classList.contains('has-boss'),true);eq(h.$('bossName').textContent,boss.name);eq(h.$('bossHpText').textContent,Math.ceil(boss.hp)+' / '+boss.maxHp);eq(h.$('bossHpFill').style.width,Math.max(0,boss.hp/boss.maxHp*100)+'%');
 boss.windup=1;await refresh(h);ok(h.$('bossTell').textContent.includes('預告'));ok(h.$('bossTell').textContent.includes('左下'));boss.windup=0;await refresh(h);eq(h.$('bossTell').textContent,h.E.BOSSES.find(d=>d.id===boss.speciesId).description);
 s.projectiles.push({x:boss.x,y:boss.y,tx:boss.x,ty:boss.y,target:boss.id,kind:'spark',damage:boss.maxHp+10000,speed:100000,color:'#fff'});h.E.tick(s,.1);ok(!s.enemies.some(e=>e.id===boss.id));await refresh(h);eq(h.$('bossHud').hidden,true);eq(h.$('world').parentElement.classList.contains('has-boss'),false);eq(s.discoveries[boss.speciesId].kills,1);
});
await test('Boss HUD is hidden immediately on real damage-triggered retreat despite living enemies',async()=>{
 const h=await boot();h.click('pause');const s=h.state;s.depth=3;s.frontier=3;s.encounter=3;s.mode='travel';s.world.goal={x:s.player.x,y:s.player.y};h.E.tick(s,.1);for(let n=0;n<40;n++)h.E.tick(s,.1);const boss=s.enemies.find(e=>e.boss);ok(boss);s.world.camp={x:-300,y:300};await refresh(h);eq(h.$('bossHud').hidden,false);eq(h.$('world').parentElement.classList.contains('has-boss'),true);
 s.player.hp=1;s.enemyShots.push({x:s.player.x,y:s.player.y-15,tx:s.player.x,ty:s.player.y-15,kind:'hostile',color:'#fff',speed:100000,damage:100000,age:0,ownerId:boss.id});h.E.tick(s,.1);eq(s.mode,'retreat');ok(s.enemies.some(e=>e.boss&&e.hp>0),'retreat fixture keeps a living boss');await refresh(h);eq(h.$('bossHud').hidden,true,'living boss must not leave stale combat HUD after retreat');eq(h.$('world').parentElement.classList.contains('has-boss'),false,'normal stage labels restored after retreat');
});
await test('V2 synthetic save migrates unchanged inventory and world into V3 with empty discoveries',async()=>{
 const h=await boot(),s=h.E.create(214);s.gold=1234;s.level=4;s.attrPoints=9;s.skillPoints=3;for(let i=0;i<36;i++){const item=h.E.makeItem(s,1+i%4);item.locked=i%7===0;s.bag.push(item);}s.world.camp={x:350,y:-350};s.world.wave=17;const legacy=JSON.parse(h.E.serialize(s));legacy.version=2;delete legacy.profile.discoveries;const raw=JSON.stringify(legacy),old=inventorySnapshot(legacy.profile.bag);
 const b=await boot({storage:memory({'arcade.starweave-idle.save.v1':raw})});eq(b.state.version,3);eq(b.state.gold,1234);eq(inventorySnapshot(b.state.bag),old);eq(b.state.bag.length,36);eq(Object.keys(b.state.discoveries).length,0);eq(b.state.world.camp.x,350);eq(b.state.world.wave,17);eq(b.state.mode,'camp');eq(b.$('discoveryCount').textContent,'0/60');eq(b.$('bagItems').children.length,30);b.click('exportSave');const exported=JSON.parse(await b.blobs.get(b.doc.downloads.at(-1).href).text());eq(exported.version,3);eq('basket' in exported.profile,false);eq(inventorySnapshot(exported.profile.bag),old);
 for(const version of [1,2,3]){const valid=JSON.parse(h.E.serialize(s));valid.version=version;if(version===1)valid.profile.basket=[];for(const value of [null,false,0,'',[]]){valid.profile.discoveries=value;let error=null;try{h.E.restore(JSON.stringify(valid));}catch(e){error=e;}ok(error&&/discoveries/.test(error.message),'reject malformed present discoveries in V'+version+' '+JSON.stringify(value));}delete valid.profile.discoveries;if(version<3)eq(Object.keys(h.E.restore(JSON.stringify(valid)).discoveries).length,0,'V'+version+' may omit discoveries');else{let error=null;try{h.E.restore(JSON.stringify(valid));}catch(e){error=e;}ok(error&&/Missing discoveries/.test(error.message),'V3 requires discoveries');}}
 h.click('settings');const beforeGold=h.state.gold,beforeSaved=h.storage.map.get(h.S.KEY);for(const missing of [false,true]){const bad=JSON.parse(h.E.serialize(s));if(missing)delete bad.profile.discoveries;else bad.profile.discoveries=null;const input=JSON.stringify(bad);h.$('importSave').files=[{size:input.length,text:async()=>input}];await h.change('importSave');eq(h.$('confirmDialog').open,false,'invalid discovery import rejected before confirmation');eq(h.state.gold,beforeGold);eq(h.storage.map.get(h.S.KEY),beforeSaved);ok(h.$('toast').textContent.includes('無法驗證'));}
});
await test('V3 cache tokens and catalog-first dependency checks protect old V2 asset order',async()=>{
 const refs=[...html.matchAll(/(?:src|href)="(starweave-idle\/[^\"]+)"/g)].map(m=>m[1]);eq(refs.length,6);ok(refs.every(r=>r.endsWith('?v=4')));ok(refs.every(r=>!r.endsWith('?v=2')));const empty=vm.createContext({});let caught=null;try{vm.runInContext(source['engine.js'],empty,{filename:'engine.js'});}catch(e){caught=e;}ok(caught&&/catalog unavailable/.test(caught.message),'missing catalog rejects before creating state');eq(empty.Starweave,undefined);vm.runInContext(source['bestiary.js'],empty,{filename:'bestiary.js'});vm.runInContext(source['engine.js'],empty,{filename:'engine.js'});eq(empty.Starweave.VERSION,3);eq(empty.Starweave.CREATURES.length,60);
 measurements.cacheProtection={assetQueryVersion:3,catalogBeforeEngine:true,missingCatalogRejects:true,forcedStaleResponsesNotSimulated:true};
});
await test('Bestiary navigation does not alter backpack selection, filters or selected-sale safety',async()=>{
 const h=await boot();bagAdd(h,43);await refresh(h);h.click(h.doc.querySelectorAll('[data-tab]').find(t=>t.dataset.tab==='bag'));await choose(h,'bagFilter','unlocked');h.click('selectPage');const summary=h.$('selectionSummary').textContent,bagBefore=h.state.bag.map(i=>i.id).join(','),gold=h.state.gold;
 h.click(h.doc.querySelectorAll('[data-tab]').find(t=>t.dataset.tab==='bestiary'));await choose(h,'creatureKind','boss');h.click(h.doc.querySelectorAll('[data-tab]').find(t=>t.dataset.tab==='bag'));eq(h.$('selectionSummary').textContent,summary);eq(h.state.bag.map(i=>i.id).join(','),bagBefore);eq(h.state.gold,gold);h.click('sellSelected');eq(h.$('confirmDialog').open,true);h.click('cancelConfirm');eq(h.state.bag.map(i=>i.id).join(','),bagBefore);eq(h.state.gold,gold);eq('basket' in h.state,false);eq(h.raf.size,1);
});

// Direct storage tests isolate browser-independent ownership guarantees.
const S=require(path.join(base,'storage.js'));
await test('Storage lease deny/expire/release never deletes a foreign lease',async()=>{let now=100;const b=memory(),a=S.make(b,{token:'a',now:()=>now}),c=S.make(b,{token:'c',now:()=>now});eq(a.claim(),true);eq(c.claim(),false);eq(c.save('wrong'),false);eq(a.save('first'),true);now+=9001;eq(c.claim(),true);eq(a.valid(),false);eq(a.heartbeat(),false);eq(a.save('stale'),false);a.release();eq(JSON.parse(b.map.get(S.LEASE)).token,'c');eq(c.save('second'),true);eq(b.map.get(S.KEY),'second');c.release();eq(b.map.has(S.LEASE),false);});
await test('Storage protect blocks ordinary writes; explicit force replacement is bounded',async()=>{const b=memory({[S.KEY]:'corrupt','other':'keep'}),a=S.make(b);a.claim();a.protect();eq(a.save('ordinary'),false);eq(b.map.get(S.KEY),'corrupt');eq(a.save('replacement',true),true);eq(a.status.protected,false);eq(b.map.get('other'),'keep');a.release();eq(a.save('ownerless',true),false);});
await test('Storage blocked reads/writes and quota errors explicitly avoid a false saved state',async()=>{const denied={getItem(){throw Error('denied');},setItem(){throw Error('denied');},removeItem(){throw Error('denied');}},a=S.make(denied);eq(a.read().status,'unavailable');eq(a.claim(),true);eq(a.save('new'),false);eq(a.status.lastSaved,0);eq(a.status.temporary,true);ok(a.status.lastError);const b=memory(),c=S.make(b);c.claim();b.setItem=()=>{throw Error('QuotaExceededError');};eq(c.save('new'),false);eq(c.status.lastSaved,0);ok(c.status.lastError.includes('失敗'));eq(c.heartbeat(),true);eq(c.status.temporary,true);});
await test('Web Locks reject occupied acquisition, release ownership, and gracefully fall back',async()=>{const b=memory(),locks=webLocks(),a=S.make(b,{token:'a'}),c=S.make(b,{token:'c'});eq(await a.acquire(locks),true);eq(await c.acquire(locks),false);a.release();await flush();eq(await c.acquire(locks),true);c.release();await flush();const d=S.make(b,{token:'d'});eq(await d.acquire({request(){throw Error('unavailable');}}),true);d.release();const e=S.make(b,{token:'e'});eq(await e.acquire({request(){return Promise.reject(Error('not supported'));}}),true);e.release();});
await test('Every audited production source remained stable throughout run',async()=>{for(const [f,text]of Object.entries(source))eq(fs.readFileSync(path.join(base,f),'utf8'),text,'source changed during audit: '+f);});
const report={suite:'Starweave v4 independent bestiary, UI, unified-backpack and storage audit',generatedAt:new Date().toISOString(),environment:{node:process.version,browserUsed:false,dependencies:'Node built-ins only'},method:'Unmodified production engine/storage/renderer/UI evaluated in Node VM with event-capable mock DOM, simulated timers/visibility/locks/storage and finite-checking canvas. Direct storage module tests isolate exact ownership failures.',limitations:['Mock DOM does not prove native dialog focus trapping, keyboard file picker activation, accessibility tree, actual layout, overflow or canvas raster quality.','Storage event and lifecycle behavior are simulated at registered handler boundaries, not across real browser processes.','Source-only accessibility findings require live-browser verification after publication.'],sourceDigests:Object.fromEntries(Object.entries(source).map(([f,t])=>[f,crypto.createHash('sha256').update(t).digest('hex')])),measurements,counts:{tests:results.length,passed:results.filter(r=>r.status==='passed').length,failed:results.filter(r=>r.status==='failed').length,assertions},results};
const arg=process.argv.indexOf('--report');if(arg>=0&&!process.argv[arg+1])throw Error('--report needs an output path');const out=arg<0?(process.env.STARWEAVE_UI_REPORT||path.join(fs.mkdtempSync(path.join(os.tmpdir(),'starweave-v3-ui-')),'ui-v3-independent-results.json')):path.resolve(process.argv[arg+1]);fs.mkdirSync(path.dirname(out),{recursive:true});fs.writeFileSync(out,JSON.stringify(report,null,2)+'\n');for(const r of results)console.log((r.status==='passed'?'PASS ':'FAIL ')+r.name+(r.error?'\n  '+r.error:''));console.log(JSON.stringify(report.counts));console.log('Report: '+out);process.exitCode=report.counts.failed?1:0;
})().catch(e=>{console.error(e);process.exitCode=1;});
