#!/usr/bin/env node
'use strict';
// Offline, independent UI/storage audit: production scripts are evaluated unchanged.
// This mock-DOM harness cannot prove native-browser layout, accessibility tree,
// top-layer behavior, focus trapping, or raster quality. No browser is launched.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict'),crypto=require('node:crypto'),os=require('node:os');
const base=fs.existsSync(path.join(__dirname,'engine.js'))?__dirname:path.resolve(__dirname,'../games/starweave-idle');
const files=['../starweave-idle.html','engine.js','storage.js','render.js','ui.js','style.css'];
const source=Object.fromEntries(files.map(f=>[f,fs.readFileSync(path.join(base,f),'utf8')]));
const html=source['../starweave-idle.html'],css=source['style.css'];
let assertions=0;const results=[];
function ok(v,m){assertions++;assert.ok(v,m);}function eq(a,b,m){assertions++;assert.equal(a,b,m);}
async function test(name,fn){const before=assertions;try{await fn();results.push({name,status:'passed',assertions:assertions-before});}catch(e){results.push({name,status:'failed',assertions:assertions-before,error:e.message,stack:e.stack.split('\n').slice(0,5).join('\n')});}}
class Events{constructor(){this.listeners=new Map();}addEventListener(t,f){if(!this.listeners.has(t))this.listeners.set(t,[]);this.listeners.get(t).push(f);}emit(t,extra={}){const e={type:t,target:this,currentTarget:this,defaultPrevented:false,preventDefault(){this.defaultPrevented=true;},stopPropagation(){this.stopped=true;},...extra};const responses=[];for(const f of this.listeners.get(t)||[])responses.push(f(e));e.responses=responses;return e;}}
function context2d(){const stats={calls:0,methods:new Set()};return new Proxy({stats},{get(o,k){if(k in o)return o[k];if(k==='measureText')return t=>({width:String(t).length*6});if(k==='createLinearGradient'||k==='createRadialGradient')return (...a)=>{for(const n of a)assert.ok(Number.isFinite(n),'finite gradient');return{addColorStop(){}};};return (...a)=>{stats.calls++;stats.methods.add(k);if(['ellipse','arc','arcTo','fillRect','clearRect','moveTo','lineTo','translate','rotate','scale','setTransform','bezierCurveTo','quadraticCurveTo'].includes(k))for(const n of a)assert.ok(typeof n==='boolean'||Number.isFinite(n),'finite canvas '+k);};},set(o,k,v){o[k]=v;return true;}});}
function matches(e,s){if(s==='dialog')return e.tagName==='DIALOG';if(s==='dialog[open]')return e.tagName==='DIALOG'&&e.open;if(s==='button')return e.tagName==='BUTTON';if(s.startsWith('#'))return e.id===s.slice(1);const m=s.match(/^\[([\w-]+)(?:="([^"]*)")?\]$/);if(m)return e.getAttribute(m[1])!==null&&(m[2]===undefined||e.getAttribute(m[1])===m[2]);throw Error('Unsupported selector '+s);}
class Element extends Events{
 constructor(tag,doc){super();this.tagName=tag.toUpperCase();this.ownerDocument=doc;this.attributes={};this.children=[];this.parentElement=null;this.style={};this.dataset={};this.hidden=false;this.open=false;this.checked=false;this.disabled=false;this._text='';this._html='';this._classes=new Set();this.classList={add:(...x)=>x.forEach(v=>this._classes.add(v)),remove:(...x)=>x.forEach(v=>this._classes.delete(v)),contains:x=>this._classes.has(x),toggle:(x,force)=>{const v=force===undefined?!this._classes.has(x):!!force;v?this._classes.add(x):this._classes.delete(x);return v;}};}
 setAttribute(k,v){this.attributes[k]=String(v);if(k==='id')this.id=String(v);if(k==='class')this._classes=new Set(String(v).split(/\s+/));if(['hidden','disabled','checked','open'].includes(k))this[k]=true;if(k.startsWith('data-'))this.dataset[k.slice(5).replace(/-([a-z])/g,(_,c)=>c.toUpperCase())]=String(v);}
 getAttribute(k){return this.attributes[k]??null;}removeAttribute(k){delete this.attributes[k];if(['hidden','disabled','checked','open'].includes(k))this[k]=false;}
 get className(){return [...this._classes].join(' ');}set className(v){this.setAttribute('class',v);}
 get isConnected(){let e=this;while(e.parentElement)e=e.parentElement;return e===this.ownerDocument.root;}
 get textContent(){return this._text+this.children.map(e=>e.textContent||'').join('');}set textContent(v){this.detach();this._text=String(v);}
 get innerHTML(){return this._html;}set innerHTML(v){this.detach();this._html=String(v);this._text='';parse(String(v),this.ownerDocument,this);}
 detach(){const focused=this.ownerDocument.activeElement;if(focused&&this.contains(focused)&&focused!==this)this.ownerDocument.activeElement=this.ownerDocument.body;for(const e of this.children)e.parentElement=null;this.children=[];}
 contains(el){for(let e=el;e;e=e.parentElement)if(e===this)return true;return false;}
 append(...nodes){for(const n of nodes){this.children.push(n);n.parentElement=this;}}
 focus(){this.ownerDocument.activeElement=this;}
 showModal(){this.open=true;this.beforeFocus=this.ownerDocument.activeElement;this.ownerDocument.activeElement=this;}
 close(){if(this.open){this.open=false;this.ownerDocument.activeElement=this.beforeFocus?.isConnected?this.beforeFocus:this.ownerDocument.body;this.emit('close');}}
 closest(s){for(let e=this;e;e=e.parentElement)if(matches(e,s))return e;return null;}
 querySelectorAll(s){return walk(this).slice(1).filter(e=>matches(e,s));}querySelector(s){return this.querySelectorAll(s)[0]||null;}
 getContext(){return this.context||(this.context=context2d());}
 click(){if(this.tagName==='A'){this.ownerDocument.downloads.push({href:this.href,download:this.download});return;}return this.ownerDocument.click(this);}
}
function walk(el){return[el,...el.children.flatMap(walk)];}
class Document extends Events{
 constructor(){super();this.root=new Element('root',this);this.body=null;this.activeElement=null;this.hidden=false;this.downloads=[];}
 createElement(t){return new Element(t,this);}getElementById(id){return walk(this.root).find(e=>e.id===id)||null;}
 querySelectorAll(s){return walk(this.root).filter(e=>matches(e,s));}querySelector(s){return this.querySelectorAll(s)[0]||null;}
 click(el){if(el.disabled)return null;let e={type:'click',target:el,defaultPrevented:false,preventDefault(){this.defaultPrevented=true;},stopPropagation(){this.stopped=true;}};for(let n=el;n&&!e.stopped;n=n.parentElement)for(const f of n.listeners.get('click')||[])f(e);if(!e.stopped)for(const f of this.listeners.get('click')||[])f(e);return e;}
}
function parse(text,doc,parent){const stack=[parent],voids=new Set(['area','base','br','col','embed','hr','img','input','link','meta','param','source','track','wbr']);for(const m of text.matchAll(/<!--[\s\S]*?-->|<![^>]*>|<\/?([a-zA-Z][\w-]*)([^>]*)>|([^<]+)/g)){if(m[0].startsWith('<!'))continue;if(m[3]){stack.at(-1)._text+=m[3];continue;}const t=m[1].toLowerCase();if(m[0].startsWith('</')){while(stack.length>1&&stack.pop().tagName.toLowerCase()!==t){}continue;}const el=doc.createElement(t);for(const a of m[2].matchAll(/([\w:-]+)(?:\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s'"=<>`]+)))?/g))el.setAttribute(a[1],a[2]??a[3]??a[4]??'');stack.at(-1).append(el);if(t==='body')doc.body=el;if(!voids.has(t))stack.push(el);}return doc;}
function memory(initial={}){const map=new Map(Object.entries(initial));return{map,sets:[],removes:[],getItem(k){return map.get(k)??null;},setItem(k,v){this.sets.push([k,String(v)]);map.set(k,String(v));},removeItem(k){this.removes.push(k);map.delete(k);}};}
const flush=async()=>{for(let i=0;i<8;i++)await Promise.resolve();};
function webLocks(){let held=false;return{request:async(name,opts,fn)=>{if(held)return fn(null);held=true;try{return await fn({name});}finally{held=false;}},get held(){return held;}};}
async function boot(options={}){
 const doc=new Document();parse(html,doc,doc.root);doc.activeElement=doc.body;doc.hidden=!!options.hidden;
 const window=new Events(),raf=new Map(),timers=new Map(),intervals=new Map(),draws=[],actions=[],steps=[],blobs=new Map();let next=1,ts=100,state=null;
 Object.assign(window,{document:doc,window,devicePixelRatio:options.dpr||1,matchMedia:()=>({matches:!!options.reduced})});const storage=options.storage||memory();Object.defineProperty(window,'localStorage',options.denied?{get(){throw Error('denied');}}:{value:storage});
 class TestDate extends Date{static now(){return 1720000000000+Math.floor(ts);}}
 const seededMath=Object.create(Math);let seed=7;seededMath.random=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};
 const context=vm.createContext({window,document:doc,navigator:{locks:options.locks},console,Date:TestDate,Math:seededMath,CSS:{escape:String},Blob,URL:{createObjectURL:b=>{const u='blob:mock-'+next++;blobs.set(u,b);return u;},revokeObjectURL:u=>blobs.delete(u)},performance:{now:()=>ts},requestAnimationFrame:f=>{const id=next++;raf.set(id,f);return id;},cancelAnimationFrame:id=>raf.delete(id),setTimeout:(fn,delay=0)=>{const id=next++;timers.set(id,{fn,due:ts+delay});return id;},clearTimeout:id=>timers.delete(id),setInterval:(fn,delay)=>{const id=next++;intervals.set(id,{fn,delay,due:ts+delay});return id;},clearInterval:id=>intervals.delete(id)});
 for(const f of ['engine.js','storage.js','render.js']){vm.runInContext(source[f],context,{filename:f});for(const key of ['Starweave','StarweaveStorage','StarweaveRender'])if(context[key])window[key]=context[key];}
 const E=window.Starweave,S=window.StarweaveStorage,R=window.StarweaveRender;
 // Observe only state actually used by UI stats/tick/draw, not speculative import fixtures.
 for(const method of ['stats','tick','act']){const raw=E[method];E[method]=(s,...a)=>{state=s;if(method==='tick')steps.push(a[0]);const result=raw(s,...a);if(method==='act')actions.push({type:a[0],payload:a[1],result});return result;};}
 const rawDraw=R.draw;R.draw=(ctx,s,opts)=>{state=s;draws.push({time:s.time,opts});return rawDraw(ctx,s,opts);};
 vm.runInContext(source['ui.js'],context,{filename:'ui.js'});await flush();
 const $=id=>doc.getElementById(id);
 async function tick(n=1,ms=100){for(let i=0;i<n;i++){ts+=ms;for(const [id,t] of [...timers])if(t.due<=ts){timers.delete(id);t.fn();}for(const t of intervals.values())if(t.due<=ts){t.due=ts+t.delay;t.fn();}await flush();const fns=[...raf.values()];raf.clear();for(const fn of fns)fn(ts);await flush();}}
 async function change(id,extra={}){const e=$(id).emit('change',{target:$(id),...extra});await Promise.all(e.responses);await flush();}
 function close(id){doc.click(doc.querySelectorAll('[data-close]').find(e=>e.dataset.close===id));}
 async function visibility(hidden){doc.hidden=hidden;doc.emit('visibilitychange');await flush();}
 function escape(id){const d=$(id),e=d.emit('cancel');if(!e.defaultPrevented)d.close();return e;}
 return{$,doc,window,storage,E,S,R,steps,actions,draws,blobs,raf,context,get state(){return state;},click:id=>doc.click(typeof id==='string'?$(id):id),change,tick,close,escape,visibility,elapse:ms=>{ts+=ms;},get ts(){return ts;}};
}
function grow(h,level=3){const s=h.state;s.level=level;s.attrPoints=(level-1)*3;s.skillPoints=level-1;return s;}
function rawAt(E,{gold=777,level=3}={}){const s=E.create(53);s.gold=gold;s.level=level;s.attrPoints=(level-1)*3;s.skillPoints=level-1;return E.serialize(s);}
function detailButton(h,type){return h.$('itemActions').querySelectorAll('[data-action]').find(e=>e.dataset.action===type);}
function refresh(h){return h.tick(2);}
(async()=>{
await test('HTML IDs, local asset references and script order are valid',async()=>{const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(x=>x[1]);eq(ids.length,new Set(ids).size);for(const m of source['ui.js'].matchAll(/\$\('([^']+)'\)/g))ok(ids.includes(m[1]),'HTML ID: '+m[1]);for(const m of html.matchAll(/(?:src|href)="([^"]+)"/g)){if(m[1]==='../index.html?category=simulation')continue;ok(!/^https?:/.test(m[1]));ok(fs.existsSync(path.resolve(base,'..',m[1])),'asset: '+m[1]);}ok(!/\b(?:fetch|XMLHttpRequest|WebSocket)\s*\(/.test(source['ui.js']));});
await test('Zero-input boot advances actual engine and renderer continuously',async()=>{const h=await boot();eq(h.$('pauseOverlay').hidden,true);eq(h.raf.size,1);await h.tick(250);ok(h.state.time>24);ok(h.state.metrics.kills>0,'zero-input kills');ok(h.draws.length>=250);eq(h.raf.size,1);ok(h.$('world').context.stats.calls>1000);eq(h.$('world').width,960);ok(h.storage.map.has(h.S.KEY),'automatic save');});
await test('Manual pause and resume preserve one RAF and freeze simulation',async()=>{const h=await boot();await h.tick(5);h.click('pause');const t=h.state.time;await h.tick(30);eq(h.state.time,t);eq(h.raf.size,1);eq(h.$('pauseOverlay').hidden,false);h.click('pause');await h.tick(3);ok(h.state.time>t);eq(h.$('pauseOverlay').hidden,true);});
await test('Help/settings close and native Escape leave RAF alive and resume correctly',async()=>{for(const [button,id]of [['help','guideDialog'],['settings','settingsDialog']]){const h=await boot();await h.tick(5);h.click(button);const t=h.state.time;eq(h.$(id).open,true);await h.tick(5);eq(h.state.time,t);eq(h.raf.size,1);h.close(id);await h.tick(3);ok(h.state.time>t);h.click(button);const e=h.escape(id);eq(e.defaultPrevented,false);await h.tick(2);eq(h.$(id).open,false);eq(h.raf.size,1);}});
await test('Closing guide preserves prior explicit pause',async()=>{const h=await boot();h.click('pause');h.click('help');h.close('guideDialog');const t=h.state.time;await h.tick(4);eq(h.state.time,t);eq(h.$('pause').textContent,'繼續');});
await test('Item dialog allows continuing auto battle and repeated upgrade transactions stay bounded',async()=>{const h=await boot();h.state.gold=100000;const item=h.state.equipment.wand;h.click(h.doc.querySelectorAll('[data-item]').find(e=>e.dataset.item===item.id));eq(h.$('itemDialog').open,true);const t=h.state.time;await h.tick(3);ok(h.state.time>t);let expected=0;for(let i=0;i<10;i++)expected+=h.E.enhanceCost({...item,enhance:i});const gold=h.state.gold;for(let i=0;i<14;i++)h.click(detailButton(h,'enhance'));eq(item.enhance,10);eq(h.state.gold,gold-expected);eq(detailButton(h,'enhance').disabled,true);eq(h.raf.size,1);});
await test('Attribute/skill eligibility and repeated delegated clicks cannot overspend',async()=>{const h=await boot();eq(h.$('plus-int').disabled,true);eq(h.$('learn-ice').disabled,true);grow(h);await refresh(h);for(let i=0;i<9;i++)h.click('plus-int');eq(h.state.attrs.int,6);eq(h.state.attrPoints,0);eq(h.$('plus-int').disabled,true);h.click('learn-ice');h.click('learn-fire');h.click('learn-fire');eq(h.state.skillPoints,0);eq(h.state.skills.ice,1);eq(h.state.skills.fire,2);eq(h.$('learn-shield').disabled,true);});
await test('Inventory tabs, equip/stash/retrieve/lock and repeated sale use actual UI actions',async()=>{const h=await boot();const a=h.E.makeItem(h.state,4,'wand','rare'),b=h.E.makeItem(h.state,3,'hat','magic');h.state.bag.push(a);h.state.basket.push(b);await refresh(h);h.click(h.doc.querySelectorAll('[data-tab]').find(e=>e.dataset.tab==='bag'));eq(h.$('panel-bag').hidden,false);eq(h.$('panel-growth').hidden,true);eq(h.doc.querySelectorAll('[data-tab]').find(e=>e.dataset.tab==='bag').getAttribute('aria-pressed'),'true');eq(h.doc.querySelectorAll('[data-tab]').find(e=>e.dataset.tab==='growth').getAttribute('aria-pressed'),'false');h.click(h.doc.querySelectorAll('[data-item]').find(e=>e.dataset.item===a.id));h.click(detailButton(h,'equip'));eq(h.state.equipment.wand.id,a.id);eq(detailButton(h,'equip').disabled,true);h.close('itemDialog');h.click(h.doc.querySelectorAll('[data-item]').find(e=>e.dataset.item===b.id));h.click(detailButton(h,'lock'));h.close('itemDialog');const gold=h.state.gold;h.click('sellAll');eq(h.state.gold,gold);eq(h.state.basket.length,1);h.click(h.doc.querySelectorAll('[data-item]').find(e=>e.dataset.item===b.id));h.click(detailButton(h,'lock'));h.click(detailButton(h,'retrieve'));eq(h.state.basket.length,0);h.click(detailButton(h,'stash'));eq(h.state.basket.length,1);h.close('itemDialog');const value=h.E.sellValue(b);for(let i=0;i<8;i++)h.click('sellAll');eq(h.state.gold,gold+value);eq(h.state.metrics.sold,1);eq(h.state.basket.length,0);});
await test('Reset Cancel, Escape and repeated Confirm are transactional',async()=>{const h=await boot();h.state.gold=555;h.click('settings');h.click('reset');eq(h.$('confirmDialog').open,true);h.click('cancelConfirm');eq(h.state.gold,555);eq(h.$('settingsDialog').open,true);h.click('reset');h.escape('confirmDialog');eq(h.state.gold,555);h.click('acceptConfirm');eq(h.state.gold,555,'dismissed callback cannot execute');h.click('reset');h.click('acceptConfirm');const seed=h.state.rng;eq(h.state.gold,0);h.click('acceptConfirm');eq(h.state.rng,seed);eq(h.$('settingsDialog').open,false);await h.tick(3);eq(h.raf.size,1);});
await test('Import validation and confirmation protect current progress',async()=>{const h=await boot();h.state.gold=555;h.click('settings');for(const file of [{size:2600000,text:async()=>'{large'}, {size:10,text:async()=>'{corrupt'}, {size:10,text:async()=>JSON.stringify({version:999,profile:{}})}]){h.$('importSave').files=[file];await h.change('importSave');eq(h.state.gold,555);eq(h.$('confirmDialog').open,false);}const raw=rawAt(h.E,{gold:777});h.$('importSave').files=[{size:raw.length,text:async()=>raw}];await h.change('importSave');eq(h.state.gold,555);eq(h.$('confirmDialog').open,true);h.click('cancelConfirm');eq(h.state.gold,555);h.$('importSave').files=[{size:raw.length,text:async()=>raw}];await h.change('importSave');h.click('acceptConfirm');eq(h.state.gold,777);eq(h.state.level,3);eq(h.state.mode,'camp');eq(h.$('settingsDialog').open,false);eq(JSON.parse(h.storage.map.get(h.S.KEY)).profile.gold,777);});
await test('Export downloads current validated save and revokes its blob URL',async()=>{const h=await boot();h.state.gold=234;h.click('exportSave');eq(h.doc.downloads.length,1);const d=h.doc.downloads[0];ok(d.download.endsWith('.json'));const data=await h.blobs.get(d.href).text();eq(h.E.restore(data).gold,234);await h.tick(11);eq(h.blobs.has(d.href),false);});
await test('Visibility hide/resume saves, releases lease, loads fresh camp and never simulates hidden time',async()=>{const h=await boot();await h.tick(13);h.state.gold=654;await h.visibility(true);const t=h.state.time;ok(!h.storage.map.has(h.S.LEASE));await h.tick(300);eq(h.state.time,t);eq(h.raf.size,1);await h.visibility(false);eq(h.state.gold,654);eq(h.state.time,t);eq(h.state.mode,'camp');await h.tick(2);ok(h.state.time>t);});
await test('Pagehide/pageshow preserve RAF, saved progress and prevent elapsed wall-time gains',async()=>{const h=await boot();await h.tick(5);h.state.gold=432;h.window.emit('pagehide');const t=h.state.time;h.elapse(12000);eq(h.state.time,t);h.window.emit('pageshow');await flush();eq(h.state.gold,432);eq(h.state.time,t);await h.tick(3);ok(h.state.time>t);eq(h.raf.size,1);});
await test('Initially background-loaded page does not claim the active writer lease',async()=>{const h=await boot({hidden:true});h.window.emit('pageshow');await flush();eq(h.storage.map.has(h.S.LEASE),false,'hidden initial page must not retain lease');await h.tick(5);eq(h.state.time,0);await h.visibility(false);await h.tick(3);ok(h.state.time>0);});
await test('Blocked storage remains playable and retains temporary progress across visibility changes',async()=>{const h=await boot({denied:true});await h.tick(15);h.state.gold=456;const t=h.state.time;ok(/儲存|保存/.test(h.$('saveStatus').textContent));await h.visibility(true);await h.tick(10);await h.visibility(false);eq(h.state.gold,456,'temporary gold preserved');eq(h.state.time,t,'temporary journey preserved');await h.tick(3);ok(h.state.time>t);});
await test('Quota failure preserves unsaved progress when returning from background',async()=>{const storage=memory(),h=await boot({storage});h.state.gold=123;h.click('pause');h.click('pause');const original=storage.map.get(h.S.KEY);storage.setItem=function(k,v){if(k===h.S.KEY)throw Error('QuotaExceededError');this.map.set(k,String(v));};h.state.gold=999;await h.visibility(true);eq(storage.map.get(h.S.KEY),original);await h.visibility(false);eq(h.state.gold,999,'unsaved progress survives quota failure');});
await test('Corrupt saved bytes are protected, exportable, and temporary progress survives hiding',async()=>{const key='arcade.starweave-idle.save.v1',storage=memory({[key]:'{broken'}),h=await boot({storage});h.state.gold=567;await h.tick(60);eq(storage.map.get(key),'{broken');eq(h.$('exportOriginal').hidden,false);h.click('exportSave');const live=h.doc.downloads.at(-1);eq(h.E.restore(await h.blobs.get(live.href).text()).gold,567,'current temporary session exported separately');h.click('exportOriginal');const d=h.doc.downloads.at(-1);eq(await h.blobs.get(d.href).text(),'{broken');ok(d.download.includes('original-recovery'));await h.visibility(true);await h.visibility(false);eq(h.state.gold,567,'protected temporary session survives');eq(storage.map.get(key),'{broken');});
await test('Waiting tab cannot mutate and takes latest progress after ownership release',async()=>{const storage=memory(),locks=webLocks(),first=await boot({storage,locks}),second=await boot({storage,locks});eq(second.$('pauseOverlay').hidden,false);ok(second.$('autoLabel').textContent.includes('等候'));first.state.gold=987;grow(first);await refresh(first);await first.visibility(true);await second.tick(26);eq(second.state.gold,987);eq(second.state.level,3);eq(second.$('pauseOverlay').hidden,true);h: {const t=second.state.time;await second.tick(3);ok(second.state.time>t);}await second.visibility(true);});
await test('Lease theft event prevents UI transactions and keeps other-game keys untouched',async()=>{const storage=memory({'other-game':'keep'}),h=await boot({storage});grow(h);await refresh(h);const before=h.state.attrs.int;storage.map.set(h.S.LEASE,JSON.stringify({token:'other',until:1720001000000}));h.window.emit('storage',{key:h.S.LEASE});h.click('plus-int');eq(h.state.attrs.int,before);eq(h.$('pauseOverlay').hidden,false);eq(storage.map.get('other-game'),'keep');ok(storage.sets.every(([k])=>[h.S.KEY,h.S.LEASE].includes(k)));});
await test('Changed saved bytes after failed save protect both sessions and export live unsaved progress',async()=>{const storage=memory(),h=await boot({storage});h.state.gold=123;h.click('pause');h.click('pause');const original=storage.map.get(h.S.KEY),set=storage.setItem.bind(storage);let quota=true;storage.setItem=function(k,v){if(quota&&k===h.S.KEY)throw Error('QuotaExceededError');set(k,v);};h.state.gold=999;await h.visibility(true);eq(storage.map.get(h.S.KEY),original);const external=rawAt(h.E,{gold:888});storage.map.set(h.S.KEY,external);quota=false;await h.visibility(false);eq(h.state.gold,999);ok(h.$('storageNotice').textContent.includes('另一分頁已更新'));await h.tick(60);eq(storage.map.get(h.S.KEY),external,'foreign save preserved');h.click('exportSave');const d=h.doc.downloads.at(-1);eq(h.E.restore(await h.blobs.get(d.href).text()).gold,999);h.click('settings');h.$('importSave').files=[{size:external.length,text:async()=>external}];await h.change('importSave');h.click('acceptConfirm');eq(h.state.gold,888);eq(h.$('storageNotice').textContent.includes('另一分頁已更新'),false);eq(h.E.restore(storage.map.get(h.S.KEY)).gold,888);});
await test('Waiting duplicate-tab export never produces a fabricated fresh-session backup',async()=>{const storage=memory(),locks=webLocks(),a=await boot({storage,locks});a.state.gold=876;a.click('pause');const b=await boot({storage,locks});b.click('settings');b.click('exportSave');if(b.doc.downloads.length===0){ok(b.$('exportSave').disabled||b.$('toast').textContent.length>0,'unavailable export explained');}else{const d=b.doc.downloads.at(-1);eq(b.E.restore(await b.blobs.get(d.href).text()).gold,876,'export actual saved state while waiting');}await a.visibility(true);});
await test('Reset confirmation cannot mutate after losing tab ownership',async()=>{const h=await boot();h.state.gold=654;h.click('settings');h.click('reset');h.storage.map.set(h.S.LEASE,JSON.stringify({token:'other',until:1720001000000}));h.window.emit('storage',{key:h.S.LEASE});const raw=h.storage.map.get(h.S.KEY);h.click('acceptConfirm');eq(h.state.gold,654);eq(h.storage.map.get(h.S.KEY),raw);ok(h.$('toast').textContent.includes('等候'));});
await test('Import confirmation cannot mutate after losing tab ownership',async()=>{const h=await boot();h.state.gold=654;const raw=rawAt(h.E,{gold:999});h.click('settings');h.$('importSave').files=[{size:raw.length,text:async()=>raw}];await h.change('importSave');h.storage.map.set(h.S.LEASE,JSON.stringify({token:'other',until:1720001000000}));h.window.emit('storage',{key:h.S.LEASE});const before=h.storage.map.get(h.S.KEY);h.click('acceptConfirm');eq(h.state.gold,654);eq(h.storage.map.get(h.S.KEY),before);});
await test('Newer file choice wins when older asynchronous import finishes late',async()=>{const h=await boot();h.click('settings');const old=rawAt(h.E,{gold:111}),latest=rawAt(h.E,{gold:222});let complete;h.$('importSave').files=[{size:old.length,text:()=>new Promise(r=>{complete=r;})}];const pending=h.change('importSave');await flush();h.$('importSave').files=[{size:latest.length,text:async()=>latest}];await h.change('importSave');ok(h.$('confirmText').textContent.includes('222'));h.click('acceptConfirm');eq(h.state.gold,222);complete(old);await pending;eq(h.$('confirmDialog').open,false,'obsolete import must not reopen confirmation after newer import accepted');eq(h.state.gold,222);});
await test('Closing settings invalidates an unfinished file read',async()=>{const h=await boot();h.state.gold=321;h.click('settings');const raw=rawAt(h.E,{gold:999});let complete;h.$('importSave').files=[{size:raw.length,text:()=>new Promise(r=>{complete=r;})}];const pending=h.change('importSave');await flush();h.close('settingsDialog');complete(raw);await pending;eq(h.$('confirmDialog').open,false,'dismissed settings must not resurface a deferred import dialog');eq(h.state.gold,321);});
await test('Escape from settings invalidates an unfinished file read',async()=>{const h=await boot();h.state.gold=321;h.click('settings');const raw=rawAt(h.E,{gold:999});let complete;h.$('importSave').files=[{size:raw.length,text:()=>new Promise(r=>{complete=r;})}];const pending=h.change('importSave');await flush();h.escape('settingsDialog');complete(raw);await pending;eq(h.$('confirmDialog').open,false);eq(h.state.gold,321);eq(h.raf.size,1);});
await test('Reset decision invalidates an earlier pending import without stale prompts',async()=>{const h=await boot();h.state.gold=321;h.click('settings');const raw=rawAt(h.E,{gold:999});let complete;h.$('importSave').files=[{size:raw.length,text:()=>new Promise(r=>{complete=r;})}];const pending=h.change('importSave');await flush();h.click('reset');complete(raw);await pending;ok(h.$('confirmTitle').textContent.includes('重新'));h.click('cancelConfirm');eq(h.state.gold,321);});
await test('Original damaged-save export disappears after explicit accepted recovery',async()=>{const key='arcade.starweave-idle.save.v1',storage=memory({[key]:'{broken'}),h=await boot({storage});eq(h.$('exportOriginal').hidden,false);h.click('settings');const raw=rawAt(h.E,{gold:444});h.$('importSave').files=[{size:raw.length,text:async()=>raw}];await h.change('importSave');h.click('acceptConfirm');eq(h.state.gold,444);eq(h.$('exportOriginal').hidden,true);eq(h.E.restore(storage.map.get(key)).gold,444);});
await test('Basket pagination expands deterministically and locked bulk-sale items remain',async()=>{const h=await boot();for(let i=0;i<125;i++){const item=h.E.makeItem(h.state,1);item.locked=i%3===0;h.state.basket.push(item);}await refresh(h);eq(h.$('basketItems').children.length,60);eq(h.$('basketMore').hidden,false);h.click('basketMore');eq(h.$('basketItems').children.length,120);h.click('basketMore');eq(h.$('basketItems').children.length,125);eq(h.$('basketMore').hidden,true);const locked=h.state.basket.filter(i=>i.locked).length;h.click('sellAll');eq(h.state.basket.length,locked);ok(h.state.basket.every(i=>i.locked));eq(h.$('sellAll').disabled,true);});
await test('Reduced motion settings take OS preference initially and survive saved settings',async()=>{const h=await boot({reduced:true});eq(h.state.settings.reducedMotion,true);eq(h.$('reducedMotion').checked,true);h.click('settings');h.$('reducedMotion').checked=false;await h.change('reducedMotion');eq(h.state.settings.reducedMotion,false);h.$('sound').checked=true;await h.change('sound');eq(h.state.settings.sound,true);h.close('settingsDialog');await h.tick(3);eq(h.draws.at(-1).opts.reducedMotion,false);});
await test('Keyboard-focused item action survives passive inventory/detail rerender',async()=>{const h=await boot();h.click(h.doc.querySelectorAll('[data-item]')[0]);const button=detailButton(h,'lock');button.focus();eq(h.doc.activeElement,button);h.state.gold+=1;await refresh(h);ok(h.doc.activeElement?.dataset.action==='lock','current item action focus retained after gold/inventory update');});
await test('Import action is reachable from keyboard in source',async()=>{const h=await boot(),input=h.$('importSave'),label=input.parentElement;ok(!input.hidden||label.getAttribute('tabindex')==='0'||h.doc.querySelectorAll('[data-import]').length>0||h.$('importButton'),'file picker has a keyboard-focusable route');});
await test('Responsive and accessibility source safeguards exist',async()=>{for(const pattern of [/@media\(max-width:860px\)/,/@media\(max-width:560px\)/,/focus-visible/,/prefers-reduced-motion/,/100dvh/,/\[hidden\]/])ok(pattern.test(css),'CSS safeguard '+pattern);ok(html.includes('width=device-width'));ok(html.includes('aria-live="polite"'));for(const id of ['guideDialog','settingsDialog','itemDialog','confirmDialog'])ok(new RegExp('<dialog id="'+id+'" aria-labelledby=').test(html),'named native dialog '+id);ok(!html.includes('onclick='));});
// Direct storage tests isolate browser-independent ownership guarantees.
const S=require(path.join(base,'storage.js'));
await test('Storage lease deny/expire/release never deletes a foreign lease',async()=>{let now=100;const b=memory(),a=S.make(b,{token:'a',now:()=>now}),c=S.make(b,{token:'c',now:()=>now});eq(a.claim(),true);eq(c.claim(),false);eq(c.save('wrong'),false);eq(a.save('first'),true);now+=9001;eq(c.claim(),true);eq(a.valid(),false);eq(a.heartbeat(),false);eq(a.save('stale'),false);a.release();eq(JSON.parse(b.map.get(S.LEASE)).token,'c');eq(c.save('second'),true);eq(b.map.get(S.KEY),'second');c.release();eq(b.map.has(S.LEASE),false);});
await test('Storage protect blocks ordinary writes; explicit force replacement is bounded',async()=>{const b=memory({[S.KEY]:'corrupt','other':'keep'}),a=S.make(b);a.claim();a.protect();eq(a.save('ordinary'),false);eq(b.map.get(S.KEY),'corrupt');eq(a.save('replacement',true),true);eq(a.status.protected,false);eq(b.map.get('other'),'keep');a.release();eq(a.save('ownerless',true),false);});
await test('Storage blocked reads/writes and quota errors explicitly avoid a false saved state',async()=>{const denied={getItem(){throw Error('denied');},setItem(){throw Error('denied');},removeItem(){throw Error('denied');}},a=S.make(denied);eq(a.read().status,'unavailable');eq(a.claim(),true);eq(a.save('new'),false);eq(a.status.lastSaved,0);eq(a.status.temporary,true);ok(a.status.lastError);const b=memory(),c=S.make(b);c.claim();b.setItem=()=>{throw Error('QuotaExceededError');};eq(c.save('new'),false);eq(c.status.lastSaved,0);ok(c.status.lastError.includes('失敗'));eq(c.heartbeat(),true);eq(c.status.temporary,true);});
await test('Web Locks reject occupied acquisition, release ownership, and gracefully fall back',async()=>{const b=memory(),locks=webLocks(),a=S.make(b,{token:'a'}),c=S.make(b,{token:'c'});eq(await a.acquire(locks),true);eq(await c.acquire(locks),false);a.release();await flush();eq(await c.acquire(locks),true);c.release();await flush();const d=S.make(b,{token:'d'});eq(await d.acquire({request(){throw Error('unavailable');}}),true);d.release();const e=S.make(b,{token:'e'});eq(await e.acquire({request(){return Promise.reject(Error('not supported'));}}),true);e.release();});
await test('Every audited production source remained stable throughout run',async()=>{for(const [f,text]of Object.entries(source))eq(fs.readFileSync(path.join(base,f),'utf8'),text,'source changed during audit: '+f);});
const report={suite:'Starweave independent offline UI and storage audit',generatedAt:new Date().toISOString(),environment:{node:process.version,browserUsed:false,dependencies:'Node built-ins only'},method:'Unmodified production engine/storage/renderer/UI evaluated in Node VM with event-capable mock DOM, simulated timers/visibility/locks/storage and finite-checking canvas. Direct storage module tests isolate exact ownership failures.',limitations:['Mock DOM does not prove native dialog focus trapping, keyboard file picker activation, accessibility tree, actual layout, overflow or canvas raster quality.','Storage event and lifecycle behavior are simulated at registered handler boundaries, not across real browser processes.','Source-only accessibility findings require live-browser verification after publication.'],sourceDigests:Object.fromEntries(Object.entries(source).map(([f,t])=>[f,crypto.createHash('sha256').update(t).digest('hex')])),counts:{tests:results.length,passed:results.filter(r=>r.status==='passed').length,failed:results.filter(r=>r.status==='failed').length,assertions},results};
const arg=process.argv.indexOf('--report');if(arg>=0&&!process.argv[arg+1])throw Error('--report needs an output path');const out=arg<0?(process.env.STARWEAVE_UI_REPORT||path.join(fs.mkdtempSync(path.join(os.tmpdir(),'starweave-ui-')),'ui-independent-results.json')):path.resolve(process.argv[arg+1]);fs.mkdirSync(path.dirname(out),{recursive:true});fs.writeFileSync(out,JSON.stringify(report,null,2)+'\n');for(const r of results)console.log((r.status==='passed'?'PASS ':'FAIL ')+r.name+(r.error?'\n  '+r.error:''));console.log(JSON.stringify(report.counts));console.log('Report: '+out);process.exitCode=report.counts.failed?1:0;
})().catch(e=>{console.error(e);process.exitCode=1;});
