#!/usr/bin/env node
'use strict';
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict'),crypto=require('node:crypto'),cp=require('node:child_process');
const base=__dirname,html=fs.readFileSync(path.join(base,'../starweave-idle.html'),'utf8'),checks=[],out=fs.mkdtempSync(path.join(os.tmpdir(),'starweave-v4-verify-'));
const hash=file=>crypto.createHash('sha256').update(fs.readFileSync(path.join(base,file))).digest('hex');
function check(name,fn){fn();checks.push(name);}
function run(script,file){cp.execFileSync(process.execPath,[path.join(base,script),'--report',path.join(out,file)],{stdio:'pipe'});return JSON.parse(fs.readFileSync(path.join(out,file)));}
check('Local closure and shared v4 asset cache tokens',()=>{assert(html.includes('lang="zh-Hant"'));for(const m of html.matchAll(/(?:src|href)="([^"]+)"/g)){const ref=m[1];if(ref==='../index.html?category=simulation')continue;assert(!/^https?:|^\/\//.test(ref));assert(fs.existsSync(path.resolve(base,'..',ref.split('?')[0])),'missing '+ref);}for(const f of ['bestiary.js','engine.js','storage.js','render.js','ui.js','style.css'])assert(html.includes('starweave-idle/'+f+'?v=4'));assert(!html.includes('panel-basket'));for(const f of ['engine.js','storage.js','render.js','ui.js'])cp.execFileSync(process.execPath,['--check',path.join(base,f)]);});
check('Same game identity and isolated persistent save key',()=>{const c=JSON.parse(fs.readFileSync(path.join(base,'catalog.json')));assert.equal(c.id,'starweave-idle');assert.equal(c.artFile,'games/starweave-idle/art.svg');assert.equal(require('./engine.js').VERSION,3);assert.equal(require('./storage.js').KEY,'arcade.starweave-idle.save.v1');});
let engineResult,inventoryResult,uiResult;
check('Independent spatial, progression, whole-build comparison and migration regression',()=>{engineResult=run('verify-engine.cjs','engine.json');assert.equal(engineResult.engineSha256,hash('engine.js'));assert.equal(engineResult.failed,0);assert(engineResult.passed>=23);assert(engineResult.runs.length>=3);assert(engineResult.runs.every(r=>!r.errors?.length));});
check('No 18 or 2000 item cap; synthetic v1 items and locks all preserved',()=>{inventoryResult=run('verify-cap.cjs','inventory.json');assert.equal(inventoryResult.engineSha256,hash('engine.js'));assert.equal(inventoryResult.status,'passed');assert(inventoryResult.unifiedBagItems>10000);assert(inventoryResult.roundTripExact&&inventoryResult.combatContinues&&inventoryResult.legacy.allItemFieldsPreserved);assert.equal(inventoryResult.autoSale,false);});
check('Final-hash actual-time engine runs are distinct from accelerated all-boss witnesses',()=>{const r=JSON.parse(fs.readFileSync(path.join(base,'realtime-verification.json')));assert.equal(r.engineSha256,hash('engine.js'));assert.equal(r.catalogSha256,hash('bestiary.js'));assert.equal(r.failed,0);assert.equal(r.passed,2);assert(r.elapsedSeconds>=90);assert.equal(r.runs.length,2);assert(r.runs.every(c=>c.errors.length===0));const allBossRun=engineResult.runs.find(r=>Object.keys(r.bosses||{}).length===10);assert(allBossRun);assert(Object.values(allBossRun.bosses).every(b=>b.kills>0&&b.casts>0&&b.hazardKinds.length>0));});
check('Exact50 normal and10 boss roster, geometry and artwork bindings',()=>{const B=require('./bestiary.js');assert.equal(B.monsters.length,50);assert.equal(B.bosses.length,10);assert.equal(new Set(B.all.map(x=>x.id)).size,60);for(let i=0;i<5;i++){assert.equal(B.forBiome(i,'normal').length,10);assert.equal(B.forBiome(i,'boss').length,2);}const c=JSON.parse(fs.readFileSync(path.join(base,'bestiary-verification.json')));assert.equal(c.sha256,hash('bestiary.js'));assert(c.catalog.ok);const r=JSON.parse(fs.readFileSync(path.join(base,'render-verification.json')));assert.equal(r.sourceHashes['render.js'],hash('render.js'));assert.equal(r.sourceHashes['bestiary.js'],hash('bestiary.js'));assert.equal(r.counts.uniqueAlphaSilhouettes,60);assert.equal(r.counts.uniqueMonochromeGeometryRenders,60);assert(r.checks.southwestHazardClipAllFourShapes);assert(r.checks.coneBoundaryMatchesEngine);assert(r.checks.coneBoundaryProbes.every(p=>p.engineInside===p.expectedInside&&p.renderedTelegraphPresent===p.expectedInside));});
check('NE-only entry and retained identical hazard geometry preserve narrow V4 scope',()=>{const E=require('./engine.js'),r=JSON.parse(fs.readFileSync(path.join(base,'engine-verification-results.json')));assert.equal(r.comparisonEngineSha256,'c105ff95020831832fb230409b41cfb491b12fe13464e1cd384166e7624458d7');assert(r.pacing.some(p=>p.version==='V3')&&r.pacing.some(p=>p.version==='V4'));const collision=crypto.createHash('sha256').update(E.hazardContains.toString()).digest('hex');assert.equal(collision,'7badfd72b6f56481b386404faf8c098c99ded7b7cf951e0e21494631f51dbba2');assert(!html.includes('怪物從左上、右上與右下'));assert(html.includes('怪物統一從右上'));});
check('Independent unified-bag, selection, highlight, lifecycle and persistence UI audit',()=>{uiResult=run('verify-ui.cjs','ui.json');assert.equal(uiResult.counts.failed,0);assert(uiResult.counts.tests>=63);for(const [f,digest]of Object.entries(uiResult.sourceDigests))assert.equal(digest,hash(f));});
const report={status:'passed',version:4,saveSchemaVersion:3,groups:checks.length,checks,engineSha256:hash('engine.js'),engineChecks:engineResult.passed,legalProgressionRuns:engineResult.runs.length,uiChecks:uiResult.counts.tests,uiAssertions:uiResult.counts.assertions,inventoryItems:inventoryResult.unifiedBagItems,scope:'Source/static/VM and legal simulation gate. Retained actual-time engine trace is separate from accelerated runs. This is not actual browser or human-play acceptance.'};
const i=process.argv.indexOf('--report');if(i>=0){const dest=process.argv[i+1]?path.resolve(process.argv[i+1]):path.join(base,'verification-report.json');fs.writeFileSync(dest,JSON.stringify(report,null,2)+'\n');}
console.log(JSON.stringify(report,null,2));
