/* Transactional profile/run envelope. No legacy keys are ever read. */
(function(r,f){if(typeof module==='object'&&module.exports)module.exports=f(require('./engine.js'));else r.OrbitStorage=f(r.OrbitEngine);})(globalThis,function(E){'use strict';
const KEY='arcade.classic30.orbit-marble-chain.v2',copy=v=>JSON.parse(JSON.stringify(v));
const ok=(x,m)=>{if(!x)throw Error(m||'存檔格式不完整');},num=(x,a,b)=>Number.isInteger(x)&&x>=a&&x<=b;
function walk(v,depth=0){ok(depth<22,'存檔結構太深');if(typeof v==='number')ok(Number.isFinite(v),'非有限數字');if(v&&typeof v==='object'){ok(Object.keys(v).length<1500,'資料過大');for(const [k,x] of Object.entries(v)){ok(!['__proto__','prototype','constructor'].includes(k),'不安全欄位');walk(x,depth+1);}}}
function blank(writer){return{schema:1,game:'orbit-marble-chain',writer,revision:0,profile:{records:{},awarded:[]},run:null,session:{mode:'solo',round:1,scores:[],stage:'01',seed:E.levels[0].initial.seed},settings:{reducedMotion:false,helpOpen:false,sound:false}};}
/* A persisted outcome is a single atomic record: run, award marker and current result agree. */
function validateOutcome(p,allowPendingTerminal=false){const s=p.run,q=p.session;if(!s){ok(q.mode==='solo'&&q.round===1&&q.scores.length===0,'熱座進度缺少本局');return;}const terminal=['won','lost'].includes(s.status),awarded=p.profile.awarded.includes(s.runId);if(!terminal){ok(!awarded,'未結束的本局不能已結算');if(q.mode==='hotseat'){ok(q.scores.length===q.round-1,'本局尚未結束卻已有分數');ok(p.profile.awarded.length>=q.round-1,'缺少前一位玩家的結算紀錄');}return;}if(!awarded){ok(allowPendingTerminal,'結束的本局缺少結算紀錄');if(q.mode==='hotseat'){ok(q.scores.length===q.round-1,'未結算的本局已有結果');ok(p.profile.awarded.length>=q.round-1,'缺少前一位玩家的結算紀錄');}return;}if(q.mode==='hotseat'){ok(q.scores.length===q.round,'熱座回合與結果數量不符');const result=q.scores[q.round-1];ok(result.score===s.score&&result.shots===s.shotCount&&result.outcome===s.status,'本局結果與熱座分數不一致');ok(p.profile.awarded.length>=q.round,'缺少前一位玩家的結算紀錄');}else if(s.status==='won'){const record=p.profile.records[s.levelId];ok(record&&record.score>=s.score&&record.shots<=s.shotCount&&record.combo>=s.maxCombo,'通關紀錄與本局不一致');}}
function validate(p){ok(p&&typeof p==='object'&&!Array.isArray(p));walk(p);ok(p.schema===1&&p.game==='orbit-marble-chain','版本不符');ok(typeof p.writer==='string'&&/^[A-Za-z0-9_-]{1,90}$/.test(p.writer));ok(num(p.revision,0,1000000000));ok(p.profile&&p.profile.records&&typeof p.profile.records==='object'&&!Array.isArray(p.profile.records));for(const [id,v] of Object.entries(p.profile.records)){ok(E.levels.some(l=>l.id===id));ok(v&&num(v.score,0,100000000)&&num(v.shots,0,100000000)&&num(v.combo,0,1000000)&&num(v.wins,1,1000000));}ok(Array.isArray(p.profile.awarded)&&p.profile.awarded.length<=200&&new Set(p.profile.awarded).size===p.profile.awarded.length&&p.profile.awarded.every(x=>typeof x==='string'&&/^[A-Za-z0-9_-]{1,90}$/.test(x)));if(p.run!==null)E.validate(p.run);const q=p.session;ok(q&&['solo','hotseat'].includes(q.mode)&&num(q.round,1,2)&&Array.isArray(q.scores)&&q.scores.length<=2&&q.scores.every(v=>v&&num(v.score,0,100000000)&&num(v.shots,0,100000000)&&['won','lost'].includes(v.outcome))&&E.levels.some(l=>l.id===q.stage)&&num(q.seed,0,4294967295));ok(q.mode!=='solo'||(q.round===1&&q.scores.length===0));ok(q.mode!=='hotseat'||q.scores.length>=q.round-1);if(p.run){ok(p.run.levelId===q.stage&&p.run.seed===q.seed);if(q.mode==='hotseat')ok(q.scores.length<=q.round);}ok(p.settings&&typeof p.settings.reducedMotion==='boolean'&&typeof p.settings.helpOpen==='boolean'&&(p.settings.sound===undefined||typeof p.settings.sound==='boolean'));validateOutcome(p);return true;}
function parse(text){ok(typeof text==='string'&&text.length<800000,'備份太大');const p=JSON.parse(text);validate(p);return p;}
function read(storage,writer){const t=storage.getItem(KEY);return t===null?blank(writer):parse(t);}
function save(storage,p,expectedRevision,writer,{force=false}={}){validate(p);const previous=storage.getItem(KEY);if(previous!==null&&!force){const live=parse(previous);ok(live.revision===expectedRevision,'CONFLICT');}else if(previous===null&&!force)ok(expectedRevision===0,'CONFLICT');const next=copy(p);next.writer=writer;let base=p.revision;if(force&&previous!==null){try{base=Math.max(parse(previous).revision,base);}catch(e){/* Explicit takeover can replace a corrupt save. */}}next.revision=base+1;validate(next);storage.setItem(KEY,JSON.stringify(next));return next;}
function importSave(storage,text,current,writer){const parsed=parse(text);/* Validation and conflict detection precede the sole commit. */parsed.revision=current.revision;parsed.writer=writer;if(parsed.run?.status==='running')E.applyAction(parsed.run,{type:'pause'});return save(storage,parsed,current.revision,writer);}
function finish(p){if(!p.run||!['won','lost'].includes(p.run.status))return false;validateOutcome(p,true);if(p.profile.awarded.includes(p.run.runId))return false;const s=p.run;p.profile.awarded.push(s.runId);p.profile.awarded=p.profile.awarded.slice(-200);if(p.session.mode==='hotseat'){p.session.scores.push({score:s.score,shots:s.shotCount,outcome:s.status});}else if(s.status==='won'){const old=p.profile.records[s.levelId];p.profile.records[s.levelId]={score:Math.max(old?.score||0,s.score),shots:old?Math.min(old.shots,s.shotCount):s.shotCount,combo:Math.max(old?.combo||0,s.maxCombo),wins:(old?.wins||0)+1};}return true;}
function nextPlayer(p,runId){validate(p);ok(typeof runId==='string'&&/^[A-Za-z0-9_-]{1,90}$/.test(runId)&&!p.profile.awarded.includes(runId),'新回合識別碼不可重複');ok(p.session.mode==='hotseat'&&p.session.round===1&&p.session.scores.length===1&&p.run&&['won','lost'].includes(p.run.status),'尚未輪到下一位');p.session.round=2;p.run=E.createScenario(p.session.stage,{seed:p.session.seed,runId});return p;}
function result(p){if(p.session.scores.length!==2)return null;validateOutcome(p);const[a,b]=p.session.scores;if(a.score===b.score&&a.shots===b.shots)return '平手';if(a.score!==b.score)return a.score>b.score?'玩家一獲勝':'玩家二獲勝';return a.shots<b.shots?'玩家一以較少發射獲勝':'玩家二以較少發射獲勝';}
return Object.freeze({KEY,blank,validate,parse,read,save,importSave,finish,nextPlayer,result});});
