'use strict';
// Purpose-built HTML/SVG event simulation, not a rendering engine or browser QA substitute.
const fs=require('fs'),path=require('path'),vm=require('vm');
const decode=s=>String(s).replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&#39;/g,"'");
const descendants=n=>n.children.flatMap(x=>[x,...descendants(x)]);
function matches(el,selector){if(selector.includes(' ')&&!selector.includes('[')){const parts=selector.split(/\s+/);const last=parts.pop();if(!matches(el,last))return false;let parent=el.parentNode;while(parent){if(matches(parent,parts.join(' ')))return true;parent=parent.parentNode;}return false;}if(selector.includes(',')&&!selector.includes('['))return selector.split(',').some(s=>matches(el,s.trim()));let s=selector;const attrs=[...s.matchAll(/\[([^=\]]+)(?:="([^"]*)")?\]/g)];s=s.replace(/\[[^\]]+\]/g,'');const tag=s.match(/^[\w-]+/),id=s.match(/#([\w-]+)/),classes=[...s.matchAll(/\.([\w-]+)/g)].map(m=>m[1]);if(tag&&el.tagName!==tag[0].toUpperCase()||id&&el.id!==id[1]||classes.some(c=>!el.className.split(/\s+/).includes(c)))return false;return attrs.every(([,k,v])=>{const value=k==='open'?(el.open?'':null):el.getAttribute(k);return value!==null&&(v===undefined||value===v);});}
class Element{constructor(tag,doc){this.tagName=tag.toUpperCase();this.ownerDocument=doc;this.children=[];this.parentNode=null;this.dataset={};this.attributes={};this.events={};this.disabled=false;this.hidden=false;this.value='';this.open=false;this.style={};this._text='';this.className='';this.id='';this.tabIndex=-1;}
set innerHTML(html){this.children=[];this._html=String(html);this._text='';const stack=[this];for(const token of String(html).match(/<[^>]+>|[^<]+/g)||[]){if(token.startsWith('</')){const tag=token.match(/^<\/([\w-]+)/)?.[1]?.toUpperCase();while(stack.length>1){const popped=stack.pop();if(popped.tagName===tag)break;}continue;}if(token.startsWith('<')){const match=/^<([\w-]+)/.exec(token);if(!match)continue;const el=new Element(match[1],this.ownerDocument),raw=token.slice(match[0].length).replace(/\/?\s*>$/,'');for(const m of raw.matchAll(/([\w-]+)(?:="([^"]*)")?/g))el.setAttribute(m[1],decode(m[2]??''));stack.at(-1).append(el);if(!token.endsWith('/>')&&!['INPUT','BR','HR','META','LINK','IMG'].includes(el.tagName))stack.push(el);}else stack.at(-1)._text+=decode(token);}}
get innerHTML(){return this._html||'';}set textContent(v){this._text=String(v);this.children=[];}get textContent(){return this._text+this.children.map(x=>x.textContent).join('');}append(...nodes){for(const n of nodes){n.parentNode=this;this.children.push(n);if(this.tagName==='SELECT'&&n.tagName==='OPTION'&&(!this.value||n.getAttribute('selected')!==null))this.value=n.value;}}remove(){if(this.parentNode)this.parentNode.children=this.parentNode.children.filter(x=>x!==this);this.parentNode=null;}setAttribute(k,v){v=String(v);this.attributes[k]=v;if(k==='id')this.id=v;if(k==='class')this.className=v;if(k==='value')this.value=v;if(k==='disabled')this.disabled=true;if(k==='hidden')this.hidden=true;if(k==='checked')this.checked=true;if(k.startsWith('data-'))this.dataset[k.slice(5).replace(/-([a-z])/g,(_,c)=>c.toUpperCase())]=v;}getAttribute(k){if(k==='id')return this.id||null;if(k==='class')return this.className||null;return this.attributes[k]??null;}addEventListener(t,fn){(this.events[t]||=[]).push(fn);}removeEventListener(t,fn){this.events[t]=(this.events[t]||[]).filter(f=>f!==fn);}fire(type,extra={}){if(type==='click'&&this.disabled)return;const e={type,target:this,key:'',preventDefault(){this.defaultPrevented=true;},...extra};for(const f of this.events[type]||[])f(e);return e;}click(){this.fire('click');}focus(){this.ownerDocument.activeElement=this;}closest(s){let p=this;while(p){if(matches(p,s))return p;p=p.parentNode;}return null;}getBoundingClientRect(){return {left:0,top:0,width:640,height:320};}matches(s){return matches(this,s);}querySelectorAll(s){return descendants(this).filter(n=>matches(n,s));}querySelector(s){return this.querySelectorAll(s)[0]||null;}showModal(){this.open=true;}close(){this.open=false;this.fire('close');}}

const {FakeAudioContext,Timers}=require('./mock-audio.cjs');
function boot(slug,storage=new Map()){
const root=path.resolve(__dirname,'..'),html=fs.readFileSync(path.join(root,slug+'.html'),'utf8'),timers=new Timers(),doc={events:{},activeElement:null,hidden:false,createElement(tag){return new Element(tag,this);},getElementById(id){return descendants(this.body).find(n=>n.id===id)||null;},querySelectorAll(s){return this.body.querySelectorAll(s);},querySelector(s){return this.querySelectorAll(s)[0]||null;},addEventListener(t,f){(this.events[t]||=[]).push(f);}};
doc.body=new Element('body',doc);doc.body.setAttribute('data-game',slug);doc.body.innerHTML=html.match(/<body[^>]*>([\s\S]*)<\/body>/)[1];const errors=[],windowEvents={};
const ctx={document:doc,console,localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},AudioContext:FakeAudioContext,performance:{now:()=>100},setInterval:timers.setInterval.bind(timers),clearInterval:timers.clearInterval.bind(timers),setTimeout:timers.setTimeout.bind(timers),clearTimeout:timers.clearTimeout.bind(timers),addEventListener(t,f){(windowEvents[t]||=[]).push(f);},Blob:class{constructor(a){this.content=a;}},URL:{createObjectURL:()=>'blob:test',revokeObjectURL(){}}};ctx.window=ctx;ctx.globalThis=ctx;vm.createContext(ctx);for(const m of html.matchAll(/<script[^>]*src="([^"]+)"/g))vm.runInContext(fs.readFileSync(path.join(root,m[1]),'utf8'),ctx,{filename:m[1]});
function get(sel){const n=doc.querySelector(sel);if(!n)throw Error('Missing '+slug+' UI '+sel);return n;}
async function fire(target,type,extra={}){const event={type,target,key:'',preventDefault(){},...extra};for(const fn of doc.events[type]||[])await fn(event);}
return{doc,ctx,storage,errors,timers,controller:ctx.Music120App,get,fire,click:sel=>fire(get(sel),'click'),act:a=>fire(get('[data-act="'+a+'"]'),'click'),field:async(path,value)=>{const t=get('[data-field="'+path+'"]');t.value=value;await fire(t,'input');await fire(t,'change');},selectLevel:async(n)=>{const t=get('#level');t.value=n;await fire(t,'change');},key:key=>fire(doc.body,'keydown',{key}),windowEvent:async(name)=>{for(const f of windowEvents[name]||[])await f();},snapshot:()=>JSON.parse(JSON.stringify(ctx.Music120App.getState())),run:code=>vm.runInContext(code,ctx)};}
module.exports={boot,Element};
