'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto'),E=require('./engine.js'),catalog=require('./catalog.json'),report=require('./verification-report.json');
const root=path.resolve(__dirname,'../..'),hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
for(const [file,digest]of Object.entries(report.sourceFiles))if(hash(path.join(root,file))!==digest)throw Error('Source changed after verifier: '+file);
const policies={
'sound-collection':['arranger','Alternates only collected sound types, leaving every third cell silent.','Collected sound IDs and current composition.'],
'loop-garden':['arranger','Fills only currently empty slots of each independent cycle with consonant notes.','Plant lengths, public note cells and plant index.'],
'foley-studio':['arranger','Aligns cues to public film timings; chooses final sound from current object selection.','Public film timeline and selected prop.'],
'timbre-alchemy':['coach','Chooses a complementary waveform and attack based on cutoff and release.','Current synthesis controls.'],
'spatial-orchestra':['arranger','Places three sources around the current listener.','Visible listener coordinates and source array.'],
'melody-graft':['teammate','Appends one bar, preserves motif head and rises/falls based on previous mean pitch.','Public motif, previous bar, current turn and twelve-bar limit.'],
'echo-architect':['none','No AI claimed; constructive reference and measured feedback.','Not applicable.'],
'story-score':['arranger','Uses character pitch ranges and public scene ordering to choose instrument/tempo.','Editable character motifs and public four-cue story.'],
'silent-composer':['arranger','Spaces note onsets and removes events until sounding-time union fits the budget.','Current slots, release time and budget.'],
'soundscape-terrarium':['coach','Adjusts activity probabilities to current day/night condition.','Current rain/bird/insect probabilities and cycle.'],
'instrument-inventor':['none','No AI claimed; constructive reference and measured feedback.','Not applicable.'],
'sound-camouflage':['arranger','Author-side helper chooses mask intensity from the selected secret type.','Author-visible secret; never presented as a blind solver.'],
'same-tune-scenes':['arranger','Suggests major/minor quality from melody accents and chosen chord roots.','Public immutable melody and editable chord roots.'],
'graphic-score':['arranger','Fills alternating empty columns by neighboring height and recent color.','Current painted cells and selected color.'],
'sound-relay':['teammate','One operation based on duration, average frequency and turn parity.','Current clip and turn; no hidden state.']};
const manifest={schemaVersion:1,family:'music',status:'implementation-awaiting-independent-review',games:catalog.map(g=>{const based=!!E.level(g.id,1),p=policies[g.id];return {id:g.id,title:g.title,entry:'games/'+g.id+'.html',engine:'games/music120-common/engine.js',controller:'games/music120-common/app.js',audio:'games/music120-common/audio.js',artFile:g.artFile,levelBased:based,levelCount:based?100:0,...based?{levels:'games/'+g.id+'/levels.json',levelRecordPath:[],proof:{kind:'validated-parameter-action-construction',path:'games/'+g.id+'/proofs.json',recordPath:[],claim:g.id==='echo-architect'?'All 100 documented one-dimensional delay/amplitude targets admit an action-replayed wall/material construction; alternate constructions accepted. No full room-acoustics claim.':'All 100 ideal string/closed-pipe/membrane pitch-span targets admit an action-replayed design, with independent formula checks and alternate constructions. No real-instrument engineering claim.'}}:{mode:g.id==='sound-camouflage'?'user-authored-creative-listening-sandbox':'creative-sandbox'},ai:{kind:p[0],policy:p[1],information:p[2],externalServices:false},distinctness:{method:based?'Physical target canonicalization excludes task IDs and titles; 100 unique acoustic/tuning constraints.':'Different editor, composition rule model, event parameterization and independently hashed numerical waveform.',evidencePath:'games/music120-common/verification-report.json'}};}),commands:[['node','games/music120-common/verify.cjs'],['node','games/music120-common/verify.cjs','--check-report']],generationCommand:['node','games/music120-common/generate.cjs'],finalizationCommand:['node','games/music120-common/finalize.cjs'],freshReports:['games/music120-common/verification-report.json','games/music120-common/dom-verification-report.json'],sourceFiles:report.sourceFiles,claims:{browserTesting:false,physicalDeviceAudioListening:false,allGamesHaveLevels:false,allSolutionsUnique:false,allOpponentWinsForced:false,noObjectiveAestheticJudgment:true},counts:{games:15,levelBasedGames:2,creativeSandboxes:13,levels:200},limits:['Idealized one-dimensional echo and modal instrument equations; not certified acoustical engineering.','WebAudio scheduling tested with graph mocks; numerical renderer is not bit-identical to native audio.','No physical-device audition or browser layout/visual claim in family report.','Pause rearticulates an overlapping voice with a fresh envelope.','No remote AI, accounts, microphone, external assets or network multiplayer.']};
fs.writeFileSync(path.join(__dirname,'release-manifest.json'),JSON.stringify(manifest,null,2)+'\n');console.log('Music manifest bound to '+Object.keys(report.sourceFiles).length+' source/art/corpus files');
