(function(){'use strict';
const E=PegEngine,S=PegSession,levels=PEG_LEVELS,$=id=>document.getElementById(id),KEY='arcade.peg-solitaire.v1';
let index=0,actions=[],states=[],seconds=0,assisted=false,progress={},selected=null,hintMove=null,focusCell=null,playing=false,busy=false,playTimer=null,worker=null,searchTimer=null,operation=0,confirmAction=null,message='',storageOK=true;
let proofStates=[];
const level=()=>levels[index],state=()=>states.at(-1),won=()=>E.won(level(),state()),time=n=>Math.floor(n/60)+':'+String(Math.floor(n%60)).padStart(2,'0'),coord=i=>`${Math.floor(i/level().width)+1} 列 ${i%level().width+1} 欄`;
function save(){try{localStorage.setItem(KEY,JSON.stringify({version:1,index,actions,seconds,assisted,progress}));storageOK=true;}catch(_){storageOK=false;}$('save').textContent=storageOK?'進度已保存在此瀏覽器'+(assisted?' · 本局已使用輔助':''):'此瀏覽器無法儲存；仍可遊玩，離開後進度可能遺失';}
function stop(announce=false){operation++;clearTimeout(playTimer);clearTimeout(searchTimer);if(worker)worker.terminate();worker=null;playing=false;busy=false;if(announce)message='已停止，你可以接著思考';}
function bestText(){const b=progress[index];return b?`最佳：${time(b.seconds)} · ${b.assisted?'輔助完成':'自行完成'}`:'最佳紀錄：尚未完成';}
function options(){const v=index;$('level').replaceChildren(...levels.map((l,i)=>{const o=document.createElement('option');o.value=i;o.textContent=`${progress[i]?'✓ ':''}${String(i+1).padStart(2,'0')} · ${l.name} · ${l.pegs.length} 顆${l.goal!==null?' ★':''}`;return o;}));$('level').value=v;}
function mount(){const l=level();proofStates=E.proof(l);$('board').style.gridTemplateColumns=`repeat(${l.width},1fr)`;$('board').replaceChildren();for(let i=0;i<l.width*l.height;i++){const c=document.createElement(l.cells.includes(i)?'button':'span');if(l.cells.includes(i)){c.className='cell';c.dataset.cell=i;c.type='button';c.addEventListener('click',()=>click(i));c.addEventListener('focus',()=>{focusCell=i;for(const b of $('board').querySelectorAll('button'))b.tabIndex=Number(b.dataset.cell)===i?0:-1;});}else{c.className='void';c.setAttribute('aria-hidden','true');}$('board').append(c);}focusCell=state()[0]??l.cells[0];}
function render(){const l=level(),s=state(),done=won(),legal=E.moves(l,s),dest=selected===null?[]:legal.filter(m=>m.from===selected).map(m=>m.to);for(const b of $('board').querySelectorAll('button')){const i=Number(b.dataset.cell),peg=s.includes(i);b.className='cell'+(peg?' peg':'')+(i===selected?' selected':'')+(dest.includes(i)?' destination':'')+(i===l.goal?' goal':'')+(hintMove&&(i===hintMove.from||i===hintMove.to)?' hint':'');b.disabled=done||playing||busy;b.tabIndex=i===focusCell?0:-1;b.setAttribute('aria-pressed',String(i===selected));b.setAttribute('aria-label',`${coord(i)}，${peg?'有棋子':'空位'}${i===l.goal?'，指定終點':''}${dest.includes(i)?'，可跳入':''}${hintMove&&i===hintMove.from?'，提示起點':''}${hintMove&&i===hintMove.to?'，提示落點':''}`);}
$('remaining').innerHTML=s.length+'<span>顆</span>';$('moves').textContent=actions.length;$('timer').textContent=time(seconds);$('progress').innerHTML=Object.keys(progress).length+'<span>/ 50</span>';$('boardTitle').textContent=`第 ${String(index+1).padStart(2,'0')} 關 · ${l.name}`;$('levelInfo').textContent=`${l.pegs.length} 顆 → 1 顆 · ${l.pegs.length-1} 次跳躍\n${l.goal===null?'最後一顆可停在任何格':'★ 最後一顆須停在星形格'}`;$('best').textContent=bestText();$('next').disabled=index===levels.length-1;$('undo').disabled=!actions.length||busy||playing;$('hint').disabled=done||busy||playing;$('solution').disabled=done||busy||playing;$('solution').hidden=playing||busy;$('stop').hidden=!playing&&!busy;$('stop').textContent=busy?'■ 停止分析':'■ 停止播放';$('win').hidden=!done;if(done){$('winDetail').textContent=`${actions.length} 次跳躍 · ${time(seconds)} · ${assisted?'輔助完成':'自行完成'}。${index===49?'你已來到最後一關！':'可以前往下一關了'}`;}$('status').textContent=message||(done?'這一局完成了':!legal.length?'目前已無合法跳躍；復原幾步，再試另一條路':l.goal!==null?'最後一顆要停在星形格；先點棋子，再點落點':'先點一顆棋子，再點可跳入的空位');}
function finish(){if(!won())return;stop();const b={moves:actions.length,seconds,assisted,witness:actions.map(a=>({...a}))},old=progress[index];if(!old||old.assisted&&!b.assisted||old.assisted===b.assisted&&b.seconds<old.seconds)progress[index]=b;options();message='棋庭安靜下來了，恭喜完成！';}
function perform(a){states.push(E.step(level(),state(),a));actions.push({from:a.from,over:a.over,to:a.to});selected=null;hintMove=null;focusCell=a.to;message='';finish();save();render();}
function click(i){if(won()||playing||busy)return;hintMove=null;focusCell=i;if(state().includes(i)){selected=selected===i?null:i;const n=E.moves(level(),state()).filter(m=>m.from===selected).length;message=selected===null?'已取消選取':n?`已選 ${coord(i)}，點金色落點完成跳躍`:'這顆棋子目前不能跳，請換一顆';render();return;}if(selected!==null){const a=E.moves(level(),state()).find(m=>m.from===selected&&m.to===i);if(a){perform(a);$('board').querySelector(`[data-cell="${i}"]`).focus();return;}}message='只能直線跳過相鄰的一顆棋子，落在兩格外的空位';render();}
function start(i){stop();index=i;actions=[];states=[E.initial(level())];seconds=0;assisted=false;selected=null;hintMove=null;message='';options();mount();save();render();}
function confirm(text,fn){stop();render();confirmAction=fn;$('confirmText').textContent=text;$('confirmDialog').showModal();}
function requestStart(i){if(actions.length&&!won())confirm('目前棋局尚未完成，繼續會清除這一局的步驟紀錄。完成紀錄仍會保留。',()=>start(i));else start(i);}
async function route(){for(let i=0;i<proofStates.length;i++)if(E.equal(state(),proofStates[i]))return level().solution.slice(i);const token=++operation;busy=true;message='正在分析目前局面，請稍候…';render();const l=level(),s=state().slice();return new Promise(resolve=>{let settled=false;const finish=r=>{if(settled)return;settled=true;clearTimeout(searchTimer);if(worker)worker.terminate();worker=null;if(token!==operation){resolve(null);return;}busy=false;resolve(r.solution);};try{worker=new Worker('peg-solitaire/solver-worker.js');worker.onmessage=e=>finish(e.data);worker.onerror=()=>{finish(E.solve(l,s,15000));};worker.postMessage({level:l,state:s});searchTimer=setTimeout(()=>finish({solution:null}),6000);}catch(_){setTimeout(()=>finish(E.solve(l,s,15000)),10);}});}
async function assist(play){if(won()||busy||playing)return;const before=state().join(','),current=index,pending=route(),request=operation;const seq=await pending;if(operation!==request||index!==current||state().join(',')!==before)return;if(!seq||!seq.length){message='暫未找到目前局面的解答；可能已無解或超過搜尋上限。請復原幾步，或重玩本局後看解答';render();return;}assisted=true;hintMove=seq[0];message=`提示：${coord(seq[0].from)} → ${coord(seq[0].to)}，跳過中間棋子`;save();if(!play){render();return;}playing=true;const token=++operation;let p=0;function tick(){if(token!==operation||!playing)return;if(p>=seq.length){stop();render();return;}const a=seq[p++];if(!E.legal(level(),state(),a)){stop();message='局面已改變，播放已停止';render();return;}perform(a);if(playing){message='解答播放中，可隨時停止並接手';render();playTimer=setTimeout(tick,650);}}render();playTimer=setTimeout(tick,550);}
$('level').addEventListener('change',e=>{const n=Number(e.target.value);e.target.value=index;if(Number.isInteger(n)&&n>=0&&n<levels.length)requestStart(n);});$('restart').addEventListener('click',()=>{if(actions.length||seconds>0)confirm('重來會清除本局步驟與時間。已完成的紀錄仍會保留。',()=>start(index));else start(index);});$('next').addEventListener('click',()=>{if(index<49)requestStart(index+1);});$('undo').addEventListener('click',()=>{if(!actions.length||playing||busy)return;stop();actions.pop();states.pop();selected=null;hintMove=null;message='已復原上一個跳躍';save();render();});$('hint').addEventListener('click',()=>assist(false));$('solution').addEventListener('click',()=>assist(true));$('stop').addEventListener('click',()=>{stop(true);render();});$('help').addEventListener('click',()=>{stop();render();$('helpDialog').showModal();});$('closeHelp').addEventListener('click',()=>$('helpDialog').close());$('cancelConfirm').addEventListener('click',()=>{confirmAction=null;$('confirmDialog').close();});$('acceptConfirm').addEventListener('click',()=>{const fn=confirmAction;confirmAction=null;$('confirmDialog').close();if(fn)fn();});$('confirmDialog').addEventListener('cancel',()=>{confirmAction=null;});
$('board').addEventListener('keydown',e=>{const i=Number(e.target.dataset.cell);if(!Number.isInteger(i)||!level().cells.includes(i))return;if(e.key==='Escape'){selected=null;hintMove=null;message='已取消選取';render();return;}const d={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]}[e.key];if(!d)return;e.preventDefault();let x=i%level().width+d[0],y=Math.floor(i/level().width)+d[1];while(x>=0&&x<level().width&&y>=0&&y<level().height){const n=y*level().width+x;if(level().cells.includes(n)){$('board').querySelector(`[data-cell="${n}"]`).focus();break;}x+=d[0];y+=d[1];}});
let recovered=false;try{const raw=localStorage.getItem(KEY);if(raw){const v=S.restore(JSON.parse(raw),levels,E);({index,actions,states,seconds,assisted,progress}=v);recovered=true;}}catch(_){message='無法讀取有效存檔，已安全建立新棋局';}if(!recovered)states=[E.initial(level())];options();mount();if(recovered)message=won()?'已還原完成棋局':'已還原並驗證上次進度';render();save();setInterval(()=>{if(!document.hidden&&!won()&&!$('helpDialog').open&&!$('confirmDialog').open){seconds++;$('timer').textContent=time(seconds);if(seconds%5===0)save();}},1000);document.addEventListener('visibilitychange',()=>{if(document.hidden){stop();save();render();}});window.addEventListener('pagehide',()=>{stop();save();});
})();
