'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),vm=require('node:vm');
const {ids}=require('./generate.cjs'),UI=require('./ui.js');
globalThis.ArcadeChallenge=require('../challenge-common/core.js');require('../challenge-common/ui.js');
class Element{
 constructor(tag,doc){this.tagName=tag;this.ownerDocument=doc;this.children=[];this.attributes={};this.events={};this.dataset={};this.style={};this.className='';this.hidden=false;this.disabled=false;this._text='';this.open=false;}
 set textContent(v){this._text=String(v);this.children=[];}get textContent(){return this._text+this.children.map(c=>c.textContent).join('');}
 append(...children){for(const c of children){c.parentNode=this;this.children.push(c);}}replaceChildren(...c){this.children=[];this._text='';this.append(...c);}
 setAttribute(k,v){this.attributes[k]=String(v);if(k==='open')this.open=true;if(k==='class')this.className=String(v);}getAttribute(k){return this.attributes[k]??null;}
 addEventListener(k,fn){(this.events[k]??=new Set()).add(fn);}removeEventListener(k,fn){this.events[k]?.delete(fn);}emit(k,extra={}){const e={target:this,preventDefault(){this.defaultPrevented=true;},...extra};if(k==='click'&&this.disabled)return e;for(const fn of [...this.events[k]||[]])fn(e);return e;}
 focus(){this.ownerDocument.activeElement=this;}showModal(){this.open=true;}close(){this.open=false;this.emit('close');}remove(){if(this.parentNode)this.parentNode.children=this.parentNode.children.filter(c=>c!==this);}all(){return [this,...this.children.flatMap(c=>c.all())];}
}
function document(){const d={events:{},createElement(tag){return new Element(tag,d);},createElementNS(ns,tag){return new Element(tag,d);},addEventListener(k,f){(d.events[k]??=new Set()).add(f);},removeEventListener(k,f){d.events[k]?.delete(f);},emit(k){for(const f of d.events[k]||[])f();}};return d;}
function store(){const values={};return {values,getItem:k=>values[k]??null,setItem:(k,v)=>values[k]=v};}
const stable=a=>JSON.stringify(Object.fromEntries(Object.entries(a).sort(([a],[b])=>a.localeCompare(b))));
let assertions=0,clicks=0;const ok=(x,m)=>{assert(x,m);assertions++;},eq=(a,b,m)=>{assert.deepEqual(a,b,m);assertions++;};
const reports=[];
for(const id of ids){const data=require('../'+id+'/data.js'),engine=require('../'+id+'/engine.js'),view=require('../'+id+'/view.js'),doc=document(),root=doc.createElement('main'),storage=store(),app=UI.mount(id,root,{data,engine,view},ArcadeChallenge,doc,storage),c=app.controller;
 const nodes=()=>root.all(),find=(tag,text)=>nodes().find(n=>n.tagName===tag&&(text===undefined||n.textContent===text)),buttons=text=>nodes().filter(n=>n.tagName==='button'&&n.textContent===text),selector=()=>nodes().find(n=>n.className==='ac-select');
 const select=(key,value)=>{const n=nodes().find(n=>n.tagName==='select'&&n.dataset.key===key);ok(n,'select '+id+' '+key);if(n.value!==String(value)){n.value=String(value);n.emit('change');}};
 function manual(a){if(a.cell!==undefined&&['museum-curator','deep-sea-treasure'].includes(id)){const b=nodes().find(n=>n.dataset.cell===String(a.cell));ok(b,'map cell');b.emit('click');clicks++;if(id==='deep-sea-treasure')return;}
 if(id==='hotel-manager'){if(a.type==='checkin')select('guest-'+a.room,a.guest);if(a.type==='clean')select('clean-'+a.room,a.worker);if(a.type==='serve')select('serve-'+c.snapshot().state.rooms.findIndex(r=>r.guest===a.guest),a.worker);}
 if(id==='museum-curator'&&a.type==='place')select('exhibit',a.exhibit);
 if(id==='theater-manager'){if(a.type==='cast')select('cast-'+a.show+'-'+a.role,a.actor);if(a.type==='schedule')for(const k of ['show','slot','stage','kind'])select(k,a[k]);if(a.type==='unschedule')select('event',a.event);}
 if(id==='tower-defense'){if(a.type==='build')select('pad',a.pad);if(a.type==='upgrade')select('pad',c.snapshot().state.towers[a.tower].pad);}
 if(id==='conservation-park'&&a.type==='move'){select('to-'+a.patch,a.to);select('species-'+a.patch,a.species);}
 if(id==='alchemy-lab'&&a.type==='brew'){for(const [key,v]of [['first',a.a],['second',a.b],['tool',a.tool],['heat',a.heat]])select(key,v);a={...a,a:Math.min(a.a,a.b),b:Math.max(a.a,a.b)};}
 const node=nodes().find(n=>n.dataset.action&&stable(JSON.parse(n.dataset.action))===stable(a));ok(node,'visible action '+id+' '+JSON.stringify(a));ok(!node.disabled,'enabled action '+id+' '+JSON.stringify(a));node.emit('click');clicks++;}
 eq(selector().children.length,100);let completed=0,manualCount=0;
 for(const levelId of ['001','050','100']){selector().value=levelId;selector().emit('change');eq(c.snapshot().levelId,levelId);const l=data.levels.find(x=>x.id===levelId),initial=c.snapshot().state;const stale=nodes().find(n=>n.dataset.action&&!n.disabled);find('button','提示').emit('click');eq(c.snapshot().state,initial,'hint does not change board');ok(c.snapshot().assisted);
 if(stale){const before=c.snapshot().state;stale.emit('click');eq(c.snapshot().state,before,'stale detached controls ignored');}
 for(const a of data.witnesses[levelId].actions){manual(a);manualCount++;}ok(c.snapshot().inspection.goalMet,id+' actual DOM manual win '+levelId);completed++;eq(c.snapshot().progress.completed,completed);ok(c.snapshot().assisted);const final=c.snapshot().state;const bad=c.dispatch({type:'not-an-action'});ok(!bad.ok);eq(c.snapshot().state,final);
 const reset=buttons('重新開始')[0],confirm=buttons('重新開始')[1],cancel=find('button','保留盤面'),dialog=find('dialog');reset.emit('click');ok(dialog.open);cancel.emit('click');ok(!dialog.open);eq(c.snapshot().state,final);reset.emit('click');dialog.emit('cancel');confirm.emit('click');eq(c.snapshot().state,final,'stale confirmation cancelled');reset.emit('click');confirm.emit('click');eq(c.snapshot().state,engine.createState(l));const attempts=c.snapshot().attempts;confirm.emit('click');eq(c.snapshot().attempts,attempts);eq(c.snapshot().progress.completed,completed);
 if(levelId==='050'){const before=c.snapshot().state,prior=c.snapshot().progress.completed;find('button','解答示範').emit('click');eq(c.snapshot().mode,'replay');for(let k=0;k<data.witnesses[levelId].actions.length;k++)find('button','示範下一步').emit('click');ok(c.snapshot().inspection.goalMet);eq(c.snapshot().progress.completed,prior,'replay does not grant completion');find('button','返回我的盤面').emit('click');eq(c.snapshot().state,before);}
 }
 c.select('002');const invalidBefore=c.snapshot().state;ok(!c.dispatch({type:'not-an-action'}).ok);eq(c.snapshot().state,invalidBefore);ok(nodes().some(n=>n.getAttribute('role')==='status'));ok(nodes().filter(n=>n.tagName==='select').every(n=>n.getAttribute('aria-label')));
 if(id==='tower-defense'){const realSet=globalThis.setInterval,realClear=globalThis.clearInterval;let next=0;const timers=new Map();globalThis.setInterval=f=>{timers.set(++next,f);return next;};globalThis.clearInterval=n=>timers.delete(n);try{for(const a of data.witnesses['002'].actions){manual(a);if(a.type==='start')break;}find('button','自動推進時間').emit('click');eq(timers.size,1);[...timers.values()][0]();eq(c.snapshot().state.tick,1);app.pause();eq(timers.size,0,'public pause cancels autoplay');find('button','自動推進時間').emit('click');doc.hidden=true;doc.emit('visibilitychange');eq(timers.size,0,'hidden document cancels autoplay');doc.hidden=false;find('button','自動推進時間').emit('click');c.select('003');eq(timers.size,0,'navigation cancels autoplay');}finally{globalThis.setInterval=realSet;globalThis.clearInterval=realClear;}}
 c.select('004');c.dispatch(data.witnesses['004'].actions[0]);const saved=c.snapshot().state;c.flush();const reloaded=ArcadeChallenge.createController({gameId:id,revision:data.revision,levels:data.levels,engine,storage});eq(reloaded.snapshot().state,saved,'save/reload');reloaded.destroy();const denied=ArcadeChallenge.createController({gameId:id,revision:data.revision,levels:data.levels,engine,storage:{getItem(){throw Error('denied');},setItem(){throw Error('quota');}}});ok(denied.snapshot().storageWarning);ok(denied.dispatch(data.witnesses['001'].actions[0]).ok);denied.destroy();const corrupted=store();corrupted.setItem('arcade:challenge:v1:'+id,'{invalid json');const recovered=ArcadeChallenge.createController({gameId:id,revision:data.revision,levels:data.levels,engine,storage:corrupted});eq(recovered.snapshot().state,engine.createState(data.levels[0]));recovered.destroy();const lifecycle={};doc.body={dataset:{game:id}};doc.getElementById=()=>root;vm.runInNewContext(fs.readFileSync(path.join(__dirname,'bootstrap.js'),'utf8'),{document:doc,ManagementGames:{[id]:{data,engine,view}},ManagementUI:{mount:()=>app},ArcadeChallenge,localStorage:storage,addEventListener:(name,fn)=>lifecycle[name]=fn});lifecycle.blur();ok(root.children.length>0,'blur preserves game');lifecycle.pagehide({persisted:true});ok(root.children.length>0,'bfcache pagehide preserves game');ok(c.select('005').ok,'bfcache game remains usable');lifecycle.pagehide({persisted:false});app.destroy();eq(root.children.length,0);eq(doc.events.visibilitychange.size,0);
 const report={gameId:id,passed:true,manualWinLevels:['001','050','100'],manualActionClicks:manualCount,levelCount:100,scope:'Actual per-game renderer and shared lifecycle in simulated DOM. Not a real browser or visual-layout pass.',coverage:['100-entry selector','three complete manual UI wins','selection and map clicks','stale control invalidation','hint nonmutation and assistance','separate proof replay without progress grant','reset confirm/cancel/Escape/repeated callback','invalid action atomicity','saved-state reload','corrupt and denied storage','DOM status labels','listener cleanup','actual bootstrap blur and pagehide lifecycle','bfcache pause/save retains usable controller',...(id==='tower-defense'?['autoplay fixed-tick dispatch','autoplay cancellation on navigation']:[])],browserQA:{status:'not-run',reason:'Local browser preview is unavailable; simulated DOM is not visual QA.'}};fs.writeFileSync(path.join(__dirname,'..',id,'controller-report.json'),JSON.stringify(report,null,2)+'\n');reports.push(report);console.log(id+': '+manualCount+' manual UI actions passed');}
const summary={passed:true,games:reports.length,assertions,clicks,reports};fs.writeFileSync(path.join(__dirname,'controller-report.json'),JSON.stringify(summary,null,2)+'\n');console.log(JSON.stringify({passed:true,games:reports.length,assertions,clicks}));
