(function(C){const{act,rng,shuffle,key,path,DIRS,grid}=C;
function options(o,kind){const network=kind==='root'?o.roots:o.stems,out=new Map();for(const p of network)for(const d of DIRS){const x=p[0]+d.dx,y=p[1]+d.dy,k=key(x,y);if(x<0||x>=7||y<0||y>=8||(kind==='root'?y<5:y>4)||o.stones.includes(k)||network.some(q=>key(...q)===k))continue;out.set(k,[x,y]);}return [...out.values()];}
function nextGrowth(o){if(!o.roots.some(p=>o.wells.some(w=>key(...w)===key(...p)))){let best=null;for(const p of o.roots)for(const w of o.wells){const route=path(7,8,p,w,[...o.stones,...Array.from({length:35},(_,i)=>key(i%7,Math.floor(i/7)))]);if(route?.length&&(!best||route.length<best.route.length))best={p,route};}if(best){const d=DIRS.find(d=>d.key===best.route[0]);return{kind:'root',pos:[best.p[0]+d.dx,best.p[1]+d.dy]};}}let best=null;for(const target of o.fruits.filter(t=>!o.stems.some(p=>key(...p)===key(...t))))for(const p of o.stems){const route=path(7,5,p,target,o.stones);if(route?.length&&(!best||route.length<best.route.length))best={p,route};}if(best){const d=DIRS.find(d=>d.key===best.route[0]);return{kind:'stem',pos:[best.p[0]+d.dx,best.p[1]+d.dy]};}return null;}
C.register('plant-gardener',{
roles:['植物','園丁'],icon:'❧',color:'#a4d584',intro:'植物自行選擇根莖方向；園丁移動燈光、為接通水源的根澆水，架好新枝條的支架。',help:['先把地下根系伸到藍色水源。根不耗水，地上每次生長消耗一份水。','植物點生長位置先提出需求，再次點同位置才真正長出。園丁在兩次操作間調光、澆水和搭架。','每根新莖必須有支架與同列燈光。觸及所有果實格即可完成，可自由分枝、繞開石頭。'],
generate(n){const r=rng(n*937),fruits=shuffle(Array.from({length:21},(_,i)=>[i%7,Math.floor(i/7)]),r).slice(0,2+n%4),wells=shuffle(Array.from({length:7},(_,x)=>[x,7]),r).slice(0,1+n%3);let stones=[];for(let y=0;y<8;y++)for(let x=0;x<7;x++)if(!fruits.some(p=>key(...p)===key(x,y))&&!wells.some(p=>key(...p)===key(x,y))&&key(x,y)!=='3,4'&&key(x,y)!=='3,5'&&r()<.12)stones.push(key(x,y));while(fruits.some(t=>!path(7,5,[3,4],t,stones))||!wells.some(w=>path(7,8,[3,5],w,[...stones,...Array.from({length:35},(_,i)=>key(i%7,Math.floor(i/7)))])))stones.pop();return{id:n,fruits,wells,stones};},
init(){return{roots:[[3,5]],stems:[[3,4]],request:null,water:0,lamp:-1,supports:[]};},
observe(s,r){return{roots:s.roots,stems:s.stems,request:s.request,water:s.water,lamp:s.lamp,supports:s.supports,...s.level};},
actions(o){if(o.role===0)return ['root','stem'].flatMap(kind=>options(o,kind).map(pos=>act('grow',`${kind==='root'?'長根':'生莖'} (${pos[0]+1},${pos[1]+1})`,{kind,pos})));return[...Array.from({length:7},(_,x)=>act('lamp',`燈光照第 ${x+1} 列`,{x})),act('water','為接通水源的根澆水'),...(o.request?.kind==='stem'?[act('support',`架起 (${o.request.pos[0]+1},${o.request.pos[1]+1}) 支架`,{pos:o.request.pos})]:[])];},
step(s,r,a){if(r===1){if(a.type==='lamp'&&Number.isInteger(a.x)&&a.x>=0&&a.x<7){s.lamp=a.x;return{ok:true};}if(a.type==='water'&&s.roots.some(p=>s.level.wells.some(w=>key(...w)===key(...p)))){s.water=8;return{ok:true};}if(a.type==='support'&&s.request?.kind==='stem'&&key(...a.pos)===key(...s.request.pos)){if(!s.supports.includes(key(...a.pos)))s.supports.push(key(...a.pos));return{ok:true};}return{ok:false,reason:'根尚未接到水源或尚無支架需求'};}if(a.type!=='grow'||!['root','stem'].includes(a.kind)||!Array.isArray(a.pos))return{ok:false};const o=C.observe(s,0);if(!options(o,a.kind).some(p=>key(...p)===key(...a.pos)))return{ok:false,reason:'必須由既有根莖鄰接生長，不能穿石'};if(a.kind==='root'){s.roots.push(a.pos);return{ok:true};}if(!s.request||key(...s.request.pos)!==key(...a.pos)){s.request={kind:a.kind,pos:a.pos};return{ok:true};}if(!s.water||s.lamp!==a.pos[0]||!s.supports.includes(key(...a.pos)))return{ok:false,reason:'等待園丁提供水、光與支架'};s.water--;s.stems.push(a.pos);s.request=null;s.won=s.level.fruits.every(t=>s.stems.some(p=>key(...p)===key(...t)));return{ok:true};},
ai(o){if(o.role===0){if(o.request){if(o.water&&o.lamp===o.request.pos[0]&&o.supports.includes(key(...o.request.pos)))return act('grow','依協作條件長出枝條',o.request);return null;}const g=nextGrowth(o);return g?act('grow','尋找果實或水源路線',g):null;}if(!o.request)return null;if(!o.water)return o.roots.some(p=>o.wells.some(w=>key(...w)===key(...p)))?act('water','補充根系水分'):null;if(o.lamp!==o.request.pos[0])return act('lamp','調整光照',{x:o.request.pos[0]});if(!o.supports.includes(key(...o.request.pos)))return act('support','支撐新枝條',{pos:o.request.pos});return null;},
view(o){return grid(7,8,(x,y)=>{const k=key(x,y),stem=o.stems.some(p=>key(...p)===k),root=o.roots.some(p=>key(...p)===k),fruit=o.fruits.some(p=>key(...p)===k),well=o.wells.some(p=>key(...p)===k);return{color:o.stones.includes(k)?'#525a52':stem?'#528d4a':root?'#a07c49':well?'#267998':y>=5?'#624934':o.lamp===x?'#697f42':'#264b44',label:stem&&fruit?'✿':fruit?'○':stem?'│':root?'╋':well?'≈':o.request&&key(...o.request.pos)===k?'?':o.stones.includes(k)?'◆':''};});},status:o=>`水分 ${o.water}/8 · 果實 ${o.fruits.filter(t=>o.stems.some(p=>key(...p)===key(...t))).length}/${o.fruits.length} · ${o.request?`請園丁照料 (${o.request.pos.map(v=>v+1).join(',')})`:'植物正在選擇生長方向'}`
});})(typeof module!=='undefined'?require('../coop120-common/core.js'):CoopCore);
