(function(C){const{act,rng,svg,txt}=C;
C.register('reflection-twins',{
roles:['實體','倒影'],icon:'◇',color:'#9dc8f2',intro:'實體調整反光面，倒影沿反射支路取回光印；光印凝成實體腳下的新路。',help:['實體在每個平臺切換反光面的角度（上、平、下），把倒影的路接向下一枚光印。','倒影只能沿目前反光面移動。到達光印後折回光束，為實體搭橋。','實體過橋後才能操作下一面鏡。每一段的有效反射角與支路長度不同。'],
generate(n){const r=rng(n*227+9);return{id:n,stages:Array.from({length:3+n%5},()=>({angle:Math.floor(r()*3),length:1+Math.floor(r()*3),height:Math.floor(r()*3)}))};},
init(){return{stage:0,angle:-1,shadow:0,bridge:false};},
observe(s,r){return{stage:s.stage,total:s.level.stages.length,angle:s.angle,shadow:s.shadow,bridge:s.bridge,route:s.level.stages[s.stage]};},
actions(o){return o.role===0?[...[0,1,2].map(angle=>act('angle',`反光面：${['上斜','水平','下斜'][angle]}`,{angle})),act('cross','沿新橋前進')]:[act('drift','沿反光面滑行'),act('return','退回一段倒影'),act('seal','折回光印，凝成橋')];},
step(s,r,a){const z=s.level.stages[s.stage];if(r===0){if(a.type==='angle'&&[0,1,2].includes(a.angle)&&s.shadow===0){s.angle=a.angle;return{ok:true};}if(a.type==='cross'&&s.bridge){s.stage++;s.angle=-1;s.shadow=0;s.bridge=false;s.won=s.stage===s.level.stages.length;return{ok:true};}}else{if(a.type==='drift'&&s.angle===z.angle&&s.shadow<z.length){s.shadow++;return{ok:true};}if(a.type==='return'&&s.shadow>0){s.shadow--;return{ok:true};}if(a.type==='seal'&&s.shadow===z.length&&!s.bridge){s.bridge=true;return{ok:true};}}return{ok:false,reason:'反光面或光印尚未接通'};},
ai(o){if(o.role===0){if(o.bridge)return act('cross','踏上倒影形成的新路');if(o.angle!==o.route.angle&&o.shadow===0)return act('angle','把反光面接向光印',{angle:o.route.angle});return null;}if(o.angle!==o.route.angle||o.bridge)return null;return o.shadow<o.route.length?act('drift','沿反光面移動'):act('seal','折回光印');},
view(o){const z=o.route;if(!z)return svg(txt(280,160,'倒影與實體重逢',30));let b=`<path d="M0 160H560" stroke="#a5c9ee" stroke-width="3"/><rect x="50" y="122" width="120" height="20" fill="#7ba9b3"/><rect x="390" y="122" width="120" height="20" fill="#7ba9b3"/>`;if(o.bridge)b+=`<path d="M170 135H390" stroke="#e6d6a0" stroke-width="12"/>`;for(let i=0;i<3;i++){const y=205+i*35;b+=`<path d="M100 190L440 ${y}" stroke="${i===o.angle?'#8be8ec':'#384e6c'}" stroke-width="8"/>`+txt(465,y+5,i===z.angle?'✦':'×',24);}b+=txt(108,109,'●',34)+txt(100+o.shadow*340/z.length,202+o.angle*35*o.shadow/z.length,'◇',28)+txt(280,50,`光印位於${['上斜','水平','下斜'][z.angle]}支路`,24);return svg(b);},status:o=>`雙生路段 ${Math.min(o.stage+1,o.total)}/${o.total} · 倒影 ${o.shadow}/${o.route?.length||0} · ${o.bridge?'新橋已成形':'等待光印'}`
});})(typeof module!=='undefined'?require('../coop120-common/core.js'):CoopCore);
