(function(root,factory){const B=typeof module==='object'&&module.exports?require('../action-common/base.js'):root.ActionBase;const api=factory(B);if(typeof module==='object'&&module.exports)module.exports=api;else (root.ActionGames||(root.ActionGames={}))[api.id]=api})(globalThis,function(B){
'use strict';
const {W,H,clamp,copy,rng,integer,dist2,segmentDistance,baseState,event,frame,text,circle,rect,line}=B;

function generateLevels(){return Array.from({length:100},(_,n)=>{let r=rng(71713+n*701),fish=[];for(let k=0;k<1+Math.floor(n/40);k++){let phases=[];for(let j=0;j<9+Math.floor(n/15);j++)phases.push({duration:integer(r,45,85),pull:j%3===1?1.1+integer(r,0,5)/10:.25+integer(r,0,5)/10});fish.push({bite:90+integer(r,0,110),window:40-Math.floor(n/25)*4,distance:95+integer(r,0,35)+Math.floor(n/20)*15,phases,castCenter:.35+integer(r,0,30)/100,castWidth:.28-Math.floor(n/40)*.04})}return{id:'fishing-challenge-'+String(n+1).padStart(3,'0'),seed:71713+n*701,tier:1+Math.floor(n/20),fish,maxTicks:10000}})}
function createState(l){return baseState({phase:'cast',fishIndex:0,phaseTick:0,tension:35,distance:l.fish[0].distance,slackTicks:0,landed:0,castErrors:0,hookHeld:false,reeling:false})}
function meter(s){return .5+.48*Math.sin(s.tick*.045)}
function pull(l,s){let f=l.fish[s.fishIndex],t=s.phaseTick%f.phases.reduce((v,p)=>v+p.duration,0);for(let p of f.phases){if(t<p.duration)return p.pull;t-=p.duration}return .4}
function step(l,s,i){s.tick++;s.phaseTick++;let f=l.fish[s.fishIndex];if(s.phase==='cast'){if(i.cast){let power=meter(s);if(Math.abs(power-f.castCenter)<=f.castWidth/2){s.phase='wait';s.phaseTick=0;event(s,'cast',{power})}else{s.castErrors++;event(s,'bad-cast',{power});if(s.castErrors>=5)s.status='lost'}}return}if(s.phase==='wait'){if(i.hook&&!s.hookHeld){if(s.phaseTick>=f.bite&&s.phaseTick<=f.bite+f.window){event(s,'hook',{latency:s.phaseTick-f.bite});s.phase='fight';s.phaseTick=0;s.tension=35;s.distance=f.distance}else{s.status='lost';event(s,'early-hook')}}if(s.phaseTick>f.bite+f.window){s.status='lost';event(s,'late-hook')}s.hookHeld=!!i.hook;return}if(s.phase==='fight'){s.reeling=!!i.reel;let force=pull(l,s);s.tension+=i.reel?.48+force*.48:-.85+force*.16;s.distance+=i.reel?-(.34/(.65+force*.25)):.045*force;s.tension=clamp(s.tension,0,110);if(s.tension<8)s.slackTicks++;else s.slackTicks=0;if(s.tension>=100||s.slackTicks>=90){s.status='lost';event(s,'line-fail',{tension:s.tension});return}if(s.distance<=0){s.landed++;s.score++;event(s,'land',{fish:s.fishIndex,tension:s.tension});s.fishIndex++;if(s.fishIndex===l.fish.length){s.status='won';s.phase='done'}else{s.phase='cast';s.phaseTick=0;s.distance=l.fish[s.fishIndex].distance;s.hookHeld=false}}}}
function bot(l,s){let f=l.fish[s.fishIndex];if(!f)return{};if(s.phase==='cast')return{cast:Math.abs(.5+.48*Math.sin((s.tick+1)*.045)-f.castCenter)<f.castWidth*.3};if(s.phase==='wait')return{hook:s.phaseTick+1===f.bite+12};return{reel:s.reeling?s.tension<65:s.tension<38}}
function draw(l,s,c){frame(c);rect(c,0,145,480,455,'#103a51');for(let k=0;k<9;k++)line(c,{x:0,y:175+k*45},{x:480,y:175+k*45},'#16465c',2);let f=l.fish[Math.min(s.fishIndex,l.fish.length-1)];text(c,`釣獲 ${s.landed}／${l.fish.length}`,240,35);if(s.phase==='cast'){text(c,'在金色區域按「拋竿」',240,235);rect(c,40,270,400,30,'#25324a');rect(c,40+400*(f.castCenter-f.castWidth/2),270,400*f.castWidth,30,'#dbae5b');rect(c,38+400*meter(s),262,4,46,'#ffffff');text(c,'力度',240,335)}else if(s.phase==='wait'){let bite=s.phaseTick>=f.bite;line(c,{x:80,y:120},{x:260,y:bite?295:265},'#d5dce2',2);circle(c,260,bite?295:265,10,bite?'#ffbc71':'#f79b9c');text(c,bite?'咬鉤！現在提竿':'等浮標下沉，再提竿',240,400,bite?'#ffe1a1':'#c2d6e2',25)}else{let force=s.phase==='fight'?pull(l,s):0;circle(c,250+Math.sin(s.tick*.08)*force*12,350,27,'#7bd7df');line(c,{x:75,y:110},{x:250,y:330},'#d9decb',2);text(c,force>1?'魚正在猛衝，注意張力':'魚較平靜，可以收線',240,185);rect(c,40,450,400,22,'#283245');rect(c,40,450,400*s.tension/100,22,s.tension>80?'#ff8892':'#82d1ad');text(c,`張力 ${Math.round(s.tension)}／100`,240,505);text(c,`剩餘距離 ${Math.max(0,Math.ceil(s.distance))}`,240,545)}text(c,'收線會增加張力；放線讓張力下降',240,585,'#b2c8d8',15)}
return B.define('fishing-challenge',{title:'釣魚挑戰',generateLevels,createState,step,bot,draw,controls:'C 拋竿，H 提竿；空白鍵按住收線，放開放線。也可操作下方按鈕。',rules:'先把力度停在金色區域；浮標下沉時提竿。交替收線與放線，把魚拉到岸邊。張力達100斷線，低於8持續1.5秒會脫鉤。每關須釣完指定魚。',hint:'張力在40–65間交替收放；魚猛衝時提早放線，穩定後再收。',buttons:[['cast','拋竿'],['hook','提竿'],['reel','按住收線']],pointer:'none',hud:(l,s)=>`階段：${({cast:'拋竿',wait:'等咬鉤',fight:'收放搏魚',done:'完成'})[s.phase]} · 失誤拋竿 ${s.castErrors}／5`,valid:(l,s)=>s.fishIndex>=0&&s.fishIndex<=l.fish.length&&s.landed===s.fishIndex&&s.tension>=0&&s.tension<=110,meter,pull});

});
