(function(){
'use strict';
const E=window.HeartsMatch,AI=window.HeartsAI,$=id=>document.getElementById(id),LOCK='arcade.hearts.active-table.v3',SAVE='arcade.hearts.full-match.v3',PREF='arcade.hearts.preferences.v3',STATS='arcade.hearts.results.v3';
const names=['你','青禾','阿木','小岑'],marks=['你','禾','木','岑'],levels={easy:'入門',normal:'標準',hard:'進階'},passNames={1:'向左傳牌',3:'向右傳牌',2:'傳給對面',0:'本副不傳牌'};
let selected=[],timer=null,generation=0,paused=false,conflict=false,started=false,collecting=false,saveError=false,knownRaw=null,notice='',toastTimer=null,audioCtx=null;
let lockUnavailable=!(window.navigator?.locks?.request),lockHeld=false,lockBlocked=false,lockPending=false,releaseLock=null,lockEpoch=0;
let prefs={speed:'normal',motion:window.matchMedia?.('(prefers-reduced-motion: reduce)').matches||false,sound:false},s=E.create(freshSeed()),stats={version:1,results:[]};
function freshSeed(){let n;try{const a=new Uint32Array(1);crypto.getRandomValues(a);n=a[0];}catch{n=(Date.now()^Math.floor(Math.random()*4294967296))>>>0;}return n;}
function read(key){try{return localStorage.getItem(key);}catch{return null;}}
function toast(t){$('toast').textContent=t;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,4200);}
try{const p=JSON.parse(read(PREF)||'null');if(p&&['slow','normal','fast'].includes(p.speed)&&typeof p.motion==='boolean'&&typeof p.sound==='boolean')prefs=p;}catch{}
try{const p=JSON.parse(read(STATS)||'null');if(p?.version===1&&Array.isArray(p.results)&&p.results.length<=200&&p.results.every(x=>typeof x.id==='string'&&['random','seeded'].includes(x.mode)&&['easy','normal','hard'].includes(x.difficulty)&&typeof x.won==='boolean'))stats=p;}catch{}
function decode(raw){const x=JSON.parse(raw);if(!x||x.schema!==1||typeof x.game!=='string')throw Error('存檔格式不符');return E.load(x.game);}
knownRaw=read(SAVE);if(knownRaw){try{s=decode(knownRaw);started=true;paused=true;notice='已恢復上次牌局。';}catch{notice='舊的完整對局存檔無法讀取。開始新對局可重新遊玩；指定牌局舊存檔不受影響。';}}
function clearTimer(){generation++;if(timer!==null)clearTimeout(timer);timer=null;collecting=false;}
function ownerReady(){return lockUnavailable||lockHeld;}
function releaseOwnership(){lockEpoch++;lockPending=false;if(!lockHeld)return;lockHeld=false;const release=releaseLock;releaseLock=null;if(release)release();}
function lockFailure(){releaseOwnership();lockUnavailable=true;conflict=false;lockHeld=false;lockBlocked=false;lockPending=false;releaseLock=null;saveError=true;paused=true;render();toast('此瀏覽器無法取得分頁鎖，本場只在記憶體遊玩，不會覆寫存檔。');}
function acquireLock(done){if(lockUnavailable||lockHeld){if(done)done();return;}if(lockPending)return;lockPending=true;const ticket=++lockEpoch;try{window.navigator.locks.request(LOCK,{mode:'exclusive',ifAvailable:true},lock=>{if(ticket!==lockEpoch)return;lockPending=false;if(!lock){lockBlocked=true;paused=true;render();toast('另一分頁正在操作牌桌，請先暫停或關閉那一頁。');return;}lockHeld=true;lockBlocked=false;if(read(SAVE)!==knownRaw){conflict=true;paused=true;}return new Promise(resolve=>{releaseLock=resolve;if(document.hidden){releaseOwnership();return;}render();if(done)done();});}).catch(()=>{if(ticket===lockEpoch)lockFailure();});}catch{if(ticket===lockEpoch)lockFailure();}}
function write(){if(!started||conflict)return;if(lockUnavailable){saveError=true;return;}if(!lockHeld)return;if(read(SAVE)!==knownRaw){conflict=true;paused=true;clearTimer();return;}const raw=JSON.stringify({schema:1,game:E.save(s)});try{localStorage.setItem(SAVE,raw);knownRaw=raw;saveError=false;}catch{saveError=true;}}
function ownership(){if(lockUnavailable)return true;if(!lockHeld){lockBlocked=true;paused=true;clearTimer();render();return false;}const now=read(SAVE);if(now!==knownRaw){conflict=true;paused=true;clearTimer();render();return false;}return true;}
function persistPrefs(){try{localStorage.setItem(PREF,JSON.stringify(prefs));}catch{}applyPrefs();}
function applyPrefs(){document.documentElement.classList.toggle('reduced-motion',prefs.motion);$('speed-input').value=prefs.speed;$('motion-input').checked=prefs.motion;$('sound-input').checked=prefs.sound;$('sound-button').textContent=prefs.sound?'♪ 音效開':'♪ 音效關';$('sound-button').setAttribute('aria-pressed',String(prefs.sound));$('sound-button').setAttribute('aria-label',prefs.sound?'關閉音效':'開啟音效');}
function sound(kind){if(!prefs.sound)return;try{audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();const t=audioCtx.currentTime;const notes=kind==='end'?[392,493.88,587.33]:kind==='pass'?[293.66,349.23]:[kind==='collect'?196:523.25];notes.forEach((f,i)=>{const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='sine';o.frequency.value=f;g.gain.setValueAtTime(0,t+i*.065);g.gain.linearRampToValueAtTime(.025,t+i*.065+.008);g.gain.exponentialRampToValueAtTime(.001,t+i*.065+.12);o.connect(g);g.connect(audioCtx.destination);o.start(t+i*.065);o.stop(t+i*.065+.13);});}catch{}}
function open(id){clearTimer();$(id).showModal();render();}
function close(id){$(id).close();if(paused||!started)releaseOwnership();render();queue();}
function anyDialog(){return Array.from(document.querySelectorAll('dialog')).some(d=>d.open);}
function interactive(){return ownerReady()&&started&&!paused&&!conflict&&!anyDialog()&&!document.hidden;}
function cardHTML(c,button=false,extra=''){const su=E.suit(c),r=E.RANKS[c%13],symbol=E.SUITS[su],cl=`card ${su===1||su===2?'red':''} ${c===49?'queen':''} ${extra}`;const interior=`<span class="card-top">${r}<small>${symbol}</small></span><span class="card-center" aria-hidden="true">${symbol}</span><span class="card-bottom" aria-hidden="true">${r}<br>${symbol}</span>`;return button?`<button class="${cl}" data-card="${c}" aria-label="${E.name(c)}${E.penalty(c)?'，'+E.penalty(c)+' 失分':''}" aria-pressed="${selected.includes(c)}">${interior}</button>`:`<div class="${cl}" role="img" aria-label="${E.name(c)}">${interior}</div>`;}
function describe(){if(s.phase==='pass')return s.passes[0]?'其他玩家正在挑選傳牌。':`選三張牌，${s.passDirection===1?'傳給左手邊的青禾':s.passDirection===3?'傳給右手邊的小岑':'傳給對面的阿木'}。`;if(s.phase==='trickEnd')return `${names[s.turn]}收下這墩 · ${s.trick.reduce((n,x)=>n+E.penalty(x.card),0)} 分`;if(s.phase==='roundEnd'||s.phase==='matchEnd')return s.phase==='matchEnd'?'完整對局已結束。':'本副結束，準備好再發下一副。';if(s.turn!==0)return `${names[s.turn]}正在思考。`;if(s.history.length===0&&!s.trick.length)return'你有梅花 2，由你開始第一墩。';if(s.trick.length){const led=E.suit(s.trick[0].card);return s.hands[0].some(c=>E.suit(c)===led)?`請跟${['梅花','方塊','紅心','黑桃'][led]}；亮起的牌都可以選。`:s.history.length===0?'你沒有梅花；第一墩請避開罰分牌。':'你沒有首出花色，可以選其他花色。';}return s.broken?'輪到你領牌，選一張開始這一墩。':'輪到你領牌，紅心還不能先出。';}
function render(){applyPrefs();$('round-label').textContent=`第 ${s.round} 副`;$('pass-label').textContent=passNames[s.passDirection];$('trick-count').textContent=`第 ${Math.min(13,s.history.length+1)} / 13 墩`;$('broken-label').textContent=s.broken?'♥ 紅心已破':'♡ 紅心未破';$('difficulty-label').textContent=`${levels[s.difficulty]} AI${s.mode==='seeded'?' · 種子重玩':''}`;$('table').dataset.winner=String(s.turn);
for(let p=0;p<4;p++){const el=$('seat-'+p),active=started&&!paused&&((s.phase==='play'||s.phase==='trickEnd')?s.turn===p:s.phase==='pass'&&!s.passes[p]);el.classList.toggle('active',active);el.innerHTML=`<span class="avatar">${marks[p]}</span><div><span class="seat-name">${names[p]}</span><small>${p===0?'這是你的座位':levels[s.difficulty]+' AI'}</small><div class="seat-count"><span class="cardback" aria-hidden="true"></span>${s.hands[p].length} 張 · 本副 ${s.roundScores?s.roundScores[p]:s.points[p]} 分</div></div>`;}
const prev=$('trick').dataset.key||'',key=s.round+':'+s.history.length+':'+s.trick.map(x=>x.card).join(',');if(prev!==key){$('trick').innerHTML=s.trick.map((x,i)=>`<div class="played" data-seat="${x.p}" style="${prev.startsWith(s.round+':'+s.history.length+':')&&i<s.trick.length-1?'animation:none':''}">${cardHTML(x.card)}<span class="played-label">${names[x.p]}</span></div>`).join('');$('trick').dataset.key=key;}$('trick').classList.toggle('collecting',collecting);
$('pass-center').hidden=s.phase!=='pass';if(s.phase==='pass')$('pass-center').innerHTML=`<div class="pass-backs" aria-hidden="true"><i class="pass-back"></i><i class="pass-back"></i><i class="pass-back"></i></div><strong>${s.passes[0]?'三張煩惱，送出了。':passNames[s.passDirection]}</strong><small>${s.passes[0]?'等大家選好後一起交換':s.passDirection===1?'← 送給青禾':s.passDirection===3?'送給小岑 →':'↑ 送給阿木'}</small>`;
const legal=s.phase==='play'&&s.turn===0?E.legalCards(s):[],canPass=s.phase==='pass'&&!s.passes[0],canAct=interactive()&&(canPass||s.phase==='play'&&s.turn===0);const focusCard=document.activeElement?.dataset.card;
$('hand').innerHTML=s.hands[0].map((c,i)=>cardHTML(c,true,`${selected.includes(c)?'selected':''} ${canAct&&(canPass||legal.includes(c))?'legal':''}`)).join('');$('hand').querySelectorAll('[data-card]').forEach((el,i)=>{const c=Number(el.dataset.card);el.disabled=!canAct||!canPass&&!legal.includes(c);el.style.setProperty('--i',i);el.style.setProperty('--angle',`${(i-(s.hands[0].length-1)/2)*.55}deg`);if(!canPass&&!legal.includes(c))el.title='現在不能出這張牌：'+describe();});if(focusCard&&canAct)$('hand').querySelector(`[data-card="${focusCard}"]`)?.focus({preventScroll:true});
$('hand-count').textContent=`${s.hands[0].length} 張`;$('hand-instruction').textContent=describe();$('selection-count').hidden=!canPass;$('selection-count').textContent=`${selected.length} / 3`;const end=['roundEnd','matchEnd'].includes(s.phase),confirm=$('confirm-button');confirm.disabled=end?!interactive():!canAct||(canPass?selected.length!==3:selected.length!==1);confirm.textContent=end?'查看結算 →':canPass?(selected.length===3?`確認${s.passDirection===1?'向左':s.passDirection===3?'向右':'向對面'}傳出`:`選擇三張牌（${selected.length}/3）`):selected.length?`出這張 ${E.name(selected[0])}`:s.phase==='trickEnd'?'正在收牌…':s.turn===0?'請選一張牌':'等待 AI 出牌';
$('status').textContent=notice||(canPass?'傳出的三張牌會同時交換。':s.phase==='play'&&s.turn===0?'先選牌，再確認。':'每墩四張，首出花色最大者收牌。');$('skip-button').hidden=!(s.phase==='trickEnd'&&interactive());
const ordered=[0,1,2,3].sort((a,b)=>s.totals[a]-s.totals[b]||a-b);$('score-list').innerHTML=ordered.map((p,i)=>`<div class="score-row ${p===0?'you':''}"><span class="rank-no">${i+1}</span><div class="score-person">${names[p]}${p===0?' · YOU':''}<small>本副 ${s.roundScores?s.roundScores[p]:s.points[p]} 分</small></div><div class="score-value">${s.totals[p]}<small>累積失分</small></div></div>`).join('');
const tip=s.phase==='pass'?['先送出三張煩惱','大紅心、黑桃皇后與孤單的大牌，常是值得考慮的傳牌。']:s.history.length===0?['第一墩，平安出發','梅花 2 領牌。能跟花色就要跟；第一墩不要墊紅心或黑桃皇后。']:s.points.some(p=>p>=13)&&s.points.filter(p=>p>0).length===1?['留意那輪滿月','若有人收齊全部罰分牌，其他三人會各加 26 分。適時分走一點，也能阻止射月。']:['不接，也是一種智慧','收下紅心與黑桃皇后會失分。觀察已出過的牌與對手缺少的花色。'];$('tip-title').textContent=tip[0];$('tip-text').textContent=tip[1];
$('pause-overlay').hidden=!paused&&!conflict&&!lockBlocked&&started;$('pause-title').textContent=lockBlocked?'牌桌正在另一分頁使用':conflict?'另一分頁更新了牌局':!started?'一副新牌，一個開始。':'牌局已暫停';$('pause-detail').textContent=lockBlocked?'請先在另一分頁按暫停、切換分頁或關閉它，再回來繼續。':conflict?'為避免兩邊互相覆寫，這一頁已暫停。讀取最新進度後再繼續。':!started?'選擇難度，和三位 AI 坐下來打一場。':'手中的牌會等你，回來再繼續。';$('resume-button').textContent=lockBlocked?'重新取得牌桌 →':conflict?'讀取最新進度 →':!started?'開始新對局 →':'繼續對局 →';$('pause-button').textContent=paused?'▶ 繼續':'Ⅱ 暫停';$('save-label').textContent=lockUnavailable?'此瀏覽器無分頁鎖，本場不會寫入存檔':lockBlocked?'另一分頁持有牌桌操作權':conflict?'分頁同步已暫停':saveError?'暫時無法儲存，請勿關閉此頁':started?'● 已自動儲存於這個瀏覽器':'準備好時開始';}
function recordResult(){if(s.phase!=='matchEnd')return;try{const latest=JSON.parse(read(STATS)||'null');if(latest?.version===1&&Array.isArray(latest.results)&&latest.results.length<=200&&latest.results.every(x=>typeof x.id==='string'&&['random','seeded'].includes(x.mode)&&['easy','normal','hard'].includes(x.difficulty)&&typeof x.won==='boolean')){const joined=[...latest.results,...stats.results];stats.results=joined.filter((x,i)=>joined.findIndex(y=>y.id===x.id)===i).slice(-200);}}catch{}const id=`${s.mode}:${s.difficulty}:${s.seed}`;if(stats.results.some(r=>r.id===id))return;stats.results.push({id,mode:s.mode,difficulty:s.difficulty,won:s.winners.includes(0)});stats.results=stats.results.slice(-200);if(!lockUnavailable&&lockHeld)try{localStorage.setItem(STATS,JSON.stringify(stats));}catch{}}
function commit(a){if(!interactive()||!ownership())return false;try{s=E.transition(s,a);selected=[];notice='';write();if(s.phase==='matchEnd')recordResult();render();if(a.type==='play')sound('play');if(a.type==='collect')sound(s.phase==='roundEnd'||s.phase==='matchEnd'?'end':'collect');if(a.type==='pass'&&s.phase==='play'){sound('pass');notice=`收到 ${s.received[0].map(E.name).join('、')}。`;render();}if(['roundEnd','matchEnd'].includes(s.phase))showResult();else queue();return true;}catch(err){paused=true;clearTimer();notice='動作未通過檢查，牌局已暫停。';render();toast('請繼續牌局後重試。');return false;}}
function queue(){clearTimer();if(!interactive())return;const ticket=generation,delay={slow:1050,normal:650,fast:240}[prefs.speed];if(s.phase==='pass'&&s.passes[0]){const p=s.passes.findIndex(x=>!x);if(p>=0)timer=setTimeout(()=>{if(ticket!==generation||!interactive())return;try{const action=AI.choose(E.observe(s,p),s.difficulty);commit(action);}catch{paused=true;notice='AI 傳牌暫時停下來了。按繼續重新嘗試。';render();}},prefs.motion?80:delay*.6);}
else if(s.phase==='play'&&s.turn!==0){timer=setTimeout(()=>{if(ticket!==generation||!interactive())return;try{const action=AI.choose(E.observe(s,s.turn),s.difficulty);commit(action);}catch{paused=true;notice='AI 暫時停下來了。按繼續重新嘗試。';render();}},delay);}
else if(s.phase==='trickEnd'){timer=setTimeout(()=>{if(ticket!==generation||!interactive())return;if(prefs.motion){commit({type:'collect'});return;}collecting=true;render();timer=setTimeout(()=>{if(ticket===generation&&interactive()){collecting=false;commit({type:'collect'});}},360);},prefs.motion?delay:delay+650);}}
function pause(){clearTimer();paused=true;selected=[];write();releaseOwnership();render();}
function resume(){if(!ownerReady()){acquireLock(resume);return;}if(!started){showSetup();return;}if(conflict){const raw=read(SAVE);try{if(!raw)throw Error('empty');s=decode(raw);knownRaw=raw;conflict=false;selected=[];notice='已載入另一分頁的最新進度。';}catch{knownRaw=raw;conflict=true;paused=true;notice='最新存檔無法讀取。請開始新對局，或等待另一分頁修復進度。';render();toast(notice);return;}}paused=false;render();if(['roundEnd','matchEnd'].includes(s.phase))showResult();else queue();}
function showSetup(){if(!ownerReady())acquireLock();document.querySelector(`[name="difficulty"][value="${s.difficulty}"]`).checked=true;$('setup-warning').hidden=!started||s.phase==='matchEnd';$('setup-error').textContent=lockUnavailable?'此瀏覽器不支援分頁鎖，本場只在記憶體遊玩，不會覆寫舊存檔。':'';open('setup-dialog');}
function showResult(){clearTimer();const end=s.phase==='matchEnd';$('result-eyebrow').textContent=end?'MATCH COMPLETE':'ROUND COMPLETE';$('result-title').textContent=end?(s.winners.includes(0)?s.winners.length>1?'並列勝利，一起輕鬆離席。':'你贏了，輕鬆離席。':`${s.winners.map(p=>names[p]).join('、')}${s.winners.length>1?'並列獲勝。':'贏得這一場。'}`):'這一副，塵埃落定。';$('result-text').textContent=s.moon!==null?`${names[s.moon]}射月成功！自己 0 分，其他三人各加 26 分。`:end?'有人累積失分達 100 分，最低分者獲勝。':`第 ${s.round} 副收牌完畢。下一副${passNames[[1,3,2,0][s.round%4]]}。`;$('result-scores').innerHTML='<div class="result-row head"><span>玩家</span><span>本副</span><span>累積</span></div>'+[0,1,2,3].map(p=>`<div class="result-row"><span class="${end&&s.winners.includes(p)?'best':''}">${names[p]}${end&&s.winners.includes(p)?' · 勝':''}</span><span>+${s.roundScores[p]}</span><span>${s.totals[p]}</span></div>`).join('');$('next-button').textContent=end?'開始全新對局 →':'發下一副 →';if(!$('result-dialog').open)$('result-dialog').showModal();render();}
$('setup-form').addEventListener('submit',ev=>{ev.preventDefault();if(!ownerReady()){acquireLock(()=>{$('setup-error').textContent='牌桌已就緒，請再按一次開始。';});return;}const seedText=$('seed-input').value.trim(),difficulty=document.querySelector('[name="difficulty"]:checked').value;if(seedText&&!/^(0|[1-9]\d{0,9})$/.test(seedText)||seedText&&Number(seedText)>4294967295){$('setup-error').textContent='請輸入 0–4294967295 的整數，或留空重新隨機洗牌。';return;}if(!ownership()){$('setup-dialog').close();return;}clearTimer();let seed=seedText?Number(seedText):freshSeed();if(!seedText&&seed===s.seed)seed=(seed+1)>>>0;s=E.create(seed,{difficulty,mode:seedText?'seeded':'random'});started=true;paused=false;conflict=false;selected=[];notice='';write();$('setup-dialog').close();render();sound('pass');queue();});
$('hand').addEventListener('click',ev=>{const card=ev.target.closest('[data-card]');if(!card||card.disabled||!interactive())return;const c=Number(card.dataset.card);if(s.phase==='pass'&&!s.passes[0]){if(selected.includes(c))selected=selected.filter(x=>x!==c);else if(selected.length<3)selected.push(c);else{toast('已選好三張；再點選可取消。');return;}}else if(s.phase==='play'&&s.turn===0&&E.legalCards(s).includes(c))selected=selected.includes(c)?[]:[c];else return;notice='';render();});
$('confirm-button').onclick=()=>{if(!interactive())return;if(['roundEnd','matchEnd'].includes(s.phase)){showResult();return;}if(s.phase==='pass'&&selected.length===3)commit({type:'pass',p:0,cards:selected});else if(s.phase==='play'&&s.turn===0&&selected.length===1)commit({type:'play',p:0,card:selected[0]});};
$('skip-button').onclick=()=>{if(interactive()&&s.phase==='trickEnd'){clearTimer();commit({type:'collect'});}};$('pause-button').onclick=()=>paused?resume():pause();$('resume-button').onclick=resume;$('new-button').onclick=showSetup;$('help-button').onclick=()=>open('rules-dialog');$('settings-button').onclick=()=>open('settings-dialog');
$('next-button').onclick=()=>{const end=s.phase==='matchEnd';$('result-dialog').close();if(end){showSetup();return;}paused=false;render();commit({type:'next'});};
$('history-button').onclick=()=>{$('round-history').innerHTML=s.rounds.length?'<div class="history-grid head"><span>副</span>'+names.map(n=>`<span>${n}</span>`).join('')+'</div>'+s.rounds.map(r=>`<div class="history-grid ${r.moon!==null?'moon':''}"><span>${r.round}</span>${r.scores.map(v=>`<span>+${v}</span>`).join('')}</div>`).join(''):'<p class="small-copy">打完第一副後，這裡會記錄每位玩家的失分。</p>';$('seed-label').textContent=s.seed;$('mode-label').textContent=s.mode==='random'?'隨機完整對局':'指定種子重玩';const list=stats.results.filter(x=>x.mode===s.mode&&x.difficulty===s.difficulty);$('stats-label').textContent=`${levels[s.difficulty]} · ${s.mode==='random'?'隨機':'種子'}紀錄：最近 ${list.length} 場完成，${list.filter(x=>x.won).length} 次勝利（含並列）。`;open('history-dialog');};
document.querySelectorAll('[data-close]').forEach(el=>el.onclick=()=>close(el.dataset.close));document.querySelectorAll('dialog').forEach(d=>d.addEventListener('cancel',()=>setTimeout(()=>{if(paused||!started)releaseOwnership();render();queue();},0)));
$('sound-button').onclick=()=>{prefs.sound=!prefs.sound;persistPrefs();sound('play');};$('sound-input').onchange=()=>{prefs.sound=$('sound-input').checked;persistPrefs();sound('play');};$('motion-input').onchange=()=>{prefs.motion=$('motion-input').checked;persistPrefs();};$('speed-input').onchange=()=>{prefs.speed=$('speed-input').value;persistPrefs();};
document.addEventListener('visibilitychange',()=>{if(document.hidden){if(started)pause();else releaseOwnership();}});window.addEventListener('pagehide',()=>{clearTimer();if(!conflict)write();releaseOwnership();});window.addEventListener('pageshow',ev=>{if(ev.persisted&&started){clearTimer();paused=true;render();}});window.addEventListener('storage',ev=>{if(!lockUnavailable&&ev.key===SAVE&&ev.newValue!==knownRaw){conflict=true;paused=true;clearTimer();render();}});document.addEventListener('keydown',ev=>{if(ev.key==='Escape'&&!anyDialog()&&started){ev.preventDefault();pause();}});
applyPrefs();render();if(!started)showSetup();else if(!paused)acquireLock();
/* Read-only snapshot helps diagnostics; no hidden hand data is exposed here. */
window.HeartsRoom=Object.freeze({snapshot:()=>({started,paused,conflict,lockHeld,lockBlocked,lockUnavailable,phase:s.phase,round:s.round,turn:s.turn,hand:s.hands[0].slice(),legal:s.turn===0?E.legalCards(s):[],totals:s.totals.slice(),trick:E.copy(s.trick),history:E.copy(s.history),difficulty:s.difficulty,mode:s.mode,events:s.events.length}),version:E.VERSION});
})();
