'use strict';
// Executes the actual shipped app.js. The DOM is minimal: this is NOT visual browser QA.
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const game=path.basename(__dirname),isH=game==='hitori',L=require('./levels.js'),E=require('./engine.js'),S=require('./state.js');
function boot(seed=new Map(),deny=false){let document;class Element{constructor(tag='div'){this.tagName=tag.toUpperCase();this.children=[];this.dataset={};this.events={};this.attributes={};this.style={setProperty(k,v){this[k]=v;}};this.textContent='';this.className='';this.value='';this.disabled=false;this.open=false;this.tabIndex=-1;}appendChild(x){this.children.push(x);return x;}replaceChildren(...x){this.children=x;}setAttribute(k,v){this.attributes[k]=String(v);}addEventListener(k,f){(this.events[k]??=[]).push(f);}dispatch(k,e={}){e.target??=this;e.preventDefault??=()=>{};for(const f of this.events[k]||[])f(e);}click(){if(!this.disabled)this.dispatch('click');}focus(){document.activeElement=this;this.dispatch('focus');}showModal(){this.open=true;}close(){this.open=false;}getBoundingClientRect(){return{width:750,height:440};}querySelector(s){const m=s.match(/data-cell="(\d+)"/);return this.children.find(x=>x.dataset.cell===m?.[1])||null;}get options(){return this.children;}}
const html=fs.readFileSync(path.join(__dirname,'../'+game+'.html'),'utf8'),ids=[...html.matchAll(/id="([^"]+)"/g)].map(a=>a[1]);assert.equal(ids.length,new Set(ids).size);const els=Object.fromEntries(ids.map(id=>[id,new Element(id==='level'?'select':'div')]));document={body:{dataset:{game}},getElementById:id=>els[id],createElement:t=>new Element(t),activeElement:null};const ctx={document,window:{addEventListener(){}},PuzzleEngine:E,PuzzleState:S,[isH?'HITORI_LEVELS':'SHIKAKU_LEVELS']:L,localStorage:{getItem(k){if(deny)throw Error('storage denied');return seed.get(k)||null;},setItem(k,v){if(deny)throw Error('storage denied');seed.set(k,v);}},ResizeObserver:class{constructor(f){this.f=f;}observe(){this.f();}},console};vm.runInNewContext(fs.readFileSync(__dirname+'/app.js','utf8'),ctx,{filename:game+'/app.js'});return{els,document,storage:seed,key:'arcade.logic.'+game+'.v1',state(){return JSON.parse(seed.get(this.key));},select(i){els.level.value=String(i);els.level.dispatch('change');},cell(i){return els.board.querySelector('[data-cell="'+i+'"]');},keyCell(i,key){this.cell(i).dispatch('keydown',{key});},reset(){els.reset.click();assert(els.resetDialog.open);els.resetConfirm.click();assert(!els.resetDialog.open);},place(z,n){this.cell(z[0]*n+z[1]).click();this.cell(z[2]*n+z[3]).click();assert(!els.confirm.disabled);els.confirm.click();}};}
const field=isH?'cells':'rects';function board(a,index=a.state().index){return a.state().records[index][field];}function won(a,p){return E.validateSolution(p,board(a));}function hintsWin(a,p){let n=0;while(!won(a,p)&&n++<220)a.els.hint.click();assert(n<220);assert(a.els.winDialog.open);assert(a.state().records[a.state().index].hints>0);}
function test(){const a=boot();assert.equal(a.els.level.options.length,50);assert(a.els.prev.disabled);let manual=0,hints=0,wrong=0;
for(let i=0;i<50;i++){a.select(i);const p=L[i];if(isH)p.solution.forEach((v,k)=>{if(v===2)a.keyCell(k,'2');});else p.solution.forEach(z=>a.place(z,p.size));assert(won(a,p));assert(a.state().finished[i]);assert.equal(a.state().finished[i].assisted,false);assert(a.els.winDialog.open);a.els.winClose.click();manual++;}
assert(a.els.next.disabled);assert.equal(Object.keys(a.state().finished).length,50);const reloadAll=boot(a.storage);assert.equal(Object.keys(reloadAll.state().finished).length,50);
for(let i=0;i<50;i++){const b=boot();b.select(i);hintsWin(b,L[i]);hints++;}
for(let i=0;i<50;i++){const b=boot();b.select(i);const p=L[i];if(isH){const j=p.solution.findIndex(v=>v===1);b.keyCell(j,'2');assert(!won(b,p));b.els.hint.click();assert.equal(board(b)[j],0);}else{const z=E.candidates(p).find(c=>!p.solution.some(a=>E.same(a,c.rect))).rect;b.place(z,p.size);assert(!won(b,p));b.els.hint.click();assert.equal(board(b).length,0);}assert(b.els.status.textContent.includes('衝突'));hintsWin(b,p);wrong++;}
const f=boot(),original=board(f);f.els.solution.click();assert(f.els.status.textContent.includes('預覽'));assert(f.els.hint.disabled);assert(f.els.reset.disabled);assert(f.els.undo.disabled);f.cell(0).click();f.keyCell(0,'Enter');assert.deepEqual(board(f),original);assert.equal(Object.keys(f.state().finished).length,0);assert(!f.els.winDialog.open);f.els.solution.click();assert.deepEqual(board(f),original);
f.els.hint.click();const hinted=board(f);f.els.undo.click();assert.deepEqual(board(f),original);assert.equal(f.state().records[0].hints,1);f.els.hint.click();const hinted2=board(f);f.els.reset.click();assert(f.els.resetDialog.open);f.els.resetCancel.click();assert(!f.els.resetDialog.open);assert.deepEqual(board(f),hinted2);f.els.reset.click();f.els.resetDialog.dispatch('cancel');f.els.resetDialog.close();assert.deepEqual(board(f),hinted2);f.reset();assert.deepEqual(board(f),original);assert.equal(f.state().records[0].hints,0);f.els.undo.click();assert.deepEqual(board(f),hinted2);assert.equal(f.state().records[0].hints,2);
f.els.help.click();assert(f.els.helpDialog.open);f.els.helpClose.click();assert(!f.els.helpDialog.open);const restored=boot(f.storage);assert.deepEqual(board(restored),hinted2);const bad=boot(new Map([[f.key,'not json']]));assert.equal(bad.state().index,0);assert.deepEqual(board(bad),original);const poison={version:1,index:999,records:{0:{[field]:isH?Array(16).fill(99):[[0,0,99,99]],undo:[{}]}},finished:{0:{[field]:original,assisted:false}}};const clean=boot(new Map([[f.key,JSON.stringify(poison)]]));assert.equal(clean.state().index,0);assert.equal(Object.keys(clean.state().finished).length,0);assert.deepEqual(board(clean),original);const denied=boot(new Map(),true);assert(denied.els.saveNotice.textContent.includes('無法儲存'));denied.els.hint.click();
f.cell(0).focus();f.keyCell(0,'ArrowRight');assert.equal(f.document.activeElement.dataset.cell,'1');f.keyCell(1,'ArrowLeft');assert.equal(f.document.activeElement.dataset.cell,'0');f.keyCell(0,'ArrowLeft');assert.equal(f.document.activeElement.dataset.cell,'0');f.keyCell(0,'ArrowDown');assert.equal(f.document.activeElement.dataset.cell,String(L[0].size));
if(isH){f.reset();f.els.paint2.click();f.cell(0).click();assert.equal(board(f)[0],2);f.cell(0).click();assert.equal(board(f)[0],0);f.els.paint1.click();f.cell(0).click();assert.equal(board(f)[0],1);f.keyCell(0,'0');assert.equal(board(f)[0],0);f.cell(0).dispatch('contextmenu');assert.equal(board(f)[0],1);f.cell(0).dispatch('contextmenu');assert.equal(board(f)[0],0);f.keyCell(0,'Enter');assert.equal(board(f)[0],1);f.keyCell(0,'Delete');assert.equal(board(f)[0],0);}
else{f.reset();const p=L[0],z=p.solution[0],start=z[0]*p.size+z[1],end=z[2]*p.size+z[3];f.keyCell(start,'Enter');assert(f.cell(start).className.includes('anchor'));f.cell(end).dispatch('pointerenter');assert(f.cell(end).className.includes('preview'));assert(f.els.confirm.disabled);assert.deepEqual(board(f),[]);f.keyCell(end,'Enter');assert(!f.els.confirm.disabled);assert.deepEqual(board(f),[]);f.els.cancelSelection.click();assert(f.els.confirm.disabled);assert(!f.cell(start).className.includes('preview'));f.cell(start).click();f.keyCell(start,'Escape');assert(f.els.confirm.disabled);f.place(z,p.size);const placed=board(f);f.cell(start).click();f.cell(end).click();assert(f.els.confirm.disabled);assert(f.els.status.textContent.includes('重疊'));f.els.cancelSelection.click();assert.deepEqual(board(f),placed);f.els.erase.click();f.cell(start).click();assert.deepEqual(board(f),[]);f.els.draw.click();f.place(z,p.size);f.keyCell(start,'Delete');assert.deepEqual(board(f),[]);f.place(z,p.size);f.cell(start).dispatch('contextmenu');assert.deepEqual(board(f),[]);f.cell(0).click();f.cell(p.size*p.size-1).click();assert(f.els.confirm.disabled);assert(f.els.status.textContent.includes('恰好包含'));assert.deepEqual(board(f),[]);f.els.cancelSelection.click();}
f.select(1);f.els.prev.click();assert.equal(f.state().index,0);f.els.next.click();assert.equal(f.state().index,1);const saved=board(f);f.els.solution.click();f.select(2);assert.equal(f.els.solution.textContent,'解答預覽');assert.deepEqual(f.state().records[1][field],saved);f.els.level.value='-1';f.els.level.dispatch('change');assert.equal(f.state().index,2);
const result={game,passed:true,manualWinFlows:manual,hintToWinFlows:hints,wrongMoveHintRecoveryFlows:wrong,otherPassed:['50-level selector and boundaries','current-board rules validate victory','reloaded all 50 completions validated','non-destructive solution preview','preview locks editing and never awards completion','undo with retained hint usage','restart Cancel and Escape preserve board','restart undo restores board','help open/close','save reload','malformed JSON recovery','invalid current board discarded','forged completion discarded','storage denied still playable','keyboard navigation and editing','click/touch controls','previous/next navigation','preview exits on level change','invalid level request ignored',...(isH?['black-only completion without mandatory white marking','three paint modes and right-click white marking']:['tap-two-corner input with confirmation preview','hover/keyboard preview','cancel preview','invalid rectangle rejected','overlap rejected','erase rectangle','right-click and Delete removal'])],visualBrowserQA:'Not run in this automated suite. The actual controller code is executed with a minimal mock DOM, which does not test rendering.',desktopDesignTarget:'1180×757, 100dvh no body scrolling; 30px minimum board cells; mobile controls remain in fixed shell'};fs.writeFileSync(__dirname+'/ui-verification.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result,null,2));return result;}
if(require.main===module)test();module.exports={boot,test};
