(function(){'use strict';
const E=window.Words120Engine,id=document.body.dataset.game,game=window.Words120Data[id],$=s=>document.querySelector(s),make=(tag,text,cls)=>{let e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
if(!game){document.body.textContent='遊戲資料未載入，請重新整理。';return;}
const storageKey='words120-v1:'+id;let progress;try{progress=E.validateProgress(JSON.parse(localStorage.getItem(storageKey)||'null'));}catch(e){progress=E.validateProgress(null);}let level=game.levels[progress.level-1],state=E.createState(level),demoQueue=[],demoIndex=0,saveAvailable=true;
const app=$('#app');app.append(make('a','← 遊戲大廳','home'));$('.home').href='../index.html';const header=make('header');header.append(make('p','LANGUAGE LAB · 文字與語言','eyebrow'),make('h1',game.title),make('p',game.proposal,'subtitle'));app.append(header);
const nav=make('nav',undefined,'level-nav'),prev=make('button','上一關'),select=make('select'),next=make('button','下一關');select.setAttribute('aria-label','選擇關卡');nav.append(prev,select,next);app.append(nav);const count=make('p',undefined,'progress');app.append(count);
const tutorial=make('details'),summary=make('summary','玩法、規則與本機夥伴');tutorial.open=true;tutorial.append(summary,make('p',game.tutorial),make('p','全部 100 關可直接選擇。提示與示範會標成「協助完成」；自行解題與協助紀錄分開保存。','muted'));if(game.ai!=='none')tutorial.append(make('p','夥伴使用公開的詞彙／語意規則推理。接收訊息的夥伴不會讀取目標答案，也不是連線聊天 AI。','muted'));app.append(tutorial);
const challenge=make('section',undefined,'challenge'),title=make('h2'),prompt=make('p',undefined,'goal'),board=make('div',undefined,'board'),work=make('div',undefined,'workspace');challenge.append(title,prompt,board,work);app.append(challenge);
const actions=make('div',undefined,'actions'),submit=make('button','檢查／執行','primary'),hint=make('button','提示'),demo=make('button','解答示範'),step=make('button','下一個示範步驟'),reset=make('button','重置本關');step.hidden=true;actions.append(submit,hint,demo,step,reset);app.append(actions);
const feedback=make('section',undefined,'feedback');feedback.setAttribute('aria-live','polite');const status=make('p'),extra=make('div'),provenance=make('p',undefined,'provenance');feedback.append(status,extra,provenance);app.append(feedback);
const footer=make('footer','本機保存進度 · 無帳號、無外部 API · 句法與詞義限於題目列出的範圍。');app.append(footer);
function persist(){progress.level=level.id;try{localStorage.setItem(storageKey,JSON.stringify(progress));saveAvailable=true;}catch(e){saveAvailable=false;}updateCounts();}
function updateCounts(){let manual=Object.values(progress.records).filter(x=>x.manual).length,assisted=Object.values(progress.records).filter(x=>x.assisted&&!x.manual).length;count.textContent=`自行完成 ${manual}／100 · 協助完成 ${assisted}／100${saveAvailable?'':' · 瀏覽器不允許保存，這次紀錄僅留在畫面'}`;select.replaceChildren();for(let l of game.levels){let r=progress.records[l.id],o=make('option',`${String(l.id).padStart(3,'0')} · ${l.title}${r?.manual?' ✓ 自行':r?.assisted?' ◇ 協助':''}`);o.value=l.id;select.append(o);}select.value=level.id;prev.disabled=level.id===1;next.disabled=level.id===100;}
function change(n){demoQueue=[];demoIndex=0;step.hidden=true;level=game.levels[Math.max(1,Math.min(100,n))-1];state=E.createState(level);status.textContent='';extra.replaceChildren();persist();render();}
prev.onclick=()=>change(level.id-1);next.onclick=()=>change(level.id+1);select.onchange=()=>change(Number(select.value));
function dispatch(action,rebuild=false,fromDemo=false){if(!fromDemo&&action.type!=='assist'&&demoQueue.length){demoQueue=[];demoIndex=0;step.hidden=true;}let old=state;state=E.reduce(level,state,action);if(old===state)return;if(state.status==='won'){progress=E.saveRecord(progress,level,state);if(level.kind==='dictionary')for(let w of level.words)progress.notebook[w]=level.concepts[Number(state.input[w])];persist();}if(rebuild)render();else updateFeedback();}
function updateFeedback(){status.textContent=state.result?.message||'';feedback.classList.toggle('success',state.status==='won');provenance.textContent=state.assisted?'本次作答：使用協助，完成後記為協助紀錄。':'本次作答：自行解題。';submit.disabled=state.status==='won';if(state.result?.animation)renderAnimation(state.result.animation);}
function renderAnimation(q){extra.replaceChildren();const row=make('div',undefined,'animation');const actor=make('span',(q.plural?'🤖🤖':'🤖')+' '+level.vocab.S[q.S][1],'actor');const arrow=make('span',q.neg?'✕ 不動作':'→ '+level.vocab.V[q.V][1],'arrow');const target=make('span',level.vocab.O[q.O][1],'object');row.append(actor,arrow,target);if(!q.neg)row.classList.add('moving');extra.append(row);}
function addCard(c,parent=board){let article=make('article',undefined,'card');if(c.title)article.append(make('h3',c.title));if(c.text)article.append(make('p',c.text));if(c.animation){let b=make('button','播放語料動作');b.onclick=()=>renderAnimation(c.animation);article.append(b);}parent.append(article);}
function chips(field,parent){const container=make('div',undefined,'chips');for(let o of field.options||[]){let b=make('button',o.label,'chip'),selected=(state.input[field.key]||[]).includes(o.value);b.type='button';b.setAttribute('aria-pressed',String(selected));b.disabled=state.status==='won';b.onclick=()=>{demoQueue=[];step.hidden=true;let vals=state.input[field.key]||[];dispatch({type:'set',key:field.key,value:vals.includes(o.value)?vals.filter(x=>x!==o.value):[...vals,o.value]},true);};container.append(b);}parent.append(container);let picked=(state.input[field.key]||[]).map(v=>field.options.find(o=>o.value===v)?.label||v);parent.append(make('p','已選：'+(picked.join(' → ')||'尚未選擇'),'picked'));}
function inputField(f){let fieldset=make('fieldset'),legend=make('legend',f.label);fieldset.append(legend);
 if(f.type==='multi'){chips(f,fieldset);work.append(fieldset);return;}
 if(f.type==='segmentation'){let text=state.input[f.key]||f.raw,cuts=new Set(),p=0;for(let ch of text){if(ch==='/')cuts.add(p);else p++;}let stream=make('div',undefined,'segmentation');[...f.raw].forEach((ch,j)=>{let unit=make('span',undefined,'segment-unit');unit.append(make('span',ch,'character'));if(j<f.raw.length-1){let b=make('button',cuts.has(j+1)?'│':'·','cut');b.setAttribute('aria-label',`在第 ${j+1} 字「${ch}」後${cuts.has(j+1)?'合併':'切詞'}`);b.setAttribute('aria-pressed',String(cuts.has(j+1)));b.disabled=state.status==='won';b.onclick=()=>{if(cuts.has(j+1))cuts.delete(j+1);else cuts.add(j+1);let next=[...f.raw].map((c,k)=>c+(cuts.has(k+1)?'/':'')).join('');dispatch({type:'set',key:f.key,value:next},true);};unit.append(b);}stream.append(unit);});fieldset.append(stream,make('p','目前：'+text,'picked'));work.append(fieldset);return;}
 if(f.options&&f.options.some(o=>o.label.length>38)){let choices=make('div',undefined,'long-choices');for(let o of f.options){let b=make('button',o.label,'long-choice');b.setAttribute('aria-pressed',String(state.input[f.key]===o.value));b.disabled=state.status==='won';b.onclick=()=>dispatch({type:'set',key:f.key,value:o.value},true);choices.append(b);}fieldset.append(choices);work.append(fieldset);return;}
 let control;if(f.options){control=make('select');control.append(Object.assign(make('option','請選擇'),{value:''}));for(let o of f.options)control.append(Object.assign(make('option',o.label),{value:o.value}));}else{control=make('textarea');control.rows=level.kind==='punctuation'?2:3;control.maxLength=600;control.spellcheck=false;}control.id='input-'+f.key;control.setAttribute('aria-label',f.label);control.value=state.input[f.key]||'';control.disabled=state.status==='won';control.addEventListener('input',()=>{demoQueue=[];step.hidden=true;dispatch({type:'set',key:f.key,value:control.value});});fieldset.append(control);
 if(f.tokens){let bank=make('div',undefined,'tokens');for(let token of f.tokens){let b=make('button',token);b.onclick=()=>{let sep=level.kind==='grammar'?' ':'';let value=cleanValue(control.value)+(control.value&&sep?sep:'')+token;control.value=value;dispatch({type:'set',key:f.key,value});};bank.append(b);}let undo=make('button','刪最後一詞');undo.onclick=()=>{let value=level.kind==='grammar'?control.value.trim().split(/\s+/).slice(0,-1).join(' '):control.value.replace(/(?:而且|[\s\S])$/,'');control.value=value;dispatch({type:'set',key:f.key,value});};bank.append(undo);fieldset.append(bank);}
 if(f.suggestions){let details=make('details'),sum=make('summary',level.kind==='punctuation'?'標點句法工具（自行判讀兩種意思）':'可用詞句工具');details.append(sum);let bank=make('div',undefined,'suggestions');for(let s of f.suggestions){let b=make('button',s);b.onclick=()=>{control.value=s;dispatch({type:'set',key:f.key,value:s});};bank.append(b);}details.append(bank);fieldset.append(details);}
 work.append(fieldset);
}
function cleanValue(s){return String(s||'').trim();}
function render(){title.textContent=`第 ${level.id}／100 關 · ${level.title}`;prompt.textContent=level.prompt;board.replaceChildren();work.replaceChildren();for(let c of level.cards||[])addCard(c);
 if(level.kind==='forbidden'){let route=level.route[state.stage];addCard({title:`旅途進度：第 ${state.stage+1}／3 站`,text:route.request+'\n累積禁字：'+route.banned.join('、')});let shelf=make('div',undefined,'shelf');for(let item of route.board)addCard({title:item.name,text:item.features.join(' · ')},shelf);board.append(shelf);inputField({key:'stop'+state.stage,label:'向店員描述（不要說出禁字）',type:'multi',options:route.clues.map(x=>({value:x.id,label:x.label}))});}
 else if(level.kind==='metaphor'){let shelf=make('div',undefined,'shelf');for(let item of level.board)addCard({title:'🖼 '+item.name,text:item.features.map(f=>level.clues.find(c=>c.feature===f)?.label).join('；')},shelf);board.append(shelf);}
 else if(level.kind==='fate'){level.scene.switches.forEach((pair,j)=>{let card=make('article',undefined,'story-card'),text=pair[state.bits[j]?0:1],after=pair[state.bits[j]?1:0];card.append(make('p',text));let b=make('button','改一字 → '+after);b.disabled=state.status==='won';b.onclick=()=>dispatch({type:'edit',index:j},true);card.append(b);work.append(card);});let track=make('div',undefined,'causal');track.append(make('h3','因果追蹤（隨改字即時更新）'));for(let effect of E.fateEffects(level,state.bits))track.append(make('p',(effect.value?'✓ ':'✕ ')+effect.name));work.append(track);if(state.history.length){let log=make('ol');for(let h of state.history)log.append(make('li',h.before+' → '+h.after));work.append(log);}}
 else if(level.kind==='naming'){let grid=make('div',undefined,'shape-grid');for(let o of level.board){let card=make('div',undefined,'shape-card'),target=!!(level.targetMask&(1<<o.id));card.append(make('span',target?'★ 目標':'· 干擾','target-label'));let shape=make('div',undefined,'shape '+(o.features.includes('圓')?'circle':'square')+' '+(o.features.includes('紅')?'red':'blue')+' '+(o.features.includes('大')?'large':'small')+' '+(o.features.includes('空')?'hollow':''));shape.setAttribute('aria-hidden','true');let frame=make('div',undefined,'shape-frame');frame.append(shape);card.append(frame,make('small',o.features.join(' ')));grid.append(card);}board.append(grid);}
 for(let f of level.fields||[])inputField(f);
 if(level.kind==='dictionary'&&Object.keys(progress.notebook).length){let book=make('details');book.append(make('summary','已解出的字典筆記（本機）'));let entries=Object.entries(progress.notebook);book.append(make('p',entries.slice(-80).map(([w,meaning])=>w+' = '+meaning).join('；')));board.append(book);}
 updateFeedback();updateCounts();}
submit.onclick=()=>{dispatch({type:'submit'},true);};reset.onclick=()=>{demoQueue=[];demoIndex=0;step.hidden=true;state=E.reduce(level,state,{type:'reset'});status.textContent='已重置，開始新的自行解題嘗試。';extra.replaceChildren();render();};hint.onclick=()=>{dispatch({type:'assist'});extra.replaceChildren(make('p',level.hint));};
demo.onclick=()=>{state=E.createState(level);dispatch({type:'assist'});demoQueue=E.witnessActions(level,level.solution);demoIndex=0;step.textContent='下一個示範步驟';step.hidden=false;extra.replaceChildren(make('p','示範將使用與你相同的合法操作，一次一步。按「下一個示範步驟」繼續。'));render();};step.onclick=()=>{if(demoIndex>=demoQueue.length)return;let a=demoQueue[demoIndex++];dispatch(a,true,true);step.textContent=`下一個示範步驟（${demoIndex}／${demoQueue.length}）`;if(demoIndex===demoQueue.length){step.hidden=true;extra.replaceChildren(make('p','示範完成。可重置後自行試出另一個合法解。'));}};
window.addEventListener('pagehide',()=>{demoQueue=[];persist();});document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();dispatch({type:'submit'},true);}});
render();persist();window.Words120App={getState:()=>JSON.parse(JSON.stringify(state)),getLevel:()=>level.id,change,dispatch,storageKey};
})();
