'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto'),assert=require('assert'),vm=require('vm');
const root=path.resolve(__dirname,'../..'),E=require('./engine.js'),data=require('./data.json'),catalog=require('./catalog.json');
const reports=[],hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');let total=0,alt=0,negatives=0,life=0;
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
for(const [id,g]of Object.entries(data)){
 assert.equal(g.levels.length,100,id+' count');assert.equal(catalog.find(x=>x.id===id).title,g.title);
 let signs=new Set(),passed=0,alternates=0;
 for(let l of g.levels){
  assert.equal(l.id,passed+1);let signature=E.semanticSignature(l);assert(!signs.has(signature),id+' duplicate semantic task '+l.id);signs.add(signature);
  let result=E.replay(l,l.solution);assert.equal(result.status,'won',`${id} ${l.id}: ${result.result?.message}`);assert.equal(result.assisted,false);assert(result.result.ok);passed++;total++;
  let empty=E.reduce(l,E.createState(l),{type:'submit'});assert.notEqual(empty.status,'won',id+' empty '+l.id);negatives++;
  if(l.alternate){let a=E.replay(l,l.alternate);assert.equal(a.status,'won',id+' alternate '+l.id+': '+a.result?.message);alt++;alternates++;}
  let demo=E.replay(l,l.solution,true);assert.equal(demo.status,'won');assert(demo.assisted);let p=E.saveRecord(null,l,demo);assert.equal(p.records[l.id].manual,false);assert.equal(p.records[l.id].assisted,true);p=E.saveRecord(p,l,result);assert(p.records[l.id].manual&&p.records[l.id].assisted);
  let again=E.reduce(l,result,{type:'submit'});assert.deepStrictEqual(again,result);let reset=E.reduce(l,result,{type:'reset'});assert.deepStrictEqual(reset,E.createState(l));let illegal=E.reduce(l,reset,{type:'set',key:'unknown',value:'bad'});assert.deepStrictEqual(illegal,reset);let badact=E.reduce(l,reset,{type:'edit',index:99});assert.deepStrictEqual(badact,reset);life+=7;
  // Corrupt every filled field individually; a nontrivial successful construction cannot be empty.
  if(l.kind!=='fate'){let invalid=structuredClone(l.solution),key=Object.keys(invalid)[0];invalid[key]=Array.isArray(invalid[key])?[]:'';assert.notEqual(E.replay(l,invalid).status,'won',id+' accepts incomplete '+l.id);negatives++;}
  if(l.kind==='punctuation'){for(let j=0;j<l.rules.length;j++){let r=l.rules[j];assert.equal(E.letters(r.readings[0]),r.raw);assert.equal(E.letters(r.readings[1]),r.raw);let bad={...l.solution,['p'+j]:r.readings[1-r.goal]};assert.notEqual(E.replay(l,bad).status,'won');negatives++;}}
  if(l.kind==='relay'){let bad={...l.solution,body:['wrong_'+l.genre+'_event',l.genre+'_condition']};assert.notEqual(E.replay(l,bad).status,'won');negatives++;}
  if(l.kind==='tone'){assert.notEqual(E.replay(l,{...l.solution,fact:'wrong'}).status,'won');negatives++;}
  if(l.kind==='radical'){for(let r of l.recipes)assert(r[1].length>=2&&['左右','上下','包圍','品字'].includes(r[2]));}
  if(l.kind==='telegram'){let observation={message:l.solution.message,dictionary:l.dictionary};let first=E.telegramPartner(observation);assert.deepStrictEqual(first,E.telegramPartner({...observation,target:['wrong'],secretGoal:['fake']}));assert.deepStrictEqual(first.commands,l.goal);let reverse={message:[...l.goal].reverse().join('')};assert.notEqual(E.replay(l,reverse).status,'won');negatives++;}
  if(l.kind==='grammar'&&l.grammar.marked){let badGrammar={...l.grammar,caseBefore:!l.grammar.caseBefore};assert(E.alienPartner({sentence:l.solution.sentence,grammar:badGrammar,vocab:l.vocab}).error,'case marker side is operative');negatives++;}
  if(l.kind==='grammar'){let q=E.alienPartner({sentence:l.solution.sentence,grammar:l.grammar,vocab:l.vocab});for(let k of Object.keys(l.goal))assert.equal(q[k],l.goal[k]);let o={sentence:l.solution.sentence,grammar:l.grammar,vocab:l.vocab};assert.deepStrictEqual(q,E.alienPartner({...o,goal:{V:99}}));}
  if(l.kind==='forbidden'||l.kind==='metaphor'){let routes=l.route||[{target:l.target,board:l.board,clues:l.clues,banned:[]}];for(let [j,r]of routes.entries()){let message=l.kind==='forbidden'?l.solution['stop'+j]:l.solution.clues,o={message,board:r.board,clues:r.clues,banned:r.banned};let q=E.featurePartner(o);assert.deepStrictEqual(q.matches,[r.target]);assert.deepStrictEqual(q,E.featurePartner({...o,target:999,solution:['fake']}));assert(E.featurePartner({...o,message:['unlisted']}).error);assert(E.featurePartner({...o,message:[message[0],message[0]]}).error);negatives+=2;}}
  if(l.kind==='fate'){assert(l.solution.edits.length>0);for(let p of l.scene.switches){assert.equal([...p[0]].length,[...p[1]].length);assert.equal([...p[0]].filter((c,j)=>c!==[...p[1]][j]).length,1);}for(let h of result.history)assert.equal([...h.before].filter((c,j)=>c!==[...h.after][j]).length,1);assert(E.fateEffects(l,result.bits)[l.goalNode].value);}
  if(l.kind==='segmentation'){for(let r of l.rules)for(let p of r.readings)assert.equal(p[0].replaceAll('/',''),r.raw);}
  if(l.kind==='rhyme'){assert.equal([...l.cards[0].text].length,l.meter);assert.equal([...l.prefix+l.solution.ending].length,l.meter);let term=l.lexicon.find(x=>x.id===l.goal);assert.equal(term.rhyme,l.rhyme);assert(term.phrases.every(s=>[...s].length===3));}
  if(l.kind==='naming'){let q=E.parseExpression(l.solution.expression,l.board);assert.equal(q.mask,l.targetMask);assert.equal(q.atoms,l.minCost);assert(E.parseExpression('紅而且',l.board).error);assert(E.parseExpression('alert(1)',l.board).error);negatives+=2;}
 }
 const levelFile=JSON.parse(read(`games/${id}/levels.json`)),proof=JSON.parse(read(`games/${id}/proofs.json`));assert.deepStrictEqual(levelFile,g.levels);assert.equal(proof.length,100);for(let p of proof)assert.equal(E.replay(levelFile[p.id-1],p.input).status,'won');
 let browserData={window:{}};vm.runInNewContext(read(`games/${id}/levels.js`),browserData);assert.equal(JSON.stringify(browserData.window.Words120Data[id]),JSON.stringify(g),'route data differs from audited corpus');let html=read(`games/${id}.html`);assert(html.includes('<title>'+g.title));assert(html.includes('lang="zh-Hant"'));assert(html.includes('viewport'));for(let dep of [...html.matchAll(/(?:src|href)="\.\/([^"#]+)"/g)])assert(fs.existsSync(path.join(root,'games',dep[1])),id+' dependency '+dep[1]);
 reports.push({id,levels:passed,semanticTasks:signs.size,alternateConstructions:alternates,solutions:'All replayed through production reducer and validator',browserTested:false});
}
// Independent truth-table shortest-description certificate. Dynamic programming enumerates ALL formulas with fewer atoms.
const board=data['precise-naming'].levels[0].board,seen=new Map(),sets=[[]];for(let word of ['紅','藍','圓','方','大','小','實','空']){let mask=board.reduce((m,o)=>m|(o.features.includes(word)?1<<o.id:0),0);seen.set(mask,1);}sets[1]=[...seen.keys()];for(let c=2;c<=Math.max(...data['precise-naming'].levels.map(l=>l.minCost));c++){let fresh=[];for(let a=1;a<c;a++)for(let x of sets[a])for(let y of sets[c-a])for(let m of [x&y,x|y]){if(!seen.has(m)){seen.set(m,c);fresh.push(m);}}sets[c]=fresh;}for(let l of data['precise-naming'].levels)assert.equal(seen.get(l.targetMask),l.minCost,'minimum cost independently proved');
assert.deepStrictEqual(E.validateProgress({version:1,level:999,records:{'-1':{manual:true,assisted:true},'2':{manual:'true',assisted:false}},notebook:{'<script>':'bad'}}),{version:1,level:1,records:{},notebook:{}});
const checks={levelSolutions:total,alternateConstructions:alt,negativeCases:negatives,lifecycleAssertions:life,minimalDescriptionTruthTables:100,aiObservationChecks:true,persistenceValidation:true};
const sources={};for(let file of fs.readdirSync(__dirname).sort()){if(file.endsWith('-report.json')||file==='release-manifest.json')continue;let p=path.join(__dirname,file);if(fs.statSync(p).isFile())sources['games/words120-common/'+file]=hash(p);}for(let id of Object.keys(data)){sources['games/'+id+'.html']=hash(path.join(root,'games',id+'.html'));for(let file of fs.readdirSync(path.join(root,'games',id)).sort()){let p=path.join(root,'games',id,file);if(fs.statSync(p).isFile())sources['games/'+id+'/'+file]=hash(p);}}

const report={schemaVersion:1,family:'words',status:'passed',generatedAt:new Date().toISOString(),checks,games:reports,sourceFiles:sources,limitations:['Browser checks are separate and have not been run by this verifier.','Bounded authored vocabulary and semantic structures; no general natural-language understanding.','Proofs establish legal reachability, not unique solutions.']};
fs.writeFileSync(path.join(__dirname,'verification-report.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({status:'passed',...checks},null,2));
