/* Explicitly simplified educational game models; not ecological forecasting. */
(function(root,factory){const api=factory();if(typeof module==='object')module.exports=api;else root.EcologyEngine=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const clone=x=>JSON.parse(JSON.stringify(x)), sum=a=>a.reduce((x,y)=>x+y,0), min=a=>Math.min(...a), max=a=>Math.max(...a), clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
const names=['droplet-world','evolving-island','before-wings','symbiotic-partners','intertidal-shift','mycelium-exchange','century-pedigree','migration-memory','bloom-timing','lost-predators','vent-colony','borrowed-appearance','dormant-seedbank','social-cost','last-habitat'];
const M={};const opt=(id,label)=>({id,label});
M['droplet-world']={
 init:c=>({energy:c.energy,pop:1,membrane:0,gill:0,food:c.patches.slice(),eaten:0}),
 actions:s=>[...s.food.map((_,i)=>opt('feed'+i,['左側藻團','中央菌團','右側碎屑'][i])),opt('membrane','演化隔熱膜 · 2 能量'),opt('gill','演化吸氧構造 · 2 能量'),opt('divide','吞食後分裂 · 3 能量')],
 tick(s,a,c){const e=c.weather[s.turn];if(a.startsWith('feed')){let i=+a.slice(4),n=s.food[i];s.energy+=n;s.eaten+=n;s.food[i]=0;s.note=`吞食 ${n} 單位；食物需要回復。`;}if(a==='membrane'&&s.energy>=2){s.membrane++;s.energy-=2;}if(a==='gill'&&s.energy>=2){s.gill++;s.energy-=2;}if(a==='divide'&&s.energy>=3){s.pop++;s.energy-=3;}const stress=Math.max(0,e[0]-s.membrane)+Math.max(0,e[1]-s.gill);s.energy-=1+stress;if(s.energy<0){s.pop--;s.energy=0;}s.food=s.food.map((v,i)=>Math.min(c.patches[i],v+c.regen[i]));s.note+=` 水溫壓力 ${e[0]}、缺氧 ${e[1]}，本代消耗 ${1+stress}。`;},
 metrics:s=>[['細胞',s.pop],['能量',s.energy],['隔熱膜',s.membrane],['吸氧',s.gill]],goal:(s,c)=>s.pop>=c.target&&s.energy>=1&&s.eaten>=10,score:s=>s.pop*18+s.energy*1.5+s.membrane*3+s.gill*3,
 objective:c=>`在 ${c.turns} 代後保留 ${c.target} 個細胞、至少 1 能量，累計吞食 10 單位。`, scene:'cells',reason:'吞食會耗盡斑塊；膜與吸氧構造減少不同壓力；分裂把能量轉成族群。'
};
M['evolving-island']={
 init:c=>({pop:c.population.slice(),habitat:c.habitat.slice(),moves:0}),
 actions:s=>['水量','林蔭','岩地'].flatMap((v,i)=>[opt('up'+i,`增加${v}`),opt('down'+i,`減少${v}`)]),
 tick(s,a,c){let i=+a.slice(-1);s.habitat[i]=clamp(s.habitat[i]+(a.startsWith('up')?1:-1),0,4);s.moves++;const fit=c.niches.map(n=>6-sum(n.map((v,j)=>Math.abs(v-s.habitat[j]))));let chosen=policy('island',{pop:s.pop,fit},s.difficulty,s.turn);s.ai=chosen;s.pop=s.pop.map((p,j)=>p===0?0:Math.max(0,p+(fit[j]>=3?2:fit[j]>=1?1:-1)-(sum(s.pop)>c.capacity&&j===chosen?1:0)));s.note=`環境只改了一項；三支系適合度 ${fit.join('／')}。資源過擠時，入侵覓食者優先採食支系 ${chosen+1}。`;},
 metrics:s=>s.pop.map((n,i)=>['支系'+(i+1),n]).concat([['水／蔭／岩',s.habitat.join('/')]]),goal:(s,c)=>min(s.pop)>=3&&s.pop[c.endangered]>=c.target,score:(s,c)=>min(s.pop)*10+s.pop[c.endangered]*3+sum(s.pop),objective:c=>`三支系都保留至少 3 隻，瀕危支系 ${c.endangered+1} 達 ${c.target} 隻。`,scene:'island',reason:'不同支系有不同環境偏好；改善一項條件可能壓縮另一支系的空間。族群歸零即滅絕，本作沒有移入或種子庫。'
};
M['before-wings']={
 init:c=>({climb:c.traits[0],glide:c.traits[1],forage:c.traits[2],energy:c.energy,crossed:0,range:0}),actions:s=>[opt('climb','選育攀爬肢'),opt('glide','選育滑翔膜'),opt('forage','選育覓食喙')],
 tick(s,a,c){s[a]++;let gap=c.gaps[s.turn],fruit=c.fruit[s.turn];s.range=s.climb*2+s.glide*3;s.energy+=s.forage+fruit-s.glide-2;if(s.range>=gap&&s.energy>0){s.crossed++;s.energy--;}s.note=`本代滑翔距離 ${s.range}；峽谷 ${gap}。覓食 +${s.forage+fruit}，滑翔膜維持費 ${s.glide+2}。`;},
 metrics:s=>[['攀爬',s.climb],['滑翔',s.glide],['覓食',s.forage],['能量',s.energy],['跨越',s.crossed]],goal:(s,c)=>s.crossed>=c.target&&s.energy>=2,score:s=>s.crossed*20+s.energy+s.climb+s.glide+s.forage,objective:c=>`跨過至少 ${c.target} 道峽谷，最後保留 2 能量；特徵逐代繼承。`,scene:'glider',reason:'攀爬與滑翔共同增加距離；大滑翔膜也提高每代食物需求。'
};
M['symbiotic-partners']={
 init:c=>({health:c.health.slice(),sugar:[4,4,4],links:[-1,-1,-1,-1,-1,-1],seeds:0,fungal:3}),
 actions:s=>Array.from({length:12},(_,n)=>{let host=n%3,kind=Math.floor(n/6),partner=Math.floor(n/3)%2;return opt(`link${kind}${host}${partner}`,`${['植物甲','植物乙','植物丙'][host]} ↔ ${kind?'授粉昆蟲':'根部真菌'}${partner+1}`);}),
 tick(s,a,c){let k=+a[4],h=+a[5],p=+a[6];s.links[k*3+h]=p;let e=c.seasons[s.turn];s.health=s.health.map((v,i)=>{let f=s.links[i],bug=s.links[3+i],water=f<0?0:c.fungi[f][e[0]],poll=bug<0?0:c.insects[bug][e[1]];if(f>=0){s.sugar[i]=Math.max(0,s.sugar[i]-1);s.fungal++;}s.sugar[i]+=e[2];if(bug>=0&&s.sugar[i]>0){s.seeds+=Math.max(0,poll-(e[3]===i?1:0));s.sugar[i]--;}return Math.max(0,v+water-e[0]-(s.sugar[i]===0?1:0));});s.fungal=Math.max(0,s.fungal-2);s.note=`水需求 ${e[0]}；花型 ${e[1]+1}；真菌取碳供水，昆蟲帶走花蜜並授粉。`;},
 metrics:s=>s.health.map((v,i)=>['植株'+(i+1),v]).concat([['種子',s.seeds],['菌儲備',s.fungal]]),goal:(s,c)=>min(s.health)>=2&&s.seeds>=c.target&&s.fungal>=1,score:s=>min(s.health)*8+s.seeds*3+s.links.filter(x=>x>=0).length*3+Math.min(s.fungal,8),objective:c=>`三株植物水分活力至少 2、菌儲備至少 1，取得 ${c.target} 顆種子。`,scene:'mutualism',reason:'連線持續交換資源；植株數固定三株，水分活力 0 表示枯萎但根系仍活著，可補水恢復，並不是死亡後復活。'
};
M['intertidal-shift']={
 init:c=>({size:c.population.slice(),height:c.height.slice(),fed:0}),actions:s=>Array.from({length:12},(_,n)=>opt('place'+Math.floor(n/4)+(n%4),`${['藤壺','貽貝','海葵'][Math.floor(n/4)]} → ${['低潮線','低岸','高岸','浪花帶'][n%4]}`)),
 tick(s,a,c){let i=+a[5],h=+a[6];s.height[i]=h;let [tide,wave,plankton]=c.tides[s.turn];s.size=s.size.map((v,j)=>{if(v===0)return 0;let wet=s.height[j]<=tide,gain=wet?plankton:0,loss=wet?Math.max(0,wave-c.grip[j]-s.height[j]):Math.max(0,s.height[j]-tide-c.dry[j]);s.fed+=gain;return Math.max(0,v+gain-loss-1);});s.note=`潮位 ${tide}，浪力 ${wave}，水中食物 ${plankton}；低處能吃到食物，也承受浪擊。`;},metrics:s=>s.size.map((v,i)=>[['藤壺','貽貝','海葵'][i],v]).concat([['總攝食',s.fed]]),goal:(s,c)=>min(s.size)>=2&&s.fed>=c.target,score:s=>min(s.size)*15+sum(s.size)+s.fed/2,objective:c=>`三個附著群落都存活（至少 2），累積攝食 ${c.target}。每潮只能搬一群。`,scene:'tide',reason:'附著高度影響浸水、乾燥與浪擊；三種生物耐乾和抓地不同。群落歸零即滅絕，搬位不會產生新個體。'
};
M['mycelium-exchange']={
 init:c=>({health:c.health.slice(),carbon:c.carbon.slice(),water:c.water.slice(),fungus:c.fungus,soil:c.soil,rainReceived:0,waterConsumed:0,waterExtracted:0,transfers:0}),actions:s=>[...Array.from({length:9},(_,n)=>[Math.floor(n/3),n%3]).filter(([i,j])=>i!==j).map(([i,j])=>opt('route'+i+j,`宿主${i+1} 的碳 → 菌網 → 宿主${j+1} 的水`)),opt('reserve','菌網儲存碳')],
 tick(s,a,c){let e=c.weather[s.turn];s.carbon=s.carbon.map((v,i)=>Math.min(10,v+e.sun[i]));s.water=s.water.map((v,i)=>Math.max(0,v+e.rain[i]));s.rainReceived+=sum(e.rain);if(a==='reserve'){let i=s.carbon.indexOf(max(s.carbon));let n=Math.min(3,s.carbon[i]);s.carbon[i]-=n;s.fungus+=n;}else{let i=+a[5],j=+a[6],n=Math.min(3,s.carbon[i]);s.carbon[i]-=n;s.fungus+=n;if(s.fungus>=2&&s.soil>0){let water=Math.min(3,s.soil);s.fungus-=2;s.soil-=water;s.water[j]+=water;s.waterExtracted+=water;s.transfers++;}}s.health=s.health.map((v,i)=>{let enough=s.water[i]>=e.demand[i];s.waterConsumed+=Math.min(s.water[i],e.demand[i]);s.water[i]=Math.max(0,s.water[i]-e.demand[i]);return Math.max(0,v+(enough?1:-2));});s.fungus=Math.max(0,s.fungus-1);s.note=`本輪耗水 ${e.demand.join('／')}。碳由供應者支付，菌網付 2 能量，從有限地下水取最多 3 水給接收者，另維持 1；地下水剩 ${s.soil}。`;},metrics:s=>s.health.map((v,i)=>['宿主'+(i+1),v]).concat([['菌能',s.fungus],['地下水',s.soil],['成功交換',s.transfers]]),goal:(s,c)=>min(s.health)>=3&&max(s.health)-min(s.health)<=c.balance&&s.fungus>=1&&s.transfers>=3,score:s=>min(s.health)*20+sum(s.health)+Math.min(s.fungus,8)+s.transfers*2,objective:c=>`每個宿主健康至少 3，健康差不超過 ${c.balance}，菌能至少 1，完成 3 次交換。`,scene:'fungus',reason:'宿主供碳給菌網，菌網付能量從有限地下水取水給另一宿主；地下水耗盡不能取水，只有預報雨水另行補充宿主。'
};
M['century-pedigree']={
 init:c=>({adults:clone(c.adults),known:c.adults.map(()=>false),offspring:0,lineages:c.adults.map((_,i)=>i),survived:0,assays:0}),
 actions:s=>[...s.adults.map((_,i)=>opt('assay'+i,`觀察個體 ${i+1} 的隱性特徵`)).filter((_,i)=>!s.known[i]),...Array.from({length:15},(_,n)=>n).flatMap((_,i)=>[]),...s.adults.flatMap((_,i)=>s.adults.slice(i+1).map((__,n)=>opt('pair'+i+(i+1+n),`配對 ${i+1} × ${i+2+n}`)))],
 tick(s,a,c){if(a.startsWith('assay')){let i=+a.slice(5);s.known[i]=true;s.assays++;s.noAdvance=true;s.note=`觀察個體 ${i+1}：冷耐 ${s.adults[i][0]}，旱耐 ${s.adults[i][1]}。`;return;}let i=+a[4],j=+a[5],x=s.adults[i],y=s.adults[j],e=c.climate[s.turn];const kids=[[x[0],y[1]],[y[0],x[1]]];s.offspring+=2;let viable=kids.filter(g=>g[e[2]]>=e[e[2]]);s.survived+=viable.length;s.adults=s.adults.slice(2).concat(kids);s.known=s.known.slice(2).concat([s.known[i]&&s.known[j],s.known[i]&&s.known[j]]);s.lineages=s.lineages.slice(2).concat([s.lineages[i],s.lineages[j]]);s.note=`子代交叉繼承兩項特徵，${viable.length}/2 通過本代氣候；最老兩個體退出繁殖群。`;},metrics:s=>[['兩性狀多樣性',s.aggregateDiversity===undefined?diversity(s):s.aggregateDiversity],['氣候存活子代',s.survived],['已觀察',s.known.filter(Boolean).length]],goal:(s,c)=>diversity(s)>=c.diversity&&s.survived>=c.target&&s.offspring>=8,score:s=>diversity(s)*15+s.survived*8,objective:c=>`完成 ${c.turns} 代配對，兩性狀保留 ${c.diversity} 種等位值，至少 ${c.target} 個子代通過氣候。`,scene:'pedigree',reason:'這是兩性狀的簡化交叉繼承模型，不是完整孟德爾遺傳；未觀察的隱性值不公開。'
};function diversity(s){return new Set(s.adults.map(x=>x[0])).size+new Set(s.adults.map(x=>x[1])).size;}
M['migration-memory']={
 init:c=>({energy:c.energy,pop:c.population,wetlands:c.wetlands.slice(),memory:[0,0,0],arrivals:0,last:-1}),actions:s=>[opt('route0','北方山脊 · 兩站'),opt('route1','中部河谷 · 兩站'),opt('route2','南方繞道 · 三站')],
 tick(s,a,c){let r=+a[5],nodes=[[0,2],[1,3],[0,4,3]][r],e=c.seasons[s.turn];let gain=0;nodes.forEach(i=>{let n=Math.min(c.eat,s.wetlands[i]);s.wetlands[i]-=n;gain+=n;});let cost=Math.max(1,c.cost[r]+e.wind[r]-s.memory[r]);s.energy+=gain-cost;s.wetlands=s.wetlands.map((v,i)=>Math.min(c.wetlands[i],v+(nodes.includes(i)?0:e.rain)));if(s.energy>=2){s.arrivals++;s.pop+=2;s.energy-=2;}else{s.pop-=2;s.energy=Math.max(0,s.energy);}s.memory[r]=Math.min(3,s.memory[r]+1);s.last=r;s.note=`路線記憶 ${s.memory[r]} 傳給後代。補食 ${gain}、飛行耗能 ${cost}；未使用棲地回復 ${e.rain}。`;},metrics:s=>[['族群',s.pop],['能量',s.energy],['抵達',s.arrivals],['路線記憶',s.memory.join('/')]],goal:(s,c)=>s.pop>=c.target&&s.arrivals>=c.turns-1&&sum(s.wetlands)>=c.reserve,score:s=>s.pop*8+s.arrivals*8+s.energy+sum(s.wetlands)/2,objective:c=>`族群達 ${c.target}，至少 ${c.turns-1} 次抵達，沿途仍保留 ${c.reserve} 單位食物。`,scene:'migration',reason:'走過的路線降低後代能耗；同一濕地重複取食會耗盡，空置才回復。'
};
M['bloom-timing']={
 init:c=>({seeds:0,reserve:c.reserve,day:c.day,shape:c.shape,visits:0,ai:[]}),actions:s=>Array.from({length:8},(_,n)=>opt('bloom'+Math.floor(n/2)+(n%2),`第 ${Math.floor(n/2)+1} 時窗 · ${n%2?'深筒花':'淺盤花'}`)),
 tick(s,a,c){let day=+a[5],shape=+a[6],e=c.seasons[s.turn],change=Math.abs(day-s.day);s.reserve+=e.sun-1-change;s.day=day;s.shape=shape;let offers=[{id:0,reward:Math.max(0,s.reserve),day,shape},{id:1,reward:e.rivalReward,day:e.rivalDay,shape:e.rivalShape}];s.ai=[];for(let insect=0;insect<3;insect++){let who=policy('pollinator',{offers,flight:e.flight[insect],tongue:c.tongues[insect],crowd:s.ai},s.difficulty,s.turn+insect);s.ai.push(who);if(who===0&&day!==e.frost){s.seeds+=shape===c.tongues[insect]?3:1;s.visits++;s.reserve=Math.max(0,s.reserve-1);}}s.note=`授粉者選擇 ${s.ai.map(x=>x<0?'休息':x===0?'你的花':'競爭花').join('、')}；霜凍時窗 ${e.frost+1}。`;},metrics:s=>[['種子',s.seeds],['花蜜儲備',s.reserve],['訪花',s.visits],['花期',s.day+1]],goal:(s,c)=>s.seeds>=c.target&&s.reserve>=1&&s.visits>=5,score:s=>s.seeds*5+s.visits*2+s.reserve,objective:c=>`取得 ${c.target} 顆種子、至少 5 次訪花，剩 1 花蜜儲備；改花期會耗能。`,scene:'flowers',reason:'花期與授粉者飛行時窗須相遇，花型影響效率；競爭者花蜜與霜凍也有作用。'
};
M['lost-predators']={
 init:c=>({plants:c.plants,herb:c.herb.slice(),pred:c.pred,refuge:0,released:0,hunts:0,ai:0}),actions:s=>[opt('release','引回一隻捕食者'),opt('plant','恢復植被 +8'),opt('refuge','建立草食者避難區'),opt('relocate','遷出一隻捕食者'),opt('grazer','補回較少的草食者')],
 tick(s,a,c){if(a==='release'){s.pred++;s.released++;}if(a==='plant')s.plants+=8;if(a==='refuge')s.refuge++;if(a==='relocate')s.pred=Math.max(0,s.pred-1);if(a==='grazer'){let i=s.herb[0]<=s.herb[1]?0:1;s.herb[i]+=2;}let rain=c.rain[s.turn];s.plants+=rain;let eaten=Math.min(s.plants,Math.ceil(sum(s.herb)/2));s.plants-=eaten;s.herb=s.herb.map(n=>n===0?0:Math.max(0,n+(s.plants>=5?2:-1)));let prey=policy('predator',{herb:s.herb,refuge:s.refuge,plants:s.plants},s.difficulty,s.turn);s.ai=prey;let killed=Math.min(Math.max(0,s.herb[prey]-Math.min(s.refuge,3)),s.pred);s.herb[prey]-=killed;if(killed>0)s.hunts++;if(killed===0&&s.pred>0)s.pred--;s.note=`草食者吃掉 ${eaten} 植被；捕食者追蹤支系 ${prey+1}，捕獲 ${killed}。`;},metrics:s=>[['植被',s.plants],['鹿群',s.herb[0]],['兔群',s.herb[1]],['捕食者',s.pred],['回引',s.released],['捕食回合',s.hunts]],goal:(s,c)=>s.plants>=c.target&&min(s.herb)>=2&&s.pred>=1&&s.pred<=6&&s.released>=1&&s.hunts>=2,score:s=>Math.min(s.plants,30)*2+min(s.herb)*8+Math.min(s.pred,3)*6+Math.min(s.released,1)*18+Math.min(s.hunts,2)*8,objective:c=>`植被至少 ${c.target}，鹿兔各至少 2，捕食者維持 1–6；親自回引至少 1 隻，建立至少兩回合捕食。`,scene:'foodweb',reason:'捕食改變草食壓力，草食壓力再影響植被；過多捕食者也會讓獵物與自身衰退。'
};
M['vent-colony']={
 init:c=>({reserve:c.reserve,cap:c.cap,pop:c.population,dormant:false,enzyme:0,hot:0}),actions:s=>[opt('harvest','化能收穫'),opt('store','演化儲能囊 · 容量 +4'),opt('sleep','進入休眠'),opt('wake','甦醒繁殖'),opt('enzyme','演化低能耗酵素')],
 tick(s,a,c){let pulse=c.pulses[s.turn];if(a==='store'&&s.reserve>=2){s.cap+=4;s.reserve-=2;}if(a==='enzyme'&&s.reserve>=2){s.enzyme++;s.reserve-=2;}if(a==='sleep')s.dormant=true;if(a==='wake')s.dormant=false;if(a==='harvest'&&!s.dormant){s.reserve+=pulse*3;s.hot++;}if(a==='wake'&&pulse>0&&s.reserve>=3){s.pop++;s.reserve-=2;}let need=s.dormant?1:Math.max(1,3-s.enzyme);s.reserve=Math.min(s.cap,s.reserve)-need;if(s.reserve<0){s.pop--;s.reserve=0;}s.note=`噴泉強度 ${pulse}；${s.dormant?'休眠':'活動'}維持費 ${need}，超出容量的能量逸散。`;},metrics:s=>[['群落',s.pop],['能量',s.reserve],['容量',s.cap],['酵素',s.enzyme],['狀態',s.dormant?'休眠':'活動']],goal:(s,c)=>s.pop>=c.target&&s.reserve>=2&&!s.dormant&&s.hot>=2,score:s=>s.pop*18+s.reserve+Math.min(s.cap,18)/2+s.enzyme*3,objective:c=>`群落至少 ${c.target}，最後甦醒、儲能至少 2，完成兩次化能收穫。`,scene:'vent',reason:'熱脈衝提供能量；容量、酵素與休眠分別改變溢流、活動成本與冷卻期存活。'
};
M['borrowed-appearance']={
 init:c=>({pop:c.population,energy:c.energy,memory:[0,0,0],pattern:0,strategy:'camo',attacks:0,survived:0,warned:0,mimicked:0,ai:'attack'}),actions:s=>['camo','warning','mimic'].flatMap(t=>Array.from({length:3},(_,i)=>opt(t+i,`${{camo:'隱蔽色',warning:'有毒警戒',mimic:'無毒擬態'}[t]} ${['葉綠','沙黃','朱紅'][i]}`))),
 tick(s,a,c){let pattern=+a.slice(-1),type=a.slice(0,-1),e=c.habitat[s.turn];s.pattern=pattern;s.strategy=type;s.energy+=e.food-(type==='warning'?3:type==='mimic'?1:0);let visible=type!=='camo'||pattern!==e.background;let choice=policy('mimic',{signal:pattern,visible,memory:s.memory.slice()},s.difficulty,s.turn);s.ai=choice;if(choice==='attack'){s.attacks++;let damage=type==='warning'?0:type==='mimic'?2:1;s.pop-=damage;s.memory[pattern]=clamp(s.memory[pattern]+(type==='warning'?3:-2),0,6);if(type==='warning')s.warned++;}else{s.survived++;s.pop++;if(type==='mimic'){s.mimicked++;s.memory[pattern]=Math.max(0,s.memory[pattern]-1);}}s.memory=s.memory.map((v,i)=>Math.max(0,v-(i===pattern?0:1)));if(s.energy<0){s.pop+=s.energy;s.energy=0;}s.note=`捕食者${choice==='attack'?'試探攻擊':'迴避'}。${type==='warning'?'毒性使牠學會警戒；':type==='mimic'?'一旦受試探，假警戒會失效；':'符合背景可降低可見度；'}訊號記憶 ${s.memory.join('／')}。`;},metrics:s=>[['族群',s.pop],['能量',s.energy],['擬態避開',s.mimicked],['毒性教訓',s.warned],['天敵記憶',s.memory.join('/')]],goal:(s,c)=>s.pop>=c.target&&s.energy>=1&&s.survived>=2&&s.warned>=1&&s.mimicked>=2,score:s=>s.pop*10+s.energy+s.survived*4+Math.min(s.warned,1)*25+Math.min(s.mimicked,2)*22,objective:c=>`保留 ${c.target} 隻、1 能量並避開至少 2 次攻擊；先讓天敵親身學會一次有毒警戒，再用無毒擬態迴避兩次。`,scene:'mimic',reason:'捕食者只能看外表、背景與過去攻擊結果；不能讀取本代是否真的有毒。'
};
M['dormant-seedbank']={
 init:c=>({cohorts:[c.bank,0,0],bank:c.bank,harvest:0,goodYears:0,germinated:0}),actions:s=>[opt('sprout0','只發芽四分之一'),opt('sprout1','發芽一半'),opt('sprout2','發芽四分之三'),opt('sprout3','全部發芽')],
 tick(s,a,c){let q=+a[6]+1,e=c.years[s.turn],g=Math.max(1,Math.floor(s.bank*q/4)),remain=s.bank-g;s.germinated=g;let crop=Math.floor(g*e.yield);if(crop>0)s.goodYears++;s.harvest+=crop;let decay=Math.ceil(remain*e.decay);s.bank=Math.min(c.capacity,Math.max(0,remain-decay+crop));s.cohorts=[crop,Math.max(0,remain-decay),0];s.note=`${g} 顆發芽 × 年景 ${e.yield} → ${crop} 新種子；休眠種子損失 ${decay}。`;},metrics:s=>[['種子庫',s.bank],['累計產種',s.harvest],['有收成年',s.goodYears],['本年發芽',s.germinated]],goal:(s,c)=>s.bank>=c.target&&s.goodYears>=c.goodYears,score:s=>s.bank*2+s.goodYears*10,objective:c=>`結束時種子庫至少 ${c.target}，至少 ${c.goodYears} 年有收成；種子庫歸零即失敗。`,scene:'seeds',reason:'休眠分散災年的風險，但有儲藏損耗；豐年投入發芽才能補足長期種子庫。'
};
M['social-cost']={
 init:c=>({adults:c.adults,young:c.young,food:c.food,trust:c.trust,free:0,ai:'forage',care:0}),actions:s=>[opt('share','分享食物與建立互信'),opt('watch','守望防掠食'),opt('nurse','育幼'),opt('sanction','拒絕搭便車者分食'),opt('forage','採集食物')],
 tick(s,a,c){let e=c.days[s.turn];s.ai=policy('social',{food:s.food,trust:s.trust,young:s.young,free:s.free,raid:e.raid},s.difficulty,s.turn);let workers=(a==='forage'?3:0)+(s.ai==='forage'?2:0);s.food+=workers+e.fruit;if(a==='share'){s.food-=2;s.trust=Math.min(6,s.trust+2);}if(a==='sanction'){s.free=Math.max(0,s.free-2);s.trust=Math.max(0,s.trust-1);}if(s.ai==='steal'){s.food-=2;s.free++;s.trust=Math.max(0,s.trust-1);}if(s.adults>0&&(a==='nurse'||s.ai==='nurse')){s.young++;s.care++;}let guarded=a==='watch'||s.ai==='watch';if(e.raid&&!guarded){s.adults--;s.food-=e.raid;}s.food-=2;if(s.food<0){s.young=Math.max(0,s.young-1);s.adults--;s.food=0;}s.adults=Math.max(0,s.adults);if(s.young>=3&&s.food>=1){s.young-=2;s.adults++;s.food--;}s.note=`鄰居選擇${{forage:'採集',watch:'守望',nurse:'育幼',steal:'搭便車'}[s.ai]}；${e.raid?'掠食風險 '+e.raid:'平靜的一天'}。互信 ${s.trust}，搭便車 ${s.free}。`;},metrics:s=>[['成體',s.adults],['幼體',s.young],['食物',s.food],['互信',s.trust],['育幼',s.care]],goal:(s,c)=>s.adults>=c.target&&s.young>=1&&s.food>=1&&s.trust>=2&&s.care>=2,score:s=>s.adults*20+s.young*8+Math.min(s.food,12)*2+s.trust*2+s.care*3,objective:c=>`成體至少 ${c.target}、幼體至少 1、食物至少 1、互信至少 2，育幼至少兩次。`,scene:'social',reason:'採食、警戒與育幼互相佔用時間；鄰居依可見互信與資源決定合作或搭便車。'
};
M['last-habitat']={
 init:c=>({pop:c.population.slice(),open:c.edges.map(()=>false),budget:c.budget,flux:[],built:0}),actions:(s,c)=>[...c.edges.map((e,i)=>opt('edge'+i,`${e[0]+1} ↔ ${e[1]+1} 通道 · 成本 ${e[2]}${s.open[i]?'（已建）':''}`)),opt('wait','等待一代擴散')],
 tick(s,a,c){if(a!=='wait'){let i=+a.slice(4),e=c.edges[i];if(!s.open[i]&&s.budget>=e[2]){s.budget-=e[2];s.open[i]=true;s.built++;}}s.flux=[];s.open.forEach((yes,i)=>{if(!yes)return;let [a,b]=c.edges[i];if(s.pop[a]<s.pop[b])[a,b]=[b,a];if(s.pop[a]-s.pop[b]>=2&&s.pop[a]>2){s.pop[a]--;s.pop[b]++;s.flux.push([a,b]);}});s.pop=s.pop.map((p,i)=>{let cap=c.capacity[i]+c.seasons[s.turn][i];return p===0?0:Math.max(0,p+(p>=2&&p<cap?1:p>cap?-1:p===1?-1:0));});s.note=`${s.flux.length} 次沿已建通道擴散。小族群只有 1 隻時會消失；2 隻以上才能繁殖。`;},metrics:s=>s.pop.map((v,i)=>['棲地'+(i+1),v]).concat([['工程預算',s.budget]]),goal:(s,c)=>min(s.pop)>=2&&sum(s.pop)>=c.target&&s.built>=3,score:s=>s.pop.filter(x=>x>=2).length*30+sum(s.pop)+min(s.pop)*8,objective:c=>`五塊棲地各至少 2 隻，總數 ${c.target}；至少三條有效通道，工程預算不可超支。`,scene:'corridors',reason:'通道才允許個體移動；小族群需要救援，承載量與每代氣候決定能否建立。'
};
function policy(type,o,d='normal',t=0){
 if(type==='island'){if(d==='easy'){let i=o.pop.findIndex(n=>n>=6);return i>=0?i:Math.max(0,o.pop.findIndex(n=>n>0));}if(d==='normal')return o.pop.indexOf(max(o.pop));let scores=o.fit.map((v,i)=>o.pop[i]>0?v+o.pop[i]/2:-Infinity);return scores.indexOf(max(scores));}
 if(type==='pollinator'){let candidates=o.offers.filter(x=>Math.abs(x.day-o.flight)<=1);if(!candidates.length)return -1;if(d==='easy')return candidates[0].id;let scores=candidates.map(x=>x.reward+(x.shape===o.tongue?3:0)-Math.abs(x.day-o.flight)*2-(d==='hard'?o.crowd.filter(i=>i===x.id).length*5:0));return candidates[scores.indexOf(max(scores))].id;}
 if(type==='predator'){if(d==='easy'){let i=o.herb.findIndex(n=>n>o.refuge+1);return i>=0?i:o.herb.indexOf(max(o.herb));}if(d==='normal')return o.herb.indexOf(max(o.herb));return Math.max(0,o.herb[0]-o.refuge)*2>=Math.max(0,o.herb[1]-o.refuge)?0:1;}
 if(type==='mimic'){if(!o.visible)return 'avoid';let threshold=d==='easy'?1:d==='normal'?2:4;return o.memory[o.signal]>=threshold?'avoid':'attack';}
 if(type==='social'){if(d==='easy'){if(o.food<3)return 'forage';if(o.trust<2)return 'steal';return o.young<1?'nurse':'watch';}if(d==='normal'){if(o.food<4)return 'forage';if(o.trust<2)return 'steal';return o.young<2?'nurse':'watch';}if(o.raid)return o.trust>=2?'watch':'steal';if(o.food<5)return 'forage';if(o.free>1)return 'steal';return 'nurse';}
 throw Error('Unknown AI');
}
function validate(c){if(!c||!names.includes(c.game)||!Number.isInteger(c.turns)||c.turns<3||c.turns>15||typeof c.id!=='string')throw Error('Invalid mission');if(c.game==='mycelium-exchange'&&(!Number.isInteger(c.soil)||c.soil<0))throw Error('Missing bounded groundwater');return true;}
function start(c,difficulty='normal'){validate(c);if(!['easy','normal','hard'].includes(difficulty))throw Error('Invalid difficulty');return Object.assign({game:c.game,turn:0,difficulty,done:false,won:false,note:'選一個行動，觀察因果；所有數值都是遊戲抽象。',history:[],actionsTaken:[]},M[c.game].init(c));}
function actions(s,c){if(s.done)return [];return M[c.game].actions(s,c);}
function advance(s,a,c){if(!actions(s,c).some(x=>x.id===a))throw Error('Illegal action '+a);let n=clone(s);n.note='';M[c.game].tick(n,a,c);n.actionsTaken.push(a);if(!n.noAdvance)n.turn++;delete n.noAdvance;if(n.turn>=c.turns){n.done=true;n.won=!!M[c.game].goal(n,c);}if((c.game==='evolving-island'&&min(n.pop)===0)||(c.game==='intertidal-shift'&&min(n.size)===0)||(c.game==='social-cost'&&n.adults===0&&n.young===0)||(n.pop!==undefined&&typeof n.pop==='number'&&n.pop<=0)||(c.game==='dormant-seedbank'&&n.bank<=0)||(c.game==='before-wings'&&n.energy<0)){n.done=true;n.won=false;}n.history.push({turn:n.turn,values:M[c.game].metrics(n).filter(x=>typeof x[1]==='number').map(x=>({label:x[0],value:x[1]}))});return n;}
function metrics(s){return M[s.game].metrics(s);}
function score(s,c){return M[c.game].score(s,c)+(s.won?100000:0)-(s.done&&!s.won?100000:0);}
function publicState(s){let n=clone(s);if(s.game==='century-pedigree'){n.aggregateDiversity=diversity(s);n.adults=n.adults.map((g,i)=>n.known[i]?g:[g[0],null]);}return n;}
function permutations(a){return a.length?a.flatMap((x,i)=>permutations(a.filter((_,j)=>j!==i)).map(p=>[x,...p])):[[]];}
const P3=permutations([0,1,2]),P5=permutations([0,1,2,3,4]);
function fingerprint(c){let n=clone(c);delete n.id;delete n.title;delete n.brief;const pack=x=>JSON.stringify(x),least=a=>a.map(pack).sort()[0];
 if(c.game==='droplet-world'){n.foodPatches=n.patches.map((v,i)=>[v,n.regen[i]]).sort((a,b)=>a[0]-b[0]||a[1]-b[1]);delete n.patches;delete n.regen;}
 if(c.game==='evolving-island')return least(P3.map(p=>{let x=clone(n);x.habitat=p.map(i=>n.habitat[i]);x.lineages=n.niches.map((v,i)=>({niche:p.map(j=>v[j]),population:n.population[i],endangered:i===n.endangered})).sort((a,b)=>pack(a).localeCompare(pack(b)));delete x.niches;delete x.population;delete x.endangered;return x;}));
 if(c.game==='symbiotic-partners')return least(P3.map(p=>{let x=clone(n);x.health=p.map(i=>n.health[i]);x.seasons=n.seasons.map(e=>[e[0],e[1],e[2],p.indexOf(e[3])]);return x;}));
 if(c.game==='mycelium-exchange')return least(P3.map(p=>{let x=clone(n);for(let k of ['health','carbon','water'])x[k]=p.map(i=>n[k][i]);x.weather=n.weather.map(e=>Object.fromEntries(['sun','rain','demand'].map(k=>[k,p.map(i=>e[k][i])])));return x;}));
 if(c.game==='century-pedigree'){n.climate=n.climate.map(e=>[e[2],e[e[2]]]);let flip=clone(n);flip.adults=flip.adults.map(g=>[g[1],g[0]]);flip.climate=flip.climate.map(e=>[1-e[0],e[1]]);return least([n,flip]);}
 if(c.game==='bloom-timing'){delete n.shape;return least([0,1,2,3].map(code=>{let x=clone(n),day=d=>code&1?3-d:d,shape=t=>code&2?1-t:t;x.day=day(x.day);x.tongues=x.tongues.map(shape);x.seasons=x.seasons.map(e=>({...e,rivalDay:day(e.rivalDay),rivalShape:shape(e.rivalShape),flight:e.flight.map(day),frost:day(e.frost)}));return x;}));}
 if(c.game==='borrowed-appearance'){let mapping=[];n.habitat=n.habitat.map(e=>{if(!mapping.includes(e.background))mapping.push(e.background);return {...e,background:mapping.indexOf(e.background)};});}
 if(c.game==='last-habitat')return least(P5.map(p=>{let x=clone(n),inverse=i=>p.indexOf(i);x.population=p.map(i=>n.population[i]);x.capacity=p.map(i=>n.capacity[i]);x.seasons=n.seasons.map(e=>p.map(i=>e[i]));x.edges=n.edges.map(([a,b,cost])=>[Math.min(inverse(a),inverse(b)),Math.max(inverse(a),inverse(b)),cost]);return x;}));
 return pack(n);}

function replay(c,trace,d='normal'){if(!Array.isArray(trace)||!trace.length)throw Error('Empty witness');let s=start(c,d);for(let a of trace){if(typeof a!=='string')throw Error('Corrupt witness');s=advance(s,a,c);}if(!s.done||!s.won)throw Error('Witness did not achieve objective');return s;}
function solve(c,width=120){let s=start(c),prefix=[];if(c.game==='century-pedigree'){for(let i=0;i<6;i++){let a='assay'+i;s=advance(s,a,c);prefix.push(a);}}let beam=[{s,path:prefix}],best=null;for(let depth=0;depth<c.turns;depth++){let all=[],seen=new Set;for(let b of beam){for(let a of actions(b.s,c).filter(x=>!x.id.startsWith('assay'))){let n=advance(b.s,a.id,c);if(n.won)return b.path.concat(a.id);if(n.done)continue;let key=JSON.stringify(Object.fromEntries(Object.entries(n).filter(([k])=>!['history','actionsTaken','note','ai','flux'].includes(k))));if(seen.has(key))continue;seen.add(key);all.push({s:n,path:b.path.concat(a.id),q:score(n,c)});}}all.sort((x,y)=>y.q-x.q||x.path.join().localeCompare(y.path.join()));beam=all.slice(0,width);if(!beam.length)break;}return best;}
return {names,models:M,start,actions,advance,metrics,score,publicState,fingerprint,replay,solve,policy,clone,diversity};
});
