(function(r,f){if(typeof module==='object'&&module.exports)module.exports=f(require('../management-common/model.js'));else(r.ManagementGames||={})['alchemy-lab']={...(r.ManagementGames||{})['alchemy-lab'],engine:f(r.ManagementModel)};})(globalThis,function(M){'use strict';const {need,make}=M;const pair=(a,b)=>[a,b].sort((x,y)=>x-y).join(',');
return make({start:l=>({cash:l.cash,fuel:l.fuel,time:0,inventory:l.inventory.slice(),tools:[true,false,false],wear:[0,0,0],learned:[],waste:0,delivered:l.goals.map(()=>0),failed:false,note:'本遊戲是幻想鍊金規則。依原料、器具與熱度實驗，成功配方會寫入筆記。'}),
 status(l,s){return s.failed?'lost':s.delivered.every((n,i)=>n>=l.goals[i].quantity)&&s.learned.length>=l.research?'won':'playing';},
 step(l,s,a){
 if(a.type==='tool'){need([1,2].includes(a.tool)&&!s.tools[a.tool]&&s.cash>=4,'工具已解鎖或資金不足。');s.cash-=4;s.tools[a.tool]=true;s.time++;s.note='新工具已啟用。';}
 else if(a.type==='service'){need([0,1,2].includes(a.tool)&&s.tools[a.tool]&&s.wear[a.tool]>0&&s.cash>=2,'不需要保養或資金不足。');s.cash-=2;s.wear[a.tool]=0;s.time++;s.note='工具保養完成，恢復 4 次耐久。';}
 else if(a.type==='brew'){need(Number.isInteger(a.a)&&Number.isInteger(a.b)&&l.materials[a.a]&&l.materials[a.b]&&s.inventory[a.a]>0&&s.inventory[a.b]>(a.a===a.b?1:0),'需要兩份正確原料。');need([0,1,2].includes(a.tool)&&s.tools[a.tool]&&s.wear[a.tool]<4&&[1,2,3].includes(a.heat),'工具尚未啟用、磨損或熱度無效。');need(s.fuel>=a.heat,'燃料不足。');s.inventory[a.a]--;s.inventory[a.b]--;s.fuel-=a.heat;s.time+=a.heat;s.wear[a.tool]++;const ri=l.recipes.findIndex(r=>pair(r.a,r.b)===pair(a.a,a.b)&&r.tool===a.tool&&r.heat===a.heat);if(ri>=0){const r=l.recipes[ri];s.inventory[r.out]++;if(!s.learned.includes(ri))s.learned.push(ri);s.note='實驗成功：'+l.materials[r.out].name+'。';}else{s.waste+=l.materials[a.a].mass+l.materials[a.b].mass;s.note='實驗沒有形成穩定物質，原料轉為廢料。';}}
 else if(a.type==='deliver'){const g=l.goals[a.goal];need(g&&s.inventory[g.material]>0&&s.delivered[a.goal]<g.quantity,'沒有成品或已完成這份委託。');s.inventory[g.material]--;s.delivered[a.goal]++;s.note='交付一份'+l.materials[g.material].name+'。';}
 else throw Error('未知鍊金動作。');if(s.waste>l.maxWaste||s.time>l.deadline)s.failed=true;
 },actions(l,s){const a=[...[1,2].map(tool=>({type:'tool',tool})),...[0,1,2].map(tool=>({type:'service',tool})),...l.goals.map((g,goal)=>({type:'deliver',goal}))];for(let i=0;i<s.inventory.length;i++)if(s.inventory[i]>0)for(let j=i;j<s.inventory.length;j++)if(s.inventory[j]>(i===j?1:0))for(let tool=0;tool<3;tool++)for(let heat=1;heat<=3;heat++)a.push({type:'brew',a:i,b:j,tool,heat});return a;},
 describe:(l,a)=>a.type==='tool'?'啟用'+['研缽','蒸餾器','熔爐'][a.tool]:a.type==='service'?'保養'+['研缽','蒸餾器','熔爐'][a.tool]:a.type==='deliver'?'交付'+l.materials[l.goals[a.goal].material].name:`${l.materials[a.a].name}＋${l.materials[a.b].name}／${['研缽','蒸餾器','熔爐'][a.tool]}／熱度 ${a.heat}`,
 tip:()=> '原料可以重複，但需要兩份。配方線索會列出原料與器具熱度；自行試驗可發現配方，但失敗的全部質量都計入廢料。注意工具每做 4 次實驗就要保養。'
});});
