'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const E=require('./engine'),{Session}=require('./session');const K=E.id==='kalah';let checks=0;
const report={game:E.id,passed:false,difficultyLevels:Object.keys(E.LEVELS),checks:[],visualQA:'Not run by this suite. DOM/Worker harness does not measure browser layout.'};
function test(name,fn){fn();checks++;report.checks.push(name);console.log('PASS',name);}
function harness({saved=null,blockedStorage=false,noWorker=false}={}){
 const timers=new Map(),workers=[],events={},els=new Map();let tick=0;const storage=new Map(saved===null?[]:[['arcade.'+E.id+'.v1',saved]]);
 class El{
  constructor(tag='div'){this.tag=tag;this.children=[];this.listeners={};this.dataset={};this.style={setProperty(){}};this.disabled=false;this.open=false;this.value='';this.hidden=false;this.textContent='';}
  addEventListener(type,fn){(this.listeners[type]??=[]).push(fn);} emit(type,extra={}){for(const f of this.listeners[type]||[])f({target:this,preventDefault(){},...extra});}
  append(...nodes){this.children.push(...nodes);}replaceChildren(...nodes){this.children=[...nodes];}setAttribute(k,v){this[k]=v;}
  all(){return this.children.flatMap(x=>[x,...x.all()]);}
  querySelectorAll(sel){return this.all().filter(x=>x.tag==='button'&&(!sel.includes(':not(:disabled)')||!x.disabled));}
  querySelector(sel){const match=sel.match(/data-cell="([^"]+)"/);return this.querySelectorAll(sel).find(x=>!match||x.dataset.cell===match[1])||null;}
  focus(){doc.activeElement=this;}showModal(){this.open=true;}close(){this.open=false;this.emit('close');}
  click(){if(!this.disabled)this.emit('click');}
 }
 const html=fs.readFileSync(path.join(__dirname,'../'+E.id+'.html'),'utf8');for(const m of html.matchAll(/id="([^"]+)"/g))els.set(m[1],new El());
 const doc={hidden:false,activeElement:null,getElementById:id=>els.get(id),createElement:tag=>new El(tag),addEventListener:(type,fn)=>(events[type]??=[]).push(fn)};
 class Worker{constructor(){if(noWorker)throw Error('Worker unavailable');this.dead=false;workers.push(this);}postMessage(data){this.request=data;}terminate(){this.dead=true;}deliver(data){this.onmessage({data});}}
 const ctx={console,document:doc,localStorage:{getItem:k=>{if(blockedStorage)throw Error('Storage denied');return storage.get(k)||null;},setItem:(k,v)=>{if(blockedStorage)throw Error('Storage denied');storage.set(k,v);}},Worker,setTimeout:fn=>{timers.set(++tick,fn);return tick;},clearTimeout:id=>timers.delete(id),addEventListener:(type,fn)=>(events[type]??=[]).push(fn)};ctx.window=ctx;ctx.self=ctx;vm.createContext(ctx);for(const file of ['engine.js','session.js','app.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,file),'utf8'),ctx,{filename:file});
 return {ctx,doc,els,workers,storage,timers,get S(){return ctx.GameUI.session;},click:id=>els.get(id).click(),change(id,value){els.get(id).value=String(value);els.get(id).emit('change');},event(type){for(const fn of events[type]||[])fn({});},flush(){const item=timers.entries().next().value;if(item){timers.delete(item[0]);item[1]();}},move(){const s=ctx.GameUI.session.state;const m=ctx.GameEngine.legal(s)[0];if(K)els.get('board').querySelector('[data-cell="'+m+'"]')?.click();else{if(m.from!==undefined)els.get('points').querySelector('[data-cell="'+m.from+'"]')?.click();els.get('points').querySelector('[data-cell="'+(m.remove??m.to)+'"]')?.click();}},respond(worker=workers.at(-1)){const s=worker.request.state;worker.deliver({token:worker.request.token,move:ctx.GameEngine.legal(s)[0]});}};
}
function local(){const h=harness();h.change('mode','local');return h;}
function aiWaiting(){const h=harness();h.change('side',1);h.flush();assert(h.workers.length);return h;}
test('local mode enables alternating legal actions and disables AI settings',()=>{const h=local();assert(h.els.get('side').disabled);assert(h.els.get('difficulty').disabled);h.move();assert.equal(h.S.actions.length,1);assert.equal(h.timers.size,0);});
test('local undo restores initial state and can be repeated safely',()=>{const h=local();h.move();h.click('undo');assert.equal(h.S.actions.length,0);h.click('undo');assert.equal(h.S.actions.length,0);});
test('restart cancellation preserves all actions',()=>{const h=local();h.move();const data=JSON.stringify(h.S.save());h.click('restart');assert(h.els.get('confirmDialog').open);h.click('cancelConfirm');assert.equal(JSON.stringify(h.S.save()),data);});
test('restart approval resets state and stored transcript',()=>{const h=local();h.move();h.click('restart');h.click('acceptConfirm');assert.equal(h.S.actions.length,0);assert.equal(JSON.parse(h.storage.get('arcade.'+E.id+'.v1')).actions.length,0);});
test('setting cancellation restores displayed and active config',()=>{const h=local();h.move();h.change('mode','ai');assert(h.els.get('confirmDialog').open);h.click('cancelConfirm');assert.equal(h.S.config.mode,'local');assert.equal(h.els.get('mode').value,'local');});
test('confirmed settings reset once and use requested difficulty',()=>{const h=local();h.move();h.change('mode','ai');h.click('acceptConfirm');h.change('difficulty','hard');assert.equal(h.S.config.difficulty,'hard');assert.equal(h.S.actions.length,0);});
test('save and reload replay the identical local state',()=>{const h=local();for(let i=0;i<4;i++)h.move();const next=harness({saved:h.storage.get('arcade.'+E.id+'.v1')});assert.equal(JSON.stringify(next.S.state),JSON.stringify(h.S.state));});
test('malformed and illegal saves recover to a fresh game',()=>{for(const saved of ['{oops',JSON.stringify({version:1,game:E.id,config:{mode:'ai',human:0,difficulty:'normal'},actions:[K?13:{to:99}]})]){const h=harness({saved});assert.equal(h.S.actions.length,0);assert(h.els.get('status').textContent.includes('安全'));}});
test('disabled storage never blocks legal gameplay',()=>{const h=harness({blockedStorage:true});h.move();assert.equal(h.S.actions.length,1);assert(h.els.get('save').textContent.includes('無法'));});
test('computer first locks board and disallows opening undo',()=>{const h=aiWaiting();assert(h.ctx.GameUI.busy);assert(h.els.get('undo').disabled);h.move();assert.equal(h.S.actions.length,0);h.respond();assert.equal(h.S.actions.length,1);});
test('duplicate worker replies cannot apply the same search twice',()=>{const h=aiWaiting(),w=h.workers[0];h.respond(w);const n=h.S.actions.length;h.respond(w);assert.equal(h.S.actions.length,n);});
test('help pauses AI; obsolete worker reply is ignored; closing resumes',()=>{const h=aiWaiting(),w=h.workers[0];h.click('help');assert(w.dead);h.respond(w);assert.equal(h.S.actions.length,0);assert.equal(h.timers.size,0);h.click('closeHelp');h.flush();assert.equal(h.workers.length,2);h.respond();assert.equal(h.S.actions.length,1);});
test('background visibility cancels AI and foreground resumes',()=>{const h=aiWaiting(),w=h.workers[0];h.doc.hidden=true;h.event('visibilitychange');h.respond(w);assert.equal(h.S.actions.length,0);h.doc.hidden=false;h.event('visibilitychange');h.flush();h.respond();assert.equal(h.S.actions.length,1);});
test('pagehide cancels and pageshow resumes a pending computer turn',()=>{const h=aiWaiting(),w=h.workers[0];h.event('pagehide');assert(w.dead);h.respond(w);assert.equal(h.S.actions.length,0);h.event('pageshow');h.flush();h.respond();assert.equal(h.S.actions.length,1);});
test('restart prevents obsolete search from mutating the new game',()=>{const h=aiWaiting(),w=h.workers[0];h.click('restart');h.click('acceptConfirm');h.respond(w);assert.equal(h.S.actions.length,0);h.flush();h.respond();assert.equal(h.S.actions.length,1);});
test('illegal worker result falls back to a legal move',()=>{const h=aiWaiting(),w=h.workers[0];w.deliver({token:w.request.token,move:K?13:{to:99}});assert.equal(h.S.actions.length,1);assert(h.els.get('status').textContent.includes('合法'));});
test('worker error falls back to bounded synchronous search',()=>{const h=aiWaiting();h.workers[0].onerror();h.flush();assert.equal(h.S.actions.length,1);});
test('unsupported worker uses a bounded compatibility search',()=>{const h=harness({noWorker:true});h.change('side',1);h.flush();h.flush();assert.equal(h.S.actions.length,1);});
test('wrong worker generation is ignored',()=>{const h=aiWaiting(),w=h.workers[0];w.deliver({token:w.request.token-1,move:h.ctx.GameEngine.legal(h.S.state)[0]});assert.equal(h.S.actions.length,0);h.respond();assert.equal(h.S.actions.length,1);});
test('AI undo retracts human turn and pending response',()=>{const h=harness();h.move();while(!h.S.isAI()&&h.S.state.result===null)h.move();h.flush();const w=h.workers.at(-1);h.click('undo');assert.equal(h.S.actions.length,0);h.respond(w);assert.equal(h.S.actions.length,0);});
test('session save snapshots cannot mutate the live transcript',()=>{const s=new Session();s.play(E.legal(s.state)[0]);const save=s.save();save.actions.push(K?1:{to:2});if(!K)save.actions[0].to=99;assert.equal(s.actions.length,1);assert.deepEqual(E.replay(s.actions),s.state);});
if(K)test('local undo retracts an entire bonus-turn chain',()=>{const s=new Session({mode:'local',human:0,difficulty:'normal'});s.play(2);assert.equal(s.state.turn,0);s.play(0);s.undo();assert.equal(s.actions.length,0);});
else test('mill placement and capture form one local undo unit',()=>{const s=new Session({mode:'local',human:0,difficulty:'normal'});for(const m of [{to:0},{to:9},{to:1},{to:10},{to:2},{remove:9}])assert(s.play(m));s.undo();assert.equal(s.actions.length,4);assert.equal(s.state.board[2],-1);assert.equal(s.state.board[9],1);});
for(const difficulty of Object.keys(E.LEVELS))test(difficulty+' worker script returns a legal opening with matching token',()=>{let answer;const ctx={self:{postMessage:data=>answer=data}};ctx.self.self=ctx.self;ctx.importScripts=()=>{ctx.GameEngine=E;};vm.createContext(ctx);vm.runInContext(fs.readFileSync(path.join(__dirname,'ai-worker.js'),'utf8'),ctx);ctx.self.onmessage({data:{token:73,state:E.initial(),difficulty}});assert.equal(answer.token,73);assert(E.legal(E.initial()).some(m=>K?m===answer.move:E.equalMove(m,answer.move)));});
report.passed=true;report.total=checks;report.controller={passed:true,checks};try{report.rules=JSON.parse(fs.readFileSync(path.join(__dirname,'rule-results.json'),'utf8'));report.passed=report.passed&&report.rules.passed;}catch(error){report.passed=false;report.rules={passed:false,error:'Run rules-tests.cjs first'};}fs.writeFileSync(path.join(__dirname,'verification.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({passed:true,game:E.id,controllerChecks:checks}));
