(function(root,factory){const api=factory();if(typeof module==='object')module.exports=api;else root.PinballStorage=api;})(globalThis,function(){'use strict';
const current='arcade.starport.pinball20.v1',legacy='arcade.starport.polish-v2.v1';
const empty=()=>({schema:3,manual:0,assisted:0,awarded:[],manualStages:[],assistedStages:[]});
function validate(raw,isLegacy=false){try{const p=JSON.parse(raw);if(!p||!(isLegacy?[1,2]:[3]).includes(p.schema)||![p.manual,p.assisted].every(x=>Number.isFinite(x)&&x>=0)||!Array.isArray(p.awarded)||!p.awarded.every(x=>typeof x==='string'))return null;const max=isLegacy?10:20;if(p.schema!==1&&!['manualStages','assistedStages'].every(k=>Array.isArray(p[k])&&p[k].length<=max&&new Set(p[k]).size===p[k].length&&p[k].every(x=>Number.isInteger(x)&&x>=1&&x<=max)))return null;return{schema:3,manual:p.manual,assisted:p.assisted,awarded:p.awarded.slice(-100),manualStages:p.schema===1?[]:[...p.manualStages],assistedStages:p.schema===1?[]:[...p.assistedStages]};}catch(e){return null;}}
function merge(...profiles){const out=empty();for(const p of profiles.filter(Boolean)){out.manual=Math.max(out.manual,p.manual);out.assisted=Math.max(out.assisted,p.assisted);out.awarded=[...new Set([...out.awarded,...p.awarded])].slice(-100);for(const k of ['manualStages','assistedStages'])out[k]=[...new Set([...out[k],...p[k]])].sort((a,b)=>a-b);}return out;}
function readProfile(storage){let now=null,old=null;try{now=validate(storage.getItem(current+'.records'));}catch(e){}try{old=validate(storage.getItem(legacy+'.records'),true);}catch(e){}return now||old?merge(now,old):null;}
function migrateProfileIfAbsent(storage){try{if(storage.getItem(current+'.records')!==null)return false;const old=validate(storage.getItem(legacy+'.records'),true);if(!old)return false;storage.setItem(current+'.records',JSON.stringify(old));return true;}catch(e){return false;}}
function readRun(storage){const raw=storage.getItem(current+'.run');if(raw!==null)return{raw,isLegacy:false};const old=storage.getItem(legacy+'.run');return old===null?null:{raw:old,isLegacy:true};}
function readPreferences(storage){for(const key of [current,legacy]){try{const p=JSON.parse(storage.getItem(key+'.preferences'));if(p&&['sound','haptics','reduced'].every(k=>typeof p[k]==='boolean'))return p;}catch(e){}}return null;}
return Object.freeze({current,legacy,empty,validate,merge,readProfile,migrateProfileIfAbsent,readRun,readPreferences});});
