'use strict';const assert=require('node:assert/strict'),C=require('./common'),E=require('./engine'),Cl=require('./climbing'),T=require('./tricks'),P=require('./poker'),R=require('./rummy'),I=require('./independent.cjs');const card=(r,s=0)=>s*13+(r===1?12:r-2);const hand=spec=>spec.map(([r,s])=>card(r,s||0));
function rules(game){const e=E.create(game);assert.equal(e.validatePosition({version:1,game,turn:0,stock:[],ply:0}),false);assert.equal(e.validatePosition(null),false);assert.throws(()=>e.apply(e.initial(3),{type:'hack'}));if(game==='big-two'){assert(!Cl.bigType(hand([[3,0],[3,1],[4,0],[4,1],[5,0]])),'two pair is not a five card play');assert(Cl.bigType(hand([[1,0],[2,1],[3,2],[4,3],[5,0]])));assert(!Cl.bigType(hand([[12,0],[13,1],[1,2],[2,3],[3,0]])),'no wrap straight');assert(e.beats(Cl.bigType([card(2,3)]),Cl.bigType([card(1,3)])));assert(e.beats(Cl.bigType([card(3,0)]),Cl.bigType([card(3,1)])));let s=e.initial(2);assert(!e.legal(s,{type:'pass'}));let a=e.actions(s)[0];s=e.apply(s,a);const leader=s.leader;for(let i=0;i<3;i++)s=e.apply(s,{type:'pass'});assert.equal(s.turn,leader);assert.equal(s.last,null);}
if(game==='dou-dizhu'){const cases=[[[3,0]],[[3,0],[3,1]],[[3,0],[3,1],[3,2]],[[3,0],[3,1],[3,2],[4,0]],[[3,0],[3,1],[3,2],[4,0],[4,1]],[[3,0],[4,0],[5,0],[6,0],[7,0]],[[3,0],[3,1],[4,0],[4,1],[5,0],[5,1]],[[3,0],[3,1],[3,2],[4,0],[4,1],[4,2]],[[3,0],[3,1],[3,2],[4,0],[4,1],[4,2],[7,0],[8,0]],[[3,0],[3,1],[3,2],[4,0],[4,1],[4,2],[7,0],[7,1],[8,0],[8,1]],[[3,0],[3,1],[3,2],[3,3]],[[3,0],[3,1],[3,2],[3,3],[4,0],[5,0]],[[3,0],[3,1],[3,2],[3,3],[4,0],[4,1],[5,0],[5,1]]];for(const x of cases){assert(Cl.douType(hand(x)));assert.deepEqual(Cl.douType(hand(x)),I.dou(hand(x)));}assert.equal(Cl.douType([52,53])[0],'rocket');assert.equal(Cl.douType([1,14,27,2,15,28,3,16,29,4,17,30])[0],'plane','Four bare triplets must not be mistaken for single wings');assert(e.beats(Cl.douType([52,53]),Cl.douType(hand(cases[10]))));assert(!Cl.douType(hand([[11,0],[12,0],[13,0],[1,0],[2,0]])),'2 excluded from straights');assert(!Cl.douType([...hand(cases[10]),52,53]),'both jokers cannot be kickers');let s=e.initial(3);s=e.apply(s,{type:'pass'});s=e.apply(s,{type:'pass'});s=e.apply(s,{type:'pass'});assert(s.over);s=e.initial(4);s=e.apply(s,{type:'bid',value:3});assert.equal(s.hands[s.landlord].length,20);assert.equal(s.bottom.length,3);assert.equal(s.stock.length,0);}
if(game==='sevens'){const s=e.initial(2);assert.deepEqual(e.actions(s),[{type:'play',card:18}]);assert(!e.legal(s,{type:'pass'}));let x=e.apply(s,e.actions(s)[0]);for(const a of e.actions(x))I.action(x,a);}
if(game==='crazy-eights'){const s=e.initial(10);assert.notEqual(C.rank(s.discard[0]),8);const h=s.hands[s.turn];const eight=h.find(c=>C.rank(c)===8);if(eight!==undefined)assert.equal(e.actions(s).filter(a=>a.card===eight).length,4);assert(e.legal(s,{type:'draw'}));const x=e.apply(s,{type:'draw'});assert.equal(x.turn,s.turn);assert.equal(x.hands[s.turn].length,h.length+1);}
if(game==='hearts'||game==='spades'){let s=e.initial(82,{round:3});if(game==='hearts'){assert.equal(s.phase,'play');assert.deepEqual(e.actions(s),[{type:'play',card:0}]);}else{for(let p=0;p<4;p++)s=e.apply(s,{type:'bid',value:p===0?0:3});assert.equal(s.phase,'play');assert(!e.actions(s).some(a=>C.suit(a.card)===3));}while(!s.over){const a=e.choose(s);s=e.apply(s,a);}assert.equal(s.tricks.reduce((a,b)=>a+b,0),13);if(game==='hearts')assert([26,78].includes(s.scores.reduce((a,b)=>a+b,0)));}
if(game==='contract-bridge'){assert.equal(T.bridgeScore({level:3,denom:4,doubled:0},9,false),400);assert.equal(T.bridgeScore({level:4,denom:3,doubled:0},10,true),620);assert.equal(T.bridgeScore({level:2,denom:2,doubled:1},8,false),470);assert.equal(T.bridgeScore({level:6,denom:4,doubled:0},12,true),1440);assert.equal(T.bridgeScore({level:7,denom:4,doubled:0},13,false),1520);assert.equal(T.bridgeScore({level:4,denom:3,doubled:1},7,false),-500);assert.equal(T.bridgeScore({level:4,denom:3,doubled:2},7,true),-1600);let s=e.initial(7);s=e.apply(s,{type:'bid',level:1,denom:2});assert(e.legal(s,{type:'double'}));s=e.apply(s,{type:'double'});assert(e.legal(s,{type:'redouble'}));s=e.apply(s,{type:'redouble'});for(let i=0;i<3;i++)s=e.apply(s,{type:'pass'});assert.equal(s.declarer,0);assert.equal(s.dummy,2);assert.equal(s.turn,1);assert(!('dummyHand'in e.observe(s,0)));s=e.apply(s,e.actions(s)[0]);assert.deepEqual(e.observe(s,0).dummyHand,s.hands[2]);assert.equal(e.actor(s),0);assert.equal(s.contract.doubled,2);}
if(game==='gin-rummy'){const gin=hand([[1,0],[2,0],[3,0],[4,0],[5,1],[6,1],[7,1],[9,0],[9,1],[9,2]]);assert.equal(R.analyze(gin).deadwood,0);assert.equal(I.independentDeadwood(gin),0);const knock=hand([[3,0],[4,0],[5,0],[8,0],[8,1],[8,2],[11,1],[12,1],[13,1],[2,2]]);assert.equal(R.analyze(knock).deadwood,2);assert.equal(R.layoff(hand([[2,0],[6,0],[7,0]]),[hand([[3,0],[4,0],[5,0]])]).value,0);let s=e.initial(1);s=e.apply(s,{type:'pass'});s=e.apply(s,{type:'pass'});assert.deepEqual(e.actions(s),[{type:'stock'}]);s=e.apply(s,{type:'stock'});assert.equal(s.phase,'discard');s=e.apply(s,e.actions(s).find(a=>a.type==='discard'));s=e.apply(s,{type:'take'});assert(!e.actions(s).some(a=>a.card===s.picked));}
if(game==='chinese-poker'){const s=e.initial(98),rows=P.arrangement(s.hands[0]);assert(P.arrangeLegal(s.hands[0],rows));assert(!P.arrangeLegal(s.hands[0],[rows[2],rows[1],rows[0]]));assert.equal(C.poker(hand([[2,0],[3,0],[4,0]]))[0],0);assert.equal(C.poker(hand([[7,0],[7,1],[7,2]]))[0],3);const a={type:'arrange',rows};assert(e.legal(s,a));assert.equal(e.apply(s,a).turn,1);}
if(game==='texas-holdem'){let s=e.initial(53);assert.equal(s.turn,3);assert.equal(s.pot,3);assert(!e.legal(s,{type:'raise',amount:3}));assert(e.legal(s,{type:'raise',amount:4}));const raiser=s.turn;s=e.apply(s,{type:'raise',amount:8});assert.equal(s.minRaise,6);s=e.apply(s,{type:'call'});s=e.apply(s,{type:'call'});s=e.apply(s,{type:'call'});assert.equal(s.street,1);assert.equal(s.board.length,3);assert.equal(s.burned.length,1);assert.equal(s.turn,1);assert.equal(s.pot,32);assert.equal(s.currentBet,0);const fixture={contributions:[50,100,100,200],folded:[false,false,false,false],dealer:0,hands:hand([[1,0],[1,1],[13,0],[13,1],[12,0],[12,1],[11,0],[11,1]]).reduce((a,c,i)=>(a[Math.floor(i/2)].push(c),a),[[],[],[],[]]),board:hand([[2,2],[4,3],[6,0],[8,2],[10,3]])};const pots=P.settlePots(fixture);assert.deepEqual(pots.payouts,[200,150,0,100]);assert.equal(pots.payouts.reduce((a,b)=>a+b,0),450);const short=e.initial(2,{stacks:[200,10,200,200]});let q=e.apply(short,{type:'raise',amount:8});q=e.apply(q,{type:'call'});q=e.apply(q,{type:'raise',amount:10});assert(q.raiseLocked[3]);assert(q.pending.includes(3));assert.equal(q.minRaise,6);
let cum=e.initial(1,{stacks:[10,14,200,200]});cum=e.apply(cum,{type:'raise',amount:8});cum=e.apply(cum,{type:'raise',amount:10});cum=e.apply(cum,{type:'raise',amount:14});assert(!cum.raiseLocked[3]);cum=e.apply(cum,{type:'call'});assert(e.legal(cum,{type:'raise',amount:20}));
let tiny=e.initial(2,{stacks:[200,3,200,200]});for(let i=0;i<4;i++)tiny=e.apply(tiny,{type:i<3?'call':'check'});tiny=e.apply(tiny,{type:'raise',amount:1});assert(e.legal(tiny,{type:'raise',amount:2}));assert.equal(e.minRaiseTo(tiny),2);
}
console.log('PASS rule fixtures',game);return true;}if(require.main===module)for(const game of process.argv.slice(2).length?process.argv.slice(2):E.IDS)rules(game);module.exports={rules};
