(function(root,factory){const api=factory(typeof module==='object'?require('./common.js'):root.CardCore);if(typeof module==='object'&&module.exports)module.exports=api;else root.CardRummy=api;})(typeof globalThis!=='undefined'?globalThis:this,function(C){
'use strict';const {clone,rank,low,suit,base,remove,combos}=C;
const value=c=>Math.min(10,low(c));
function melds(h){const out=[];for(const[,cs]of C.groups(h)){for(const k of[3,4])for(const cards of combos(cs,k))out.push(cards);}for(let su=0;su<4;su++){const cs=h.filter(c=>suit(c)===su).sort((a,b)=>low(a)-low(b));for(let i=0;i<cs.length;i++)for(let j=i+2;j<cs.length;j++){const seq=cs.slice(i,j+1);if(seq.every((c,k)=>!k||low(c)===low(seq[k-1])+1))out.push(seq);}}return out;}
function partitions(h,visit){const ms=melds(h).map(cards=>({cards,mask:cards.reduce((m,c)=>m|1<<h.indexOf(c),0)}));function go(mask,chosen,dead){if(!mask){visit(chosen,dead);return;}const i=Math.floor(Math.log2(mask&-mask)),bit=1<<i;go(mask^bit,chosen,[...dead,h[i]]);for(const m of ms)if((m.mask&bit)&&(m.mask&mask)===m.mask)go(mask^m.mask,[...chosen,m.cards],dead);}go((1<<h.length)-1,[],[]);}
function analyze(h){let best={deadwood:Infinity,melds:[],dead:[]};partitions(h,(ms,dead)=>{const n=dead.reduce((v,c)=>v+value(c),0);if(n<best.deadwood)best={deadwood:n,melds:ms,dead};});return best;}
function layoff(dead,ms){let best={value:dead.reduce((n,c)=>n+value(c),0),cards:[]};function go(ds,sets,used){const v=ds.reduce((n,c)=>n+value(c),0);if(v<best.value)best={value:v,cards:used};for(const c of ds)for(let i=0;i<sets.length;i++){const m=sets[i],same=m.every(x=>rank(x)===rank(m[0]));const valid=same?rank(c)===rank(m[0])&&m.length<4:suit(c)===suit(m[0])&&(low(c)===Math.min(...m.map(low))-1||low(c)===Math.max(...m.map(low))+1);if(valid){const next=sets.map(x=>x.slice());next[i].push(c);go(ds.filter(x=>x!==c),next,[...used,c]);}}}go(dead,ms,[]);return best;}
function defense(h,knockMelds,gin){let best={deadwood:Infinity,melds:[],dead:[],layoff:[]};partitions(h,(ms,dead)=>{const lo=gin?{value:dead.reduce((n,c)=>n+value(c),0),cards:[]}:layoff(dead,knockMelds);if(lo.value<best.deadwood)best={deadwood:lo.value,melds:ms,dead,layoff:lo.cards};});return best;}
function create(){const game='gin-rummy';function initial(seed,opts={}){const s=base(game,seed,2,10);s.turn=(opts.round||0)%2;s.dealer=1-s.turn;s.discard=[s.stock.shift()];s.phase='draw';s.opening=0;s.picked=null;return s;}
function actions(s){if(s.over)return[];if(s.phase==='draw'){if(s.opening<2)return[{type:'take'},{type:'pass'}];return[{type:'stock'},...(s.opening===2?[]:s.discard.length?[{type:'take'}]:[])];}const out=[];for(const card of s.hands[s.turn])if(card!==s.picked){out.push({type:'discard',card});if(analyze(s.hands[s.turn].filter(c=>c!==card)).deadwood<=10)out.push({type:'knock',card});}return out;}
function legal(s,a){return actions(s).some(x=>C.equal(x,a));}
function apply(s,a){if(!legal(s,a))throw Error('抽牌或棄牌不合法');s=clone(s);const p=s.turn;s.ply++;if(s.phase==='draw'){if(a.type==='pass'){s.opening++;s.turn=1-p;return s;}s.picked=a.type==='take'?s.discard.at(-1):null;s.hands[p].push(a.type==='take'?s.discard.pop():s.stock.shift());s.phase='discard';s.opening=3;return s;}
s.hands[p]=remove(s.hands[p],[a.card]);s.discard.push(a.card);s.picked=null;if(a.type==='knock'){const own=analyze(s.hands[p]),opp=defense(s.hands[1-p],own.melds,own.deadwood===0);s.over=true;s.phase='end';s.arrangements=[];s.arrangements[p]=own;s.arrangements[1-p]=opp;let w=p,points;if(!own.deadwood)points=25+opp.deadwood;else if(opp.deadwood<=own.deadwood){w=1-p;points=25+own.deadwood-opp.deadwood;}else points=opp.deadwood-own.deadwood;s.scores[w]=points;s.winners=[w];s.result=!own.deadwood?'Gin：無散牌':w===p?'敲牌成功':'反敲（Undercut）';}else if(s.stock.length<=2){s.over=true;s.phase='end';s.result='牌庫剩兩張，和局';}else{s.turn=1-p;s.phase='draw';}return s;}
function ai(o,level='normal'){if(o.phase==='draw'){const take=o.actions.find(x=>x.type==='take'),cur=analyze(o.hand).deadwood;let best=Infinity;if(take){const h=[...o.hand,o.discard.at(-1)];for(const c of o.hand)best=Math.min(best,analyze(h.filter(x=>x!==c)).deadwood);}if(take&&best<cur)return take;return o.actions.find(x=>x.type==='stock'||x.type==='pass')||take;}const knock=o.actions.filter(x=>x.type==='knock');if(knock.length)return knock.sort((a,b)=>analyze(o.hand.filter(c=>c!==a.card)).deadwood-analyze(o.hand.filter(c=>c!==b.card)).deadwood)[0];let scored=o.actions.map(x=>({x,d:analyze(o.hand.filter(c=>c!==x.card)).deadwood})).sort((a,b)=>a.d-b.d||value(b.x.card)-value(a.x.card));if(level==='easy')return scored[C.hash([o.hand,o.discard])%Math.min(3,scored.length)].x;return scored[0].x;}
return{game,initial,actions,legal,apply,ai,actor:s=>s.turn};}
return{create,melds,analyze,partitions,layoff,defense};
});
