/* Executes actual UI JavaScript in a tiny deterministic DOM. No visual claims. */
'use strict';const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),E=require('./engine.js'),DATA=require('./levels.json');
class El{constructor(tag='div'){this.tagName=tag.toUpperCase();this.children=[];this.listeners={};this.dataset={};this.attributes={};this._text='';this.className='';this.hidden=false;this.disabled=false;this.value='';this.open=false;this.style={setProperty:(k,v)=>this.style[k]=v};this.classList={toggle:(c,on)=>{let a=this.className.split(/\s+/).filter(Boolean);if(on&&!a.includes(c))a.push(c);if(!on)a=a.filter(x=>x!==c);this.className=a.join(' ');},contains:c=>this.className.split(/\s+/).includes(c)};}set textContent(t){this._text=String(t);this.children=[];}get textContent(){return this._text;}set innerHTML(t){this._html=t;this.children=[];}appendChild(e){this.children.push(e);return e;}setAttribute(k,v){this.attributes[k]=String(v);}addEventListener(k,f){(this.listeners[k]??=[]).push(f);}dispatch(k,e={}){for(const f of this.listeners[k]||[])f(e);}click(){if(!this.disabled&&this.onclick)this.onclick({target:this});}showModal(){this.open=true;}close(){this.open=false;this.dispatch('close');}}
const html=fs.readFileSync(__dirname+'/../traffic-jam.html','utf8'),source=fs.readFileSync(__dirname+'/app.js','utf8');const storage=new Map();
function boot(){const ids={};for(const m of html.matchAll(/<([\w]+)[^>]*\bid="([^"]+)"/g))ids[m[2]]=new El(m[1]);const closes=['helpDialog','solutionDialog'].map(id=>{let b=new El('button');b.dataset.close=id;return b;});let tid=0;const timers=new Map(),intervals=new Map(),events={};const doc={hidden:false,getElementById:id=>{assert(ids[id],id);return ids[id];},createElement:tag=>new El(tag),querySelector:s=>s==='dialog[open]'?Object.values(ids).find(e=>e.tagName==='DIALOG'&&e.open)||null:null,querySelectorAll:s=>s==='[data-close]'?closes:[],addEventListener:(k,f)=>{(events[k]??=[]).push(f);}};const win={addEventListener:(k,f)=>{(events['window:'+k]??=[]).push(f);}};const ctx={window:win,document:doc,TrafficEngine:E,TRAFFIC_LEVELS:DATA,console,localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},confirm:()=>true,setTimeout:f=>{timers.set(++tid,f);return tid;},clearTimeout:id=>timers.delete(id),setInterval:f=>{intervals.set(++tid,f);return tid;}};vm.runInNewContext(source,ctx);function flush(limit=10000){let n=0;while(timers.size){assert(n++<limit,'timer loop');const [id,f]=timers.entries().next().value;timers.delete(id);f();}return n;}return {ids,ctx,game:win.TrafficGame,flush,timers,intervals,events,doc,closes};}
let ui=boot(),{ids,game}=ui;assert.equal(game.getLevel(),1);assert.equal(ids.level.children.length,50);assert.equal(ids.board.children.length,36+DATA.levels[0].cars.length);
// Exercise actual car selection and destination taps for every published move.
for(const l of DATA.levels){game.setLevel(l.id,false);for(const m of l.solution){const before=game.getState(),[axis,lane,len]=l.cars[m[0]],at=m[1]<before[m[0]]?m[1]:m[1]+len-1,x=axis==='H'?at:lane,y=axis==='H'?lane:at;ids.board.children[36+m[0]].click();assert.equal(ids.board.children[36+m[0]].attributes['aria-pressed'],'true');ids.board.children[y*6+x].click();assert.equal(game.getState()[m[0]],m[1]);}assert(E.won(l,game.getState()));assert.equal(ids.won.hidden,false);assert.equal(game.getHistory().length,l.optimal);ids.undo.click();assert(!E.won(l,game.getState()));assert.equal(ids.won.hidden,true);}
assert.equal(ids.completed.textContent,'50/50');
// Unlimited undo restores exact start even after a deliberately inefficient route.
game.setLevel(1,false);const initial=E.key(game.getState());let m=E.moves(DATA.levels[0],game.getState())[0];for(let k=0;k<200;k++){const old=game.getState()[m[0]];game.move(m);m=[m[0],old];}assert.equal(game.getHistory().length,200);for(let k=0;k<200;k++)ids.undo.click();assert.equal(E.key(game.getState()),initial);
// Current-state re-solving works after leaving the published witness.
const first=DATA.levels[0].solution[0];const deviation=E.moves(DATA.levels[0],game.getState()).find(m=>m[0]!==first[0]||m[1]!==first[1]);game.move(deviation);ids.hint.click();ui.flush();assert.equal(ids.applyHint.hidden,false);assert.match(ids.status.textContent,/目前至少還需/);const before=game.getHistory().length;ids.applyHint.click();assert.equal(game.getHistory().length,before+1);
// Full route, single-step, playback pause, modal close cancellation, and stale search.
ids.solution.click();assert(ids.solutionDialog.open);ui.flush();assert(ids.solutionList.children.length>0);ids.stepSolution.click();assert.equal(game.getRouteIndex(),1);ids.playSolution.click();assert(ui.timers.size>0);ids.stopSolution.click();assert.equal(ui.timers.size,0);ids.playSolution.click();ids.solutionDialog.close();assert.equal(ui.timers.size,0);const paused=game.getHistory().length;ui.flush();assert.equal(game.getHistory().length,paused);
game.setLevel(50,false);ids.hint.click();assert(ui.timers.size>0);game.setLevel(2,false);ui.flush();assert.equal(game.getLevel(),2);assert.equal(ids.applyHint.hidden,true);
// Full solution playback to the hardest puzzle's win then restore a saved state.
game.setLevel(50,false);ids.solution.click();ui.flush();ids.playSolution.click();ui.flush();assert(E.won(DATA.levels[49],game.getState()));assert.equal(game.getHistory().length,44);assert.equal(ids.stepSolution.disabled,true);ids.solutionDialog.close();ids.undo.click();const restoredKey=E.key(game.getState()),restoredMoves=game.getHistory().length;ui=boot();ids=ui.ids;game=ui.game;assert.equal(E.key(game.getState()),restoredKey);assert.equal(game.getHistory().length,restoredMoves);assert.equal(ids.completed.textContent,'50/50');
// Cancelled restart and level change preserve the complete state.
ui.ctx.confirm=()=>false;ids.restart.click();assert.equal(E.key(game.getState()),restoredKey);ids.level.value='2';ids.level.onchange({target:ids.level});assert.equal(game.getLevel(),50);assert.equal(ids.level.value,'50');ui.ctx.confirm=()=>true;
// Storage exceptions do not prevent moves/undo. Invalid saves never load.
ui.ctx.localStorage.setItem=()=>{throw Error('disabled storage');};ids.undo.click();assert.equal(game.getHistory().length,restoredMoves-1);assert.match(ids.status.textContent,/無法儲存/);storage.set('arcade.traffic-jam.v1',JSON.stringify({...game.getPayload(),state:[]}));ui=boot();assert.equal(ui.game.getLevel(),1);assert.equal(ui.game.getHistory().length,0);
// Completed flags alone are not trusted; only legal winning histories count.
storage.set('arcade.traffic-jam.completed.v1',JSON.stringify({1:{history:[],elapsed:0},2:{history:[[0,4]],elapsed:0},99:{history:[],elapsed:0}}));ui=boot();assert.equal(ui.ids.completed.textContent,'0/50');
console.log('PASS actual UI script: all 50 tap-played witnesses; 200-step undo; divergent hints; complete 44-step playback; modal/pause/navigation cancellation; stale-search cancellation; reload; corrupt-state and false-completion rejection; storage failure. Visual rendering NOT tested.');
