(function(){'use strict';
const E=LightsEngine,S=LightsSession,levels=LIGHTS_LEVELS,$=id=>document.getElementById(id),KEY='arcade.lights-out.v1';
let index=0,actions=[],states=[],seconds=0,assisted=false,progress={},hintCell=null,focusCell=0,playing=false,playTimer=null,operation=0,confirmAction=null,message='';
const level=()=>levels[index],state=()=>states.at(-1),won=()=>E.won(state()),time=n=>Math.floor(n/60)+':'+String(Math.floor(n%60)).padStart(2,'0'),coord=i=>`${Math.floor(i/level().size)+1} 列 ${i%level().size+1} 欄`;
function save(){let ok=true;try{localStorage.setItem(KEY,JSON.stringify({version:1,index,actions,seconds,assisted,progress}));}catch(_){ok=false;}$('save').textContent=ok?'進度已保存在此瀏覽器'+(assisted?' · 本局已使用輔助':''):'此瀏覽器無法儲存；仍可遊玩，離開後進度可能遺失';}
function stop(announce=false){operation++;clearTimeout(playTimer);playing=false;if(announce)message='已停止，你可以接著思考';}
function options(){$('level').replaceChildren(...levels.map((l,i)=>{const o=document.createElement('option');o.value=i;o.textContent=`${progress[i]?'✓ ':''}${String(i+1).padStart(2,'0')} · ${l.size}×${l.size} · 目標 ${l.par} 步`;return o;}));$('level').value=index;}
function mount(){const l=level();$('board').style.gridTemplateColumns=`repeat(${l.size},1fr)`;$('board').replaceChildren();for(let i=0;i<l.size*l.size;i++){const b=document.createElement('button');b.className='cell';b.type='button';b.dataset.cell=i;b.addEventListener('click',()=>{if(!won()&&!playing){focusCell=i;perform(i);}});b.addEventListener('focus',()=>{focusCell=i;for(const cell of $('board').querySelectorAll('button'))cell.tabIndex=Number(cell.dataset.cell)===i?0:-1;});$('board').append(b);}focusCell=0;}
function render(){const l=level(),s=state(),done=won(),range=hintCell===null?[]:E.affected(l.size,hintCell);for(const b of $('board').querySelectorAll('button')){const i=Number(b.dataset.cell);b.className='cell'+(s[i]?' on':'')+(i===hintCell?' hint':range.includes(i)?' affected':'');b.disabled=done||playing;b.tabIndex=i===focusCell?0:-1;b.setAttribute('aria-pressed',String(!!s[i]));b.setAttribute('aria-label',`${coord(i)}，${s[i]?'亮燈':'熄燈'}${i===hintCell?'，提示點擊':''}`);}
$('remaining').innerHTML=s.reduce((a,b)=>a+b,0)+'<span>盞</span>';$('moves').textContent=actions.length;$('timer').textContent=time(seconds);$('progress').innerHTML=Object.keys(progress).length+'<span>/ 50</span>';$('boardTitle').textContent=`第 ${String(index+1).padStart(2,'0')} 關 · ${l.size} × ${l.size}`;$('levelInfo').textContent=`${l.size}×${l.size} 棋盤 · 初始目標 ${l.par} 步\n熄滅所有燈，不限步數`;const b=progress[index];$('best').textContent=b?`最佳：${b.moves} 步 · ${time(b.seconds)} · ${b.assisted?'輔助完成':'自行完成'}`:'最佳紀錄：尚未完成';$('next').disabled=index===49;$('undo').disabled=!actions.length||playing;$('hint').disabled=done||playing;$('solution').disabled=done||playing;$('solution').hidden=playing;$('stop').hidden=!playing;$('win').hidden=!done;if(done)$('winDetail').textContent=`${actions.length} 步 · 目標 ${l.par} 步 · ${time(seconds)} · ${assisted?'輔助完成':'自行完成'}`;$('status').textContent=message||(done?'全暗了！這一局完成':'點一盞燈，翻轉它與上下左右的燈光');}
function finish(){if(!won())return;stop();const b={moves:actions.length,seconds,assisted,witness:actions.slice()},old=progress[index];if(!old||old.assisted&&!b.assisted||old.assisted===b.assisted&&(b.moves<old.moves||b.moves===old.moves&&b.seconds<old.seconds))progress[index]=b;options();message=actions.length===level().par?'漂亮！你用初始目標步數熄滅了所有燈':'所有燈都熄滅了，恭喜完成！';}
function perform(i){states.push(E.step(level(),state(),i));actions.push(i);hintCell=null;message='';finish();save();render();}
function start(i){stop();index=i;actions=[];states=[E.initial(level())];seconds=0;assisted=false;hintCell=null;message='';options();mount();save();render();}
function confirm(text,fn){stop();render();confirmAction=fn;$('confirmText').textContent=text;$('confirmDialog').showModal();}
function requestStart(i){if(actions.length&&!won())confirm('目前棋局尚未完成，繼續會清除這一局的步驟紀錄。完成紀錄仍會保留。',()=>start(i));else start(i);}
function assist(play){if(won()||playing)return;const seq=E.solve(level(),state());if(!seq||!seq.length){message='目前局面無法求解，請重新開始本局';render();return;}assisted=true;hintCell=seq[0];message=`提示：點 ${coord(seq[0])}。目前還有 ${seq.length} 步可熄滅所有燈`;save();if(!play){render();return;}playing=true;const token=++operation;let p=0;function tick(){if(token!==operation||!playing)return;if(p>=seq.length){stop();render();return;}focusCell=seq[p];perform(seq[p++]);if(playing){message='解答播放中，可隨時停止並接手';render();playTimer=setTimeout(tick,600);}}render();playTimer=setTimeout(tick,500);}
$('level').addEventListener('change',e=>{const n=Number(e.target.value);e.target.value=index;if(Number.isInteger(n)&&n>=0&&n<levels.length)requestStart(n);});$('restart').addEventListener('click',()=>{if(actions.length||seconds>0)confirm('重來會清除本局步驟與時間。完成紀錄仍會保留。',()=>start(index));else start(index);});$('next').addEventListener('click',()=>{if(index<49)requestStart(index+1);});$('undo').addEventListener('click',()=>{if(!actions.length||playing)return;stop();actions.pop();states.pop();hintCell=null;message='已復原上一個點擊';save();render();});$('hint').addEventListener('click',()=>assist(false));$('solution').addEventListener('click',()=>assist(true));$('stop').addEventListener('click',()=>{stop(true);render();});$('help').addEventListener('click',()=>{stop();render();$('helpDialog').showModal();});$('closeHelp').addEventListener('click',()=>$('helpDialog').close());$('cancelConfirm').addEventListener('click',()=>{confirmAction=null;$('confirmDialog').close();});$('acceptConfirm').addEventListener('click',()=>{const fn=confirmAction;confirmAction=null;$('confirmDialog').close();if(fn)fn();});$('confirmDialog').addEventListener('cancel',()=>{confirmAction=null;});
$('board').addEventListener('keydown',e=>{const i=Number(e.target.dataset.cell);if(!Number.isInteger(i)||i<0||i>=level().size**2)return;const d={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]}[e.key];if(!d)return;e.preventDefault();const x=i%level().size+d[0],y=Math.floor(i/level().size)+d[1];if(x>=0&&x<level().size&&y>=0&&y<level().size)$('board').querySelector(`[data-cell="${y*level().size+x}"]`).focus();});
let recovered=false;try{const raw=localStorage.getItem(KEY);if(raw){const v=S.restore(JSON.parse(raw),levels,E);({index,actions,states,seconds,assisted,progress}=v);recovered=true;}}catch(_){message='無法讀取有效存檔，已安全建立新棋局';}if(!recovered)states=[E.initial(level())];options();mount();if(recovered)message=won()?'已還原完成棋局':'已還原並驗證上次進度';render();save();setInterval(()=>{if(!document.hidden&&!won()&&!$('helpDialog').open&&!$('confirmDialog').open){seconds++;$('timer').textContent=time(seconds);if(seconds%5===0)save();}},1000);document.addEventListener('visibilitychange',()=>{if(document.hidden){stop();save();render();}});window.addEventListener('pagehide',()=>{stop();save();});
})();
