(function(root,factory){const common=typeof module==='object'&&module.exports;const api=factory(common?require('./engine.js'):root.Story120,common?require('./session.js'):root.StorySession);if(common)module.exports=api;else {root.StoryUI=api;api.boot();}})(typeof globalThis!=='undefined'?globalThis:this,function(E,Session){
'use strict';
const esc=x=>String(x===undefined?'尚未決定':x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function journalText(s,entry){if(s.id!=='last-council'||!['河谷農會','工匠公會','邊境守軍'].includes(entry.speaker))return entry.text;return entry.text.replace(/^(願意配合。|暫不配合。)(已公開依據 \d+)、已履行 ([01])、衝突 /,(_,reply,evidence,pledged)=>reply+evidence+'、投票時已承諾 '+pledged+(pledged==='1'?'（尚未兌現）':'')+'、衝突 ');}
function render(session){const s=session.state,v=E.scene(s),goal=E.goalStatus(s),count=Object.keys(session.records).length,detail={easy:'寬鬆：願考慮急迫性，接受較少佐證',normal:'一般：要求可核對理由與可信履行',hard:'審慎：提高佐證門檻，承諾衝突加倍計入'};return `
<section class="controls" aria-label="故事設定"><label>情境<select id="level" data-control="level" aria-label="選擇情境">${session.levels.map(l=>`<option value="${l.id}" ${l.id===s.levelId?'selected':''}>${esc(l.title)}</option>`).join('')}</select></label><label>玩法<select id="mode" data-control="mode" aria-label="選擇玩法"><option value="challenge" ${s.mode==='challenge'?'selected':''}>目標情境 · 一般角色</option><option value="free" ${s.mode==='free'?'selected':''}>自由故事 · 可調角色</option></select></label><label>角色判斷<select id="difficulty" data-control="difficulty" aria-label="角色判斷難度" ${s.mode==='challenge'?'disabled':''}>${E.DIFFICULTIES.map((d,i)=>`<option value="${d}" ${s.difficulty===d?'selected':''}>${['寬鬆','一般','審慎'][i]}</option>`).join('')}</select></label></section>
<p class="scope">${s.mode==='challenge'?'100 個目標情境只認證一般角色規則；難度固定。其他結局也可以成立，不代表道德上的錯誤。':'自由故事不計入目標完成紀錄，可自由調整角色判斷。'} ${detail[s.difficulty]}。</p>
<section class="statusbar"><span>第 ${s.levelId}／100 個情境</span><span>獨立完成 ${count}／100</span><span class="provenance">${s.assisted?'本次使用輔助':s.mode==='free'?'自由故事':'本次獨立選擇'}</span></section>
<div class="layout"><article class="story"><p class="eyebrow">${s.done?'EPILOGUE · 尾聲':'A CHOICE LEAVES A TRACE'}</p><h2 id="scene-title" tabindex="-1">${esc(v.title)}</h2><p class="scene-text">${esc(v.text)}</p>
${s.done?`<p class="ending ${E.won(s)?'matched':''}" role="status">${s.mode==='free'?'自由故事已結束':E.won(s)?(s.assisted?'示範／輔助到達目標；未計獨立完成':'已到達本局目標'):'這是一個不同於本局目標的結局'}。</p>`:''}
<div class="choices" aria-label="目前可作的選擇">${E.choices(s).map((c,i)=>`<button type="button" class="choice" data-action="${esc(c.id)}" ${c.enabled?'':'disabled'}><span class="choice-no">${i+1}</span><span><strong>${esc(c.label)}</strong><small>${esc(c.detail)}</small>${c.enabled?'':'<em>先前條件尚未成立，這句話／行動目前不可用。</em>'}</span></button>`).join('')}</div>
${s.done?'<button type="button" class="primary" data-do="reset">再走另一條路</button>':''}
<div class="toolbar"><button type="button" data-do="reset">重新開始</button><button type="button" data-do="hint">目前分支提示</button><button type="button" data-do="demo">觀看完整示範</button><button type="button" data-do="help" aria-expanded="${session.showHelp}">玩法與角色規則</button></div>
${session.hintText?`<aside class="hint" role="status"><strong>分支提示</strong><p>${esc(session.hintText)}</p></aside>`:''}
<p class="notice" role="status" aria-live="polite">${esc(session.notice)}</p>
${session.showHelp?`<section class="help"><h3>怎麼玩</h3><ol><li>先讀這局希望看見的結局與條件，再看篇章關係。</li><li>用按鈕作決定。灰色選項表示先前的事件或資源尚未讓它成立。</li><li>每次選擇後查看故事回聲與人物／事件表；先前的選擇會改變後來能做的事。</li><li>目標不是唯一正確答案。你也能走完另一種結局，或在自由故事試驗不同角色判斷。</li></ol><h3>公開的角色決策</h3><p>這是本機規則式角色，不是自由聊天 AI。角色只接收當刻已公開的佐證、履約、衝突與急迫性。寬鬆門檻為 1，會計入急迫性；一般門檻為 2；審慎門檻為 3，衝突權重為 2。回應會解釋使用哪些公開條件。</p><p>使用提示或示範會標記這一次嘗試；既有獨立紀錄不會被覆蓋。重新開始、換情境或換玩法會結束目前嘗試。故事從合法選擇紀錄自動儲存；可用滑鼠、觸控或 Tab／Enter 操作。</p></section>`:''}
</article><aside class="sidebar"><section class="goals"><p class="eyebrow">DIRECTOR'S BRIEF</p><h2>${s.mode==='free'?'可參考的情境目標':'本局希望抵達的結果'}</h2><p>${esc(session.level().premise)}</p><ul>${goal.map(g=>`<li><strong>${esc(g.label)}：${esc(g.expected)}</strong>${s.done?`<span>${g.met?'符合':'實際為'} ${g.met?'此條件':esc(g.actual)}</span>`:''}</li>`).join('')}</ul></section>
<details class="rules"><summary>篇章關係與本局條件</summary><ul>${E.rules(s).map(t=>'<li>'+esc(t)+'</li>').join('')}</ul></details>
<section class="relations"><h3>人物與事件</h3><div class="table-scroll" role="region" aria-label="可橫向捲動的人物與事件表" tabindex="0"><table><tbody>${v.rows.map(r=>'<tr>'+r.map((x,i)=>`<${i?'td':'th'} ${i?'':'scope="row"'}>${esc(x)}</${i?'td':'th'}>`).join('')+'</tr>').join('')}</tbody></table></div></section>
<section class="journal"><h3>故事回聲 <span>${s.log.length} 則</span></h3><div class="log" role="log" aria-live="polite" aria-relevant="additions" tabindex="0">${s.log.slice(-6).map(r=>`<p><b>${esc(r.speaker)}</b>${esc(journalText(s,r))}</p>`).join('')}</div><details><summary>翻閱完整故事紀錄</summary><ol class="all-log">${s.log.map(r=>`<li><strong>${esc(r.speaker)}：</strong>${esc(journalText(s,r))}</li>`).join('')}</ol></details></section></aside></div>`;}
function mount(node,session){function draw(){node.innerHTML=render(session);}function act(type,value){try{session.dispatch(type,value);draw();}catch(e){session.notice='這次操作沒有生效：'+e.message;draw();}}node.addEventListener('click',event=>{const b=event.target.closest('button');if(!b||!node.contains(b)||b.disabled)return;if(b.dataset.action)act('choice',b.dataset.action);else if(b.dataset.do)act(b.dataset.do);});node.addEventListener('change',event=>{const t=event.target;if(t.dataset.control&&!t.disabled)act(t.dataset.control,t.value);});draw();return {session,draw,act};}
async function boot(){const id=document.body.dataset.game,node=document.getElementById('app');try{const files=await Promise.all(['levels.json','proofs.json'].map(p=>fetch('./'+id+'/'+p).then(r=>{if(!r.ok)throw Error('無法讀取情境檔案');return r.json();})));let storage;try{storage=window.localStorage;}catch(e){}const session=Session.create(id,files[0],files[1],storage);mount(node,session);}catch(e){node.textContent='情境暫時未能載入。請重新整理，或返回大廳後再試。';}}
return {render,mount,boot};
});
