'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{Session}=require('./session.js'),{ids,sha}=require('./corpus.cjs');
const memory=()=>{let data=new Map();return{getItem:k=>data.get(k)||null,setItem:(k,v)=>data.set(k,v),data}};
function setup(id,storage=memory()){let game=require('../'+id+'/engine.js'),levels=require('../'+id+'/levels.json'),certificates=require('../'+id+'/certificates.json');return new Session(game,levels,certificates,storage)}
function trace(session){let c=session.certificates[session.levelIndex],at=0,input={};return()=>{while(at<c.inputs.length&&c.inputs[at][0]<=session.state.tick+1)input=c.inputs[at++][1];return input}}
for(let id of ids){test(id+': manual win, isolated demo, restored in-progress save and assistance',()=>{let s=setup(id);s.choose(49);s.start();let read=trace(s);for(let k=0;k<30;k++)s.tick(read());let manual=sha(s.state),stored=s.storage;s.save();let restored=setup(id,stored);assert.equal(sha(restored.state),manual);assert.ok(restored.paused);s.beginDemo();let duringDemo=setup(id,stored);assert.ok(duringDemo.assisted);assert.equal(sha(duringDemo.state),manual);while(s.state.status==='playing')s.tick({});assert.equal(s.state.status,'won');assert.equal(s.completed.size,0);s.endDemo();assert.equal(sha(s.state),manual);assert.equal(s.completed.size,0);s.start();while(s.state.status==='playing')s.tick(read());assert.equal(s.state.status,'won');assert.equal(s.completed.size,0);assert.ok(s.assisted);s.reset();s.start();read=trace(s);while(s.state.status==='playing')s.tick(read());assert.equal(s.completed.size,1);s.beginDemo();s.endDemo();assert.equal(s.completed.size,1);s.choose(0);s.hint();s.start();read=trace(s);while(s.state.status==='playing')s.tick(read());assert.equal(s.completed.has(0),false);s.reset();assert.equal(s.assisted,false)});
 test(id+': frame schedules replay identical, including 120Hz and 30Hz',()=>{let hashes=[];for(let hz of [30,60,120]){let s=setup(id,null);s.beginDemo();let t=0;s.advance(t,()=>({}));while(!s.paused){t+=1000/hz;s.advance(t,()=>({}))}hashes.push(sha(s.state));assert.equal(s.completed.size,0)}assert.equal(new Set(hashes).size,1)});
}
test('interruption, stale time, bounded catchup, reset/navigation and unavailable storage',()=>{let s=setup('snake',null);s.start();s.advance(0,()=>({}));s.advance(10000,()=>({}));assert.equal(s.state.tick,6);s.pause();s.advance(50000,()=>({}));assert.equal(s.state.tick,6);s.start();s.advance(90000,()=>({}));assert.equal(s.state.tick,6);s.beginDemo();s.choose(99);assert.equal(s.demo,false);assert.equal(s.state.tick,0);assert.ok(s.paused);assert.equal(s.choose(100),false);assert.equal(s.levelIndex,99);let broken={getItem(){throw Error('denied')},setItem(){throw Error('full')}};s=setup('snake',broken);assert.ok(s.warning);s.start();s.tick({dir:'right'});s.save();assert.ok(s.warning.includes('無法儲存'))});
test('corrupt save safely resets; terminal state rejects play and invalid index',()=>{let storage=memory();let s=setup('breakout',storage);storage.setItem(s.key,JSON.stringify({version:1,revision:'action-1',levelIndex:0,completed:[5000],state:{}}));let restored=setup('breakout',storage);assert.equal(restored.levelIndex,0);assert.equal(restored.state.tick,0);assert.equal(restored.completed.size,0);assert.ok(restored.warning);s.state.status='lost';assert.equal(s.start(),false);assert.equal(s.tick({}),false);assert.equal(s.choose(NaN),false)});
