'use strict';
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),test=require('node:test'),assert=require('node:assert/strict'),{ids}=require('./corpus.cjs');
function boot(id){let drawCalls=0,focus=null;
class Element{constructor(tag='div',id=''){this.tagName=tag.toUpperCase();this.id=id;this.dataset={};this.children=[];this.listeners={};this.attributes={};this.value='';this.textContent='';this.hidden=false;this.disabled=false}appendChild(e){this.children.push(e);return e}setAttribute(k,v){this.attributes[k]=v}addEventListener(k,fn){(this.listeners[k]||=[]).push(fn)}dispatch(type,props={}){let e={type,target:this,preventDefault(){this.defaultPrevented=true},pointerId:1,clientX:240,clientY:300,...props};for(let fn of this.listeners[type]||[])fn(e);return e}focus(){focus=this}setPointerCapture(){}getBoundingClientRect(){return{left:0,top:0,width:480,height:600}}getContext(){return new Proxy({},{get(t,k){if(['fillStyle','strokeStyle','font','textAlign','lineWidth','lineCap'].includes(k))return t[k];return(...args)=>{for(let a of args)if(typeof a==='number')assert.ok(Number.isFinite(a),k+' received nonfinite coordinate');drawCalls++}},set(t,k,v){t[k]=v;return true}})}}
let html=fs.readFileSync(path.join(__dirname,'..',id+'.html'),'utf8'),els={};for(let match of html.matchAll(/<([a-z]+)[^>]*\bid="([^"]+)"/g))els[match[2]]=new Element(match[1],match[2]);let document=new Element('document');document.body=new Element('body');document.body.dataset.game=id;document.getElementById=id=>els[id];document.createElement=tag=>new Element(tag);document.querySelectorAll=sel=>sel==='[data-control]'?els.controls.children:[];document.hidden=false;let win=new Element('window'),frames=new Map(),serial=0,store=new Map(),context={document,localStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v)},console,requestAnimationFrame:fn=>{let id=++serial;frames.set(id,fn);return id},cancelAnimationFrame:id=>frames.delete(id)};context.window=win;vm.createContext(context);for(let src of [...html.matchAll(/<script src="([^"]+)"/g)].map(m=>m[1]))vm.runInContext(fs.readFileSync(path.join(__dirname,'..',src),'utf8'),context,{filename:src});
return{context,els,document,win,frames,store,get drawCalls(){return drawCalls},get focus(){return focus},frame(t){let now=[...frames.entries()];frames.clear();for(let [,fn]of now)fn(t)},key(code,down=true){document.dispatch(down?'keydown':'keyup',{code,key:code==='Space'?' ':code,target:focus||els.board,repeat:false})}}}
for(let id of ids)test(id+': actual HTML scripts, canvas draw, navigation, input, pause and demo isolation in simulated DOM',()=>{let b=boot(id),{els,context}=b,s=context.ActionApp.session;assert.equal(els.level.children.length,100);b.frame(0);assert.ok(b.drawCalls>0);assert.equal(b.frames.size,1);els.start.dispatch('click');assert.equal(b.focus,els.board);b.frame(1);b.key('ArrowRight');b.frame(51);assert.ok(s.state.tick>0);b.key('ArrowRight',false);let tick=s.state.tick;b.win.dispatch('blur');b.frame(30000);assert.equal(s.state.tick,tick);assert.ok(s.paused);els.level.value='99';els.level.dispatch('change');assert.equal(s.levelIndex,99);assert.equal(s.state.tick,0);els.demo.dispatch('click');b.frame(30001);b.frame(30101);assert.equal(s.demo,true);assert.ok(s.state.tick>0);els.demo.dispatch('click');assert.equal(s.demo,false);assert.equal(s.state.tick,0);assert.equal(s.completed.size,0);assert.ok(s.assisted);els.hintButton;els['hint-button'].dispatch('click');assert.ok(s.assisted);els.reset.dispatch('click');assert.equal(s.assisted,false);assert.equal(s.state.tick,0);els.prev.dispatch('click');assert.equal(s.levelIndex,98);for(let n=0;n<20;n++){els.next.dispatch('click');els.prev.dispatch('click')}assert.equal(b.frames.size,1);assert.equal(b.document.listeners.keydown.length,1);assert.equal(b.document.listeners.visibilitychange.length,1);b.document.hidden=true;b.document.dispatch('visibilitychange');assert.ok(s.paused);b.win.dispatch('pagehide');assert.equal(b.frames.size,0);b.win.dispatch('pageshow');assert.equal(b.frames.size,1)});
test('game-specific actual pointer and key handlers deliver proper controls',()=>{let b=boot('snake');b.els.start.dispatch('click');b.key('ArrowDown');assert.equal(b.context.ActionApp.input().dir,'down');b=boot('rhythm-drums');b.els.start.dispatch('click');b.key('KeyD');b.key('KeyK');assert.deepEqual(Array.from(b.context.ActionApp.input().lanes),[0,3]);b.key('KeyD',false);assert.deepEqual(Array.from(b.context.ActionApp.input().lanes),[3]);b=boot('whack-a-mole');b.els.board.dispatch('pointerdown',{clientX:240,clientY:310});assert.equal(b.context.ActionApp.input().hit,4);b.key('Digit9');assert.equal(b.context.ActionApp.input().hit,8);b=boot('fruit-slice');b.els.board.dispatch('pointerdown',{clientX:200,clientY:400});b.els.board.dispatch('pointermove',{clientX:250,clientY:390});let a=b.context.ActionApp.input();assert.equal(a.x,250);assert.equal(a.stroke,true);b.els.board.dispatch('pointerup');assert.ok(!b.context.ActionApp.input().stroke);b=boot('bubble-shooter');b.els.board.dispatch('pointerdown',{clientX:240,clientY:100});a=b.context.ActionApp.input();assert.ok(a.fire);assert.equal(a.aim,-Math.PI/2);assert.ok(!b.context.ActionApp.input().fire);b.key('ArrowRight');a=b.context.ActionApp.input();assert.ok(a.right);assert.equal(a.aim,undefined)});
module.exports={boot};

test('actual pointer cancellation and release stop space-dodge movement commands',()=>{for(let type of ['pointerup','pointercancel','lostpointercapture']){let b=boot('space-dodge');b.els.start.dispatch('click');b.els.board.dispatch('pointerdown',{clientX:430,clientY:350});let a=b.context.ActionApp.input();assert.equal(a.x,430);assert.equal(a.y,350);b.els.board.dispatch(type);a=b.context.ActionApp.input();assert.equal(a.x,undefined);assert.equal(a.y,undefined);let s=b.context.ActionApp.session,x=s.state.x,y=s.state.y;s.tick(a);assert.equal(s.state.x,x);assert.equal(s.state.y,y)}});

test('fruit actual DOM: pointerdown alone never slices and non-cutting hover positioning works',()=>{let b=boot('fruit-slice'),s=b.context.ActionApp.session;b.els.start.dispatch('click');while(s.state.tick<s.level.objects[0].at+39)s.tick(b.context.ActionApp.input());let fruit=s.state.objects.find(q=>q.active&&!q.bomb&&!q.cut);b.els.board.dispatch('pointerdown',{clientX:fruit.x,clientY:fruit.y});for(let k=0;k<15;k++)s.tick(b.context.ActionApp.input());assert.equal(s.state.score,0);b.els.board.dispatch('pointerup');b.els.board.dispatch('pointermove',{clientX:180,clientY:350});let a=b.context.ActionApp.input();assert.equal(a.x,180);assert.equal(a.y,350);assert.ok(!a.stroke)});
