(function(root){'use strict';const E=root.RogueEngine,sp=E.Specs.byId(document.body.dataset.game),$=id=>document.getElementById(id),key='frontier120-rogue:'+sp.id;let s=E.start(sp.id),paused=false,assisted=false,demo=false,mode='challenge',actionMode='move',token=0,timer=null,selectedPack=0,selectedStar=null,memorySlot=0,progress=[],toastTimer;const colors=['#c78f9b','#9fc3e5','#d9c591'];
function storageGet(k){try{return localStorage.getItem(k);}catch(e){return null;}}function storageSet(k,v){try{localStorage.setItem(k,v);return true;}catch(e){$('saveNote').textContent='瀏覽器目前無法寫入存檔。遊戲仍可玩，離開前請留意進度不會保存。';return false;}}
function toast(text){$('toast').textContent=text;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,2500);}
function stopDemo(){token++;if(timer!==null)clearTimeout(timer);timer=null;demo=false;$('demo').textContent='觀看示範';}
function persist(){storageSet(key,JSON.stringify({...E.save(s,assisted,demo),mode,paused}));}
function load(){try{let p=JSON.parse(storageGet(key+':progress')||'[]');if(Array.isArray(p)&&p.length<=100&&p.every(n=>Number.isInteger(n)&&n>=1&&n<=100))progress=[...new Set(p)];let data=JSON.parse(storageGet(key)||'null'),r=E.restore(data);if(r&&r.state.game===sp.id){s=r.state;memorySlot=s.build.slot;assisted=r.assisted||r.demo;mode=data.mode==='free'?'free':'challenge';if(mode==='challenge'&&s.difficulty!=='normal'){s=E.start(sp.id,s.level.id);assisted=false;}paused=true;$('saveNote').textContent='已重播合法操作，還原上次遠征並保持暫停。按「繼續」後可接著玩。';}else if(data)$('saveNote').textContent='舊存檔格式不符或內容損壞，已安全開啟新遠征。';}catch(e){$('saveNote').textContent='無法讀取舊存檔，已安全開啟新遠征。';}}
function newGame(n=s.level.id){stopDemo();s=E.start(sp.id,n,mode==='challenge'?'normal':$('difficulty').value);assisted=false;paused=false;selectedPack=0;selectedStar=null;memorySlot=0;persist();render();}
function play(a,fromDemo=false){if(paused&&!fromDemo){toast('目前暫停，按「繼續」後再操作。');return false;}if(demo&&!fromDemo)stopDemo();let r=E.apply(s,a);if(!r.legal){toast(a.type==='descend'?'必須完成構築、清除所有敵人，再到出口下樓。':'這一步目前無法執行。請查看位置、魔力或構築條件。');return false;}s=r.state;if(s.kind==='memory'&&a.type==='build')memorySlot=s.build.slot;if(s.status==='won'&&mode==='challenge'&&!assisted&&!fromDemo&&!progress.includes(s.level.id)){progress.push(s.level.id);progress.sort((a,b)=>a-b);storageSet(key+':progress',JSON.stringify(progress));}persist();render();return true;}
function button(text,fn,cls=''){const b=document.createElement('button');b.type='button';b.textContent=text;if(cls)b.className=cls;b.onclick=fn;return b;}
function tag(text){const t=document.createElement('span');t.className='tag';t.textContent=text;return t;}
function buildPanel(){const b=s.build,k=s.kind,box=$('buildDetail'),extras=$('extraControls'),visual=$('buildVisual');box.textContent='';extras.replaceChildren();visual.replaceChildren();let info='';
if(k==='wand')info='枝節：'+(b.branches.map(n=>['穿透','反彈','分裂'][n]).join(' → ')||'尚未萌芽')+'｜近擊 '+b.styles[0]+'、施法 '+b.styles[1]+'、防守 '+b.styles[2];
if(k==='pack'){const p=E.packPower(s);info='近擊加成 +'+p.attack+'｜盾加成 +'+p.shield+'｜相鄰共鳴 '+p.links;let inv=document.createElement('div');inv.className='tags';for(const it of b.pack)inv.append(button(['橫刃','直盾','電池'][it.type]+' #'+it.id,()=>{selectedPack=it.id;render();},selectedPack===it.id?'active':''));visual.append(inv);let grid=document.createElement('div');grid.className='pack';for(let y=0;y<4;y++)for(let x=0;x<4;x++){let it=b.pack.find(it=>E.packCells(it).some(c=>c[0]===x&&c[1]===y)),cell=button(it?['刃','盾','電'][it.type]:'·',()=>{if(selectedPack)play({type:'pack',id:selectedPack,x,y});else if(it){selectedPack=it.id;render();}});cell.setAttribute('aria-label','背包 '+(y+1)+' 列 '+(x+1)+' 格'+(it?'，'+['刃','盾','電池'][it.type]:'空格'));if(it)cell.style.background=colors[it.type]+'40';grid.append(cell);}visual.append(grid);extras.append(button('旋轉選中裝備',()=>play({type:'rotate',id:selectedPack})));}
if(k==='weapon')info='目前武器：'+['長槍 · 2 格','弓 · 5 格','巨斧 · 周圍'][b.weapon]+'｜繼承：'+['突刺','散射','橫掃'][b.inherited];
if(k==='vitality')info='抵押生命 '+b.debt+'｜鋒刃 '+b.perks[0]+' / 屏障 '+b.perks[1]+' / 汲取 '+b.perks[2];
if(k==='echo')info='殘影 '+b.echoes.filter(g=>g.hp>0).length+' / 3｜本層錄影 '+s.floorHistory.length+' 步｜已倒帶 '+s.rewinds+' 次';
if(k==='parts'){info='負重 '+b.parts.reduce((sum,p)=>sum+[2,3,1][p],0)+' / 6｜庫存零件 '+b.scraps+'｜'+b.parts.map(p=>['翼','殼','觸角'][p]).join('＋');for(let c=0;c<3;c++)extras.append(button('拼裝'+['翅膀','甲殼','觸角'][c],()=>play({type:'assemble',choice:c})));}
if(k==='potion'){info='配方：'+sp.choices[b.recipe]+'｜每次使用消耗 3 魔力';extras.append(button('喝下藥水',()=>play({type:'skill',mode:'drink',dir:s.p.face})),button('塗在地面',()=>play({type:'skill',mode:'coat',dir:s.p.face})));}
if(k==='curse')info='禁忌：'+(b.curse<0?'未簽約':sp.choices[b.curse])+'｜連續守約 '+b.kept+'｜破戒 '+b.broken+' 次';
if(k==='astro'){info='每回合指針前進一格。點兩格可交換，耗一回合。';let ring=document.createElement('div');ring.className='star-ring';for(let i=0;i<4;i++)ring.append(button((b.pointer===i?'▼ ':'')+['焰','盾','療'][b.stars[i]],()=>{if(selectedStar===null){selectedStar=i;render();}else{let a=selectedStar;selectedStar=null;play({type:'swap',a,b:i});}},(b.pointer===i?'pointer ':'')+(selectedStar===i?'active':'')));visual.append(ring);}
if(k==='terrain'){info='胃袋：'+(b.stomach.map(v=>['岩','冰','熔岩'][v]).join(' → ')||'空，先吞噬地形');extras.append(button('吞噬面向地形',()=>play({type:'eat',dir:s.p.face})));}
if(k==='boss'){info='借招：'+sp.choices[b.borrowed]+'｜充能 '+b.charge+' / 6｜擊破首領後到出口借一招';if(s.enemies.length===0)for(let c=0;c<3;c++)extras.append(button('借走'+sp.choices[c],()=>play({type:'borrow',choice:c})));}
if(k==='memory'){info='由左至右是拾取順序。第四招會移除左邊最舊招。';for(let i=0;i<b.memory.length;i++)extras.append(button((i+1)+'. '+['烈焰','冰環','汲取'][b.memory[i]],()=>{memorySlot=i;render();},memorySlot===i?'active':''));}
if(k==='wound'){info='裂槽 '+b.wounds+' / 4｜符文：'+(b.runes.map(n=>['穿甲','反擊'][n]).join('＋')||'尚未鑲嵌');extras.append(button('修復一條裂槽',()=>play({type:'repair'})));}
if(k==='heart')info='心臟：'+['疾速','緩拍','均衡'][b.heart]+'｜時鐘 '+b.clock+'｜已解鎖 '+b.hearts.map(n=>['疾','緩','衡'][n]).join(' / ');
if(k==='dual')info='目前：'+['光界','影界'][s.p.world]+'｜界印 '+b.marks.map(v=>v?'◆':'◇').join(' ')+'｜兩界共用生命、劍印與護符';
box.textContent=info;$('buildChoices').replaceChildren();sp.choices.forEach((label,c)=>{let el=button((c+1)+'. '+label,()=>play({type:'build',choice:c}));el.disabled=s.chosen||s.status!=='playing'||s.kind==='weapon'&&s.floor>0&&c!==s.build.previousWeapon&&c!==s.build.inherited;$('buildChoices').append(el);});$('workshopNote').textContent=s.chosen?'本層構築已完成，下一層可再選一次。':'移到 ✦ 工坊旁邊，選擇一項本層構築。';}
function render(){document.documentElement.style.setProperty('--accent',sp.color);$('level').value=s.level.id;$('mode').value=mode;$('difficulty').value=s.difficulty;$('difficulty').disabled=mode==='challenge';$('difficultyLabel').title=mode==='challenge'?'100 關證明採用標準 AI。自由遠征可更換難度。':'';$('pause').textContent=paused?'繼續遠征':'暫停';$('health').textContent=s.p.hp+' / '+s.p.maxhp;$('energy').textContent=s.p.energy+' / 10';$('floor').textContent=(s.floor+1)+' / 3';$('enemyCount').textContent=s.enemies.length;$('mapText').textContent='你的位置：第 '+(s.p.y+1)+' 列、第 '+(s.p.x+1)+' 格。'+s.enemies.filter(e=>e.world===s.p.world).map(e=>({scout:'斥候',brute:'重兵',archer:'弓手',boss:'首領',hunter:'追獵者'}[e.type])+'：第 '+(e.y+1)+' 列 '+(e.x+1)+' 格，生命 '+e.hp+(e.windup?'，鎖定第 '+(e.ty+1)+' 列 '+(e.tx+1)+' 格':'')).join('；');$('turn').textContent='第 '+s.turn+' 回合 · '+['↑ 北','→ 東','↓ 南','← 西'][s.p.face]+' · 護盾 '+s.p.shield;$('status').textContent=paused?'遠征已暫停。':s.log[0];$('status').className='status '+(s.status==='won'?'win':s.status==='lost'?'lost':'');$('assist').textContent=mode==='free'?'自由遠征，不計挑戰進度':assisted?'已使用提示／示範：本次計為協助通關':'手動遠征 · 未使用協助';$('assist').className='assist '+(!assisted&&mode==='challenge'?'manual':'');$('progress').textContent='手動完成 '+progress.length+' / 100';$('skill').textContent=sp.skill+' [空白]';$('log').replaceChildren(...s.log.slice(1,5).map(t=>{let li=document.createElement('li');li.textContent=t;return li;}));document.querySelectorAll('[data-action-mode]').forEach(el=>el.classList.toggle('active',el.dataset.actionMode===actionMode));$('actionLabel').textContent='方向按鈕目前：'+({move:'移動',attack:'近擊',skill:sp.skill,eat:'吞噬地形'}[actionMode]);buildPanel();root.RogueRender.draw($('board'),s,sp);document.querySelectorAll('[data-level]').forEach(el=>{el.classList.toggle('done',progress.includes(Number(el.dataset.level)));el.classList.toggle('active',Number(el.dataset.level)===s.level.id);});}
function direction(dir){play(actionMode==='skill'?{type:'skill',dir,slot:memorySlot}:{type:actionMode,dir});}
function hint(){assisted=true;persist();$('hintBox').hidden=false;$('hintText').textContent=!s.chosen?'先走到起點旁的 ✦ 工坊，從三種構築選一種。看到敵人鎖定的紅框後，移出紅框可躲過下一擊。':s.enemies.length?'紅框是敵人已鎖定的落點。注意牆壁阻擋直線法術；可以移動誘敵、先蓄護盾，再利用'+sp.skill+'。'+sp.rules:'走到右下角 ⇩ 出口，使用「下樓／離開」。'+(s.kind==='dual'?'先確認光影兩界的界印皆已取得。':'');render();}
function startDemo(){if(demo){stopDemo();persist();render();return;}stopDemo();mode='challenge';s=E.start(sp.id,s.level.id,'normal');paused=false;assisted=true;demo=true;const proof=(root.RogueProofs||[]).find(p=>p.id===s.level.id);if(!proof){demo=false;toast('本關示範資料尚未載入。');return;}let at=0,my=token;$('demo').textContent='停止示範';persist();render();function tick(){if(my!==token||!demo||paused)return;if(at>=proof.actions.length){stopDemo();persist();render();return;}if(!play(proof.actions[at++],true)){stopDemo();toast('示範資料不符，已停止。');return;}timer=setTimeout(tick,document.hidden?500:170);}timer=setTimeout(tick,300);}
function setup(){document.title=sp.title+'｜遊戲小宇宙';$('title').textContent=sp.title;$('subtitle').textContent=sp.description;$('eyebrow').textContent=sp.word+' · TACTICAL ROGUELIKE';$('art').src='./'+sp.id+'/art.svg';$('art').alt=sp.title+'主題插畫';$('specificRules').textContent=sp.rules;for(let n=1;n<=100;n++){let o=document.createElement('option');o.value=n;o.textContent=String(n).padStart(3,'0')+' · '+E.level(sp.id,n).title.split(' ')[0];$('level').append(o);let b=button(String(n),()=>newGame(n));b.dataset.level=n;b.setAttribute('aria-label','第 '+n+' 關');$('levelMap').append(b);}load();$('level').onchange=()=>newGame(Number($('level').value));$('mode').onchange=()=>{mode=$('mode').value;newGame();};$('difficulty').onchange=()=>newGame();$('restart').onclick=()=>newGame();$('next').onclick=()=>newGame(s.level.id%100+1);$('random').onclick=()=>{mode='free';newGame(1+Math.floor(Math.random()*100));};$('pause').onclick=()=>{stopDemo();paused=!paused;persist();render();};$('hint').onclick=hint;$('closeHint').onclick=()=>{$('hintBox').hidden=true;};$('demo').onclick=startDemo;$('save').onclick=()=>{if(storageSet(key,JSON.stringify({...E.save(s,assisted,demo),mode,paused})))toast('已儲存本次操作與協助標記。');};$('skill').onclick=()=>play({type:'skill',dir:s.p.face,slot:memorySlot});$('interact').onclick=()=>play({type:'interact'});$('descend').onclick=()=>play({type:'descend'});$('guard').onclick=()=>play({type:'guard'});$('attack').onclick=()=>play({type:'attack',dir:s.p.face});document.querySelectorAll('[data-dir]').forEach(el=>el.onclick=()=>direction(Number(el.dataset.dir)));document.querySelectorAll('[data-action-mode]').forEach(el=>el.onclick=()=>{actionMode=el.dataset.actionMode;render();});$('board').onclick=ev=>{let r=$('board').getBoundingClientRect(),x=Math.floor((ev.clientX-r.left)/r.width*9),y=Math.floor((ev.clientY-r.top)/r.height*9),dx=x-s.p.x,dy=y-s.p.y;if(!dx&&!dy){play({type:'interact'});return;}let dir=Math.abs(dx)>Math.abs(dy)?(dx>0?1:3):(dy>0?2:0);direction(dir);};
document.addEventListener('keydown',ev=>{if(ev.target.tagName==='BUTTON'&&[' ','Enter'].includes(ev.key))return;if(ev.repeat||ev.altKey||ev.metaKey||['INPUT','SELECT','TEXTAREA'].includes(ev.target.tagName))return;let key=ev.key.toLowerCase(),dirs={arrowup:0,w:0,arrowright:1,d:1,arrowdown:2,s:2,arrowleft:3,a:3};if(key in dirs){ev.preventDefault();let dir=dirs[key];play({type:ev.ctrlKey?'skill':ev.shiftKey?'attack':'move',dir,slot:memorySlot});return;}if([' ','q','e','f','p','r','z'].includes(key)){ev.preventDefault();if(key===' ')play({type:'skill',dir:s.p.face,slot:memorySlot});if(key==='q')play({type:'guard'});if(key==='e')play({type:'interact'});if(key==='f')play({type:'descend'});if(key==='p')$('pause').click();if(key==='r')newGame();if(key==='z'&&s.kind==='terrain')play({type:'eat',dir:s.p.face});}});
document.addEventListener('visibilitychange',()=>{if(document.hidden){stopDemo();paused=true;persist();render();}});root.addEventListener('pagehide',()=>{stopDemo();persist();});render();}
root.RogueUI={getState:()=>E.save(s,assisted,demo),play,newGame,stopDemo,render,setup};setup();})(globalThis);
