(()=>{'use strict';const E=AkariEngine,levels=AKARI_LEVELS,$=id=>document.getElementById(id),key='logic-akari-v1';let index=0,states={},completed=new Set,focus=0,onConfirm=null,storageOk=true;
try{const d=JSON.parse(localStorage.getItem(key));if(d&&d.version===1&&Number.isInteger(d.current)&&d.current>=0&&d.current<50){index=d.current;let records=d.records&&typeof d.records==='object'&&!Array.isArray(d.records)?d.records:{};for(let i=0;i<50;i++){states[i]=E.state(levels[i],records[i]);if(E.inspect(levels[i],states[i].marks).won)completed.add(i)}}}catch(e){storageOk=false}
const p=()=>levels[index],s=()=>states[index]||(states[index]=E.state(p(),null));function save(){try{localStorage.setItem(key,JSON.stringify({version:1,current:index,records:states}))}catch(e){storageOk=false}}function say(t){$('message').textContent=t;$('message').className='message'}
function drawBoard(el,level,marks,interactive){let info=E.inspect(level,marks);el.innerHTML='';el.style.gridTemplateColumns=`repeat(${level.size},minmax(0,1fr))`;el.style.width=interactive?`min(100%, ${level.size*46}px)`:`${level.size*35}px`;let map=new Map(info.numbers.map(x=>[x.i,x]));for(let i=0;i<level.size*level.size;i++){let b=document.createElement(interactive?'button':'span'),white=E.white(level,i),n=map.get(i),r=Math.floor(i/level.size),c=i%level.size;b.className='cell '+(white?'white':'wall');b.setAttribute('role','gridcell');if(white){if(info.lit.has(i))b.classList.add('lit');if(marks[i]===1){b.textContent='☀';b.classList.add('bulb')}if(marks[i]===2){b.textContent='×';b.classList.add('mark')}if(info.bad.has(i))b.classList.add('conflict');b.setAttribute('aria-label',`第${r+1}列第${c+1}欄，${marks[i]===1?'燈泡':marks[i]===2?'不放燈標記':'空白'}，${info.lit.has(i)?'已照亮':'未照亮'}`);if(interactive){b.dataset.cell=i;b.tabIndex=i===focus?0:-1;b.onclick=ev=>act(i,ev.shiftKey);b.oncontextmenu=ev=>{ev.preventDefault();act(i,true)};b.onfocus=()=>{focus=i};b.onkeydown=ev=>boardKey(ev,i)}}else{b.textContent=n?n.target:'';b.setAttribute('aria-label',n?`黑格 ${n.target}，目前相鄰 ${n.count} 個燈泡`:'黑格');if(interactive)b.disabled=true;if(n&&n.count===n.target)b.classList.add('good');if(n&&n.count>n.target)b.classList.add('over')}el.append(b)}return info}
function render(){const info=drawBoard($('board'),p(),s().marks,true);if(info.won)completed.add(index);$('level').innerHTML='';levels.forEach((_,i)=>{let o=document.createElement('option');o.value=i;o.textContent=`第 ${String(i+1).padStart(2,'0')} 關${completed.has(i)?' ✓':''}`;$('level').append(o)});$('level').value=index;$('prev').disabled=index===0;$('next').disabled=index===49;$('variant').textContent=`${p().size} × ${p().size} · 唯一解`;$('litCount').textContent=`已照亮 ${info.lit.size} / ${info.total}`;$('undo').disabled=!s().history.length;$('progress').textContent=`已完成 ${completed.size} / 50 關${storageOk?'':' · 儲存空間不可用'}`;if(info.won){say('全部亮起來了！燈泡與數字都正確 🎉');$('message').classList.add('win')}else if(info.bad.size)say('紅色燈泡互相看見了，試著移走其中一個。');else if(info.numbers.some(x=>x.count>x.target))say('有數字黑格周圍的燈泡過多了。');save()}
function act(i,back=false){focus=i;if(E.cycle(p(),s(),i,back)){say('');render();$('board').querySelector(`[data-cell="${i}"]`).focus()}}
function boardKey(ev,i){const moves={ArrowUp:-p().size,ArrowDown:p().size,ArrowLeft:-1,ArrowRight:1};if(ev.key in moves){ev.preventDefault();let next=i;while(true){let prev=next;next+=moves[ev.key];if(next<0||next>=p().size*p().size||((ev.key==='ArrowLeft'||ev.key==='ArrowRight')&&Math.floor(prev/p().size)!==Math.floor(next/p().size)))break;if(E.white(p(),next)){$('board').querySelector(`[data-cell="${next}"]`).focus();break}}}else if(ev.key===' '||ev.key==='Enter'){ev.preventDefault();act(i,ev.shiftKey)}else if(['b','B','x','X','Delete','Backspace'].includes(ev.key)){ev.preventDefault();let value=ev.key.toLowerCase()==='b'?1:ev.key.toLowerCase()==='x'?2:0;if(s().marks[i]!==value){s().history.push(s().marks.slice());if(s().history.length>1500)s().history.shift();s().marks[i]=value;say('');render();$('board').querySelector(`[data-cell="${i}"]`).focus()}}}
function move(i){index=Math.max(0,Math.min(49,i));focus=p().board.join('').indexOf('.');say('');render()}
function modal(title,body,confirm){$('modalTitle').textContent=title;$('modalBody').replaceChildren(body);onConfirm=confirm;$('confirm').hidden=!confirm;$('cancel').textContent=confirm?'取消':'繼續挑戰';$('modal').showModal()}
$('level').onchange=()=>move(+$('level').value);$('prev').onclick=()=>move(index-1);$('next').onclick=()=>move(index+1);$('undo').onclick=()=>{if(E.undo(p(),s())){say('已撤銷上一個動作。');render()}};$('reset').onclick=()=>{let t=document.createElement('p');t.textContent='這一關的燈泡與 × 標記將被清除。';modal('重新開始這一關？',t,()=>{states[index]=E.state(p(),null);completed.delete(index);say('已重新開始。');render()})};$('hint').onclick=()=>{let sol=new Set(p().solution),wrong=s().marks.findIndex((v,i)=>v===1&&!sol.has(i)),missing=p().solution.find(i=>s().marks[i]!==1),i=wrong>=0?wrong:missing;if(i===undefined){say('所有燈泡都已在正確的位置！');return}say(`提示：唯一解的第 ${Math.floor(i/p().size)+1} 列、第 ${i%p().size+1} 欄${wrong>=0?'不放燈泡':'要放燈泡'}。棋盤未更動。`)};$('solution').onclick=()=>{let b=document.createElement('div'),t=document.createElement('p'),grid=document.createElement('div');t.textContent='唯一解。查看不會完成關卡，也不會改動你的燈泡。';grid.className='board dialogboard';drawBoard(grid,p(),Array.from({length:p().size*p().size},(_,i)=>p().solution.includes(i)?1:0),false);b.append(t,grid);modal('解答 · 第 '+(index+1)+' 關',b,null)};$('cancel').onclick=()=>$('modal').close();$('confirm').onclick=()=>{let fn=onConfirm;$('modal').close();onConfirm=null;if(fn)fn()};$('modal').addEventListener('close',()=>{onConfirm=null});focus=p().board.join('').indexOf('.');render();
})();
