(()=>{'use strict';const E=MastermindEngine,levels=MASTERMIND_LEVELS,$=id=>document.getElementById(id),key='logic-mastermind-v1',names=['紅','橙','綠','藍','紫','粉'];let index=0,records={},states={},completed=new Set,selected=0,hints=0,onConfirm=null,storageOk=true;
try{const data=JSON.parse(localStorage.getItem(key));if(data&&data.version===1&&Number.isInteger(data.current)&&data.current>=0&&data.current<50){index=data.current;if(data.records&&typeof data.records==='object'&&!Array.isArray(data.records))records=data.records;for(let i=0;i<50;i++){states[i]=E.state(levels[i],records[i]);if(E.won(levels[i],states[i]))completed.add(i)}}}catch(e){storageOk=false}
const p=()=>levels[index],s=()=>states[index]||(states[index]=E.state(p(),null));
function save(){try{localStorage.setItem(key,JSON.stringify({version:1,current:index,records:states}))}catch(e){storageOk=false}}
function peg(v){const el=document.createElement('span');el.className='peg c'+v;el.textContent=v+1;el.setAttribute('aria-label',names[v]+' '+(v+1));return el}
function code(a){let box=document.createElement('div');box.className='code';a.forEach(x=>box.append(peg(x)));return box}
function say(t){$('message').textContent=t;$('message').className='message'}
function row(a,fb,label){const r=document.createElement('div');r.className='history-row';const l=document.createElement('span');l.className='rowlabel';l.textContent=label;r.append(l,code(a));const f=document.createElement('span');f.className='feedback';f.textContent='● '+fb[0]+'　○ '+fb[1];f.setAttribute('aria-label',`${fb[0]} 個黑，${fb[1]} 個白`);r.append(f);return r}
function render(){let level=p(),state=s(),win=E.won(level,state);if(win)completed.add(index);$('level').innerHTML='';levels.forEach((_,i)=>{let o=document.createElement('option');o.value=i;o.textContent=`第 ${String(i+1).padStart(2,'0')} 關${completed.has(i)?' ✓':''}`;$('level').append(o)});$('level').value=index;$('prev').disabled=index===0;$('next').disabled=index===49;$('variant').textContent=`${level.length} 格 · ${level.colors} 色 · ${level.repeat?'可重複':'不可重複'}`;$('attempts').textContent=`猜測 ${state.guesses.length} / ${level.limit}`;$('history').innerHTML='';level.clues.forEach((c,i)=>$('history').append(row(c.guess,c.feedback,'線索 '+(i+1))));state.guesses.forEach((g,i)=>$('history').append(row(g,E.score(level.solution,g),'猜測 '+(i+1))));$('draft').innerHTML='';state.draft.forEach((v,i)=>{let b=document.createElement('button');b.className='slot'+(i===selected?' active':'');b.setAttribute('aria-label',`第 ${i+1} 格：${v===null?'尚未選色':names[v]}`);b.setAttribute('aria-pressed',String(i===selected));if(v!==null)b.append(peg(v));else b.textContent='·';b.onclick=()=>{selected=i;render()};$('draft').append(b)});$('palette').innerHTML='';let label=document.createElement('span');label.className='palette-label';label.textContent='選擇顏色';$('palette').append(label);for(let v=0;v<level.colors;v++){let b=document.createElement('button');b.append(peg(v));b.setAttribute('aria-label',`選擇 ${names[v]} ${v+1}`);b.onclick=()=>choose(v);$('palette').append(b)}$('undo').disabled=!state.guesses.length;$('submit').disabled=win||state.guesses.length>=level.limit;$('rule').textContent=level.repeat?'本關可重複顏色；猜測與秘密色碼都可以出現同色多次。':'本關不可重複顏色；猜測與秘密色碼的每個顏色最多一次。';$('progress').textContent=`已完成 ${completed.size} / 50 關${storageOk?'':' · 儲存空間不可用'}`;if(win){say('破解成功！這就是所有線索的唯一答案 🎉');$('message').classList.add('win')}else if(state.guesses.length>=level.limit)say('本次機會用完了。可以撤銷，或重新開始再挑戰。');save()}
function choose(v){if(E.won(p(),s())||s().guesses.length>=p().limit)return;s().draft[selected]=v;selected=(selected+1)%p().length;say('');render()}
function submit(){if(!E.validCode(s().draft,p())){say(s().draft.some(v=>v===null)?'請先填滿每一格。':'本關不可重複使用顏色。');return}if(E.submit(p(),s())){selected=0;say('新回饋已加入，繼續推理吧。');render();$('history').scrollTop=$('history').scrollHeight}}
function move(i){index=Math.max(0,Math.min(49,i));selected=0;hints=0;say('');render()}
function modal(title,body,confirm){$('modalTitle').textContent=title;$('modalBody').replaceChildren(body);onConfirm=confirm;$('confirm').hidden=!confirm;$('cancel').textContent=confirm?'取消':'繼續挑戰';$('modal').showModal()}
$('submit').onclick=submit;$('level').onchange=()=>move(+$('level').value);$('prev').onclick=()=>move(index-1);$('next').onclick=()=>move(index+1);$('undo').onclick=()=>{if(E.undo(p(),s())){selected=0;say('已撤銷上一個猜測，可以修改後再送出。');render()}};$('reset').onclick=()=>{let b=document.createElement('p');b.textContent='確定清除這一關的猜測紀錄嗎？預置線索會保留。';modal('重新開始這一關？',b,()=>{states[index]=E.state(p(),null);completed.delete(index);selected=0;say('已重新開始。');render()})};$('hint').onclick=()=>{let i=hints++%p().length;const v=p().solution[i];say(`提示：唯一答案的第 ${i+1} 格是 ${v+1}（${names[v]}）。目前輸入未更動。`)};$('solution').onclick=()=>{const b=document.createElement('div'),t=document.createElement('p');t.textContent='所有預置線索共同決定的唯一答案。查看不會完成關卡，也不改動猜測。';b.append(t,code(p().solution));modal('解答 · 第 '+(index+1)+' 關',b,null)};$('cancel').onclick=()=>$('modal').close();$('confirm').onclick=()=>{const fn=onConfirm;$('modal').close();onConfirm=null;if(fn)fn()};$('modal').addEventListener('close',()=>{onConfirm=null});document.addEventListener('keydown',ev=>{if($('modal').open||['SELECT','INPUT','TEXTAREA'].includes(ev.target.tagName))return;if(ev.key==='ArrowLeft'||ev.key==='ArrowRight'){ev.preventDefault();selected=(selected+(ev.key==='ArrowLeft'?-1:1)+p().length)%p().length;render()}else if(/^[1-6]$/.test(ev.key)&&+ev.key<=p().colors){ev.preventDefault();choose(+ev.key-1)}else if(ev.key==='Backspace'||ev.key==='Delete'){ev.preventDefault();s().draft[selected]=null;say('');render()}else if(ev.key==='Enter'&&ev.target.tagName!=='BUTTON'){ev.preventDefault();submit()}});render();
})();
