(function(r,f){if(typeof module==='object'&&module.exports)module.exports=f(require('./specs.js'));else r.PhysicsEngine=f(r.PhysicsSpecs);})(globalThis,function(S){'use strict';
const DT=1/60,clone=o=>JSON.parse(JSON.stringify(o)),clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rad=a=>a*Math.PI/180,mag=(x,y)=>Math.hypot(x,y),rnd=(seed)=>{let a=seed>>>0;return()=>{a+=0x6D2B79F5;let t=a;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296;}};
function sanitize(id,parts){const sp=S.find(s=>s.id===id);if(!sp)throw Error('Unknown game');if(!Array.isArray(parts))return[];return parts.slice(0,10).map(p=>Object.fromEntries(sp.fields.map(f=>[f.key,clamp(Number.isFinite(+p[f.key])?+p[f.key]:f.min,f.min,f.max)])));}
function create(level,parts,options={}){const s={level:clone(level),id:level.game,parts:sanitize(level.game,parts),t:0,tick:0,status:'ready',reason:'',difficulty:['easy','normal','hard'].includes(options.difficulty)?options.difficulty:'normal',bodies:[],lines:[],metrics:{},events:[],trace:[],input:{drive:0,squat:false},energy:0};init(s);return s;}
function start(s){if(s.status==='ready'){s.status='running';s.events.push({tick:0,type:'start'});}return s;}
function fail(s,why){s.status='lost';s.reason=why;}
function forceBody(b,fx,fy,dt=DT){b.vx+=(fx/b.m)*dt;b.vy+=(fy/b.m)*dt;b.x+=b.vx*dt;b.y+=b.vy*dt;}
function part(s,i,fallback={}){return s.parts[i]||fallback;}
function init(s){let l=s.level,p=s.parts;
 switch(s.id){
 case'jelly-skyscraper':s.bodies=l.loads.map((m,i)=>({x:part(s,i,{x:0}).x||0,y:8+i*9,v:0,m,broken:false}));s.metrics.peak=0;break;
 case'chain-demolition':s.bodies=l.towers.map(t=>({...t,angle:0,omega:0,awake:false,hit:false}));s.fired=[];s.metrics.protected=true;break;
 case'junk-mech-battle':s.bodies=[{x:22,y:8,v:0,lean:0,spin:0,m:3+p.reduce((a,q)=>a+q.radius*.25+q.torque*.015,0)},{x:75,y:8,v:0,lean:0,spin:0,m:l.enemyMass}];s.aiNext=0;s.aiDrive=0;s.metrics.aiDecisions=0;s.metrics.peakLean=0;break;
 case'steam-pressure-lab':s.pressure=0;s.temperature=20;s.bodies=l.loads.map((load,i)=>({x:0,v:0,p:0,load,done:false,doneAt:null}));s.metrics.volume=0;break;
 case'gravity-room-workshop':s.bodies=[{x:4,y:l.startY,vx:0,vy:0,m:1,docked:false},{x:1,y:l.startY+1.5,vx:0,vy:0,m:1,docked:false}];s.crossings=[];s.pathCrossings=[[],[]];break;
 case'wind-tunnel-cargo':s.bodies=[{x:5,y:64,vx:0,vy:0,m:l.mass}];s.crossings=[];break;
 case'resonance-glass':s.bodies=l.glass.map(g=>({...g,x:0,v:0,peak:0,broken:false}));s.metrics.guardPeak=0;break;
 case'melting-ice-bridge':s.bodies=l.segments.map((g,i)=>({...g,ice:part(s,i,{thickness:.15}).thickness,gate:g.gate}));s.car={x:0,y:8};s.metrics.minIce=3;break;
 case'sand-collapse-lab':{const R=rnd(l.seed),mix=p.length?p.reduce((a,q)=>a+q.gravel,0)/p.length:l.gravel;s.metrics.mixture=mix;s.bodies=Array.from({length:l.count},(_,i)=>({x:l.sourceX+(R()-.5)*6,y:70+Math.floor(i/5)*2.2,vx:0,vy:0,m:i/l.count<mix?1.8:1,r:i/l.count<mix?1.05:.75,bin:-1}));s.metrics.bins=[0,0,0];break;}
 case'rope-net-catch':s.bodies=[{x:l.dropX,y:74,vx:0,vy:0,m:l.mass}];s.caught=false;s.metrics.minY=74;s.metrics.peakForce=0;break;
 case'magnetic-sculpture':s.bodies=l.pieces.map((m,i)=>({x:8+i*84/(l.pieces.length-1),y:2.5,m,vx:0,vy:0,r:2.5}));s.bonds=[];s.metrics.withdrawn=false;break;
 case'friction-playground':s.bodies=[{x:1,v:l.speed,y:35}];s.metrics.crest=false;break;
 case'cloth-parachute':{let q=part(s,0,{width:4,rope:4,bias:0,cut:.95});s.bodies=Array.from({length:5},(_,i)=>({x:50+(i-2)*q.width/2,y:68,vx:0,vy:0,m:.15}));s.bodies.push({x:50+q.bias,y:68-q.rope,vx:0,vy:0,m:l.mass});s.metrics.strain=0;break;}
 case'hydraulic-hand':s.bodies=[{x:0,v:0,p:0},{x:0,v:0,p:0}];s.metrics.volume=0;s.metrics.peakClamp=0;s.phase=0;break;
 case'soap-bubble-lab':s.bodies=[{x:5,y:4,vx:0,vy:0,m:l.mass}];s.metrics.apex=4;s.metrics.gateY=null;break;
 }
}
function step(s,input={}){if(s.status!=='running')return s;s.input={drive:clamp(+input.drive||0,-1,1),squat:!!input.squat};s.tick++;s.t=s.tick*DT;const fn=updates[s.id];fn(s);if(s.tick%15===0)s.trace.push(snapshot(s));if(s.status==='running'&&s.t>=s.level.duration)finish(s);return s;}
function snapshot(s){return{tick:s.tick,bodies:s.bodies.map(b=>({x:b.x,y:b.y,angle:b.angle,broken:b.broken,ice:b.ice,bin:b.bin})),metrics:clone(s.metrics)};}
function finish(s){if(s.status!=='running')return;const result=grade(s);s.status=result.ok?'won':'lost';s.reason=result.reason;}
function grade(s){const l=s.level,g=l.goal||{},m=s.metrics,b=s.bodies,p=s.parts;if(!l.goal)return{ok:false,reason:'探索結果'};let ok=false,reason='未達成目標，調整建構後再試。';
 switch(s.id){
 case'jelly-skyscraper':ok=b.every(z=>!z.broken)&&m.peak<=g.maxDeflection&&p.length===b.length&&cost(s)<=l.budget&&p.every((q,i)=>q.k<=l.materialCaps[i]);reason=`最大擺幅 ${fmt(m.peak)}／${g.maxDeflection}；用料 ${fmt(cost(s))}／${l.budget}`;break;
 case'chain-demolition':ok=b.every(z=>z.angle>1.18)&&m.protected&&cost(s)<=l.budget;reason=`倒下 ${b.filter(z=>z.angle>1.18).length}/${b.length} 棟；鄰屋${m.protected?'完整':'受損'}`;break;
 case'junk-mech-battle':ok=b[1].x>94&&b[0].x>6&&Math.abs(b[0].lean)<1.05&&cost(s)<=l.budget&&p.every(q=>Math.abs(q.x)<=l.axleLimit);reason=`對手位置 ${fmt(b[1].x)}；機身傾角 ${fmt(Math.abs(b[0].lean)*180/Math.PI)}°`;break;
 case'steam-pressure-lab':ok=b.every(z=>z.done)&&l.order.every((n,i)=>!i||b[l.order[i-1]].doneAt<b[n].doneAt)&&s.temperature<l.maxTemp&&m.volume<l.volume;reason=`活塞 ${b.filter(z=>z.done).length}/${b.length}；溫度 ${fmt(s.temperature)}；用氣 ${fmt(m.volume)}/${l.volume}`;break;
 case'gravity-room-workshop':ok=b.every(z=>z.docked)&&s.pathCrossings.every(path=>path.length===3&&path.every((q,i)=>Math.abs(q-l.gates[i])<=l.aperture));reason=`裝配會合 ${b.filter(z=>z.docked).length}/2；首件穿孔 ${s.crossings.filter((q,i)=>Math.abs(q-l.gates[i])<=l.aperture).length}/3`;break;
 case'wind-tunnel-cargo':ok=!!m.landed&&Math.abs(b[0].x-g.x)<=g.radius&&m.impact<=g.maxImpact&&s.crossings.length>=2&&s.crossings.slice(0,2).every((q,i)=>Math.abs(q-l.gates[i])<=l.aperture);reason=`落點 ${fmt(b[0].x)}；落速 ${fmt(m.impact||0)}；通風孔 ${s.crossings.length}/2`;break;
 case'resonance-glass':ok=b.slice(0,-1).every(z=>z.broken)&&!b.at(-1).broken&&cost(s)<=l.budget;reason=`目標破裂 ${b.slice(0,-1).filter(z=>z.broken).length}/${b.length-1}；保護器物${b.at(-1).broken?'破裂':'完整'}`;break;
 case'melting-ice-bridge':ok=s.car.x>=l.length&&m.minIce>0;reason=`行駛 ${fmt(s.car.x)}/${fmt(l.length)}；最薄餘冰 ${fmt(m.minIce)}`;break;
 case'sand-collapse-lab':ok=m.bins.every((n,i)=>n>=g.bins[i])&&m.bins.reduce((a,v)=>a+v,0)>=g.total;reason=`三槽 ${m.bins.join(' / ')}；需 ${g.bins.join(' / ')}`;break;
 case'rope-net-catch':ok=s.caught&&m.minY>=g.minY&&m.peakForce<=l.strength&&mag(b[0].vx,b[0].vy)<g.maxSpeed&&b[0].y<56&&Math.abs(b[0].x-l.targetX)<3;reason=`最低點 ${fmt(m.minY)}；峰值張力 ${fmt(m.peakForce)}/${l.strength}；末速 ${fmt(mag(b[0].vx,b[0].vy))}`;break;
 case'magnetic-sculpture':ok=m.withdrawn&&b.every(z=>Math.abs(z.x-g.x)<=g.width&&z.y<=g.height&&mag(z.vx,z.vy)<g.maxSpeed)&&s.bonds.length>=g.bonds;reason=`殘磁接合 ${s.bonds.length}；已撤磁 ${m.withdrawn?'是':'否'}；輪廓內 ${b.filter(z=>Math.abs(z.x-g.x)<=g.width&&z.y<=g.height).length}/${b.length}`;break;
 case'friction-playground':ok=Math.abs(b[0].x-g.x)<=g.radius&&Math.abs(b[0].v)<.15&&m.crest;reason=`停靠 ${fmt(b[0].x)}，目標 ${fmt(g.x)} ± ${g.radius}；速度 ${fmt(b[0].v)}`;break;
 case'cloth-parachute':ok=m.landed&&Math.abs(b[5].x-g.x)<=g.radius&&m.impact<=g.maxImpact;reason=`包裹落點 ${fmt(b[5].x)}；落速 ${fmt(m.impact||0)}/${g.maxImpact}`;break;
 case'hydraulic-hand':ok=b[0].x>=l.height&&b[1].x>=g.minClamp&&b[1].x<=g.maxClamp&&m.peakClamp<=l.crush&&m.volume<=l.volume;reason=`抬升 ${fmt(b[0].x)}/${l.height}；夾持 ${fmt(b[1].x)}；峰力 ${fmt(m.peakClamp)}/${l.crush}`;break;
 case'soap-bubble-lab':ok=m.landed&&m.gateY>=l.obstacle&&Math.abs(b[0].x-g.x)<=g.radius&&m.impact<=g.maxImpact;reason=`越障高度 ${fmt(m.gateY||0)}/${l.obstacle}；落點 ${fmt(b[0].x)}；落速 ${fmt(m.impact||0)}`;break;
 }return{ok,reason};}
function fmt(v){return Number.isFinite(v)?Number(v.toFixed(2)):0;}
function cost(s){switch(s.id){case'jelly-skyscraper':return s.parts.reduce((a,p)=>a+p.k*.025+p.d*.1+p.width*.3,0);case'chain-demolition':return s.parts.reduce((a,p)=>a+p.power,0);case'junk-mech-battle':return s.parts.reduce((a,p)=>a+p.torque*.3+p.grip*2+p.hinge*.12,0);case'resonance-glass':return s.parts.reduce((a,p)=>a+p.amplitude*p.duration,0);default:return s.parts.length;}}
const updates={};
updates['jelly-skyscraper']=s=>{const l=s.level,b=s.bodies,forces=b.map((z,i)=>l.wind*Math.sin(s.t*l.windHz+i*.17)+l.quake*z.m*Math.sin(s.t*l.quakeHz));for(let i=0;i<b.length;i++){const q=part(s,i,{x:0,k:5,d:0,width:2}),z=b[i],below=i?b[i-1]:{x:0,v:0},rest=q.x-(i?part(s,i-1,{x:0}).x:0),extension=z.x-below.x-rest,F=-q.k*extension-q.d*(z.v-below.v);if(!z.broken){forces[i]+=F;if(i)forces[i-1]-=F;if(Math.abs(extension)>q.width*.62)z.broken=true;}}b.forEach((z,i)=>{z.v+=forces[i]/z.m*DT;z.x+=z.v*DT;s.metrics.peak=Math.max(s.metrics.peak,Math.abs(z.x));if(!Number.isFinite(z.x)||Math.abs(z.x)>60)fail(s,'樓層斷裂並失穩。');});};
updates['chain-demolition']=s=>{let l=s.level,b=s.bodies;for(let i=0;i<s.parts.length;i++){let p=s.parts[i];if(!s.fired[i]&&s.t>=p.time){s.fired[i]=true;let near=b.map((z,j)=>[mag(z.x-p.x,p.y),j]).sort((a,b)=>a[0]-b[0])[0];if(near&&near[0]<7&&p.power>0){let z=b[near[1]];z.awake=true;z.omega+=(p.x<z.x?1:-1)*p.power/(z.m*.9);}}}for(let i=0;i<b.length;i++){let z=b[i];if(z.awake){z.omega+=(2.2*Math.sin(z.angle)-.07*z.omega)*DT;z.angle+=z.omega*DT;if(z.angle>Math.PI/2){z.angle=Math.PI/2;z.omega=0;}if(z.angle<-.4)s.metrics.protected=false;let tip=z.x+Math.sin(z.angle)*z.h;if(i+1<b.length&&tip>=b[i+1].x&&z.angle<1.57&&!z.hit){z.hit=true;let n=b[i+1];n.awake=true;n.omega+=Math.max(.35,z.omega*z.m/n.m*.65);z.omega*=.75;}if(tip<l.protect)s.metrics.protected=false;}}};
function ai(s){const a=s.bodies[1],p=s.bodies[0],tier=s.difficulty;let interval=tier==='easy'?.65:tier==='hard'?.06:.22;s.aiNext=s.t+interval;s.metrics.aiDecisions++;if(tier==='easy')return s.t<1.8?0:-.52;if(tier==='hard'){if(a.x>83)return-1;if(a.x-p.x<12&&p.v>3&&Math.abs(p.lean)>.16)return .25;if(a.x-p.x>18)return-.85;return-1;}return a.x-p.x>14?-.72:-.85;}
updates['junk-mech-battle']=s=>{let l=s.level,[a,b]=s.bodies;if(s.t>=s.aiNext)s.aiDrive=ai(s);let wheels=s.parts,span=wheels.length?Math.max(...wheels.map(p=>p.x))-Math.min(...wheels.map(p=>p.x)):0,traction=wheels.reduce((z,p)=>z+Math.min(p.torque/p.radius,p.grip*a.m*9.8/wheels.length)*Math.min(1,p.radius/l.bump)**4,0),stiff=wheels.reduce((z,p)=>z+p.hinge,0),fa=traction*s.input.drive,fb=l.enemyForce*s.aiDrive; a.v+=(fa/a.m-a.v*.45)*DT;b.v+=(fb/b.m-b.v*.45)*DT;a.x+=a.v*DT;b.x+=b.v*DT;let overlap=12-(b.x-a.x),contact=0;if(overlap>0){contact=overlap*65+Math.max(0,a.v-b.v)*8;let j=contact*DT;a.v-=j/a.m;b.v+=j/b.m;a.x-=overlap*.4;b.x+=overlap*.4;}let center=s.input.squat?.6:1.6;a.spin+=((fa-contact)*center/(a.m*8)-a.lean*(span*.4+stiff*.08)-a.spin*4)*DT;a.lean+=a.spin*DT;s.metrics.peakLean=Math.max(s.metrics.peakLean,Math.abs(a.lean));if(Math.abs(a.lean)>1.05||a.x<6)fail(s,'機械翻覆或被推出平台。');else if(b.x>94)finish(s);};
updates['steam-pressure-lab']=s=>{let l=s.level,b=s.bodies;s.pressure+=((l.supply-s.pressure)*2.2-l.leak*s.pressure)*DT;s.temperature+=(s.pressure*.08-(s.temperature-20)*.08)*DT;for(let i=0;i<b.length;i++){let z=b[i],q=part(s,i,{source:4,area:.2,flow:.1,delay:8}),src=Math.round(q.source)-1,enabled=s.t>=q.delay&&(src<0||(b[src]&&b[src].done));let flow=enabled?Math.max(0,s.pressure-z.p)*q.flow:0;z.p+=(flow-z.p*l.leak-z.v*q.area)*DT;z.p=Math.max(0,z.p);s.pressure=Math.max(0,s.pressure-flow*.12*DT);let f=z.p*q.area-z.load;z.v=Math.max(0,z.v+(f-z.v*4)*DT);let dx=Math.min(z.v*DT,l.strokes[i]-z.x);if(!z.done){z.x+=dx;s.metrics.volume+=Math.max(0,dx*q.area);if(z.x>=l.strokes[i]-.0001){z.x=l.strokes[i];z.v=0;z.done=true;z.doneAt=s.t;}}}if(s.temperature>l.maxTemp)fail(s,'鍋爐過熱。');if(b.every(z=>z.done))finish(s);};
updates['gravity-room-workshop']=s=>{let l=s.level;for(let n=0;n<s.bodies.length;n++){let z=s.bodies[n];if(z.docked)continue;let i=Math.min(2,Math.floor(z.x/33.333)),p=part(s,i,{angle:0,strength:8}),old=z.x;forceBody(z,Math.cos(rad(p.angle))*p.strength-z.vx*2,Math.sin(rad(p.angle))*p.strength-z.vy*2);for(let k=0;k<3;k++)if(old<[33,66,96][k]&&z.x>=[33,66,96][k]){s.pathCrossings[n][k]=z.y;if(n===0)s.crossings[k]=z.y;if(l.goal&&Math.abs(z.y-l.gates[k])>l.aperture)fail(s,'零件撞上裝配孔邊緣。');}if(z.y<1||z.y>74)fail(s,'零件撞上房間邊界。');if(z.x>=96){z.x=97;z.docked=true;z.vx=z.vy=0;}}if(s.bodies.every(z=>z.docked))finish(s);};
updates['wind-tunnel-cargo']=s=>{let l=s.level,z=s.bodies[0],wx=0,wy=0,old=z.x;for(let p of s.parts){let w=Math.max(0,1-Math.abs(z.x-p.x)/25)*(.55+.45*Math.exp(-Math.abs(z.y-p.y)/50));wx+=Math.cos(rad(p.angle))*p.power*w;wy+=Math.sin(rad(p.angle))*p.power*w;}let dx=wx-z.vx,dy=wy-z.vy,area=l.area;forceBody(z,clamp(dx*Math.abs(dx)*area*.055,-60,60),clamp(dy*Math.abs(dy)*area*.055,-50,80)-z.m*5);for(let k=0;k<2;k++)if(old<[32,62][k]&&z.x>=[32,62][k]){s.crossings[k]=z.y;if(l.goal&&Math.abs(z.y-l.gates[k])>l.aperture)fail(s,'貨箱撞上導流孔邊緣。');}if(z.y<=2){z.y=2;s.metrics.landed=true;s.metrics.impact=mag(z.vx,z.vy);finish(s);}else if(z.x>110||z.y>90||z.x<0)fail(s,'貨箱離開風洞。');};
updates['resonance-glass']=s=>{let elapsed=0,F=0;for(let p of s.parts){if(s.t>=elapsed&&s.t<elapsed+p.duration)F+=p.amplitude*Math.sin(2*Math.PI*p.frequency*(s.t-elapsed));elapsed+=p.duration;}for(let z of s.bodies){if(z.broken)continue;let w=2*Math.PI*z.frequency;z.v+=(F-2*z.damping*w*z.v-w*w*z.x)*DT;z.x+=z.v*DT;z.peak=Math.max(z.peak,Math.abs(z.x));if(Math.abs(z.x)>z.limit)z.broken=true;}s.metrics.guardPeak=s.bodies.at(-1).peak;};
updates['melting-ice-bridge']=s=>{let l=s.level;for(let z of s.bodies){let heatBridge=0,heatGate=0;for(let p of s.parts){heatBridge+=p.power*Math.exp(-mag(p.x-z.center,p.y)/4);heatGate+=p.power*Math.exp(-mag(p.x-z.center,p.y-6)/4);}z.ice-=heatBridge*.004*DT;z.gate=Math.max(0,z.gate-heatGate*.022*DT);s.metrics.minIce=Math.min(s.metrics.minIce,z.ice);}s.car.x+=l.speed*DT;let z=s.bodies.find(z=>s.car.x>=z.start&&s.car.x<z.end);if(z){let capacity=45*Math.pow(Math.max(0,z.ice),3)/z.span;if(capacity<l.mass)fail(s,'承重冰面彎折，車輛墜落。');if(s.car.x>=z.center-1&&s.car.x<=z.center+1&&z.gate>.02)fail(s,'擋路冰塊還沒有融開。');}if(s.car.x>=l.length)finish(s);};
updates['sand-collapse-lab']=s=>{let b=s.bodies,dt=DT;for(let z of b){if(z.bin>=0)continue;z.vy-=12*dt;z.vx*=.998;z.x+=z.vx*dt;z.y+=z.vy*dt;for(let p of s.parts){let c=Math.cos(rad(p.angle)),sn=Math.sin(rad(p.angle)),dx=z.x-p.x,dy=z.y-p.y,u=dx*c+dy*sn,n=-dx*sn+dy*c,vn=-z.vx*sn+z.vy*c;if(Math.abs(u)<p.length/2&&n<z.r&&n>-(z.r+2)&&vn<0){let push=z.r-n;z.x-=sn*push;z.y+=c*push;let tangent=(z.vx*c+z.vy*sn)*(1-p.wet*.09);z.vx=tangent*c+vn*(z.m>1?.18:.05)*sn;z.vy=tangent*sn-vn*(z.m>1?.18:.05)*c;}}if(z.x<z.r){z.x=z.r;z.vx=Math.abs(z.vx)*.4;}if(z.x>100-z.r){z.x=100-z.r;z.vx=-Math.abs(z.vx)*.4;}if(z.y<=z.r){z.bin=z.x<s.level.binEdges[0]?0:z.x<s.level.binEdges[1]?1:2;s.metrics.bins[z.bin]++;z.vx=z.vy=0;z.y=z.r;}}for(let i=0;i<b.length;i++)for(let j=i+1;j<b.length;j++){let a=b[i],z=b[j];if(a.bin>=0||z.bin>=0)continue;let dx=z.x-a.x,dy=z.y-a.y,d=mag(dx,dy),min=a.r+z.r;if(d>0&&d<min){let h=(min-d)*.5,nx=dx/d,ny=dy/d;a.x-=nx*h;a.y-=ny*h;z.x+=nx*h;z.y+=ny*h;let rel=(z.vx-a.vx)*nx+(z.vy-a.vy)*ny;if(rel<0){let imp=-(1.04)*rel/(1/a.m+1/z.m);a.vx-=imp/a.m*nx;a.vy-=imp/a.m*ny;z.vx+=imp/z.m*nx;z.vy+=imp/z.m*ny;}}}if(s.metrics.bins.reduce((a,v)=>a+v,0)===b.length)finish(s);};
updates['rope-net-catch']=s=>{let l=s.level,z=s.bodies[0];if(!s.caught&&z.y<50&&s.parts.length>=2&&z.x>Math.min(...s.parts.map(p=>p.x))&&z.x<Math.max(...s.parts.map(p=>p.x)))s.caught=true;let fx=-z.vx*.2,fy=-z.m*9.8;if(s.caught)for(let p of s.parts){let dx=p.x-z.x,dy=p.y-z.y,d=mag(dx,dy),stretch=d-p.length;if(stretch>0&&d>0){let away=-(z.vx*dx+z.vy*dy)/d,F=Math.max(0,p.k*stretch+p.d*away);s.metrics.peakForce=Math.max(s.metrics.peakForce,F);fx+=F*dx/d;fy+=F*dy/d;if(F>l.strength)fail(s,'繩索張力超過強度而斷裂。');}}forceBody(z,fx,fy);s.metrics.minY=Math.min(s.metrics.minY,z.y);if(z.y<3)fail(s,'巨石穿過網底碰地。');};
updates['magnetic-sculpture']=s=>{let b=s.bodies;for(let i=0;i<b.length;i++){let z=b[i],fx=-z.vx*1.3,fy=-z.m*8-z.vy*1.3;for(let p of s.parts)if(s.t<p.off){let dx=p.x-z.x,dy=p.y-z.y,d=mag(dx,dy),force=p.strength*Math.exp(-d/35);if(d>0){fx+=force*dx/(d+2);fy+=force*dy/(d+2);}}for(let pair of s.bonds){let j=pair[0]===i?pair[1]:pair[1]===i?pair[0]:-1;if(j<0)continue;let o=b[j],dx=o.x-z.x,dy=o.y-z.y,d=mag(dx,dy),F=(d-5)*12;if(d){fx+=F*dx/d;fy+=F*dy/d;}}forceBody(z,fx,fy);if(z.y<2.5){z.y=2.5;z.vy=Math.max(0,-z.vy*.05);z.vx*=.92;}z.x=clamp(z.x,2.5,97.5);}for(let i=0;i<b.length;i++)for(let j=i+1;j<b.length;j++){let a=b[i],z=b[j],dx=z.x-a.x,dy=z.y-a.y,d=mag(dx,dy);if(d<5.3&&s.t<8&&!s.bonds.some(p=>p[0]===i&&p[1]===j))s.bonds.push([i,j]);if(d<5&&d>0){let h=(5-d)*.5;a.x-=dx/d*h;a.y-=dy/d*h;z.x+=dx/d*h;z.y+=dy/d*h;let rel=((z.vx-a.vx)*dx+(z.vy-a.vy)*dy)/d;if(rel<0){a.vx+=rel*dx/d*.5;a.vy+=rel*dy/d*.5;z.vx-=rel*dx/d*.5;z.vy-=rel*dy/d*.5;}}}b.forEach(z=>{if(z.y<2.5){z.y=2.5;z.vy=Math.max(0,z.vy);}});s.metrics.withdrawn=s.parts.every(p=>s.t>p.off);};
updates['friction-playground']=s=>{let l=s.level,z=s.bodies[0],slope=z.x<l.ramp?-l.angle:z.x<l.ramp+l.hump?l.uphill:0,mu=.01;for(let p of [...s.parts].sort((a,b)=>a.x-b.x))if(z.x>=p.x)mu=p.mu;let drive=-9.8*Math.sin(slope),friction=mu*9.8*Math.cos(slope),a=(drive-Math.sign(z.v||drive)*friction)/(1+l.inertia);if(Math.abs(z.v)<.05&&Math.abs(drive)<=friction)z.v=0;else{let next=z.v+a*DT;if(z.v*next<0&&Math.abs(drive)<=friction)z.v=0;else z.v=next;}z.x+=z.v*DT;z.y=35-Math.min(z.x,l.ramp)*Math.tan(l.angle)+Math.max(0,Math.min(l.hump,z.x-l.ramp))*Math.tan(l.uphill);if(z.x>l.ramp+l.hump)s.metrics.crest=true;if(z.x>105||z.x<0)fail(s,'物件滑出安全跑道。');if(s.metrics.crest&&z.v===0)finish(s);};
updates['cloth-parachute']=s=>{let l=s.level,p=part(s,0,{width:4,cut:.95,rope:4,bias:0}),b=s.bodies,dt=DT/2;for(let sub=0;sub<2;sub++){let forces=b.map(z=>({x:0,y:-z.m*9.8}));for(let i=0;i<5;i++){let z=b[i],air=l.wind*(.6+.4*z.y/70),area=p.width/5*(1-p.cut),dx=air-z.vx,dy=-z.vy;forces[i].x+=clamp(dx*Math.abs(dx)*area*.08,-40,40);forces[i].y+=clamp(dy*Math.abs(dy)*area*.08,-40,50);}function spring(i,j,len,k,d){let a=b[i],z=b[j],dx=z.x-a.x,dy=z.y-a.y,dist=mag(dx,dy);if(!dist)return;let speed=((z.vx-a.vx)*dx+(z.vy-a.vy)*dy)/dist,F=k*(dist-len)+d*speed;forces[i].x+=F*dx/dist;forces[i].y+=F*dy/dist;forces[j].x-=F*dx/dist;forces[j].y-=F*dy/dist;s.metrics.strain=Math.max(s.metrics.strain,Math.abs(dist-len));}for(let i=0;i<4;i++)spring(i,i+1,p.width/2,35,1.1);spring(0,5,Math.hypot(p.width,p.rope)+p.bias,28,2);spring(4,5,Math.hypot(p.width,p.rope)-p.bias,28,2);spring(2,5,p.rope,12,1);b.forEach((z,i)=>forceBody(z,forces[i].x-z.vx*.025,forces[i].y,dt));if(b[5].y<=2){s.metrics.landed=true;s.metrics.impact=mag(b[5].vx,b[5].vy);b[5].y=2;finish(s);break;}if(b.some(z=>!Number.isFinite(z.x)||Math.abs(z.x)>250||z.y>200)){fail(s,'傘具失穩。');break;}}};
updates['hydraulic-hand']=s=>{let l=s.level,i=s.phase,z=s.bodies[i],q=part(s,i,{area:.3,relief:1,flow:.2,stop:.1}),load=i===0?l.mass*9.8:l.shell*z.x,P=Math.min(l.pressure,q.relief),force=P*q.area;z.p=P;let desired=q.flow/q.area,acc=(force-load-z.v*2)/(i===0?l.mass:1);z.v=clamp(z.v+acc*DT,0,desired);let move=Math.max(0,Math.min(z.v*DT,q.stop-z.x));z.x+=move;s.metrics.volume+=move*q.area;if(i===1){s.metrics.peakClamp=Math.max(s.metrics.peakClamp,l.shell*z.x);if(l.shell*z.x>l.crush)fail(s,'薄殼被壓碎。');}if(s.metrics.volume>l.volume)fail(s,'液壓油行程用盡。');if(i===0&&z.x>=l.height){s.phase=1;z.v=0;}if(i===1&&s.t>l.duration-.05)finish(s);};
updates['soap-bubble-lab']=s=>{let l=s.level,z=s.bodies[0],parts=s.parts.filter(p=>s.t<p.pop),volume=parts.reduce((a,p)=>a+p.volume,0),allMerge=parts.length>1&&parts.every(p=>s.t>p.merge),surface=allMerge?Math.pow(volume,2/3):parts.reduce((a,p)=>a+Math.pow(p.volume,2/3),0),drag=.08+surface*.045,dx=l.wind-z.vx,dy=-z.vy,old=z.x;s.metrics.volume=volume;s.metrics.drag=drag;s.metrics.merged=allMerge;forceBody(z,dx*Math.abs(dx)*drag,(volume*.13-z.m)*5+dy*Math.abs(dy)*drag);s.metrics.apex=Math.max(s.metrics.apex,z.y);if(old<l.gateX&&z.x>=l.gateX)s.metrics.gateY=z.y;if(l.goal&&old<l.gateX&&z.x>=l.gateX&&z.y<l.obstacle)fail(s,'泡泡貨物撞到障礙。');if(z.y<=2&&s.t>.5){z.y=2;s.metrics.landed=true;s.metrics.impact=mag(z.vx,z.vy);finish(s);}else if(z.y>78||z.x>110)fail(s,'泡泡貨物離開實驗區。');};
function run(l,parts,controls,options={}){let s=create(l,parts,options);start(s);let i=0,input={drive:0,squat:false};while(s.status==='running'&&s.tick<1800){while(controls&&i<controls.length&&controls[i].tick<=s.tick){input=controls[i].input||{};i++;}step(s,input);}return s;}
function capacity(l){return l.game==='jelly-skyscraper'?l.loads.length:l.game==='steam-pressure-lab'?l.loads.length:['gravity-room-workshop'].includes(l.game)?3:l.game==='melting-ice-bridge'?4:l.game==='cloth-parachute'?1:l.game==='hydraulic-hand'?2:10;}
function controlWitness(id){return id==='junk-mech-battle'?[{tick:0,action:'start',input:{drive:1,squat:true}}]:[{tick:0,action:'start',input:{}}];}
return{DT,S,clone,clamp,rnd,create,start,step,run,grade,cost,sanitize,snapshot,controlWitness,ai,fmt,capacity};});
