'use strict';
const fs=require('fs'),path=require('path'),E=require('./engine.js'),base=path.resolve(__dirname,'..');
const round=(x,d=3)=>+x.toFixed(d);const R=(r,a,b)=>a+r()*(b-a);
function make(sp,n,attempt=0){let r=E.rnd((sp.index+1)*1000000+n*1999+attempt*317),l={id:n,game:sp.id,seed:(sp.index+1)*1000000+n*1999+attempt*317,duration:12},p=[],blank=[],a=sp.id;
if(a==='jelly-skyscraper'){l.loads=Array.from({length:3+n%4},()=>round(R(r,.7,1.6)));l.wind=round(R(r,3,8));l.windHz=round(R(r,1.1,4.5));l.quake=round(R(r,.3,1.7));l.quakeHz=round(R(r,3,7));p=l.loads.map((m,i)=>({x:0,k:120-i*3,d:18,width:10}));blank=p.map(q=>({...q,k:5,d:0,width:2}));l.materialCaps=l.loads.map(()=>round(R(r,95,155)));p=p.map((q,i)=>({...q,k:l.materialCaps[i]*.94,d:round(R(r,12,20)),width:round(R(r,8,12))}));l.goal={maxDeflection:7};l.budget=round(E.cost(E.create(l,p))*1.05);}
if(a==='chain-demolition'){let count=3+n%3,h=R(r,13,18),x=15;l.towers=Array.from({length:count},(_,i)=>{let z={x:round(x),h:round(h+R(r,-1,2)),m:round(R(r,1,2))};x+=(i===1&&n%3!==0?R(r,1.07,1.22):R(r,.5,.7))*h;return z;});l.protect=5;l.duration=12;p=l.towers.filter((z,i)=>!i||z.x-l.towers[i-1].x>l.towers[i-1].h*.97).map((z,i)=>({x:z.x-2,y:0,power:6,time:.5+i*.7}));blank=p.map(q=>({...q,power:0}));l.goal={all:true};l.budget=p.length*6.7;}
if(a==='junk-mech-battle'){l.enemyMass=round(R(r,4,7));l.enemyForce=round(R(r,9,18));l.duration=20;l.bump=round(R(r,1.2,3.6));l.axleLimit=round(R(r,7,13));let radius=round(l.bump+.2),torque=round(Math.min(44,(l.enemyForce+6)*radius*.9));p=[{x:-l.axleLimit,radius,torque,grip:1.8,hinge:16},{x:l.axleLimit,radius,torque,grip:1.8,hinge:16}];blank=p.map(q=>({...q,torque:1,grip:.15,hinge:2}));l.goal={ringout:true};l.budget=round(E.cost(E.create(l,p))*1.04);}
if(a==='steam-pressure-lab'){let count=3+n%2;l.loads=Array.from({length:count},()=>round(R(r,4,13)));l.strokes=l.loads.map(()=>round(R(r,1,2.8)));l.order=Array.from({length:count},(_,i)=>i);for(let j=count-1;j>0;j--){let k=Math.floor(r()*(j+1));[l.order[j],l.order[k]]=[l.order[k],l.order[j]];}l.supply=round(R(r,11,16));l.leak=round(R(r,.005,.06));l.maxTemp=48;l.duration=24;p=l.loads.map((v,i)=>({source:l.order.indexOf(i)===0?0:l.order[l.order.indexOf(i)-1]+1,area:round(v/l.supply+1),flow:3,delay:0}));blank=p.map(q=>({...q,area:.2,source:4}));l.volume=45;l.goal={sequence:true};}
if(a==='gravity-room-workshop'){l.startY=round(R(r,24,52));l.aperture=3;l.duration=25;p=Array.from({length:3},()=>({angle:round(R(r,-25,25)),strength:round(R(r,16,28))}));blank=p.map(q=>({...q,angle:0,strength:8}));l.gates=[0,0,0];}
if(a==='wind-tunnel-cargo'){l.mass=round(R(r,.8,1.6));l.area=round(R(r,1.2,2.2));l.aperture=4;l.duration=24;p=[{x:17,y:50,angle:round(R(r,15,28)),power:round(R(r,17,21))},{x:46,y:38,angle:round(R(r,10,23)),power:round(R(r,17,21))},{x:76,y:22,angle:round(R(r,-25,-5)),power:round(R(r,12,18))}];blank=p.map(q=>({...q,power:1,angle:0}));l.gates=[0,0];}
if(a==='resonance-glass'){l.glass=Array.from({length:3},(_,i)=>({frequency:round(.6+i*.6+R(r,-.24,.24)),damping:round(R(r,.022,.048)),limit:round(R(r,.55,.85)),guard:false}));l.glass.push({frequency:round(R(r,3.2,3.8)),damping:.065,limit:.4,guard:true});p=l.glass.slice(0,3).map(g=>({frequency:g.frequency,amplitude:round(2*Math.PI*g.frequency*1.8),duration:3.8}));blank=p.map(q=>({...q,amplitude:0}));l.goal={targets:3};l.budget=round(E.cost(E.create(l,p))*1.07);l.duration=12;}
if(a==='melting-ice-bridge'){l.mass=round(R(r,2,4));l.speed=round(R(r,3.7,4.5));let x=0;l.segments=Array.from({length:4},()=>{let span=R(r,16,21),z={start:round(x),end:round(x+span),span:round(span),center:round(x+span/2),gate:round(R(r,.25,.45))};x+=span;return z;});l.length=round(x);l.duration=25;p=l.segments.map(z=>({thickness:round(Math.cbrt(l.mass*z.span/45)+.6),x:z.center,y:6,power:round(Math.max(7,z.gate/(z.center/l.speed)*65))}));blank=p.map(q=>({...q,thickness:.15,power:0}));l.goal={cross:true};}
if(a==='sand-collapse-lab'){l.count=32+n%15;l.gravel=round(R(r,.1,.65));l.sourceX=round(R(r,36,65));l.binEdges=[round(R(r,22,36)),round(R(r,63,78))];l.duration=15;let direction=n%2?1:-1;p=[{x:l.sourceX,y:round(R(r,43,52)),angle:round(direction*R(r,28,44)),length:round(R(r,32,44)),wet:round(R(r,0,.15))},{x:l.sourceX-direction*19,y:round(R(r,19,28)),angle:round(direction*R(r,25,39)),length:round(R(r,20,32)),wet:round(R(r,0,.18))}];blank=p.map(q=>({...q,length:8,angle:0,wet:.8}));}
if(a==='rope-net-catch'){l.mass=round(R(r,3,7));l.targetX=round(R(r,35,65));l.dropX=round(l.targetX+R(r,-5,5));l.strength=430;l.duration=15;let span=round(R(r,22,30)),sag=round(R(r,20,27));p=[{x:l.targetX-span,y:58,length:round(Math.hypot(span,sag)),k:7,d:7},{x:l.targetX,y:62,length:sag+4,k:7,d:7},{x:l.targetX+span,y:58,length:round(Math.hypot(span,sag)),k:7,d:7}];blank=p.map(q=>({...q,length:60,k:.1,d:0}));l.goal={minY:9,maxSpeed:.4};}
if(a==='magnetic-sculpture'){l.pieces=Array.from({length:5+n%4},()=>round(R(r,.7,1.2)));l.duration=18;let center=round(R(r,28,72));p=[{x:center,y:7,strength:100,off:9},{x:center-6,y:6,strength:50,off:9},{x:center+6,y:6,strength:50,off:9}];blank=p.map(q=>({...q,strength:0}));}
if(a==='friction-playground'){l.ramp=round(R(r,18,28));l.hump=round(R(r,4,9));l.angle=round(R(r,.32,.48));l.uphill=round(R(r,.06,.18));l.inertia=n%2?.4:0;l.speed=round(R(r,2,4));l.duration=25;p=[{x:0,mu:round(R(r,.015,.035))},{x:l.ramp,mu:round(R(r,.02,.07))},{x:l.ramp+l.hump,mu:round(R(r,.17,.3))}];blank=p.map(q=>({...q,mu:0}));}
if(a==='cloth-parachute'){l.mass=round(R(r,.8,1.8));l.wind=round(R(r,-3.5,3.5));l.duration=30;p=[{width:round(R(r,7,18)),cut:round(R(r,.02,.5)),rope:round(R(r,6,13)),bias:round(R(r,-1.8,1.8))}];blank=[{width:4,cut:.95,rope:6,bias:0}];}
if(a==='hydraulic-hand'){l.mass=round(R(r,2,6));l.height=round(R(r,3,9));l.shell=round(R(r,6,15));l.pressure=round(R(r,18,28));let clamp=round(R(r,.8,1.6)),A=round(l.mass*9.8/l.pressure*1.45);p=[{area:A,relief:l.pressure,flow:8,stop:l.height+1},{area:1,relief:round(l.shell*clamp*1.1),flow:1.5,stop:clamp}];l.crush=round(l.shell*clamp*1.3);l.volume=round(A*(l.height+1)+clamp+2);l.duration=18;l.goal={minClamp:round(clamp*.9),maxClamp:round(clamp*1.1)};blank=p.map(q=>({...q,area:.3,relief:1,stop:.1}));}
if(a==='soap-bubble-lab'){l.mass=round(R(r,1.6,2.4));l.wind=round(R(r,4.2,6));l.gateX=25;l.obstacle=0;l.duration=28;let v=l.mass/ .13*1.5,time=round(R(r,5.8,7.5));p=[{volume:round(v*.5),merge:2.5,pop:time},{volume:round(v*.3),merge:2.5,pop:time+.3},{volume:round(v*.2),merge:2.5,pop:time+.6}];blank=p.map(q=>({...q,volume:0}));}
if(sp.id==='sand-collapse-lab'){p=p.map(q=>({...q,gravel:l.gravel}));blank=blank.map(q=>({...q,gravel:l.gravel}));}return{l,p:E.sanitize(sp.id,p),blank:E.sanitize(sp.id,blank)};}
function prepare(sp,n){for(let attempt=0;attempt<400;attempt++){let {l,p,blank}=make(sp,n,attempt),first=E.run(l,p,E.controlWitness(sp.id)),m=first.metrics,b=first.bodies;if(sp.id==='steam-pressure-lab')l.maxTemp=round(first.temperature+.7);if(!l.goal){if(sp.id==='gravity-room-workshop'){if(first.crossings.length!==3)continue;l.gates=first.crossings.map(v=>round(v));l.goal={assembly:true};}if(sp.id==='wind-tunnel-cargo'){if(!m.landed||first.crossings.length!==2||b[0].x<65)continue;l.gates=first.crossings.map(v=>round(v));l.goal={x:round(b[0].x),radius:4,maxImpact:round(m.impact+2)};}if(sp.id==='sand-collapse-lab'){let sourceBin=l.sourceX<l.binEdges[0]?0:l.sourceX<l.binEdges[1]?1:2;if(m.bins.reduce((a,v,i)=>a+(i!==sourceBin?v:0),0)<l.count*.5||m.bins.reduce((a,v)=>a+v,0)<l.count*.85)continue;l.goal={bins:m.bins.map(v=>Math.max(0,Math.floor(v*.8)-1)),total:Math.floor(l.count*.85)};}if(sp.id==='magnetic-sculpture'){if(!m.withdrawn||first.bonds.length<2||b.some(z=>Math.hypot(z.vx,z.vy)>1))continue;let center=b.reduce((a,z)=>a+z.x,0)/b.length,width=Math.max(...b.map(z=>Math.abs(z.x-center)));if(width>22)continue;l.goal={x:round(center),width:round(width+3),height:round(Math.max(...b.map(z=>z.y))+3),maxSpeed:1.5,bonds:Math.max(2,first.bonds.length-2)};}if(sp.id==='friction-playground'){if(!m.crest||Math.abs(b[0].v)>.15||b[0].x>98)continue;l.goal={x:round(b[0].x),radius:2,maxSpeed:.15};}if(sp.id==='cloth-parachute'){if(!m.landed||m.impact>12||b[5].x<8||b[5].x>92)continue;l.goal={x:round(b[5].x),radius:2.5,maxImpact:round(m.impact+.8)};}if(sp.id==='soap-bubble-lab'){if(!m.landed||!m.gateY||m.gateY<8||b[0].x<35||b[0].x>98)continue;l.obstacle=round(m.gateY-3);l.goal={x:round(b[0].x),radius:4,maxImpact:round(m.impact+1.5)};}}
let s=E.run(l,p,E.controlWitness(sp.id));if(s.status!=='won')continue;let bad=E.run(l,blank,E.controlWitness(sp.id));if(bad.status==='won')continue;l.initial=blank;l.partNames=p.map((q,i)=>sp.id==='steam-pressure-lab'?`活塞 ${i+1}`:`${sp.part} ${i+1}`);l.description=description(l);return{level:l,proof:{id:n,status:s.status,construction:p,witness:E.controlWitness(sp.id),ticks:s.tick,metrics:s.metrics,reason:s.reason},attempt};}throw Error(sp.id+' #'+n+' no feasible witness');}
function description(l){switch(l.game){case'jelly-skyscraper':return`${l.loads.length} 層樓；風力 ${l.wind}、震動 ${l.quake}；擺幅 ≤ ${l.goal.maxDeflection}，預算 ${l.budget}`;case'chain-demolition':return`清空 ${l.towers.length} 棟；左側 X=${l.protect} 以內鄰屋不可受損；能量 ≤ ${l.budget}`;case'junk-mech-battle':return`對手機重 ${l.enemyMass}，推力 ${l.enemyForce}。推至 X>94；建構成本 ≤ ${l.budget}`;case'steam-pressure-lab':return`完成順序 ${l.order.map(i=>i+1).join(' → ')}；負載 ${l.loads.join('、')}；行程 ${l.strokes.join('、')}；最高溫 ${l.maxTemp}，用氣 ≤${l.volume}`;case'gravity-room-workshop':return`三道孔高度 ${l.gates.join(' → ')}；容差 ±${l.aperture}`;case'wind-tunnel-cargo':return`質量 ${l.mass}、迎風面積 ${l.area}；孔高 ${l.gates.join('、')}；落點 ${l.goal.x} ±${l.goal.radius}`;case'resonance-glass':return`目標固有頻率 ${l.glass.slice(0,-1).map(z=>z.frequency).join('、')} Hz；保護 ${l.glass.at(-1).frequency} Hz；聲能 ≤${l.budget}`;case'melting-ice-bridge':return`載重 ${l.mass}；車速 ${l.speed}；四段橋長 ${l.segments.map(z=>z.span).join('、')}`;case'sand-collapse-lab':return`${l.count} 顆；礫石比 ${l.gravel}；左/中/右槽至少 ${l.goal.bins.join(' / ')} 顆，總共至少 ${l.goal.total} 顆`;
case'rope-net-catch':return`巨石質量 ${l.mass}，落點 X=${l.dropX}；最低高度 ≥${l.goal.minY}，張力 ≤${l.strength}，末速 <${l.goal.maxSpeed}`;case'magnetic-sculpture':return`${l.pieces.length} 片鐵；撤磁後全部留在 X=${l.goal.x} ±${l.goal.width}、高度 ≤${l.goal.height}；至少 ${l.goal.bonds} 個接合`;case'friction-playground':return`${l.inertia?'滾球':'滑塊'}，下坡 ${l.ramp}＋上坡 ${l.hump}；停在 ${l.goal.x} ±${l.goal.radius}`;case'cloth-parachute':return`包裹 ${l.mass}，側風 ${l.wind}；落點 ${l.goal.x} ±${l.goal.radius}，落速 ≤${l.goal.maxImpact}`;case'hydraulic-hand':return`重物 ${l.mass} 抬至 ${l.height}；薄殼夾持 ${l.goal.minClamp}～${l.goal.maxClamp}；壓碎力 ${l.crush}；總油量 ${l.volume}`;case'soap-bubble-lab':return`質量 ${l.mass}，側風 ${l.wind}；X=${l.gateX} 越過高度 ${l.obstacle}；落點 ${l.goal.x} ±${l.goal.radius}`;}}
if(require.main===module){const only=process.argv[2];for(let sp of E.S.filter(s=>!only||s.id===only)){let levels=[],proofs=[],maxAttempt=0;for(let n=1;n<=100;n++){let z=prepare(sp,n);levels.push(z.level);proofs.push(z.proof);maxAttempt=Math.max(maxAttempt,z.attempt);}let dir=path.join(base,sp.id);fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'levels.json'),JSON.stringify(levels));fs.writeFileSync(path.join(dir,'proofs.json'),JSON.stringify(proofs));console.log(sp.id,levels.length,'maximum retries',maxAttempt);}}
module.exports={make,prepare,description};
