(function(r,f){if(typeof module==='object'&&module.exports)module.exports=f(require('./engine.js'));else r.PhysicsSession=f(r.PhysicsEngine);})(globalThis,function(E){'use strict';
const VERSION=1;
function newSession(level,build){return{version:VERSION,level:level.id,parts:E.sanitize(level.game,build||level.initial),assisted:false,source:'manual',mode:'challenge',difficulty:'normal',tick:0,inputs:[],completed:[],builds:{}};}
function assist(session,kind){session.assisted=true;session.source=kind;return session;}
function record(session,tick,input){const v={drive:Math.max(-1,Math.min(1,+input.drive||0)),squat:!!input.squat},last=session.inputs.at(-1);if(!last||JSON.stringify(last.input)!==JSON.stringify(v))session.inputs.push({tick,input:v});session.tick=tick;}
function credit(session,state){if(state.status==='won'&&session.mode==='challenge'&&!session.assisted&&state.id===state.level.game&&session.level===state.level.id&&!session.completed.includes(session.level))session.completed.push(session.level);}
function pack(session,state){let out=JSON.parse(JSON.stringify(session));out.tick=Math.min(1800,state.tick);out.parts=E.sanitize(state.id,state.parts);out.builds[out.level]={parts:out.parts,assisted:out.assisted,source:out.source};return JSON.stringify(out);}
function restore(raw,levels,game){try{let o=typeof raw==='string'?JSON.parse(raw):raw;if(!o||o.version!==VERSION||!Number.isInteger(o.level)||o.level<1||o.level>100||!Array.isArray(o.parts))return null;const level=levels[o.level-1];let n=newSession(level,o.parts);n.assisted=!!o.assisted;n.source=['manual','hint','demo'].includes(o.source)?o.source:'manual';if(n.source!=='manual')n.assisted=true;n.mode=o.mode==='free'?'free':'challenge';n.difficulty=n.mode==='challenge'?'normal':['easy','normal','hard'].includes(o.difficulty)?o.difficulty:'normal';n.completed=Array.isArray(o.completed)?[...new Set(o.completed.filter(v=>Number.isInteger(v)&&v>=1&&v<=100))]:[];n.inputs=Array.isArray(o.inputs)?o.inputs.filter(v=>Number.isInteger(v.tick)&&v.tick>=0&&v.tick<=1800&&v.input).slice(0,1801).map(v=>({tick:v.tick,input:{drive:E.clamp(+v.input.drive||0,-1,1),squat:!!v.input.squat}})).sort((a,b)=>a.tick-b.tick):[];n.tick=E.clamp(Math.floor(+o.tick||0),0,1800);n.builds={};if(o.builds&&typeof o.builds==='object')for(let [id,v] of Object.entries(o.builds))if(+id>=1&&+id<=100&&v&&Array.isArray(v.parts))n.builds[id]={parts:E.sanitize(game,v.parts),assisted:!!v.assisted||v.source==='demo'||v.source==='hint',source:v.source==='demo'?'demo':v.source==='hint'?'hint':'manual'};return n;}catch{return null;}}
function recover(session,level){let s=E.create(level,session.parts,{difficulty:session.mode==='challenge'?'normal':session.difficulty});if(!session.tick)return s;E.start(s);let input={},i=0;while(s.tick<session.tick&&s.status==='running'){while(i<session.inputs.length&&session.inputs[i].tick<=s.tick)input=session.inputs[i++].input;E.step(s,input);}return s;}
return{VERSION,newSession,assist,record,credit,pack,restore,recover};});
