'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),vm=require('node:vm');
const E=require('./engine.js'),S=require('./session.js'),D=require('./definitions.js'),base=path.dirname(__dirname),root=path.dirname(base);const started=Date.now(),counts={witnessWins:0,emptyWitnessFailures:0,invalidWitnessFailures:0,deterministicReplays:0,restartChecks:0,aiTicks:0,independentAssertions:0,provenanceChecks:0,staticFiles:0};const perGame=[];
function test(name,fn){try{fn();console.log('PASS',name);counts.independentAssertions++;}catch(e){console.error('FAIL',name);throw e;}}
function finite(value){if(typeof value==='number')assert.ok(Number.isFinite(value));else if(value&&typeof value==='object')for(const v of Object.values(value))finite(v);}
const inputKeys=new Set(['mx','my','aim','power','spin','loft','p2x','p2y','target','action','p2action','sweep','run']);
function auditReplay(kind,L){const s=E.create(kind,L),w=L.witness;let j=0;for(let tick=0;tick<=L.maxTicks&&s.status==='playing';tick++){let u={};while(j<w.length&&w[j].tick===tick)Object.assign(u,w[j++].input);const old=E.clone(s.q);E.step(s,u);const q=s.q;if(['hockey','pong','badminton','basketball','tennis','volleyball','fencing'].includes(kind)){assert.ok(E.dist(old,q)<=s.aiSpeed+1e-8,kind+' AI teleport at tick '+tick);assert.ok(q.stamina>=0&&q.stamina<=100);counts.aiTicks++;}finite(s);for(const event of s.aiEvents){assert.ok(event.x>=0&&event.x<=1000&&event.y>=0&&event.y<=600);assert.ok(event.stamina>=0&&event.stamina<=100);}}
return s;}
function terminal(s){const L=s.level,b=s.b;switch(s.kind){case'hockey':assert.ok(b.y<25&&Math.abs(b.x-L.goalX)<L.goalWidth/2);break;case'pong':assert.ok(b.x>995);break;case'badminton':assert.ok((b.y>520&&b.x>500)||(s.lastHitter===1&&(b.x<25||b.x>975||Math.abs(b.x-500)<30)));break;case'soccer':assert.ok(b.x>965&&Math.abs(b.y-L.goalY)<L.goalWidth/2&&s.passes>=L.minPasses);break;case'basketball':assert.ok(b.vz<0&&b.z<70&&E.dist(b,s.target)<L.rim);break;case'tennis':assert.ok(s.bounces>=2||s.lastHitter===1);break;case'volleyball':assert.ok(b.y>525&&b.x>500&&s.touches===3);break;case'bowling':assert.ok(s.pins.every(p=>p.fallen));assert.ok(s.rolls.reduce((a,b)=>a+b,0)===s.pins.length);break;case'billiards':assert.ok(b.active&&s.objects.every(p=>!p.active));break;case'curling':assert.ok(b.active&&E.dist(b,s.target)<=L.requiredDistance);assert.ok(s.stones.filter(p=>p.active&&p.team===1).every(p=>E.dist(p,s.target)>E.dist(b,s.target)));break;case'archery':assert.ok(Math.abs(s.lastLanding.y-s.target.y)<=L.bull);break;case'golf':assert.ok(E.dist(b,s.target)<L.holeRadius&&b.vx===0&&b.vy===0&&s.attempts<=L.maxShots);break;case'baseball':assert.ok(s.score>=L.requiredBases&&Math.abs(s.runner-Math.round(s.runner))<.04);break;case'fencing':assert.ok(s.parries>=L.requiredParries&&s.p.attack===0&&s.q.x-s.p.x<=L.reach);break;case'frisbee':assert.ok(E.dist(s.lastLanding,s.target)<L.radius);break;}counts.independentAssertions++;}
for(const d of D){const dir=path.join(base,d.id),L=JSON.parse(fs.readFileSync(path.join(dir,'levels.json'),'utf8'));assert.equal(L.length,100);assert.equal(new Set(L.map(E.fingerprint)).size,100,d.id+' structural duplicates');const script={};vm.runInNewContext(fs.readFileSync(path.join(dir,'levels.js'),'utf8'),{window:script});assert.equal(JSON.stringify(script.SportsLevels),JSON.stringify(L));const entry=fs.readFileSync(path.join(base,d.id+'.html'),'utf8');assert.ok(entry.includes('lang="zh-Hant"'));assert.ok(entry.includes('width=device-width'));for(const m of entry.matchAll(/(?:src|href)="([^"#]+)"/g)){if(!m[1].startsWith('http'))assert.ok(fs.existsSync(path.resolve(base,m[1])),d.id+' missing '+m[1]);}counts.staticFiles+=4;let ticks=0;for(let i=0;i<L.length;i++){const l=L[i];assert.equal(l.id,i+1);assert.ok(l.witness.length>0);let previous=-1,actions=0;for(const e of l.witness){assert.ok(Number.isInteger(e.tick)&&e.tick>previous&&e.tick<=l.maxTicks);previous=e.tick;assert.ok(e.input&&typeof e.input==='object');for(const key of Object.keys(e.input))assert.ok(inputKeys.has(key),key);if(e.input.action)actions++;assert.deepEqual(E.input(e.input),e.input,d.id+' invalid controls '+l.id);}assert.ok(actions>0);const first=E.replay(d.kind,l),second=E.replay(d.kind,l);assert.equal(first.status,'won',d.id+' '+l.id+': '+first.message);assert.deepEqual(second,first);counts.witnessWins++;counts.deterministicReplays++;terminal(first);ticks+=first.tick;const empty=E.replay(d.kind,l,[]);assert.equal(empty.status,'lost',d.id+' empty succeeded '+l.id);counts.emptyWitnessFailures++;const invalid=E.replay(d.kind,l,[{tick:0,input:{action:'__win',status:'won',score:9999}}]);assert.equal(invalid.status,'lost');counts.invalidWitnessFailures++;const restart=E.create(d.kind,l);assert.equal(restart.tick,0);assert.equal(restart.status,'playing');assert.equal(restart.attempts,0);counts.restartChecks++;if(i%10===0){const a=auditReplay(d.kind,l);assert.equal(a.status,'won');}}
perGame.push({id:d.id,kind:d.kind,levels:100,structuralFingerprints:100,legalWitnessWins:100,emptyFailures:100,invalidInputFailures:100,deterministicReplays:100,totalWinningTicks:ticks});console.log('PASS',d.id,'100 wins / 100 empty failures / 100 invalid failures');}
// Independent invariant and rule examples, not outcome-only snapshots.
test('collision exchanges equal-mass normal velocity and conserves momentum',()=>{const a={x:0,y:0,vx:4,vy:2,r:12,active:true},b={x:23,y:0,vx:-2,vy:1,r:12,active:true};const px=a.vx+b.vx,py=a.vy+b.vy,ke=a.vx*a.vx+a.vy*a.vy+b.vx*b.vx+b.vy*b.vy;E.physics.circle(a,b,1);assert.ok(Math.abs(a.vx+b.vx-px)<1e-10);assert.ok(Math.abs(a.vy+b.vy-py)<1e-10);assert.ok(Math.abs(a.vx*a.vx+a.vy*a.vy+b.vx*b.vx+b.vy*b.vy-ke)<1e-10);assert.ok(a.vx<0&&b.vx>0);});
test('wall contact reverses only the normal component',()=>{let b={x:2,y:100,vx:-5,vy:3,r:10};E.physics.rail(b,0,1000,0,600,1);assert.equal(b.x,10);assert.equal(b.vx,5);assert.equal(b.vy,3);});
test('illegal/nonfinite input cannot mutate results',()=>{const a=E.input({aim:Infinity,power:NaN,spin:4,mx:8,action:'win',target:{x:99999,y:-9}});assert.deepEqual(a,{mx:1,spin:1,target:{x:1000,y:0}});});
const sample=k=>JSON.parse(fs.readFileSync(path.join(base,D.find(d=>d.kind===k).id,'levels.json')))[0];
test('racket refuses contact outside reach',()=>{let s=E.create('badminton',sample('badminton'));s.b.x=850;const before=s.p.stamina;E.step(s,{action:'smash'});assert.equal(s.phase,'ready');assert.equal(s.p.stamina,before);});
test('badminton stamina and cooldown constrain repeated smash',()=>{let s=E.create('badminton',sample('badminton'));E.step(s,{action:'smash'});assert.ok(s.p.stamina<70);const cost=s.p.stamina;E.step(s,{action:'smash'});assert.ok(s.p.stamina>=cost);assert.equal(s.contacts,1);});
test('soccer pass is a moving ball and ownership changes only on receipt',()=>{let s=E.create('soccer',sample('soccer'));E.step(s,{action:'pass'});assert.equal(s.owner,-1);assert.equal(s.passes,0);assert.ok(Math.hypot(s.b.vx,s.b.vy)>0);for(let i=0;i<50&&s.owner<0;i++)E.step(s,{});assert.equal(s.owner,1);assert.equal(s.passes,1);});
test('basketball genuine close defender blocks; fake creates opening',()=>{let L=sample('basketball');L.opponent={x:L.player.x+45,y:L.player.y};let s=E.create('basketball',L);E.step(s,{action:'shoot'});assert.equal(s.status,'lost');let f=E.create('basketball',L);E.step(f,{action:'fake'});E.step(f,{action:'shoot'});assert.equal(f.status,'playing');assert.equal(f.phase,'flight');assert.ok(f.q.stun>0);});
test('volleyball requires legal receive/set/spike order and reachable height',()=>{let L=sample('volleyball'),s=E.create('volleyball',L);E.step(s,{action:'spike'});assert.equal(s.touches,0);s.b.y=150;E.step(s,{action:'receive'});assert.equal(s.touches,0);s.b.y=370;E.step(s,{action:'receive'});assert.equal(s.touches,1);E.step(s,{action:'set'});assert.equal(s.touches,1);});
test('bowling official strike/spare/ten-frame bonus score',()=>{assert.equal(E.bowlingScore(Array(12).fill(10)),300);assert.equal(E.bowlingScore(Array(21).fill(5)),150);assert.equal(E.bowlingScore(Array(20).fill(0)),0);assert.equal(E.bowlingScore(Array.from({length:20},(_,i)=>i%2?0:9)),90);});
test('billiards cue scratch loses even with last object potted',()=>{let s=E.create('billiards',sample('billiards'));s.phase='flight';s.b.x=42;s.b.y=42;s.objects.forEach(o=>o.active=false);E.step(s,{});assert.equal(s.status,'lost');});
test('curling sweep reduces friction, and spin changes lateral position',()=>{let L=sample('curling'),a=E.create('curling',L),b=E.create('curling',L),c=E.create('curling',L);for(const s of [a,b,c])E.step(s,{action:'shoot',aim:0,power:40});for(let i=0;i<80;i++){E.step(a,{});E.step(b,{sweep:true});E.step(c,{spin:1});}assert.ok(b.b.x>a.b.x);c=E.create('curling',L);E.step(c,{action:'shoot',aim:0,power:40,spin:1});for(let i=0;i<80;i++)E.step(c,{});assert.ok(Math.abs(c.b.y-a.b.y)>5);});
test('archery wind alters horizontal motion and gravity accelerates downward',()=>{let L=sample('archery');L.wind=0;L.gust=0;L.obstacles=[];let a=E.create('archery',L);L.wind=.08;let b=E.create('archery',L);for(let s of [a,b])E.step(s,{action:'shoot',aim:-25,power:50});let vy=a.b.vy;for(let i=0;i<15;i++){E.step(a,{});E.step(b,{});}assert.ok(a.b.vy>vy);assert.ok(b.b.x>a.b.x);});
test('golf gate moves with tick, water fails, fast ball does not auto-pocket',()=>{let L=sample('golf');L.gates=[{x:450,y:250,w:20,h:80,axis:'y',amplitude:90,rate:.05,phase:0}];let s=E.create('golf',L);E.step(s,{});const y=s.gates[0].currentY;for(let i=0;i<10;i++)E.step(s,{});assert.notEqual(s.gates[0].currentY,y);s.level.water=[{x:s.b.x-20,y:s.b.y-20,w:50,h:50}];E.step(s,{action:'shoot',aim:0,power:80});assert.equal(s.status,'lost');});
test('fencing attacks have windup, reach and stamina limits; parry creates stun',()=>{let L=sample('fencing');L.incoming=0;L.opponent.x=L.player.x+350;let s=E.create('fencing',L,{opponent:'human'});E.step(s,{action:'shoot'});assert.equal(s.status,'playing');assert.ok(s.p.attack>0);for(let i=0;i<40;i++)E.step(s,{});assert.equal(s.status,'playing');let p=E.create('fencing',sample('fencing'));const witness=sample('fencing').witness;for(let i=0;i<50&&p.status==='playing';i++){const e=witness.find(e=>e.tick===i);E.step(p,e?.input||{});}assert.ok(p.parries>=1);assert.ok(p.q.stun>0||p.status==='won');});
test('frisbee spin changes path; low obstruction is cleared only at sufficient altitude',()=>{let L=sample('frisbee');L.obstacles=[];let a=E.create('frisbee',L),b=E.create('frisbee',L);E.step(a,{action:'shoot',aim:0,power:55,loft:40,spin:0});E.step(b,{action:'shoot',aim:0,power:55,loft:40,spin:1});for(let i=0;i<20;i++){E.step(a,{});E.step(b,{});}assert.ok(Math.abs(a.b.y-b.b.y)>10);let c=E.create('frisbee',L);c.level.obstacles=[{x:c.b.x+10,y:c.b.y-20,w:80,h:40,height:999}];E.step(c,{action:'shoot',aim:0,power:55,loft:40});assert.equal(c.phase,'ready');assert.equal(c.attempts,1);});
test('AI difficulty adjusts bounded movement and delayed observations',()=>{let L=sample('pong'),a=E.create('pong',L,{difficulty:'easy'}),b=E.create('pong',L,{difficulty:'hard'});assert.ok(b.aiSpeed>a.aiSpeed);assert.ok(b.aiLatency<a.aiLatency);E.step(a,{action:'shoot',aim:30});const target=E.clone(a.aiTarget);for(let i=0;i<a.aiLatency-1;i++)E.step(a,{});assert.deepEqual(a.aiTarget,target);});
test('demo / hints never award manual completion; save/load keeps provenance',()=>{let p=S.fresh();p=S.record(p,1,{won:true,demo:true,ticks:1});assert.deepEqual(p.manual,[]);assert.deepEqual(p.demos,[1]);p=S.record(p,1,{won:true,ticks:90});assert.deepEqual(p.manual,[]);assert.deepEqual(p.assisted,[1]);p=S.record(p,2,{won:true,ticks:85});assert.deepEqual(p.manual,[2]);p=S.record(p,3,{hint:true});p=S.record(p,3,{won:true,ticks:20});assert.ok(p.assisted.includes(3));p=S.record(p,4,{won:true,mode:'free'});assert.ok(!p.manual.includes(4));const data=new Map(),storage={getItem:k=>data.get(k),setItem:(k,v)=>data.set(k,v)};assert.equal(S.save(storage,'test',p),true);assert.deepEqual(S.load(storage,'test'),p);assert.equal(S.load(storage,'other').manual.length,0);counts.provenanceChecks+=10;});
test('corrupted and disabled storage recover safely',()=>{const store={getItem:()=>'{no',setItem:()=>{throw Error('denied');}};assert.deepEqual(S.load(store,'x'),S.fresh());assert.equal(S.save(store,'x',S.fresh()),false);const p=S.clean({version:1,selected:999,manual:[1,1,0,-2,101,'3'],assisted:'bad',demos:[NaN],best:{2:34,400:4,'hello':5}});assert.deepEqual(p.manual,[1]);assert.equal(p.selected,100);assert.deepEqual(p.best,{'2':34});counts.provenanceChecks+=5;});
test('pause/restart/level/demo browser lifecycle hooks are present',()=>{const source=fs.readFileSync(path.join(__dirname,'ui.js'),'utf8');for(const marker of ['visibilitychange','pointercancel','lostpointercapture','requestAnimationFrame','demoIndex=0','held={}','roundSerial=0','recorded=false','localStorage','if(demo||state.status'])assert.ok(source.includes(marker),marker);assert.ok(!source.includes('setInterval('));assert.ok(!source.includes('fetch('));});
const files=[];for(const d of D){files.push(path.join(base,d.id+'.html'));for(const f of fs.readdirSync(path.join(base,d.id)))if(fs.statSync(path.join(base,d.id,f)).isFile())files.push(path.join(base,d.id,f));}for(const f of fs.readdirSync(__dirname))if(/\.(js|cjs|css|md|json)$/.test(f)&&!['verification-report.json','release-manifest.json'].includes(f))files.push(path.join(__dirname,f));const hashes={};for(const f of [...new Set(files)].sort())hashes[path.relative(root,f)]=crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex');const report={family:'sports120',engineVersion:E.VERSION,generatedAt:new Date().toISOString(),result:'pass',scope:'offline actual-engine witnesses, independent rule/property assertions, legal AI movement, provenance, static file wiring; browser visual QA is separate',durationMs:Date.now()-started,counts,games:perGame,sourceHashes:hashes};fs.writeFileSync(path.join(__dirname,'verification-report.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({result:'pass',durationMs:report.durationMs,counts},null,2));
