(function(root,factory){const U=typeof module==='object'&&module.exports?require('../spatial-common/util.js'):root.SpatialUtil;const E=factory(U);if(typeof module==='object'&&module.exports)module.exports=E;else root.SpatialEngine=E;})(globalThis,function(U){'use strict';

const normals=[[0,0,1],[0,0,-1],[1,0,0],[-1,0,0],[0,1,0],[0,-1,0]],ups=[[0,1,0],[0,1,0],[0,1,0],[0,1,0],[0,0,-1],[0,0,1]];
function fold(frame,d){const{r,u,n}=frame;return d===0?{r,u:U.neg(n),n:u}:d===1?{r:U.neg(n),u,n:r}:d===2?{r,u:n,n:U.neg(u)}:{r:n,u,n:U.neg(r)};}
function frames(l,s){const out={0:{r:[1,0,0],u:[0,1,0],n:[0,0,1]}},queue=[0],errors=[];while(queue.length){const i=queue.shift(),p=s.faces[i];for(let d=0;d<4;d++){const x=p.x+[0,1,0,-1][d],y=p.y+[-1,0,1,0][d],j=s.faces.findIndex(q=>q&&q.x===x&&q.y===y);if(j<0)continue;const f=fold(out[i],d);if(out[j]){if(!U.same(f,out[j]))errors.push('形成環路，無法沿接縫摺成盒子');}else{out[j]=f;queue.push(j);}}}const ns=Object.values(out).map(f=>U.key(f.n));if(new Set(ns).size<ns.length)errors.push('摺起後有面重疊');return{frames:out,errors};}
function arrow(f,r){return [f.u,f.r,U.neg(f.u),U.neg(f.r)][r];}
const E=U.wrapper('cube-nets',{normals,ups,fold,frames,arrow,createState:l=>({faces:[{x:l.anchor[0],y:l.anchor[1],r:0},null,null,null,null,null]}),validateState:(l,s)=>s&&Array.isArray(s.faces)&&s.faces.length===6&&U.same(s.faces[0],{x:l.anchor[0],y:l.anchor[1],r:0})&&s.faces.every(p=>p===null||(p&&U.integer(p.r,0,3)&&l.allowed.some(v=>v[0]===p.x&&v[1]===p.y)))&&new Set(s.faces.filter(Boolean).map(p=>p.x+','+p.y)).size===s.faces.filter(Boolean).length,act(l,s,a){U.demand(U.integer(a.face,1,5),'前面是固定基準。');if(a.type==='remove'){s.faces[a.face]=null;return s;}U.demand(a.type==='place'&&U.integer(a.r,0,3)&&l.allowed.some(p=>p[0]===a.x&&p[1]===a.y));U.demand(!s.faces.some((p,i)=>i!==a.face&&p&&p.x===a.x&&p.y===a.y),'此格已有其他面。');s.faces[a.face]={x:a.x,y:a.y,r:a.r};return s;},inspect(l,s){const f=frames(l,s),v=f.errors.slice();if(Object.keys(f.frames).length<s.faces.filter(Boolean).length)v.push('所有面必須邊對邊連接');for(const [i,frame]of Object.entries(f.frames)){const p=s.faces[i];if(!U.same(frame.n,normals[i])||!U.same(arrow(frame,p.r),ups[i]))v.push('面的位置或箭頭方向與目標立方體不同');}const won=s.faces.every(Boolean)&&!v.length;return{status:won?'won':'playing',goalMet:won,violations:[...new Set(v)]};},describe:(l,a)=>'將「'+['前','後','右','左','上','下'][a.face]+'」面放到 ('+(a.x+1)+','+(a.y+1)+')，箭頭旋轉 '+a.r*90+'°。'});

return E;});
