(function(C){const{act,rng,shuffle,svg,txt}=C;const types=['工具','足跡','時段'],icons=[['⚒','✂','⌕'],['△','○','□'],['☀','◐','☽']];
C.register('silent-investigation',{
roles:['現場員','分析員'],icon:'⌕',color:'#b5becf',intro:'現場員搜查房間，分析員掌握嫌疑人背景。全案只能傳送三個圖示，以交叉證據找出唯一嫌疑人。',help:['現場員搜查場所，找出工具、足跡、時段三種已核實證據。只用三次圖示傳訊，請避開未核實傳聞。','分析員只能看案件資料與已收到的圖示，可用類別圖示請求證據。收齊三類後提名嫌疑人。','現場員核對提名後執行逮捕。AI 分析員不會讀取未傳送現場證據，無需文字聊天或連線。'],
generate(n){const r=rng(n*787),culprit=Math.floor(r()*(4+n%3)),target=Array.from({length:3},()=>Math.floor(r()*3));const suspects=Array.from({length:4+n%3},(_,i)=>{const code=i===culprit?target.slice():Array.from({length:3},()=>Math.floor(r()*3));if(i!==culprit&&code.every((v,k)=>v===target[k]))code[i%3]=(code[i%3]+1)%3;return{name:`代號 ${String.fromCharCode(65+i)}`,code};});const rooms=shuffle([{name:'工坊',type:0,value:target[0],verified:true},{name:'庭院',type:1,value:target[1],verified:true},{name:'鐘樓',type:2,value:target[2],verified:true},{name:'酒館',type:Math.floor(r()*3),value:Math.floor(r()*3),verified:false}],r);return{id:n,suspects,culprit,rooms};},
init(){return{inspected:[],messages:[],request:0,nominee:null};},
observe(s,r){return{messages:s.messages,request:s.request,nominee:s.nominee,...(r===0?{rooms:s.level.rooms.map((q,i)=>({i,name:q.name,...(s.inspected.includes(i)?q:{})})),inspected:s.inspected}:{suspects:s.level.suspects})};},
actions(o){if(o.role===0)return[...o.rooms.map(q=>act('search',`搜查${q.name}`,{i:q.i})),...icons.flatMap((arr,type)=>arr.map((icon,value)=>act('message',`傳 ${types[type]}：${icon}`,{clueType:type,value}))),act('arrest','依提名逮捕')];return[...types.map((t,clueType)=>act('request',`請求${t}圖示`,{clueType})),...o.suspects.map((q,i)=>act('nominate',`提名 ${q.name}`,{i}))];},
step(s,r,a){if(r===0){if(a.type==='search'&&Number.isInteger(a.i)&&s.level.rooms[a.i]){if(!s.inspected.includes(a.i))s.inspected.push(a.i);return{ok:true};}if(a.type==='message'&&s.messages.length<3&&[0,1,2].includes(a.clueType)&&[0,1,2].includes(a.value)){s.messages.push({type:a.clueType,value:a.value});return{ok:true};}if(a.type==='arrest'&&s.nominee!==null&&s.messages.length===3){s.won=s.nominee===s.level.culprit&&[0,1,2].every(t=>s.messages.filter(m=>m.type===t).length===1)&&s.messages.every(m=>m.value===s.level.suspects[s.nominee].code[m.type]&&s.inspected.some(i=>s.level.rooms[i].verified&&s.level.rooms[i].type===m.type&&s.level.rooms[i].value===m.value));s.lost=!s.won;return{ok:true};}}else{if(a.type==='request'&&[0,1,2].includes(a.clueType)){s.request=a.clueType;return{ok:true};}if(a.type==='nominate'&&Number.isInteger(a.i)&&s.level.suspects[a.i]&&s.messages.length===3){s.nominee=a.i;return{ok:true};}}return{ok:false,reason:'請先搜證、用三個圖示完成交叉分析，再提名與逮捕'};},
ai(o){if(o.role===0){if(o.nominee!==null)return act('arrest','依分析員提名逮捕');if(o.messages.length>=3)return null;if(o.messages.some(m=>m.type===o.request))return null;const found=o.rooms.find(q=>q.verified&&q.type===o.request);if(found)return act('message','只傳送核實證據',{clueType:found.type,value:found.value});const room=o.rooms.find(q=>!o.inspected.includes(q.i));return room?act('search','搜查尚未檢驗場所',{i:room.i}):null;}for(let t=0;t<3;t++)if(!o.messages.some(m=>m.type===t))return o.request===t?null:act('request','請求缺少的證據',{clueType:t});if(o.nominee!==null)return null;const candidates=o.suspects.map((q,i)=>({q,i})).filter(({q})=>o.messages.every(m=>q.code[m.type]===m.value));return candidates.length===1?act('nominate','依三項交叉證據提名',{i:candidates[0].i}):null;},
view(o){let b=txt(280,35,'三格密訊　'+o.messages.map(m=>icons[m.type][m.value]).join('　')+'　□'.repeat(3-o.messages.length),24);if(o.role===0){o.rooms.forEach((q,i)=>{const x=55+(i%2)*245,y=65+Math.floor(i/2)*118;b+=`<rect x="${x}" y="${y}" width="205" height="95" rx="12" fill="#394858"/>`+txt(x+102,y+30,q.name,20)+txt(x+102,y+68,q.verified===undefined?'尚未搜查':`${q.verified?'已核實':'傳聞'} ${types[q.type]} ${icons[q.type][q.value]}`,18);});}else o.suspects.forEach((q,i)=>{const y=74+i*34;b+=txt(130,y,q.name,18)+txt(340,y,q.code.map((v,k)=>icons[k][v]).join('　'),23);});return svg(b);},status:o=>`已傳 ${o.messages.length}/3 個圖示 · 請求：${types[o.request]} · ${o.nominee===null?'尚未提名':`提名代號 ${String.fromCharCode(65+o.nominee)}`}`
});})(typeof module!=='undefined'?require('../coop120-common/core.js'):CoopCore);
