(function(){
'use strict';
const E=window.GameEngine,S=window.GameSession,L=window.GAME_LEVELS,$=id=>document.getElementById(id),TANGRAM=E.kind==='tangram',KEY='arcade.'+(TANGRAM?'tangram':'mahjong-solitaire')+'.v1';
let raw=null;try{raw=localStorage.getItem(KEY)}catch{}const loaded=S.load(raw,L,E);let data=loaded.data,level=L[data.index],state=E.replay(level,data.actions),preview=null,pending=null,message='',hintData=null;
function time(n){return Math.floor(n/60)+':'+String(n%60).padStart(2,'0')}
function save(){try{localStorage.setItem(KEY,JSON.stringify(data));$('save').textContent='進度保存在此瀏覽器'+(data.assisted?' · 本局使用輔助':'')}catch{$('save').textContent='目前無法儲存；仍可遊玩，關閉後進度可能遺失'}}
function blocked(){return !!preview||!!pending||$('helpDialog').open}
function normal(){return TANGRAM?'先選一片，再點剪影放下；也可以拖曳拼片':'先選一張自由牌，再選相同圖案的另一張'}
function render(){const shown=preview?preview.state:state,won=E.won(level,shown);$('remaining').textContent=TANGRAM?shown.filter(Boolean).length+' / 7':shown.filter(x=>!x).length;$('moves').textContent=data.actions.length;$('timer').textContent=time(data.seconds);$('progress').textContent=Object.keys(data.completed).length+' / 50';$('progressBar').style.width=(Object.keys(data.completed).length*2)+'%';$('boardTitle').textContent='第 '+String(data.index+1).padStart(2,'0')+' 關 · '+level.name;$('badge').textContent=preview?'解答觀摩 · 不計過關':TANGRAM?'七片標準形狀 · 合法拼法皆可':level.layers+' 層 · '+E.pairs(level,state).length+' 對可取';$('level').replaceChildren();for(let i=0;i<L.length;i++){const o=document.createElement('option');o.value=String(i);o.textContent=String(i+1).padStart(2,'0')+' · '+L[i].name+(data.completed[i]?' ✓':'');$('level').append(o)}$('level').value=String(data.index);$('levelInfo').textContent=TANGRAM?'剪影 '+level.width+' × '+level.height+' · 標準總面積 32\n旋轉、鏡射與平移去重的完整拼圖':level.tiles.length+' 張牌 · '+level.layers+' 層 · '+level.solution.length+' 對\n完整合法配對證明，初始保證可解';$('undo').disabled=!!preview||!data.actions.length;$('restart').disabled=!!preview;$('next').disabled=!!preview||data.index===49;$('level').disabled=!!preview;$('hint').disabled=!!preview||E.won(level,state);$('solution').hidden=!!preview;$('solution').disabled=E.won(level,state);for(const id of ['pause','step','stop'])$(id).hidden=!preview;$('pause').disabled=!!preview&&preview.done;$('step').disabled=!!preview&&preview.done;$('pause').textContent=preview&&preview.paused?'繼續':'暫停';$('win').hidden=!(won&&(preview?preview.done:true));if(won){$('winTitle').textContent=preview?'解答觀摩完成':TANGRAM?'七片歸位，形狀完整。':'層層鬆開，牌桌清空。';$('winDetail').textContent=preview?'沒有計入過關，原本棋局完整保留':data.actions.length+' 步 · '+time(data.seconds)+' · '+(data.assisted?'使用輔助':'自力完成')}const best=data.completed[data.index];$('best').textContent=best?'最佳：'+best.actions.length+' 步 · '+time(best.seconds)+' · '+(best.assisted?'使用輔助':'自力完成'):'最佳紀錄：尚未完成';drawBoard(shown);$('status').textContent=message;}
function action(a){if(blocked()||E.won(level,state))return false;if(!E.legal(level,state,a))return false;if(data.actions.length>=20000){message='保存步數已達上限，請復原或重新開始';render();return false}state=E.step(level,state,a);data.actions.push(JSON.parse(JSON.stringify(a)));hintData=null;afterAction();const won=S.record(data,level,E);message=won?'完成！可以復原回想，或前往下一關':normal();save();render();return true}
function ask(text,fn){if(pending)return;pending=fn;$('confirmText').textContent=text;$('confirmDialog').showModal()}
function choose(index){if(blocked()||!Number.isInteger(index)||!L[index]||index===data.index)return;const run=()=>{data=S.fresh(index,data.completed);level=L[index];state=E.initial(level);hintData=null;resetSelection();message=normal();save();render()};if(data.actions.length&&!E.won(level,state))ask('換關會清除目前尚未完成的走法；已完成紀錄會保留。',run);else run()}
$('level').addEventListener('change',()=>{const n=Number($('level').value);$('level').value=String(data.index);choose(n)});$('next').addEventListener('click',()=>choose(data.index+1));
$('restart').addEventListener('click',()=>{if(blocked())return;const run=()=>{data=S.fresh(data.index,data.completed);state=E.initial(level);hintData=null;resetSelection();message='已重新開始，慢慢想，不用急';save();render()};if(data.actions.length||data.assisted)ask('本局走法、時間與輔助標記會歸零；完成紀錄會保留。',run);else run()});
$('cancelConfirm').addEventListener('click',()=>{pending=null;$('confirmDialog').close()});$('confirmDialog').addEventListener('cancel',()=>{pending=null});$('confirmDialog').addEventListener('close',()=>{pending=null});$('acceptConfirm').addEventListener('click',()=>{const f=pending;pending=null;$('confirmDialog').close();if(f)f()});
$('undo').addEventListener('click',()=>{if(blocked()||!data.actions.length)return;data.actions.pop();state=E.replay(level,data.actions);hintData=null;resetSelection();message='已復原一步；已驗證的完成紀錄會保留';save();render()});
$('hint').addEventListener('click',()=>{if(blocked()||E.won(level,state))return;data.assisted=true;showHint();save();render()});
function schedule(){if(preview&&!preview.paused&&!preview.done)preview.timer=setTimeout(tick,700)}
function tick(){if(!preview||preview.done)return;preview.timer=null;preview.state=E.step(level,preview.state,level.solution[preview.pos]);preview.pos++;preview.done=preview.pos===level.solution.length;message=preview.done?'觀摩完成；按「返回自己的棋局」繼續原本進度':'觀摩 '+preview.pos+' / '+level.solution.length+'；原本走法與時間不變';render();schedule()}
function stopPreview(text='已返回自己的棋局，盤面、走法與時間都保留'){if(!preview)return;clearTimeout(preview.timer);preview=null;message=text;render();save()}
$('solution').addEventListener('click',()=>{if(blocked()||E.won(level,state))return;data.assisted=true;preview={state:E.initial(level),pos:0,done:false,paused:false,timer:null};message='從關卡起點觀摩完整解答；你的棋局會完整保留';save();render();schedule()});
$('pause').addEventListener('click',()=>{if(!preview||preview.done)return;preview.paused=!preview.paused;clearTimeout(preview.timer);preview.timer=null;message=preview.paused?'觀摩已暫停；可單步或返回自己的棋局':'繼續觀摩；原本進度不變';render();schedule()});$('step').addEventListener('click',()=>{if(!preview||preview.done)return;clearTimeout(preview.timer);preview.paused=true;tick()});$('stop').addEventListener('click',()=>stopPreview());
$('help').addEventListener('click',()=>{if(preview){clearTimeout(preview.timer);preview.paused=true;render()}$('helpDialog').showModal()});$('closeHelp').addEventListener('click',()=>$('helpDialog').close());
$('home').addEventListener('click',ev=>{if(preview)stopPreview();if(data.actions.length&&!E.won(level,state)){ev.preventDefault();ask('棋局已自動保存在此瀏覽器。要返回遊戲大廳嗎？',()=>{save();window.location.href=$('home').getAttribute('href')})}});
setInterval(()=>{if(!document.hidden&&!blocked()&&!E.won(level,state)){data.seconds++;$('timer').textContent=time(data.seconds);if(data.seconds%5===0)save()}},1000);document.addEventListener('visibilitychange',()=>{if(document.hidden){if(preview)stopPreview('頁面進入背景，已停止觀摩並保留原本棋局');save()}});window.addEventListener('pagehide',save);
let selected=null,pose={x:0,y:0,r:0,f:false},drag=null,suppressClick=false;
const COLORS=['#bf7659','#dba164','#b29b65','#64887c','#7994a1','#8e809a','#6b7a53'],NAMES=['大三角 A','大三角 B','中三角','小三角 A','小三角 B','正方形','平行四邊'];
function svg(tag,attrs={}){const e=document.createElementNS('http://www.w3.org/2000/svg',tag);for(const[k,v]of Object.entries(attrs))e.setAttribute(k,String(v));return e}
function points(p){return p.map(a=>a.join(',')).join(' ')}function center(poly){return [poly.reduce((a,p)=>a+p[0],0)/poly.length,poly.reduce((a,p)=>a+p[1],0)/poly.length]}
function resetSelection(){selected=null;pose={x:0,y:0,r:0,f:false};drag=null}function afterAction(){drag=null}
function selectPiece(i){if(blocked())return;selected=i;pose=state[i]?{...state[i]}:{x:0,y:0,r:0,f:false};hintData=null;message='已選 '+NAMES[i]+'；旋轉、翻面，再放入剪影';render();$('board').focus({preventScroll:true})}
function drawBoard(shown){const board=$('board');board.setAttribute('viewBox','-2 -2 '+(level.width+4)+' '+(level.height+4));board.replaceChildren();for(let x=0;x<=level.width;x++)for(let y=0;y<=level.height;y++)board.append(svg('circle',{cx:x,cy:y,r:.025,class:'grid-dot'}));for(const poly of level.target)board.append(svg('polygon',{points:points(poly),class:'target'}));for(const[a,b]of level.boundary)board.append(svg('line',{x1:a[0],y1:a[1],x2:b[0],y2:b[1],class:'target-outline'}));for(let i=0;i<7;i++)if(shown[i]){const poly=E.polygon(i,shown[i]),p=svg('polygon',{points:points(poly),fill:COLORS[i],class:'placed'+(!preview&&selected===i?' selected-piece':''),'data-piece':i,role:'img','aria-label':NAMES[i]+'，已放入'});p.dataset.piece=String(i);board.append(p);const c=center(poly),t=svg('text',{x:c[0],y:c[1],class:'piece-label'});t.textContent=String(i+1);board.append(t)}if(!preview&&hintData)board.append(svg('polygon',{points:points(E.polygon(hintData.i,hintData.p)),class:'hint-shape'}));if(!preview&&selected!==null&&!E.won(level,state)){const reason=E.reason(level,state,selected,pose);board.append(svg('polygon',{points:points(E.polygon(selected,pose)),class:'ghost'+(reason?' invalid':'')}));board.append(svg('path',{d:'M '+(pose.x-.16)+' '+pose.y+' h .32 M '+pose.x+' '+(pose.y-.16)+' v .32',class:'anchor'}))}$('tray').replaceChildren();for(let i=0;i<7;i++){const b=document.createElement('button');b.className='piece-button'+(selected===i&&!preview?' active':'')+(shown[i]?' placed-button':'');b.dataset.piece=String(i);b.setAttribute('aria-label',(i+1)+' '+NAMES[i]+(shown[i]?'，已放置，可移動':'，尚未放置'));b.setAttribute('aria-pressed',String(selected===i&&!preview));b.disabled=!!preview;const icon=svg('svg',{viewBox:'-2.2 -.2 6.4 4.4','aria-hidden':'true'});icon.append(svg('polygon',{points:points(E.BASE[i]),fill:COLORS[i]}));const label=document.createElement('span');label.textContent=String(i+1)+' '+NAMES[i];b.append(icon,label);b.addEventListener('click',()=>{if(suppressClick){suppressClick=false;return}selectPiece(i)});b.addEventListener('pointerdown',ev=>{if(blocked())return;selectPiece(i);beginDrag(ev,false)});$('tray').append(b)}for(const id of ['rotateLeft','rotateRight','flip','remove'])$(id).disabled=!!preview||selected===null||E.won(level,state);$('remove').disabled=!!preview||selected===null||!state[selected]||E.won(level,state)}
function boardPoint(ev){const r=$('board').getBoundingClientRect(),w=level.width+4,h=level.height+4,scale=Math.min(r.width/w,r.height/h);return [(ev.clientX-r.left-(r.width-w*scale)/2)/scale-2,(ev.clientY-r.top-(r.height-h*scale)/2)/scale-2]}
function centerAt(point){const c=center(E.polygon(selected,{...pose,x:0,y:0}));pose.x=Math.round((point[0]-c[0])*2)/2;pose.y=Math.round((point[1]-c[1])*2)/2}
function commit(){if(blocked()||selected===null||E.won(level,state))return;const why=E.reason(level,state,selected,pose);if(why){message=why+'；調整位置或方向後再放下';render();return}if(state[selected]&&E.equivalent(selected,state[selected],pose)){message='這片已在相同位置；可改選另一片';render();return}action({i:selected,p:{...pose}})}
function transform(kind){if(blocked()||selected===null||E.won(level,state))return;const c=center(E.polygon(selected,pose));if(kind==='flip')pose.f=!pose.f;else pose.r=(pose.r+(kind==='left'?7:1))%8;centerAt(c);hintData=null;message='預覽 '+NAMES[selected]+' · '+(pose.r*45)+'°'+(pose.f?' · 已翻面':'')+'；按棋盤或 Enter 確認放下';render();$('board').focus({preventScroll:true})}
$('rotateLeft').addEventListener('click',()=>transform('left'));$('rotateRight').addEventListener('click',()=>transform('right'));$('flip').addEventListener('click',()=>transform('flip'));$('remove').addEventListener('click',()=>{if(selected!==null&&state[selected])action({i:selected,p:null})});
function beginDrag(ev,onBoard){if(ev.button!==undefined&&ev.button!==0)return;drag={x:ev.clientX,y:ev.clientY,moved:false,onBoard};try{if(ev.pointerId!==undefined)$('board').setPointerCapture(ev.pointerId)}catch{}if(ev.preventDefault)ev.preventDefault()}
$('board').addEventListener('pointerdown',ev=>{if(blocked()||E.won(level,state))return;const i=ev.target&&ev.target.dataset?ev.target.dataset.piece:undefined;if(i!==undefined){selectPiece(Number(i));beginDrag(ev,true)}else if(selected!==null){centerAt(boardPoint(ev));beginDrag(ev,false);drawBoard(state)}});
window.addEventListener('pointermove',ev=>{if(!drag||blocked()||selected===null)return;if(Math.hypot(ev.clientX-drag.x,ev.clientY-drag.y)>5)drag.moved=true;if(drag.moved){centerAt(boardPoint(ev));drawBoard(state)}});
window.addEventListener('pointerup',ev=>{if(!drag)return;const d=drag;drag=null;if(blocked())return;const r=$('board').getBoundingClientRect(),inside=ev.clientX>=r.left&&ev.clientX<=r.left+r.width&&ev.clientY>=r.top&&ev.clientY<=r.top+r.height;if(inside&&(d.moved||!d.onBoard)){centerAt(boardPoint(ev));commit()}suppressClick=true;setTimeout(()=>{suppressClick=false},0)});window.addEventListener('pointercancel',()=>{drag=null;render()});
$('board').addEventListener('click',ev=>{if(suppressClick){suppressClick=false;return}if(blocked()||E.won(level,state))return;const i=ev.target&&ev.target.dataset?ev.target.dataset.piece:undefined;if(i!==undefined){selectPiece(Number(i));return}if(selected!==null){centerAt(boardPoint(ev));commit()}});
$('board').addEventListener('keydown',ev=>{if(blocked()||E.won(level,state))return;if(/^[1-7]$/.test(ev.key)){ev.preventDefault();selectPiece(Number(ev.key)-1);return}if(selected===null)return;const deltas={ArrowLeft:[-.5,0],ArrowRight:[.5,0],ArrowUp:[0,-.5],ArrowDown:[0,.5]};if(deltas[ev.key]){ev.preventDefault();pose.x+=deltas[ev.key][0];pose.y+=deltas[ev.key][1];hintData=null;drawBoard(state);message='定位 '+NAMES[selected]+'；Enter 放下';$('status').textContent=message}else if(ev.key==='Enter'||ev.key===' '){ev.preventDefault();commit()}else if(ev.key.toLowerCase()==='q'){ev.preventDefault();transform('left')}else if(ev.key.toLowerCase()==='e'){ev.preventDefault();transform('right')}else if(ev.key.toLowerCase()==='f'){ev.preventDefault();transform('flip')}else if(ev.key==='Delete'||ev.key==='Backspace'){ev.preventDefault();if(state[selected])action({i:selected,p:null})}else if(ev.key==='Escape'){selected=null;hintData=null;render()}});
function showHint(){const ref=level.solution.find(a=>!state[a.i]||!E.equivalent(a.i,state[a.i],a.p));if(!ref){message='你的拼法已符合參考解';return}hintData={i:ref.i,p:{...ref.p}};selected=ref.i;pose={...ref.p};const why=E.reason(level,state,ref.i,ref.p);message='提示：虛線是 '+NAMES[ref.i]+' 的參考位置'+(why?'；與目前拼法衝突，需要先調整其他片':'；按 Enter 可放入，或自行調整')+'。不限制其他合法解';$('board').focus({preventScroll:true})}

S.record(data,level,E);message=loaded.bad?'部分存檔未通過合法性驗證，已安全恢復':data.actions.length?'已還原上次棋局，接著慢慢想':normal();render();save();
})();
