'use strict';
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const L=require('./levels.json'),E=require('./engine.js'),S=require('./session.js'),slug=path.basename(__dirname),T=slug==='tangram',KEY='arcade.'+slug+'.v1';
function setup(raw=null,disabled=false){
 const els=new Map(),timers=new Map(),storage=new Map();let tid=0;
 const doc={hidden:false,activeElement:null,handlers:{},getElementById:id=>els.get(id),createElement:tag=>new El(tag),createElementNS:(ns,tag)=>new El(tag),addEventListener(k,f){(this.handlers[k]??=[]).push(f)},fire(k){for(const f of this.handlers[k]??[])f()}};
 class El{constructor(tag){this.tagName=tag.toUpperCase();this.children=[];this.dataset={};this.attrs={};this.handlers={};this.style={setProperty(k,v){this[k]=v}};this.disabled=false;this.hidden=false;this.open=false;this.value='';this._text='';}set textContent(v){this._text=String(v);this.children=[]}get textContent(){return this._text+this.children.map(c=>c.textContent).join('')}append(...c){this.children.push(...c)}replaceChildren(...c){this.children=c;this._text=''}setAttribute(k,v){this.attrs[k]=String(v);if(k.startsWith('data-'))this.dataset[k.slice(5)]=String(v)}getAttribute(k){return this.attrs[k]??null}addEventListener(k,f){(this.handlers[k]??=[]).push(f)}fire(k,extra={}){if(this.disabled&&k==='click')return;for(const f of this.handlers[k]??[])f({target:this,preventDefault(){},...extra})}focus(){doc.activeElement=this}showModal(){this.open=true}close(){this.open=false;this.fire('close')}getBoundingClientRect(){return{left:0,top:0,width:600,height:360}}querySelectorAll(sel){const out=[];function walk(n){for(const c of n.children){if(sel==='button'&&c.tagName==='BUTTON'||sel==='polygon'&&c.tagName==='POLYGON')out.push(c);walk(c)}}walk(this);return out}querySelector(s){const m=/\[data-(\w+)="([^"]*)"\]/.exec(s);if(!m)return null;const find=n=>{for(const c of n.children){if(c.dataset[m[1]]===m[2])return c;const q=find(c);if(q)return q}return null};return find(this)}}
 const html=fs.readFileSync(path.join(__dirname,'..',slug+'.html'),'utf8');for(const m of html.matchAll(/<([a-z]+)[^>]*\bid="([^"]+)"[^>]*>/g)){const e=new El(m[1]);e.id=m[2];const href=/href="([^"]+)"/.exec(m[0]);if(href)e.setAttribute('href',href[1]);els.set(e.id,e)}if(raw!==null)storage.set(KEY,raw);
 const winHandlers={};const context={console,document:doc,location:{href:''},addEventListener(k,f){(winHandlers[k]??=[]).push(f)},setInterval:(f,ms)=>{timers.set(++tid,{f,ms,repeat:true});return tid},setTimeout:(f,ms)=>{timers.set(++tid,{f,ms,repeat:false});return tid},clearTimeout:id=>timers.delete(id),localStorage:{getItem:k=>{if(disabled)throw Error();return storage.get(k)||null},setItem:(k,v)=>{if(disabled)throw Error();storage.set(k,v)}}};context.window=context;vm.createContext(context);for(const f of ['levels.js','engine.js','session.js','app.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,f),'utf8'),context,{filename:f});
 return{get:id=>els.get(id),click:id=>els.get(id).fire('click'),key:k=>els.get('board').fire('keydown',{key:k}),saved:()=>JSON.parse(storage.get(KEY)),raw:()=>storage.get(KEY),doc,context,winFire(k,ev={}){for(const f of winHandlers[k]??[])f(ev)},tile:i=>els.get('board').querySelector('[data-tile="'+i+'"]'),piece:i=>els.get('tray').querySelector('[data-piece="'+i+'"]'),advance(){for(const[id,t]of[...timers])if(!t.repeat){timers.delete(id);t.f()}},tick(){for(const t of timers.values())if(t.repeat)t.f()},timerCount:()=>[...timers.values()].filter(t=>!t.repeat).length};
}
function fresh(i=0){return JSON.stringify(S.fresh(i))}
function clickPoint(ui,l,p){const w=l.width+4,h=l.height+4,scale=Math.min(600/w,360/h);ui.get('board').fire('click',{clientX:(p[0]+2)*scale+(600-w*scale)/2,clientY:(p[1]+2)*scale+(360-h*scale)/2})}
function move(ui,l,a){if(!T){ui.tile(a[0]).fire('click');ui.tile(a[1]).fire('click')}else{ui.piece(a.i).fire('click');for(let k=0;k<a.p.r;k++)ui.click('rotateRight');if(a.p.f)ui.click('flip');const poly=E.polygon(a.i,a.p),c=[poly.reduce((s,p)=>s+p[0],0)/poly.length,poly.reduce((s,p)=>s+p[1],0)/poly.length];clickPoint(ui,l,c)}}
assert.equal(L.length,50);let total=0;
for(let i=0;i<50;i++){const l=L[i];let s=E.initial(l);for(const a of l.solution){assert(E.legal(l,s,a));s=E.step(l,s,a);total++}assert(E.won(l,s));if(T){const swapped=s.map(x=>({...x}));[swapped[0],swapped[1]]=[swapped[1],swapped[0]];[swapped[3],swapped[4]]=[swapped[4],swapped[3]];assert(E.won(l,swapped),'must accept same-shape swaps');for(let j=0;j<7;j++)for(let r=0;r<8;r++)for(const f of[false,true])assert(Math.abs(E.area(E.polygon(j,{x:1,y:2,r,f}))-E.AREAS[j])<1e-7)}else{assert.equal(E.solve(l,E.initial(l)).route.length,l.solution.length);assert(!E.legal(l,E.initial(l),[0,0]))}}
// Real DOM handlers: every witness, including rotation, flip and click placement.
for(let i=0;i<50;i++){const ui=setup(fresh(i));for(const a of L[i].solution)move(ui,L[i],a);assert(!ui.get('win').hidden,'win '+i);assert(ui.saved().completed[i],'record '+i);assert.equal(ui.saved().actions.length,L[i].solution.length);assert(!ui.saved().assisted,'manual witness must be unassisted')}
let ui=setup();assert.equal(ui.get('level').children.length,50);move(ui,L[0],L[0].solution[0]);assert.equal(ui.saved().actions.length,1);ui.click('undo');assert.equal(ui.saved().actions.length,0);ui.click('hint');assert(ui.saved().assisted);assert.equal(ui.saved().actions.length,0);assert.match(ui.get('status').textContent,/提示/);
// Preview never writes its board, advances player's timer, or awards a completion.
for(const index of[0,49]){ui=setup(fresh(index));move(ui,L[index],L[index].solution[0]);ui.tick();ui.click('hint');const actions=JSON.stringify(ui.saved().actions),secs=ui.saved().seconds;ui.click('solution');assert(ui.get('level').disabled);ui.advance();ui.click('pause');const msg=ui.get('status').textContent;ui.advance();assert.equal(ui.get('status').textContent,msg);ui.tick();assert.equal(ui.saved().seconds,secs);ui.click('step');assert.match(ui.get('status').textContent,/觀摩/);ui.click('pause');for(let j=0;j<100;j++)ui.advance();assert.equal(ui.get('winTitle').textContent,'解答觀摩完成');assert.equal(JSON.stringify(ui.saved().actions),actions);assert.equal(Object.keys(ui.saved().completed).length,0);ui.click('stop');assert(ui.get('win').hidden);assert.equal(JSON.stringify(ui.saved().actions),actions);assert.equal(ui.timerCount(),0);assert(!ui.get('level').disabled)}
// Mid-preview stop prevents late callbacks and preserves progress.
ui=setup();ui.click('solution');ui.advance();ui.click('stop');const prior=ui.raw();ui.advance();assert.equal(ui.raw(),prior);
// Restart and level chooser confirmations; Cancel and Escape preserve moves.
ui=setup();move(ui,L[0],L[0].solution[0]);ui.click('restart');assert(ui.get('confirmDialog').open);ui.click('cancelConfirm');assert.equal(ui.saved().actions.length,1);ui.click('restart');ui.get('confirmDialog').fire('cancel');ui.get('confirmDialog').close();assert.equal(ui.saved().actions.length,1);ui.get('level').value='49';ui.get('level').fire('change');assert.equal(ui.get('level').value,'0');ui.click('acceptConfirm');assert.equal(ui.saved().index,49);assert(ui.get('next').disabled);move(ui,L[49],L[49].solution[0]);ui.click('restart');ui.click('acceptConfirm');assert.equal(ui.saved().actions.length,0);
// Completion witnesses survive undo/reload, but forged records do not.
ui=setup();for(const a of L[0].solution)move(ui,L[0],a);ui.click('undo');assert(ui.get('win').hidden);assert(ui.saved().completed[0]);let restored=setup(ui.raw());assert.equal(restored.saved().actions.length,L[0].solution.length-1);const forged=restored.saved();forged.completed[0].actions=[];restored=setup(JSON.stringify(forged));assert.equal(Object.keys(restored.saved().completed).length,0);assert.match(restored.get('status').textContent,/驗證/);
// Background/help pause; storage denial and corrupt data are nonfatal.
ui=setup();ui.tick();ui.click('help');ui.tick();assert.equal(ui.get('timer').textContent,'0:01');ui.click('closeHelp');ui.click('solution');ui.doc.hidden=true;ui.doc.fire('visibilitychange');assert(!ui.get('solution').hidden);ui.tick();assert.equal(ui.get('timer').textContent,'0:01');ui.doc.hidden=false;ui.tick();assert.equal(ui.get('timer').textContent,'0:02');
for(const raw of['{bad',JSON.stringify({...S.fresh(),actions:[T?{i:0,p:{x:99,y:99,r:0,f:false}}:[0,0]]})]){ui=setup(raw);assert.equal(ui.saved().actions.length,0);assert.match(ui.get('status').textContent,/驗證/)}ui=setup(null,true);assert.match(ui.get('save').textContent,/無法儲存/);move(ui,L[0],L[0].solution[0]);assert.equal(ui.get('moves').textContent,'1');
// Unfinished home navigation is explicitly confirmed.
ui=setup();move(ui,L[0],L[0].solution[0]);ui.click('home');ui.click('cancelConfirm');assert.equal(ui.context.location.href,'');ui.click('home');ui.click('acceptConfirm');assert.equal(ui.context.location.href,'../index.html');
if(T){ui=setup();ui.key('7');ui.click('hint');ui.key('Enter');assert.equal(ui.saved().actions.length,1);ui.key('Delete');assert.equal(ui.saved().actions.length,2);assert.equal(E.replay(L[0],ui.saved().actions).filter(Boolean).length,0);ui.key('Escape');ui.key('1');ui.key('ArrowRight');ui.key('q');ui.key('e');ui.key('f');assert.equal(ui.saved().actions.length,2);assert(!E.legal(L[0],E.initial(L[0]),{i:0,p:{x:-99,y:-99,r:0,f:false}}));assert(E.intersection([[0,0],[2,0],[0,2]],[[2,0],[4,0],[2,2]])<1e-8);assert(Math.abs(E.intersection([[0,0],[2,0],[0,2]],[[1,0],[3,0],[1,2]])-.5)<1e-8)}else{ui=setup();const blocked=L[0].tiles.find(t=>!E.free(L[0],E.initial(L[0]),t.id));ui.tile(blocked.id).fire('click');assert.equal(ui.saved().actions.length,0);assert.match(ui.get('status').textContent,/夾住|壓住/);const a=L[0].solution[0];ui.tile(a[0]).fire('click');ui.tile(a[0]).fire('click');assert.equal(ui.saved().actions.length,0);ui.tile(a[0]).focus();ui.key('ArrowRight');assert(ui.doc.activeElement);ui.key('Escape')}

// Pointer lifecycle: tray drag, captured pointer, immediate click suppression, invalid drop.
if(T){
 ui=setup();const a=L[0].solution[0],poly=E.polygon(a.i,a.p),c=[poly.reduce((s,p)=>s+p[0],0)/poly.length,poly.reduce((s,p)=>s+p[1],0)/poly.length],w=L[0].width+4,h=L[0].height+4,scale=Math.min(600/w,360/h),at={clientX:(c[0]+2)*scale+(600-w*scale)/2,clientY:(c[1]+2)*scale+(360-h*scale)/2,pointerId:2};
 let captured=null;ui.get('board').setPointerCapture=id=>{captured=id};ui.piece(a.i).fire('pointerdown',{clientX:100,clientY:400,pointerId:2,button:0});assert.equal(captured,2);ui.winFire('pointermove',at);ui.winFire('pointerup',at);assert.equal(ui.saved().actions.length,1);ui.get('board').fire('click',at);assert.equal(ui.saved().actions.length,1);ui.advance();
 const original=JSON.stringify(ui.saved().actions),placed=ui.get('board').querySelector('[data-piece="'+a.i+'"]');ui.get('board').fire('pointerdown',{...at,target:placed,button:0});ui.winFire('pointermove',{clientX:1,clientY:1});ui.winFire('pointerup',{clientX:1,clientY:1});ui.get('board').fire('click',{clientX:1,clientY:1});assert.equal(JSON.stringify(ui.saved().actions),original);assert.match(ui.get('status').textContent,/超出/);ui.advance();
 ui.piece(1).fire('pointerdown',{clientX:100,clientY:400,pointerId:3,button:0});ui.winFire('pointerup',{clientX:100,clientY:400});assert.equal(JSON.stringify(ui.saved().actions),original);ui.advance();
}
console.log('PASS '+slug+': 50 independent runtime witness replays ('+total+' steps), 50 manual DOM wins, alternate fits/rules, non-destructive hints/preview/pause/step/stop, undo/reload, validated saves, confirmation cancellation, keyboard, disabled storage and background timers');
