'use strict';
// Real app.js with a deterministic Web Audio/DOM mock; no browser or physical audio claim.
const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),path=require('path'),crypto=require('crypto'),C=require('./core.js'),Session=require('./session.js'),manifest=require('./release-manifest.json');
const root=path.resolve(__dirname,'../..'),hash=x=>crypto.createHash('sha256').update(x).digest('hex');require('../sonar-submarine/model.js');for(const[p,v]of Object.entries(manifest.sourceFiles))assert.equal(hash(fs.readFileSync(path.join(root,p))),v,`Source changed after seal: ${p}`);
async function harness({deferred=false}={}){const nodes=new Map(),events={},intervals=[],contexts=[];let now=0;
class Element{constructor(tag='div',id=''){this.tagName=tag.toUpperCase();this.id=id;this.dataset={};this.listeners={};this.value=id==='mode'?'solo':id==='human'?'0':'';this.checked=id==='auto';this.children=[];this.style={setProperty(){}};}set innerHTML(v){this._html=String(v);for(const id of this.children)nodes.delete(id);this.children=[];for(const m of this._html.matchAll(/<([a-z][a-z0-9]*)\b[^>]*\bid="([^"]+)"[^>]*>/g)){nodes.set(m[2],new Element(m[1],m[2]));this.children.push(m[2]);}this.p=this._html.includes('<p')?new Element('p'):null;}get innerHTML(){return this._html;}addEventListener(t,f){(this.listeners[t]??=[]).push(f);}querySelector(t){return t==='p'?this.p:null;}fire(t){for(const f of this.listeners[t]||[])f({target:this});if(t==='click')this.onclick?.();}}
class AudioContext{constructor(){this.currentTime=10;this.destination={};this.state='running';this.oscs=[];this.gains=[];this.closeCalls=0;this.resumeCalls=0;this.rejectResume=null;contexts.push(this);}resume(){this.resumeCalls++;if(deferred)return new Promise((resolve,reject)=>{this.resolveResume=resolve;this.rejectResume=reject;});return Promise.resolve();}close(){this.closeCalls++;this.state='closed';return Promise.resolve();}createOscillator(){const oscillator={frequency:{value:0},stops:[],disconnects:0,connect(n){return n;},start(t){this.started=t;},stop(t){this.stops.push(t);},disconnect(){this.disconnects++;}};this.oscs.push(oscillator);return oscillator;}createGain(){const gain={gain:{events:[],setValueAtTime(v,t){this.events.push(['set',v,t]);},exponentialRampToValueAtTime(v,t){this.events.push(['ramp',v,t]);},cancelScheduledValues(t){this.events.push(['cancel',t]);}},disconnects:0,connect(n){return n;},disconnect(){this.disconnects++;}};this.gains.push(gain);return gain;}}
const body=new Element('body');body.dataset.game='sonar-submarine';nodes.set('app',new Element('div','app'));const document={body,title:'指揮與潛艇｜',documentElement:new Element(),hidden:false,getElementById:id=>nodes.get(id),addEventListener:(t,f)=>(events[t]??=[]).push(f)},window={AudioContext,addEventListener:(t,f)=>(events[t]??=[]).push(f)};
await vm.runInNewContext(fs.readFileSync(path.join(__dirname,'app.js'),'utf8'),{CoopCore:C,CoopSession:Session,document,window,performance:{now:()=>now},setInterval:f=>intervals.push(f),localStorage:{getItem(){return null;},setItem(){}},fetch:async url=>({ok:true,json:async()=>JSON.parse(fs.readFileSync(path.join(root,'games',url),'utf8'))}),console});
const fire=(t,event={})=>events[t]?.forEach(f=>f(event));return{nodes,contexts,document,window,fire,advance(){now+=400;intervals.forEach(f=>f());},click:id=>nodes.get(id).fire('click'),change(id,value){const e=nodes.get(id);e.value=value;e.fire('change');},key(key){fire('keydown',{key,repeat:false,target:{tagName:'DIV'},preventDefault(){}});},sound(v){const e=nodes.get('sound');e.checked=v;e.fire('change');}};}
function cancelled(context,first=0,count=4){for(let i=first;i<first+count;i++){const o=context.oscs[i],g=context.gains[i];assert(o.stops.length>=2,'Every queued voice must receive a cancellation stop');assert.equal(o.stops.at(-1),context.currentTime,'Future-start voices must stop immediately, not at their planned future endpoint');assert(o.disconnects>0,'Oscillator must disconnect');assert(g.disconnects>0,'Gain must disconnect');assert(g.gain.events.some(e=>e[0]==='cancel'),'Scheduled gain automation must be cancelled');assert(g.gain.events.some(e=>e[0]==='set'&&e[1]===0&&e[2]===context.currentTime),'Gain must be zeroed immediately');}}
async function prepare(local=false,opts){const h=await harness(opts);if(local){h.change('mode','local');h.click('reveal');h.click('handoff');h.click('reveal');}else h.change('human','1');h.key('1');h.sound(true);assert.equal(h.contexts.length,1);assert.equal(h.contexts[0].oscs.length,4);assert(h.contexts[0].oscs.slice(1).every(o=>o.started>h.contexts[0].currentTime),'Test must include voices that have not started yet');return h;}
(async()=>{const cases=[];for(const name of ['mute','pause','reset','change-level','handoff','pagehide','hidden-tab','blur','pointercancel','privacy-key','change-mode','change-human-role','start-demo']){const h=await prepare(name==='handoff'),context=h.contexts[0];switch(name){case'mute':h.sound(false);break;case'pause':h.click('pause');break;case'reset':h.click('reset');break;case'change-level':h.change('level','1');break;case'handoff':h.click('handoff');break;case'pagehide':h.fire('pagehide');break;case'hidden-tab':h.document.hidden=true;h.fire('visibilitychange');break;case'blur':h.fire('blur');break;case'pointercancel':h.fire('pointercancel');break;case'privacy-key':h.key('Escape');break;case'change-mode':h.change('mode','local');break;case'change-human-role':h.change('human','0');break;case'start-demo':h.click('demo');break;}cancelled(context);if(['mute','pagehide'].includes(name))assert.equal(context.closeCalls,1);if(h.window.coopGame.observation()===null){const count=context.oscs.length;h.sound(true);h.advance();assert.equal(context.oscs.length,count,'Covered/paused view must not queue new voices');}cases.push({name,queuedVoices:4,allStoppedAtCancellationTime:true,allOscillatorsAndGainsDisconnected:true,upcomingVoicesCancelled:true,passed:true});}
const pilot=await harness();pilot.advance();pilot.sound(true);pilot.advance();assert.equal(pilot.contexts.length,0,'Pilot must not hear AI sonar private echo');assert.equal(pilot.nodes.get('sound').disabled,true);cases.push({name:'pilot-cannot-hear-AI-private-echo',passed:true});
const overlap=await prepare(),context=overlap.contexts[0];overlap.key('1');assert.equal(overlap.contexts.length,1,'A live context should be reused');assert.equal(context.oscs.length,8);cancelled(context,0,4);for(let i=4;i<8;i++)context.oscs[i].onended();for(let i=4;i<8;i++){assert(context.oscs[i].disconnects>0&&context.gains[i].disconnects>0);assert.equal(context.oscs[i].stops.length,1);}overlap.sound(false);for(let i=4;i<8;i++)assert.equal(context.oscs[i].stops.length,1,'Naturally finished voices must be removed from tracking');overlap.sound(true);assert.equal(overlap.contexts.length,2,'A muted closed context must be replaced safely');assert.equal(overlap.contexts[1].oscs.length,4);cases.push({name:'overlap-cancellation-natural-cleanup-context-reuse',passed:true});
const late=await prepare(false,{deferred:true}),old=late.contexts[0];late.sound(false);cancelled(old);late.sound(true);const fresh=late.contexts[1];assert.equal(fresh.oscs.length,4);old.rejectResume(Error('late old-context resume rejection'));await Promise.resolve();await Promise.resolve();assert.equal(late.nodes.get('sound').checked,true,'Stale resume rejection must not mute a newer context');assert.equal(fresh.closeCalls,0);fresh.resolveResume();await Promise.resolve();assert.equal(old.oscs.length,4,'Resolving/rejecting old requests must never schedule late voices');cases.push({name:'stale-resume-rejection-cannot-affect-new-context',passed:true});
const denied=await prepare(false,{deferred:true}),dc=denied.contexts[0];dc.rejectResume(Error('autoplay denied'));await Promise.resolve();await Promise.resolve();cancelled(dc);assert.equal(denied.nodes.get('sound').checked,false);assert.equal(dc.closeCalls,1);cases.push({name:'current-resume-denial-cancels-and-closes',passed:true});
const report={schemaVersion:1,family:'coop',status:'passed',verifiedAt:new Date().toISOString(),sourceFiles:manifest.sourceFiles,sourceFingerprint:hash(JSON.stringify(manifest.sourceFiles)),cases,claims:{actualAppExecuted:true,webAudioMock:true,browserTesting:false,physicalAudioTesting:false,roleRestrictedPlayback:true,allQueuedVoicesCancelled:true}};fs.writeFileSync(path.join(__dirname,'audio-verification-report.json'),JSON.stringify(report,null,2)+'\n');console.log(`${cases.length} strict audio lifecycle/privacy cases passed, including every queued/future voice in all six reported interruption contexts.`);})().catch(e=>{console.error(e);process.exitCode=1;});
