(function(C){const{act,rng,shuffle,svg,txt}=C;const goods=['水','晶石','種子'],tones=['敬意','平等','安慰'],marks=['△','◇','◉','⟐','⋈','⌁','⊙','⊓','⋇'];
C.register('translator-envoy',{
roles:['使節','譯者'],icon:'⟐',color:'#f0bbda',intro:'使節讀懂表情與需求，譯者掌握外星字典和語序。傳遞意圖、組句、再由使節談判。',help:['使節看得到對方需求，但看不到外星字典。先選物品、數量、語氣，傳給譯者。','譯者依字典和語序逐槽放字，再交回譯文。使節說出句子後才能知道反應。','需求允許一個數量範圍，多種報價都有效。錯誤報價會降低信任，可重新組句。'],
generate(n){const r=rng(n*661);return{id:n,grammar:shuffle([0,1,2],r),lexicon:shuffle(marks,r),rounds:Array.from({length:2+n%5},()=>{const min=1+Math.floor(r()*2);return{good:Math.floor(r()*3),min,max:Math.min(3,min+Math.floor(r()*2)),tone:Math.floor(r()*3)};})};},
init(){return{round:0,intent:[null,null,null],shared:null,phrase:[null,null,null],ready:false,trust:5,reply:'請先觀察談判對象。'};},
observe(s,r){return{round:s.round,total:s.level.rounds.length,trust:s.trust,reply:s.reply,ready:s.ready,...(r===0?{demand:s.level.rounds[s.round],intent:s.intent,phrase:s.ready?s.phrase:null}:{grammar:s.level.grammar,lexicon:s.level.lexicon,shared:s.shared,phrase:s.phrase})};},
actions(o){if(o.role===0)return [...goods.map((g,v)=>act('intent',`物品：${g}`,{field:0,v})),...[1,2,3].map(v=>act('intent',`數量：${v}`,{field:1,v})),...tones.map((t,v)=>act('intent',`語氣：${t}`,{field:2,v})),act('share','傳送目前意圖'),act('speak','說出譯文')];return o.grammar.flatMap((field,slot)=>[0,1,2].map(v=>act('word',`第 ${slot+1} 槽：${o.lexicon[field*3+v]}`,{slot,word:o.lexicon[field*3+v]}))).concat([act('ready','交回完整譯文')]);},
step(s,r,a){if(r===0){if(a.type==='intent'&&[0,1,2].includes(a.field)&&Number.isInteger(a.v)&&a.v>=(a.field===1?1:0)&&a.v<=(a.field===1?3:2)){s.intent[a.field]=a.v;return{ok:true};}if(a.type==='share'&&s.intent.every(x=>x!==null)){s.shared=s.intent.slice();s.phrase=[null,null,null];s.ready=false;s.reply='意圖已送出。';return{ok:true};}if(a.type==='speak'&&s.ready){const decoded=[];s.phrase.forEach((w,slot)=>{const index=s.level.lexicon.indexOf(w),field=s.level.grammar[slot];decoded[field]=Math.floor(index/3)===field?index%3+(field===1?1:0):-1;});const d=s.level.rounds[s.round];if(decoded[0]===d.good&&decoded[1]>=d.min&&decoded[1]<=d.max&&decoded[2]===d.tone){s.round++;s.reply='對方展開光環：提案獲接受。';s.won=s.round===s.level.rounds.length;}else{s.trust--;s.reply='對方縮回觸角：物品、數量、語氣或語法有誤。';s.lost=s.trust<=0;}s.intent=[null,null,null];s.shared=null;s.ready=false;s.phrase=[null,null,null];return{ok:true};}}if(r===1&&s.shared){if(a.type==='word'&&[0,1,2].includes(a.slot)&&s.level.lexicon.includes(a.word)){s.phrase[a.slot]=a.word;s.ready=false;return{ok:true};}if(a.type==='ready'&&s.phrase.every(x=>x!==null)){s.ready=true;return{ok:true};}}return{ok:false,reason:'意圖或句子尚未完成'};},
ai(o){if(o.role===0){if(o.ready)return act('speak','提交譯文');const target=[o.demand.good,o.demand.min,o.demand.tone];for(let field=0;field<3;field++)if(o.intent[field]!==target[field])return act('intent','依反應整理意圖',{field,v:target[field]});if(o.reply!=='意圖已送出。')return act('share','將意圖送給譯者');return null;}if(!o.shared||o.ready)return null;for(let slot=0;slot<3;slot++){const f=o.grammar[slot],w=o.lexicon[f*3+o.shared[f]-(f===1?1:0)];if(o.phrase[slot]!==w)return act('word','套用外星語序',{slot,word:w});}return act('ready','送回已校對譯文');},
view(o){if(o.won)return svg(txt(280,160,'星際協議全部完成',30));let b=`<ellipse cx="280" cy="155" rx="80" ry="90" fill="#705e9c"/><circle cx="250" cy="135" r="12" fill="#e8f9bd"/><circle cx="310" cy="135" r="12" fill="#e8f9bd"/><path d="M245 193Q280 217 315 193" stroke="#f7c4de" fill="none" stroke-width="5"/>`;if(o.role===0&&o.demand)b+=txt(280,45,`需要 ${goods[o.demand.good]} ${o.demand.min}–${o.demand.max} 份 · ${tones[o.demand.tone]}`,22)+txt(280,290,`你的意圖：${o.intent.map((v,i)=>v===null?'？':i===0?goods[v]:i===1?v:tones[v]).join(' / ')}`,19);else{b=txt(280,38,`語序：${o.grammar.map(f=>['物品','數量','語氣'][f]).join(' → ')}`,21);for(let f=0;f<3;f++)b+=txt(280,88+f*42,[goods,[1,2,3],tones][f].map((v,i)=>`${v}=${o.lexicon[f*3+i]}`).join('　'),19);b+=txt(280,252,`意圖：${o.shared?o.shared.map((v,i)=>i===0?goods[v]:i===1?v:tones[v]).join(' / '):'尚未收到'}`,20)+txt(280,294,o.phrase.map(x=>x||'□').join('　'),26);}return svg(b);},status:o=>`協議 ${o.round}/${o.total} · 信任 ${o.trust}/5 · ${o.reply}`
});})(typeof module!=='undefined'?require('../coop120-common/core.js'):CoopCore);
