'use strict';
const KIND='slitherlink',E=window.PuzzleEngine,levels=window.PUZZLES.levels,$=id=>document.getElementById(id),KEY='arcade-'+KIND+'-v1',colors=['#ed9d89','#a3c8f0','#e9c775','#b7a1e3','#8dceb7','#eb9fc7','#c5d785','#8bd1dd'];
let records={},complete={},index=0,state,history=[],moves=0,elapsed=0,selected=0,shape=null,demo=false,demoSaved=null,demoTimer=null,pending=null,lastClock=Date.now();
const clone=x=>JSON.parse(JSON.stringify(x));function level(){return levels[index]}function status(s){$('status').textContent=s}
try{const raw=JSON.parse(localStorage.getItem(KEY)||'null');if(raw&&raw.version===1){index=Number.isInteger(raw.index)&&raw.index>=0&&raw.index<50?raw.index:0;if(raw.records&&typeof raw.records==='object')records=raw.records;if(raw.complete&&typeof raw.complete==='object')for(const[k,v]of Object.entries(raw.complete))if(+k>=0&&+k<50&&Number.isInteger(v)&&v>=0)complete[k]=v}}catch(e){}
function validRecord(r,l){return r&&E.valid(l,r.state)&&Array.isArray(r.history)&&r.history.every(h=>h&&E.valid(l,h.state)&&Number.isInteger(h.moves)&&h.moves>=0)&&Number.isInteger(r.moves)&&r.moves>=0&&Number.isFinite(r.elapsed)&&r.elapsed>=0}
function persist(){if(demo)return;records[index]={state:clone(state),history:clone(history),moves,elapsed};try{localStorage.setItem(KEY,JSON.stringify({version:1,index,records,complete}))}catch(e){$('tip').textContent='瀏覽器儲存不可用，目前仍可遊玩；離開後可能無法保留進度。'}}
function load(n){if(demo)exitDemo();persist();index=n;const r=records[index];if(validRecord(r,level())){state=clone(r.state);history=clone(r.history);moves=r.moves;elapsed=r.elapsed}else{state=E.initial(level());history=[];moves=0;elapsed=0}selected=0;shape=KIND==='polyomino'?clone(level().pieces[0].cells):null;$('level').value=String(index);lastClock=Date.now();status('');render();persist()}
function update(next,msg){if(demo)return;if(!E.valid(level(),next))throw Error('invalid state');history.push({state:clone(state),moves});state=next;moves++;if(E.won(level(),state)){complete[index]=Math.min(complete[index]??Infinity,moves);msg='完成！這一關已通過驗證，你可以撤銷繼續研究或挑戰下一關。'}render();persist();status(msg||'')}
function ask(title,text,fn){pending=fn;$('confirmTitle').textContent=title;$('confirmText').textContent=text;$('confirmDialog').showModal()}
$('cancelConfirm').onclick=()=>{$('confirmDialog').close();pending=null};$('acceptConfirm').onclick=()=>{const fn=pending;pending=null;$('confirmDialog').close();if(fn)fn()};$('confirmDialog').addEventListener('cancel',()=>{pending=null});
function reset(){if(demo)exitDemo();state=E.initial(level());history=[];moves=0;elapsed=0;selected=0;shape=KIND==='polyomino'?clone(level().pieces[0].cells):null;render();persist();status('已重新開始，本關通關紀錄保留。')}
function render(){const l=level(),b=$('board');b.replaceChildren();$('tier').textContent=`第 ${index+1}/50 關 · 第 ${l.tier} 階段`;$('moves').textContent=`操作 ${moves} 次`;$('progress').textContent=`完成 ${Object.keys(complete).length}/50`;$('undo').disabled=demo||!history.length;$('hint').disabled=demo||E.won(l,state);$('next').disabled=index===49;$('demoBar').hidden=!demo;
if(KIND==='slitherlink'){const g=E.geometry(l);b.className='board slither';b.style.gridTemplateColumns=`repeat(${l.w*2+1},1fr)`;b.style.gridTemplateRows=`repeat(${l.h*2+1},1fr)`;
for(let r=0;r<=l.h*2;r++)for(let c=0;c<=l.w*2;c++){let x;if(r%2===0&&c%2===0){x=document.createElement('i');x.className='dot'}else if(r%2&&c%2){x=document.createElement('span');const n=(r>>1)*l.w+(c>>1),v=l.clues[n],used=g.cells[n].filter(i=>state[i]===1).length;x.className='clue'+(v!==null&&used>v?' bad':'');x.textContent=v===null?'':v}else{const horizontal=r%2===0,i=horizontal?(r>>1)*l.w+(c>>1):(l.h+1)*l.w+(r>>1)*(l.w+1)+(c>>1);x=document.createElement('button');x.className='edge'+(!horizontal?' vertical':'')+(state[i]===1?' on':state[i]===-1?' cross':'');x.setAttribute('aria-label',`${horizontal?'橫':'直'}邊 第${(r>>1)+1}列第${(c>>1)+1}欄：${state[i]===1?'已畫線':state[i]===-1?'叉號':'空白'}`);x.disabled=demo;x.onclick=()=>{update(E.act(l,state,i));requestAnimationFrame(()=>b.querySelector(`[data-edge="${i}"]`)?.focus())};x.dataset.edge=i}b.append(x)}$('result').textContent=E.won(l,state)?'✓ 唯一環線完成':`${state.filter(x=>x===1).length} 條線段`;}
else{if(selected!==null&&state[selected]){selected=state.findIndex(p=>!p);if(selected<0)selected=null;shape=selected===null?null:clone(l.pieces[selected].cells)}b.className='board';b.style.gridTemplateColumns=`repeat(${l.w},1fr)`;b.style.gridTemplateRows=`repeat(${l.h},1fr)`;const occupancy=E.board(l,state);occupancy.forEach((v,i)=>{const x=document.createElement('button');x.className='cell'+(v===-2?' blocked':'');if(v>=0){x.style.background=colors[v%colors.length];x.style.color='#172234';x.textContent=String.fromCharCode(65+v)}x.disabled=demo||v===-2;x.setAttribute('aria-label',`第${Math.floor(i/l.w)+1}列第${i%l.w+1}欄 ${v>=0?'拼片'+String.fromCharCode(65+v):v===-2?'障礙':'空格'}`);x.onclick=()=>{if(v>=0){const next=clone(state);selected=v;shape=clone(state[v].cells);next[v]=null;update(next,'已拿回拼片，可旋轉或重新放置。')}else if(selected!==null){try{update(E.place(l,state,selected,shape,Math.floor(i/l.w),i%l.w));selected=state.findIndex(p=>!p);if(selected<0)selected=null;shape=selected===null?null:clone(l.pieces[selected].cells);render()}catch(e){status(e.message)}}};b.append(x)});const palette=$('palette');palette.replaceChildren();l.pieces.forEach((p,i)=>{const x=document.createElement('button');x.className='piece'+(i===selected?' selected':'');x.disabled=demo||Boolean(state[i]);x.setAttribute('aria-label',`拼片${String.fromCharCode(65+i)}${state[i]?'已放置':''}`);const f=i===selected?shape:p.cells,pw=Math.max(5,1+Math.max(...f.map(p=>p[1]))),ph=Math.max(3,1+Math.max(...f.map(p=>p[0])));x.style.gridTemplateColumns=`repeat(${pw},var(--mini,11px))`;x.style.gridAutoRows='var(--mini,11px)';for(let r=0;r<ph;r++)for(let c=0;c<pw;c++){const v=document.createElement('i');v.className='mini';if(f.some(([rr,cc])=>rr===r&&cc===c))v.style.background=colors[i%colors.length];x.append(v)}x.onclick=()=>{selected=i;shape=clone(p.cells);render();status('已選拼片 '+String.fromCharCode(65+i)+'，可旋轉、翻面後點格放置。')};palette.append(x)});$('rotate').disabled=demo||selected===null;$('flip').disabled=demo||selected===null;}
requestAnimationFrame(sizeBoard)}
function sizeBoard(){const p=$('board').parentElement,l=level(),width=Math.max(80,p.clientWidth-30),height=Math.max(80,p.clientHeight-30),ratio=KIND==='slitherlink'?(l.w*2+1)/(l.h*2+1):l.w/l.h;let w=Math.min(width,height*ratio,650);$('board').style.width=w+'px';$('board').style.height=w/ratio+'px'}
if(KIND==='polyomino'){$('rotate').onclick=()=>{shape=E.rotate(shape);render()};$('flip').onclick=()=>{shape=E.flip(shape);render()}}
$('undo').onclick=()=>{if(!history.length||demo)return;const h=history.pop();state=h.state;moves=h.moves;render();persist();status('已撤銷一次操作。')};$('restart').onclick=()=>ask('重新開始這一關？','目前配置與本次操作紀錄會清除，已完成的關卡紀錄保留。',reset);$('help').onclick=()=>$('helpDialog').showModal();
$('hint').onclick=()=>{const l=level();if(KIND==='slitherlink'){const i=state.findIndex((x,i)=>(x===1?1:0)!==l.solution[i]);if(i<0)return;const n=state.slice();n[i]=l.solution[i]===1?1:-1;update(n,`依唯一解修正一條邊。${l.solution[i]?'這條邊應畫線。':'這條邊不在環上。'}`)}else{const target=l.solution.find(p=>!state[p.piece]);if(!target)return;try{update(E.place(l,state,target.piece,target.cells,target.row,target.col),`參考解：拼片${String.fromCharCode(65+target.piece)}置於第${target.row+1}列第${target.col+1}欄。`)}catch(e){status('目前拼法與參考解不同，不代表無解。可撤銷幾步，或開啟不改動進度的解答示範。')}}};
function exitDemo(){if(!demo)return;clearTimeout(demoTimer);demoTimer=null;state=demoSaved.state;history=demoSaved.history;moves=demoSaved.moves;elapsed=demoSaved.elapsed;selected=demoSaved.selected;shape=demoSaved.shape;demo=false;demoSaved=null;render();status('已離開示範，恢復原本進度。');lastClock=Date.now()}
function startDemo(){if(demo)exitDemo();persist();demoSaved={state:clone(state),history:clone(history),moves,elapsed,selected,shape:clone(shape)};demo=true;state=E.initial(level());moves=0;history=[];let steps=KIND==='slitherlink'?level().solution.map((x,i)=>x?i:-1).filter(i=>i>=0):level().solution;let i=0;render();const tick=()=>{if(!demo)return;if(i>=steps.length){status(E.won(level(),state)?'示範通關！可離開示範回到原本進度。':'示範驗證失敗');return}if(KIND==='slitherlink')state[steps[i]]=1;else{const p=steps[i];state=E.place(level(),state,p.piece,p.cells,p.row,p.col)}i++;moves=i;render();demoTimer=setTimeout(tick,170)};tick()}
$('solution').onclick=()=>{if(demo){exitDemo();return}ask('觀看完整解答？','將暫時播放本關參考解，離開示範會恢復你的配置，不會計入通關紀錄。',startDemo)};$('exitDemo').onclick=exitDemo;
for(let i=0;i<levels.length;i++){const o=document.createElement('option');o.value=i;o.textContent=String(i+1).padStart(2,'0')+' · 階段'+levels[i].tier;$('level').append(o)}
$('level').onchange=()=>load(+$('level').value);$('next').onclick=()=>{if(index<49)load(index+1)};window.addEventListener('resize',sizeBoard);document.addEventListener('visibilitychange',()=>{lastClock=Date.now();persist()});window.addEventListener('pagehide',persist);
setInterval(()=>{const now=Date.now();if(!demo&&!document.hidden&&!E.won(level(),state))elapsed+=(now-lastClock)/1000;lastClock=now;const n=Math.floor(elapsed);$('timer').textContent=`${Math.floor(n/60)}:${String(n%60).padStart(2,'0')}`;persist()},1000);
// Initial load without writing undefined state.
state=E.initial(level());const first=index;const saved=records[first];if(validRecord(saved,level())){state=clone(saved.state);history=clone(saved.history);moves=saved.moves;elapsed=saved.elapsed}shape=KIND==='polyomino'?clone(level().pieces[0].cells):null;$('level').value=String(index);render();persist();
