'use strict';
const assert=require('node:assert/strict'),levels=require('./levels.js'),E=require('./engine.js'),{solve}=require('./solver.cjs');
function independentValid(p,values){const es=[];for(let a=0;a<p.islands.length;a++)for(let b=a+1;b<p.islands.length;b++){const u=p.islands[a],v=p.islands[b];if(u[0]!==v[0]&&u[1]!==v[1])continue;const middle=p.islands.some((w,k)=>k!==a&&k!==b&&(u[0]===v[0]?w[0]===u[0]&&w[1]>Math.min(u[1],v[1])&&w[1]<Math.max(u[1],v[1]):w[1]===u[1]&&w[0]>Math.min(u[0],v[0])&&w[0]<Math.max(u[0],v[0])));if(!middle)es.push([a,b]);}
const live=E.edges(p);assert.equal(live.length,es.length);const weighted=es.map(([a,b])=>[a,b,values[live.findIndex(([x,y])=>x===a&&y===b||x===b&&y===a)]]),deg=p.islands.map(()=>0),adj=p.islands.map(()=>[]),occupied=new Map();for(const[a,b,k]of weighted){if(!Number.isInteger(k)||k<0||k>2)return false;if(!k)continue;deg[a]+=k;deg[b]+=k;adj[a].push(b);adj[b].push(a);const [x,y]=p.islands[a],[xx,yy]=p.islands[b],dx=Math.sign(xx-x),dy=Math.sign(yy-y);for(let qx=x+dx,qy=y+dy;qx!==xx||qy!==yy;qx+=dx,qy+=dy){const key=qx+','+qy;if(occupied.has(key)&&occupied.get(key)!==(dx?'h':'v'))return false;occupied.set(key,dx?'h':'v');}}
if(!deg.every((d,i)=>d===p.islands[i][2]))return false;const stack=[0],seen=new Set([0]);while(stack.length){const u=stack.pop();for(const v of adj[u])if(!seen.has(v)){seen.add(v);stack.push(v);}}return seen.size===p.islands.length;}
function canonical(p){const variants=[];for(const flip of [false,true])for(let turn=0;turn<4;turn++){const q=p.islands.map(([x,y,v])=>{if(flip)x=p.size-1-x;for(let t=0;t<turn;t++)[x,y]=[p.size-1-y,x];return [x,y,v];}).sort((a,b)=>a[0]-b[0]||a[1]-b[1]);variants.push(p.size+':'+JSON.stringify(q));}return variants.sort()[0];}
function brute(p){const es=E.edges(p),values=es.map(()=>0),degrees=p.islands.map(()=>0);let count=0;function go(k){if(count>1)return;if(k===es.length){if(independentValid(p,values))count++;return;}const [a,b]=es[k];for(let v=0;v<=2;v++){if(degrees[a]+v>p.islands[a][2]||degrees[b]+v>p.islands[b][2])continue;values[k]=v;degrees[a]+=v;degrees[b]+=v;let possible=true;for(let u=0;u<degrees.length;u++){const remaining=es.slice(k+1).filter(([x,y])=>x===u||y===u).length*2;if(degrees[u]+remaining<p.islands[u][2]){possible=false;break;}}if(possible)go(k+1);degrees[a]-=v;degrees[b]-=v;}}go(0);return count;}
const keys=new Set();let mutations=0;const rows=[];assert.equal(levels.length,50);for(const [i,p]of levels.entries()){assert.equal(p.id,i+1);assert.equal(new Set(p.islands.map(a=>a[0]+','+a[1])).size,p.islands.length);assert(p.islands.every(([x,y,v])=>x>=0&&y>=0&&x<p.size&&y<p.size&&v>=1&&v<=8));const k=canonical(p);assert(!keys.has(k),'rotation/mirror duplicate '+p.id);keys.add(k);const proof=solve(p,2);assert.equal(proof.count,1,'nonunique level '+p.id);assert.deepEqual(proof.solutions[0],p.solution);assert(E.validateSolution(p,p.solution));assert(independentValid(p,p.solution));assert(!E.validateSolution(p,p.solution.map(()=>0)));for(let j=0;j<p.solution.length;j++){const x=p.solution.slice();x[j]=(x[j]+1)%3;assert(!E.validateSolution(p,x));mutations++;}rows.push({id:p.id,size:p.size,islands:p.islands.length,edges:p.solution.length,solutions:proof.count,searchNodes:proof.nodes});}
for(const p of levels.slice(0,10))assert.equal(brute(p),1,'independent brute-count level '+p.id);
const disconnected={size:5,islands:[[0,0,1],[2,0,1],[0,2,1],[2,2,1]]};assert(!E.validateSolution(disconnected,[1,0,0,1]));
console.log(JSON.stringify({game:'Hashi',levels:50,exactUnique:50,canonicalDistinct:50,independentRuleChecks:50,independentBruteCounts:10,singleEdgeMutationRejections:mutations,rows},null,2));
