(function(root,f){if(typeof module==='object'&&module.exports)module.exports=f();else root.NumericSession=f();})(typeof globalThis!=='undefined'?globalThis:this,function(){'use strict';
const clone=x=>JSON.parse(JSON.stringify(x));
function create({slug,levels,proofs,engine:E,storage}){let index=0,actions=[],state,assisted=false,preview=null,records={},error=!storage;const key='arcade.numeric.v1.'+slug;
function replay(l,aa){let s=E.createState(l);if(!Array.isArray(aa)||aa.length>500)throw Error('走法無效');for(let a of aa){s=E.applyAction(l,s,a);if(!E.validateState(l,s))throw Error('走法無效');}return s;}
function save(){try{storage?.setItem(key,JSON.stringify({version:1,index,actions,assisted,records}));}catch(e){error=true;}}
try{let raw=storage?.getItem(key);if(raw){let p=JSON.parse(raw);if(p.version!==1)throw Error('版本不合');for(let [id,r]of Object.entries(p.records||{})){let l=levels.find(x=>x.id===id);if(l&&E.inspect(l,replay(l,r.actions)).goalMet)records[id]={actions:r.actions,assisted:!!r.assisted};}if(Number.isInteger(p.index)&&p.index>=0&&p.index<levels.length){index=p.index;state=replay(levels[index],p.actions);actions=p.actions;assisted=!!p.assisted;}}}catch(e){error=true;actions=[];}if(!state)state=E.createState(levels[index]);
function snap(){return clone({index,level:levels[index],state,actions,assisted,preview,records,error});}
return{snapshot:snap,dispatch(a){if(preview)return false;state=E.applyAction(levels[index],state,a);actions.push(clone(a));if(E.inspect(levels[index],state).goalMet){let old=records[levels[index].id];if(!old||old.assisted&&!assisted||old.assisted===assisted&&actions.length<old.actions.length)records[levels[index].id]={actions:clone(actions),assisted};}save();return true;},undo(){if(preview)return;actions.pop();state=replay(levels[index],actions);save();},reset(){preview=null;actions=[];state=E.createState(levels[index]);assisted=false;save();},select(i){if(!Number.isInteger(i)||!levels[i])throw Error('關卡不存在');index=i;actions=[];preview=null;state=E.createState(levels[index]);assisted=false;save();},assist(){assisted=true;save();},startReplay(){assisted=true;preview={state:E.createState(levels[index]),cursor:0,total:proofs[index].actions.length};save();},stepReplay(){if(!preview||preview.cursor>=preview.total)return;preview.state=E.applyAction(levels[index],preview.state,proofs[index].actions[preview.cursor++]);},stopReplay(){preview=null;save();},flush:save};}
return{create};});
