'use strict';const fs=require('fs'),path=require('path'),crypto=require('crypto'),E=require('./engine.js'),catalog=require('./catalog.js'),Canonical=require('./canonical.cjs');
const root=path.resolve(__dirname,'..');function rng(seed){let a=seed>>>0;return()=>{a+=0x6D2B79F5;let t=a;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function pick(r,a){return a[Math.floor(r()*a.length)]}function shuffle(r,a){a=a.slice();for(let i=a.length-1;i>0;i--){let j=Math.floor(r()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function make(kind,id,attempt){const r=rng((id*198491317+attempt*65497+catalog.findIndex(c=>c.slug===kind)*9973)>>>0),w=6+id%2,h=5+Math.floor((id-1)/10)%2;let l={id,kind,w,h,start:0,exit:w*h-1,walls:[],guards:[],cycle:12,budget:999};const cells=()=>Array.from({length:l.w*l.h},(_,p)=>p).filter(p=>E.open(l,p));const q=()=>pick(r,cells().filter(p=>p!==l.start&&p!==l.exit));
if(kind==='thief-exchange'){l.n=10+2*(id%4);l.cycle=l.n*4;l.targetStart=1+id%(l.n-1);l.targetSpeed=1;l.pickup=1+Math.floor(r()*(l.n-2));l.crowd=Array.from({length:4},()=>shuffle(r,Array.from({length:l.n},(_,i)=>i)).slice(0,4+id%3));l.watch=Array.from({length:4},()=>Math.floor(r()*l.n));l.limit=l.n*5;return l}
if(kind==='tailing-mission'){l.lane=id%3;l.targetLane=(id+1)%3;l.route=Array.from({length:12+id%11},(_,i)=>({speed:r()<.2?0:r()<.7?1:2,lane:Math.floor(r()*3),look:i%3===id%3||r()<.2}));l.blocks=[];l.covers=[];let end=l.route.reduce((a,b)=>a+b.speed,3);for(let i=4;i<end;i++){if(r()<.24)l.blocks.push({x:i,lane:Math.floor(r()*3)});if(r()<.35)l.covers.push({x:i,lane:Math.floor(r()*3)})}return l}
if(kind==='document-swap'){l.cols=3+id%2;l.docs=[];const values=shuffle(r,Array.from({length:27},(_,i)=>i)).slice(0,l.cols*3);for(let v of values)l.docs.push({dept:v%3,rank:Math.floor(v/3)%3,mark:Math.floor(v/9),paper:Math.floor(r()*3),seal:Math.floor(r()*3),date:Math.floor(r()*3)});const target=pick(r,l.docs);l.clues=[target.dept,target.rank,target.mark];l.limit=12+id%5;l.cycle=l.cols;return l}
if(kind==='bug-sweep'){l.w=5+id%3;l.h=5+Math.floor(id/3)%3;let pos=shuffle(r,Array.from({length:l.w*l.h},(_,i)=>i));l.bugs=pos.slice(0,2);l.noise=Array.from({length:3+id%4},()=>10+10*Math.floor(r()*4));l.battery=10+id%4;return l}
if(kind==='dual-infiltration'){l.w=7;l.h=10;l.walls=[];let ra=id%5,rb=Math.floor(id/5)%5;l.gates=[ra*7+3,(rb+5)*7+3];for(let y=0;y<10;y++)if(y!==ra&&y!==rb+5)l.walls.push(y*7+3);l.starts=[(id%5)*7,35+(Math.floor(id/10)%5)*7];l.exits=[(Math.floor(id/20)%5)*7+6,35+(id%5)*7+6];l.plate=(Math.floor(id/5)%5)*7+1;l.switch=35+((id+2)%5)*7+5;for(let region=0;region<2;region++){let pool=cells().filter(p=>Math.floor(p/7)>=region*5&&Math.floor(p/7)<region*5+5&&p%7!==3&&![...l.starts,...l.exits,l.plate,l.switch].includes(p));l.walls.push(...shuffle(r,pool).slice(0,2+id%3))}return l}
if(kind==='disguise-pass'){l.w=7;l.h=5;const a=(id-1)%5,b=Math.floor((id-1)/5)%5;for(let y=0;y<5;y++){if(y!==a)l.walls.push(y*7+2);if(y!==b)l.walls.push(y*7+4)}l.start=Math.floor((id-1)/25)*7;l.exit=((id+2)%5)*7+6;l.chip=((id+4)%5)*7+5;l.doors=[{p:a*7+2,identity:1},{p:b*7+4,identity:2}];l.wardrobes=[l.start,((id+1)%5)*7+3];l.budget=80;return l}
if(kind==='decoy-setup'){l.w=7;l.h=5+id%2;let row=1+id%(l.h-2);for(let y=0;y<l.h;y++)if(y!==row)l.walls.push(y*7+3);l.start=(id%l.h)*7;l.exit=((id+2)%l.h)*7+6;l.chip=((id+3)%l.h)*7+5;l.guards=[{route:[row*7+3],range:2,dir:3,search:3+id%3}];l.decoys=2+id%2;let pool=cells().filter(p=>p%7!==3&&p%7!==2&&p%7!==4&&![l.start,l.exit,l.chip].includes(p));l.walls.push(...shuffle(r,pool).slice(0,1+id%4));l.budget=80;return l}
// General reconnaissance sites vary both topology and mission positions.
l.walls=shuffle(r,Array.from({length:w*h-2},(_,i)=>i+1)).slice(0,3+id%8);l.start=pick(r,cells().filter(p=>p%w===0));l.exit=pick(r,cells().filter(p=>p%w===w-1));l.chip=q();
if(kind==='vent-escape'){
 l.guards=[];l.pipes=Array(w*h).fill(0);let visited=new Set([l.start]),stack=[l.start];while(stack.length){let p=stack.at(-1),ds=shuffle(r,[0,1,2,3]).filter(d=>E.open(l,E.next(l,p,d))&&!visited.has(E.next(l,p,d)));if(!ds.length){stack.pop();continue}let d=ds[0],n=E.next(l,p,d);l.pipes[p]|=1<<d;l.pipes[n]|=1<<((d+2)%4);visited.add(n);stack.push(n)}
 if(!visited.has(l.chip)||!visited.has(l.exit))return null;for(let p of visited)for(let d=1;d<=2;d++){let n=E.next(l,p,d);if(E.open(l,n)&&r()<.18){l.pipes[p]|=1<<d;l.pipes[n]|=1<<((d+2)%4)}}
 l.fans=shuffle(r,[...visited].filter(p=>![l.start,l.exit,l.chip].includes(p))).slice(0,2+id%3).map(p=>({p,period:3,off:id%3}));l.valve=pick(r,[...visited].filter(p=>!l.fans.some(f=>f.p===p)));l.oxygen=shuffle(r,[...visited].filter(p=>p!==l.start)).slice(0,2);l.air=45+id%10;l.refill=12;return l;
}
if(kind==='camera-labyrinth'){l.cameras=shuffle(r,cells().filter(p=>![l.start,l.exit,l.chip].includes(p))).slice(0,2+id%2).map(p=>({p,dir:Math.floor(r()*4),range:3+id%3,speed:1}));l.hack=q();l.cycle=4;return l}
let routes=[];for(let p of cells()){let x=p%w,y=Math.floor(p/w);if(x<w-1&&y<h-1&&[p,p+1,p+w,p+w+1].every(n=>E.open(l,n)&&![l.start,l.exit,l.chip].includes(n)))routes.push([p,p+1,p+w+1,p+w])}
if(!routes.length)return null;l.guards=[{route:pick(r,routes),range:2+id%2,dir:id%4,search:2+id%3}];
if(kind==='shadow-infiltration')l.lights=shuffle(r,cells().filter(p=>p!==l.start)).slice(0,4+id%7).map(p=>({p,period:3,on:Math.floor(r()*3)}));
if(kind==='silent-footsteps'){l.floors=Array.from({length:w*h},()=>pick(r,[0,0,2,4]));l.budget=Math.ceil(Math.max(4,E.path(l,l.start,l.chip).length+E.path(l,l.chip,l.exit).length-2)*1.4)+1}
if(kind==='prison-break'){l.key=q();l.tool=q();if(l.key===l.tool)return null;l.dig=q();l.requiredDigs=2+id%3;l.doors=shuffle(r,cells().filter(p=>![l.start,l.key,l.tool,l.dig].includes(p))).slice(0,2+id%3).map(p=>({p,open:Math.floor(r()*4)}));l.budget=90}
if(kind==='hostage-extraction'){l.hostage=q();if(l.hostage===l.chip)return null;l.budget=90}
if(kind==='spy-photography'){l.evidence=shuffle(r,cells().filter(p=>![l.start,l.exit].includes(p))).slice(0,2+id%2);l.budget=90}
if(kind==='rewind-agent'){l.traps=shuffle(r,cells().filter(p=>![l.start,l.exit,l.chip].includes(p))).slice(0,1+Math.floor(id/25)%2);l.rewinds=l.traps.length+1;l.budget=100}
return l}
function direct(l){if(l.kind==='document-swap'){let j=l.docs.findIndex(d=>l.clues.every((v,i)=>d[['dept','rank','mark'][i]]===v)),d=l.docs[j],a=['select:'+j];for(const f of ['paper','seal','date'])if(d[f]!==0)a.push(f+':'+d[f]);if(a.length%l.cols===j%l.cols)a.push('wait');a.push('swap','leave');return{actions:a,explored:1}}
if(l.kind==='bug-sweep'){let a=['noise'];for(let f=0;f<2;f++)a.push('freq:'+f,'scan:0','scan:'+(l.w-1),'remove:'+l.bugs[f]);return{actions:a,explored:1}}return null}
function decoySolve(l,max=25000){let q=[{s:E.initial(l),parent:-1,a:null,g:0}],heap=[],seen=new Map();const h=s=>{if(l.kind==='rewind-agent'&&!s.off){let left=l.traps.filter((p,i)=>!(s.memory&(1<<i)));return left.length?Math.min(...left.map(p=>E.md(l,s.p,p)))+left.length*5:E.md(l,s.p,l.start)+1+E.md(l,l.start,l.chip)+E.md(l,l.chip,l.exit)}return s.mask&1?E.md(l,s.p,l.exit):E.md(l,s.p,l.chip)+E.md(l,l.chip,l.exit)};function push(idx){heap.push(idx);let i=heap.length-1;while(i){let p=(i-1)>>1;if(q[heap[p]].score<=q[heap[i]].score)break;[heap[p],heap[i]]=[heap[i],heap[p]];i=p}}function pop(){let x=heap[0],v=heap.pop();if(heap.length){heap[0]=v;let i=0;for(;;){let a=i*2+1,b=a+1,c=i;if(a<heap.length&&q[heap[a]].score<q[heap[c]].score)c=a;if(b<heap.length&&q[heap[b]].score<q[heap[c]].score)c=b;if(c===i)break;[heap[c],heap[i]]=[heap[i],heap[c]];i=c}}return x}q[0].score=h(q[0].s)*2;push(0);let explored=0;while(heap.length&&explored++<max){let i=pop(),n=q[i];if(n.s.status==='won'){let a=[];for(let j=i;q[j].parent>=0;j=q[j].parent)a.unshift(q[j].a);return{actions:a,explored}}for(let a of E.actions(l,n.s)){let s=E.step(l,n.s,a);if(s===n.s||(s.status==='lost'&&l.kind!=='rewind-agent'))continue;let k=E.key(l,s),g=n.g+1;if(seen.has(k)&&seen.get(k)<=g)continue;seen.set(k,g);q.push({s,parent:i,a,g,score:g+h(s)*2});push(q.length-1)}}return null}
function hash(x){return crypto.createHash('sha256').update(x).digest('hex')}
module.exports={make,direct,decoySolve};if(require.main===module){const selected=process.argv.slice(2);let all=[];for(const c of catalog){if(selected.length&&!selected.includes(c.slug))continue;let levels=[],witness=[],seen=new Set();for(let id=1;id<=100;id++){let ok=false;for(let attempt=0;attempt<500;attempt++){let l=make(c.slug,id,attempt);if(!l)continue;const result=direct(l)||(['decoy-setup','rewind-agent'].includes(c.slug)?decoySolve(l):E.solve(l,undefined,c.slug==='silent-footsteps'?30000:65000));if(!result)continue;let s=E.initial(l);for(const a of result.actions)s=E.step(l,s,a);if(s.status!=='won')throw Error(c.slug+' bad witness '+id);
if(c.slug==='silent-footsteps'&&(!result.actions.some(a=>a.startsWith('fast'))||!result.actions.some(a=>/^m[0-3]$/.test(a))))continue;if(c.slug==='disguise-pass'&&result.actions.filter(a=>a.startsWith('dress')).length<2)continue;if(c.slug==='decoy-setup'&&!result.actions.some(a=>a.startsWith('decoy')))continue;let identity=l.kind==='bug-sweep'?Canonical.bugSweep(l):JSON.stringify({...l,id:0});if(seen.has(identity))continue;seen.add(identity);l.seedAttempt=attempt;levels.push(l);witness.push({id,actions:result.actions,explored:result.explored,finalUsed:s.used});ok=true;break}if(!ok)throw Error('Failed generation '+c.slug+' '+id);if(id%20===0)console.log(c.slug,id)}
const dir=path.join(root,c.slug);fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'levels.json'),JSON.stringify(levels));fs.writeFileSync(path.join(dir,'witnesses.json'),JSON.stringify(witness));fs.writeFileSync(path.join(dir,'levels.js'),'window.STEALTH_LEVELS='+JSON.stringify(levels)+';\nwindow.STEALTH_WITNESSES='+JSON.stringify(witness)+';\n');all.push({slug:c.slug,levelCount:levels.length,uniqueStructures:seen.size,corpusHash:hash(JSON.stringify(levels)),witnessHash:hash(JSON.stringify(witness))});console.log('GENERATED',c.slug)}
fs.writeFileSync(path.join(__dirname,'generation'+(selected.length?'-'+selected.join('_'):'')+'.json'),JSON.stringify(all,null,2));

}
