(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.Skyscrapers=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';const cache=new Map();
function permutations(n){if(cache.has(n))return cache.get(n);const all=[];function visit(a,used){if(a.length===n){all.push(a);return;}for(let v=1;v<=n;v++)if(!(used&(1<<v)))visit(a.concat(v),used|(1<<v));}visit([],0);cache.set(n,all);return all;}
function visible(a){let high=0,count=0;for(const v of a)if(v>high){count++;high=v;}return count;}
function clues(n,grid){const c={top:[],right:[],bottom:[],left:[]};for(let i=0;i<n;i++){let row=grid.slice(i*n,i*n+n),col=Array.from({length:n},(_,r)=>grid[r*n+i]);c.left.push(visible(row));c.right.push(visible(row.slice().reverse()));c.top.push(visible(col));c.bottom.push(visible(col.slice().reverse()));}return c;}
function solve(level,limit=2,override){const{n}=level,c=level.clues,g=override||level.givens,perms=permutations(n);let nodes=0,count=0,first=null,grid=Array(n*n).fill(0),masks=Array(n).fill(0);
 const candidates=Array.from({length:n},(_,r)=>perms.filter(p=>(!c.left[r]||visible(p)===c.left[r])&&(!c.right[r]||visible(p.slice().reverse())===c.right[r])&&p.every((v,j)=>!g[r*n+j]||g[r*n+j]===v)));
 function visit(r){nodes++;if(r===n){for(let col=0;col<n;col++){const a=Array.from({length:n},(_,rr)=>grid[rr*n+col]);if(c.bottom[col]&&visible(a.reverse())!==c.bottom[col])return;}count++;if(!first)first=grid.slice();return;}
 for(const p of candidates[r]){if(p.some((v,col)=>masks[col]&(1<<v)))continue;let ok=true;for(let col=0;col<n&&ok;col++)if(c.top[col]){const a=Array.from({length:r},(_,rr)=>grid[rr*n+col]).concat(p[col]);const seen=visible(a);if(seen>c.top[col]||seen+n-r-1<c.top[col]||(r===n-1&&seen!==c.top[col]))ok=false;}if(!ok)continue;for(let col=0;col<n;col++){grid[r*n+col]=p[col];masks[col]|=1<<p[col];}visit(r+1);for(let col=0;col<n;col++){masks[col]&=~(1<<p[col]);grid[r*n+col]=0;}if(count>=limit)return;}
 }visit(0);return{count,solution:first,nodes};}
function valid(level,grid){const n=level.n;if(!Array.isArray(grid)||grid.length!==n*n||grid.some(v=>!Number.isInteger(v)||v<1||v>n))return false;if(level.givens.some((v,i)=>v&&v!==grid[i]))return false;for(let i=0;i<n;i++)if(new Set(grid.slice(i*n,i*n+n)).size!==n||new Set(Array.from({length:n},(_,r)=>grid[r*n+i])).size!==n)return false;const c=clues(n,grid);return Object.keys(c).every(side=>c[side].every((v,i)=>!level.clues[side][i]||v===level.clues[side][i]));}
function conflicts(level,grid){const n=level.n,bad=new Set(),edges=[];for(let k=0;k<n;k++){for(const ids of[Array.from({length:n},(_,i)=>k*n+i),Array.from({length:n},(_,i)=>i*n+k)]){const vals=ids.map(i=>grid[i]);ids.forEach((id,j)=>{if(vals[j]&&vals.filter(v=>v===vals[j]).length>1)bad.add(id);});}}const c=clues(n,grid);for(const side of Object.keys(c))for(let i=0;i<n;i++){const line=(side==='top'||side==='bottom')?Array.from({length:n},(_,r)=>grid[r*n+i]):grid.slice(i*n,i*n+n);if(line.every(Boolean)&&level.clues[side][i]&&c[side][i]!==level.clues[side][i])edges.push(side+i);}return{cells:[...bad],edges};}
function canonical(n,grid){let a=[];for(let f=0;f<2;f++)for(let r=0;r<4;r++){let out=Array(n*n);grid.forEach((v,i)=>{let x=i%n,y=Math.floor(i/n);if(f)x=n-1-x;for(let k=0;k<r;k++)[x,y]=[n-1-y,x];out[y*n+x]=v;});a.push(out.join(''));}return a.sort()[0];}
function initial(level){return{grid:level.givens.slice(),notes:Array(level.n**2).fill(0),moves:0,assisted:false,won:false};}
function replay(level,actions){let s=initial(level),history=[];if(!Array.isArray(actions)||actions.length>5000)throw Error('Bad actions');for(const a of actions){if(!a||typeof a!=='object')throw Error('Bad action');if(a.type==='assist'){s.assisted=true;continue;}if(a.type==='undo'){if(history.length){const assisted=s.assisted;s=history.pop();s.assisted=assisted;}continue;}if(s.won)throw Error('Action after win');if(a.type!=='set'&&a.type!=='note')throw Error('Bad type');if(!Number.isInteger(a.i)||a.i<0||a.i>=level.n**2||level.givens[a.i]||!Number.isInteger(a.v)||a.v<0||a.v>level.n)throw Error('Bad entry');history.push(JSON.parse(JSON.stringify(s)));if(a.type==='note'){if(!s.grid[a.i])s.notes[a.i]=a.v?s.notes[a.i]^(1<<a.v):0;}else{s.grid[a.i]=a.v;s.notes[a.i]=0;}s.moves++;s.won=valid(level,s.grid);}s.undoCount=history.length;return s;}
return{permutations,visible,clues,solve,valid,conflicts,canonical,initial,replay};
});
