'use strict';
// Event-driven DOM harness only. This tests actual app.js handlers, NOT browser rendering.
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');const slug=path.basename(__dirname),black=slug==='black-box',key='arcade-'+slug+'-v1',data=require('./levels.json'),levels=data.levels,E=require('./engine');
function setup(saved=null,blocked=false,query=''){
 const elements=new Map(),storage=new Map();
 const doc={activeElement:null,handlers:{},getElementById:id=>elements.get(id),addEventListener(k,f){(this.handlers[k]??=[]).push(f);},querySelector(sel){if(sel==='dialog[open]')return[...elements.values()].find(e=>e.tagName==='DIALOG'&&e.open)||null;return null;},fire(k,e){for(const f of this.handlers[k]??[])f(e);}};
 class Element{
 constructor(tag='div'){this.tagName=tag.toUpperCase();this.children=[];this.dataset={};this.attrs={};this.handlers={};this.disabled=false;this.hidden=false;this.className='';this.textContent='';this.value='';this.style={setProperty(k,v){this[k]=v;}};this.open=false;this.parent=null;this.id='';this.classList={toggle:(k,v)=>{const s=new Set(this.className.split(' '));if(v)s.add(k);else s.delete(k);this.className=[...s].join(' ');}};}
 set innerHTML(html){this._html=html;this.children=[];for(const m of html.matchAll(/<(button|option|span)\b([^>]*)>/g)){const el=new Element(m[1]);el.parent=this;for(const a of m[2].matchAll(/([\w-]+)="([^"]*)"/g)){el.attrs[a[1]]=a[2];if(a[1].startsWith('data-'))el.dataset[a[1].slice(5)]=a[2];if(a[1]==='value')el.value=a[2];if(a[1]==='class')el.className=a[2];}el.disabled=/\bdisabled\b/.test(m[2]);this.children.push(el);}}
 get innerHTML(){return this._html||'';}get options(){return this.children.filter(x=>x.tagName==='OPTION');}
 setAttribute(k,v){this.attrs[k]=String(v);}addEventListener(k,f){(this.handlers[k]??=[]).push(f);}fire(k,extra={}){if(k==='click'&&this.disabled)return;const e={target:this,key:'',preventDefault(){},...extra};for(const f of this.handlers[k]??[])f(e);if(this.parent)for(const f of this.parent.handlers[k]??[])f(e);if(k==='keydown')doc.fire(k,e);}
 focus(){doc.activeElement=this;}showModal(){this.open=true;}close(){this.open=false;}
 matches(sel){if(sel==='button')return this.tagName==='BUTTON';if(sel[0]==='#')return this.id===sel.slice(1);const m=/^\[data-([\w-]+)(?:="([^"]*)")?\]$/.exec(sel);if(m)return this.dataset[m[1]]!==undefined&&(m[2]===undefined||this.dataset[m[1]]===m[2]);return false;}
 closest(sel){return this.matches(sel)?this:this.parent?.closest(sel)||null;}querySelector(sel){return this.children.find(x=>x.matches(sel))||null;}querySelectorAll(sel){return this.children.filter(x=>x.matches(sel));}}
 const html=fs.readFileSync(path.join(__dirname,'../'+slug+'.html'),'utf8');for(const m of html.matchAll(/<([a-z]+)[^>]*\bid="([^"]+)"[^>]*>/g)){const el=new Element(m[1]);el.id=m[2];elements.set(el.id,el);}
 if(saved!==null)storage.set(key,saved);const context={console,document:doc,URLSearchParams,location:{search:query},localStorage:{getItem(k){if(blocked)throw Error('denied');return storage.get(k)||null;},setItem(k,v){if(blocked)throw Error('denied');storage.set(k,v);}}};context.window=context;vm.createContext(context);for(const file of ['engine.js','levels.js','app.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,file),'utf8'),context,{filename:file});return{get:id=>elements.get(id),click:id=>elements.get(id).fire('click'),cell:i=>elements.get('board').querySelector('[data-cell="'+i+'"]'),port:p=>elements.get('board').querySelector('[data-port="'+p+'"]'),number:v=>elements.get('numberPad').querySelector('[data-value="'+v+'"]'),doc,saved:()=>JSON.parse(storage.get(key)),raw:()=>storage.get(key)};
}
function boardState(ui,id=ui.saved().index+1){return E.replay(levels[id-1],ui.saved().records[id]||[]);}function select(ui,i){ui.get('level').value=''+i;ui.get('level').fire('change');}function fill(ui,level){if(black){for(const i of level.atoms)ui.cell(i).fire('click');ui.click('check');}else{for(let i=0;i<level.n**2;i++)if(!level.givens[i]){ui.cell(i).fire('click');ui.number(level.solution[i]).fire('click');}}}
let ui=setup();assert.equal(ui.get('level').options.length,50);assert.equal(ui.saved().index,0);
if(black){ui.port(0).fire('click');assert.equal(boardState(ui).probes.length,1);ui.click('undo');assert.equal(boardState(ui).probes.length,0);ui.cell(0).fire('click');assert.deepEqual(boardState(ui).marks,[0]);ui.click('excludeMode');ui.cell(0).fire('click');assert.deepEqual(boardState(ui).marks,[]);assert.deepEqual(boardState(ui).excluded,[0]);ui.click('undo');assert.deepEqual(boardState(ui).marks,[0]);ui.click('atomMode');}else{const i=levels[0].givens.findIndex(v=>!v);ui.cell(i).fire('click');ui.click('noteMode');ui.number(2).fire('click');assert.equal(boardState(ui).notes[i],1<<2);ui.click('undo');assert.equal(boardState(ui).notes[i],0);ui.click('valueMode');ui.number(1).fire('click');assert.equal(boardState(ui).grid[i],1);ui.click('check');assert.match(ui.get('status').textContent,/衝突|橘色/);}
// Every help feature leaves the actual puzzle unchanged; it may only add assist markers.
let before=boardState(ui);ui.click('hint');let after=boardState(ui);assert.deepEqual(black?after.marks:after.grid,black?before.marks:before.grid);assert(after.assisted);ui.click('solution');assert(ui.get('solutionDialog').open);after=boardState(ui);assert.deepEqual(black?after.marks:after.grid,black?before.marks:before.grid);assert(!after.won);ui.click('closeSolution');assert(!ui.get('solutionDialog').open);
// Reset requires explicit acceptance; cancellation preserves all actions.
const length=ui.saved().records[1].length;ui.click('restart');assert(ui.get('confirmDialog').open);ui.click('cancelConfirm');assert.equal(ui.saved().records[1].length,length);ui.click('restart');ui.click('acceptConfirm');assert.equal((ui.saved().records[1]||[]).length,0);
// Wrong answers are never accepted, even when saved with forged completion fields.
if(black){const l=levels[0],wrong=Array.from({length:l.n**2},(_,i)=>i).filter(i=>!l.atoms.includes(i)).slice(0,l.atoms.length);for(const i of wrong)ui.cell(i).fire('click');ui.click('check');assert(!boardState(ui).won);assert(ui.get('win').hidden);}else{const l=levels[0];for(let i=0;i<l.n**2;i++)if(!l.givens[i]){ui.cell(i).fire('click');ui.number(1).fire('click');}assert(!boardState(ui).won);ui.click('check');assert.match(ui.get('status').textContent,/橘色/);}
const forged=ui.saved();forged.won=true;forged.progress=50;ui=setup(JSON.stringify(forged));assert(ui.get('win').hidden);assert(ui.get('progress').innerHTML.startsWith('0<'));
// Switching away and back and reloading preserves current progress.
const old=JSON.stringify(ui.saved().records[1]);select(ui,49);assert.equal(ui.saved().index,49);select(ui,0);assert.equal(JSON.stringify(ui.saved().records[1]),old);ui=setup(ui.raw());assert.equal(JSON.stringify(ui.saved().records[1]),old);
// Play all 50 official solutions through the real delegated UI handlers.
ui=setup();for(let i=0;i<50;i++){select(ui,i);fill(ui,levels[i]);assert(!ui.get('win').hidden,'UI win '+(i+1));assert(boardState(ui).won);}
assert(ui.get('progress').innerHTML.startsWith('50<'));const finished=ui.raw();ui=setup(finished);assert(ui.get('progress').innerHTML.startsWith('50<'));ui.click('undo');assert(!boardState(ui).won);assert(ui.get('win').hidden);assert(ui.get('progress').innerHTML.startsWith('49<'));ui=setup(ui.raw());assert(!boardState(ui).won);
// Corrupt one record, preserve other completed records.
const damaged=JSON.parse(finished);damaged.records[25]=[{type:black?'mark':'set',i:-1,v:2}];ui=setup(JSON.stringify(damaged));assert(ui.get('progress').innerHTML.startsWith('49<'));assert.match(ui.get('status').textContent,/無法驗證/);
ui=setup('{broken');assert.match(ui.get('status').textContent,/無法驗證/);ui=setup(null,true);assert.match(ui.get('save').textContent,/不可用/);
// Keyboard and deep-link navigation.
ui=setup(null,false,'?level=50');assert.equal(ui.saved().index,49);if(black){const b=ui.cell(0);b.fire('keydown',{key:'ArrowRight'});assert.equal(ui.doc.activeElement.dataset.cell,'1');ui.cell(0).fire('keydown',{key:'x'});assert.equal(ui.get('excludeMode').attrs['aria-pressed'],'true');}else{ui.cell(0).fire('click');ui.cell(0).fire('keydown',{key:'ArrowRight'});assert.equal(ui.doc.activeElement.dataset.cell,'1');ui.cell(1).fire('keydown',{key:'n'});assert.equal(ui.get('noteMode').attrs['aria-pressed'],'true');}
console.log('PASS '+slug+': 50 actual-handler wins, false-answer rejection, probes/marks or values/notes, undo, non-destructive hint/solution, reset confirmation/cancel, all-level persistence, corruption isolation, forged-win rejection, blocked storage, keyboard, level-50 deep link. No browser/render claim.');

fs.writeFileSync(path.join(__dirname,'ui-test-report.json'),JSON.stringify({passed:true,levelsPlayedThroughRealHandlers:50,scope:'Node event-driven DOM mock; no browser rendering',tests:['all-level UI completion','false answers','undo after win','non-destructive hint and solution','reset confirmation and cancellation','all-level save/reload','corruption isolation','forged-win rejection','blocked storage','keyboard','level-50 deep link']},null,2)+'\n');
