(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.BoardEngine=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const N=8,DIR=[[-1,-1],[-1,0],[-1,1],[0,-1],[0,1],[1,-1],[1,0],[1,1]],CORNERS=[0,7,56,63];
const WEIGHTS=[100,-25,12,6,6,12,-25,100,-25,-45,-3,-3,-3,-3,-45,-25,12,-3,4,2,2,4,-3,12,6,-3,2,1,1,2,-3,6,6,-3,2,1,1,2,-3,6,12,-3,4,2,2,4,-3,12,-25,-45,-3,-3,-3,-3,-45,-25,100,-25,12,6,6,12,-25,100];
function initial(){const board=Array(64).fill(0);board[27]=board[36]=-1;board[28]=board[35]=1;return{board,turn:1,over:false,winner:0,last:-1,passed:0,ply:0};}
function flips(board,index,player){if(!Number.isInteger(index)||index<0||index>=64||board[index]!==0)return[];const r=index>>3,c=index%8,out=[];for(const[dr,dc]of DIR){let y=r+dr,x=c+dc,line=[];while(y>=0&&y<8&&x>=0&&x<8&&board[y*8+x]===-player){line.push(y*8+x);y+=dr;x+=dc;}if(line.length&&y>=0&&y<8&&x>=0&&x<8&&board[y*8+x]===player)out.push(...line);}return out;}
function legalMoves(state,player=state.turn){if(state.over)return[];const result=[];for(let i=0;i<64;i++)if(!state.board[i]&&flips(state.board,i,player).length)result.push(i);return result;}
function counts(state){return state.board.reduce((a,v)=>(v===1?a.black++:v===-1?a.white++:a.empty++,a),{black:0,white:0,empty:0});}
function normalize(state){const s={...state,board:state.board.slice(),passed:0};if(legalMoves({...s,over:false}).length)return s;const old=s.turn;s.turn=-s.turn;if(legalMoves({...s,over:false}).length){s.passed=old;return s;}s.over=true;const c=counts(s);s.winner=Math.sign(c.black-c.white);return s;}
function play(state,index){if(state.over)return null;const captured=flips(state.board,index,state.turn);if(!captured.length)return null;const board=state.board.slice();board[index]=state.turn;for(const i of captured)board[i]=state.turn;return normalize({board,turn:-state.turn,over:false,winner:0,last:index,passed:0,ply:state.ply+1});}
function evaluate(s,p){const c=counts(s);if(s.over)return s.winner===0?0:s.winner===p?100000+(c.black-c.white)*p:-100000+(c.black-c.white)*p;let positional=0,frontier=0,stable=0;for(let i=0;i<64;i++){if(!s.board[i])continue;positional+=s.board[i]*WEIGHTS[i];const r=i>>3,c=i%8;if(DIR.some(([dr,dc])=>r+dr>=0&&r+dr<8&&c+dc>=0&&c+dc<8&&!s.board[(r+dr)*8+c+dc]))frontier-=s.board[i];}for(const corner of CORNERS){if(!s.board[corner])continue;stable+=s.board[corner]*25;const r=corner>>3,c=corner%8;for(const[dr,dc]of [[r? -1:1,0],[0,c?-1:1]]){let y=r+dr,x=c+dc;while(y>=0&&y<8&&x>=0&&x<8&&s.board[y*8+x]===s.board[corner]){stable+=s.board[corner]*8;y+=dr;x+=dc;}}}const mobility=legalMoves(s,1).length-legalMoves(s,-1).length;return p*(positional*2+mobility*(c.empty>20?15:8)+frontier*5+stable+(c.black-c.white)*(c.empty<16?8:1));}
function* search(state,level='normal',options={}){if(state.over)return{move:null,nodes:0,depth:0};let moves=legalMoves(state);if(!moves.length)return{move:null,nodes:0,depth:0};const cfg={easy:{depth:1,nodes:250,ms:80},normal:{depth:3,nodes:5000,ms:300},hard:{depth:6,nodes:50000,ms:1100}}[level]||{depth:3,nodes:5000,ms:300};const maxNodes=options.maxNodes??cfg.nodes,deadline=Date.now()+(options.timeMs??cfg.ms),p=state.turn;let nodes=0,completedDepth=0,best=moves[0];const rng=options.random||Math.random,abort={};
function ordered(s,preferred){return legalMoves(s).map(m=>({m,v:WEIGHTS[m]+(m===preferred?1000:0)+flips(s.board,m,s.turn).length})).sort((a,b)=>b.v-a.v||a.m-b.m).map(x=>x.m);}
function* visit(s,d,alpha,beta){nodes++;if(nodes>maxNodes||Date.now()>deadline)throw abort;if(nodes%16===0)yield{nodes};if(s.over||d===0)return evaluate(s,p);const list=ordered(s);let value=s.turn===p?-Infinity:Infinity;for(const m of list){const score=yield*visit(play(s,m),d-1,alpha,beta);if(s.turn===p){value=Math.max(value,score);alpha=Math.max(alpha,value);}else{value=Math.min(value,score);beta=Math.min(beta,value);}if(alpha>=beta)break;}return value;}
if(level==='easy'){const ranked=moves.map(m=>({m,v:evaluate(play(state,m),p)+rng()*110})).sort((a,b)=>b.v-a.v);return{move:ranked[0].m,nodes:moves.length,depth:1};}
const depthLimit=options.maxDepth??(level==='hard'&&counts(state).empty<=10?counts(state).empty:cfg.depth);moves=ordered(state);best=moves[0];for(let depth=1;depth<=depthLimit;depth++){let roundBest=best,value=-Infinity;try{for(const m of moves){const score=yield*visit(play(state,m),depth-1,value,Infinity);if(score>value){value=score;roundBest=m;}}best=roundBest;completedDepth=depth;moves=ordered(state,best);if(Math.abs(value)>=100000)break;}catch(error){if(error!==abort)throw error;break;}yield{nodes,depth:completedDepth};}return{move:best,nodes,depth:completedDepth};}
function chooseMove(s,l,o){const it=search(s,l,o);let r;do{r=it.next();}while(!r.done);return r.value;}
async function chooseMoveAsync(s,l,o={}){const it=search(s,l,o);while(true){if(o.signal?.aborted)return null;const start=Date.now();let r;do{r=it.next();if(r.done)return o.signal?.aborted?null:r.value;}while(Date.now()-start<7);await new Promise(resolve=>setTimeout(resolve,0));}}
return{N,initial,flips,legalMoves,counts,normalize,play,evaluate,search,chooseMove,chooseMoveAsync};
});
