'use strict';const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),E=require('./engine.js');let checks=0;const ok=(x,msg)=>{assert.ok(x,msg);checks++},eq=(a,b,msg)=>{assert.deepEqual(a,b,msg);checks++};const levels=['easy','normal','hard'];const seeded=seed=>()=>((seed=(Math.imul(seed,1664525)+1013904223)>>>0)/4294967296);
function reference(board,index,p){if(board[index]||index<0||index>63)return[];const out=[];for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){if(!dy&&!dx)continue;let r=Math.floor(index/8)+dy,c=index%8+dx,line=[];while(r>=0&&r<8&&c>=0&&c<8){let v=board[r*8+c];if(v===-p)line.push(r*8+c);else{if(v===p&&line.length)out.push(...line);break;}r+=dy;c+=dx;}}return out.sort((a,b)=>a-b);}
function legal(s,p=s.turn){return s.board.map((_,i)=>i).filter(i=>reference(s.board,i,p).length);}
let s=E.initial();eq(E.legalMoves(s),[19,26,37,44]);eq(E.counts(s),{black:2,white:2,empty:60});ok(!E.play(s,0));ok(!E.play(s,-1));ok(!E.play(s,64));ok(!E.play(s,19.2));const original=JSON.stringify(s);let after=E.play(s,19);eq(JSON.stringify(s),original);eq(E.counts(after),{black:4,white:1,empty:59});eq(after.turn,-1);
const radial=E.initial();radial.board.fill(0);radial.turn=1;for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){if(!dy&&!dx)continue;radial.board[(3+dy)*8+3+dx]=-1;radial.board[(3+2*dy)*8+3+2*dx]=1;}eq(E.flips(radial.board,27,1).length,8);eq(E.counts(E.play(radial,27)).black,17);
const noChain=E.initial();noChain.board.fill(0);noChain.board[1]=-1;noChain.board[2]=1;noChain.board[9]=-1;noChain.board[17]=1;eq(E.play(noChain,0).board[9],-1);const wrap=Array(64).fill(0);wrap[7]=-1;wrap[8]=1;eq(E.flips(wrap,6,1),[]);
const pass={board:[-1,-1,-1,-1,-1,1,0,0,-1,-1,-1,-1,1,0,0,0,-1,1,1,1,0,0,0,0,0,0,1,1,1,0,0,0,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],turn:-1,over:false,winner:0,last:5,passed:0,ply:17};const passed=E.play(pass,6);eq(passed.passed,1);eq(passed.turn,-1);ok(!passed.over);eq(legal(passed,1),[]);ok(legal(passed,-1).length>0);
let terminal=E.initial();terminal.board.fill(1);terminal.board[0]=0;terminal=E.normalize(terminal);ok(terminal.over);eq(terminal.winner,1);eq(E.counts(terminal).empty,1);eq(E.chooseMove(terminal,'hard').move,null);ok(!E.play(terminal,0));let draw=E.initial();draw.board=draw.board.map((_,i)=>i%2?1:-1);draw=E.normalize(draw);ok(draw.over);eq(draw.winner,0);
const corner=E.initial();corner.board.fill(0);corner.board[1]=-1;corner.board[2]=1;corner.board[19]=-1;corner.board[20]=1;let tactics=0;const effort={};for(const level of levels){const result=E.chooseMove(E.initial(),level,{random:seeded(9)});ok(legal(E.initial()).includes(result.move));effort[level]={nodes:result.nodes,depth:result.depth};eq(E.chooseMove(corner,level,{random:seeded(2)}).move,0);tactics++;}ok(effort.hard.nodes>effort.normal.nodes);ok(effort.normal.nodes>effort.easy.nodes);
function referencePlay(st,m){const board=st.board.slice();board[m]=st.turn;for(const i of reference(st.board,m,st.turn))board[i]=st.turn;const next={board,turn:-st.turn};if(!legal(next).length){next.turn=st.turn;if(!legal(next).length)next.over=true;}return next;}
function solve(st,p){if(st.over)return st.board.reduce((sum,v)=>sum+v*p,0);const values=legal(st).map(m=>solve(referencePlay(st,m),p));return st.turn===p?Math.max(...values):Math.min(...values);}
for(let seed=1;seed<=6;seed++){let st=E.initial(),rng=seeded(seed*901);while(!st.over&&E.counts(st).empty>6){const list=E.legalMoves(st);st=E.play(st,list[Math.floor(rng()*list.length)]);}if(st.over)continue;const list=legal(st),values=list.map(m=>solve(referencePlay(st,m),st.turn)),best=Math.max(...values),chosen=E.chooseMove(st,'hard',{maxNodes:1000000,timeMs:10000}).move;ok(list.includes(chosen));eq(Math.sign(values[list.indexOf(chosen)]),Math.sign(best),'Hard endgame preserves independently solved result');tactics++;}
let games=0,moves=0,passCount=0,terminalCount=0;const seeds=[];for(const level of levels)for(let run=1;run<=3;run++){const seed=run*173;seeds.push(level+':'+seed);let st=E.initial(),rng=seeded(seed);for(let ply=0;ply<60&&!st.over;ply++){const ref=legal(st);eq(E.legalMoves(st),ref);const result=E.chooseMove(st,level,{random:rng,maxNodes:900,timeMs:10000});ok(ref.includes(result.move),'AI legal '+level);const next=E.play(st,result.move),f=reference(st.board,result.move,st.turn);eq(next.board[result.move],st.turn);for(let i=0;i<64;i++)eq(next.board[i],i===result.move||f.includes(i)?st.turn:st.board[i]);eq(E.counts(next).empty,E.counts(st).empty-1);if(next.passed){eq(legal(next,next.passed),[]);passCount++;}st=next;moves++;}ok(st.over);eq(legal(st,1).length+legal(st,-1).length,0);eq(st.winner,Math.sign(E.counts(st).black-E.counts(st).white));games++;terminalCount++;}
let report={};const file=path.join(__dirname,'verification.json');try{report=JSON.parse(fs.readFileSync(file))}catch{}report={...report,schemaVersion:1,game:'reversi',difficultyLevels:levels,rules:{passed:true,assertions:checks,fixtures:9,independentOracle:true},AI:{passed:true,legalAllDifficulties:true,defaultEffort:effort},tactics:{passed:true,fixtures:tactics,description:'Corner capture at each difficulty; six independently exhaustively solved endgame outcomes'},selfPlay:{passed:true,games,moves,passes:passCount,terminalCount,seeds},browserQA:'Not run here; publisher performs deployed browser QA'};report.passed=!!(report.rules.passed&&report.controller?.passed);fs.writeFileSync(file,JSON.stringify(report,null,2)+'\n');console.log(`Reversi rules/AI: ${checks} assertions, ${games} seeded complete games, ${moves} legal moves, ${passCount} passes`);
