/* Original bounded 32×32 navigation fields. Cached by topology revision, never serialized. */
(function(root){'use strict';const SIZE=32,D=[[1,0],[0,1],[-1,0],[0,-1]],cache=new WeakMap();
function field(s,end,allowQueue){let c=cache.get(s);if(!c||c.revision!==s.topology){c={revision:s.topology,fields:new Map(),queues:new Map(),hits:0,misses:0};cache.set(s,c);}const key=end[0]+','+end[1]+','+allowQueue;if(c.fields.has(key)){c.hits++;return c.fields.get(key);}c.misses++;const dist=new Int16Array(1024).fill(-1),q=new Int16Array(1024);let head=0,tail=0;const valid=(x,y)=>x>=0&&y>=0&&x<32&&y<32,walk=k=>s.map[k].path&&(allowQueue||s.map[k].path!=='queue'),height=k=>s.map[k].height+(s.map[k].path==='bridge'?1:0);if(valid(...end)){const k=end[1]*32+end[0];if(walk(k)){dist[k]=0;q[tail++]=k;}}
while(head<tail){const k=q[head++],x=k%32,y=k>>5;for(const [dx,dy]of D){const nx=x+dx,ny=y+dy,n=ny*32+nx;if(valid(nx,ny)&&dist[n]<0&&walk(n)&&Math.abs(height(k)-height(n))<=1){dist[n]=dist[k]+1;q[tail++]=n;}}}if(c.fields.size>=128)c.fields.delete(c.fields.keys().next().value);c.fields.set(key,dist);return dist;}
function route(s,start,end,allowQueue=true){if(!Array.isArray(start)||!Array.isArray(end)||![...start,...end].every(Number.isInteger)||[...start,...end].some(n=>n<0||n>=32))return null;const d=field(s,end,allowQueue);let k=start[1]*32+start[0];if(d[k]<0)return null;const out=[];while(d[k]>0){const x=k%32,y=k>>5;let next=-1;for(const[dx,dy]of D){const nx=x+dx,ny=y+dy,n=ny*32+nx;if(nx>=0&&ny>=0&&nx<32&&ny<32&&d[n]===d[k]-1&&Math.abs(s.map[k].height+(s.map[k].path==='bridge'?1:0)-s.map[n].height-(s.map[n].path==='bridge'?1:0))<=1){next=n;break;}}if(next<0)return null;k=next;out.push([k%32,k>>5]);}return out;}
function cachedQueue(s,id,make){field(s,s.gate,false);const c=cache.get(s);if(!c.queues.has(id))c.queues.set(id,make());return c.queues.get(id);}
function connected(s,point,allowQueue=false){if(!Array.isArray(point)||point.length!==2||!point.every(n=>Number.isInteger(n)&&n>=0&&n<32))return false;return field(s,s.gate,allowQueue)[point[1]*32+point[0]]>=0;}
function profile(s){const c=cache.get(s);return c?{navigationCacheHits:c.hits,navigationCacheMisses:c.misses,navigationFields:c.fields.size}:{};}
const API={route,cachedQueue,profile,connected};if(typeof module!=='undefined')module.exports=API;else root.ParkSpatial=API;})(typeof globalThis!=='undefined'?globalThis:this);
