'use strict';
const hash=x=>require('node:crypto').createHash('sha256').update(typeof x==='string'||Buffer.isBuffer(x)?x:JSON.stringify(x)).digest('hex');
function permute(a){if(a.length<2)return[a];return a.flatMap((x,i)=>permute(a.filter((_,j)=>j!==i)).map(t=>[x,...t]));}
function graphKey(l){let n=l.points.length,m=Array.from({length:n},()=>Array(n).fill('')),labels=Array(n).fill('');if(l.kind==='tour'){m=l.distance.map(r=>r.map(String));labels[0]='depot';}else{labels[l.start]+='S';labels[l.goal]+='G';if(l.kind==='stairs')labels[l.key]+='K';if(l.kind==='energy')l.chargers.forEach(c=>labels[c.p]+='C'+c.amount);for(let e of l.edges){if(l.kind==='energy'){m[e.a][e.b]+='e'+e.cost+'/'+e.capacity+';';}else{let[a,b,z]=e;if(l.kind==='stairs'&&z){m[a][b]+='forward;';m[b][a]+='back;';}else{m[a][b]+='edge;';m[b][a]+='edge;';}}}}
const normalize=a=>{let u=[...new Set(a)].sort();return a.map(x=>u.indexOf(x));};let colors=normalize(labels);
for(let z=0;z<n;z++){let c=normalize(colors.map((v,i)=>v+'|'+m[i].map((e,j)=>e?e+':'+m[j][i]+':'+colors[j]:'').filter(Boolean).sort().join('|')));if(c.every((v,i)=>v===colors[i]))break;colors=c;}
let groups=[...new Set(colors)].sort((a,b)=>a-b).map(c=>colors.map((v,i)=>v===c?i:-1).filter(i=>i>=0)),best=null;
function visit(k,order){if(k===groups.length){let key=JSON.stringify([order.map(i=>labels[i]),order.map(i=>order.map(j=>m[i][j]))]);if(best===null||key<best)best=key;return;}for(let p of permute(groups[k]))visit(k+1,[...order,...p]);}visit(0,[]);return JSON.stringify([l.kind,l.capacity,l.energy,l.reserve,best]);}
function gridKey(l){const isKnight=l.kind==='knight',raw=isKnight?Array.from({length:l.w*l.h},(_,i)=>+l.cells.includes(i)):l.kind==='dual'?l.maps[0].map((x,i)=>[x,l.maps[1][i]]):l.cells;
const used=raw.map((x,i)=>(Array.isArray(x)?x.some(Boolean):!!x)?i:-1).filter(i=>i>=0),xs=used.map(i=>i%l.w),ys=used.map(i=>Math.floor(i/l.w)),minx=Math.min(...xs),miny=Math.min(...ys),W=Math.max(...xs)-minx+1,H=Math.max(...ys)-miny+1;
let keys=[],palettes=l.kind==='color'?permute([0,1,2]):[[0,1,2]];
for(let t=0;t<8;t++){if(l.kind==='dual'&&t>=4)continue;const xy=i=>{let x=i%l.w-minx,y=Math.floor(i/l.w)-miny;if(t&1)x=W-1-x;if(t&2)y=H-1-y;return t&4?[y,x]:[x,y];},pos=i=>xy(i).join(',');for(let palette of palettes){const tile=v=>l.kind==='color'?(v>=5?5+palette[v-5]:v>=2?2+palette[v-2]:v):v;let cells=used.map(i=>[pos(i),Array.isArray(raw[i])?raw[i]:tile(raw[i])]).sort((a,b)=>a[0].localeCompare(b[0]));let base={kind:l.kind,cells};if(l.kind==='dual'){for(let swap=0;swap<2;swap++)keys.push(JSON.stringify({...base,cells:cells.map(([p,v])=>[p,swap?v.slice().reverse():v]),start:l.start.map(pos)[swap?'reverse':'slice'](),goal:l.goal.map(pos)[swap?'reverse':'slice'](),mirror:l.mirror}));}else if(l.kind==='tether'){keys.push(JSON.stringify({...base,rope:l.rope.map(pos),goal:l.goal.map(pos),length:l.length}));keys.push(JSON.stringify({...base,rope:l.rope.map(pos).reverse(),goal:l.goal.map(pos).reverse(),length:l.length}));}else keys.push(JSON.stringify({...base,start:pos(l.start),goal:l.goal===undefined?null:pos(l.goal),closed:l.closed||false,period:l.period,portals:l.portals?.map(pos).sort(),color:l.color===undefined?undefined:palette[l.color]}));}}
return keys.sort()[0];}
function canonical(l){return hash(l.points?graphKey(l):gridKey(l));}
module.exports={canonical,hash,graphKey,gridKey};
