(function(){
'use strict';
const E=window.SlidingEngine,DATA=window.SLIDING_LEVEL_DATA,LEVELS=DATA.levels,$=id=>document.getElementById(id),KEY='arcade-sliding-blocks-v1';
const tiers=['初陣','佈陣','深謀','重圍','絕境'],arrows={up:'↑',down:'↓',left:'←',right:'→'};
let index=0,state,history=[],selected=-1,records={},cert=[],certMap=new Map(),hintMove=null,timer=null,pending=null,assisted=false,storageOK=true,drag=null,suppressClick=false;
function title(i){const p=LEVELS[index].pieces[i];if(i===0)return '曹操';const group=LEVELS[index].pieces.slice(0,i+1).filter(q=>q[2]===p[2]&&q[3]===p[3]).length;return (p[2]===1&&p[3]===2?'直將':p[2]===2?'橫將':'小卒')+group;}
function moveText(m,generic=false){const i=state.findIndex(p=>p[1]*4+p[0]===m[0]&&p[2]===m[2]&&p[3]===m[3]);const dx=m[1]%4-m[0]%4,dy=Math.floor(m[1]/4)-Math.floor(m[0]/4);return `${i>=0&&!generic?title(i):m[2]===2&&m[3]===2?'曹操':m[2]===1&&m[3]===2?'直將':m[2]===2?'橫將':'小卒'}（第 ${Math.floor(m[0]/4)+1} 列、第 ${m[0]%4+1} 欄）${dx<0?'←':dx>0?'→':dy<0?'↑':'↓'} ${Math.abs(dx||dy)} 格`;}
function notice(s){$('status').textContent=s;}
function position(){return certMap.get(E.canonical(state))??-1;}
function stop(){if(timer!==null){clearInterval(timer);timer=null;}$('solution').textContent='☷ 完整解答';$('play').textContent='▶ 播放';}
function save(){try{localStorage.setItem(KEY,JSON.stringify({version:1,index,records,run:{state,history,assisted}}));storageOK=true;}catch{storageOK=false;}$('record').textContent=storageOK?(records[index+1]?`最佳紀錄：${records[index+1].best} 步 · 自動存檔已開啟`:'進度會儲存在這個瀏覽器'):'瀏覽器無法儲存；本次仍可遊玩，關閉後進度可能遺失';}
function readSaved(){try{const raw=localStorage.getItem(KEY);if(!raw||raw.length>5000000)return null;const d=JSON.parse(raw);if(d.version!==1)return null;for(const[id,r]of Object.entries(d.records||{})){const l=LEVELS[Number(id)-1];if(!l||String(l.id)!==id||!r||!Array.isArray(r.solution)||r.solution.length>10000||r.best!==r.solution.length)continue;let s=E.clone(l.pieces);for(const m of r.solution){s=E.apply(s,m);if(!s)break;}if(s&&E.won(s))records[id]={best:r.best,solution:r.solution};}return d;}catch{return null;}}
function levelsUI(){$('levelGrid').innerHTML=LEVELS.map((l,i)=>`<button data-level="${i}" data-tier="${l.tier}" class="${i===index?'current ':''}${records[l.id]?'solved':''}" aria-label="第 ${l.id} 關，${tiers[l.tier]}，最短 ${l.optimal} 步${records[l.id]?'，已通關':''}">${String(l.id).padStart(2,'0')}${records[l.id]?' ✓':''}<small>${l.optimal} 步</small></button>`).join('');}
function render(){
 const l=LEVELS[index];$('levelsOpen').textContent=`關卡 ${String(l.id).padStart(2,'0')} / 50`;$('levelName').textContent=l.name;$('tier').textContent=tiers[l.tier];$('moves').textContent=history.length;$('optimal').textContent=l.optimal;$('completed').textContent=`${Object.keys(records).length} / 50`;
 let html=state.map(([x,y,w,h],i)=>`<button class="piece ${i===0?'target':w===2?'horizontal':h===1?'soldier':'vertical'}${i===selected?' selected':''}${hintMove&&y*4+x===hintMove[0]&&w===hintMove[2]&&h===hintMove[3]?' hinted':''}" data-piece="${i}" style="left:calc(${x*25}% + 3px);top:calc(${y*20}% + 3px);width:calc(${w*25}% - 6px);height:calc(${h*20}% - 6px)" aria-pressed="${i===selected}" aria-label="${title(i)}，${w} 乘 ${h}，第 ${y+1} 列、第 ${x+1} 欄"><strong>${i===0?'曹操':title(i)}</strong><small>${i===0?'突 圍':w+' × '+h}</small></button>`).join('');
 if(selected>=0&&!E.won(state)){const p=state[selected];for(const m of E.moves(state).filter(m=>m[0]===p[1]*4+p[0]&&m[2]===p[2]&&m[3]===p[3])){const dx=m[1]%4-p[0],dy=Math.floor(m[1]/4)-p[1];html+=`<button class="landing${E.same(m,hintMove)?' hint-landing':''}" data-move="${m.join(',')}" style="left:${(m[1]%4+p[2]/2)*25}%;top:${(Math.floor(m[1]/4)+p[3]/2)*20}%" aria-label="${moveText(m)}">${dx<0?'←':dx>0?'→':dy<0?'↑':'↓'}${Math.abs(dx||dy)}</button>`;}}
 $('board').innerHTML=html;$('selection').textContent=selected>=0?`已選：${title(selected)}`:'點選一枚棋子';$('undo').disabled=!history.length;$('hint').disabled=E.won(state);$('finish').hidden=!E.won(state);
 document.querySelectorAll('[data-dir]').forEach(b=>b.disabled=selected<0||E.won(state));
 if(E.won(state)){$('finishText').textContent=assisted?`解答示範完成，共 ${history.length} 步`:`${history.length} 步出關${history.length===l.optimal?'，達成最短解！':'，最短解為 '+l.optimal+' 步'}`;$('next').textContent=index===49?'回到選關 →':'下一關 →';}
 save();
}
function load(i,run=null){stop();index=Math.max(0,Math.min(49,i));const l=LEVELS[index];state=E.clone(l.pieces);history=[];selected=-1;hintMove=null;assisted=false;cert=E.certifiedStates(l);certMap=new Map(cert.map((s,k)=>[E.canonical(s),k]));const checked=run&&E.validateRun(l,run);if(checked){state=checked.state;history=checked.history;assisted=!!run.assisted;}render();notice(checked?'已恢復上次盤面。點棋子繼續。':`第 ${l.id} 關 · ${tiers[l.tier]}。先替曹操騰出通道。`);}
function commit(m,demo=false){const next=E.apply(state,m);if(!next||E.won(state))return false;if(!demo)stop();const p=state.findIndex(p=>p[1]*4+p[0]===m[0]&&p[2]===m[2]&&p[3]===m[3]),text=moveText(m);history.push(E.clone(state));state=next;selected=p;hintMove=null;if(demo)assisted=true;if(E.won(state)){stop();if(!assisted&&(!records[index+1]||history.length<records[index+1].best)){const chain=[...history,state],solution=[];for(let i=1;i<chain.length;i++)solution.push(E.transition(chain[i-1],chain[i]));records[index+1]={best:history.length,solution};}notice(assisted?'解答示範完成！重來後可以自己挑戰。':'成功出關！可以復原研究其他解法，或前往下一關。');}else notice(demo?`示範第 ${history.length} 步：${text}`:text);render();return true;}
function undo(){stop();if(!history.length)return;state=history.pop();hintMove=null;selected=-1;render();notice('已復原一步。所有走過的步驟都可以復原。');}
function reset(){load(index);}
function askReset(after,reason){stop();pending=after;$('resetText').textContent=reason;$('resetDialog').showModal();}
function needRoute(after){if(position()>=0){after();return;}askReset(()=>{reset();after();},'目前盤面已離開內建解答路線。要使用這份提示或解答，需要回到本關起點；本次步數與復原紀錄會清除。已通關的紀錄不受影響。');}
function hint(){stop();needRoute(()=>{const n=position();if(n<0||n>=LEVELS[index].solution.length){notice('曹操已抵達出口。');return;}hintMove=LEVELS[index].solution[n];selected=state.findIndex(p=>p[1]*4+p[0]===hintMove[0]&&p[2]===hintMove[2]&&p[3]===hintMove[3]);render();notice(`提示：${moveText(hintMove)}。點亮色落點完成這一步。`);});}
function solutionList(){const n=position(),l=LEVELS[index];$('solutionNote').textContent=`本關最短解 ${l.optimal} 步。你目前位於解答的第 ${Math.max(0,n)} 步。每列標示移動前的列／欄。`;$('solutionList').innerHTML=l.solution.map((m,i)=>`<li class="${i<n?'done':i===n?'active':''}">${moveText(m,true)}</li>`).join('');$('play').disabled=n>=l.solution.length;$('step').disabled=n>=l.solution.length;}
function showSolution(){if(timer!==null){stop();notice('已暫停解答示範。可以復原、繼續遊玩，或再次開啟解答。');return;}needRoute(()=>{solutionList();$('solutionDialog').showModal();});}
function step(){const n=position();if(n<0||n>=LEVELS[index].solution.length){stop();return false;}return commit(LEVELS[index].solution[n],true);}
function play(){if($('solutionDialog').open)$('solutionDialog').close();stop();if(E.won(state))return;notice('解答示範中。點「暫停解答」可隨時停下。');$('solution').textContent='⏸ 暫停解答';timer=setInterval(()=>{step();if(E.won(state))stop();},750);}
function direction(dir,long=false){if(selected<0){notice('請先點選要移動的棋子。');return;}const d={up:[0,-1],down:[0,1],left:[-1,0],right:[1,0]}[dir],p=state[selected];let best=null;for(let n=1;n<=4;n++){const x=p[0]+d[0]*n,y=p[1]+d[1]*n;if(x<0||x+p[2]>4||y<0||y+p[3]>5)break;const m=[p[1]*4+p[0],y*4+x,p[2],p[3]];if(!E.apply(state,m))break;best=m;if(!long)break;}if(best)commit(best);else notice('這個方向被擋住了，試試先移開其他棋子。');}
function dialogOpen(){return ['levelDialog','helpDialog','resetDialog','solutionDialog'].some(id=>$(id).open);}
$('board').addEventListener('click',e=>{if(suppressClick){suppressClick=false;return;}const dest=e.target.closest('[data-move]');if(dest){commit(dest.dataset.move.split(',').map(Number));return;}const b=e.target.closest('[data-piece]');if(b){stop();selected=Number(b.dataset.piece);hintMove=null;render();}});
$('board').addEventListener('pointerdown',e=>{const b=e.target.closest('[data-piece]');if(!b||e.button>0)return;stop();selected=Number(b.dataset.piece);hintMove=null;drag={x:e.clientX,y:e.clientY,id:e.pointerId,piece:selected};$('board').setPointerCapture(e.pointerId);render();});
$('board').addEventListener('pointerup',e=>{if(!drag||drag.id!==e.pointerId)return;const d=drag;drag=null;const dx=e.clientX-d.x,dy=e.clientY-d.y;if(Math.max(Math.abs(dx),Math.abs(dy))<12)return;suppressClick=true;selected=d.piece;const rect=$('board').getBoundingClientRect(),horizontal=Math.abs(dx)>Math.abs(dy),n=Math.max(1,Math.round((horizontal?Math.abs(dx)/(rect.width/4):Math.abs(dy)/(rect.height/5)))),p=state[selected],sx=horizontal?Math.sign(dx):0,sy=horizontal?0:Math.sign(dy);let m=null;for(let k=1;k<=n;k++){const x=p[0]+sx*k,y=p[1]+sy*k;if(x<0||x+p[2]>4||y<0||y+p[3]>5)break;const q=[p[1]*4+p[0],y*4+x,p[2],p[3]];if(!E.apply(state,q))break;m=q;}if(m)commit(m);else notice('這裡無法滑動，請先挪出空格。');});
$('board').addEventListener('pointercancel',()=>{drag=null;});
$('undo').onclick=undo;$('restart').onclick=()=>history.length?askReset(reset,'本次步數與復原紀錄會清除。已完成關卡與最佳紀錄仍會保留。'):reset();$('hint').onclick=hint;$('solution').onclick=showSolution;
$('helpOpen').onclick=()=>{stop();$('helpDialog').showModal();};$('levelsOpen').onclick=()=>{stop();levelsUI();$('levelDialog').showModal();};$('levelGrid').onclick=e=>{const b=e.target.closest('[data-level]');if(!b)return;$('levelDialog').close();load(Number(b.dataset.level));};
$('next').onclick=()=>index<49?load(index+1):$('levelsOpen').onclick();
$('resetCancel').onclick=()=>{pending=null;$('resetDialog').close();};$('resetConfirm').onclick=()=>{const f=pending;pending=null;$('resetDialog').close();if(f)f();};$('resetDialog').addEventListener('cancel',()=>pending=null);
$('play').onclick=play;$('step').onclick=()=>{stop();step();solutionList();};$('solutionReset').onclick=()=>{reset();solutionList();};
for(const b of document.querySelectorAll('[data-close]'))b.onclick=()=>{stop();$(b.dataset.close).close();};
for(const b of document.querySelectorAll('[data-dir]'))b.onclick=()=>direction(b.dataset.dir);
document.addEventListener('keydown',e=>{if(dialogOpen()||e.ctrlKey||e.altKey||e.metaKey)return;const map={ArrowUp:'up',ArrowDown:'down',ArrowLeft:'left',ArrowRight:'right'};if(map[e.key]){e.preventDefault();direction(map[e.key],e.shiftKey);}else if(e.key.toLowerCase()==='z'){e.preventDefault();undo();}});
document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();});
window.addEventListener('pagehide',()=>{stop();save();});
const saved=readSaved();load(saved&&Number.isInteger(saved.index)&&saved.index>=0&&saved.index<50?saved.index:0,saved?.run);
// Read-only snapshots plus ordinary actions, also exercised by the DOM harness.
window.SlidingApp={load,commit,undo,hint,showSolution,step,stop,direction,readSaved,snapshot:()=>({index,state:E.clone(state),history:history.map(E.clone),selected,records:JSON.parse(JSON.stringify(records)),assisted,position:position(),playing:timer!==null})};
})();
