(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.SudokuCore=api})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
function units(L){const n=L.size,u=[];for(let r=0;r<n;r++)u.push(Array.from({length:n},(_,c)=>r*n+c));for(let c=0;c<n;c++)u.push(Array.from({length:n},(_,r)=>r*n+c));for(let r=0;r<n;r+=L.boxRows)for(let c=0;c<n;c+=L.boxCols){const box=[];for(let y=0;y<L.boxRows;y++)for(let x=0;x<L.boxCols;x++)box.push((r+y)*n+c+x);u.push(box)}return u}
function candidates(L,values,i){if(values[i])return [];const used=new Set(units(L).filter(u=>u.includes(i)).flatMap(u=>u.map(j=>values[j])));return Array.from({length:L.size},(_,k)=>k+1).filter(v=>!used.has(v))}
function conflicts(L,values){const bad=new Set();for(const u of units(L)){const m=new Map();for(const i of u)if(values[i]){if(!m.has(values[i]))m.set(values[i],[]);m.get(values[i]).push(i)}for(const cells of m.values())if(cells.length>1)cells.forEach(i=>bad.add(i))}return bad}
function solved(L,s){return s.values.every(v=>v>0)&&conflicts(L,s.values).size===0}
function initial(L){return {values:L.clues.slice(),notes:Array.from({length:L.size*L.size},()=>[]),moves:0}}
function validState(L,s){return !!s&&Array.isArray(s.values)&&s.values.length===L.size*L.size&&s.values.every((v,i)=>Number.isInteger(v)&&v>=0&&v<=L.size&&(!L.clues[i]||v===L.clues[i]))&&Array.isArray(s.notes)&&s.notes.length===s.values.length&&s.notes.every((a,i)=>Array.isArray(a)&&a.length<=L.size&&new Set(a).size===a.length&&a.every(v=>Number.isInteger(v)&&v>=1&&v<=L.size)&&(!s.values[i]||a.length===0))&&Number.isInteger(s.moves)&&s.moves>=0&&s.moves<10000000}
function enter(L,s,i,v,note){if(!Number.isInteger(i)||i<0||i>=s.values.length||L.clues[i]||!Number.isInteger(v)||v<0||v>L.size)return false;if(note&&v){if(s.values[i])return false;const a=s.notes[i],p=a.indexOf(v);p<0?a.push(v):a.splice(p,1);a.sort((a,b)=>a-b)}else{if(s.values[i]===v&&!s.notes[i].length)return false;s.values[i]=v;s.notes[i]=[]}s.moves++;return true}
function logicalHint(L,s){const bad=conflicts(L,s.values);if(bad.size)return {type:'conflict',cell:[...bad].find(i=>!L.clues[i]),text:'紅色格有同行、同列或同宮重複，請先修正'};for(let i=0;i<s.values.length;i++)if(!s.values[i]){const c=candidates(L,s.values,i);if(c.length===1)return {type:'naked',cell:i,value:c[0],text:'唯一候選：這格只有一個數字可填'}}for(const u of units(L))for(let v=1;v<=L.size;v++){if(u.some(i=>s.values[i]===v))continue;const places=u.filter(i=>!s.values[i]&&candidates(L,s.values,i).includes(v));if(places.length===1)return {type:'hidden',cell:places[0],value:v,text:'唯一位置：這個數字在某一行、列或宮只剩一個位置'}}return null}
return {units,candidates,conflicts,solved,initial,validState,enter,logicalHint};});
