'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto'),os=require('os'),cp=require('child_process'),assert=require('assert/strict');
const root=path.resolve(__dirname,'../..'),manifest=JSON.parse(fs.readFileSync(path.join(__dirname,'release-manifest.json'),'utf8'));
const destination=fs.mkdtempSync(path.join(os.tmpdir(),'social120-isolated-'));
for(const [relative,expected]of Object.entries(manifest.sourceFiles)){assert(!path.isAbsolute(relative)&&!relative.split('/').includes('..'));const source=path.join(root,relative),contents=fs.readFileSync(source),actual=crypto.createHash('sha256').update(contents).digest('hex');assert.equal(actual,expected,'Stale binding: '+relative);const target=path.join(destination,relative);fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,contents);}
fs.copyFileSync(path.join(__dirname,'release-manifest.json'),path.join(destination,'games/social120-common/release-manifest.json'));
for(const command of [['node','games/social120-common/verify.cjs'],['node','games/social120-common/verify-ui.cjs']]){const result=cp.spawnSync(command[0],command.slice(1),{cwd:destination,encoding:'utf8',timeout:120000});if(result.status!==0)throw Error(command.join(' ')+' failed in isolated package:\n'+result.stdout+'\n'+result.stderr);}
const artHashes=new Set();for(const game of manifest.games){assert(game.artFile&&game.artPath&&game.cover,game.id+' art metadata');const art=fs.readFileSync(path.join(destination,game.artFile),'utf8');assert(art.includes('<svg')&&art.includes('<title')&&art.includes('<desc')&&art.includes('viewBox="0 0 640 400"'));assert(!/(?:href|src)=|<script|<foreignObject/i.test(art),'Non-local SVG content');const geometry=art.replace(/<title[^>]*>[\s\S]*?<\/title>|<desc[^>]*>[\s\S]*?<\/desc>/g,'');artHashes.add(crypto.createHash('sha256').update(geometry).digest('hex'));}assert.equal(artHashes.size,15,'Art must have different geometry, not renamed text');
console.log(JSON.stringify({passed:true,files:Object.keys(manifest.sourceFiles).length,isolatedEngineReplay:1500,isolatedUIControllers:15,distinctSVGGeometry:artHashes.size,packageDirectory:destination,browserQA:'not-run'},null,2));
