(()=>{'use strict';
const ID='checkers',IS_CHECKERS=true,E=IS_CHECKERS?CheckersEngine:ConnectFourEngine,$=id=>document.getElementById(id),SAVE='arcade-tabletop-'+ID+'-v1';let focus=IS_CHECKERS?40:35,selection=[],lastState=null,storageOk=true,confirmation=null,notice='',initialNotice='';
function runner(state,difficulty){let stopped=false,worker=null,timer=null,deadline=null,resolveJob,rejectJob;const promise=new Promise((resolve,reject)=>{resolveJob=resolve;rejectJob=reject});function finish(info){if(stopped)return;stopped=true;clearTimeout(timer);clearTimeout(deadline);if(worker)worker.terminate();resolveJob(info)}function fallback(){if(stopped)return;if(worker){worker.terminate();worker=null}clearTimeout(deadline);timer=setTimeout(()=>{if(stopped)return;try{finish({...E.chooseMove(state,difficulty,{timeMs:45,maxDepth:E.LIMITS[difficulty].depth}),fallback:true})}catch(e){stopped=true;rejectJob(e)}},30)}try{worker=new Worker('./'+ID+'/worker.js?v=1');worker.onmessage=event=>{if(event.data.error)fallback();else finish(event.data)};worker.onerror=event=>{event.preventDefault();fallback()};worker.postMessage({id:1,state,difficulty});deadline=setTimeout(fallback,4000)}catch(e){fallback()}return{promise,cancel(){stopped=true;clearTimeout(timer);clearTimeout(deadline);if(worker)worker.terminate()}}}
const game=new TabletopSession.Session(E,{id:ID,runner,changed:render});
try{let raw=localStorage.getItem(SAVE);if(raw){if(game.restore(raw))initialNotice='已接續這台瀏覽器的棋局';else initialNotice='存檔無法驗證，已安全開啟新棋局'}}catch(e){storageOk=false}
function save(){try{localStorage.setItem(SAVE,game.serialize())}catch(e){storageOk=false}$('saveNote').textContent=storageOk?'棋局自動儲存於此瀏覽器':'瀏覽器無法儲存 · 關閉頁面會失去進度'}
const name=side=>side===1?'紅方':'藍方';const coordinate=i=>String.fromCharCode(65+i%8)+(8-Math.floor(i/8));
function describeResult(result){if(!result)return'';if(result.winner)return name(result.winner)+'獲勝！';return'平分秋色，和局'}
function reason(result){if(!result)return'';return{four:'四顆棋子連成一線',full:'棋盤已滿，沒有任何四連',pieces:'對手已沒有棋子',blocked:'對手已沒有合法走法',repetition:'相同盤面與行棋方第三次出現',quiet:'連續 80 個半回合沒有吃子或普通棋移動'}[result.reason]||''}
function boardPreview(){let board=game.state.board.slice();if(IS_CHECKERS&&selection.length>1){let piece=board[selection[0]];board[selection[0]]=0;for(let k=1;k<selection.length;k++){let a=selection[k-1],b=selection[k];if(Math.abs(Math.floor(a/8)-Math.floor(b/8))===2)board[(a+b)/2]=0}board[selection[selection.length-1]]=piece}return board}
function eligible(){if(!IS_CHECKERS)return[];return E.legal(game.state).filter(m=>selection.every((v,k)=>m.path[k]===v))}
function say(text){notice=text;$('status').textContent=text}
function render(){let hadFocus=document.activeElement&&document.activeElement.hasAttribute&&document.activeElement.hasAttribute('data-cell');if(lastState!==game.state){selection=[];notice='';lastState=game.state}const s=game.state,end=game.result,moving=s.turn,canAct=!end&&!game.pending&&game.humanTurn;let visible=boardPreview(),dest=IS_CHECKERS&&selection.length?eligible().map(m=>m.path[selection.length]).filter(v=>v!==undefined):[];const board=$('board');board.replaceChildren();board.setAttribute('aria-busy',game.pending?'true':'false');for(let i=0;i<visible.length;i++){const b=document.createElement('button'),v=visible[i],r=Math.floor(i/(IS_CHECKERS?8:7)),c=i%(IS_CHECKERS?8:7);b.type='button';b.className='cell';b.dataset.cell=i;b.tabIndex=i===focus?0:-1;b.setAttribute('role','gridcell');b.setAttribute('aria-disabled',canAct?'false':'true');if(IS_CHECKERS){b.classList.add((r+c)%2?'dark':'light');if(v){const token=document.createElement('span');token.className='piece '+(v>0?'red':'blue')+(Math.abs(v)===2?' king':'');token.textContent=Math.abs(v)===2?'♛':'';token.setAttribute('aria-hidden','true');b.append(token)}if(selection.at(-1)===i)b.classList.add('selected');if(dest.includes(i))b.classList.add('destination');if(s.last&&s.last.path.at(-1)===i)b.classList.add('last');b.setAttribute('aria-label',coordinate(i)+'，'+(v?name(Math.sign(v))+(Math.abs(v)===2?'王棋':'普通棋'):(r+c)%2?'空格':'淺色格，不能落子')+(dest.includes(i)?'，合法落點':''));b.setAttribute('aria-selected',selection.at(-1)===i?'true':'false')}else{if(v)b.classList.add(v===1?'red':'blue');if(s.last===i)b.classList.add('last');if(end&&end.cells&&end.cells.includes(i))b.classList.add('win');b.setAttribute('aria-label','第 '+(c+1)+' 欄，第 '+(r+1)+' 列，'+(v?name(v):'空格')+'；點選在此欄投棋')}
b.onclick=()=>act(i);b.onfocus=()=>{focus=i;for(const el of board.children)el.tabIndex=el===b?0:-1};b.onkeydown=event=>boardKey(event,i);board.append(b)}
if(!IS_CHECKERS){$('columnKeys').replaceChildren();for(let c=0;c<7;c++){let button=document.createElement('button');button.textContent='↓ '+(c+1);button.setAttribute('aria-label','在第 '+(c+1)+' 欄投棋');button.disabled=!canAct||Boolean(s.board[c]);button.onclick=()=>act(35+c);$('columnKeys').append(button)}}
$('turn').textContent=end?describeResult(end):name(moving)+(game.pending?' · 電腦思考中…':' · '+(game.settings.mode==='local'?'請落子':game.humanTurn?'輪到你':'準備落子'));$('turn').className='turn-badge'+(moving===-1?' blue-turn':'');$('moveCount').textContent='第 '+(s.ply+1)+' 手'+(end?' · 已結束':'');$('mode').value=game.settings.mode;$('side').value=String(game.settings.side);$('difficulty').value=game.settings.difficulty;$('side').disabled=$('difficulty').disabled=game.settings.mode==='local';$('difficultyNote').textContent=game.settings.mode==='local'?'在同一台裝置輪流落子，一起享受對弈':({easy:'搜尋最多 2 層 · 輕鬆熟悉棋路',normal:'搜尋最多 5 層 · 攻防平衡',hard:'搜尋最多 9 層 · 深入思考局面'}[game.settings.difficulty])+' · 本機運算';
for(const [side,color]of [[1,'Red'],[-1,'Blue']]){let lower=color.toLowerCase();$('player'+color).classList.toggle('active',!end&&moving===side);$(lower+'Role').textContent=game.settings.mode==='local'?'玩家 '+(side===1?'一 · 先手':'二 · 後手'):side===game.settings.side?'你 · '+(side===1?'先手':'後手'):'電腦 · '+(side===1?'先手':'後手');$(lower+'Count').textContent=s.board.filter(v=>Math.sign(v)===side).length+(IS_CHECKERS?' 子':' 顆')}
$('resultTitle').textContent=end?describeResult(end):game.pending?'正在推敲下一步…':game.settings.mode==='local'?'把棋盤交給'+name(moving):game.humanTurn?'輪到你發揮':'電腦準備落子';let ai=game.aiInfo;$('resultNote').textContent=end?reason(end):IS_CHECKERS?(E.legal(s)[0]?.captures.length?'本回合必須吃子，亮點引導下一跳':'先選棋子，再選斜向落點'):'橫、直或斜向，先連四顆就贏';if(ai&&!end&&game.settings.mode==='ai')$('resultNote').textContent+=' · '+(ai.fallback?'相容搜尋':('電腦已搜尋 '+ai.depth+' 層'));$('resultCard').classList.toggle('ended',Boolean(end));$('undo').disabled=game.undoIndex()<0&&!selection.length;$('boardTip').textContent=IS_CHECKERS?'♛ 王棋可前後走 · 有吃必吃':'點上方箭頭或任一格，投向該欄';$('lastMove').textContent=IS_CHECKERS?(s.last?'上手 '+s.last.path.map(coordinate).join(' → '):'珊瑚紅先行'):(s.last>=0?'上手：第 '+(s.last%7+1)+' 欄':'珊瑚紅先行');$('status').textContent=notice||game.error||(end?reason(end):game.pending?'請稍候，棋盤暫時鎖定；仍可悔棋或開新局':selection.length>1?'連跳尚未完成，請點下一個亮點':IS_CHECKERS?'點棋子與亮點落子；Esc 取消尚未完成的選擇':'小圓點標示上一手，數字 1–7 也能投棋');save();if(hadFocus)focusCell(focus)}
function focusCell(i){let el=$('board').children[i];if(el){focus=i;el.focus({preventScroll:true})}}
function act(i){focus=i;if(game.pending){say('電腦正在思考，請稍候或使用悔棋');return}if(game.result){say('棋局已結束，可以悔棋或重新開局');return}if(!game.humanTurn)return;if(!IS_CHECKERS){if(!game.play(i%7))say('這一欄已滿，請選另一欄');return}const s=game.state,moves=E.legal(s),own=Math.sign(s.board[i])===s.turn;if(selection.length<=1&&own){if(moves.some(m=>m.path[0]===i)){selection=[i];notice='';render();focusCell(i)}else say(moves[0]?.captures.length?'有子可吃必須吃，請選能吃子的棋子':'這顆棋子目前沒有合法走法');return}if(selection.length){let matches=eligible().filter(m=>m.path[selection.length]===i);if(matches.length){selection.push(i);notice='';let complete=matches.find(m=>m.path.length===selection.length);if(complete){game.play(complete);focusCell(i)}else{render();focusCell(i)}return}}say(selection.length>1?'連跳必須繼續同一顆棋子，請選亮點':'先點自己的棋子，再點亮點落子')}
function boardKey(event,i){const n=IS_CHECKERS?8:7,r=Math.floor(i/n),c=i%n,arrows={ArrowUp:[-1,0],ArrowDown:[1,0],ArrowLeft:[0,-1],ArrowRight:[0,1]};if(arrows[event.key]){event.preventDefault();let[dr,dc]=arrows[event.key],rr=r+dr,cc=c+dc;if(rr>=0&&rr<(IS_CHECKERS?8:6)&&cc>=0&&cc<n)focusCell(rr*n+cc)}else if(event.key==='Enter'||event.key===' '){event.preventDefault();act(i)}}
function undo(){if(selection.length){selection=[];notice='已取消尚未提交的選擇';render();return}if(game.undo())say('已退回上一個可由你決定的回合')}
function ask(title,text,callback){if($('confirmDialog').open)return;$('confirmTitle').textContent=title;$('confirmText').textContent=text;confirmation=callback;$('confirmDialog').showModal()}
$('undo').onclick=undo;$('reset').onclick=()=>ask('重新開局？','目前棋局與悔棋記錄會清除，對局設定會保留。',()=>{selection=[];game.reset()});
function changeSetting(){const next={mode:$('mode').value,side:Number($('side').value),difficulty:$('difficulty').value};render();if(next.mode===game.settings.mode&&next.side===game.settings.side&&next.difficulty===game.settings.difficulty)return;if(game.moves.length||game.pending||selection.length)ask('切換設定並開新局？','新的對局方式、先後手或難度會從新棋局開始；目前棋局與悔棋記錄將清除。',()=>{selection=[];game.reset(next)});else game.reset(next)}
$('mode').onchange=$('side').onchange=$('difficulty').onchange=changeSetting;$('help').onclick=()=>{if(!$('helpDialog').open)$('helpDialog').showModal()};$('closeHelp').onclick=()=>$('helpDialog').close();$('cancelConfirm').onclick=()=>{confirmation=null;$('confirmDialog').close()};$('acceptConfirm').onclick=()=>{let action=confirmation;confirmation=null;$('confirmDialog').close();if(action)action()};$('confirmDialog').addEventListener('close',()=>{confirmation=null;render()});$('confirmDialog').addEventListener('cancel',()=>confirmation=null);
document.addEventListener('keydown',event=>{if($('helpDialog').open||$('confirmDialog').open)return;if(event.target&&['SELECT','INPUT','TEXTAREA'].includes(event.target.tagName))return;if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='z'){event.preventDefault();undo()}else if(event.key==='Escape'&&selection.length){selection=[];notice='已取消尚未提交的選擇';render()}else if(!IS_CHECKERS&&/^[1-7]$/.test(event.key)&&!event.ctrlKey&&!event.metaKey&&!event.altKey){event.preventDefault();act(35+Number(event.key)-1)}});window.addEventListener('pagehide',()=>{save();game.destroy()});window.addEventListener('pageshow',()=>game.startAI());game.start();if(initialNotice)say(initialNotice);
})();
