'use strict';const assert=require('node:assert/strict'),E=require('./engine.js');
function run(){let names=[],ai={},selfPlay=[];function test(name,fn){fn();names.push(name)}function fixture(pieces,turn=1,quiet=0){let board=Array(64).fill(0);for(const [i,p]of pieces)board[i]=p;let s={board,turn,ply:0,quiet,seen:{},last:null};s.seen[E.key(s)]=1;return s}const move=(s,path)=>E.apply(s,{path});
test('standard 8-by-8 opening, red first, twelve per side',()=>{let s=E.create();assert.equal(s.board.filter(v=>v===1).length,12);assert.equal(s.board.filter(v=>v===-1).length,12);assert.equal(s.turn,1);assert.equal(E.legal(s).length,7);s.board.forEach((v,i)=>{if(v)assert.equal((Math.floor(i/8)+i%8)%2,1)})});
test('men only move and capture forwards, kings both ways',()=>{let s=fixture([[26,1],[35,-1]]);assert(E.legal(s).every(m=>m.captures.length===0));assert.throws(()=>move(s,[26,44]));s=fixture([[26,2],[35,-1]]);assert.deepEqual(E.legal(s).map(m=>m.path),[[26,44]]);assert.throws(()=>move(s,[26,53]));assert.equal(move(s,[26,44]).board[44],2)});
test('global capture priority and complete multi-jump enforcement',()=>{let s=fixture([[42,1],[46,1],[33,-1],[37,-1],[19,-1]]),ms=E.legal(s);assert(ms.every(m=>m.captures.length>0));assert(ms.some(m=>m.path.join(',')==='42,24'));assert(ms.some(m=>m.path.join(',')==='46,28,10'));assert.throws(()=>move(s,[46,28]));assert.throws(()=>move(s,[42,35]));let n=move(s,[46,28,10]);assert.equal(n.board[37],0);assert.equal(n.board[19],0);assert.equal(n.board[10],1);assert.equal(n.turn,-1);assert.equal(n.ply,1);assert.equal(n.quiet,0)});
test('no maximum capture obligation and capture choice',()=>{let s=fixture([[42,1],[46,1],[33,-1],[37,-1],[19,-1]]);assert.doesNotThrow(()=>move(s,[42,24]));assert.doesNotThrow(()=>move(s,[46,28,10]))});
test('crowning stops capture immediately, new king cannot continue',()=>{let s=fixture([[17,1],[10,-1],[12,-1]]),ms=E.legal(s);assert.deepEqual(ms.map(m=>m.path),[[17,3]]);assert.throws(()=>move(s,[17,3,21]));let n=move(s,[17,3]);assert.equal(n.board[3],2);assert.equal(n.board[12],-1);assert.equal(n.turn,-1);assert.equal(n.quiet,0)});
test('blue crowns on bottom row and simple promotion',()=>{let s=fixture([[10,1],[53,-1]],-1);let n=move(s,[53,62]);assert.equal(n.board[62],-2);s=fixture([[10,1],[53,-1]]);n=move(s,[10,1]);assert.equal(n.board[1],2)});
test('no pieces or no legal move loses',()=>{let n=move(fixture([[42,1],[33,-1]]),[42,24]);assert.equal(E.outcome(n).winner,1);assert.equal(E.outcome(n).reason,'pieces');let s=fixture([[54,-1],[61,1],[63,1]],-1);assert.equal(E.outcome(s).winner,1);assert.equal(E.outcome(s).reason,'blocked');assert.equal(E.legal(s).length,0)});
test('same position and side three times automatically draws',()=>{let s=fixture([[56,2],[7,-2]]);for(let repeat=0;repeat<2;repeat++)for(const path of [[56,49],[7,14],[49,56],[14,7]])s=move(s,path);assert.equal(E.outcome(s).reason,'repetition');assert.equal(E.outcome(s).winner,0);assert.equal(E.legal(s).length,0);assert.throws(()=>move(s,[56,49]))});
test('80 king-only non-capturing half-turns draw; man/capture reset',()=>{let s=fixture([[21,2],[58,-2]],1,79),n=move(s,[21,12]);assert.equal(E.outcome(n).reason,'quiet');s=fixture([[42,1],[7,-2]],1,79);n=move(s,[42,33]);assert.equal(n.quiet,0);assert.equal(E.outcome(n),null);s=fixture([[26,2],[35,-1],[7,-2]],1,79);assert.equal(move(s,[26,44]).quiet,0)});
test('engines are immutable and illegal path/capture payload rejected',()=>{let s=E.create(),before=JSON.stringify(s);E.apply(s,E.legal(s)[0]);assert.equal(JSON.stringify(s),before);for(const m of [null,{}, {path:[1,1]}, {path:[40,41]}, {path:[42]}])assert.throws(()=>E.apply(s,m));let tactical=fixture([[42,1],[33,-1]]),n=E.apply(tactical,{path:[42,24],captures:[],promote:true});assert.equal(n.board[33],0);assert.equal(n.board[24],1)});
for(const difficulty of ['easy','normal','hard']){let tactical=fixture([[42,1],[33,-1]]),win=E.chooseMove(tactical,difficulty,{timeMs:80}),start=E.chooseMove(E.create(),difficulty,{timeMs:180});assert.deepEqual(win.move.path,[42,24]);assert.equal(E.outcome(E.apply(tactical,win.move)).winner,1);assert(E.legal(E.create()).some(m=>E.moveKey(m)===E.moveKey(start.move)));ai[difficulty]={legal:true,immediateWin:true,forcedCapture:true,openingDepth:start.depth,openingNodes:start.nodes,maxDepth:E.LIMITS[difficulty].depth};}
test('difficulty search depths and budgets differ',()=>{assert(E.LIMITS.easy.depth<E.LIMITS.normal.depth&&E.LIMITS.normal.depth<E.LIMITS.hard.depth);assert(E.LIMITS.easy.ms<E.LIMITS.normal.ms&&E.LIMITS.normal.ms<E.LIMITS.hard.ms);assert.equal(ai.easy.openingDepth,2);assert(ai.normal.openingDepth>2);assert(ai.hard.openingDepth>2)});
for(let seed=1;seed<=6;seed++){let s=E.create(),levels=['easy','normal','hard'];while(!E.outcome(s)&&s.ply<400){let d=levels[(s.ply+seed)%3],pick=E.chooseMove(s,d,{timeMs:8,maxDepth:d==='easy'?2:3,seed:seed*123+s.ply});assert(E.legal(s).some(m=>E.moveKey(m)===E.moveKey(pick.move)));s=E.apply(s,pick.move);for(let i=0;i<64;i++)if(s.board[i]){assert.equal((Math.floor(i/8)+i%8)%2,1);assert(Math.abs(s.board[i])<=2)}}assert(E.outcome(s),'seeded match must finish, not merely hit the safety bound');selfPlay.push({seed,plies:s.ply,result:E.outcome(s),legalEveryTurn:true})}
return{passed:true,rules:{count:names.length,names},ai,selfPlay}}
if(require.main===module){let r=run();require('node:fs').writeFileSync(__dirname+'/rules-report.json',JSON.stringify(r,null,2)+'\n');console.log('English Checkers rules / AI passed:',r.rules.count,'fixtures;',r.selfPlay.length,'seeded matches')}module.exports={run};
