(function(C){const{act,rng,svg,txt}=C;
function footprint(cells,rot){const points=cells.map(p=>{let[x,y]=p;for(let i=0;i<rot;i++)[x,y]=[-y,x];return[x,y];}),minX=Math.min(...points.map(p=>p[0])),minY=Math.min(...points.map(p=>p[1]));return points.map(([x,y])=>[x-minX,y-minY]).sort((a,b)=>a[0]-b[0]||a[1]-b[1]);}
function width(cells,rot){return Math.max(...footprint(cells,rot).map(p=>p[0]))+1;}
const fits=(cells,rot,pad)=>JSON.stringify(footprint(cells,rot))===JSON.stringify(pad);
function physics(s,dx=0){s.omega=s.omega*.78-s.theta*.16-dx*.09;s.theta+=s.omega;if(Math.abs(s.theta)<.00001&&Math.abs(s.omega)<.00001)s.theta=s.omega=0;}
function loadPosition(s){return{x:s.x+Math.sin(s.theta)*s.rope,bottom:s.z-Math.cos(s.theta)*s.rope};}
function stable(o){return Math.abs(o.theta)<.015&&Math.abs(o.omega)<.01;}
C.register('aerial-cargo',{
roles:['飛行員','地勤'],icon:'⌁',color:'#85cce4',intro:'飛行員控制水平航位與高度，地勤收放纜繩、旋轉異形貨物和扣具。風擺平息後才能精準卸貨。',help:['開始在貨物上方，地勤先扣住貨物並收短纜繩。飛行員上升，確保貨物底部高於障礙。','每次水平移動會推動擺錘；「穩定懸停」讓阻尼與重力逐步消除擺動。這是離散時間的簡化擺錘物理。','到停機坪正上方，先等擺動變小，再放長纜繩。地勤旋轉貨物，讓異形貨物的輪廓完整吻合黃色接貨架，再解扣。不只比較寬度，也檢查每個凸出格。'],
generate(n){const r=rng(n*1673),dest=18+n%13,shape=n%3===0?[[0,0],[1,0],[2,0],[0,1]]:n%3===1?[[0,0],[1,0],[2,0],[1,1]]:[[0,0],[1,0],[2,0],[3,0],[0,1]];const obstacles=Array.from({length:2+n%5},(_,i)=>({x:5+i*(dest-9)/(2+n%5),width:1+r(),height:2+Math.floor(r()*5)}));const padCells=footprint(shape,n%4);return{id:n,dest,shape,obstacles,padCells,padWidth:width(shape,n%4)+.5,clearance:Math.max(...obstacles.map(o=>o.height))+3};},
init(){return{x:2,z:6,rope:6,theta:0,omega:0,hooked:false,rotation:0,attachedOnce:false};},
observe(s,r){return{x:s.x,z:s.z,rope:s.rope,theta:s.theta,omega:s.omega,hooked:s.hooked,rotation:s.rotation,attachedOnce:s.attachedOnce,dest:s.level.dest,shape:s.level.shape,padWidth:s.level.padWidth,padCells:s.level.padCells,obstacles:s.level.obstacles,clearance:s.level.clearance,load:loadPosition(s),loadWidth:width(s.level.shape,s.rotation)};},
actions(o){return o.role===0?[act('move','向左航行一格',{dx:-1}),act('move','向右航行一格',{dx:1}),act('altitude','上升一格',{dz:1}),act('altitude','下降一格',{dz:-1}),act('hover','穩定懸停一拍')]:[act('hook','扣住貨物'),act('reel','收繩至 2 格',{length:2}),act('reel','放繩至地面',{length:o.z}),...[0,1,2,3].map(rotation=>act('rotate',`貨物轉向 ${rotation*90}°`,{rotation})),act('drop','解扣，放下貨物')];},
step(s,r,a){const l=s.level;if(r===0){let dx=0;if(a.type==='move'&&[-1,1].includes(a.dx)&&s.x+a.dx>=0&&s.x+a.dx<=l.dest+2){dx=a.dx;s.x+=dx;}else if(a.type==='altitude'&&[-1,1].includes(a.dz)&&s.z+a.dz>=2&&s.z+a.dz<=12)s.z+=a.dz;else if(a.type!=='hover')return{ok:false};physics(s,dx);}else{if(a.type==='hook'&&!s.hooked&&!s.attachedOnce&&Math.abs(s.x-2)<.2&&Math.abs(s.z-s.rope)<.1){s.hooked=true;s.attachedOnce=true;}else if(a.type==='reel'&&s.hooked&&Number.isInteger(a.length)&&a.length>=2&&a.length<=12){s.rope=a.length;}else if(a.type==='rotate'&&s.hooked&&[0,1,2,3].includes(a.rotation)){s.rotation=a.rotation;}else if(a.type==='drop'&&s.hooked){const p=loadPosition(s);if(Math.abs(p.x-l.dest)>.25||Math.abs(p.bottom)>.15||!stable(s)||!fits(l.shape,s.rotation,l.padCells))return{ok:false,reason:'貨物尚未平穩落在停機坪內，或寬度不合'};s.hooked=false;s.won=true;return{ok:true};}else return{ok:false,reason:'扣具、纜繩或貨物位置不合'};}if(s.hooked){const p=loadPosition(s),half=width(l.shape,s.rotation)/2;if(p.bottom<-.2||l.obstacles.some(o=>Math.abs(p.x-o.x)<half+o.width/2&&p.bottom<o.height))s.lost=true;}return{ok:true};},
ai(o){if(o.role===1){if(!o.hooked)return !o.attachedOnce&&o.x===2&&o.z===o.rope?act('hook','連接扣具'):null;if(!fits(o.shape,o.rotation,o.padCells))return act('rotate','讓異形貨物吻合接貨架',{rotation:[0,1,2,3].find(r=>fits(o.shape,r,o.padCells))});if(o.x===o.dest&&stable(o)){if(o.rope!==o.z)return act('reel','平穩降下貨物',{length:o.z});return act('drop','安全解扣');}if(o.rope!==2)return act('reel','收短纜繩',{length:2});return null;}if(!o.hooked)return null;if(o.x===o.dest)return stable(o)?null:act('hover','等待擺錘穩定');if(o.rope!==2)return null;if(o.z<o.clearance+2)return act('altitude','提升貨物離地高度',{dz:1});return act('move','沿航線運送',{dx:o.dest>o.x?1:-1});},
view(o){const scale=490/(o.dest+4),ground=280,px=35+o.x*scale,py=ground-o.z*19,load=o.hooked?o.load:{x:2,bottom:0};let b=`<path d="M20 ${ground}H540" stroke="#719096" stroke-width="5"/>`;for(const q of o.obstacles)b+=`<rect x="${35+(q.x-q.width/2)*scale}" y="${ground-q.height*19}" width="${q.width*scale}" height="${q.height*19}" rx="3" fill="#52627a"/>`;b+=`<rect x="${35+(o.dest-o.padWidth/2)*scale}" y="${ground-4}" width="${o.padWidth*scale}" height="8" fill="#edcc76"/><path d="M${px} ${py}L${35+load.x*scale} ${ground-load.bottom*19-12}" stroke="#e7dbc2" stroke-width="3"/>`+txt(px,py,'✦',30);for(const [a,bx]of o.padCells)b+=`<rect x="${35+(o.dest-(o.padWidth-.5)/2+a)*scale}" y="${ground-12-bx*12}" width="${scale-1}" height="11" fill="none" stroke="#edcc76" stroke-width="2"/>`;for(const [a,bx]of footprint(o.shape,o.rotation))b+=`<rect x="${35+(load.x-o.loadWidth/2+a)*scale}" y="${ground-load.bottom*19-12-bx*12}" width="${scale-1}" height="11" fill="#dba676"/>`;return svg(b);},status:o=>`航位 ${o.x}/${o.dest} · 高度 ${o.z} · 繩長 ${o.rope} · 擺角 ${(o.theta*180/Math.PI).toFixed(1)}° · ${o.hooked?'貨物已扣住':'等待扣具'}`,
physics,loadPosition,footprint,fits
});})(typeof module!=='undefined'?require('../coop120-common/core.js'):CoopCore);
