'use strict';const assert=require('node:assert/strict'),fs=require('node:fs'),E=require('./engine'),{Session}=require('./session');const K=E.id==='kalah';let checks=0;function test(name,fn){fn();checks++;console.log('PASS',name);}const report={passed:false,game:E.id,difficultyLevels:Object.keys(E.LEVELS),rules:[],tactics:[],selfPlay:[],ai:[]};
function fixture(a,b,extra={}){const s=E.initial();s.hand=[0,0];for(const i of a)s.board[i]=0;for(const i of b)s.board[i]=1;return Object.assign(s,extra);}
if(K){
 test('standard 48 seeds and 6 legal opening pits',()=>{assert.equal(E.initial().board.reduce((a,b)=>a+b),48);assert.deepEqual(E.legal(E.initial()),[0,1,2,3,4,5]);});
 test('landing in own store keeps the same player',()=>{const s=E.step(E.initial(),2);assert.equal(s.turn,0);assert(s.last.bonus);assert.equal(s.board[6],1);});
 test('multiple laps skip opponent store',()=>{const s={...E.initial(),board:[1,1,1,1,1,14,0,1,1,1,1,1,1,23]},n=E.step(s,5);assert.equal(n.board[13],23);assert.equal(n.board[6],2);assert.equal(n.turn,0);});
 test('own empty pit captures opposite stones and landing seed',()=>{const s={...E.initial(),board:[0,1,0,0,1,0,20,1,1,1,5,0,0,18]},n=E.step(s,1);assert.equal(n.board[6],26);assert.equal(n.board[2],0);assert.equal(n.board[10],0);assert.equal(n.last.captured,6);});
 test('empty opposite pit does not capture own landing seed',()=>{const s={...E.initial(),board:[0,1,0,0,1,0,20,1,1,1,0,0,0,23]},n=E.step(s,1);assert.equal(n.board[2],1);assert.equal(n.last.captured,0);});
 test('end sweep overrides bonus turn and counts winner',()=>{const s={...E.initial(),board:[0,0,0,0,0,1,20,2,0,0,0,0,0,25]},n=E.step(s,5);assert.equal(n.result,1);assert.equal(n.board[6],21);assert.equal(n.board[13],27);assert(!n.last.bonus);assert.deepEqual(E.legal(n),[]);});
 test('tied final stores are a draw',()=>{const s={...E.initial(),board:[0,0,0,0,0,1,23,1,0,0,0,0,0,23]};assert.equal(E.step(s,5).result,'draw');});
 test('enemy pits, stores and empty pits are rejected without mutation',()=>{const s=E.initial(),copy=JSON.stringify(s);for(const m of [-1,6,7,13,14,null,'2'])assert.equal(E.step(s,m),null);assert.equal(JSON.stringify(s),copy);});
 for(const level of Object.keys(E.LEVELS)){test(level+' chooses a six-stone tactical capture',()=>{const s={...E.initial(),board:[0,1,0,0,1,0,20,1,1,1,5,0,0,18]},r=E.choose(s,level);assert.equal(r.move,1);report.tactics.push({level,fixture:'six-stone-capture',move:r.move,depth:r.depth});});}
}else{
 test('board has 24 intersections, 16 mills and symmetric adjacency',()=>{assert.equal(E.POINTS.length,24);assert.equal(E.MILLS.length,16);for(let i=0;i<24;i++)for(const j of E.ADJ[i])assert(E.ADJ[j].includes(i));assert(!E.ADJ[1].includes(7));assert(!E.ADJ[11].includes(12));});
 test('nine reserves each; placement decrements one and alternates',()=>{const s=E.initial(),n=E.step(s,{to:0});assert.deepEqual(n.hand,[8,9]);assert.equal(n.turn,1);assert.equal(E.step(n,{to:0}),null);assert.equal(E.step(n,{from:0,to:1}),null);});
 test('a mill keeps the turn for capture and protects enemy mills',()=>{const s=fixture([0,1],[9,10,11,3],{hand:[7,5]}),n=E.step(s,{to:2});assert(n.capture);assert.equal(n.turn,0);assert.deepEqual(E.legal(n),[{remove:3}]);assert.equal(E.step(n,{remove:9}),null);const f=E.step(n,{remove:3});assert(!f.capture);assert.equal(f.turn,1);assert.equal(f.board[3],-1);});
 test('when all enemies are in mills any one can be captured',()=>{const s=fixture([0,1],[9,10,11],{hand:[7,6]}),n=E.step(s,{to:2});assert.equal(E.legal(n).length,3);});
 test('mill without enemy pieces does not leave a stuck capture phase',()=>{const s=fixture([0,1],[],{hand:[7,9]}),n=E.step(s,{to:2});assert(!n.capture);assert.equal(n.turn,1);});
 test('four pieces move adjacent only; three pieces can fly',()=>{let s=fixture([0,3,6,8],[21,18,15,23]);assert.equal(E.step(s,{from:0,to:22}),null);assert(E.step(s,{from:0,to:1}));s=fixture([0,3,8],[21,18,15,23]);assert(E.step(s,{from:0,to:22}));});
 test('under three loses after capture, but not during placement',()=>{let s=fixture([0,1,2],[9,10,18],{capture:true});assert.equal(E.step(s,{remove:18}).result,0);s=fixture([0,1,2],[9,10,18],{capture:true,hand:[3,3]});assert.equal(E.step(s,{remove:18}).result,null);});
 test('blocked player loses after the opponent ends its move',()=>{const s=fixture([0,3,6,9],[1,4,7,10,11,21,22],{turn:1});const n=E.step(s,{from:22,to:23});assert.equal(n.result,1);});
 test('third identical board plus turn draws in movement phase',()=>{let s=fixture([0,3,8],[21,18,15]);s.seen[E.key(s)]=1;for(let cycle=0;cycle<2;cycle++)for(const m of [{from:0,to:1},{from:21,to:22},{from:1,to:0},{from:22,to:21}]){s=E.step(s,m);assert(s);}assert.equal(s.result,'repetition');});
 test('100 movement actions without capture draw; captures reset clock',()=>{let s=fixture([0,3,8],[21,18,15],{quiet:99});assert.equal(E.step(s,{from:0,to:1}).result,'quiet');s=fixture([0,1,2],[9,10,18,23],{capture:true,quiet:99});assert.equal(E.step(s,{remove:18}).quiet,0);});
 test('invalid actions do not mutate state',()=>{const s=E.initial(),copy=JSON.stringify(s);for(const m of [null,{}, {to:24},{to:0,from:0},{remove:0},{to:0,evil:true}])assert.equal(E.step(s,m),null);assert.equal(JSON.stringify(s),copy);});
 for(const level of Object.keys(E.LEVELS)){test(level+' completes a mill and evaluates its capture continuation',()=>{const s=fixture([0,1],[3,4],{hand:[7,7]}),r=E.choose(s,level);assert.deepEqual(r.move,{to:2});const n=E.step(s,r.move),cap=E.choose(n,level,{nodes:1500,time:50});assert(E.legal(n).some(m=>E.equalMove(m,cap.move)));report.tactics.push({level,fixture:'mill-and-capture',move:r.move,depth:r.depth});});}
}
let rng=0xdeadbeef;function random(){rng^=rng<<13;rng^=rng>>>17;rng^=rng<<5;return (rng>>>0)/4294967296;}
for(let game=0;game<12;game++)test('seeded legal playout '+game,()=>{let s=E.initial(),moves=0;const actions=[];while(s.result===null&&moves<1900){const legal=E.legal(s);assert(legal.length);const m=legal[Math.floor(random()*legal.length)],n=E.step(s,m);assert(n);if(K)assert.equal(n.board.reduce((a,b)=>a+b),48);else{assert(n.board.every(x=>[-1,0,1].includes(x)));assert(n.hand.every(x=>x>=0&&x<=9));assert(E.count(n,0)+n.hand[0]<=9);assert(E.count(n,1)+n.hand[1]<=9);}s=n;actions.push(m);moves++;}assert.notEqual(s.result,null);assert.deepEqual(E.replay(actions),s);report.selfPlay.push({kind:'seeded-random',seed:game,actions:moves,result:s.result});});
for(const level of Object.keys(E.LEVELS))test('full bounded '+level+' AI self-play with legality and terminal checks',()=>{let s=E.initial(),moves=0;const actions=[];while(s.result===null&&moves<1900){const r=E.choose(s,level,{nodes:K?500:100,time:K?30:15});assert(E.legal(s).some(m=>K?m===r.move:E.equalMove(m,r.move)));const n=E.step(s,r.move);assert(n);s=n;actions.push(r.move);moves++;}assert.notEqual(s.result,null);assert.deepEqual(E.replay(actions),s);report.ai.push({level,actions:moves,result:s.result,budget:'reduced test budget; real level configuration tested in tactics'});});
test('save boundary replays moves, discards forged board, rejects invalid transcripts',()=>{const s=new Session();s.play(E.legal(s.state)[0]);const data=s.save();data.board=['forged'];assert.deepEqual(Session.restore(JSON.stringify(data)).state,s.state);for(const bad of [{...data,actions:[K?13:{to:24}]},{...data,version:99},{...data,config:{mode:'wat',human:0,difficulty:'easy'}},{...data,actions:'fake'}])assert.throws(()=>Session.restore(bad));});
report.passed=true;report.checks=checks;report.rules={passed:true,fixtures:checks-report.tactics.length-report.selfPlay.length-report.ai.length-1};fs.writeFileSync(__dirname+'/rule-results.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({passed:true,game:E.id,checks}));
