(function(){'use strict';
const E=GameEngine,kind=document.body.dataset.kind,flight=kind==='flight',id=flight?'aeroplane-chess':'chinese-checkers',key='arcade-'+id+'-v2',$=x=>document.getElementById(x),levels={easy:'簡單',normal:'普通',hard:'困難'},session=new GameSession.Session(E,kind,{count:2,level:'normal',players:['human','ai']}),guard=new GameSession.Guard();let selected=null,blocked=false;
try{const raw=localStorage.getItem(key);if(raw&&!session.restore(JSON.parse(raw)))$('save').textContent='舊存檔無法讀取，已建立新局';}catch(e){$('save').textContent='儲存空間無法使用，仍可繼續遊玩';}
function save(){try{localStorage.setItem(key,JSON.stringify(session.export()));$('save').textContent='棋局已自動保存在此瀏覽器';}catch(e){$('save').textContent='無法保存：仍可遊玩，離開後進度可能消失';}}
const color=p=>flight?E.color(session.state,p):session.state.homes[p],name=p=>E.names[color(p)],paint=p=>E.colors[color(p)],human=()=>session.config.players[session.state.turn]==='human',ready=()=>!session.state.over&&!blocked&&human(),svg=(tag,a,inner='')=>'<'+tag+' '+Object.entries(a).map(([k,v])=>k+'="'+v+'"').join(' ')+'>'+inner+'</'+tag+'>',circle=(x,y,r,fill,cls='')=>svg('circle',{cx:x,cy:y,r,fill,class:cls});
function point(i){const c=E.cells[i];return[330+c.x*35,285+c.y*35];}function fp(p,pos,n){return E.position(session.state,p,pos,n).map(v=>34+v*38);}
function drawChinese(){const s=session.state,moves=selected===null?[]:E.pieceMoves(s,selected),dest=new Set(moves.map(m=>m.to));let out='';for(let a=0;a<6;a++){const pts=E.arms[a].map(i=>point(i));const cx=pts.reduce((v,p)=>v+p[0],0)/10,cy=pts.reduce((v,p)=>v+p[1],0)/10;out+=circle(cx,cy,67,E.colors[a]+'16');}if(s.last&&!s.last.pass)out+=svg('polyline',{points:s.last.path.map(i=>point(i).join(',')).join(' '),class:'last-path'});E.cells.forEach((c,i)=>{const[x,y]=point(i),p=s.board[i],selectable=ready()&&(p===s.turn||dest.has(i));out+=svg('g',{'data-cell':i,class:'node '+(selectable?'selectable':''),tabindex:selectable?0:-1,role:'button','aria-label':p<0?'空孔 '+(i+1):name(p)+'棋子 '+(i+1)},circle(x,y,15,'transparent','hit')+circle(x,y,8,'','hole')+(dest.has(i)?circle(x,y,12,'','target'):'')+(p>=0?circle(x,y,11,paint(p),'marble'):'')+(selected===i?circle(x,y,15,'','selected'):''));});$('board').innerHTML=out;}
function drawFlight(){const s=session.state;let out='';for(let c=0;c<4;c++){const p=s.seats.indexOf(c),center=E.rotate([3,12],c).map(v=>34+v*38),a=E.rotate([7,13],c),b=E.rotate([7,8],c);out+=svg('rect',{x:center[0]-83,y:center[1]-64,width:166,height:128,rx:25,fill:E.colors[c],stroke:E.colors[c],class:'airport'});out+=svg('text',{x:center[0],y:center[1]-43,'text-anchor':'middle',class:'airport-label'},E.names[c]+'機庫');for(let k=0;k<6;k++){const pt=E.rotate([7,13-k],c).map(v=>34+v*38);out+=circle(...pt,15,E.colors[c]+'aa','lane');}const launch=E.rotate([5,13],c).map(v=>34+v*38);out+=circle(...launch,16,'','launch');const aa=E.track[(c*13+18)%52].map(v=>34+v*38),bb=E.track[(c*13+30)%52].map(v=>34+v*38);out+=svg('path',{d:'M'+aa.join(',')+'L'+bb.join(','),stroke:E.colors[c],class:'flight-line'});}E.track.forEach((p,i)=>{const[x,y]=p.map(v=>34+v*38),c=((i%4)+2)%4;out+=circle(x,y,16,E.colors[c],'track');if(i%13===5)out+=svg('text',{x,y:y+4,'text-anchor':'middle',class:'track-label'},'✦');});out+=circle(300,300,24,'#fff');out+=svg('text',{x:300,y:305,'text-anchor':'middle',fill:'#53796b','font-size':14},'終點');const legal=ready()?E.legal(s):[];s.planes.forEach((planes,p)=>planes.forEach((pos,n)=>{let[x,y]=fp(p,pos,n);const peers=planes.flatMap((v,k)=>v===pos?[k]:[]);if(pos>=0&&pos<58&&peers.length>1){const j=peers.indexOf(n);x+=(j%2?6:-6);y+=j<2?-6:6;}out+=svg('g',{'data-plane':n,'data-player':p,class:'plane '+(p===s.turn&&legal.includes(n)?'can-move':''),role:'button',tabindex:p===s.turn&&legal.includes(n)?0:-1,'aria-label':name(p)+' '+(n+1)+' 號飛機，'+(pos<0?'機庫':pos===58?'已抵達':'第 '+pos+' 格')},circle(x,y,11,paint(p),'marble')+svg('text',{x,y:y+4,'text-anchor':'middle','font-size':12},n+1));}));$('board').innerHTML=out;}
function render(){const s=session.state;$('turn').textContent=s.over?'本局結束':name(s.turn)+(human()?' · 真人':' · AI');$('difficulty').textContent=levels[session.config.level];$('moveCount').textContent=s.moves;$('boardTitle').textContent=flight?'各自起飛，一起回家':'選一顆棋，往對面的星角';$('seats').innerHTML=session.config.players.map((p,i)=>'<div class="seat '+(s.turn===i&&!s.over?'active':'')+'"><span class="seat-dot" style="--seat:'+paint(i)+'">'+(i+1)+'</span><span class="seat-name">'+name(i)+'<small>'+(p==='human'?'同機真人':'AI · '+levels[session.config.level])+'</small></span><span class="seat-score">'+E.progress(s,i)+' / '+(flight?4:10)+'</span></div>').join('');$('undo').disabled=!session.history.length;$('pause').textContent=session.paused?'繼續 AI':'暫停 AI';$('pause').disabled=!session.config.players.includes('ai');$('result').hidden=!s.over;if(s.over)$('result').innerHTML='<strong>'+(flight?name(s.rank[0])+'率先抵達！':s.draw?'這局平分秋色':name(s.winner)+'獲勝！')+'</strong>'+(flight?s.rank.map((p,i)=>(i+1)+'. '+name(p)).join(' · '):'開一局新挑戰，或復原重新思考。');let status=s.over?'本局已結束':session.paused?'AI 已暫停；真人仍可操作':human()?(flight?s.die===null?'請擲骰，看看今天的風向。':'擲出 '+s.die+' 點，請選發亮的飛機。':selected===null?'請選擇自己的棋子，再選虛線目的地。':'虛線標示所有合法目的地，點擊即可完成走棋。'):'AI 正在思考…';if(flight){$('die').textContent=['⚀','⚁','⚂','⚃','⚄','⚅'][(s.die||s.lastDie||1)-1];$('die').setAttribute('aria-label',s.die?'骰子 '+s.die+' 點':'等待擲骰');$('dieInfo').textContent=s.die?'本次 '+s.die+' 點'+(s.die===6?' · 可再擲一次':''):'輪到 '+name(s.turn);$('roll').disabled=!ready()||s.die!==null;const legal=E.legal(s);$('planeOptions').innerHTML=s.planes[s.turn].map((pos,n)=>'<button class="plane-option" data-option="'+n+'" '+(!ready()||!legal.includes(n)?'disabled':'')+'>'+(n+1)+' 號<small>'+(pos<0?'機庫':pos===58?'抵達':pos===0?'起飛區':'第 '+pos+' 格')+'</small></button>').join('');if(s.die!==null&&!legal.length)status='沒有可走飛機，將自動交棒。';drawFlight();}else{$('pass').hidden=s.over||E.legal(s).length>0;$('pass').disabled=!ready();drawChinese();}$('status').textContent=status;}
function cancel(){guard.cancel();session.cancel();}function commit(m){try{session.move(m);selected=null;save();render();schedule();}catch(e){$('status').textContent='這一步不可走，請重新選擇。';}}
function die(){if(window.crypto&&crypto.getRandomValues){const a=new Uint32Array(1);do{crypto.getRandomValues(a);}while(a[0]>=4294967292);return a[0]%6+1;}return Math.floor(Math.random()*6)+1;}
function doRoll(){session.roll(die);save();render();schedule();}
function schedule(){guard.cancel();const s=session.state;if(s.over||blocked)return;if(flight&&s.die!==null&&!E.legal(s).length){guard.schedule(()=>commit(null),700);return;}if(human()||session.paused)return;guard.schedule(token=>{if(flight&&session.state.die===null){doRoll();return;}const epoch=session.epoch,finish=move=>{if(!guard.valid(token)||session.epoch!==epoch||blocked||session.paused)return;commit(move);};try{const w=new Worker(id+'/worker.js');guard.job=w;w.onmessage=e=>{if(e.data.token!==token)return;if(e.data.error){w.terminate();guard.job=null;finish(E.choose(session.state,session.config.level));}else finish(e.data.move);};w.onerror=()=>{w.terminate();guard.job=null;finish(E.choose(session.state,session.config.level));};w.postMessage({state:session.state,level:session.config.level,token});}catch(e){finish(E.choose(session.state,session.config.level));}},420);}
function activate(e){const cell=e.target.closest('[data-cell]'),plane=e.target.closest('[data-plane]');if(!ready())return;if(cell&&!flight){const i=Number(cell.dataset.cell);if(session.state.board[i]===session.state.turn){selected=selected===i?null:i;render();}else if(selected!==null){const m=E.pieceMoves(session.state,selected).find(m=>m.to===i);if(m)commit(m);}}if(plane&&flight&&Number(plane.dataset.player)===session.state.turn&&E.legal(session.state).includes(Number(plane.dataset.plane)))commit(Number(plane.dataset.plane));}
$('board').addEventListener('click',activate);$('board').addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();activate(e);}if(!flight&&e.target.dataset.cell&&['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();const i=Number(e.target.dataset.cell),c=E.cells[i],d={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]}[e.key],j=E.lookup(c.q+d[0],c.r+d[1]);if(j!==undefined){const node=$('board').querySelector('[data-cell="'+j+'"]');node.setAttribute('tabindex','0');node.focus();}}});
if(flight){$('roll').onclick=()=>{if(ready()&&session.state.die===null)doRoll();};$('planeOptions').onclick=e=>{const b=e.target.closest('[data-option]');if(b&&ready()&&E.legal(session.state).includes(Number(b.dataset.option)))commit(Number(b.dataset.option));};}else $('pass').onclick=()=>{if(ready()&&!E.legal(session.state).length)commit(null);};
$('undo').onclick=()=>{cancel();if(session.undo()){selected=null;save();render();schedule();}};$('pause').onclick=()=>{cancel();session.paused=!session.paused;save();render();schedule();};
function open(id){cancel();blocked=true;$(id).showModal();render();}function close(id){$(id).close();blocked=false;render();schedule();}document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>close(b.dataset.close));document.querySelectorAll('dialog').forEach(d=>d.addEventListener('cancel',e=>{e.preventDefault();close(d.id);}));$('help').onclick=()=>open('helpDialog');$('restart').onclick=()=>open('confirmDialog');$('acceptRestart').onclick=()=>{cancel();session.reset();selected=null;save();close('confirmDialog');};
let setupPlayers=[];function setupSeats(){const n=Number($('setupCount').value),preset=$('setupPreset').value;setupPlayers=Array.from({length:n},(_,i)=>preset==='human'?'human':preset==='ai'?(i===0?'human':'ai'):setupPlayers[i]||'ai');const temp=E.create(n);$('setupSeats').innerHTML=setupPlayers.map((p,i)=>'<label class="setup-seat"><span>'+E.names[flight?temp.seats[i]:temp.homes[i]]+'</span><select data-seat="'+i+'"><option value="human" '+(p==='human'?'selected':'')+'>同機真人</option><option value="ai" '+(p==='ai'?'selected':'')+'>AI 對手</option></select></label>').join('');}
$('setup').onclick=()=>{$('setupCount').value=session.config.count;$('setupLevel').value=session.config.level;$('setupPreset').value='custom';setupPlayers=session.config.players.slice();setupSeats();open('setupDialog');};$('setupCount').onchange=setupSeats;$('setupPreset').onchange=setupSeats;$('setupSeats').onchange=e=>{if(e.target.dataset.seat!==undefined){setupPlayers[Number(e.target.dataset.seat)]=e.target.value;$('setupPreset').value='custom';}};$('applySetup').onclick=()=>{cancel();session.reset({count:Number($('setupCount').value),level:$('setupLevel').value,players:setupPlayers.slice()});selected=null;save();close('setupDialog');};window.addEventListener('pagehide',()=>{cancel();save();});window.addEventListener('pageshow',()=>{render();schedule();});render();schedule();
})();
