'use strict';const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),E=require('./engine.js'),{Session,Guard}=require('./session.js');const flight=!!E.roll,kind=flight?'flight':'chinese';
let tests=0;function test(name,fn){fn();tests++;console.log('PASS '+name);}
test('Round undo returns human turn and cancels epoch',()=>{const s=new Session(E,kind,{count:2,level:'normal',players:['human','ai']});const before=E.copy(s.state),epoch=s.epoch;if(flight){s.roll(()=>6);s.move(0);s.roll(()=>1);s.move(0);s.roll(()=>1);s.move(null);}else{s.move(E.legal(s.state)[0]);s.move(E.legal(s.state)[0]);}assert(s.undo());assert.deepEqual(s.state,before);assert(s.epoch>epoch);});
test('Save restore and reject malformed storage',()=>{const s=new Session(E,kind,{count:2,level:'hard',players:['human','ai']});if(flight)s.roll(()=>6);else s.move(E.legal(s.state)[0]);const t=new Session(E,kind,s.config);assert(t.restore(JSON.parse(JSON.stringify(s.export()))));assert.deepEqual(t.state,s.state);assert(!t.restore({}));const bad=s.export();bad.config.players=['bad'];assert(!t.restore(bad));});
test('Restart retains config and clears history',()=>{const s=new Session(E,kind,{count:2,level:'easy',players:['ai','ai']});s.checkpoint();s.reset();assert.equal(s.history.length,0);assert.equal(s.config.level,'easy');assert.equal(s.state.moves,0);});
if(flight)test('Undo preserves dice tape and pending-roll save',()=>{const s=new Session(E,kind,{count:2,level:'hard',players:['human','ai']});s.roll(()=>6);s.move(0);s.roll(()=>3);s.move(0);s.undo();s.roll(()=>1);assert.equal(s.state.die,6);assert.equal(s.tape[1],3);const t=new Session(E,kind,s.config);assert(t.restore(s.export()));assert.equal(t.state.die,6);});
test('Guard rejects stale worker after cancel/reset',()=>{const g=new Guard();let terminated=0;g.job={terminate(){terminated++;}};const token=g.generation;g.cancel();assert(!g.valid(token));assert.equal(terminated,1);g.schedule(()=>assert.fail('cancelled timer fired'),100);g.cancel();});
class Node{constructor(id){this.id=id;this.dataset={};this.value='';this.textContent='';this.innerHTML='';this.hidden=false;this.disabled=false;this.events={};}addEventListener(n,f){this.events[n]=f;}setAttribute(){}showModal(){this.open=true;}close(){this.open=false;}querySelector(){return new Node('cell');}focus(){}}
function harness(storageBroken=false){const nodes=new Map(),get=id=>{if(!nodes.has(id))nodes.set(id,new Node(id));return nodes.get(id);},timers=new Map(),workers=[],store=new Map();let tid=0;class Worker{constructor(){workers.push(this);}terminate(){this.dead=true;}postMessage(m){this.message=m;}}const sandbox={GameEngine:E,GameSession:{Session,Guard},document:{body:{dataset:{kind}},getElementById:get,querySelectorAll:()=>[]},localStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>{if(storageBroken)throw Error('quota');store.set(k,v);}},window:{addEventListener(){},crypto:{}},crypto:{getRandomValues(a){a[0]=5;return a;}},Worker,console,setTimeout:(f)=>{timers.set(++tid,f);return tid;},clearTimeout:k=>timers.delete(k),Math}; // session Guard uses host timers; replace with sandbox implementation
vm.createContext(sandbox);vm.runInContext(fs.readFileSync(__dirname+'/session.js','utf8'),sandbox);vm.runInContext(fs.readFileSync(__dirname+'/app.js','utf8'),sandbox);return{get,store,workers,timers,run(){const entry=timers.entries().next().value;if(entry){timers.delete(entry[0]);entry[1]();}}};}
test('UI boot, setup, pause, restart, storage fallback',()=>{const h=harness();assert(h.get('board').innerHTML.includes(flight?'data-plane':'data-cell'));h.get('setup').onclick();assert(h.get('setupDialog').open);h.get('setupCount').value=flight?'4':'6';h.get('setupLevel').value='hard';h.get('setupPreset').value='human';h.get('setupPreset').onchange();h.get('applySetup').onclick();assert.equal(h.get('difficulty').textContent,'困難');assert(h.get('seats').innerHTML.includes('同機真人'));h.get('restart').onclick();assert(h.get('confirmDialog').open);h.get('acceptRestart').onclick();assert.equal(h.get('moveCount').textContent,0);const bad=harness(true);bad.get('pause').onclick();assert(bad.get('save').textContent.includes('無法保存'));});
test('UI stale worker response cannot alter restarted game',()=>{const h=harness();h.get('setup').onclick();h.get('setupCount').value='2';h.get('setupLevel').value='normal';h.get('setupPreset').value='custom';h.get('setupSeats').onchange({target:{dataset:{seat:'0'},value:'ai'}});h.get('applySetup').onclick();h.run();if(flight)h.run();const w=h.workers.at(-1);if(w){h.get('restart').onclick();h.get('acceptRestart').onclick();const before=h.get('moveCount').textContent;w.onmessage({data:{token:w.message.token,move:E.choose(w.message.state)}});assert.equal(h.get('moveCount').textContent,before);assert(w.dead);}else assert(flight,'worker should start');});
const file=__dirname+'/verification.json';let report={};try{report=JSON.parse(fs.readFileSync(file));}catch{}report.controllerTests=tests;report.controllerPassed=true;report.controller={passed:true,tests};report.passed=!!report.rulesPassed;report.difficultyLevels=['easy','normal','hard'];report.browserVisualTests=false;fs.writeFileSync(file,JSON.stringify(report,null,2)+'\n');console.log('Controller tests: '+tests);
