(()=>{'use strict';const E=UntangleEngine,L=UNTANGLE_LEVELS,$=id=>document.getElementById(id),KEY='arcade.untangle.v1',NS='http://www.w3.org/2000/svg';let index=0,records={},storageOk=true,notice='',hintNode=-1,selected=-1,drag=null,confirmAction=null,demoTimer=null;
try{let d=JSON.parse(localStorage.getItem(KEY));if(d){if(d.version!==1||!Number.isInteger(d.index)||d.index<0||d.index>=L.length)throw Error();index=d.index;for(let i=0;i<L.length;i++){let raw=d.records&&d.records[i];records[i]=E.record(L[i],raw);if(raw&&JSON.stringify(raw)!==JSON.stringify(records[i]))notice='部分儲存資料未通過驗證，已安全重設。'}}}catch(e){notice='儲存資料無法讀取，已從起點開始。'}
const p=()=>L[index],r=()=>records[index]||(records[index]={actions:[],completed:null}),state=()=>E.replay(p(),r().actions).at(-1);function save(){try{localStorage.setItem(KEY,JSON.stringify({version:1,index,records}))}catch(e){storageOk=false}$('saveNote').textContent=storageOk?'進度自動儲存在此瀏覽器':'無法儲存：此瀏覽器的儲存空間不可用'}
function svg(tag,attrs){let el=document.createElementNS(NS,tag);Object.entries(attrs||{}).forEach(([k,v])=>el.setAttribute(k,v));return el}
function draw(el,l,s,interactive,ghost=-1){let info=E.inspect(l,s),canvas=svg('svg',{viewBox:'0 0 100 100',role:'group','aria-label':'拖曳節點解開交叉線'});el.replaceChildren(canvas);l.edges.forEach(([a,b],i)=>canvas.append(svg('line',{x1:s[a][0],y1:s[a][1],x2:s[b][0],y2:s[b][1],class:'edge'+(info.badEdges.has(i)?' bad':'')})));if(ghost>=0){let [x,y]=l.solution[ghost];canvas.append(svg('line',{x1:s[ghost][0],y1:s[ghost][1],x2:x,y2:y,class:'ghostline'}),svg('circle',{cx:x,cy:y,r:4,class:'ghost'}))}s.forEach(([x,y],i)=>{let g=svg('g',{class:'node'+(info.badNodes.has(i)?' bad':'')+(interactive&&selected===i?' selected':'')+(ghost===i?' hinted':''),transform:`translate(${x} ${y})`});let dot=svg('circle',{r:3.15,class:'dot'}),hit=svg('circle',{r:5.15,class:'hit'}),text=svg('text',{});text.textContent=i+1;g.append(hit,dot,text);if(interactive){g.dataset.node=String(i);g.setAttribute('role','button');g.setAttribute('tabindex','0');g.setAttribute('aria-label',`節點 ${i+1}，位置 ${Math.round(x)}、${Math.round(y)}；方向鍵移動，Shift 加速`);g.onpointerdown=ev=>begin(ev,i);g.onkeydown=ev=>key(ev,i);g.onfocus=()=>selected=i}canvas.append(g)});return info}
function render(){const s=state(),info=E.inspect(p(),s);if(info.won&&!r().completed)r().completed=r().actions.map(a=>({...a}));draw($('board'),p(),s,true,hintNode);$('level').innerHTML='';L.forEach((_,i)=>{let o=document.createElement('option');o.value=i;o.textContent=`第 ${String(i+1).padStart(2,'0')} 關${records[i]&&records[i].completed?' ✓':''}`;$('level').append(o)});$('level').value=String(index);$('levelNumber').textContent=String(index+1).padStart(2,'0');$('metricLabel').textContent='線段交叉';$('metric').textContent=info.crossings;$('metricUnit').textContent='處';$('moves').textContent=r().actions.length;$('completed').textContent=Object.values(records).filter(x=>x.completed).length;$('variant').textContent=`${s.length} 個節點 · ${p().edges.length} 條線`;$('levelInfo').textContent='獨立平面圖 · 已驗證無交叉解法';$('prev').disabled=index===0;$('next').disabled=index===49;$('undo').disabled=!r().actions.length;$('win').hidden=!info.won;$('message').textContent=notice||(info.won?'所有線段都互不交叉，也沒有節點或線段重疊。':info.overlaps?`還有 ${info.crossings} 處交叉及 ${info.overlaps} 處貼線／重疊。請留一點空間。`:'拖曳編號節點。紅色線段有交叉，綠色線段暫時安全。');save()}
function commit(i,x,y){let old=state()[i];x=Math.round(Math.max(5,Math.min(95,x))*100)/100;y=Math.round(Math.max(5,Math.min(95,y))*100)/100;if(E.dist(old,[x,y])<.01)return;r().actions.push({node:i,x,y});hintNode=-1;notice='';selected=i;render()}
function begin(ev,i){if($('modal').open||drag||ev.button!==undefined&&ev.button!==0)return;ev.preventDefault();selected=i;drag={id:ev.pointerId,node:i,start:state(),points:state()};try{$('board').setPointerCapture(ev.pointerId)}catch(e){}draw($('board'),p(),drag.points,true,hintNode)}
function dragMove(ev){if(!drag||ev.pointerId!==drag.id)return;ev.preventDefault();let box=$('board').getBoundingClientRect(),x=(ev.clientX-box.left)/box.width*100,y=(ev.clientY-box.top)/box.height*100;drag.points[drag.node]=[Math.max(5,Math.min(95,x)),Math.max(5,Math.min(95,y))];let info=draw($('board'),p(),drag.points,true,-1);$('metric').textContent=info.crossings;$('win').hidden=true;$('message').textContent=`拖曳中：${info.crossings} 處交叉${info.overlaps?'，仍有貼線或重疊':''}。放開以記錄這一步。`}
function endDrag(keep){if(!drag)return;let d=drag;drag=null;try{$('board').releasePointerCapture(d.id)}catch(e){}if(keep){let [x,y]=d.points[d.node];commit(d.node,x,y)}render();let node=$('board').querySelector(`[data-node="${d.node}"]`);if(node)node.focus()}
function key(ev,i){if(ev.key==='Escape'){endDrag(false);return}let ds={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]};if(!ds[ev.key]||$('modal').open)return;ev.preventDefault();const [dx,dy]=ds[ev.key],s=state(),amount=ev.shiftKey?5:1;commit(i,s[i][0]+dx*amount,s[i][1]+dy*amount);$('board').querySelector(`[data-node="${i}"]`).focus()}
$('board').onpointermove=dragMove;$('board').onpointerup=ev=>{if(drag&&ev.pointerId===drag.id)endDrag(true)};$('board').onpointercancel=ev=>{if(drag&&ev.pointerId===drag.id)endDrag(false)};$('board').onlostpointercapture=()=>{if(drag)endDrag(false)};
function move(i){endDrag(false);index=Math.max(0,Math.min(49,i));hintNode=-1;selected=-1;notice='';render()}
function stopDemo(){if(demoTimer!==null)clearTimeout(demoTimer);demoTimer=null}
function modal(title,body,fn=null){endDrag(false);stopDemo();confirmAction=fn;$('modalTitle').textContent=title;$('modalBody').replaceChildren(body);$('confirm').hidden=!fn;$('cancel').textContent=fn?'取消':'返回遊戲';$('modal').showModal()}
function paragraph(text){let p=document.createElement('p');p.textContent=text;return p}
function demo(){let l=p(),states=E.replay(l,E.solutionMoves(l)),at=0,playing=false,wrap=document.createElement('div'),board=document.createElement('div'),row=document.createElement('div'),back=document.createElement('button'),play=document.createElement('button'),next=document.createElement('button'),count=document.createElement('span');board.className='board demoBoard';board.id='demoBoard';row.className='demoControls';back.textContent='← 上一步';back.id='demoPrev';next.textContent='下一步 →';next.id='demoNext';play.id='demoPlay';count.id='demoCount';row.append(back,play,next,count);wrap.append(paragraph('從起始排列逐點移至一個已驗證的平面配置。過程中的交叉可能增加；這是參考排列，解法不唯一。觀摩不會改動你的棋盤或完成進度。'),board,row);function view(){draw(board,l,states[at],false,at<l.start.length?at:-1);count.textContent=`${at} / ${l.start.length} 步`;back.disabled=at===0;next.disabled=at===l.start.length;play.textContent=playing?'暫停':at===l.start.length?'重播':'自動播放'}function tick(){if(!playing||!$('modal').open)return;if(at<l.start.length)at++;if(at===l.start.length)playing=false;view();if(playing)demoTimer=setTimeout(tick,650)}back.onclick=()=>{stopDemo();playing=false;at=Math.max(0,at-1);view()};next.onclick=()=>{stopDemo();playing=false;at=Math.min(l.start.length,at+1);view()};play.onclick=()=>{stopDemo();playing=!playing;if(playing){if(at===l.start.length)at=0;demoTimer=setTimeout(tick,650)}view()};modal('解答觀摩 · 第 '+(index+1)+' 關',wrap);view()}
$('level').onchange=()=>move(+$('level').value);$('prev').onclick=()=>move(index-1);$('next').onclick=()=>move(index+1);$('undo').onclick=()=>{endDrag(false);if(r().actions.length){r().actions.pop();hintNode=-1;notice='已撤銷上一個節點移動。';render()}};$('reset').onclick=()=>modal('重新開始這一關？',paragraph('節點會回到這一關的起始排列。其他關卡與已完成紀錄會保留。'),()=>{r().actions=[];hintNode=-1;notice='已回到起始排列。';render()});$('hint').onclick=()=>{let s=state(),info=E.inspect(p(),s);if(info.won){notice='線條已經完全解開了！';hintNode=-1}else{hintNode=[...info.badNodes].find(i=>E.dist(s[i],p().solution[i])>.5)??s.findIndex((q,i)=>E.dist(q,p().solution[i])>.5);notice=`參考解法：可把節點 ${hintNode+1} 移向虛線圓的位置。中途交叉可能增加；提示沒有移動任何節點。`}render()};$('solution').onclick=demo;$('help').onclick=()=>{let div=document.createElement('div');div.append(paragraph('目標：讓所有線段不交叉。拖曳圓圈移動節點，連線會跟著改變。兩條線共用同一個端點是合法的。'),paragraph('節點彼此必須分開，也不能放在不屬於自己的線段上。線段壓在一起、交叉點藏在節點下面都不算完成。紅色提示需要整理的線；綠色表示目前沒有衝突。'),paragraph('鍵盤：Tab 選擇節點，方向鍵移動一小格，Shift＋方向鍵移動五格。拖曳中按 Escape 或手勢取消可還原。每次放開或鍵盤移動都能撤銷。'),paragraph('小提示會畫出參考解法中一個節點的位置。它不保證每一步都減少交叉；平面配置可能有很多種。解答觀摩不會改動你的進度。'));modal('怎麼玩解開繩結',div)};$('cancel').onclick=()=>$('modal').close();$('confirm').onclick=()=>{let fn=confirmAction;$('modal').close();confirmAction=null;if(fn)fn()};$('modal').addEventListener('close',()=>{stopDemo();confirmAction=null});document.addEventListener('keydown',ev=>{if(ev.key==='Escape')endDrag(false)});document.addEventListener('visibilitychange',()=>{if(document.hidden){endDrag(false);if($('modal').open)$('modal').close()}});render();})();
