/* Interface/controller. All legal transitions, undo, restart and hint search use IceCore. */
'use strict';
(()=>{
const $=id=>document.getElementById(id),levels=window.ICE_LEVELS,C=window.IceCore;
const names=['紅棋','藍棋','金棋'],colors=['#ff6688','#49b6f5','#ffc956'],letters=['1','2','3'],chapters=['薄冰探索','移動煞車','冰道借力','夥伴接力','雪地佈局','冰原迴旋','深藍交會','極光遠征','冰冠挑戰','極地大師'];
const STORE='arcade.ice-slide.v1';let saved;try{saved=C.parseProgress(localStorage.getItem(STORE),levels.length);}catch{saved=C.parseProgress(null,levels.length);$('save-note').textContent='瀏覽器未開放儲存；這次仍可完整遊玩';}
let current=saved.last,game=new C.Session(levels[current]),selected=levels[current].target,worker=null,token=0,busy=false,hintPlan=null,solutionPlan=null,playTimer=null,playing=false,solutionRevision=-1;
const canvas=$('board'),ctx=canvas.getContext('2d');let boardPixels=0;
function status(text){$('status').textContent=text;}
function save(){saved.last=current;try{localStorage.setItem(STORE,JSON.stringify(saved));}catch{$('save-note').textContent='進度無法寫入此瀏覽器；遊戲可繼續';}}
function cancelSearch(){token++;if(worker){worker.terminate();worker=null;}busy=false;$('hint').disabled=false;$('solution').disabled=false;}
function stopPlayback(announce=false){if(playTimer)clearTimeout(playTimer);playTimer=null;const was=playing;playing=false;$('solution').textContent='查看解法';if(was&&announce)status('示範已停止，可以接著操作或悔棋');}
function invalidate(){cancelSearch();hintPlan=null;solutionPlan=null;$('apply-hint').hidden=true;}
function chooseRobot(r,announce=true){if(r<0||r>2)return;selected=r;document.querySelectorAll('[data-robot]').forEach(b=>b.setAttribute('aria-pressed',String(+b.dataset.robot===r)));if(announce)status(`已選擇${names[r]}，請決定滑行方向`);draw();}
function load(index){stopPlayback();invalidate();current=Math.max(0,Math.min(levels.length-1,index));game.load(levels[current]);selected=game.level.target;$('win-banner').hidden=true;const l=game.level;$('level-number').textContent=`${String(l.id).padStart(2,'0')} / 50`;$('level-name').textContent=l.name;$('chapter').textContent=`第 ${l.difficulty} 階段 · ${chapters[l.difficulty-1]}`;$('objective').innerHTML=`<span>讓</span><span class="goal-dot" style="background:${colors[l.target]}">${letters[l.target]}</span><span>${names[l.target]}停在</span><b style="color:${colors[l.target]}">◎</b>`;$('size-label').textContent=`${l.size} × ${l.size} 冰場`;$('next-level').textContent=current===levels.length-1?'回到選關 →':'前往下一關 →';chooseRobot(selected,false);save();refresh();status(`第 ${l.id} 關：先安排夥伴的位置，讓${names[l.target]}停在目標上`);}
function refresh(){const l=game.level,record=saved.records[l.id]||{};$('moves').textContent=game.count;$('best').textContent=record.best||'—';$('progress').innerHTML=`${Object.values(saved.records).filter(r=>r.cleared).length}<small>/ 50</small>`;$('undo').disabled=!game.history.length;canvas.setAttribute('aria-label',`第 ${l.id} 關，${l.size} 乘 ${l.size} 棋盤。目標：${names[l.target]}到第 ${Math.floor(l.goal/l.size)+1} 列、第 ${l.goal%l.size+1} 欄。${game.positions.map((p,i)=>`${names[i]}在第 ${Math.floor(p/l.size)+1} 列、第 ${p%l.size+1} 欄`).join('。')}。目前 ${game.count} 步。按 1、2、3 選棋子，方向鍵滑行。`);draw();}
function recordWin(){const l=game.level,r=saved.records[l.id]||{};r.cleared=true;if(!game.assisted)r.best=Math.min(r.best||Infinity,game.count);saved.records[l.id]=r;save();$('win-text').textContent=`${game.count} 步完成${game.assisted?' · 使用輔助，不計入個人最佳':' · 已保存個人最佳'}`;$('win-banner').hidden=false;status(game.assisted?'合作成功！重新開始可以挑戰獨立完成。':'合作成功！你的成績已保存。');stopPlayback();refresh();}
function move(robot,dir,{demo=false}={}){if(!demo)stopPlayback();invalidate();if(game.won){status('本關已完成，可以悔棋或前往下一關');return false;}selected=robot;chooseRobot(robot,false);const changed=game.move(robot,dir);if(!changed){status(`${names[robot]}的${C.DIRS[dir]?.label||'這個'}方向被擋住了；原地不計步`);return false;}$('win-banner').hidden=true;refresh();if(game.won)recordWin();else status(`${names[robot]}向${C.DIRS[dir].label}滑行 · ${game.assisted?'輔助挑戰':'試著把夥伴當成煞車'}`);return true;}
function undo(){stopPlayback();invalidate();if(game.undo()){$('win-banner').hidden=true;refresh();status('已回到上一個盤面');}else status('目前已在起點');}
function restart(){stopPlayback();invalidate();game.restart();$('win-banner').hidden=true;selected=game.level.target;chooseRobot(selected,false);refresh();status('已回到本關起點，可以重新獨立挑戰');}
function requestSolution(mode){if(playing){stopPlayback(true);return;}if(game.won){status('指定棋子已經抵達目標');return;}cancelSearch();hintPlan=null;$('apply-hint').hidden=true;game.assisted=true;busy=true;$('hint').disabled=true;$('solution').disabled=true;const request=++token,revision=game.revision,start=game.positions.slice();status('正在從目前盤面尋找路線…');
 const accept=result=>{if(request!==token||game.revision!==revision)return;cancelSearch();if(result.status==='solved'&&result.moves.length){solutionPlan=result.moves;solutionRevision=revision;if(mode==='hint'){hintPlan=result.moves[0];const [r,d]=hintPlan;chooseRobot(r,false);status(`建議下一步：${names[r]} ${C.DIRS[d].arrow} 向${C.DIRS[d].label}滑行`);$('apply-hint').hidden=false;}else{$('solution-summary').textContent=`目前盤面有一條 ${result.moves.length} 步的可行路線。每一項都是一次完整滑行。`;$('solution-list').replaceChildren(...result.moves.map(([r,d])=>{const li=document.createElement('li');li.style.color=colors[r];li.textContent=`${names[r]} ${C.DIRS[d].arrow} ${C.DIRS[d].label}`;return li;}));$('solution-dialog').showModal();status('解法已從目前盤面計算完成');}}else if(result.status==='impossible')status('目前盤面找不到到達目標的路線，請悔棋或重來');else if(result.status==='limit')status('搜尋量較大，尚未找到路線；可以悔棋或重來再試');else status('搜尋暫時無法完成，請再試一次');};
 const fallback=()=>setTimeout(()=>{if(request!==token)return;try{accept(C.search(game.b,start));}catch{accept({status:'error'});}},30);
 try{worker=new Worker('ice-slide/worker.js');worker.onmessage=e=>accept(e.data);worker.onerror=()=>{if(worker){worker.terminate();worker=null;}fallback();};worker.postMessage({token:request,level:game.level,state:start});}catch{fallback();}
}
function playback(){if(!solutionPlan||solutionRevision!==game.revision){$('solution-dialog').close();status('盤面已改變，請重新查看解法');return;}const plan=solutionPlan.map(a=>a.slice());$('solution-dialog').close();playing=true;game.assisted=true;$('solution').textContent='停止示範';let at=0;const tick=()=>{if(!playing)return;if(at>=plan.length||game.won){stopPlayback();return;}const [r,d]=plan[at++];if(!move(r,d,{demo:true})){stopPlayback();status('示範已停止；盤面與路線不一致，請重新搜尋');return;}if(playing)playTimer=setTimeout(tick,650);};playTimer=setTimeout(tick,250);}
function showLevels(){const grid=$('level-grid');grid.replaceChildren(...levels.map((l,i)=>{const b=document.createElement('button');b.className=[saved.records[l.id]?.cleared?'cleared':'',i===current?'current':''].join(' ');b.innerHTML=`${String(l.id).padStart(2,'0')}<small>階段 ${l.difficulty}</small>`;b.setAttribute('aria-label',`第 ${l.id} 關，${l.name}${saved.records[l.id]?.cleared?'，已完成':''}`);b.onclick=()=>{load(i);$('level-dialog').close();canvas.focus({preventScroll:true});};return b;}));$('level-dialog').showModal();}
function rounded(x,y,w,h,r,fill,stroke){ctx.beginPath();ctx.roundRect(x,y,w,h,r);if(fill){ctx.fillStyle=fill;ctx.fill();}if(stroke){ctx.strokeStyle=stroke;ctx.stroke();}}
function draw(){if(!ctx||!game)return;const rect=canvas.getBoundingClientRect();if(!rect.width)return;const ratio=Math.min(window.devicePixelRatio||1,2),px=Math.round(rect.width*ratio);if(canvas.width!==px||canvas.height!==px){canvas.width=px;canvas.height=px;}ctx.setTransform(ratio,0,0,ratio,0,0);const s=rect.width,n=game.level.size,c=s/n;ctx.clearRect(0,0,s,s);ctx.fillStyle='#d8f2f5';ctx.fillRect(0,0,s,s);
 for(let y=0;y<n;y++)for(let x=0;x<n;x++){const p=y*n+x,X=x*c,Y=y*c;ctx.fillStyle=(x+y)%2?'#d0edf1':'#dff4f5';ctx.fillRect(X,Y,c,c);ctx.strokeStyle='#afd5df';ctx.lineWidth=.65;ctx.strokeRect(X,Y,c,c);if(game.b.walls.has(p)){rounded(X+2,Y+3,c-4,c-5,c*.13,'#406a86','#355875');ctx.beginPath();ctx.moveTo(X+5,Y+c*.3);ctx.lineTo(X+c*.32,Y+5);ctx.lineTo(X+c*.79,Y+5);ctx.lineTo(X+c-5,Y+c*.25);ctx.lineTo(X+c*.67,Y+c*.38);ctx.closePath();ctx.fillStyle='#82b5c8';ctx.fill();ctx.beginPath();ctx.moveTo(X+c*.17,Y+c*.55);ctx.lineTo(X+c*.45,Y+c*.44);ctx.lineTo(X+c*.75,Y+c*.67);ctx.lineTo(X+c*.68,Y+c*.9);ctx.strokeStyle='#7ca2b6';ctx.lineWidth=1.2;ctx.stroke();}else if((x*7+y*11)%5===0){ctx.strokeStyle='#f6ffffb0';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(X+c*.14,Y+c*.75);ctx.lineTo(X+c*.4,Y+c*.48);ctx.lineTo(X+c*.56,Y+c*.46);ctx.stroke();}}
 const goal=game.level.goal,gx=(goal%n+.5)*c,gy=(Math.floor(goal/n)+.5)*c,gcol=colors[game.level.target];ctx.save();ctx.strokeStyle=gcol;ctx.lineWidth=Math.max(2,c*.045);ctx.setLineDash([c*.09,c*.055]);ctx.beginPath();ctx.arc(gx,gy,c*.36,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);ctx.globalAlpha=.15;ctx.fillStyle=gcol;ctx.beginPath();ctx.arc(gx,gy,c*.29,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;ctx.font=`900 ${c*.39}px system-ui`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillStyle='#305265';ctx.fillText('◎',gx,gy+1);ctx.restore();
 game.positions.forEach((p,i)=>{const x=(p%n+.5)*c,y=(Math.floor(p/n)+.5)*c,r=c*.28;if(i===selected){ctx.strokeStyle='#143d52';ctx.lineWidth=c*.045;ctx.beginPath();ctx.arc(x,y,r+c*.08,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#183f53';ctx.beginPath();ctx.moveTo(x,y-r-c*.16);ctx.lineTo(x-c*.07,y-r-c*.25);ctx.lineTo(x+c*.07,y-r-c*.25);ctx.closePath();ctx.fill();}ctx.save();ctx.shadowColor='#174c6355';ctx.shadowBlur=c*.09;ctx.shadowOffsetY=c*.05;ctx.fillStyle=colors[i];ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();ctx.restore();ctx.strokeStyle='#ffffffd0';ctx.lineWidth=c*.035;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#20334f';ctx.font=`850 ${c*.3}px system-ui`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(letters[i],x,y+1);ctx.strokeStyle='#ffffff8f';ctx.lineWidth=c*.035;ctx.beginPath();ctx.arc(x,y,r*.74,Math.PI*1.08,Math.PI*1.67);ctx.stroke();});
}
function resize(){const area=$('board-space').getBoundingClientRect();boardPixels=Math.max(180,Math.floor(Math.min(area.width,area.height,650)));$('board-space').style.setProperty('--board-size',`${boardPixels}px`);requestAnimationFrame(draw);}
document.querySelectorAll('[data-robot]').forEach(b=>b.onclick=()=>{stopPlayback();chooseRobot(+b.dataset.robot);});document.querySelectorAll('[data-dir]').forEach(b=>b.onclick=()=>move(selected,+b.dataset.dir));$('undo').onclick=undo;$('restart').onclick=restart;$('hint').onclick=()=>requestSolution('hint');$('solution').onclick=()=>requestSolution('full');$('apply-hint').onclick=()=>{if(hintPlan){const [r,d]=hintPlan;move(r,d);}};$('play-solution').onclick=playback;$('levels-open').onclick=()=>{stopPlayback();invalidate();showLevels();};$('help-open').onclick=()=>{stopPlayback();invalidate();$('help-dialog').showModal();};$('next-level').onclick=()=>{if(current===levels.length-1)showLevels();else load(current+1);};$('stay-level').onclick=()=>$('win-banner').hidden=true;
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());document.querySelectorAll('dialog').forEach(dialog=>dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}}));
document.addEventListener('keydown',e=>{if(document.querySelector('dialog[open]')||e.ctrlKey||e.metaKey||e.altKey)return;const k=e.key.toLowerCase(),map={arrowup:0,w:0,arrowright:1,d:1,arrowdown:2,s:2,arrowleft:3,a:3};if(k in map){e.preventDefault();if(!e.repeat)move(selected,map[k]);}else if(['1','2','3'].includes(k)){e.preventDefault();stopPlayback();chooseRobot(+k-1);}else if(k==='z'){e.preventDefault();undo();}else if(k==='r'){e.preventDefault();restart();}else if(k==='h'){e.preventDefault();if(!busy)requestSolution('hint');}});
let pointer=null;canvas.addEventListener('pointerdown',e=>{if(e.button!==0)return;stopPlayback();const rect=canvas.getBoundingClientRect(),n=game.level.size,p=Math.floor((e.clientY-rect.top)/rect.height*n)*n+Math.floor((e.clientX-rect.left)/rect.width*n),robot=game.positions.indexOf(p);if(robot>=0)chooseRobot(robot);pointer={id:e.pointerId,x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId);canvas.focus({preventScroll:true});});canvas.addEventListener('pointerup',e=>{if(!pointer||pointer.id!==e.pointerId)return;const dx=e.clientX-pointer.x,dy=e.clientY-pointer.y;pointer=null;if(Math.max(Math.abs(dx),Math.abs(dy))>=18)move(selected,Math.abs(dx)>Math.abs(dy)?dx>0?1:3:dy>0?2:0);});canvas.addEventListener('pointercancel',()=>{pointer=null;});window.addEventListener('blur',()=>stopPlayback());document.addEventListener('visibilitychange',()=>{if(document.hidden)stopPlayback();});window.addEventListener('resize',resize);if(typeof ResizeObserver!=='undefined')new ResizeObserver(resize).observe($('board-space'));
load(current);resize();
})();
