(function(root){'use strict';const U=root.CompetitiveUtil||(typeof require==='function'?require('../competitive-common/core.js'):null),W=11,N=121,THRONE=60,CORNERS=[0,10,110,120],restricted=i=>i===60||CORNERS.includes(i);
function initial(){const b=Array(N).fill(0);for(const i of[3,4,5,6,7,16,33,44,55,66,77,56,43,54,65,76,87,64,104,113,114,115,116,117])b[i]=1;for(const i of[38,48,49,50,58,59,61,62,70,71,72,82])b[i]=-1;b[60]=-2;const s={board:b,turn:1,ply:0,keys:[]};s.keys=[U.key(s)];return s;}
function legal(s){const a=[];for(let from=0;from<N;from++)if(Math.sign(s.board[from])===s.turn)for(const to of U.rays(s.board,from,W,W,U.dirs4))if(!restricted(to)||s.board[from]===-2)a.push({from,to});return a;}
function hostile(b,i,v){if(i<0||i>=N)return false;if(Math.sign(b[i])===-Math.sign(v))return true;if(CORNERS.includes(i))return true;return i===THRONE&&(v>0||b[i]===0);}
function apply(s,m){const b=s.board.slice();b[m.to]=b[m.from];b[m.from]=0;const x=m.to%W,y=Math.floor(m.to/W),remove=[];for(const[dx,dy]of U.dirs4){const a=x+dx,c=y+dy,u=x+2*dx,v=y+2*dy;if(!U.inside(a,c,W)||!U.inside(u,v,W))continue;const j=c*W+a,k=v*W+u;if(b[j]&&Math.sign(b[j])===-s.turn&&b[j]!==-2&&hostile(b,k,b[j]))remove.push(j);}for(const j of remove)b[j]=0;const king=b.indexOf(-2);if(king>=0&&s.turn===1){const neighbors=U.neighbors(king,W);if(neighbors.length===4&&neighbors.every(j=>b[j]===1||j===THRONE&&b[j]===0))b[king]=0;}return U.next(s,b);}
function encircled(s){const q=[],seen=new Set();for(let i=0;i<N;i++)if((i%W===0||i%W===W-1||i<W||i>=N-W)&&s.board[i]!==1){seen.add(i);q.push(i);}for(let k=0;k<q.length;k++){if(s.board[q[k]]<0)return false;for(const j of U.neighbors(q[k],W))if(s.board[j]!==1&&!seen.has(j)){seen.add(j);q.push(j);}}return true;}
function outcome(s){const king=s.board.indexOf(-2);if(king<0)return{winner:1,reason:'國王被四面合圍擒獲'};if(CORNERS.includes(king))return{winner:-1,reason:'國王抵達角落，成功逃脫'};if(encircled(s))return{winner:1,reason:'國王與所有守軍被完整包圍'};if(!legal(s).length)return{winner:-s.turn,reason:'無合法著法'};if((s.keys||[]).filter(k=>k===U.key(s)).length>=3)return{winner:0,reason:'三次同局面和局（Fetlar 重複和局的操作約定）'};return null;}
function evaluate(s,p){const k=s.board.indexOf(-2);if(k<0)return p*10000;const x=k%W,y=Math.floor(k/W),dist=Math.min(x+y,10-x+y,x+10-y,20-x-y),attack=s.board.filter(x=>x===1).length,def=s.board.filter(x=>x===-1).length;let v=attack*8-def*16+dist*3;for(const j of U.neighbors(k,W))if(s.board[j]===1)v+=7;return p*v;}
const e=U.attach('hnefatafl',{width:W,height:W,initial,legal,apply,outcome,evaluate,encircled,hostile,restricted,THRONE,CORNERS,labels:{'1':'●','-1':'○','-2':'♔'},names:{'1':'攻方','-1':'守方'}});if(typeof module!=='undefined')module.exports=e;
})(typeof globalThis!=='undefined'?globalThis:this);
